corda/corda

- README.md
Bullets items that aren't sentences don't need periods. Missing hyphens.
> Updates for grammar

- experimental/sandbox/src/test/java/net/corda/sandbox/TestUtils.java
On windows the Sandbox unit tests are failing at test class cleanup time due to a file locking issue. This change closes the temporary FileSystem objects.
> Fix file cleanup of sandbox unit tests on Windows machines.

- core/src/main/kotlin/net/corda/core/contracts/TransactionTypes.kt
> Minor transaction verification logic refactoring

- node/src/main/kotlin/net/corda/node/services/statemachine/FlowStateMachineImpl.kt
Move Future completion outside database transaction so that the effects of the flow will be externally visible at Future completion.
This is very similar to the Observable problem previously resolved, and is causing `FxTransactionBuildTutorialTest` to fail intermittently.
> Move Flow returned Future complete outside database transaction

- node/src/integration-test/kotlin/net/corda/services/messaging/ArtemisMessagingServerTest.kt
- node/src/main/kotlin/net/corda/node/services/messaging/ArtemisMessagingServer.kt
- node/src/test/kotlin/net/corda/node/services/messaging/ArtemisMessagingServerTest.kt
*Create missing artemis bridge when node is added to the network map
*Added integration test for this issue
> This PR fixes the node startup issue - https://github.com/corda/corda/issues/37

- node/src/main/kotlin/net/corda/node/services/messaging/RPCStructures.kt
This fixes the issue seen by following the README.md in trader-demo
> rpc-kryo: Kryo register hidden jar url inputstream class

- docs/source/tutorial-test-dsl.rst
Again, this time with Java examples and double spend.
> Writing contract tests docs

- client/src/main/kotlin/net/corda/client/model/TransactionDataModel.kt
- experimental/src/main/kotlin/net/corda/contracts/universal/Literal.kt
- experimental/src/test/kotlin/net/corda/contracts/universal/IRS.kt
- experimental/src/test/kotlin/net/corda/contracts/universal/RollOutTests.kt
Also update some universal DSL code to use 'may' as an infix function.
> Minor: fix some compiler warnings in client and experimental

- samples/irs-demo/src/integration-test/kotlin/net/corda/irs/IRSDemoTest.kt
Will follow up with a proper fix, this is just to unblock CI.
> Update IRS demo test date to a future date

- gradle-plugins/cordformation/build.gradle
Also added a TODO to remove duplication of this version number as the original change intended.
> Fixed a bug with building gradle plugins due to an invalid version number used.

- docs/source/contract-catalogue.rst
- samples/bank-of-corda-demo/build.gradle
RPC Client now runs from CLI (node config was missing an RPC permission set).
> Fixed gradle runnode config for Bank of Corda (RPC Client was failing).

- node/src/integration-test/kotlin/net/corda/node/services/RaftNotaryServiceTests.kt
Need to create distinct transactions to test double-spend prevention
> Update RaftNotaryServiceTest to support idempotent notary behaviour

- core/src/main/kotlin/net/corda/core/Utils.kt
- gradle.properties
- node/src/main/kotlin/net/corda/node/services/messaging/ArtemisMessagingComponent.kt
- node/src/main/kotlin/net/corda/node/services/messaging/ArtemisMessagingServer.kt
- node/src/main/kotlin/net/corda/node/services/messaging/CordaRPCClient.kt
Note that RPC SSL optionality doesn't work yet because we'll need to introduce a dedicated RPC port (which is a good idea anyway).
> Misc small tweaks

- docs/source/running-the-demos.rst
- samples/irs-demo/src/main/kotlin/net/corda/irs/plugin/IRSPlugin.kt
Add Kryo registration of FixedRatePaymentEvent and FloatingRatePaymentEvent.
Docs - reflect future date change and minor fixes.
> IRS demo fixes

- docs/generate-docsite.sh
I keep having to do this manually for doc refreshes.
> The generate docsite script now works on both msys/cygwin systems and Unix systems

- docs/source/release-notes.rst
Please can everyone marked as a reviewer (that is available) check the release notes and comment on whether anything is missing and of course suggest improvements.
> Release notes for M7

- docs/source/index.rst
Reviewed and approved by Richard G Brown.
> Updates the docs landing page to give clear direction to new users.

- samples/bank-of-corda-demo/src/main/kotlin/net/corda/bank/BankOfCordaDriver.kt
Issuer node configuration fix.
All Issuer nodes need to declare the currency they issue.
Please apply to M7 release.
> Fixed incorrect configuration of Issuer node.

- samples/bank-of-corda-demo/build.gradle
- samples/bank-of-corda-demo/src/main/kotlin/net/corda/bank/BankOfCordaDriver.kt
Fixed incorrect configuration of Bank of Corda gradle node config (preventing Explorer login and issue).
> Colljos m7 minor config fix boc

- gradle-plugins/cordformation/src/main/resources/net/corda/plugins/runnodes.bat
- publish.properties
Fixes issue #128. 
I just need one person with a Windows machine to review this one.
> runnodes.bat no longer recursives when creating nodes.

- core/src/main/kotlin/net/corda/core/flows/FlowLogic.kt
- core/src/main/kotlin/net/corda/core/flows/FlowStateMachine.kt
- finance/src/main/kotlin/net/corda/flows/CashFlow.kt
- finance/src/test/kotlin/net/corda/flows/IssuerFlowTest.kt
- node/src/main/kotlin/net/corda/node/services/statemachine/FlowIORequest.kt
- node/src/main/kotlin/net/corda/node/services/statemachine/FlowStateMachineImpl.kt
- node/src/main/kotlin/net/corda/node/services/statemachine/SessionMessage.kt
- node/src/main/kotlin/net/corda/node/services/statemachine/StateMachineManager.kt
- node/src/test/kotlin/net/corda/node/messaging/TwoPartyTradeProtocolTests.kt
- node/src/test/kotlin/net/corda/node/services/statemachine/StateMachineManagerTests.kt
- samples/irs-demo/src/main/kotlin/net/corda/simulation/IRSSimulation.kt
- samples/irs-demo/src/main/kotlin/net/corda/simulation/TradeSimulation.kt
- samples/network-visualiser/src/main/kotlin/net/corda/netmap/NetworkMapVisualiser.kt
Cleaned up some of the flow code which I noticed while looking at error handling.
> Some clean up of the flow code

- node/src/main/kotlin/net/corda/node/services/messaging/NodeMessagingClient.kt
Perform Artemis message sending in a separate thread pool to avoid memory leaks.
Netty keeps a cache for buffer allocations in a thread local variable, and some additional references  for freeing it (in `ThreadDeathWatcher`). Quasar seems to wipe the thread locals, which causes Netty to keep allocating a new cache for the same worker thread (and it's no longer able to free up the previous one), which causes a severe memory leak.
Before:
After:
> Node memory leak fix

- core/src/main/kotlin/net/corda/core/Utils.kt
- core/src/main/kotlin/net/corda/core/messaging/CordaRPCOps.kt
- core/src/main/kotlin/net/corda/core/messaging/Messaging.kt
- core/src/main/kotlin/net/corda/core/node/services/Services.kt
- core/src/test/kotlin/net/corda/core/UtilsTest.kt
- docs/source/example-code/src/test/kotlin/net/corda/docs/FxTransactionBuildTutorialTest.kt
- docs/source/example-code/src/test/kotlin/net/corda/docs/WorkflowTransactionBuildTutorialTest.kt
- node/src/main/kotlin/net/corda/node/services/events/NodeSchedulerService.kt
- node/src/test/kotlin/net/corda/node/services/persistence/DBTransactionStorageTests.kt
- test-utils/src/main/kotlin/net/corda/testing/CoreTestUtils.kt
This should also be useful in my flow exception propagation work.
> Introducing Observable.toFuture() extension method

- README.md
Condition of receiving free open-source licenses from YourKit.
> Add yourkit acknowledgment

- node/src/main/resources/reference.conf
> Set h2 write delay to 100ms to improve performance

- tools/explorer/src/main/kotlin/net/corda/explorer/model/SettingsModel.kt
- tools/explorer/src/main/kotlin/net/corda/explorer/views/LoginView.kt
- tools/explorer/src/main/resources/net/corda/explorer/css/corda.css
- tools/explorer/src/main/resources/net/corda/explorer/views/LoginView.fxml
User can now specify certificates path and keystore/truststore password in the certificate setting screen.
> Added Certificate setting to the login screen

- core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
harmonize line 167 with earlier references on line 146 for example
> unify references to notary in output

- node/src/main/kotlin/net/corda/node/driver/Driver.kt
- node/src/main/kotlin/net/corda/node/services/messaging/NodeMessagingClient.kt
This enables the user to add a system property option to add delays to the AMQ message being sent in order to demonstrate flows in slowtime. It is (obviously) not intended for production, hence the use of system properties.
> Adding optional delay to AMQ message sending via system properties

- node/src/main/kotlin/net/corda/node/services/statemachine/FlowStateMachineImpl.kt
- node/src/test/kotlin/net/corda/node/services/statemachine/StateMachineManagerTests.kt
> Flows shouldn't have to suspend if just doing a send

- client/src/main/kotlin/net/corda/client/model/NodeMonitorModel.kt
- node/src/main/kotlin/net/corda/node/services/messaging/CordaRPCClient.kt
- node/src/main/kotlin/net/corda/node/services/messaging/NodeMessagingClient.kt
CORDA-189 Suspend/wake cycle breaks RPC connection
> Added reconnect capability to RPC

- node/src/main/kotlin/net/corda/node/services/statemachine/FlowStateMachineImpl.kt
- node/src/main/kotlin/net/corda/node/services/statemachine/StateMachineManager.kt
- node/src/test/kotlin/net/corda/node/services/statemachine/StateMachineManagerTests.kt
My previous flow exception propagation commit missed the case of propagating a received `FlowException` further onto the initiating flow. This allows something like an acceptor flow to use the notary and have any `NotaryException` received from the notary propagate back to the instigator flow.
> Allow received FlowException to propagate further to initiating flow

- docs/source/release-notes.rst
Please add anything that's missing
> Release notes for M8

- samples/bank-of-corda-demo/src/main/kotlin/net/corda/bank/BankOfCordaDriver.kt
- samples/bank-of-corda-demo/src/main/kotlin/net/corda/bank/api/BankOfCordaClientApi.kt
Minor tweak to users as a precursor to #196
> Split users for bank and big corp

- docs/source/getting-set-up-fault-finding.rst
- docs/source/getting-set-up.rst
and replaced a specific milestone reference with a generic one
> Updated docs to refer to the latest milestone

- build.gradle
- node-schemas/build.gradle
Applied plugin to enable publishing of new node-schemas module.
> Publish new corda module: node-schemas

- docs/source/example-code/src/integration-test/kotlin/net/corda/docs/IntegrationTestingTutorial.kt
- finance/src/main/kotlin/net/corda/flows/CashIssueFlow.kt
- finance/src/main/kotlin/net/corda/flows/CashPaymentFlow.kt
- node/src/main/kotlin/net/corda/node/services/statemachine/FlowStateMachineImpl.kt
Add missing @Suspendable to CashIssueFlow, as well as adding sanity check to result of starting CashIssueFlow from IntegrationTestingTutorial.
> Add missing @Suspendable

- core/src/main/kotlin/net/corda/core/transactions/MerkleTransaction.kt
- core/src/main/kotlin/net/corda/core/transactions/SignedTransaction.kt
- core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
- core/src/main/kotlin/net/corda/core/transactions/WireTransaction.kt
- core/src/main/kotlin/net/corda/flows/ContractUpgradeFlow.kt
- core/src/test/kotlin/net/corda/core/contracts/TransactionTests.kt
- core/src/test/kotlin/net/corda/core/flows/ContractUpgradeFlowTest.kt
- finance/src/main/kotlin/net/corda/contracts/testing/Generators.kt
- node/src/test/kotlin/net/corda/node/services/database/RequeryConfigurationTest.kt
- node/src/test/kotlin/net/corda/node/services/persistence/DBTransactionStorageTests.kt
- test-utils/src/main/kotlin/net/corda/testing/TestDSL.kt
Each commit can be reviewed separately.
> Various small fixes

- client/src/integration-test/kotlin/net/corda/client/CordaRPCClientTest.kt
- core/src/main/kotlin/net/corda/core/messaging/CordaRPCOps.kt
- node/src/main/kotlin/net/corda/node/internal/CordaRPCOpsImpl.kt
- node/src/main/kotlin/net/corda/node/services/messaging/RPCStructures.kt
Fetches `Map<Currency, Amount<Currency>>` from node via RPC.
> Implement RPCOp getCashBalances().

- client/src/integration-test/kotlin/net/corda/client/CordaRPCClientTest.kt
- client/src/integration-test/kotlin/net/corda/client/NodeMonitorModelTest.kt
- client/src/main/kotlin/net/corda/client/model/NodeMonitorModel.kt
- node/src/integration-test/kotlin/net/corda/services/messaging/MQSecurityAsNodeTest.kt
- node/src/integration-test/kotlin/net/corda/services/messaging/MQSecurityAsRPCTest.kt
- node/src/integration-test/kotlin/net/corda/services/messaging/MQSecurityTest.kt
- node/src/main/kotlin/net/corda/node/driver/Driver.kt
- node/src/main/kotlin/net/corda/node/internal/Node.kt
- node/src/main/kotlin/net/corda/node/services/config/ConfigUtilities.kt
- node/src/main/kotlin/net/corda/node/services/config/NodeConfiguration.kt
- node/src/main/kotlin/net/corda/node/services/messaging/ArtemisMessagingComponent.kt
- node/src/main/kotlin/net/corda/node/services/messaging/ArtemisMessagingServer.kt
- node/src/main/kotlin/net/corda/node/services/messaging/CordaRPCClient.kt
- node/src/test/kotlin/net/corda/node/services/messaging/ArtemisMessagingTests.kt
- samples/bank-of-corda-demo/src/main/kotlin/net/corda/bank/api/BankOfCordaClientApi.kt
- samples/irs-demo/src/integration-test/kotlin/net/corda/irs/IRSDemoTest.kt
- samples/trader-demo/src/integration-test/kotlin/net/corda/traderdemo/TraderDemoTest.kt
- test-utils/src/main/kotlin/net/corda/testing/CoreTestUtils.kt
- test-utils/src/main/kotlin/net/corda/testing/messaging/SimpleMQClient.kt
- test-utils/src/main/kotlin/net/corda/testing/node/NodeBasedTest.kt
- test-utils/src/main/kotlin/net/corda/testing/node/SimpleNode.kt
- tools/explorer/src/main/kotlin/net/corda/explorer/Main.kt
- tools/explorer/src/main/kotlin/net/corda/explorer/model/SettingsModel.kt
- tools/explorer/src/main/kotlin/net/corda/explorer/views/LoginView.kt
- tools/explorer/src/main/resources/net/corda/explorer/views/LoginView.fxml
* New non-ssl acceptor in artemis server for RPC connection.
* Removed certificate settings in node explore
> Non-ssl artemis acceptor for RPC connection.

- gradle-plugins/cordformation/src/main/resources/net/corda/plugins/runnodes
No need to republish for this change. It'll be propagated into the next gradle plugins update.
> Modified title of the webserver on systems using xterm to run nodes.

- client/src/main/kotlin/net/corda/client/mock/Generator.kt
- tools/loadtest/src/main/kotlin/net/corda/loadtest/ConnectionManager.kt
- tools/loadtest/src/main/kotlin/net/corda/loadtest/LoadTest.kt
- tools/loadtest/src/main/kotlin/net/corda/loadtest/LoadTestConfiguration.kt
- tools/loadtest/src/main/kotlin/net/corda/loadtest/Main.kt
- tools/loadtest/src/main/kotlin/net/corda/loadtest/tests/CrossCashTest.kt
- tools/loadtest/src/main/resources/loadtest-reference.conf
Various loadtest fixes, depends on #290
> Aslemmer loadtest fixes

- node/src/test/kotlin/net/corda/node/services/DistributedImmutableBFTMapTests.kt
I've removed this test in my further BFT work
> Ignore BFT map test for now

- samples/attachment-demo/gradle.properties
- samples/bank-of-corda-demo/gradle.properties
- samples/irs-demo/gradle.properties
- samples/raft-notary-demo/gradle.properties
- samples/trader-demo/gradle.properties
These files are remnants of when the samples were each a separate gradle project before the remerge.
> Removed redundant gradle.properties in samples projects.

- client/src/integration-test/kotlin/net/corda/client/CordaRPCClientTest.kt
- client/src/integration-test/kotlin/net/corda/client/NodeMonitorModelTest.kt
- client/src/main/kotlin/net/corda/client/model/NodeMonitorModel.kt
- node/src/integration-test/kotlin/net/corda/services/messaging/MQSecurityAsNodeTest.kt
- node/src/integration-test/kotlin/net/corda/services/messaging/MQSecurityAsRPCTest.kt
- node/src/integration-test/kotlin/net/corda/services/messaging/MQSecurityTest.kt
- node/src/main/kotlin/net/corda/node/driver/Driver.kt
- node/src/main/kotlin/net/corda/node/internal/Node.kt
- node/src/main/kotlin/net/corda/node/services/config/ConfigUtilities.kt
- node/src/main/kotlin/net/corda/node/services/config/NodeConfiguration.kt
- node/src/main/kotlin/net/corda/node/services/messaging/ArtemisMessagingComponent.kt
- node/src/main/kotlin/net/corda/node/services/messaging/ArtemisMessagingServer.kt
- node/src/main/kotlin/net/corda/node/services/messaging/CordaRPCClient.kt
- node/src/test/kotlin/net/corda/node/services/messaging/ArtemisMessagingTests.kt
- samples/bank-of-corda-demo/src/main/kotlin/net/corda/bank/api/BankOfCordaClientApi.kt
- samples/irs-demo/src/integration-test/kotlin/net/corda/irs/IRSDemoTest.kt
- samples/trader-demo/src/integration-test/kotlin/net/corda/traderdemo/TraderDemoTest.kt
- test-utils/src/main/kotlin/net/corda/testing/CoreTestUtils.kt
- test-utils/src/main/kotlin/net/corda/testing/messaging/SimpleMQClient.kt
- test-utils/src/main/kotlin/net/corda/testing/node/NodeBasedTest.kt
- test-utils/src/main/kotlin/net/corda/testing/node/SimpleNode.kt
- tools/explorer/src/main/kotlin/net/corda/explorer/Main.kt
- tools/explorer/src/main/kotlin/net/corda/explorer/model/SettingsModel.kt
- tools/explorer/src/main/kotlin/net/corda/explorer/views/LoginView.kt
- tools/explorer/src/main/resources/net/corda/explorer/views/LoginView.fxml
This reverts commit f0d82e491887f55e96f0f292974356b5d765c7b6, as it breaks the samples (notably Bank of Corda, likely others), pending further testing and review.
> Revert "Non-ssl artemis acceptor for RPC connection. (#271)"

- docs/source/changelog.rst
- docs/source/index.rst
- docs/source/release-notes.rst
- docs/source/release-process.rst
Draft release notes based on the PRs raised for M9 - please raise corrections as PRs against this branch.
I'd particularly like more text on the BFT notary and vault persistence from those who worked on those, if you could?
> M9 release notes

- docs/source/running-the-demos.rst
- samples/simm-valuation-demo/build.gradle
Change port numbers in SIMM demo so both through CLI and IntelliJ webserver listens on the same port.
Related change in documentation.
> Simm ports change

- core/src/main/kotlin/net/corda/core/Utils.kt
- core/src/main/kotlin/net/corda/core/node/services/AttachmentStorage.kt
- core/src/main/kotlin/net/corda/core/schemas/requery/converters/BlobConverter.kt
- core/src/main/kotlin/net/corda/core/schemas/requery/converters/SecureHashConverter.kt
- core/src/test/kotlin/net/corda/core/flows/ResolveTransactionsFlowTest.kt
- node-schemas/src/main/kotlin/net/corda/node/services/persistence/schemas/AttachmentsSchema.kt
- node/build.gradle
- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/main/kotlin/net/corda/node/internal/CordaRPCOpsImpl.kt
- node/src/main/kotlin/net/corda/node/services/database/KotlinConfigurationTransactionWrapper.kt
- node/src/main/kotlin/net/corda/node/services/persistence/NodeAttachmentService.kt
- node/src/test/kotlin/net/corda/node/messaging/AttachmentTests.kt
- node/src/test/kotlin/net/corda/node/messaging/TwoPartyTradeFlowTests.kt
- node/src/test/kotlin/net/corda/node/services/NodeAttachmentStorageTest.kt
- samples/trader-demo/src/main/kotlin/net/corda/traderdemo/flow/BuyerFlow.kt
- test-utils/src/main/kotlin/net/corda/testing/node/MockServices.kt
Recreated a pull request #246 after strange issues with rebasing.
> Simple Attachment Storage implementation using Requery/H2 database

- docs/source/corda-configuration-file.rst
- docs/source/tutorial-clientrpc-api.rst
- node/src/main/kotlin/net/corda/node/services/messaging/RPCStructures.kt
- node/src/test/kotlin/net/corda/node/messaging/AbstractClientRPC.kt
- node/src/test/kotlin/net/corda/node/messaging/ClientRPCInfrastructureTests.kt
- node/src/test/kotlin/net/corda/node/messaging/RPCPermissionsTest.kt
An RPC user declared with this permission in `node.conf` is allowed to use any flow.
> CORDA-265: Implement "ALL" permission for RPC users.

- client/src/main/kotlin/net/corda/client/mock/Generator.kt
> client: Fix wrong pickN generator

- docs/source/running-the-demos.rst
- samples/irs-demo/build.gradle
- samples/irs-demo/src/main/kotlin/net/corda/irs/IRSDemo.kt
- samples/simm-valuation-demo/build.gradle
Revert of previous changes. Our port allocation strategy **really** needs cleaning up.
> Correct ports in demos broken after RPC port revert.

- node/webserver/src/main/kotlin/net/corda/webserver/utilities/JsonSupport.kt
This doesn't fix the deserialization problem with IRS, but fixes what could be a potential problem elsewhere.
> Remove need for full party to deserialize anonymous parties

- tools/explorer/src/main/kotlin/net/corda/explorer/views/cordapps/cash/NewTransaction.kt
Transaction ID not rendering correctly due to the length of the ID
> Fixed bug [CORDA-282] - TX id is not rendering properly in new transaction screen

- build.gradle
- core/src/main/kotlin/net/corda/core/Utils.kt
- core/src/main/kotlin/net/corda/core/node/NodeInfo.kt
- core/src/main/kotlin/net/corda/core/node/Version.kt
- core/src/test/kotlin/net/corda/core/node/VersionTest.kt
- node/build.gradle
- node/capsule/build.gradle
- node/src/integration-test/kotlin/net/corda/services/messaging/P2PSecurityTest.kt
- node/src/main/kotlin/net/corda/node/ArgsParser.kt
- node/src/main/kotlin/net/corda/node/Corda.kt
- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/main/kotlin/net/corda/node/internal/Node.kt
- node/src/main/kotlin/net/corda/node/services/config/NodeConfiguration.kt
- node/src/main/kotlin/net/corda/node/services/messaging/NodeMessagingClient.kt
- node/src/main/kotlin/net/corda/node/services/statemachine/FlowStateMachineImpl.kt
- node/src/test/kotlin/net/corda/node/ArgsParserTest.kt
- node/src/test/kotlin/net/corda/node/services/messaging/ArtemisMessagingTests.kt
- test-utils/src/main/kotlin/net/corda/testing/CoreTestUtils.kt
- test-utils/src/main/kotlin/net/corda/testing/node/MockNetworkMapCache.kt
- test-utils/src/main/kotlin/net/corda/testing/node/MockNode.kt
- test-utils/src/main/kotlin/net/corda/testing/node/MockServices.kt
- test-utils/src/main/kotlin/net/corda/testing/node/NodeBasedTest.kt
- test-utils/src/main/kotlin/net/corda/testing/node/SimpleNode.kt
* Added --version cmd line arg to print the version and git commit id
* Version and commit it are printed in the banner
* `NodeInfo` has the node version
* Each MQ message sent has the the version in its header
> Added bits of versioning info to the node

- node/src/main/kotlin/net/corda/node/internal/Node.kt
This should hopefully resolve a shutdown hang due to the misnamed "WebServer" thread not being a daemon thread.
> Minor: don't use a separate thread to start Metrics-to-JMX export.

- node/webserver/webcapsule/build.gradle
... which was missing due to an incorrect path.
> Webserver capsule now contains the correct caplet

- build.gradle
- core/build.gradle
Intended for aiding developers with limited access to maven repositories.
> Added a gradle task to build a zip of Corda dependencies

- config/dev/log4j2.xml
- config/test/log4j2.xml
- node/src/main/kotlin/net/corda/node/Corda.kt
- node/src/main/kotlin/net/corda/node/services/messaging/ArtemisMessagingServer.kt
- samples/simm-valuation-demo/src/main/resources/log4j2.xml
Fix for https://github.com/corda/corda/issues/305.
To resolve it, a new console appender and logger is added to log4j2.xml.
> Print to screen and log basic info

- core/src/main/kotlin/net/corda/core/serialization/DefaultKryoCustomizer.kt
- core/src/main/kotlin/net/corda/core/serialization/Kryo.kt
- core/src/test/kotlin/net/corda/core/serialization/KryoTests.kt
Custom Logger serialiser using only its name when serialising and deserialising using `LoggerFactory.getLogger(name)`
> Custom serialiser for Logger

- core/src/main/kotlin/net/corda/core/utilities/Emoji.kt
- core/src/main/kotlin/net/corda/core/utilities/ProgressTracker.kt
- node/src/main/kotlin/net/corda/node/utilities/ANSIProgressRenderer.kt
Catches up with a logging change in master.
> Some fixes to emoji/ANSI renderer

- gradle-plugins/cordformation/src/noderunner/kotlin/net/corda/plugins/NodeRunner.kt
- publish.properties
Reopen of #400 as the latest runnodes.jar changes conflicted a lot.
> Aslemmer fix runnodes add tmux

- tools/demobench/src/main/kotlin/net/corda/demobench/views/NodeTabView.kt
The first node that DemoBench creates needs to be a notary, so suggest a name of "Notary" for it.
> Suggest a default name of "Notary" for the first node.

- build.gradle
- node/src/main/kotlin/net/corda/node/driver/Driver.kt
Why: Cordapps broken on master due to the verifier not publishing correctly.
> Verifier is now correctly publishing

- build.gradle
- client/jackson/build.gradle
- client/jfx/build.gradle
- client/mock/build.gradle
- client/rpc/build.gradle
- core/build.gradle
- experimental/sandbox/build.gradle
- finance/build.gradle
- finance/isolated/build.gradle
- node-api/build.gradle
- node-schemas/build.gradle
- node/build.gradle
- node/capsule/build.gradle
- node/webserver/build.gradle
- node/webserver/webcapsule/build.gradle
- samples/attachment-demo/build.gradle
- samples/bank-of-corda-demo/build.gradle
- samples/irs-demo/build.gradle
- samples/network-visualiser/build.gradle
- samples/raft-notary-demo/build.gradle
- samples/simm-valuation-demo/build.gradle
- samples/trader-demo/build.gradle
- test-utils/build.gradle
- tools/demobench/build.gradle
- tools/explorer/build.gradle
- tools/loadtest/build.gradle
- verifier/build.gradle
In preparation for temporarily adding a snapshot repo for proton-j, consolidate the definition of repos to the top level.
Looks like demo bench has a superset, hopefully this still works.  Will check with @chrisr3 how to validate that.
> Consolidate maven repositories

- node/src/main/kotlin/net/corda/node/driver/Driver.kt
This fixes broken demos due to port shift.
> Use sshdPortAllocation for sshdAddress instead of portAllocation 

- node/src/main/kotlin/net/corda/node/driver/Driver.kt
Simple but effective and very useful!
> Display Corda node legal name in JVisualVM Console for MockNode testing.

- config/dev/log4j2.xml
- core/src/main/kotlin/net/corda/flows/NotaryFlow.kt
- node/src/main/kotlin/net/corda/node/services/messaging/ArtemisMessagingServer.kt
Provide useful information when Notary detects conflicting states.
> Reduce warning and info messages in node log files (Artemis)

- client/jfx/src/main/kotlin/net/corda/client/jfx/utils/AmountBindings.kt
- core/src/main/kotlin/net/corda/core/contracts/FinanceTypes.kt
- core/src/main/kotlin/net/corda/core/contracts/FungibleAsset.kt
- core/src/main/kotlin/net/corda/core/contracts/Structures.kt
- core/src/test/kotlin/net/corda/core/flows/ContractUpgradeFlowTest.kt
- core/src/test/kotlin/net/corda/core/testing/Generators.kt
- finance/src/main/kotlin/net/corda/contracts/asset/Cash.kt
- finance/src/main/kotlin/net/corda/contracts/asset/CommodityContract.kt
- finance/src/main/kotlin/net/corda/contracts/asset/Obligation.kt
- finance/src/main/kotlin/net/corda/contracts/clause/Net.kt
- tools/explorer/src/main/kotlin/net/corda/explorer/AmountDiff.kt
Split the cleanup sections of #453 into a separate PR so they can be merged independently.
> Clean up Amount type

- core/src/main/kotlin/net/corda/flows/NotaryFlow.kt
Fix for null message in NotaryException
> Fixed : Message value in NotaryException is always null

- tools/demobench/src/test/kotlin/net/corda/demobench/model/NodeConfigTest.kt
Test that DemoBench passes the H2 port number to Corda correctly.
> Test configuring DB port number.

- constants.properties
- docs/source/creating-a-cordapp.rst
- gradle-plugins/cordformation/src/main/groovy/net/corda/plugins/Node.groovy
Why: It's useful to have deterministic ports.
> Added H2 port to cordformation config

- constants.properties
- gradle-plugins/cordformation/src/noderunner/kotlin/net/corda/plugins/NodeRunner.kt
* bump gradle plugin version to 0.10.3 for MacOS's runnodes fixes 
* added arg passthrough for runnodes
> bump gradle plugin version to 0.10.3

- tools/demobench/build.gradle
- tools/demobench/src/test/kotlin/net/corda/demobench/model/NodeConfigTest.kt
Test that our node configuration can also be converted to `WebServerConfig`.
> Test webserver configuration too.

- client/mock/src/main/kotlin/net/corda/client/mock/EventGenerator.kt
- docs/source/node-explorer.rst
- tools/explorer/src/main/kotlin/net/corda/explorer/Main.kt
* changed event generator to reduce flow exception due to wrongly generated event
* some refactoring
> Reduce occurrence of flow exception in explorer demo

- core/src/main/kotlin/net/corda/core/contracts/FinanceTypes.kt
IRS demo is not working because there are problem converting enums with abstract method to json after upgrading to kaitlin 1.1.1
> [M10 Fixes] - fixes enum-json conversion problem in kotlin 1.1.1

- node/src/main/kotlin/net/corda/node/Corda.kt
- node/src/main/kotlin/net/corda/node/driver/Driver.kt
and added a log entry for the debug port.
Why: Because it should be there and I'd like to be able to check the logs for the debug port.
> Readded the debug port to the driver 

- constants.properties
- gradle-plugins/cordformation/src/noderunner/kotlin/net/corda/plugins/NodeRunner.kt
Why: This is an oft-requested feature.
> Runnodes now exposes default ports for nodes automatically

- webserver/src/main/kotlin/net/corda/webserver/internal/APIServerImpl.kt
- webserver/src/main/kotlin/net/corda/webserver/internal/AllExceptionMapper.kt
> Added an exception mapper that prints out errors emitted by the webserver

- README.md
Corda is maturing. The scary warning should be softened slightly.
> Update production readiness warning

- tools/demobench/build.gradle
- tools/demobench/src/main/kotlin/net/corda/demobench/DemoBench.kt
- tools/demobench/src/main/kotlin/net/corda/demobench/explorer/Explorer.kt
- tools/demobench/src/main/kotlin/net/corda/demobench/views/DemoBenchView.kt
- tools/demobench/src/main/kotlin/net/corda/demobench/views/NodeTabView.kt
- tools/demobench/src/main/kotlin/net/corda/demobench/web/WebServer.kt
Fix a few simple things after feedback from Adam Furgal.
> Tidy up a few rough edges for DemoBench.

- docs/source/changelog.rst
- docs/source/index.rst
- docs/source/release-notes.rst
> M10 release note

- docs/source/demobench.rst
Add download link and location of log file.
> Update DemoBench documentation.

- docs/source/key-concepts-core-types.rst
Doc changes to key-concepts-core-types
> Amiracam docs

- node/src/main/kotlin/net/corda/node/internal/Node.kt
- node/src/main/kotlin/net/corda/node/services/transactions/RaftUniquenessProvider.kt
Added shutdown of h2 and Raft copycat server on node shutdown. This caused leaks in NodeBasedTests.
I also moved the startup logic from the constructor of RaftUniquenessProvider into a dedicated start() method
> Shutdown copycat server and h2 database on Node shutdown

- node/src/main/kotlin/net/corda/node/utilities/AddressUtils.kt
Check if an IP address is reachable before using it as the broker address
> Minor: auto ip detection - check if address reachable

- build.gradle
- core/build.gradle
- core/src/main/kotlin/net/corda/core/serialization/DefaultKryoCustomizer.kt
- core/src/main/kotlin/net/corda/core/serialization/Kryo.kt
- core/src/main/kotlin/net/corda/core/utilities/Logging.kt
- node/build.gradle
- node/capsule/build.gradle
- node/src/integration-test/kotlin/net/corda/node/BootTests.kt
- node/src/integration-test/kotlin/net/corda/node/driver/DriverTests.kt
- node/src/integration-test/resources/META-INF/services/net.corda.core.node.CordaPluginRegistry
- node/src/main/kotlin/net/corda/node/Corda.kt
- node/src/main/kotlin/net/corda/node/driver/Driver.kt
- node/src/main/kotlin/net/corda/node/services/transactions/RaftUniquenessProvider.kt
- node/src/main/kotlin/net/corda/node/shell/InteractiveShell.kt
- samples/bank-of-corda-demo/src/integration-test/kotlin/net/corda/bank/BankOfCordaHttpAPITest.kt
- samples/irs-demo/src/integration-test/kotlin/net/corda/irs/IRSDemoTest.kt
- samples/simm-valuation-demo/src/integration-test/kotlin/net/corda/vega/SimmValuationTest.kt
- test-utils/src/main/kotlin/net/corda/testing/node/DriverBasedTest.kt
- tools/explorer/capsule/build.gradle
- webserver/src/integration-test/kotlin/net/corda/webserver/WebserverDriverTests.kt
- webserver/webcapsule/build.gradle
This PR implements https://r3-cev.atlassian.net/browse/CORDA-322
> Prohibit Java deserialisation in the Corda process

- core/build.gradle
- core/src/main/kotlin/net/corda/core/utilities/LegalNameValidator.kt
- core/src/test/kotlin/net/corda/core/utilities/LegalNameValidatorTest.kt
- docs/source/permissioning.rst
JIRA : https://r3-cev.atlassian.net/browse/CORDA-306
Usage of this validator will be in a separated PR
> legal name validator for doorman node registration

- tools/demobench/src/main/kotlin/net/corda/demobench/rpc/NodeRPC.kt
- tools/demobench/src/main/kotlin/net/corda/demobench/views/NodeTerminalView.kt
- tools/demobench/src/main/resources/net/corda/demobench/views/NodeTerminalView.fxml
Properly subscribe to the RPC Observables rather than polling the transactions and the vault.
> DemoBench now subscribes to updates for transaction and vault RPCs.

- core/src/main/kotlin/net/corda/core/messaging/CordaRPCOps.kt
- node/src/main/kotlin/net/corda/node/internal/CordaRPCOpsImpl.kt
- node/src/main/kotlin/net/corda/node/services/statemachine/FlowStateMachineImpl.kt
- node/src/main/kotlin/net/corda/node/services/statemachine/StateMachineManager.kt
- node/src/main/kotlin/net/corda/node/services/vault/VaultSoftLockManager.kt
- node/src/main/kotlin/net/corda/node/utilities/AddOrRemove.kt
- node/src/test/kotlin/net/corda/node/services/events/NodeSchedulerServiceTest.kt
- node/src/test/kotlin/net/corda/node/services/events/ScheduledFlowTests.kt
- samples/irs-demo/src/main/kotlin/net/corda/simulation/Simulation.kt
- test-utils/src/main/kotlin/net/corda/testing/CoreTestUtils.kt
There are two cases: normal end of flow or error. Needed for flow ui work.
> Add information on why state machine was removed from StateMachineManager

- docs/source/example-code/src/main/kotlin/net/corda/docs/ClientRpcTutorial.kt
- docs/source/tutorial-clientrpc-api.rst
- samples/irs-demo/src/main/kotlin/net/corda/irs/api/InterestRateSwapAPI.kt
- samples/irs-demo/src/main/kotlin/net/corda/irs/api/IrsDemoClientApi.kt
- samples/raft-notary-demo/src/main/kotlin/net/corda/notarydemo/NotaryDemo.kt
- samples/simm-valuation-demo/src/main/kotlin/net/corda/vega/api/PortfolioApi.kt
- samples/simm-valuation-demo/src/main/kotlin/net/corda/vega/portfolio/Portfolio.kt
- samples/trader-demo/src/main/kotlin/net/corda/traderdemo/TraderDemoClientApi.kt
- tools/loadtest/src/main/kotlin/net/corda/loadtest/LoadTest.kt
- tools/loadtest/src/main/kotlin/net/corda/loadtest/tests/CrossCashTest.kt
- tools/loadtest/src/main/kotlin/net/corda/loadtest/tests/SelfIssueTest.kt
- Mark unused Observables as notUsed()
- Remove use of `assert` and `assertEquals` in non-test code.
- Remove unused imports.
> Basic clean-up for demos, load-test and examples

- core/build.gradle
- core/src/main/kotlin/net/corda/core/Utils.kt
- core/src/main/kotlin/net/corda/core/contracts/Structures.kt
- core/src/main/kotlin/net/corda/core/serialization/SerializationToken.kt
- core/src/main/kotlin/net/corda/flows/FetchAttachmentsFlow.kt
- core/src/test/kotlin/net/corda/core/serialization/AttachmentSerializationTest.kt
- core/src/test/kotlin/net/corda/core/serialization/SerializationTokenTest.kt
- node/src/main/kotlin/net/corda/node/serialization/NodeClock.kt
- node/src/main/kotlin/net/corda/node/services/persistence/NodeAttachmentService.kt
- node/src/main/kotlin/net/corda/node/services/statemachine/StateMachineManager.kt
- node/src/main/kotlin/net/corda/node/utilities/TestClock.kt
- test-utils/src/main/kotlin/net/corda/testing/node/TestClock.kt
This PR implements https://r3-cev.atlassian.net/browse/CORDA-300
> In checkpoints, serialize hash of attachment instead of its data

- webserver/src/main/kotlin/net/corda/webserver/internal/NodeWebServer.kt
- webserver/src/main/kotlin/net/corda/webserver/servlets/CorDappInfoServlet.kt
Filtered out the default plugins.
> Filter out the default node plugins as per request from Chris.

- node/src/main/kotlin/net/corda/node/driver/Driver.kt
Rewrote node name to extract common name to use as the node path for samples, to work around characters being incorrectly treated as separators. This should fix running integration tests from IntelliJ.
> Extract common name from legal name to determine path in Driver

- tools/explorer/src/main/kotlin/net/corda/explorer/formatters/PartyNameFormatter.kt
- tools/explorer/src/main/kotlin/net/corda/explorer/views/MainView.kt
- tools/explorer/src/main/kotlin/net/corda/explorer/views/Network.kt
- tools/explorer/src/main/kotlin/net/corda/explorer/views/TransactionViewer.kt
- tools/explorer/src/main/kotlin/net/corda/explorer/views/cordapps/cash/CashViewer.kt
- tools/explorer/src/main/kotlin/net/corda/explorer/views/cordapps/cash/NewTransaction.kt
- tools/explorer/src/main/resources/net/corda/explorer/views/Network.fxml
For demo purpose we still have short common name everywhere. We can change that behaviour later by specifying different formatting.
> Explorer x500names

- docs/source/getting-set-up.rst
- docs/source/index.rst
Needs to be correct both in the branch _and_ in master!
> Fix current version.

- tools/demobench/build.gradle
- tools/demobench/src/main/kotlin/net/corda/demobench/model/NodeConfig.kt
- tools/demobench/src/main/kotlin/net/corda/demobench/model/NodeController.kt
- tools/demobench/src/main/kotlin/net/corda/demobench/views/NodeTabView.kt
- tools/demobench/src/main/kotlin/net/corda/demobench/views/NodeTerminalView.kt
- tools/demobench/src/test/kotlin/net/corda/demobench/model/NodeControllerTest.kt
Create X.500 names from the user's name choice, the nearest city and the country that city is in.
Only display the user's name choice on the tab.
> Create X.500 names for DemoBench nodes.

- docs/source/changelog.rst
- docs/source/getting-set-up.rst
- docs/source/index.rst
Update master documentation after release of M11.1.
> Update documentation for M11.1.

- samples/bank-of-corda-demo/build.gradle
It matches CoreTestUtils.kt BOC Party.
> Fix name in Bank Of Corda demo config.

- client/rpc/src/main/kotlin/net/corda/client/rpc/internal/RPCClientProxyHandler.kt
RPC operations can throw `ActiveMQException` instances when there is a problem. These are checked exceptions, but nothing on `CordaRPCOps` declares them as being thrown. This causes Java interoperability issues, so wrap any `ActiveMQException` with unchecked `RPCException`.
Fixes #698.
> Wrap any ActiveMQException inside an unchecked RPCException.

- build.gradle
- client/jackson/src/main/kotlin/net/corda/jackson/JacksonSupport.kt
- client/jackson/src/main/kotlin/net/corda/jackson/StringToMethodCallParser.kt
- client/jackson/src/test/kotlin/net/corda/jackson/StringToMethodCallParserTest.kt
- core/src/main/kotlin/net/corda/core/contracts/ContractsDSL.kt
- core/src/main/kotlin/net/corda/core/contracts/Structures.kt
- core/src/main/kotlin/net/corda/core/crypto/X509Utilities.kt
- core/src/main/kotlin/net/corda/core/identity/Party.kt
- core/src/main/kotlin/net/corda/core/schemas/PersistentTypes.kt
- core/src/main/kotlin/net/corda/flows/CollectSignaturesFlow.kt
- core/src/main/kotlin/net/corda/flows/FinalityFlow.kt
- docs/source/changelog.rst
- gradle-plugins/cordformation/src/main/groovy/net/corda/plugins/Cordform.groovy
- gradle-plugins/cordformation/src/noderunner/kotlin/net/corda/plugins/NodeRunner.kt
- node-api/src/main/kotlin/net/corda/nodeapi/serialization/DefaultWhitelist.kt
- node/src/main/kotlin/net/corda/node/Corda.kt
- node/src/main/kotlin/net/corda/node/services/statemachine/FlowStateMachineImpl.kt
- node/src/main/kotlin/net/corda/node/services/statemachine/StateMachineManager.kt
- node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt
- tools/demobench/src/main/kotlin/net/corda/demobench/rpc/NodeRPC.kt
Done as part of me writing my event booking app.
> Misc small tweaks and fixes

- core/src/main/kotlin/net/corda/core/crypto/Crypto.kt
- core/src/main/kotlin/net/corda/core/crypto/CryptoUtils.kt
- core/src/main/kotlin/net/corda/core/crypto/KeyStoreUtilities.kt
- core/src/main/kotlin/net/corda/core/crypto/X509Utilities.kt
- core/src/main/kotlin/net/corda/core/identity/Party.kt
- core/src/test/kotlin/net/corda/core/crypto/X509UtilitiesTest.kt
- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/test/kotlin/net/corda/node/services/network/InMemoryIdentityServiceTests.kt
Refactoring of the key encoding/decoding functions using an algorithm multimap.
The above helped me to create a generic converter from SUN (or other providers) to supported key implementations using an encode->decode trick.
> Key encoding/decoding and generic converters between key implementations

- tools/demobench/src/main/kotlin/net/corda/demobench/model/JVMConfig.kt
- tools/demobench/src/main/kotlin/net/corda/demobench/model/NodeConfig.kt
- tools/demobench/src/main/kotlin/net/corda/demobench/model/NodeController.kt
- tools/demobench/src/main/kotlin/net/corda/demobench/model/NodeData.kt
- tools/demobench/src/main/kotlin/net/corda/demobench/model/ServiceController.kt
- tools/demobench/src/main/kotlin/net/corda/demobench/pty/R3Pty.kt
The capsules are unpacked to `$HOME/.capsule` by default, whereas DemoBench writes the rest of its local data to subdirectories of `$HOME/demobench`. So move the capsules' working directory to `$HOME/demobench/.capsule`. This means that users can delete their `$HOME/demobench` directory and be confident that they've removed everything.
Also perform some minor clean-ups and add a new "Bank of Golden Gates" in San Francisco.
> Unpack DemoBench's capsules within $HOME/demobench directory.

- client/rpc/src/smoke-test/kotlin/net/corda/kotlin/rpc/StandaloneCordaRPClientTest.kt
Extend the attachment smoke test to check that we can download an attachment too.
> Extend smoke test to cover opening attachments.

- core/src/main/kotlin/net/corda/core/identity/AbstractParty.kt
- core/src/main/kotlin/net/corda/core/identity/PartyAndCertificate.kt
- core/src/main/kotlin/net/corda/core/utilities/TestConstants.kt
- node/src/main/kotlin/net/corda/node/utilities/DatabaseSupport.kt
- node/src/test/kotlin/net/corda/node/services/network/InMemoryIdentityServiceTests.kt
- test-utils/src/main/kotlin/net/corda/testing/node/MockNetworkMapCache.kt
Extracting this from #726 to try reducing the size of that PR
> Introduce PartyAndCertificate

- node/src/main/kotlin/net/corda/node/services/messaging/RPCServer.kt
Add diagnostic information if attempting to use an RPC interface with duplicate method names, rather than throwing a collection error.
> Add RPC registration diagnostics

- node/src/integration-test/kotlin/net/corda/node/services/BFTNotaryServiceTests.kt
- node/src/integration-test/kotlin/net/corda/services/messaging/P2PMessagingTest.kt
- node/src/integration-test/kotlin/net/corda/services/messaging/P2PSecurityTest.kt
- node/src/main/kotlin/net/corda/node/driver/Driver.kt
- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/main/kotlin/net/corda/node/utilities/ServiceIdentityGenerator.kt
- samples/notary-demo/src/main/kotlin/net/corda/notarydemo/BFTNotaryCordform.kt
- samples/notary-demo/src/main/kotlin/net/corda/notarydemo/RaftNotaryCordform.kt
- test-utils/src/main/kotlin/net/corda/testing/node/MockServices.kt
- test-utils/src/main/kotlin/net/corda/testing/node/NodeBasedTest.kt
Add certificate and path to node identity in the `NodeInfo` class.
> Add certificate to node identity

- docs/source/running-the-demos.rst
- samples/bank-of-corda-demo/build.gradle
- samples/bank-of-corda-demo/src/main/kotlin/net/corda/bank/BankOfCordaDriver.kt
> Fix bank of corda demo

- node/src/main/kotlin/net/corda/node/Corda.kt
fixing the null pointer exception issue on e.message
> Unknown EC curve null fix

- tools/explorer/src/main/kotlin/net/corda/explorer/views/Network.kt
Fix double rendering of identity label.
> Fix wrong layout of new added nodes to map view in explorer.

- docs/source/tutorial-contract-clauses.rst
- docs/source/tutorial-contract.rst
- docs/source/tutorial-test-dsl.rst
Parts of tutorial-contract.rst description related to code changes:
1) 'States' paragraph: owner is now of AbstractParty type not PublicKey, maybe some modification to owner description is needed?
2)  'wallet' occurences changed to 'vault'
> Update code snippets in tutorial.

- docs/source/running-the-demos.rst
- docs/source/shell.rst
- samples/attachment-demo/src/main/kotlin/net/corda/attachmentdemo/AttachmentDemo.kt
- samples/irs-demo/src/main/kotlin/net/corda/irs/api/IrsDemoClientApi.kt
- samples/trader-demo/src/main/kotlin/net/corda/traderdemo/TraderDemoClientApi.kt
Some demo docs changes.
I tweaked attachment demo as it threw `not implemented` when using crash command for seeing state machines. After merging CRaSH I will add information on `flow running`
> Release fixes

- tools/demobench/src/main/resources/services.conf
- tools/explorer/src/main/kotlin/net/corda/explorer/model/IssuerModel.kt
- tools/explorer/src/main/kotlin/net/corda/explorer/model/ReportingCurrencyModel.kt
This PR takes the three commits from Frederic's PRs and squashes them down. I've rebased and tested that I can issue euros and pay them to other banks in the demobench and explorer.
@FredericDalibard
> Add EUR to the cash app and demobench tool (Frederic Dalibard)

- samples/network-visualiser/src/main/kotlin/net/corda/netmap/NetworkMapVisualiser.kt
- test-utils/src/main/kotlin/net/corda/testing/node/MockNode.kt
It failed on cast when requesting signatures from notary, as now it's not a
SingleMessageRecipient but InMemoryMessagingNetwork.ServiceHandle.
> Fix bug in network simulator.

- client/jackson/src/main/kotlin/net/corda/jackson/JacksonSupport.kt
- core/src/main/kotlin/net/corda/core/contracts/FinanceTypes.kt
- samples/irs-demo/src/integration-test/kotlin/net/corda/irs/IRSDemoTest.kt
- samples/irs-demo/src/main/kotlin/net/corda/irs/contract/IRS.kt
- samples/irs-demo/src/main/kotlin/net/corda/irs/contract/IRSUtils.kt
- samples/irs-demo/src/main/resources/irsweb/js/controllers/CreateDeal.js
- samples/irs-demo/src/main/resources/irsweb/js/controllers/Deal.js
- samples/irs-demo/src/main/resources/irsweb/js/controllers/Home.js
- samples/irs-demo/src/main/resources/irsweb/js/services/HttpErrorHandler.js
- samples/irs-demo/src/main/resources/irsweb/js/services/NodeApi.js
- samples/irs-demo/src/main/resources/irsweb/view/create-deal.html
- samples/irs-demo/src/main/resources/irsweb/view/deal.html
- samples/irs-demo/src/main/resources/irsweb/view/home.html
- test-utils/src/main/kotlin/net/corda/testing/http/HttpApi.kt
- test-utils/src/main/kotlin/net/corda/testing/http/HttpUtils.kt
Why: The IRS demo has been broken and the web demo been less useful than it could be for a while.
What: Added fixings to the IRS demo web UI, a test to check that some fixings are created in the IRSTest and accompanying changes to serialisation options in Jackson to get the test working.
> IRS web demo now shows fixings + general IRS fixes

- client/jfx/src/main/kotlin/net/corda/client/jfx/model/NodeMonitorModel.kt
- client/jfx/src/main/kotlin/net/corda/client/jfx/model/TransactionDataModel.kt
- client/mock/src/main/kotlin/net/corda/client/mock/EventGenerator.kt
- core/src/main/kotlin/net/corda/core/flows/FlowLogic.kt
- tools/explorer/src/main/kotlin/net/corda/explorer/ExplorerSimulation.kt
- tools/explorer/src/main/kotlin/net/corda/explorer/Main.kt
- tools/explorer/src/main/kotlin/net/corda/explorer/identicon/IdenticonRenderer.kt
- tools/explorer/src/main/kotlin/net/corda/explorer/model/CordaViewModel.kt
- tools/explorer/src/main/kotlin/net/corda/explorer/views/Dashboard.kt
- tools/explorer/src/main/kotlin/net/corda/explorer/views/Network.kt
- tools/explorer/src/main/kotlin/net/corda/explorer/views/TransactionViewer.kt
- tools/explorer/src/main/kotlin/net/corda/explorer/views/cordapps/cash/CashViewer.kt
- tools/explorer/src/main/resources/net/corda/explorer/css/corda.css
Changes in simulation, widgets, minor visual.
> Cleanup of the explorer code related to internal flow view work.

- node/src/main/kotlin/net/corda/node/services/identity/InMemoryIdentityService.kt
Force certificate keys into a well known key format before comparing during path validation.
This works around Sun's X509Key class appearing in certificates, which is incomparable to other
key types (i.e. EdDSAKey).
> Force certificate keys into a known format before comparing

- build.gradle
- client/rpc/src/integration-test/kotlin/net/corda/client/rpc/RPCStabilityTests.kt
- node-api/src/main/kotlin/net/corda/nodeapi/RPCApi.kt
- node/src/main/kotlin/net/corda/node/internal/Node.kt
- node/src/main/kotlin/net/corda/node/services/messaging/ArtemisMessagingServer.kt
- node/src/main/kotlin/net/corda/node/services/messaging/NodeMessagingClient.kt
- node/src/main/kotlin/net/corda/node/services/messaging/RPCServer.kt
- test-utils/src/main/kotlin/net/corda/testing/RPCDriver.kt
Continuing from https://github.com/corda/corda/pull/841
Also included Artemis upgrade to 2.1.0 so we can verify the issue is gone (seems to be harder to reproduce with 1.5.3)
> RPC client hang while waiting for server response fix + Artemis Upgrade

- core/src/main/kotlin/net/corda/core/messaging/CordaRPCOps.kt
- core/src/main/kotlin/net/corda/core/node/services/Services.kt
- node/src/main/kotlin/net/corda/node/internal/CordaRPCOpsImpl.kt
- node/src/main/kotlin/net/corda/node/services/vault/HibernateVaultQueryImpl.kt
- node/src/test/java/net/corda/node/services/vault/VaultQueryJavaTests.java
> Replace Vault.PageAndUpdates with DataFeed data class

- client/rpc/src/smoke-test/kotlin/net/corda/kotlin/rpc/StandaloneCordaRPClientTest.kt
StandaloneCordaRPClientTest attempted to use a notary legal identity as service identity, which fails as the service is separate. This separates the two usages correctly.
> Correct usage of notary legal and service identities

- client/rpc/build.gradle
- constants.properties
- docs/source/tutorial-cordapp.rst
- gradle-plugins/cordformation/src/main/groovy/net/corda/plugins/Cordformation.groovy
- gradle-plugins/cordformation/src/main/groovy/net/corda/plugins/Node.groovy
- node/src/main/java/CordaCaplet.java
- samples/attachment-demo/build.gradle
- samples/network-visualiser/build.gradle
- samples/notary-demo/build.gradle
- samples/simm-valuation-demo/build.gradle
- samples/trader-demo/build.gradle
Similar to the last PR except GH won't let me reopen it.
> Cordapps now contain their own dependencies

- docs/source/example-code/src/integration-test/kotlin/net/corda/docs/IntegrationTestingTutorial.kt
- docs/source/tutorial-integration-testing.rst
Someone should own this particular bug. Will be reporting as an issue.
> Fix IntegrationTestingTutorial network map race condition

- client/jackson/src/main/kotlin/net/corda/jackson/JacksonSupport.kt
- core/src/main/kotlin/net/corda/core/crypto/CompositeKey.kt
- core/src/main/kotlin/net/corda/core/crypto/Crypto.kt
- core/src/main/kotlin/net/corda/core/crypto/CryptoUtils.kt
- core/src/main/kotlin/net/corda/core/crypto/SignatureScheme.kt
- core/src/main/kotlin/net/corda/core/crypto/composite/CompositeKey.kt
- core/src/main/kotlin/net/corda/core/crypto/composite/CompositeSignature.kt
- core/src/main/kotlin/net/corda/core/crypto/composite/CompositeSignaturesWithKeys.kt
- core/src/main/kotlin/net/corda/core/crypto/composite/KeyFactory.kt
- core/src/main/kotlin/net/corda/core/crypto/provider/CordaSecurityProvider.kt
- core/src/main/kotlin/net/corda/core/node/services/Services.kt
- core/src/main/kotlin/net/corda/core/serialization/DefaultKryoCustomizer.kt
- core/src/main/kotlin/net/corda/core/serialization/Kryo.kt
- core/src/test/kotlin/net/corda/core/contracts/TransactionTests.kt
- core/src/test/kotlin/net/corda/core/crypto/CompositeKeyTests.kt
- core/src/test/kotlin/net/corda/core/crypto/CryptoUtilsTest.kt
- node-schemas/src/test/kotlin/net/corda/node/services/vault/schemas/VaultSchemaTest.kt
- node/src/integration-test/kotlin/net/corda/node/services/BFTNotaryServiceTests.kt
- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/main/kotlin/net/corda/node/utilities/ServiceIdentityGenerator.kt
- test-utils/src/main/kotlin/net/corda/testing/TestDSL.kt
* Moved Composite Key related classes to crypto.composite
* New CordaSecurityProvider to provide composite key mappings for Java security.
* Added new Composite Key type to Crypto
* Test case for testing storing and retrieving composite key to/from keystore.
> Added composite key provider for storing composite keys in keystore

- core/src/main/kotlin/net/corda/core/messaging/CordaRPCOps.kt
- finance/src/main/kotlin/net/corda/flows/IssuerFlow.kt
- finance/src/main/kotlin/net/corda/flows/TwoPartyTradeFlow.kt
- finance/src/test/kotlin/net/corda/flows/IssuerFlowTest.kt
- node/src/main/kotlin/net/corda/node/internal/CordaRPCOpsImpl.kt
- node/src/test/kotlin/net/corda/node/messaging/TwoPartyTradeFlowTests.kt
- samples/bank-of-corda-demo/src/integration-test/kotlin/net/corda/bank/BankOfCordaHttpAPITest.kt
- samples/bank-of-corda-demo/src/integration-test/kotlin/net/corda/bank/BankOfCordaRPCClientTest.kt
- samples/bank-of-corda-demo/src/main/kotlin/net/corda/bank/BankOfCordaDriver.kt
- samples/bank-of-corda-demo/src/main/kotlin/net/corda/bank/api/BankOfCordaClientApi.kt
- samples/bank-of-corda-demo/src/main/kotlin/net/corda/bank/api/BankOfCordaWebApi.kt
- samples/trader-demo/src/main/kotlin/net/corda/traderdemo/TraderDemoClientApi.kt
- samples/trader-demo/src/main/kotlin/net/corda/traderdemo/flow/SellerFlow.kt
- tools/explorer/src/main/kotlin/net/corda/explorer/views/cordapps/cash/NewTransaction.kt
* Switch to using anonymous party as recipient
* Enable anonymisation for issuance as well as move in issuer flows.
* Pass notary into issuer flow rather than taking a notary at random from the network map.
* Enable anonymisation in IssuerFlowTest
> Clean up IssuerFlow

- node/src/integration-test/kotlin/net/corda/node/services/BFTNotaryServiceTests.kt
> Disable the BFT tests again

- core/src/main/kotlin/net/corda/core/node/services/KeyManagementService.kt
- core/src/main/kotlin/net/corda/core/node/services/TransactionVerifierService.kt
- core/src/main/kotlin/net/corda/core/node/services/VaultQueryService.kt
- core/src/main/kotlin/net/corda/core/node/services/VaultService.kt
- docs/source/api-vault-query.rst
- docs/source/soft-locking.rst
- node/src/integration-test/kotlin/net/corda/services/messaging/P2PMessagingTest.kt
- node/src/main/kotlin/net/corda/node/services/api/AbstractNodeService.kt
- node/src/main/kotlin/net/corda/node/services/api/AcceptsFileUpload.kt
- node/src/main/kotlin/net/corda/node/services/api/ServiceHubInternal.kt
- node/src/main/kotlin/net/corda/node/services/keys/E2ETestKeyManagementService.kt
- node/src/main/kotlin/net/corda/node/services/messaging/Messaging.kt
- node/src/main/kotlin/net/corda/node/services/messaging/ServiceRequestMessage.kt
- node/src/main/kotlin/net/corda/node/services/network/InMemoryNetworkMapCache.kt
- node/src/main/kotlin/net/corda/node/services/network/NetworkMapService.kt
- node/src/test/kotlin/net/corda/node/messaging/InMemoryMessagingTests.kt
- node/src/test/kotlin/net/corda/node/services/messaging/ArtemisMessagingTests.kt
- node/src/test/kotlin/net/corda/node/services/network/AbstractNetworkMapServiceTest.kt
- samples/bank-of-corda-demo/src/integration-test/kotlin/net/corda/bank/BankOfCordaRPCClientTest.kt
The Services.kt has always been difficult to tell what services are where. In addition many of the services are already in standalone files. So this is a simple cleanup. It also lets me push a couple of things into node.
> Put Services.kt in separate files

- node/src/test/kotlin/net/corda/node/services/vault/NodeVaultServiceTest.kt
I'm refactoring makeUpdate in another PR and it's no longer accessible – in this case it doesn't really need to be.
> Minor: Modify NodeVaultServiceTest to not access makeUpdate() directly

- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/main/kotlin/net/corda/node/utilities/ServiceIdentityGenerator.kt
* Remove Kryo from ServiceIdentityGenerator
* Store encoded private, public and composite key to file instead of Party and Key using Kryo.
> Remove use of Kryo in ServiceIdentityGenerator

- .gitignore
- core/src/main/kotlin/net/corda/core/Utils.kt
- core/src/main/kotlin/net/corda/core/contracts/Structures.kt
- core/src/main/kotlin/net/corda/core/contracts/TimeWindow.kt
- core/src/main/kotlin/net/corda/core/internal/InternalUtils.kt
- core/src/main/kotlin/net/corda/core/node/services/TimeWindowChecker.kt
- core/src/test/kotlin/net/corda/core/contracts/TimeWindowTest.kt
- core/src/test/kotlin/net/corda/core/node/services/TimeWindowCheckerTests.kt
- docs/source/example-code/src/main/kotlin/net/corda/docs/WorkflowTransactionBuildTutorial.kt
- node/src/integration-test/kotlin/net/corda/services/messaging/P2PMessagingTest.kt
- node/src/main/kotlin/net/corda/node/utilities/ClockUtils.kt
- node/src/main/kotlin/net/corda/node/utilities/TestClock.kt
- samples/irs-demo/src/main/kotlin/net/corda/irs/contract/IRS.kt
- samples/simm-valuation-demo/src/main/kotlin/net/corda/vega/contracts/OGTrade.kt
- samples/simm-valuation-demo/src/main/kotlin/net/corda/vega/contracts/PortfolioSwap.kt
- test-utils/src/main/kotlin/net/corda/testing/driver/Driver.kt
- test-utils/src/main/kotlin/net/corda/testing/node/TestClock.kt
- tools/demobench/src/main/kotlin/net/corda/demobench/web/WebServer.kt
I also made `midpoint` return null rather than throwing an exception if either side is null.
> Cleaned up TimeWindow and added a bit more docs.

- core/src/main/kotlin/net/corda/core/contracts/TransactionTypes.kt
- core/src/main/kotlin/net/corda/core/contracts/clauses/ClauseVerifier.kt
- core/src/main/kotlin/net/corda/core/flows/ContractUpgradeFlow.kt
- core/src/main/kotlin/net/corda/core/flows/FinalityFlow.kt
- core/src/main/kotlin/net/corda/core/transactions/BaseTransaction.kt
- core/src/main/kotlin/net/corda/core/transactions/LedgerTransaction.kt
- core/src/main/kotlin/net/corda/core/transactions/WireTransaction.kt
- core/src/test/kotlin/net/corda/core/contracts/LedgerTransactionQueryTests.kt
- core/src/test/kotlin/net/corda/core/contracts/TransactionEncumbranceTests.kt
- core/src/test/kotlin/net/corda/core/flows/CollectSignaturesFlowTests.kt
- core/src/test/kotlin/net/corda/core/node/AttachmentClassLoaderTests.kt
- docs/source/example-code/src/main/kotlin/net/corda/docs/FlowCookbook.kt
- docs/source/example-code/src/main/kotlin/net/corda/docs/WorkflowTransactionBuildTutorial.kt
- experimental/src/main/kotlin/net/corda/contracts/universal/UniversalContract.kt
- finance/src/main/kotlin/net/corda/contracts/CommercialPaper.kt
- finance/src/main/kotlin/net/corda/contracts/CommercialPaperLegacy.kt
- finance/src/main/kotlin/net/corda/contracts/asset/Obligation.kt
- finance/src/main/kotlin/net/corda/flows/IssuerFlow.kt
- finance/src/main/kotlin/net/corda/flows/TwoPartyTradeFlow.kt
- finance/src/test/kotlin/net/corda/contracts/asset/CashTests.kt
- finance/src/test/kotlin/net/corda/contracts/asset/ObligationTests.kt
- finance/src/test/kotlin/net/corda/flows/CashExitFlowTests.kt
- finance/src/test/kotlin/net/corda/flows/CashIssueFlowTests.kt
- node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt
- node/src/test/kotlin/net/corda/node/services/NotaryChangeTests.kt
- samples/attachment-demo/src/main/kotlin/net/corda/attachmentdemo/AttachmentDemo.kt
- samples/irs-demo/src/test/kotlin/net/corda/irs/contract/IRSTests.kt
- tools/explorer/src/main/kotlin/net/corda/explorer/views/Network.kt
- tools/explorer/src/main/kotlin/net/corda/explorer/views/TransactionViewer.kt
This puts various mapping and filtering operation onto BaseTransaction and LedgerTransaction to aid CorDapp developers.
> Create a friendlier set of access methods to states on transactions

- client/rpc/src/main/kotlin/net/corda/client/rpc/internal/RPCClientProxyHandler.kt
- core/src/main/kotlin/net/corda/core/Utils.kt
- core/src/main/kotlin/net/corda/core/internal/ThreadBox.kt
- node/src/main/kotlin/net/corda/node/services/events/NodeSchedulerService.kt
- node/src/main/kotlin/net/corda/node/services/keys/E2ETestKeyManagementService.kt
- node/src/main/kotlin/net/corda/node/services/keys/PersistentKeyManagementService.kt
- node/src/main/kotlin/net/corda/node/services/messaging/ArtemisMessagingServer.kt
- node/src/main/kotlin/net/corda/node/services/messaging/NodeMessagingClient.kt
- node/src/main/kotlin/net/corda/node/services/network/NetworkMapService.kt
- node/src/main/kotlin/net/corda/node/services/network/PersistentNetworkMapService.kt
- node/src/main/kotlin/net/corda/node/services/persistence/DBTransactionMappingStorage.kt
- node/src/main/kotlin/net/corda/node/services/persistence/InMemoryStateMachineRecordedTransactionMappingStorage.kt
- node/src/main/kotlin/net/corda/node/services/statemachine/StateMachineManager.kt
- node/src/main/kotlin/net/corda/node/services/transactions/PersistentUniquenessProvider.kt
- node/src/main/kotlin/net/corda/node/services/vault/HibernateVaultQueryImpl.kt
- node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt
- samples/irs-demo/src/main/kotlin/net/corda/irs/api/NodeInterestRates.kt
- test-utils/src/main/kotlin/net/corda/testing/driver/Driver.kt
- test-utils/src/main/kotlin/net/corda/testing/node/InMemoryMessagingNetwork.kt
I would have moved it into core.utilities and kept it public if it were not for the fact that it doesn't seem to work in Java.
> Moved ThreadBox into core.internal

- core/src/test/kotlin/net/corda/core/serialization/carpenter/ClassCarpenterTestUtils.kt
Just a little tidyup since it was decided we didn't want these things
in the code base and this one must've slipped through the cracks
> Remove spurious comment line

- core/src/main/kotlin/net/corda/core/utilities/LegalNameValidator.kt
- node-api/src/main/kotlin/net/corda/nodeapi/config/ConfigUtilities.kt
- node/src/main/kotlin/net/corda/node/utilities/registration/NetworkRegistrationHelper.kt
* added x500 name validation in Network registration.
* fix for github issue #1130
> Remove x500 name validation when loading config file.

- core/src/main/kotlin/net/corda/core/node/services/VaultService.kt
- core/src/test/kotlin/net/corda/core/node/VaultUpdateTests.kt
- node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt
- node/src/test/kotlin/net/corda/node/services/vault/NodeVaultServiceTest.kt
Fix a minor related issue with update type propagation.
> Add a test for notary change transaction updates in the vault.

- samples/attachment-demo/build.gradle
- samples/attachment-demo/src/main/kotlin/net/corda/attachmentdemo/AttachmentDemo.kt
- samples/bank-of-corda-demo/src/main/kotlin/net/corda/bank/api/BankOfCordaClientApi.kt
- samples/irs-demo/build.gradle
- samples/simm-valuation-demo/build.gradle
- samples/trader-demo/build.gradle
Updates node configurations to match changes introduced in #875
> Update node configurations to match changes to test constants

- core/src/main/kotlin/net/corda/core/contracts/Amount.kt
- core/src/main/kotlin/net/corda/core/contracts/Structures.kt
- core/src/main/kotlin/net/corda/core/node/PhysicalLocationStructures.kt
- core/src/test/kotlin/net/corda/core/flows/ContractUpgradeFlowTest.kt
- core/src/test/kotlin/net/corda/core/serialization/TransactionSerializationTests.kt
- finance/src/main/java/net/corda/contracts/JavaCommercialPaper.java
- finance/src/main/kotlin/net/corda/contracts/CommercialPaper.kt
- finance/src/main/kotlin/net/corda/contracts/CommercialPaperLegacy.kt
- finance/src/main/kotlin/net/corda/contracts/asset/Cash.kt
- finance/src/main/kotlin/net/corda/contracts/asset/CommodityContract.kt
- finance/src/main/kotlin/net/corda/contracts/asset/Obligation.kt
- finance/src/test/kotlin/net/corda/contracts/DummyFungibleContract.kt
- node-schemas/src/test/kotlin/net/corda/node/services/vault/schemas/VaultSchemaTest.kt
- samples/network-visualiser/src/main/kotlin/net/corda/netmap/VisualiserViewModel.kt
- test-utils/src/main/kotlin/net/corda/testing/contracts/DummyContract.kt
- tools/explorer/src/main/kotlin/net/corda/explorer/views/Network.kt
Remove a few more places where we used kotlin Pair.
> Remove kotlin.Pair from Public APIs

- build.gradle
- core/build.gradle
- test-common/build.gradle
It appears this plugin was removed by a merge conflict at some point in the last month.
> Fixed publishing to artifactory for core

- tools/demobench/src/main/kotlin/net/corda/demobench/views/NodeTerminalView.kt
> Minor: fix a DemoBench crash 

- node/src/test/java/net/corda/node/services/vault/VaultQueryJavaTests.java
To test my Git permissions more than anything else
> Minor changes to the unit test

- docs/source/example-code/build.gradle
Why: Causes a warning when Corda is building.
> Fixed a warning caused by an incorrect configuration.

- client/rpc/src/main/kotlin/net/corda/client/rpc/internal/RPCClientProxyHandler.kt
- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/test/kotlin/net/corda/node/messaging/TwoPartyTradeFlowTests.kt
- samples/simm-valuation-demo/src/main/kotlin/net/corda/vega/contracts/OGTrade.kt
- samples/simm-valuation-demo/src/main/kotlin/net/corda/vega/contracts/PortfolioSwap.kt
- Fix typos
- Fix other Kotlin warnings
> Remove usages of deprecated methods

- core/src/main/kotlin/net/corda/core/internal/ResolveTransactionsFlow.kt
- core/src/main/kotlin/net/corda/core/node/ServiceHub.kt
- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/main/kotlin/net/corda/node/services/api/ServiceHubInternal.kt
- node/src/main/kotlin/net/corda/node/services/vault/HibernateVaultQueryImpl.kt
- node/src/test/kotlin/net/corda/node/services/database/HibernateConfigurationTest.kt
- node/src/test/kotlin/net/corda/node/services/vault/NodeVaultServiceTest.kt
- test-utils/src/main/kotlin/net/corda/testing/node/MockServices.kt
* TX recorded from ResolveTransactionsFlow will not notify vault as they are always irrelevant.
> Added notifyVault flag to recordTransaction and skip notify for irrelevant TX

- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/CordaClassResolver.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/DefaultKryoCustomizer.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/Kryo.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/KryoTests.kt
Also added some unit tests that expose the problem
> Resolve a problem when Exceptions with suppression passed through Kryo serialization

- finance/src/main/java/net/corda/contracts/JavaCommercialPaper.java
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializationOutputTests.kt
Functionally this change is a NOP
> Eliminate warnings in Java and Kotlin code

- client/rpc/src/smoke-test/kotlin/net/corda/kotlin/rpc/StandaloneCordaRPClientTest.kt
Use count down latch to ensure we have processed observations before checking results.
> Fix flakey RPC tests

- build.gradle
Final clean-up lingering from the Requery Removal PR.
> Completely remove any trace of node-schemas.

- client/mock/src/main/kotlin/net/corda/client/mock/EventGenerator.kt
- finance/src/main/kotlin/net/corda/flows/AbstractCashFlow.kt
- finance/src/main/kotlin/net/corda/flows/CashExitFlow.kt
- finance/src/main/kotlin/net/corda/flows/CashIssueAndPaymentFlow.kt
- finance/src/main/kotlin/net/corda/flows/CashIssueFlow.kt
- finance/src/main/kotlin/net/corda/flows/CashPaymentFlow.kt
- tools/explorer/src/main/kotlin/net/corda/explorer/ExplorerSimulation.kt
- tools/explorer/src/main/kotlin/net/corda/explorer/views/cordapps/cash/NewTransaction.kt
- tools/loadtest/src/main/kotlin/net/corda/loadtest/LoadTest.kt
- tools/loadtest/src/main/kotlin/net/corda/loadtest/tests/CrossCashTest.kt
- tools/loadtest/src/main/kotlin/net/corda/loadtest/tests/GenerateHelpers.kt
- tools/loadtest/src/main/kotlin/net/corda/loadtest/tests/SelfIssueTest.kt
- tools/loadtest/src/main/kotlin/net/corda/loadtest/tests/StabilityTest.kt
Removing usages of the deprecated CashFlowCommand.
> Removing usages of the deprecated CashFlowCommand

- core/src/main/kotlin/net/corda/core/transactions/WireTransaction.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/DeserializationInput.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/DeserializedParameterizedType.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/Schema.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializationHelper.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializerFactory.kt
- node-api/src/test/kotlin/net/corda/nodeapi/AttachmentClassLoaderTests.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/DeserializedParameterizedTypeTests.kt
And do everything necessary for AttachmentClassLoaderTests to be passing in AMQP mode
> Make WireTransaction @CordaSerializable

- core/src/test/kotlin/net/corda/core/serialization/CommandsSerializationTests.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/AMQPSerializationScheme.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/DeserializationInput.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/Schema.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializationHelper.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializerFactory.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/custom/ClassSerializer.kt
- test-utils/src/main/kotlin/net/corda/testing/contracts/DummyContract.kt
See: `net.corda.finance.contracts.asset.Cash.Commands.Move` for example use
Also wrote the unit test that exposes the issue(CommandsSerializationTests) and fixed TransactionEncumbranceTests to make it pass in AMQP mode
> Make sure members of type `Class` correctly serialized using AMQP

- core/src/main/kotlin/net/corda/core/crypto/composite/CompositeKey.kt
- core/src/test/kotlin/net/corda/core/crypto/CompositeKeyTests.kt
> Correct misleading comment in CompositeKey and minor changes to its unit test

- finance/src/main/kotlin/net/corda/finance/contracts/asset/Cash.kt
- finance/src/main/kotlin/net/corda/finance/contracts/asset/OnLedgerAsset.kt
- finance/src/test/kotlin/net/corda/finance/contracts/asset/CashTests.kt
Multi-spends let you request multiple payments to different parties be calculated simultaneously.
Requested by Roger for Ubin.
> Add support for multi-spends to OnLedgerAsset and Cash. 

- docs/build.gradle
* Switch documentation JDK version to 8
* Add node-api to Dokka includes
> Update Dokka configuration

- .idea/runConfigurations/Quasar_exclude_pattern_extraction_from_node_tests__need_not_pass__check_output_at_the_bottom_of_console_.xml
- experimental/quasar-hook/README.md
- experimental/quasar-hook/src/main/kotlin/net/corda/quasarhook/QuasarInstrumentationHook.kt
- node/capsule/build.gradle
- test-utils/src/main/kotlin/net/corda/testing/driver/Driver.kt
The pattern was generated with the quasar-hook tool and should reduce node startup time considerably (16-17 seconds -> 9-10 seconds on my laptop)
> Add exclude pattern to the quasar agent

- core/src/main/kotlin/net/corda/core/crypto/CompositeKey.kt
- docs/packages.md
Add package descriptions used by Dokka
Part of https://r3-cev.atlassian.net/browse/CORDA-499
> Add package descriptions to Dokka

- docs/build.gradle
Add references to BouncyCastle, JavaFX and Rx documentation for Dokka to link to.
> Add external documentation

- node/src/main/kotlin/net/corda/node/services/transactions/RaftUniquenessProvider.kt
Basic Raft cluster status exported using JMX, seems useful.
> Add basic Raft cluster status metrics

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- docs/source/release-process-index.rst
- docs/source/testing.rst
This is a first version of our issue and PR templates to help and thank contributors for their work. This will appear in the PR box (like the one I am writing this message into) before the user has selected it for the first time.
> Added pull request and issue templates for GitHub.

- node/src/main/kotlin/net/corda/node/services/identity/PersistentIdentityService.kt
This changes the PersistentIdentityServiced to use the AppendOnlyPersistentMap, which gives bounded memory and prevents problems of duplicate inserts that we were encountering.
> Change PersistentIdentityService to have bounded memory

- finance/src/main/kotlin/net/corda/finance/contracts/asset/cash/selection/CashSelectionH2Impl.kt
- node/src/test/kotlin/net/corda/node/services/vault/VaultQueryTests.kt
- samples/network-visualiser/src/main/kotlin/net/corda/netmap/VisualiserViewModel.kt
- tools/demobench/src/main/kotlin/net/corda/demobench/model/NodeController.kt
- tools/demobench/src/main/kotlin/net/corda/demobench/views/NodeTabView.kt
- tools/explorer/src/main/kotlin/net/corda/explorer/views/Network.kt
- tools/explorer/src/main/kotlin/net/corda/explorer/views/cordapps/cash/CashViewer.kt
Just remove a few trivial compiler warnings in the code.
> Remove some trivial syntax related warning messages.

- docs/source/example-code/src/main/kotlin/net/corda/docs/WorkflowTransactionBuildTutorial.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializerFactory.kt
Make minor changes which are meant to ensure that "example-code" works fine with AMQP serialization
> CORDA-540: AMQP-forge "example-code"

- docs/source/changelog.rst
- node/src/integration-test/kotlin/net/corda/test/node/NodeStatePersistenceTests.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/driver/Driver.kt
https://r3-cev.atlassian.net/browse/CORDA-303
> [CORDA-303]: Add some tests that stop and start a node and check state is persistent.

- samples/irs-demo/src/integration-test/kotlin/net/corda/irs/IRSDemoTest.kt
> Fix IrsDemoTest for days that have a fixing.

- core/src/main/kotlin/net/corda/core/serialization/SerializationAPI.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/SerializationScheme.kt
- node-api/src/test/kotlin/net/corda/nodeapi/AttachmentClassLoaderTests.kt
> Correctly unwrap MissingAttachmentException.

- gradle-plugins/cordformation/src/noderunner/kotlin/net/corda/plugins/NodeRunner.kt
> Add delay to macos script startup

- core/src/main/kotlin/net/corda/core/flows/SwapIdentitiesFlow.kt
- core/src/test/kotlin/net/corda/core/flows/SwapIdentitiesFlowTests.kt
- finance/src/main/kotlin/net/corda/finance/flows/CashPaymentFlow.kt
- finance/src/main/kotlin/net/corda/finance/flows/TwoPartyDealFlow.kt
- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/main/kotlin/net/corda/node/services/CoreFlowHandlers.kt
This is the rename part of #1220 by itself, in an attempt to get it in for 1.0.
> Rename TransactionKeyFlow to SwapIdentitiesFlow

- core/src/main/kotlin/net/corda/core/serialization/SerializationAPI.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/AMQPSerializationScheme.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/CustomSerializer.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/DeserializedParameterizedType.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/MapSerializer.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/Schema.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializerFactory.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/custom/BitSetSerializer.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/custom/EnumSetSerializer.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/custom/InputStreamSerializer.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/custom/SimpleStringSerializer.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/custom/StringBufferSerializer.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/custom/ThrowableSerializer.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/custom/ZoneIdSerializer.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializationOutputTests.kt
- Also a couple of bug fixes encountered along the way.
> Some additional serializers to fill in the blanks vs. our default whitelist

- build.gradle
- confidential-identities/build.gradle
- confidential-identities/src/main/kotlin/net/corda/confidential/SwapIdentitiesFlow.kt
- confidential-identities/src/main/kotlin/net/corda/confidential/SwapIdentitiesHandler.kt
- confidential-identities/src/test/kotlin/net/corda/confidential/SwapIdentitiesFlowTests.kt
- finance/build.gradle
- finance/src/main/kotlin/net/corda/finance/flows/CashPaymentFlow.kt
- finance/src/main/kotlin/net/corda/finance/flows/TwoPartyDealFlow.kt
- node-api/build.gradle
- node/build.gradle
- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/main/kotlin/net/corda/node/services/CoreFlowHandlers.kt
- settings.gradle
> Move SwapIdentitiesFlow to confidential-identities module

- tools/explorer/src/main/kotlin/net/corda/explorer/ExplorerSimulation.kt
Fix US country code in ExplorerSimulation.kt.
It's US not USA
> Fix US country code

- samples/bank-of-corda-demo/build.gradle
- samples/bank-of-corda-demo/src/main/kotlin/net/corda/bank/BankOfCordaDriver.kt
- testing/test-utils/src/main/kotlin/net/corda/testing/CoreTestUtils.kt
Moved BigCorporation to NY for better visualisation
> [CORDA-583] Test identities names cleanup

- core/src/main/kotlin/net/corda/core/flows/AbstractStateReplacementFlow.kt
- core/src/main/kotlin/net/corda/core/flows/CollectSignaturesFlow.kt
- core/src/main/kotlin/net/corda/core/internal/InternalUtils.kt
- core/src/main/kotlin/net/corda/core/node/ServiceHub.kt
- core/src/main/kotlin/net/corda/core/transactions/TransactionWithSignatures.kt
- core/src/test/kotlin/net/corda/core/flows/CollectSignaturesFlowTests.kt
- finance/src/main/kotlin/net/corda/finance/flows/CashExitFlow.kt
- finance/src/main/kotlin/net/corda/finance/flows/TwoPartyDealFlow.kt
- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/main/kotlin/net/corda/node/services/upgrade/ContractUpgradeServiceImpl.kt
- node/src/test/kotlin/net/corda/node/messaging/TwoPartyTradeFlowTests.kt
- samples/irs-demo/src/main/kotlin/net/corda/irs/flows/AutoOfferFlow.kt
- samples/simm-valuation-demo/src/main/kotlin/net/corda/vega/flows/SimmFlow.kt
Kept this out in a distinct branch of our main porting work.
WDYT?
It's questionable whether the methods should be on `ServiceHub` since it results in a bit of `serviceHub...` in the code.  If they were on `FlowLogic` that wouldn't be the case.
> FlowSession utilities

- .github/PULL_REQUEST_TEMPLATE.md
* Use github task list format.
* Remove (seemingly?) duplicated items.
* People keep forgetting to delete the section so give up and just try to ensure the top line is edited.
* Add a police emoji to make it clear we're serious
> Adjustments to the PR checklist

- webserver/src/main/kotlin/net/corda/webserver/converters/Converters.kt
- webserver/src/main/kotlin/net/corda/webserver/internal/NodeWebServer.kt
CordaX500Name can be used as a @QueryParam in JAX-RS services
> CORDA-578 CordaX500Name JAX-RS parameter converter

- docs/source/tutorial-cordapp.rst
This webserver does not start in this demo, it's not defined in docs, code or gradle file
> Removal of non-used webserver

- client/jfx/src/main/kotlin/net/corda/client/jfx/model/NetworkIdentityModel.kt
- client/jfx/src/main/kotlin/net/corda/client/jfx/utils/ObservableUtilities.kt
- finance/src/main/kotlin/net/corda/finance/flows/CashConfigDataFlow.kt
- node/src/main/kotlin/net/corda/node/services/statemachine/FlowStateMachineImpl.kt
- samples/bank-of-corda-demo/build.gradle
- tools/explorer/src/main/kotlin/net/corda/explorer/ExplorerSimulation.kt
- tools/explorer/src/main/kotlin/net/corda/explorer/model/IssuerModel.kt
- tools/explorer/src/main/kotlin/net/corda/explorer/model/ReportingCurrencyModel.kt
- tools/explorer/src/main/kotlin/net/corda/explorer/views/Network.kt
- tools/explorer/src/main/kotlin/net/corda/explorer/views/Settings.kt
- tools/explorer/src/main/kotlin/net/corda/explorer/views/TransactionViewer.kt
- tools/explorer/src/main/kotlin/net/corda/explorer/views/cordapps/cash/NewTransaction.kt
- tools/explorer/src/main/resources/net/corda/explorer/views/Network.fxml
Fixing Cash app after changes to advertising service.
Added CashConfigDataFlow to obtain app data from cash app.
> Explorer advertising service fix

- client/jfx/src/main/kotlin/net/corda/client/jfx/model/NodeMonitorModel.kt
fetch unconsumed vault snapshot instead of ALL to prevent explorer to pull back consumed state on restart.
> Fetch unconsumed vault snapshot instead of ALL

- docs/source/running-the-demos.rst
- samples/bank-of-corda-demo/build.gradle
- samples/bank-of-corda-demo/src/integration-test/kotlin/net/corda/bank/BankOfCordaHttpAPITest.kt
- samples/bank-of-corda-demo/src/main/kotlin/net/corda/bank/BankOfCordaDriver.kt
- samples/bank-of-corda-demo/src/main/kotlin/net/corda/bank/api/BankOfCordaClientApi.kt
- samples/bank-of-corda-demo/src/main/kotlin/net/corda/bank/api/BankOfCordaWebApi.kt
Remove DUMMY_NOTARY.name because it causes confusion and is source of potential inconsistency between configs/notary identity created for a node
> Fix BankOfCorda demo after services removal

- samples/irs-demo/src/main/resources/irsweb/view/deal.html
Please see https://r3-cev.atlassian.net/browse/CORDA-570 for background for a change and test evidence
> CORDA-570: Display calendar name instead of long and incomplete list of holiday dates

- docs/source/api-states.rst
Refreshes the States API page to reflect v1.0 changes.
> Joel states api

- docs/source/api-contracts.rst
Refreshes the Contracts API docs for Corda v1.0.
> Updated documentation: API contracts

- docs/source/tutorial-cordapp.rst
Reworks the example CorDapp instructions:
* Fixes a link
* General corrections to reflect repo changes
> Updated documentation: Tutorial

- core/src/main/kotlin/net/corda/core/contracts/Structures.kt
- docs/source/api-core-types.rst
Refreshes Core Types API page to reflect codebase changes.
> Updates key types page.

- core/src/main/kotlin/net/corda/core/contracts/ContractAttachment.kt
- core/src/main/kotlin/net/corda/core/contracts/TransactionVerificationException.kt
- core/src/main/kotlin/net/corda/core/node/services/AttachmentStorage.kt
- core/src/main/kotlin/net/corda/core/transactions/MissingContractAttachments.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/GeneratedAttachment.kt
- testing/test-utils/src/main/kotlin/net/corda/testing/contracts/DummyLinearContract.kt
- testing/test-utils/src/main/kotlin/net/corda/testing/node/MockAttachment.kt
This is all base work that wasn't controversial from the main PR that could be merged in advance to reduce the size of the PR. All of it won't really do anything in isolation though.
> Base types and changes required for the Contract Constraints work.

- .idea/runConfigurations/Explorer___GUI.xml
- docs/source/node-explorer.rst
Also align the name for run configuration for Node Explorer GUI
> CORDA-611: Improve documentation for Node Explorer

- client/jfx/src/main/kotlin/net/corda/client/jfx/model/TransactionDataModel.kt
- tools/explorer/src/main/kotlin/net/corda/explorer/ExplorerSimulation.kt
fix for https://r3-cev.atlassian.net/browse/CORDA-609
> fix several elements associated with the same key bug

- docs/source/getting-set-up.rst
Removes hard-coded M12 references.
> Removes hard-coded M12 references.

- core/src/main/kotlin/net/corda/core/messaging/CordaRPCOps.kt
- core/src/main/kotlin/net/corda/core/node/services/VaultQueryService.kt
- core/src/main/kotlin/net/corda/core/node/services/VaultService.kt
- core/src/main/kotlin/net/corda/core/node/services/vault/QueryCriteriaUtils.kt
- docs/source/api-vault-query.rst
- node/src/main/kotlin/net/corda/node/internal/CordaRPCOpsImpl.kt
- node/src/main/kotlin/net/corda/node/services/vault/HibernateQueryCriteriaParser.kt
- node/src/main/kotlin/net/corda/node/services/vault/HibernateVaultQueryImpl.kt
- node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt
- node/src/test/kotlin/net/corda/node/services/vault/VaultQueryTests.kt
_ContractType_ renamed to _ContractStateType_
> Vault Query API parameter rename to aid clarity

- docs/source/tutorial-cordapp.rst
CORDA-618 - update example doc
> fix create-iou URL in docs

- docs/source/running-the-demos.rst
Adds a table of contents to the demos page. Makes the demo names hyperlinks. Links to the GitHub issues page.
> Adds ToC and internal links.

- constants.properties
> Bumping gradle plugins to match the 1.0.0 major version.

- finance/src/main/kotlin/net/corda/finance/flows/CashPaymentFlow.kt
- finance/src/main/kotlin/net/corda/finance/flows/TwoPartyTradeFlow.kt
Correct flow calls to generateSpend() to match 1.0 API changes
> Correct flow calls to generateSpend()

- samples/attachment-demo/src/integration-test/kotlin/net/corda/attachmentdemo/AttachmentDemoTest.kt
- samples/attachment-demo/src/main/kotlin/net/corda/attachmentdemo/AttachmentDemo.kt
The test didn't work because the web server for the recipient wasn't started, and the resulting exception wasn't failing the test.
> Fixed AttachmentDemoTest

- client/rpc/src/test/kotlin/net/corda/client/rpc/RepeatingBytesInputStream.kt
- core/src/test/kotlin/net/corda/core/crypto/CryptoUtilsTest.kt
- finance/src/main/kotlin/net/corda/finance/contracts/math/Interpolators.kt
- tools/loadtest/src/main/kotlin/net/corda/loadtest/tests/CrossCashTest.kt
Stylistic clean up replacing instances of `for (i in 0..blah -1)` using `until` keyword.
> Replace for ..-1 with until

- docs/source/changelog.rst
- docs/source/serialization.rst
- finance/src/main/kotlin/net/corda/finance/flows/TwoPartyDealFlow.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/CordaClosureSerializer.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/DefaultKryoCustomizer.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/SerializationScheme.kt
- node-api/src/test/java/net/corda/nodeapi/internal/serialization/ForbiddenLambdaSerializationTests.java
- node-api/src/test/java/net/corda/nodeapi/internal/serialization/LambdaCheckpointSerializationTest.java
- samples/simm-valuation-demo/src/main/kotlin/net/corda/vega/flows/SimmFlow.kt
JIRA:
-  https://r3-cev.atlassian.net/browse/CORDA-627
- https://r3-cev.atlassian.net/browse/CORDA-481
> [CORDA-627][CORDA-481]: Fixed Simm Valuation Demo Test and enable serializable java 8 lambdas.

- tools/explorer/src/main/kotlin/net/corda/explorer/ExplorerSimulation.kt
same as #1654 but for the release branch
> [CORDA-624] Node Explorer on Issuing cash throws MissingContractAttac… M16 RC2

- finance/src/main/kotlin/net/corda/finance/contracts/asset/cash/selection/CashSelectionH2Impl.kt
- samples/trader-demo/src/main/kotlin/net/corda/traderdemo/TraderDemo.kt
Coins selection total was only integer type.  This makes it a long.
> BIGINT fix for H2 coin selection.

- client/jfx/src/main/kotlin/net/corda/client/jfx/model/NetworkIdentityModel.kt
Put in hack to filter out network map as instructed
> CORDA-637 Node Explorer shows Network Map Service in Cash Issue dropdown

- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/DeserializationInput.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializationHelper.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializerFactory.kt
- node-api/src/test/java/net/corda/nodeapi/internal/serialization/amqp/ListsSerializationJavaTest.java
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/ListsSerializationTest.kt
> CORDA-540: Ensure that covariance of type is handled correctly when serializing with AMQP

- core/src/main/kotlin/net/corda/core/concurrent/ConcurrencyUtils.kt
This message isn't supposed to be visible anyway, except that it is. So at least make it unmodifiable.
> Declare internal message string as "const".

- finance/src/main/kotlin/net/corda/finance/contracts/FinanceTypes.kt
- samples/irs-demo/src/main/resources/irsweb/view/create-deal.html
Added ISDA day counting method enum
Rolling convention reflects corda enums so no errors are triggered
> IRS Demo UI Fixes

- node-api/src/main/kotlin/net/corda/nodeapi/RPCApi.kt
- node/src/main/kotlin/net/corda/node/services/messaging/RPCServer.kt
I'll rebase this on top of your PR once you merged it.
> RPC: Report failures during deserialisation of method arguments to the client as an exception.

- docs/source/example-code/src/main/kotlin/net/corda/docs/CustomNotaryTutorial.kt
- node/src/main/kotlin/net/corda/node/services/transactions/ValidatingNotaryFlow.kt
- node/src/test/kotlin/net/corda/node/services/NotaryChangeTests.kt
This fix has been approved and merged on master
> Fix validating notary flow to handle notary change transactions properly

- docs/source/tut-two-party-flow.rst
- docs/source/tutorial-test-dsl.rst
- docs/source/writing-cordapps.rst
And a rogue CordaPluginRegistry schema reference (since now converted to annotation).
Will raise to merge to 1.0 after merged to master.
> Fix up some FlowSession and contract constraints in the docs

- docs/source/changelog.rst
Accidentally deleted previous commit when squashing main PR.
> Vault API Unification: added changelog entry.

- core/src/main/kotlin/net/corda/core/flows/FlowSession.kt
- docs/source/api-flows.rst
- docs/source/example-code/src/main/java/net/corda/docs/FlowCookbookJava.java
- docs/source/example-code/src/main/kotlin/net/corda/docs/FlowCookbook.kt
- docs/source/flow-state-machines.rst
This PR adds docs and kdocs on FlowSession and elaborates on session-related things.
> FlowSession docs

- node/src/main/kotlin/net/corda/node/internal/Node.kt
- node/src/main/kotlin/net/corda/node/services/network/PersistentNetworkMapCache.kt
- node/src/test/kotlin/net/corda/node/services/network/PersistentNetworkMapCacheTest.kt
Not fixed the underlying issue yet, but made changes to improve logging around adding/removing nodes which will hopefully allow to establish what is going wrong.
See Jira for background info.
> CORDA-649: Improving logging

- core/src/main/kotlin/net/corda/core/contracts/Structures.kt
- core/src/main/kotlin/net/corda/core/flows/ContractUpgradeFlow.kt
- core/src/main/kotlin/net/corda/core/internal/UpgradeCommand.kt
- core/src/main/kotlin/net/corda/core/transactions/LedgerTransaction.kt
- core/src/test/kotlin/net/corda/core/contracts/DummyContractV2Tests.kt
- core/src/test/kotlin/net/corda/core/flows/ContractUpgradeFlowTest.kt
- node/src/main/kotlin/net/corda/node/services/CoreFlowHandlers.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/MockNode.kt
- testing/test-utils/src/main/kotlin/net/corda/testing/contracts/DummyContractV2.kt
Same as https://github.com/corda/corda/pull/1700 that was merged to the RC branch
> A temporary fix for contract upgrade transactions

- core/src/main/kotlin/net/corda/core/internal/InternalUtils.kt
- core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/AttachmentsClassLoaderTests.kt
- node/src/integration-test/kotlin/net/corda/node/services/AttachmentLoadingTests.kt
> Hide SerializationContext from public API on TransactionBuilder

- core/src/main/kotlin/net/corda/core/internal/InternalUtils.kt
> Add @suppress to prevent .internal. extension methods appearing in docs

- docs/source/tut-two-party-flow.rst
- docs/source/tutorial-test-dsl.rst
- docs/source/writing-cordapps.rst
as per approved PR https://github.com/corda/corda/pull/1690
> Misc documentation fixes as per master

- docs/source/running-the-demos.rst
- samples/simm-valuation-demo/build.gradle
For V1 write a series of JSON / curl commands a user can follow to run the demo
-- pull request looking for comments ATM
> CORDA-594 - SIMM Demo doc update

- core/src/main/kotlin/net/corda/core/cordapp/Cordapp.kt
- core/src/main/kotlin/net/corda/core/internal/cordapp/CordappImpl.kt
- docs/source/changelog.rst
- node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt
Already merged to master - will need to rebase this branch now, will do soon.
> Added Cordapp name field

- node/src/integration-test/kotlin/net/corda/node/services/network/PersistentNetworkMapCacheTest.kt
More changes in this space to follow
> CORDA-649: Disable unstable test

- docs/source/json.rst
- docs/source/shell.rst
> Fixes docsite dead links.

- README.md
> Updates readme for v1.0

- docs/source/json.rst
- docs/source/shell.rst
> Fixes dead links.

- docs/source/key-concepts-contract-constraints.rst
Fixes an issue with the docs formatting.
> Fixes a formatting issue.

- .ci/api-current.txt
Why: This is a devops/CI change - this file will be on all branches and will track the current API. CI will check the diff between it and the current API and if it changes reject the PR. This file needs to be explicitly changed to change the API. This allows us to gate the API changes.
> Added current API to CI directory

- docs/source/release-notes.rst
Fixed bold type on simplified annotation driven scanning bullet and added bold type to module name bullets
> Updated release notes to fix minor typos

- docs/source/changelog.rst
> fixed formatting for release notes.

- .ci/api-current.txt
- .ci/check-api-changes.sh
Why: I want to move the script into TC and the API descriptor is out of date with some V1 merges.
> Added new API check script and API version

- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/DeserializationInput.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/ListsSerializationTest.kt
First attempt to perform envelope verification to assert types encoded in a particular way
> CORDA-540: Perform schema verification

- core/src/test/kotlin/net/corda/core/flows/AttachmentTests.kt
- core/src/test/kotlin/net/corda/core/serialization/AttachmentSerializationTest.kt
- docs/source/example-code/src/test/kotlin/net/corda/docs/CustomVaultQueryTest.kt
- docs/source/example-code/src/test/kotlin/net/corda/docs/FxTransactionBuildTutorialTest.kt
- docs/source/example-code/src/test/kotlin/net/corda/docs/WorkflowTransactionBuildTutorialTest.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/ServiceType.kt
- node/src/integration-test/kotlin/net/corda/node/services/BFTNotaryServiceTests.kt
- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt
- node/src/main/kotlin/net/corda/node/services/config/NodeConfiguration.kt
- node/src/main/kotlin/net/corda/node/services/network/NetworkMapService.kt
- node/src/test/kotlin/net/corda/node/CordaRPCOpsImplTest.kt
- node/src/test/kotlin/net/corda/node/messaging/InMemoryMessagingTests.kt
- node/src/test/kotlin/net/corda/node/services/NotaryChangeTests.kt
- node/src/test/kotlin/net/corda/node/services/events/ScheduledFlowTests.kt
- node/src/test/kotlin/net/corda/node/services/network/AbstractNetworkMapServiceTest.kt
- node/src/test/kotlin/net/corda/node/services/network/NetworkMapCacheTest.kt
- node/src/test/kotlin/net/corda/node/services/statemachine/FlowFrameworkTests.kt
- node/src/test/kotlin/net/corda/node/services/transactions/NotaryServiceTests.kt
- node/src/test/kotlin/net/corda/node/services/transactions/ValidatingNotaryServiceTests.kt
- samples/network-visualiser/src/main/kotlin/net/corda/netmap/simulation/Simulation.kt
- testing/node-driver/src/integration-test/kotlin/net/corda/testing/FlowStackSnapshotTest.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/driver/Driver.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/MockNode.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/NodeBasedTest.kt
- tools/demobench/src/main/kotlin/net/corda/demobench/model/InstallFactory.kt
- tools/demobench/src/main/kotlin/net/corda/demobench/model/NodeController.kt
The absence or presence of the networkMapService config is what determines if a node is the network map or not.
This is part of my work to remove the adverisedServices config.
> Removed the network map service type as it's no longer needed.

- docs/source/api-index.rst
Ensure that change is reflected in `master` branch as well
> Improve API page wording

- node/src/integration-test/kotlin/net/corda/node/services/AttachmentLoadingTests.kt
- samples/bank-of-corda-demo/src/integration-test/kotlin/net/corda/bank/BankOfCordaRPCClientTest.kt
- samples/bank-of-corda-demo/src/main/kotlin/net/corda/bank/api/BankOfCordaClientApi.kt
- tools/explorer/src/main/kotlin/net/corda/explorer/ExplorerSimulation.kt
> Fixed a few instances of waitUntilNetworkReady() to fix flaky tests.

- core/src/main/kotlin/net/corda/core/messaging/CordaRPCOps.kt
- node/src/main/kotlin/net/corda/node/internal/CordaRPCOpsImpl.kt
Add new function for https://github.com/corda/corda/pull/1744#discussion_r142072757
> CORDA-654: Add CordaRPCOps.notaryPartyFromX500Name

- node/src/test/kotlin/net/corda/node/services/persistence/HibernateConfigurationTest.kt
- testing/test-utils/src/main/kotlin/net/corda/testing/SerializationTestHelpers.kt
Also a unit test fix so that it passes in AMQP mode
> CORDA-540: Allow AMQP switch for storage context

- docs/source/flow-testing.rst
> Removes broken link.

- testing/node-driver/src/main/kotlin/net/corda/testing/driver/Driver.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/MockNode.kt
see https://github.com/corda/cordapp-example/pull/116
> Make cordapp-example java tree buildable

- node/src/test/kotlin/net/corda/node/internal/CordaServiceTest.kt
Fixes a compilation error in master.
> Update to match MockNetwork API change

- gradle-plugins/api-scanner/src/main/java/net/corda/plugins/ScanApi.java
Trivial change that makes the code cleaner. There is no effect on the output.
> Fix filterAnnotationsFor() to return MethodInfo.

- docs/source/api-flows.rst
- docs/source/api-identity.rst
- docs/source/api-transactions.rst
- docs/source/example-code/src/main/java/net/corda/docs/FlowCookbookJava.java
- docs/source/example-code/src/main/kotlin/net/corda/docs/FlowCookbook.kt
Makes the cookbook sections appear by:
- Decreasing dedents
- Changing numbering scheme to avoid clashes ("1" -> "01" to prevent clash with e.g. "10")
> Fixes the API docs.

- docs/source/example-code/src/main/kotlin/net/corda/docs/tutorial/testdsl/TutorialTestDSL.kt
- docs/source/tutorial-contract.rst
- docs/source/tutorial-test-dsl.rst
Mostly nitpick and minor changes:
* Changed wrong reference to `IllegalStateException`; should be `IllegalArgumentException`
* Fixed a couple of "rendering" issues
* Removed redundant `this.` from sample code
> Tutorial Fixes

- docs/source/example-code/src/main/kotlin/net/corda/docs/tutorial/testdsl/TutorialTestDSL.kt
- docs/source/tutorial-contract.rst
- docs/source/tutorial-test-dsl.rst
**Note**: #1823, but documentation changes applied to `release-V1`
Mostly nitpick and minor changes:
* Changed wrong reference to `IllegalStateException`; should be `IllegalArgumentException`
* Fixed a couple of "rendering" issues
* Removed redundant `this.` from sample code
> Tutorial Fixes (#1823)

- docs/source/api-persistence.rst
- docs/source/api-vault-query.rst
Modifies the vault and persistence API pages to have a table of contents
Fixes identation of vault API page code samples
Various other vault API page corrections
> Adds indices, cleans up vault page.

- docs/source/api-identity.rst
> Update docs on how IdentitySyncFlow works

- core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
Removes unnecessary @JVMOverloads annotation.
> Removes unnecessary @JVMOverloads annotation.

- docs/source/changelog.rst
- docs/source/example-code/src/main/kotlin/net/corda/docs/CustomNotaryTutorial.kt
- docs/source/example-code/src/main/kotlin/net/corda/docs/CustomVaultQuery.kt
- docs/source/tutorial-custom-notary.rst
- samples/irs-demo/src/main/kotlin/net/corda/irs/api/NodeInterestRates.kt
- samples/irs-demo/src/test/kotlin/net/corda/irs/api/NodeInterestRatesTest.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/MockServices.kt
Also adds a helper to better support testing CordaService instances with MockService type tests.
> Update code to use AppServiceHub in services

- build.gradle
- constants.properties
- gradle-plugins/publish-utils/src/main/groovy/net/corda/plugins/ProjectPublishExtension.groovy
Why: Because they are annoying.
> Fixed the dozens of artifactory warnings at gradle initialisation.

- core/src/main/kotlin/net/corda/core/crypto/Crypto.kt
- core/src/main/kotlin/net/corda/core/crypto/CryptoUtils.kt
- core/src/main/kotlin/net/corda/core/utilities/EncodingUtils.kt
Also, `PublicKey.toSHA256Bytes()` now uses `.encoded`
> Clean up Crypto 

- core/src/main/kotlin/net/corda/core/node/services/NotaryService.kt
- docs/source/corda-configuration-file.rst
- docs/source/running-the-demos.rst
- docs/source/tutorial-custom-notary.rst
- docs/source/tutorials-index.rst
- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/main/kotlin/net/corda/node/services/config/NodeConfiguration.kt
- samples/bank-of-corda-demo/src/main/kotlin/net/corda/bank/BankOfCordaDriver.kt
- samples/notary-demo/build.gradle
- samples/notary-demo/src/main/kotlin/net/corda/notarydemo/CustomNotaryCordform.kt
- samples/notary-demo/src/main/kotlin/net/corda/notarydemo/MyCustomNotaryService.kt
Converted the custom notary tutorial into a sample. 
This feature is still experimental and the sample is primarily intended for testing and development purposes, so it's not yet mentioned in the demos documentation.
> Fixed AbstractNode to load custom notary services properly

- node/src/main/kotlin/net/corda/node/utilities/CordaPersistence.kt
Allowing to override isolation level on per transaction basis.
> Isolation level per transaction

- samples/bank-of-corda-demo/build.gradle
- samples/irs-demo/build.gradle
- samples/simm-valuation-demo/build.gradle
- samples/trader-demo/build.gradle
When loading finance.jar using cordapps the more generic way is to reference to group id than to hardcoded value
> reference to finance module via not hardcoded group ID

- node/src/integration-test/kotlin/net/corda/test/node/NodeStatePersistenceTests.kt
By ensuring that the nodes are properly started and aware of each other before firing any flows through them.
Also minor refactoring.
> Attempt to make NodeStatePersistenceTests more stable

- node/src/integration-test/kotlin/net/corda/test/node/NodeStatePersistenceTests.kt
The test still proven to be unstable on Windows.
(of course it passes locally when executed in isolation)
More work is needed to establish the root cause.
> Disable unstable test on Windows

- .idea/runConfigurations/BankOfCordaDriverKt___Issue_Web.xml
- .idea/runConfigurations/BankOfCordaDriverKt___Run_Stack.xml
- samples/bank-of-corda-demo/src/main/kotlin/net/corda/bank/BankOfCordaDriver.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/driver/Driver.kt
I was failing due to:
- Unable to locate Notary
- Exception reported due to attachments being missing for Cash
- Set adequate permissions for the nodes such that NodeExplorer can connect
More changes to improve output in debug mode.
> Fixing BankOfCorda demo in `release-V1` branch

- .idea/runConfigurations/BankOfCordaDriverKt___Issue_Web.xml
- .idea/runConfigurations/BankOfCordaDriverKt___Run_Stack.xml
- samples/bank-of-corda-demo/src/main/kotlin/net/corda/bank/BankOfCordaDriver.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/driver/Driver.kt
- Correct permissions used nodes
- Correct port numbers
- Pass "extraCordappPackagesToScan" or else attachment validation will fail
> Fixing Bank-Of-Corda Demo in `master`

- samples/network-visualiser/src/main/kotlin/net/corda/netmap/NetworkMapVisualiser.kt
- samples/network-visualiser/src/main/kotlin/net/corda/netmap/VisualiserViewModel.kt
- samples/network-visualiser/src/main/kotlin/net/corda/netmap/simulation/Simulation.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/MockNode.kt
> CORDA-716 Unpollute MockNode with Simulation-specific code

- gradle-plugins/cordformation/src/main/kotlin/net/corda/plugins/Cordform.kt
- gradle-plugins/cordformation/src/main/kotlin/net/corda/plugins/Cordformation.kt
- gradle-plugins/cordformation/src/main/kotlin/net/corda/plugins/Node.kt
- gradle-plugins/cordformation/src/noderunner/kotlin/net/corda/plugins/NodeRunner.kt
https://r3-cev.atlassian.net/browse/CORDA-728
Everything is quoted, and now works on Mac. Tested trader demo and bank of corda demo
> Mrizzo fix spaces in trader demo

- gradle-plugins/cordformation/src/main/kotlin/net/corda/plugins/Cordform.kt
- gradle-plugins/cordformation/src/main/kotlin/net/corda/plugins/Node.kt
This issue ONLY exhibits itself on the TC build agents.
> CORDA-742 Mrizzo fix capsule error in deploy nodes

- docs/source/_templates/layout.html
- docs/source/_templates/layout_for_doc_website.html
- docs/source/index.rst
Reflection of 617a941c837bae76cd676467db33c4a1be056bc1 on Master.
> Replaces links to Discourse with Stack Overflow links.

- build.gradle
Removing a missed reference to exposed
> Removing exposed reference

- node/src/integration-test/kotlin/net/corda/test/node/NodeStatePersistenceTests.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/driver/Driver.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/MockNode.kt
- verifier/src/integration-test/kotlin/net/corda/verifier/VerifierTests.kt
Part of the post-networkmap node clean-up series.
> Clean up mentions of nodeReady future and friends from MockNetwork/Driver

- tools/demobench/src/test/kotlin/net/corda/demobench/model/NodeControllerTest.kt
> It's not commonName it's organisation

- samples/irs-demo/src/integration-test/kotlin/net/corda/irs/IRSDemoTest.kt
- samples/simm-valuation-demo/src/integration-test/kotlin/net/corda/vega/SimmValuationTest.kt
- testing/test-utils/src/main/kotlin/net/corda/testing/IntegrationTestCategory.kt
useless kdoc, nothing refers to it, can't tell what it does
> CORDA-716 Retire marker interface

- samples/simm-valuation-demo/src/integration-test/kotlin/net/corda/vega/SimmValuationTest.kt
> Remove retired IntegrationTestCategory reference

- core/src/main/kotlin/net/corda/core/flows/CollectSignaturesFlow.kt
- core/src/main/kotlin/net/corda/core/transactions/TransactionWithSignatures.kt
- docs/source/changelog.rst
> Added verifySignaturesExcept which takes in a colleciton of PublicKeys

- core/src/test/java/net/corda/core/flows/SerializationApiInJavaTest.java
- node-api/src/test/java/net/corda/nodeapi/internal/serialization/ForbiddenLambdaSerializationTests.java
- node-api/src/test/java/net/corda/nodeapi/internal/serialization/LambdaCheckpointSerializationTest.java
- node/src/test/java/net/corda/node/services/vault/VaultQueryJavaTests.java
> CORDA-716 Enforce serialization API for Java

- core/src/main/kotlin/net/corda/core/flows/ReceiveTransactionFlow.kt
- samples/irs-demo/build.gradle
Adds a regulator node to the IRS demo, for recording transactions
> Add regulator node to IRS demo

- core/src/test/kotlin/net/corda/core/crypto/PartialMerkleTreeTest.kt
- core/src/test/kotlin/net/corda/core/transactions/TransactionEncumbranceTests.kt
- docs/source/example-code/src/main/java/net/corda/docs/java/tutorial/testdsl/CommercialPaperTest.java
- docs/source/example-code/src/main/kotlin/net/corda/docs/tutorial/testdsl/TutorialTestDSL.kt
- experimental/src/test/kotlin/net/corda/finance/contracts/universal/Cap.kt
- experimental/src/test/kotlin/net/corda/finance/contracts/universal/Caplet.kt
- experimental/src/test/kotlin/net/corda/finance/contracts/universal/FXFwdTimeOption.kt
- experimental/src/test/kotlin/net/corda/finance/contracts/universal/FXSwap.kt
- experimental/src/test/kotlin/net/corda/finance/contracts/universal/IRS.kt
- experimental/src/test/kotlin/net/corda/finance/contracts/universal/RollOutTests.kt
- experimental/src/test/kotlin/net/corda/finance/contracts/universal/Swaption.kt
- experimental/src/test/kotlin/net/corda/finance/contracts/universal/ZeroCouponBond.kt
- finance/src/test/java/net/corda/finance/contracts/asset/CashTestsJava.java
- finance/src/test/kotlin/net/corda/finance/contracts/CommercialPaperTests.kt
- finance/src/test/kotlin/net/corda/finance/contracts/asset/CashTests.kt
- finance/src/test/kotlin/net/corda/finance/contracts/asset/ObligationTests.kt
- node/src/test/kotlin/net/corda/node/messaging/TwoPartyTradeFlowTests.kt
- samples/irs-demo/cordapp/src/test/kotlin/net/corda/irs/contract/IRSTests.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/NodeTestUtils.kt
> CORDA-716 Retire some initialiseSerialization booleans

- node/src/main/kotlin/net/corda/node/services/config/NodeConfiguration.kt
- node/src/main/kotlin/net/corda/node/services/statemachine/StateMachineManagerImpl.kt
- node/src/test/kotlin/net/corda/node/services/config/NodeConfigurationImplTest.kt
Put check for checkpoint checking in a small helper function and test that
> Add helper for checking whether to check checkpoints and unit test it.

- .idea/compiler.xml
- client/rpc/src/main/kotlin/net/corda/client/rpc/internal/KryoClientSerializationScheme.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/AMQPSerializationScheme.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/kryo/DefaultKryoCustomizer.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/kryo/KryoSerializationScheme.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/OverridePKSerializerTest.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializationOutputTests.kt
- node/src/main/kotlin/net/corda/node/serialization/KryoServerSerializationScheme.kt
https://r3-cev.atlassian.net/browse/CORDA-781
Add the code to allow using different implementations of the public key serializer in different scenarios.
> Public key customization hooks

- testing/test-utils/src/main/kotlin/net/corda/testing/Measure.kt
> Don't blow up if a param is anonymous e.g. underscore

- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/main/kotlin/net/corda/node/services/transactions/BFTNonValidatingNotaryService.kt
- node/src/main/kotlin/net/corda/node/services/transactions/BFTSMaRt.kt
- samples/irs-demo/cordapp/src/test/kotlin/net/corda/irs/api/NodeInterestRatesTest.kt
- samples/network-visualiser/src/main/kotlin/net/corda/netmap/simulation/Simulation.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/MockNode.kt
> CORDA-599 Retire findTokenizableService

- testing/node-driver/src/main/kotlin/net/corda/testing/internal/RPCDriver.kt
> Fix RPCStabilityTests.`client doesnt leak threads when it fails to start`

- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/main/kotlin/net/corda/node/internal/StartedNode.kt
- node/src/main/kotlin/net/corda/node/services/transactions/BFTSMaRt.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/MockNode.kt
i broke it in #2036, must have been lucky with the tests
> Fix the BFT startup consensus workaround

- docs/source/release-notes.rst
Raising a PR for comment's and additions. I know @bpaunescu did the security thing so is best placed to add a little comment there and @mikehearn will want to add some stuff about Observer Nodes
Also I'm unclear if we should talk about why V2 and not V1.1 or if the release notes aren't the right place for that or if we're just going to go with it.
> Release - Initial release notes attempt

- .ci/api-current.txt
- core/src/main/kotlin/net/corda/core/messaging/CordaRPCOps.kt
- core/src/main/kotlin/net/corda/core/node/services/AttachmentStorage.kt
- core/src/main/kotlin/net/corda/core/node/services/vault/QueryCriteria.kt
- core/src/main/kotlin/net/corda/core/node/services/vault/QueryCriteriaUtils.kt
- docs/source/changelog.rst
- docs/source/tutorial-attachments.rst
- node/src/main/kotlin/net/corda/node/internal/CordaRPCOpsImpl.kt
- node/src/main/kotlin/net/corda/node/internal/RpcAuthorisationProxy.kt
- node/src/main/kotlin/net/corda/node/services/persistence/NodeAttachmentService.kt
- node/src/main/kotlin/net/corda/node/services/vault/HibernateQueryCriteriaParser.kt
- node/src/test/kotlin/net/corda/node/services/persistence/NodeAttachmentStorageTest.kt
- testing/test-utils/src/main/kotlin/net/corda/testing/node/MockAttachmentStorage.kt
for attachment metadata query.
Decision was made to add this changes to OS version - this is https://github.com/corda/enterprise/pull/55 ported for OS.
@mikehearn please review api-current.txt changes
> AttachmentCriteriaQuery class and infrastructure

- build.gradle
Takes account of the observer node addition in the release of V2.0
> RELEASE - Increment Platform Version Number

- docs/source/node-administration.rst
As titled - more details regarding setting log levels for modules.
> Added some more details regarding setting log levels for individual modules

- core/src/main/kotlin/net/corda/core/internal/ToggleField.kt
- core/src/main/kotlin/net/corda/core/serialization/internal/SerializationEnvironment.kt
- core/src/test/kotlin/net/corda/core/internal/ToggleFieldTest.kt
- node/src/integration-test/kotlin/net/corda/services/messaging/MQSecurityTest.kt
this and rpc connection closure eliminates leak exceptions from integration test logging
> CORDA-716 Don't allow the netty global executor to inherit serialization env holder

- node/src/main/kotlin/net/corda/node/services/transactions/DistributedImmutableMap.kt
- node/src/main/kotlin/net/corda/node/services/transactions/RaftUniquenessProvider.kt
We are storing the Raft indexes with the RaftState in the database to be able to ignore commands with index lower or equal the maximum index during log replay.
Alternatively, we could create a new metadata table and just store the maximum index there.
> Store Raft commit index in DistributedImmutableMap

- node/src/main/kotlin/net/corda/node/services/identity/PersistentIdentityService.kt
- node/src/main/kotlin/net/corda/node/services/persistence/DBCheckpointStorage.kt
- node/src/main/kotlin/net/corda/node/services/persistence/DBTransactionStorage.kt
- node/src/main/kotlin/net/corda/node/services/persistence/NodeAttachmentService.kt
- node/src/main/kotlin/net/corda/node/services/transactions/RaftUniquenessProvider.kt
- node/src/test/kotlin/net/corda/node/services/schema/NodeSchemaServiceTest.kt
* Consistent database column naming convention.
* Remove some column length constraints.
> Consistent database columns naming convention.

- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/main/kotlin/net/corda/node/internal/Node.kt
and clean up after network map team. No jira, just annoying.
> Move class to the only place that uses it

- node/src/main/kotlin/net/corda/node/services/transactions/RaftUniquenessProvider.kt
Monitor the available members of the Raft notary cluster.
> Raft notary cluster: metrics for available members

- core/src/main/kotlin/net/corda/core/utilities/KotlinUtils.kt
- samples/trader-demo/src/main/kotlin/net/corda/traderdemo/TraderDemoClientApi.kt
- samples/trader-demo/src/main/kotlin/net/corda/traderdemo/flow/BuyerFlow.kt
- samples/trader-demo/src/main/kotlin/net/corda/traderdemo/flow/SellerFlow.kt
- Fixed typo in KotlinUtils.kt
- Optimised imports in trader demo
> Typos and optimised imports

- testing/node-driver/src/main/kotlin/net/corda/testing/driver/Driver.kt
> Change default driver permissions such that NodeExplorer works.

- core/src/main/kotlin/net/corda/core/node/services/AttachmentStorage.kt
- node/src/main/kotlin/net/corda/node/internal/cordapp/CordappProviderImpl.kt
- node/src/main/kotlin/net/corda/node/services/persistence/NodeAttachmentService.kt
- node/src/test/kotlin/net/corda/node/CordaRPCOpsImplTest.kt
- testing/test-utils/src/main/kotlin/net/corda/testing/node/MockAttachmentStorage.kt
As found in https://stackoverflow.com/questions/47284059/can-not-get-file-exist-exception-after-corda-1-0
> Added exception if same attachment uploaded. Added test

- .ci/api-current.txt
- client/rpc/src/integration-test/kotlin/net/corda/client/rpc/RPCStabilityTests.kt
- core/src/main/kotlin/net/corda/core/messaging/CordaRPCOps.kt
- core/src/main/kotlin/net/corda/core/node/ServiceHub.kt
- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/main/kotlin/net/corda/node/internal/CordaRPCOpsImpl.kt
- node/src/main/kotlin/net/corda/node/internal/RpcAuthorisationProxy.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/MockServices.kt
> Revert CORDA-296: added rpc that returns an observable for node state

- node/src/main/kotlin/net/corda/node/services/transactions/RaftUniquenessProvider.kt
* Consistent database column naming convention.
> Add explicit column names.

- core/src/test/kotlin/net/corda/core/flows/ReceiveAllFlowTests.kt
- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/main/kotlin/net/corda/node/internal/Node.kt
- node/src/main/kotlin/net/corda/node/services/messaging/Messaging.kt
- node/src/main/kotlin/net/corda/node/services/messaging/NodeMessagingClient.kt
- node/src/main/kotlin/net/corda/node/shell/RPCOpsWithContext.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/InMemoryMessagingNetwork.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/MockNode.kt
> CORDA-716 Call stop on InMemoryMessagingNetwork

- docs/source/corda-networks-index.rst
- docs/source/network-map.rst
Add documentation about the additional-node-infos directory
> docs for additional-node-infos

- build.gradle
- client/rpc/src/smoke-test/java/net/corda/java/rpc/StandaloneCordaRPCJavaClientTest.java
- client/rpc/src/smoke-test/kotlin/net/corda/kotlin/rpc/StandaloneCordaRPClientTest.kt
- constants.properties
- core/src/smoke-test/kotlin/net/corda/core/NodeVersioningTest.kt
- core/src/smoke-test/kotlin/net/corda/core/cordapp/CordappSmokeTest.kt
- node/src/integration-test/kotlin/net/corda/node/BootTests.kt
- node/src/main/kotlin/net/corda/node/services/messaging/Messaging.kt
- node/src/test/kotlin/net/corda/node/services/messaging/ArtemisMessagingTests.kt
- testing/node-driver/src/integration-test/kotlin/net/corda/testing/driver/DriverTests.kt
- testing/smoke-test-utils/src/main/kotlin/net/corda/smoketesting/NodeProcess.kt
- testing/test-common/src/main/kotlin/net/corda/testing/common/internal/ProjectStructure.kt
> Added tests to make sure the platform version is correctly available

- node/src/integration-test/kotlin/net/corda/node/services/network/NetworkMapClientTest.kt
- node/src/main/kotlin/net/corda/node/internal/Node.kt
- node/src/main/kotlin/net/corda/node/services/network/PersistentNetworkMapCache.kt
- node/src/test/kotlin/net/corda/node/services/network/NetworkMapClientTest.kt
- testing/node-driver/build.gradle
- testing/node-driver/src/integration-test/kotlin/net/corda/testing/driver/DriverTests.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/driver/Driver.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/internal/RPCDriver.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/network/NetworkMapServer.kt
- verifier/src/integration-test/kotlin/net/corda/verifier/VerifierDriver.kt
* make node info file copying optional by setting "compatabilityZoneURL" in driver
* integration test for node using http network map with driver
* some bug fixes
> Integration test for http network map service

- core/src/test/kotlin/net/corda/core/flows/ReceiveAllFlowTests.kt
Given that people routinely ask, and we have no example of this in our tests, this is how to register flows dynamically in order to construct meaningful tests.
> Showcase of closures registered as flows.

- client/rpc/src/smoke-test/java/net/corda/java/rpc/StandaloneCordaRPCJavaClientTest.java
- config/dev/generalnodea.conf
- docs/source/deploying-a-node.rst
- docs/source/example-code/src/main/resources/example-node.conf
- docs/source/setting-up-a-corda-network.rst
- gradle-plugins/cordformation/src/main/kotlin/net/corda/plugins/Node.kt
- testing/smoke-test-utils/src/main/kotlin/net/corda/smoketesting/NodeConfig.kt
> Removed remaining references to networkMapService

- node/src/main/kotlin/net/corda/node/Corda.kt
- node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt
- node/src/main/kotlin/net/corda/node/utilities/registration/NetworkRegistrationHelper.kt
remove all the calls to exitProcess in NodeStartup.kt  and move them up to Corda.kt
> remove calls to exitnodes from NodeStartup

- node/src/integration-test/kotlin/net/corda/node/NodeKeystoreCheckTest.kt
fix broken test due to some class renaming from other PR.
> Fix broken NodeKeystoreCheckTest

- node/src/test/kotlin/net/corda/node/utilities/TLSAuthenticationTests.kt
TLS unit tests for mixed R1 - K1 - RSA client and CA settings.
> TLS supports K1 and mixed K1-R1-RSA

- docs/source/api-contract-constraints.rst
- docs/source/example-code/build.gradle
- docs/source/example-code/src/main/java/com/template/TemplateContract.java
- docs/source/example-code/src/main/java/net/corda/docs/java/tutorial/helloworld/IOUFlow.java
- docs/source/example-code/src/main/java/net/corda/docs/java/tutorial/helloworld/IOUState.java
- docs/source/example-code/src/main/java/net/corda/docs/java/tutorial/twoparty/IOUContract.java
- docs/source/example-code/src/main/java/net/corda/docs/java/tutorial/twoparty/IOUFlow.java
- docs/source/example-code/src/main/java/net/corda/docs/java/tutorial/twoparty/IOUFlowResponder.java
- docs/source/example-code/src/main/kotlin/net/corda/docs/tutorial/helloworld/flow.kt
- docs/source/example-code/src/main/kotlin/net/corda/docs/tutorial/helloworld/state.kt
- docs/source/example-code/src/main/kotlin/net/corda/docs/tutorial/twoparty/contract.kt
- docs/source/example-code/src/main/kotlin/net/corda/docs/tutorial/twoparty/flow.kt
- docs/source/example-code/src/main/kotlin/net/corda/docs/tutorial/twoparty/flowResponder.kt
- docs/source/hello-world-flow.rst
- docs/source/hello-world-running.rst
- docs/source/hello-world-state.rst
- docs/source/hello-world-template.rst
- docs/source/tut-two-party-contract.rst
- docs/source/tut-two-party-flow.rst
* Updates tutorial to make imports to be added clearer, and to reflect new repo structure.
* Adds links to the solution repos for tut 1.
* Further fixes based on dry-run.
> Updates tutorials (general fixes, link to solutions repos)

- testing/node-driver/src/integration-test/kotlin/net/corda/testing/node/FlowStackSnapshotTest.kt
Adding comment explaining test design.
> Adding comment to test

- samples/notary-demo/src/main/kotlin/net/corda/notarydemo/flows/DummyIssueAndMove.kt
> Corda-862 - Fix notary demo for AMQP

- node-api/src/main/kotlin/net/corda/nodeapi/internal/NetworkParametersGenerator.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/network/NetworkMapServer.kt
- testing/test-common/src/main/kotlin/net/corda/testing/common/internal/ParametersUtilities.kt
- testing/test-utils/src/main/kotlin/net/corda/testing/TestConstants.kt
- tools/demobench/src/main/kotlin/net/corda/demobench/model/NodeController.kt
Fix after after artemis version change v2.4 -> v2.1.
> Fix LargeTransactionTest

- node/src/integration-test/kotlin/net/corda/node/services/BFTNotaryServiceTests.kt
BFTNotaryServiceTests.kt - instantiate MockServices before each test, not at the class level (align to Enterprise repo).
> Refactor BFTNotaryServiceTests setup.

- docs/source/cordapp-build-systems.rst
Mirror of ff8d0881b3e72b8a7607544ecf155292c127fbe1.
> Improves CorDapp dependency docs.

- docs/source/shell.rst
* Reorganisation
* More examples
* Clearer SSH instructions
> Improvements to the shell docs.

- docs/source/shell.rst
Mirror of 5a50f564c958c5acaf39f0f0b78a4c550bd53d7d. SSH docs removed as SSH shell not present in V2.
> Mirrors changes to shell docs.

- core/src/main/kotlin/net/corda/core/flows/FlowLogicRef.kt
- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/main/kotlin/net/corda/node/internal/CordaClock.kt
- node/src/main/kotlin/net/corda/node/internal/Node.kt
- node/src/main/kotlin/net/corda/node/services/api/ServiceHubInternal.kt
- node/src/main/kotlin/net/corda/node/services/events/NodeSchedulerService.kt
- node/src/main/kotlin/net/corda/node/services/events/ScheduledActivityObserver.kt
- node/src/main/kotlin/net/corda/node/services/statemachine/FlowLogicRefFactoryImpl.kt
- node/src/test/java/net/corda/node/services/events/FlowLogicRefFromJavaTest.java
- node/src/test/kotlin/net/corda/node/services/events/FlowLogicRefTest.kt
- node/src/test/kotlin/net/corda/node/services/events/NodeSchedulerServiceTest.kt
- node/src/test/kotlin/net/corda/node/utilities/ClockUtilsTest.kt
refactoring parts of #2273 spun off as instructed by review
> CORDA-891 Refactoring for #2273

- samples/simm-valuation-demo/README.md
Restored SIMM documentation to README file
> Restoring apparently missing SIMM demo documentation

- docs/source/hello-world-running.rst
> Fixes a broken link to the shell page.

- docs/source/serialization.rst
> CORDA-902 - Serialization documentation

- core/src/main/kotlin/net/corda/core/utilities/ByteArrays.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/custom/OpaqueBytesSubSequenceSerializer.kt
Already approved by Shams and merged elsewhere
> Backport of ENT-1303 applied to 3.0-RC3

- node/src/main/kotlin/net/corda/node/internal/security/RPCSecurityManagerImpl.kt
> Close Hikari connection pool around external auth database (RPCSecurityManagerImpl.kt)

- node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/CordaPersistence.kt
- node/src/integration-test/kotlin/net/corda/node/AuthDBTests.kt
- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/main/kotlin/net/corda/node/internal/DataSourceFactory.kt
- node/src/main/kotlin/net/corda/node/internal/security/RPCSecurityManagerImpl.kt
- node/src/test/kotlin/net/corda/node/internal/AbstractNodeTests.kt
- testing/test-common/src/main/kotlin/net/corda/testing/common/internal/Thoroughness.kt
* c09a5d4: the fix
* 3ce5436: another fix, turns out it wasn't significant
* c049bdc: don't drop exceptions
> CORDA-924 Fix IntegrationTestingTutorial

- gradle-plugins/cordformation/src/main/kotlin/net/corda/plugins/Cordformation.kt
- gradle-plugins/cordformation/src/main/kotlin/net/corda/plugins/Node.kt
Changes already applied as part of R3C 3.0 Developer Preview.
Duplicate PR of https://github.com/corda/enterprise/pull/304
> Back-ported fix for Jolokia version defaulting.

- config/dev/generalnodea.conf
- config/dev/generalnodeb.conf
- config/dev/nameservernode.conf
- docs/source/corda-configuration-file.rst
- docs/source/deploying-a-node.rst
- docs/source/example-code/src/main/resources/example-network-map-node.conf
- docs/source/example-code/src/main/resources/example-node.conf
- node/src/main/kotlin/net/corda/node/services/config/NodeConfiguration.kt
- node/src/main/resources/reference.conf
- node/src/test/kotlin/net/corda/node/services/config/NodeConfigurationImplTest.kt
- samples/irs-demo/src/integration-test/kotlin/net/corda/test/spring/SpringDriver.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/driver/Driver.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/DriverDSLImpl.kt
It's still expected to be present in node.conf if the web server needs to use SSL.
> Removed useHTTPS from NodeConfiguration as it's not needed by the node.

- docs/source/aws-vm.rst
- docs/source/tools-index.rst
A guide for deploying the Corda AMI available in the AWS marketplace
> AWS marketplace getting started docs

- gradle-plugins/cordformation/src/main/kotlin/net/corda/plugins/Cordformation.kt
- gradle-plugins/cordformation/src/main/kotlin/net/corda/plugins/Node.kt
> Backported Jolokia fix.

- node/src/main/kotlin/net/corda/node/services/transactions/DistributedImmutableMap.kt
This reverts commit cf33be66fffa5d547b6d2370d8dbf0fe4121d714.
> Revert "Raft Notary: remove snapshotting"

- samples/irs-demo/build.gradle
- samples/irs-demo/cordapp/build.gradle
- samples/irs-demo/cordapp/src/main/kotlin/net/corda/irs/flows/AutoOfferFlow.kt
- samples/irs-demo/cordapp/src/test/kotlin/net/corda/irs/Main.kt
- samples/irs-demo/src/integration-test/kotlin/net/corda/irs/IRSDemoTest.kt
- samples/irs-demo/web/build.gradle
This example code was run as part of the IRS demo
The failure was intermittent because it's run on a codepath that may not notify the initiating flow in time.
> Fix non-visible IRS demo bug

- core/src/main/kotlin/net/corda/core/identity/CordaX500Name.kt
- core/src/main/kotlin/net/corda/core/internal/LegalNameValidator.kt
- core/src/test/kotlin/net/corda/core/internal/LegalNameValidatorTest.kt
- docs/source/changelog.rst
- docs/source/generating-a-node.rst
https://github.com/corda/corda/issues/2326
> Remove word restriction in corda x500 name

- .gitignore
- build.gradle
> Added option to enable docs only builds if a specific file is present

- constants.properties
- gradle-plugins/publish-utils/src/main/groovy/net/corda/plugins/PublishTasks.groovy
Extra logging and documentation to clarify an unexpected and previous undocumented behaviour.
>  Added documentation and extra logging to publish tasks

- node/src/main/kotlin/net/corda/node/services/network/NetworkMapClient.kt
- node/src/main/kotlin/net/corda/node/utilities/registration/HTTPNetworkRegistrationService.kt
- node/src/main/kotlin/net/corda/node/utilities/registration/NetworkRegistrationHelper.kt
- node/src/main/kotlin/net/corda/node/utilities/registration/NetworkRegistrationService.kt
- node/src/test/kotlin/net/corda/node/utilities/registration/NetworkRegistrationHelperTest.kt
https://r3-cev.atlassian.net/browse/CORDA-923
> set network registration poll interval via http cache control header

- .ci/api-current.txt
Add new APIs, in prep for changing some of the invocationContext API (it wasn't released so that'll be OK).
> Refresh API/ABI definition file

- core/src/main/kotlin/net/corda/core/contracts/ContractState.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/AMQPPrimitiveSerializer.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/AMQPSerializer.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/ArraySerializer.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/CollectionSerializer.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/CorDappCustomSerializer.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/CustomSerializer.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/DeserializationInput.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/EnumEvolutionSerializer.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/EnumSerializer.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/EvolutionSerializer.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/MapSerializer.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/ObjectSerializer.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/PropertySerializer.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/Schema.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializationHelper.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializationOutput.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializerFactory.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/SingletonSerializer.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/carpenter/AMQPSchemaExtensions.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/EvolvabilityTests.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/GenericsTests.kt
Backport from master - https://github.com/corda/corda/pull/2440
> CORDA-943 - Deterministic serialization order breaks object ref cache

- .ci/api-current.txt
- client/jfx/src/integration-test/kotlin/net/corda/client/jfx/NodeMonitorModelTest.kt
- client/rpc/src/integration-test/kotlin/net/corda/client/rpc/CordaRPCClientTest.kt
- core/src/main/kotlin/net/corda/core/context/AuthServiceId.kt
- core/src/main/kotlin/net/corda/core/context/InvocationContext.kt
- core/src/main/kotlin/net/corda/core/flows/FlowInitiator.kt
- core/src/main/kotlin/net/corda/core/flows/FlowLogic.kt
- core/src/main/kotlin/net/corda/core/messaging/CordaRPCOps.kt
- node/src/main/kotlin/net/corda/node/internal/CordaRPCOpsImpl.kt
- node/src/main/kotlin/net/corda/node/services/events/NodeSchedulerService.kt
- node/src/main/kotlin/net/corda/node/shell/FlowWatchPrintingSubscriber.kt
- node/src/test/kotlin/net/corda/node/internal/CordaServiceTest.kt
- node/src/test/kotlin/net/corda/node/services/events/ScheduledFlowTests.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/NodeTestUtils.kt
Mostly this removes a lot of deprecation warnings.
> Tweak the way invocation context is integrated to reduce the pain for devs using the old API

- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/CordaClassResolver.kt
Kotlin's own reflection has a habit of throwing weird errors and does not work for private objects - thus the unit test which tests this feature has actually never worked properly, but somehow works by accident. An attempt to upgrade to the latest Kotlin revealed the issue so it must have always been unstable.
> Use Java reflection for determining if a type is a Kotlin singleton.

- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializationHelper.kt
- node-api/src/test/java/net/corda/nodeapi/internal/serialization/amqp/JavaPrivatePropertyTests.java
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/GenericsTests.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/PrivatePropertyTests.kt
Removes a lib dependency for a small use case
> CORDA-915 - Replace BEANS introspector with standard reflection

- build.gradle
This is the pre-release branch
> CORDA-976 - V3.0 release version bump

- node/src/main/kotlin/net/corda/node/services/network/NetworkMapClient.kt
- node/src/main/kotlin/net/corda/node/utilities/registration/HTTPNetworkRegistrationService.kt
- node/src/main/kotlin/net/corda/node/utilities/registration/NetworkRegistrationHelper.kt
- node/src/main/kotlin/net/corda/node/utilities/registration/NetworkRegistrationService.kt
- node/src/test/kotlin/net/corda/node/utilities/registration/NetworkRegistrationHelperTest.kt
https://github.com/corda/corda/pull/2445
> [CORDA-923] - CSR polling interval to be specified in HTTP header.

- node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt
- node/src/main/kotlin/net/corda/node/services/config/NodeConfiguration.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/DriverDSLImpl.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/NodeBasedTest.kt
Merged PR link: https://github.com/corda/corda/pull/2433
Jira link: https://r3-cev.atlassian.net/browse/CORDA-988
> Added basic node configuration validation.

- node/src/main/kotlin/net/corda/node/services/persistence/DBTransactionMappingStorage.kt
Mirror PR of approved https://github.com/corda/corda/pull/2457
Customer expecting fix in Corda 3.0
> CORDA-977 PK constraint violation when up adding Mapping to DBTransactionMapping store

- build.gradle
- client/jackson/build.gradle
- constants.properties
- samples/irs-demo/build.gradle
- samples/irs-demo/web/build.gradle
- samples/network-visualiser/build.gradle
I did that thing I'm good for these days ;)
> Upgrade Kotlin to 1.2.20

- docs/source/changelog.rst
- testing/node-driver/src/main/kotlin/net/corda/testing/node/NodeTestUtils.kt
As requested in [https://github.com/corda/corda/pull/2476](https://github.com/corda/corda/pull/2476)
> CORDA-939 Adding documentation changes requested from v3 release branch PR

- .ci/api-current.txt
- core/src/main/kotlin/net/corda/core/contracts/Attachment.kt
- core/src/main/kotlin/net/corda/core/internal/AbstractAttachment.kt
- core/src/main/kotlin/net/corda/core/internal/GlobalProperties.kt
- core/src/main/kotlin/net/corda/core/internal/NodeProperties.kt
- core/src/main/kotlin/net/corda/core/node/NetworkParameters.kt
- core/src/main/kotlin/net/corda/core/transactions/WireTransaction.kt
- core/src/test/kotlin/net/corda/core/contracts/StructuresTests.kt
- core/src/test/kotlin/net/corda/core/serialization/AttachmentSerializationTest.kt
- docs/source/changelog.rst
- docs/source/network-map.rst
- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/main/kotlin/net/corda/node/internal/Node.kt
- node/src/test/kotlin/net/corda/node/services/transactions/MaxTransactionSizeTests.kt
- samples/irs-demo/src/integration-test/kotlin/net/corda/test/spring/SpringDriver.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/driver/Driver.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/MockNode.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/MockServices.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/NodeTestUtils.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/DriverDSLImpl.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/RPCDriver.kt
- testing/test-common/src/main/kotlin/net/corda/testing/common/internal/ParametersUtilities.kt
- tools/demobench/src/main/kotlin/net/corda/demobench/model/NodeController.kt
- verifier/src/integration-test/kotlin/net/corda/verifier/VerifierDriver.kt
> CORDA-961 Wire up and enforce max transaction size

- core/src/main/kotlin/net/corda/core/internal/InternalUtils.kt
- core/src/main/kotlin/net/corda/core/messaging/CordaRPCOps.kt
- core/src/main/kotlin/net/corda/core/node/NetworkParameters.kt
- core/src/main/kotlin/net/corda/core/node/services/NetworkMapCache.kt
- docs/source/network-map.rst
- node-api/src/main/kotlin/net/corda/nodeapi/internal/SignedNodeInfo.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/crypto/X509Utilities.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/network/NetworkBootstrapper.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/network/NetworkMap.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/network/NetworkParametersCopier.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/EvolvabilityTests.kt
- node/src/integration-test/kotlin/net/corda/node/services/BFTNotaryServiceTests.kt
- node/src/integration-test/kotlin/net/corda/node/services/network/NetworkMapTest.kt
- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/main/kotlin/net/corda/node/internal/CordaRPCOpsImpl.kt
- node/src/main/kotlin/net/corda/node/internal/NetworkParametersReader.kt
- node/src/main/kotlin/net/corda/node/internal/RpcAuthorisationProxy.kt
- node/src/main/kotlin/net/corda/node/services/api/ServiceHubInternal.kt
- node/src/main/kotlin/net/corda/node/services/network/NetworkMapClient.kt
- node/src/main/kotlin/net/corda/node/services/network/PersistentNetworkMapCache.kt
- node/src/test/kotlin/net/corda/node/internal/NetworkParametersTest.kt
- node/src/test/kotlin/net/corda/node/services/network/NetworkMapClientTest.kt
- node/src/test/kotlin/net/corda/node/services/network/NetworkMapUpdaterTest.kt
- node/src/test/kotlin/net/corda/node/services/network/NetworkParametersReaderTest.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/MockNode.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/DriverDSLImpl.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/network/NetworkMapServer.kt
- testing/test-common/src/main/kotlin/net/corda/testing/common/internal/ParametersUtilities.kt
- tools/demobench/src/main/kotlin/net/corda/demobench/model/NodeController.kt
https://github.com/corda/corda/pull/2412 Bon appetit!
> CORDA-952 Updates of network parameters OS client part 

- .ci/api-current.txt
- core/src/main/kotlin/net/corda/core/contracts/Attachment.kt
- core/src/main/kotlin/net/corda/core/internal/AbstractAttachment.kt
- core/src/main/kotlin/net/corda/core/internal/GlobalProperties.kt
- core/src/main/kotlin/net/corda/core/node/NetworkParameters.kt
- core/src/main/kotlin/net/corda/core/transactions/WireTransaction.kt
- core/src/test/kotlin/net/corda/core/contracts/StructuresTests.kt
- core/src/test/kotlin/net/corda/core/serialization/AttachmentSerializationTest.kt
- docs/source/changelog.rst
- docs/source/network-map.rst
- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/main/kotlin/net/corda/node/internal/Node.kt
- node/src/test/kotlin/net/corda/node/services/transactions/MaxTransactionSizeTests.kt
- samples/irs-demo/src/integration-test/kotlin/net/corda/test/spring/SpringDriver.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/driver/Driver.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/MockNode.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/MockServices.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/NodeTestUtils.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/DriverDSLImpl.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/RPCDriver.kt
- testing/test-common/src/main/kotlin/net/corda/testing/common/internal/ParametersUtilities.kt
- tools/demobench/src/main/kotlin/net/corda/demobench/model/NodeController.kt
- verifier/src/integration-test/kotlin/net/corda/verifier/VerifierDriver.kt
* wire up and enforce max transaction size
* fixup after rebase
moved network parameter from AbstractNode to NodeProperties
* removed TODO
* fix broken import
* address PR issues
* remove API breaking change
address PR issue
* added max transaction size to driver and mock network.
address PR issues
* fix failing test
* added TODO
* fix verifier test
* fix spring driver build error
(cherry picked from commit c8cf46c)
> CORDA-961 Wire up and enforce max transaction size (#2465)

- node/src/main/kotlin/net/corda/node/utilities/AppendOnlyPersistentMap.kt
- node/src/test/kotlin/net/corda/node/services/persistence/DBTransactionStorageTests.kt
Backport of https://github.com/corda/corda/pull/2498
> CORDA-1003

- build.gradle
So we can tune this setting using CI parameters
> Allows configuring maxParallelForks as system property

- docs/source/changelog.rst
- tools/scripts/upgrade-test-packages.sh
> CORDA-716 - Update changelog for test package changes and provide upgrade script

- core/src/main/kotlin/net/corda/core/crypto/Crypto.kt
- core/src/main/kotlin/net/corda/core/crypto/PartialMerkleTree.kt
- core/src/main/kotlin/net/corda/core/crypto/SignableData.kt
- core/src/main/kotlin/net/corda/core/crypto/TransactionSignature.kt
- core/src/main/kotlin/net/corda/core/node/services/NotaryService.kt
- core/src/test/kotlin/net/corda/core/crypto/TransactionSignatureTest.kt
from [master-2488](https://github.com/corda/corda/pull/2488)
> CORDA-967 Allow multi-tx signature verification

- core/src/main/kotlin/net/corda/core/flows/NotaryFlow.kt
This is needed for implementing a health check flow for notaries
> Make NotaryFlow.Client more modular and easier to customise

- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializationHelper.kt
- node-api/src/test/java/net/corda/nodeapi/internal/serialization/amqp/JavaSerializationOutputTests.java
backport of https://github.com/corda/corda/pull/2532
> CORDA-1032 - unnamed ctor param serialization issue

- docs/source/changelog.rst
- tools/scripts/upgrade-test-packages.ps1
> CORDA-1011 Add powershell script to update testing package imports

- docs/source/serialization.rst
Give an example of how to over come an issue @adagys was having
> DOCS: update AMQP serialization

- docs/source/serialization.rst
Master PR: https://github.com/corda/corda/pull/2543
> DOCS: AMQP Serialization "gotcha"

- docs/source/api-transactions.rst
- docs/source/example-code/src/main/java/net/corda/docs/FlowCookbookJava.java
- docs/source/example-code/src/main/kotlin/net/corda/docs/FlowCookbook.kt
From [PR 2546](https://github.com/corda/corda/pull/2546)
> CORDA-1038 v3.0 docs fix: TransactionWithSignatures

- node-api/src/main/kotlin/net/corda/nodeapi/internal/ArtemisMessagingClient.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/bridging/AMQPBridgeManager.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/bridging/BridgeControlListener.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/protonwrapper/netty/AMQPChannelHandler.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/protonwrapper/netty/AMQPServer.kt
- node/src/main/kotlin/net/corda/node/internal/Node.kt
These changes allow hooks for more complicated HA and out of process interactions with Artemis and with the bridge control protocol.
> CORDA-1065: Enhance the pluggability of the bridging and messaging code

- samples/irs-demo/cordapp/build.gradle
This fixes the port clash that was on port 10010 by bumping the regulator ports up by 1.
> The IRS demo has a clash between web server ports and the regulator node

- samples/irs-demo/cordapp/build.gradle
Port 10010 had a conflict for the regulator node. Bump the ports on by one to fix.
> Fix clash on ports for IRS demo

- .ci/api-current.txt
- core/src/main/kotlin/net/corda/core/flows/NotarisationRequest.kt
- core/src/main/kotlin/net/corda/core/flows/NotaryFlow.kt
- core/src/main/kotlin/net/corda/core/flows/SendTransactionFlow.kt
- core/src/main/kotlin/net/corda/core/internal/InternalUtils.kt
- core/src/main/kotlin/net/corda/core/node/services/NotaryService.kt
- core/src/main/kotlin/net/corda/core/transactions/BaseTransactions.kt
- node/src/main/kotlin/net/corda/node/services/transactions/BFTNonValidatingNotaryService.kt
- node/src/main/kotlin/net/corda/node/services/transactions/BFTSMaRt.kt
- node/src/main/kotlin/net/corda/node/services/transactions/NonValidatingNotaryFlow.kt
- node/src/main/kotlin/net/corda/node/services/transactions/ValidatingNotaryFlow.kt
- node/src/test/kotlin/net/corda/node/services/transactions/NotaryServiceTests.kt
- samples/notary-demo/src/main/kotlin/net/corda/notarydemo/MyCustomNotaryService.kt
> CORDA-1010: Send a request signature in addition to a transaction to the notary

- node/src/main/kotlin/net/corda/node/services/messaging/RPCServer.kt
This was left in from a debugging session
> Remove spurious logline

- docs/source/example-code/src/test/kotlin/net/corda/docs/FxTransactionBuildTutorialTest.kt
- testing/node-driver/src/integration-test/kotlin/net/corda/testing/driver/DriverTests.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/DriverDSLImpl.kt
Port of https://github.com/corda/corda/pull/2574.
> [CORDA-1059]: Fix Driver hanging on duplicate node names.

- docs/source/api-contract-constraints.rst
- docs/source/network-map.rst
- docs/source/upgrading-cordapps.rst
- docs/source/writing-a-cordapp.rst
This PR includes docs for contract constraints (Tudor/Michele's work), some more on contract upgrades, some network map doc improvements and some more discussion of flow drains.
> Bring doc improvements for v3 across from master

- client/rpc/src/integration-test/kotlin/net/corda/client/rpc/RPCStabilityTests.kt
- client/rpc/src/main/kotlin/net/corda/client/rpc/internal/RPCClient.kt
- client/rpc/src/main/kotlin/net/corda/client/rpc/internal/RPCClientProxyHandler.kt
- client/rpc/src/test/kotlin/net/corda/client/rpc/RPCPerformanceTests.kt
- node-api/src/main/kotlin/net/corda/nodeapi/RPCApi.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/DeduplicationChecker.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/CordaPersistence.kt
- node/src/main/kotlin/net/corda/node/services/messaging/RPCServer.kt
V3 of https://github.com/corda/corda/pull/2477
> CORDA-984: Add RPC deduplication to client and server

- testing/node-driver/src/main/kotlin/net/corda/testing/node/MockNetwork.kt
This fixes MaxTransactionSizeTests
> Pass network params to InternalMockNetwork

- node/src/main/resources/reference.conf
- webserver/src/main/kotlin/net/corda/webserver/WebServerConfig.kt
> Remove remaining occurrences of `exportJMXto` 

- .idea/compiler.xml
- build.gradle
- docs/source/example-code/build.gradle
- node/src/main/kotlin/net/corda/node/services/config/NodeConfiguration.kt
- node/src/test/kotlin/net/corda/node/services/transactions/MaxTransactionSizeTests.kt
Port of https://github.com/corda/corda/pull/2592.
> [CORDA-1089]: Ensure graceful error message is shown on node startup if RPC settings are invalid.

- node/src/main/kotlin/net/corda/node/services/persistence/NodePropertiesPersistentStore.kt
Alter column names to be consistent with R3.Corda.
> Alter column names to be consistent with R3.Corda.

- build.gradle
- node/src/main/java/net/corda/node/shell/RunShellCommand.java
Cosmetic, 'bye' and 'exit' in shell's 'help'.
> [CORDA-1075]: Add 'bye' and 'exit' commands to Shell.

- docs/source/api-testing.rst
- docs/source/conf.py
- docs/source/corda-api.rst
- docs/source/example-code/src/test/java/net/corda/docs/java/tutorial/testdsl/CommercialPaperTest.java
- docs/source/example-code/src/test/kotlin/net/corda/docs/tutorial/testdsl/TutorialTestDSL.kt
@anthonykr3 is going to add to these by creating contract testing docs.
> [CORDA-1035] Flow test API docs

- .ci/api-current.txt
- core/src/main/kotlin/net/corda/core/flows/FlowLogic.kt
- core/src/test/kotlin/net/corda/core/flows/FlowTestsUtils.kt
- docs/source/api-flows.rst
- docs/source/example-code/src/main/kotlin/net/corda/docs/FlowCookbook.kt
Backport of https://github.com/corda/corda/pull/2597
> CORDA-1043

- node/src/integration-test/kotlin/net/corda/node/modes/draining/P2PFlowsDrainingModeTest.kt
- node/src/main/kotlin/net/corda/node/services/messaging/P2PMessagingClient.kt
Port from master: https://github.com/corda/corda/pull/2613
> [CORDA-1098]: Fixed Artemis filters for flows draining mode.

- build.gradle
Switch from M18-HC02 to M18-RC01
> RELEASE: Bump release version for RC

- docs/source/api-flows.rst
- finance/src/main/kotlin/net/corda/finance/contracts/asset/cash/selection/AbstractCashSelection.kt
> CORDA-1040 docs for FlowLogic.sleep

- node/src/test/kotlin/net/corda/node/ArgsParserTest.kt
The `ArgsParserTest` creates a temporary truststore in the `node` directory and does not delete it afterwards. It also checks whether this truststore already exists and fails if it does! This means that the test cannot be run twice, and running `gradlew clean` cannot fix it.
Fix the test by:
- Creating the truststore in the `build` directory so that `clean` can delete it.
- Ensure that it deletes the truststore anyway via a `try...finally` block.
> [ENT-1552] Delete temporary truststore once the test is complete. (#484)

- docs/source/api-flows.rst
- finance/src/main/kotlin/net/corda/finance/contracts/asset/cash/selection/AbstractCashSelection.kt
(cherry picked from commit 2da28c5)
master PR https://github.com/corda/corda/pull/2625 already merged.
> CORDA-1040 docs for FlowLogic.sleep (#2625)

- node/src/main/kotlin/net/corda/node/services/transactions/BFTSMaRt.kt
> [CORDA-1119] Sign in DB transaction

- node/src/main/kotlin/net/corda/node/services/messaging/RPCServer.kt
> Fix rpc sender thread busy looping

- testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/ProcessUtilities.kt
Cherry picked from https://github.com/corda/corda/pull/2652
> [CORDA-1116] Move classpath to system variable

- node-api/src/main/kotlin/net/corda/nodeapi/internal/ClassloaderUtils.kt
Fixes CORDA-1113, cherry picked from https://github.com/corda/corda/pull/2650
> [CORDA-1113] Close classloader

- samples/irs-demo/README.md
- samples/irs-demo/web/src/test/resources/scripts/runwebapps.bat
* [CORDA-1102](https://r3-cev.atlassian.net/browse/CORDA-1102) - Fix demo instructions for Windows
* [CORDA-1103](https://r3-cev.atlassian.net/browse/CORDA-1103) - Fix web app start-up script for Windows
> CORDA-1102 / CORDA-1103 - Fix IRS Demo on Windows

- tools/explorer/README.md
- tools/explorer/src/main/kotlin/net/corda/explorer/Main.kt
> [CORDA-1127] Updated readme/comments to follow current rpc ports

- docs/source/network-map.rst
- docs/source/setting-up-a-corda-network.rst
https://r3-cev.atlassian.net/browse/CORDA-1050
> CORDA-1050 docs on whitelisting CorDapps

- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializationHelper.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/PrivatePropertyTests.kt
Backport of https://github.com/corda/corda/pull/2692
Whilst it does currently work it only does so by going down an incorrect
code path. A property THING that is public and has a getter should
be fetched using that getter, not trip into the private property
accessor.
> CORDA-1134 - Don't use private serializers for all CAPS properties

- .ci/api-current.txt
- core/src/main/kotlin/net/corda/core/CordaInternal.kt
- core/src/main/kotlin/net/corda/core/flows/FlowLogicRef.kt
- node/src/main/kotlin/net/corda/node/services/statemachine/FlowLogicRefFactoryImpl.kt
Cherrypick from master
* Fix another non-serializable exception, add docs, fix a possible security issue.
* Update API definition to reflect methods added to make more exceptions serializable
> Fix another non-serializable exception, add docs, fix a possible security issue.

- docs/source/event-scheduling.rst
- docs/source/oracles.rst
- docs/source/tutorial-tear-offs.rst
A refactor seems to have broken the links.  This fixes all the links I found in `rst` files.
> CORDA-1144 Fix documentation that refers to IRS demo code

- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/Schema.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializationHelper.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializerFactory.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializationOutputTests.kt
- samples/simm-valuation-demo/src/main/kotlin/net/corda/vega/flows/SimmFlow.kt
Backport from master - https://github.com/corda/corda/pull/2665
> CORDA-1115 - Cannot serialize private nested objects

- docs/source/network-map.rst
(cherry picked from commit 067c9fb)
> CORDA-1082: Add doc for --just-generate-node-info (#2719)

- .idea/compiler.xml
- client/rpc/src/smoke-test/java/net/corda/java/rpc/StandaloneCordaRPCJavaClientTest.java
- client/rpc/src/smoke-test/kotlin/net/corda/kotlin/rpc/StandaloneCordaRPClientTest.kt
- core/src/smoke-test/kotlin/net/corda/core/NodeVersioningTest.kt
- core/src/smoke-test/kotlin/net/corda/core/cordapp/CordappSmokeTest.kt
- testing/smoke-test-utils/src/main/kotlin/net/corda/smoketesting/NodeConfig.kt
> Fixing smoke tests after config parsing changes [CORDA-926]

- node-api/src/main/kotlin/net/corda/nodeapi/internal/network/NetworkBootstrapper.kt
https://r3-cev.atlassian.net/browse/CORDA-1150
> CORDA-1150 better log messages

- build.gradle
- samples/irs-demo/README.md
- samples/irs-demo/build.gradle
- samples/irs-demo/src/system-test/kotlin/IRSDemoDockerTest.kt
Switch to in-house fork of docker-compose-rule, so it works on default Windows
> [Corda-1137] Docker/docker-compose on Windows

- .ci/api-current.txt
- build.gradle
- constants.properties
Include `vararg` methods and order class/interface/method annotations.
> Fix public API definition for Gradle Plugin 4.0.4

- core/src/main/kotlin/net/corda/core/utilities/ProgressTracker.kt
https://r3-cev.atlassian.net/browse/CORDA-1147
> Fix Shell 

- build.gradle
- node/build.gradle
- node/src/main/kotlin/net/corda/node/shell/InteractiveShell.kt
https://r3-cev.atlassian.net/browse/CORDA-1156
> [CORDA-1156]: Output of run networkMapFeed and run networkMapSnapshot not consistent in shell (fixed)

- node-api/src/main/kotlin/net/corda/nodeapi/internal/network/NetworkBootstrapper.kt
Already merged to v3:
https://github.com/corda/corda/pull/2721
and
https://github.com/corda/corda/pull/2666
> Network Bootstrap changes to master

- core/src/main/kotlin/net/corda/core/utilities/ProgressTracker.kt
merged to v3
https://github.com/corda/corda/pull/2730
> CORDA-1147 - fix shell (#2730)

- client/rpc/src/main/kotlin/net/corda/client/rpc/internal/KryoClientSerializationScheme.kt
- core/src/test/kotlin/net/corda/core/utilities/KotlinUtilsTest.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/ServerContexts.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/SharedContexts.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/AMQPSerializationScheme.kt
Backport of https://github.com/corda/corda/pull/2716
> CORDA-1140 - RPC Client's P2P Context should use AMQP

- docs/source/troubleshooting.rst
> CORDA-1145 - troubleshooting updates

- docs/source/troubleshooting.rst
Raise against V3 (for approved and merged [PR-2738](https://github.com/corda/corda/pull/2738) in master.)
> CORDA-1145 - V3 - troubleshooting rst

- docs/source/cordapp-build-systems.rst
Added info around the plugin split to corda.net docs.
> add docs about the split plugins to corda.net

- confidential-identities/src/main/kotlin/net/corda/confidential/IdentitySyncFlow.kt
- core/src/main/kotlin/net/corda/core/flows/CollectSignaturesFlow.kt
- core/src/main/kotlin/net/corda/core/messaging/CordaRPCOps.kt
- docs/source/api-flows.rst
- docs/source/flow-library.rst
- docs/source/tutorial-cordapp.rst
- node/src/main/kotlin/net/corda/node/internal/StartedNode.kt
- samples/simm-valuation-demo/README.md
Raise against V3 (for approved and merged [PR-2744](https://github.com/corda/corda/pull/2744) in master)
> CORDA-1175 V3 counterparty consistency

- node/src/main/kotlin/net/corda/node/services/persistence/NodeAttachmentService.kt
> ENT-1575 Shorten table name

- docs/source/permissioning.rst
#2755 (cherry picked from commit 4e5df2f)
> Fix permissioning doc

- node-api/src/main/kotlin/net/corda/core/serialization/ConstructorForDeserialization.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializationHelper.kt
- node-api/src/test/java/net/corda/nodeapi/internal/serialization/amqp/JavaSerializationOutputTests.java
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/EvolvabilityTests.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/PrivatePropertyTests.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializationOutputTests.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializationPropertyOrdering.kt
Backport from master of https://github.com/corda/corda/pull/2759
> CORDA-1186 - Move ConstructorForDeserialization out of internal

- docs/source/corda-api.rst
Some API documentation is related to 1.0 so needs updating for 3.0
> CORDA-1049 Minor update to Corda API doc to replace notes relevant to 1.0 to 3.0

- docs/source/node-explorer.rst
Although the ports are updated in [`README.md`](https://github.com/corda/corda/blob/master/tools/explorer/README.md), they are not updated in `node-explorer.rst`.
> CORDA-1117 - node-explorer port fixes

- docs/source/node-explorer.rst
Raise against V3 (for approved and merged [2762](https://github.com/corda/corda/pull/2762) in master)
> CORDA-1117 - V3 - node-explorer.rst port fixes

- core/src/main/kotlin/net/corda/core/crypto/CryptoUtils.kt
- core/src/main/kotlin/net/corda/core/crypto/SecureHash.kt
Raise against V3 (for approved and merged [PR-2587](https://github.com/corda/corda/pull/2587) in master)
> CORDA-1092 - V3 - fix secureRandomBytes 

- docs/source/upgrading-cordapps.rst
Added warning about possible problems while upgrades.
> Jar clash warning

- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/PropertySerializers.kt
Backport of https://github.com/corda/corda/pull/2767
> CORDA-1192 - Quieten message when reflecting on kotlin builtin

- docs/source/node-database.rst
Sorry about that extra second changed line, seems to happen when editing on github.com. Can be ignored.
> Documents the default username and password for H2.

- docs/source/release-notes.rst
Addresses comments made on https://github.com/corda/corda/pull/2775
> CORDA-966 - RELEASE - Final release note tweeks

- core/build.gradle
- finance/build.gradle
https://r3-cev.atlassian.net/browse/CORDA-1216
> [CORDA-1216]: Moved dependency on Jackson Databind from core to finance.

- client/rpc/src/integration-test/kotlin/net/corda/client/rpc/RPCStabilityTests.kt
- client/rpc/src/main/kotlin/net/corda/client/rpc/internal/RPCClientProxyHandler.kt
Basically throw exceptions as soon as connection is lost. Subsequent RPC calls will also throw. It becomes the responsibility of the user how these exceptions are treated. Would be nice to be able to have hooks into the proxy handler and let the user know when connection goes up and down, but that seems like something that needs debating.
> Bogdan - small rework of RPC client sending

- build.gradle
- client/jfx/src/main/kotlin/net/corda/client/jfx/model/NetworkIdentityModel.kt
- client/rpc/build.gradle
- client/rpc/src/main/kotlin/net/corda/client/rpc/internal/RPCClient.kt
- client/rpc/src/main/kotlin/net/corda/client/rpc/internal/RPCClientProxyHandler.kt
- client/rpc/src/test/kotlin/net/corda/client/rpc/RPCConcurrencyTests.kt
- client/rpc/src/test/kotlin/net/corda/client/rpc/RPCPerformanceTests.kt
- constants.properties
- node-api/build.gradle
- node-api/src/main/kotlin/net/corda/nodeapi/internal/DeduplicationChecker.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/SerializationScheme.kt
- node/build.gradle
- node/src/main/kotlin/net/corda/node/internal/security/RPCSecurityManagerImpl.kt
- node/src/main/kotlin/net/corda/node/services/messaging/RPCServer.kt
- node/src/main/kotlin/net/corda/node/services/network/PersistentNetworkMapCache.kt
- node/src/main/kotlin/net/corda/node/services/persistence/NodeAttachmentService.kt
- node/src/main/kotlin/net/corda/node/utilities/AppendOnlyPersistentMap.kt
- node/src/main/kotlin/net/corda/node/utilities/NonInvalidatingCache.kt
- node/src/main/kotlin/net/corda/node/utilities/NonInvalidatingUnboundCache.kt
- node/src/main/kotlin/net/corda/node/utilities/PersistentMap.kt
- tools/explorer/src/main/kotlin/net/corda/explorer/identicon/IdenticonRenderer.kt
Replace the buggy Guava caches with Caffeine.  https://github.com/ben-manes/caffeine
> CORDA-1217 Replace Guava caches with Caffeine

- .ci/api-current.txt
Branch got renamed, re-raising
> Update final API for V3

- node/src/main/kotlin/net/corda/node/services/transactions/PersistentUniquenessProvider.kt
Fixing a glitch from previous PR
> CORDA-1208: Remove unnecessary annotation from entity

- build.gradle
- tools/shell/src/main/java/net/corda/tools/shell/RunShellCommand.java
Cosmetic, 'bye' and 'exit' in shell's 'help'.
> CORDA-1075: Add 'bye' and 'exit' commands to Shell.

- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
> Propagate cordApp classloader to shell [CORDA-1228]

- samples/simm-valuation-demo/build.gradle
- samples/trader-demo/build.gradle
CORDA-792 Standalone Shell broke shell local shell of notaries, add rpcSettings to start RPC so the local shell can connect to the node.
> Fix local shell in trader demo and SIMM valuation demo.

- core/src/main/kotlin/net/corda/core/contracts/AttachmentConstraint.kt
- core/src/main/kotlin/net/corda/core/internal/AbstractAttachment.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/AttachmentsClassLoader.kt
ref: https://r3-cev.atlassian.net/browse/ENT-1564
Adds additional uploader check to the HashConstraint.
> ENT-1564 - add additional uploader check to the HashConstraint

- docs/source/generating-a-node.rst
Port of https://github.com/corda/corda/pull/2615
> [CORDA-2615]: Added description for configFile option in deployNodes Cordform Gradle task.

- node/src/main/kotlin/net/corda/node/services/schema/NodeSchemaService.kt
> Remove repeated code

- docs/source/node-administration.rst
- node/capsule/build.gradle
- testing/node-driver/src/main/kotlin/net/corda/testing/driver/Driver.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/driver/DriverDSL.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/DriverDSLImpl.kt
- tools/explorer/capsule/build.gradle
ref: https://r3-cev.atlassian.net/browse/ENT-1633
Increase to 512m from 200m
> ENT-1633 increase node max heap size to 512m

- node/src/integration-test/kotlin/net/corda/MessageState.kt
- node/src/integration-test/kotlin/net/corda/node/modes/draining/FlowsDrainingModeContentionTest.kt
- node/src/integration-test/kotlin/net/corda/node/modes/draining/P2PFlowsDrainingModeTest.kt
Explicit node names, changed column names of a test table.
> Align DrainingMode integration tests (related to CORDA-1243) with Enterprise repo.

- tools/scripts/upgrade-test-packages.sh
Fixes an issue found by tom on pubslack.
> Improve the upgrade-test-packages.sh script to work on macOS. 

- testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/network/NetworkMapServer.kt
> Optimize imports

- node/src/main/kotlin/net/corda/node/services/network/NetworkMapUpdater.kt
Reopen of PR: https://github.com/corda/corda/pull/2891 to release-V3
> ENT-1686: Improve error message on parameters mismatch

- docs/Makefile
- docs/make-docsite.sh
- docs/requirements.txt
- docs/source/conf.py
- docs/source/index.rst
Bacport of https://github.com/corda/corda/pull/2893
> BACKPORT: Generate a PDF version of the docsite. Request from a user in Slack.

- .ci/api-current.txt
- build.gradle
- core/src/main/kotlin/net/corda/core/schemas/PersistentTypes.kt
- node/src/main/kotlin/net/corda/node/internal/schemas/NodeInfoSchema.kt
- node/src/main/kotlin/net/corda/node/services/events/NodeSchedulerService.kt
- node/src/main/kotlin/net/corda/node/services/identity/PersistentIdentityService.kt
- node/src/main/kotlin/net/corda/node/services/keys/PersistentKeyManagementService.kt
- node/src/main/kotlin/net/corda/node/services/messaging/P2PMessagingClient.kt
- node/src/main/kotlin/net/corda/node/services/persistence/DBCheckpointStorage.kt
- node/src/main/kotlin/net/corda/node/services/persistence/DBTransactionMappingStorage.kt
- node/src/main/kotlin/net/corda/node/services/persistence/DBTransactionStorage.kt
- node/src/main/kotlin/net/corda/node/services/persistence/NodePropertiesPersistentStore.kt
- node/src/main/kotlin/net/corda/node/services/transactions/PersistentUniquenessProvider.kt
- node/src/main/kotlin/net/corda/node/services/transactions/RaftUniquenessProvider.kt
- node/src/main/kotlin/net/corda/node/services/upgrade/ContractUpgradeServiceImpl.kt
- node/src/test/kotlin/net/corda/node/services/schema/NodeSchemaServiceTest.kt
Ported from https://github.com/corda/corda/pull/2882.
> Make JPA entities non-final and Serializable.

- docs/source/changelog.rst
- node/src/main/kotlin/net/corda/node/internal/NetworkParametersReader.kt
Reopen to release-V3 of PR: https://github.com/corda/corda/pull/2887
> ENT-1668: Don't crash on node startup when network map is not available
