.ci/api-current.txt, client/rpc/src/integration-test/kotlin/net/corda/client/rpc/CordaRPCClientTest.kt, client/rpc/src/main/kotlin/net/corda/client/rpc/PermissionException.kt, core/src/main/kotlin/net/corda/core/Utils.kt, core/src/main/kotlin/net/corda/core/internal/concurrent/CordaFutureImpl.kt, docs/source/changelog.rst, node-api/src/main/kotlin/net/corda/nodeapi/exceptions/InternalNodeException.kt, node-api/src/main/kotlin/net/corda/nodeapi/exceptions/OutdatedNetworkParameterHashException.kt, node-api/src/main/kotlin/net/corda/nodeapi/exceptions/RejectedCommandException.kt, node-api/src/main/kotlin/net/corda/nodeapi/exceptions/RpcSerializableError.kt, node-api/src/main/kotlin/net/corda/nodeapi/exceptions/adapters/InternalObfuscatingFlowHandle.kt, node-api/src/main/kotlin/net/corda/nodeapi/exceptions/adapters/InternalObfuscatingFlowProgressHandle.kt, node/src/integration-test/kotlin/net/corda/ClientRelevantException.kt, node/src/integration-test/kotlin/net/corda/node/services/AttachmentLoadingTests.kt, node/src/integration-test/kotlin/net/corda/node/services/rpc/RpcExceptionHandlingTest.kt, node/src/main/kotlin/net/corda/node/internal/CordaRPCOpsImpl.kt, node/src/main/kotlin/net/corda/node/internal/Node.kt, node/src/main/kotlin/net/corda/node/internal/RpcExceptionHandlingProxy.kt, node/src/main/kotlin/net/corda/node/services/network/NetworkMapUpdater.kt
PR: https://github.com/corda/corda/pull/2892
=> [CORDA-1264]: Ensure correct serialisation and masking for throwables raised by a node and propagated through RPC.

core/src/main/kotlin/net/corda/core/transactions/LedgerTransaction.kt
* Instantiating the contract class should be part of contract verification. We should not instantiate it while building LedgerTransaction.
* Also catch any exceptions from instantiating the contract.
=> ENT-1463: Instantiate the contract class as part of contract verification.

build.gradle, tools/shell/build.gradle
https://r3-cev.atlassian.net/browse/CORDA-1294
=> [CORDA-1294]: Publish corda-shell module.

node/src/main/kotlin/net/corda/node/services/messaging/RPCServer.kt
https://r3-cev.atlassian.net/browse/CORDA-1295
=> CORDA-1295: Clean up client->observable association on observable finish

docs/source/changelog.rst, docs/source/upgrade-notes.rst
Add missing change log for Embedded Shell.
=> Change log for Embedded Shell terminal for CORDA-792.

constants.properties
Upgrade corda-gradle-plugins to remove `quasar-core` from `finance` CorDapp.
=> CORDA-1301: Upgrade to corda-gradle-plugins 4.0.11

docs/source/changelog.rst, docs/source/release-notes.rst, docs/source/upgrade-notes.rst
I decided not to mention Tudor's fix to the hash constraint as it's a security issue that would only have come into effect in the future...
Clearly these are going to be small as it's a point release really to ship a single fix and we're just gathering some others up with it
=> Pre release v3.1 releasenote

build.gradle, docs/source/changelog.rst
Upgrade from H2 1.4.194 to H2 1.4.197.
=> CORDA-1299: Upgrade to H2 1.4.197.

node-api/src/test/kotlin/net/corda/nodeapi/internal/SignedNodeInfoTest.kt, node/src/test/kotlin/net/corda/node/services/network/NetworkMapClientTest.kt, testing/test-utils/src/main/kotlin/net/corda/testing/internal/TestNodeInfoBuilder.kt
* ENT-1323 Network map service to check all identities in submitted node info
(cherry picked from commit f9ed55b)
=> ENT-1323 Network map service to check all identities in submitted node info

core/src/main/kotlin/net/corda/core/crypto/Crypto.kt, core/src/main/kotlin/net/corda/core/crypto/internal/ProviderMap.kt, node/src/main/kotlin/net/corda/node/Corda.kt
=> CORDA-1337 Crypto.registerProviders

node-api/src/main/kotlin/net/corda/nodeapi/exceptions/InternalNodeException.kt
this should fix:
https://r3-cev.atlassian.net/browse/CORDA-1313
and
https://r3-cev.atlassian.net/browse/CORDA-1316
=> CORDA-1313 RPC whitelist TransactionVerificationException

constants.properties, docs/source/changelog.rst, docs/source/setting-up-a-corda-network.rst, node-api/src/main/kotlin/net/corda/nodeapi/internal/ClassloaderUtils.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/network/NetworkBootstrapper.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/network/NetworkMap.kt
=> CORDA-1312: Network bootstrapper copies any CorDapp jars into each nodes' cordapps dir

docs/source/api-vault-query.rst, node/src/test/java/net/corda/node/services/vault/VaultQueryJavaTests.java, node/src/test/kotlin/net/corda/node/services/events/ScheduledFlowTests.kt, node/src/test/kotlin/net/corda/node/services/vault/VaultQueryTests.kt
- Fix issue with paging integration example in ScheduledFlowTests when number of results % page size != 0
- Move paging example to VaultQuery tests
- Write some tests for the example that just test that
- Write java version of pagination example and add to docs
=> CORDA-1344 Fix query paging in scheduled flow tests

core/src/main/kotlin/net/corda/core/identity/PartyAndCertificate.kt, core/src/main/kotlin/net/corda/core/internal/InternalUtils.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/crypto/X509Utilities.kt
=> Better cert path validation exception message for PartyAndCertificate.verify

core/src/main/kotlin/net/corda/core/internal/InternalUtils.kt, core/src/main/kotlin/net/corda/core/utilities/KotlinUtils.kt, experimental/behave/src/scenario/kotlin/net/corda/behave/scenarios/steps/VaultSteps.kt
As per recommendation in https://github.com/corda/enterprise/pull/757
=> Move kotlin utility helper out of public into internals.

experimental/behave/src/main/kotlin/net/corda/behave/process/Command.kt, experimental/behave/src/test/kotlin/net/corda/behave/process/CommandTests.kt
Quick fix related to previous Corda Behave improvements PR.
=> Fix streaming subscription bug.

constants.properties
Unpackage `kotlin-stdlib-jdk8` from CorDapps.
=> Upgrade to corda-gradle-plugins 4.0.14

node/src/main/java/CordaCaplet.java
Also log if directory was not created / cannot be found.
=> CORDA-1354 Check for jars in nested folders (to add in classpath) 

node/src/main/kotlin/net/corda/node/services/persistence/DBTransactionStorage.kt, node/src/main/kotlin/net/corda/node/services/statemachine/FlowStateMachineImpl.kt
Turns out the bug in CORDA-1368 is not actually a bug, included some misc things here instead
=> CORDA-1368: Add flow-id to MDC, small fix in DBTransactionStorage

LICENSE
=> Update license year to 2018

docs/source/corda-configuration-file.rst, docs/source/network-map.rst
=> Add docs on private networks config and endpoint

client/jfx/src/main/kotlin/net/corda/client/jfx/model/NetworkIdentityModel.kt, tools/explorer/src/main/kotlin/net/corda/explorer/views/Network.kt
cherrypicked from https://github.com/corda/enterprise/pull/779
=> [Bug fix] - explorer doesn't remove node from network view.

experimental/behave/src/scenario/kotlin/net/corda/behave/scenarios/ScenarioState.kt, experimental/behave/src/scenario/kotlin/net/corda/behave/scenarios/helpers/Database.kt, experimental/behave/src/scenario/kotlin/net/corda/behave/scenarios/helpers/Startup.kt, experimental/behave/src/scenario/kotlin/net/corda/behave/scenarios/helpers/Substeps.kt
Unclear how these slipped through the net in original PR:
https://github.com/corda/corda/pull/2990/files#diff-801a2b2d561cabe315b215daad59951d
=> Fix incorrect imports.

docs/source/changelog.rst, node/src/main/resources/build.properties
Backport of  https://github.com/corda/corda/pull/2617
=> Update jolokia to 1.5.0 (#2617)

docs/source/upgrade-notes.rst
(cherry picked from commit 514287e)
=> Fixed invalid page ref in upgrade-notes.rst

node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt, node/src/main/kotlin/net/corda/node/utilities/registration/NetworkRegistrationHelper.kt, node/src/test/kotlin/net/corda/node/utilities/registration/NetworkRegistrationHelperTest.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/DriverDSLImpl.kt
cherry picked from commit 5ed60ab
=> Bug fix: registration tool doesn't register for service identity if keystore already contains node cert

node/src/test/kotlin/net/corda/node/services/events/NodeSchedulerServiceTest.kt
=> Add node scheduler db tests inside use block

samples/bank-of-corda-demo/src/main/kotlin/net/corda/bank/BankOfCordaCordform.kt
Added missing dependency on finance cordapp.
=> CORDA-1370 Bank of Corda demo no longer works

docs/source/changelog.rst, node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializationHelper.kt, node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializationOutputTests.kt
=> CORDA-1403 - Generics serialization issue (#3030)

build.gradle, node-api/build.gradle, node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/ByteBufferStreams.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/SerializationScheme.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/AMQPSerializationScheme.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/AMQPStreams.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/DeserializationInput.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializationOutput.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializerFactory.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/carpenter/ClassCarpenter.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/kryo/KryoSerializationScheme.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/kryo/KryoStreams.kt, node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializationSchemaTests.kt, node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/kryo/KryoStreamsTest.kt
Refactor some of the serialisation code so that we can remove non-deterministic elements.
=> ENT-1463: Prepare node-api for determination.

docs/source/upgrading-cordapps.rst
https://r3-cev.atlassian.net/browse/CORDA-1315
There were a couple of things wrong with the doc:
- ByteArray mapping
- the entity class needs to be a top level class
- missing no-arg constructor
- fields need to be non-final
=> CORDA-1315 small doc correction

docs/source/changelog.rst, node/src/integration-test/kotlin/net/corda/node/services/network/NetworkMapTest.kt, node/src/main/kotlin/net/corda/node/services/config/NodeConfiguration.kt, node/src/test/kotlin/net/corda/node/services/config/NodeConfigurationImplTest.kt
https://r3-cev.atlassian.net/browse/CORDA-1445
=> [CORDA-1445]: Raise proper error when starting node in devMode with compatibilityZoneURL.

node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt
https://r3-cev.atlassian.net/browse/CORDA-1455
=> [CORDA-1455]: Error in process-id deletion process allows multiple instances of same node to be run (fix).

docs/source/changelog.rst, node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt
https://r3-cev.atlassian.net/browse/CORDA-1394
=> [CORDA-1394]: Node can fail to fully start when a port conflict occurs, without a useful error message (fix).

finance/src/main/kotlin/net/corda/finance/schemas/CashSchemaV1.kt, finance/src/main/kotlin/net/corda/finance/schemas/CommercialPaperSchemaV1.kt, finance/src/test/kotlin/net/corda/finance/schemas/SampleCashSchemaV1.kt, finance/src/test/kotlin/net/corda/finance/schemas/SampleCommercialPaperSchemaV1.kt, finance/src/test/kotlin/net/corda/finance/schemas/SampleCommercialPaperSchemaV2.kt, node/src/main/kotlin/net/corda/node/services/persistence/NodeAttachmentService.kt, node/src/main/kotlin/net/corda/node/services/vault/VaultSchema.kt, node/src/test/kotlin/net/corda/node/services/schema/NodeSchemaServiceTest.kt, testing/test-utils/src/main/kotlin/net/corda/testing/internal/vault/DummyLinearStateSchemaV1.kt
https://r3-cev.atlassian.net/browse/CORDA-1269
=> [CORDA-1269]: Changed usages of `arrayOf()` in Entities to use Kotlin 1.2 style.

CONTRIBUTORS.md
Added name to Contributors list after fixing https://github.com/corda/corda/issues/3120
=> Updated CONTRIBUTORS.md after resloving #3120

docs/source/changelog.rst
remove rows added by a faulty git merge
=> CORDA-1461 fix merge

client/rpc/src/smoke-test/java/net/corda/java/rpc/StandaloneCordaRPCJavaClientTest.java, testing/smoke-test-utils/src/main/kotlin/net/corda/smoketesting/NodeConfig.kt
The devMode changes were breaking the api tests.
This fixes them.
=> CORDA-1461 Fix smoke tests

core/src/main/kotlin/net/corda/core/messaging/CordaRPCOps.kt, node/src/main/kotlin/net/corda/node/internal/CordaRPCOpsImpl.kt, node/src/main/kotlin/net/corda/node/internal/RpcAuthorisationProxy.kt, node/src/main/kotlin/net/corda/node/internal/RpcExceptionHandlingProxy.kt, node/src/test/kotlin/net/corda/node/CordaRPCOpsImplTest.kt
Blocked on https://github.com/corda/corda/pull/2964
=> CORDA-1352: Add killFlow

docs/source/api-vault-query.rst, node/src/test/java/net/corda/node/services/vault/VaultQueryJavaTests.java, node/src/test/kotlin/net/corda/node/services/events/ScheduledFlowTests.kt, node/src/test/kotlin/net/corda/node/services/vault/VaultQueryTests.kt
Backport from master
* Fix paging tests, move out of scheduled flow tests and provide java example
* Fix a few issues with docs
=> CORDA-1344 - Fix query paging in scheduled flow tests (#2970)

build.gradle
* Artifactory refuse nightly deployment because of this
=> `snapshot` in corda version should be uppercase

.idea/compiler.xml, docs/source/network-map.rst, node-api/build.gradle, node-api/src/main/kotlin/net/corda/nodeapi/internal/ArtemisMessagingClient.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/ArtemisMessagingComponent.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/ArtemisUtils.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/MessageSizeChecksInterceptor.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/bridging/AMQPBridgeManager.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/bridging/BridgeControlListener.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/protonwrapper/netty/AMQPClient.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/protonwrapper/netty/AMQPServer.kt, node/src/integration-test/kotlin/net/corda/node/amqp/AMQPBridgeTest.kt, node/src/integration-test/kotlin/net/corda/node/amqp/CertificateRevocationListNodeTests.kt, node/src/integration-test/kotlin/net/corda/node/amqp/ProtonWrapperTests.kt, node/src/main/kotlin/net/corda/node/internal/Node.kt, node/src/main/kotlin/net/corda/node/services/messaging/ArtemisMessagingServer.kt, node/src/main/kotlin/net/corda/node/services/messaging/P2PMessagingClient.kt, node/src/test/kotlin/net/corda/node/services/messaging/ArtemisMessagingTest.kt
* journal size now = maxMessageSize + JOURNAL_HEADER_SIZE
* added require checks on send and receive message to ensure message is less then the max message size, setting journal size alone will not drop the message.
=> CORDA-864 Wire up max message size

tools/demobench/build.gradle
Fix to enable people to upgrade Gradle more easily.
=> Fix build breakage with Gradle 4.7.

CONTRIBUTORS.md, node-api/src/main/kotlin/net/corda/nodeapi/internal/network/NetworkBootstrapper.kt
=> Network bootstrapper should check for duplicate node names improvements

node-api/src/main/kotlin/net/corda/nodeapi/internal/config/ConfigUtilities.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/crypto/X509Utilities.kt, node-api/src/test/kotlin/net/corda/nodeapi/internal/config/ConfigParsingTest.kt, node/src/main/kotlin/net/corda/node/ArgsParser.kt, node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt, node/src/main/kotlin/net/corda/node/utilities/registration/NetworkRegistrationHelper.kt, node/src/test/kotlin/net/corda/node/ArgsParserTest.kt, node/src/test/kotlin/net/corda/node/utilities/registration/NetworkRegistrationHelperTest.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/DriverDSLImpl.kt
backport of https://github.com/corda/corda/pull/2620
Cherrypick from master
=> CORDA-1317 - Add cert role to CSR and doorman issue cert according to the cert role

core/src/main/kotlin/net/corda/core/contracts/Structures.kt
=> CORDA-1386 - Updates withoutIssuer to not strip display token size.

docs/source/api-scanner.rst, docs/source/contributing.rst, docs/source/corda-api.rst, docs/source/release-process-index.rst
Add api scanner documentation to the docsite
=> CORDA-1496 Add api-scanner documentation

core/src/main/kotlin/net/corda/core/flows/FinalityFlow.kt, core/src/main/kotlin/net/corda/core/flows/NotaryFlow.kt, core/src/main/kotlin/net/corda/core/flows/ReceiveTransactionFlow.kt, core/src/main/kotlin/net/corda/core/internal/InternalUtils.kt, docs/source/changelog.rst
https://r3-cev.atlassian.net/browse/ENT-1638
=> [CORDA-1638]: Audit log of failed transactions MVP.

CONTRIBUTORS.md
simply changed Guy Hochstetler org from IBM to R3
=> guy-contributor-edit

config/dev/log4j2.xml, testing/test-common/src/main/resources/log4j2-test.xml, tools/explorer/src/main/resources/log4j2.xml
https://r3-cev.atlassian.net/browse/CORDA-1547
=> [CORDA-1547]: Make log4j2.xml files more resilient to regex escaping problems.

docs/source/changelog.rst, tools/shell/src/main/kotlin/net/corda/tools/shell/InteractiveShell.kt
https://r3-cev.atlassian.net/browse/CORDA-1542
**Notes:**
- The Shell now actually kills the flow on CTRL+C, rather than just unsubscribing from it.
=> [CORDA-1542]: Ctrl-C in the shell no longer aborts the flow (fix).

.ci/api-current.txt
=> Revert adding validatePublicKey to api-current

node/src/main/kotlin/net/corda/node/services/statemachine/SingleThreadedStateMachineManager.kt, node/src/main/kotlin/net/corda/node/services/statemachine/transitions/StateMachine.kt, node/src/main/kotlin/net/corda/node/services/statemachine/transitions/Transition.kt
=> CORDA-1540 Remove no-longer-used StateMachineConfiguration

docs/source/changelog.rst, finance/src/integration-test/kotlin/net/corda/finance/compat/CashExceptionSerialisationTest.kt, finance/src/main/kotlin/net/corda/finance/flows/AbstractCashFlow.kt
https://r3-cev.atlassian.net/browse/CORDA-1555
=> [CORDA-1356]: CashException is unable to derisalize with AMQP through RPC. (fix).

build.gradle
https://r3-cev.atlassian.net/browse/CORDA-1557
=> [CORDA-1557]: Remove "corda-" from 4.0 (and onwards) release version.

docs/source/messaging.rst, docs/source/network-map.rst
CORDA-1562
some cleanup i noticed while going through the docs
Documentation to: https://github.com/corda/corda/pull/3272
=> Add documentation on clearing network map cache

tools/shell/src/main/java/net/corda/tools/shell/FlowShellCommand.java, tools/shell/src/main/java/net/corda/tools/shell/RunShellCommand.java, tools/shell/src/main/java/net/corda/tools/shell/StartShellCommand.java, tools/shell/src/main/kotlin/net/corda/tools/shell/InteractiveShell.kt
https://r3-cev.atlassian.net/browse/CORDA-1569
=> [CORDA-1569]: Shell doesn't yield control back to the user after a completed flow and throws NullPointerExceptions

config/dev/log4j2.xml, docs/source/changelog.rst, node/src/integration-test/kotlin/net/corda/node/BootTests.kt, samples/simm-valuation-demo/src/integration-test/kotlin/net/corda/vega/SimmValuationTest.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/ProcessUtilities.kt, testing/test-common/src/main/resources/log4j2-test.xml
https://r3-cev.atlassian.net/browse/CORDA-1575
=> [CORDA-1575]: Out of process nodes started by the driver do not log to file (fix).

node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt, tools/demobench/src/main/kotlin/net/corda/demobench/model/InstallFactory.kt, tools/demobench/src/main/kotlin/net/corda/demobench/model/NodeConfig.kt, tools/demobench/src/main/kotlin/net/corda/demobench/views/NodeTerminalView.kt
https://r3-cev.atlassian.net/browse/CORDA-1408
=> [CORDA-1408]: Fixed some Demobench bugs.

node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt, node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt
backport ent fix
Dev Mode check was not correctly implemented
=> CORDA-1477 backport Ent test fixes

node-api/src/main/kotlin/net/corda/nodeapi/internal/protonwrapper/netty/AMQPChannelHandler.kt
see https://github.com/corda/enterprise/pull/934
=> ENT-2036 Handle ClosedChannelException during SSL handshake

node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/CordaPersistence.kt, node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt, node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt
see https://r3-cev.atlassian.net/browse/ENT-1837
=> ENT-1837 better error message on db failure

docs/source/flow-state-machines.rst
=> Docs: flowTracker to progressTracker

node/src/integration-test/kotlin/net/corda/node/services/statemachine/HardRestartTest.kt, node/src/main/kotlin/net/corda/node/services/messaging/MessagingExecutor.kt, node/src/main/kotlin/net/corda/node/services/statemachine/FlowStateMachineImpl.kt, node/src/main/kotlin/net/corda/node/services/statemachine/SingleThreadedStateMachineManager.kt, node/src/main/resources/reference.conf, samples/trader-demo/src/integration-test/kotlin/net/corda/traderdemo/TraderDemoTest.kt
This PR includes fixes for bugs found as part of CORDA-1191
=> CORDA-1191 SMM bugs

docs/source/changelog.rst
=> CORDA-1494: Update changelog

node/src/test/kotlin/net/corda/node/services/network/NetworkMapUpdaterTest.kt
=> Fix flakey test

client/jfx/src/main/kotlin/net/corda/client/jfx/model/NodeMonitorModel.kt
https://r3-cev.atlassian.net/browse/CORDA-1617
=> [CORDA-1617] Fix explorer login error handling.

docs/source/key-concepts-notaries.rst
Although our documentation discusses notary validation, there was not a clear distinction between them.
Also added that notaries act as timestamping authorities as well.
=> [CORDA-1515] Clarify distinction between non-validating and validating notaries

docs/source/building-against-master.rst
Also expands page to speak about building from any non-release branch.
=> Adds instructions for building Gradle plugins

node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt, node/src/main/kotlin/net/corda/node/internal/CheckpointVerifier.kt, node/src/test/kotlin/net/corda/node/services/persistence/DBCheckpointStorageTests.kt
`TokenizableServices` did not pass the checkpoint verification.
=> ENT-2084 Fix `CheckpointVerifier`

node/src/test/kotlin/net/corda/node/services/statemachine/RetryFlowMockTest.kt
Had racy use of volatile that might have meant the short circuit that was intended didn't actually work.  Not seen it happen, but fixing anyway to be more correct.
=> CORDA-1622 Fix misuse of volatile

node/src/integration-test/kotlin/net/corda/node/services/network/PersistentNetworkMapCacheTest.kt, node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt, node/src/main/kotlin/net/corda/node/services/network/PersistentNetworkMapCache.kt, node/src/test/kotlin/net/corda/node/internal/NodeTest.kt
=> ENT-2013 fix issue when a node is restarted with the same entity, but different keypair

client/rpc/src/main/kotlin/net/corda/client/rpc/internal/RPCClient.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/ArtemisMessagingClient.kt, node/src/main/kotlin/net/corda/node/services/messaging/InternalRPCMessagingClient.kt, node/src/main/kotlin/net/corda/node/services/messaging/P2PMessagingClient.kt
=> ENT-2053 Fix messaging TTL related settings causing disconnects

docs/source/cordapp-custom-serializers.rst
Having watched someone try and implement this following the documentation, it's clear that it requires some further explanation as to what we intend them to do. This PR should add some context and further explanation.
=> CORDA-1640 - Proxy serializer documentation

node/src/main/kotlin/net/corda/node/services/config/NodeConfiguration.kt, node/src/test/kotlin/net/corda/node/services/config/NodeConfigurationImplTest.kt
https://r3-cev.atlassian.net/browse/CORDA-1595
=> [CORDA-1595]: If adminAddress is not included in rpcSettings configuration node fails with NullPointerException (fix).

core-deterministic/build.gradle, core-deterministic/testing/common/build.gradle, deterministic.gradle, jdk8u-deterministic/build.gradle, serialization-deterministic/build.gradle
Refactor the common and complicated configuration for the Java and Kotlin compilers into a Gradle script plugin.
=> ENT-1463, ENT-1903: Refactor Gradle for deterministic modules

core/src/main/kotlin/net/corda/core/flows/FlowLogic.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/DriverDSLImpl.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/ShutdownManager.kt
https://r3-cev.atlassian.net/browse/CORDA-1634
=> [CORDA-1634] Destroy child processes when parent exits.

docs/source/changelog.rst, docs/source/corda-configuration-file.rst, node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt, node/src/main/kotlin/net/corda/node/services/config/NodeConfiguration.kt, node/src/main/kotlin/net/corda/node/services/statemachine/FlowMonitor.kt, node/src/main/kotlin/net/corda/node/services/statemachine/SingleThreadedStateMachineManager.kt, node/src/main/kotlin/net/corda/node/services/statemachine/StateMachineManager.kt
https://r3-cev.atlassian.net/browse/CORDA-1605
=> [CORDA-1605]: When one node in a transaction fails to respond, operator of initiating node needs to understand which node it is waiting for (fix)

docs/source/node-administration.rst
https://r3-cev.atlassian.net/browse/CORDA-1629
=> [CORDA-1629]: Documented backup strategy recommendations for Corda platform components.

core/src/main/kotlin/net/corda/core/messaging/CordaRPCOps.kt
Mark new RPC method as CordaInternal
=> CORDA-1407 Mark method as CordaInternal

docs/source/changelog.rst, node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt, node/src/main/kotlin/net/corda/node/utilities/registration/HTTPNetworkRegistrationService.kt, node/src/main/kotlin/net/corda/node/utilities/registration/NetworkRegistrationHelper.kt
https://r3-cev.atlassian.net/browse/CORDA-1638
=> [CORDA-1638]: Node crashes in --initial-registration polling mode if doorman returns a transient HTTP error (fix).

node/src/main/kotlin/net/corda/node/services/statemachine/FlowMonitor.kt
=> CORDA-1645: Fix compilation issue

README.md
I'm testing the Bot Pokey, which will auto-merge all green pull requests.
These branches will be deleted after the test is over.
@GavT will accept this, and then we will test if this pull request gets merged by the bot.
=> Setting up a bot Testing Environment

build.gradle, gradle/wrapper/gradle-wrapper.properties
Fix regressions introduced in Gradle 4.8.
https://github.com/gradle/gradle/releases/tag/v4.8.1
=> Upgrade to Gradle 4.8.1

testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/DriverDSLImpl.kt
Add access rights to new function
=> CORDA-1407 Fix explorer rpc access rights

node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt
https://r3-cev.atlassian.net/browse/CORDA-1663
=> [CORDA-1663]: Node won't start if cordapps generate states prior to deletion (fix).

client/jfx/src/main/kotlin/net/corda/client/jfx/model/NodeMonitorModel.kt
In case of initial logon - it will not be re-tried to cater for invalid endpoint and/or credentials.
However, if connection been successfully established once, re-try logic is getting activated.
=> ENT-2132  Introduce a boolean flag which controls whether we should re-try RPC connection.

node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt, node/src/main/kotlin/net/corda/node/internal/cordapp/CordappLoader.kt, node/src/main/kotlin/net/corda/node/internal/cordapp/CordappProviderImpl.kt
this is causing: https://r3-cev.atlassian.net/browse/CORDA-1670
=> CORDA-1670 fix multiple CorDapps for flow check

node/src/main/java/CordaCaplet.java
https://r3-cev.atlassian.net/browse/CORDA-1598
=> [CORDA-1598] Make argument parsing more consistent.

finance/src/main/kotlin/net/corda/finance/flows/CashIssueAndPaymentFlow.kt, finance/src/main/kotlin/net/corda/finance/flows/CashPaymentFlow.kt, tools/explorer/src/main/kotlin/net/corda/explorer/views/cordapps/cash/NewTransaction.kt
Ensure the explorer works with networks with multiple notaries.
=> Specify Notary in `CashIssueAndPaymentFlow` and `PaymentRequest`

node-api/src/main/kotlin/net/corda/nodeapi/internal/network/NetworkBootstrapper.kt
JIRA: https://r3-cev.atlassian.net/browse/ENT-2146
=> ENT-2146: Bootstrapper: Warning timer thread should run as a daemon

docs/source/node-database.rst
Add a note about schema search path in postgres and linking to the relevant postgres documentation
=> Add comment about schema search path

node/src/main/kotlin/net/corda/node/utilities/AppendOnlyPersistentMap.kt, node/src/test/kotlin/net/corda/node/services/persistence/AppendOnlyPersistentMapTest.kt
=> ENT-2124 Flush before detach in Hibernate

docs/source/corda-configuration-file.rst, docs/source/upgrade-notes.rst
This is a backport of the changes made in the ENT. Updating the CRL related information.
=> CORDA-1688 Updating CRL config docs

build.gradle, docs/source/shell.rst, tools/shell-cli/README.md, tools/shell-cli/build.gradle
Fix to publish standalone shell to repository
=> ENT-1741 Build standalone shell JAR distribution - fix

docs/source/serialization.rst
Port of https://github.com/corda/enterprise/pull/1137
=> ENT-2171: Removing outdated information in the serialisation docs

build.gradle, tools/shell-cli/README.md, tools/shell-cli/build.gradle, tools/shell/build.gradle
Fixes according to comments to https://github.com/corda/corda/pull/3474 after it was merged.
=> ENT-1741 Build standalone shell JAR distribution - subsequent fix

finance/src/main/kotlin/net/corda/finance/flows/CashConfigDataFlow.kt
https://github.com/corda/corda/pull/3493
https://github.com/corda/enterprise/pull/1141
=> CORDA-1711 - Remove dependency on PathUtilsKt in net.corda.core.internal

experimental/avalanche/build.gradle, experimental/behave/build.gradle, experimental/build.gradle, experimental/kryo-hook/build.gradle, experimental/quasar-hook/build.gradle, samples/irs-demo/build.gradle, tools/network-bootstrapper/build.gradle
The experimental modules are part of the main project and so inherit repositories, plugins and properties.
=> Clear some cut-and-paste cruft out of our Gradle files.

client/mock/src/main/kotlin/net/corda/client/mock/EventGenerator.kt, core-deterministic/testing/data/src/test/kotlin/net/corda/deterministic/data/KeyStoreGenerator.kt, core-deterministic/testing/src/test/kotlin/net/corda/deterministic/contracts/PrivacySaltTest.kt, core-deterministic/testing/src/test/kotlin/net/corda/deterministic/crypto/SecureHashTest.kt, core/src/main/kotlin/net/corda/core/crypto/SecureHash.kt, node/src/test/kotlin/net/corda/node/serialization/kryo/KryoTests.kt, tools/explorer/src/main/kotlin/net/corda/explorer/ExplorerSimulation.kt
=> Resolve warnings for constructing Kotlin ByteArray.

node/src/main/resources/build.properties
Update jolokia dependency to use latest version (1.6.0) which contains security fixes
=> CORDA-1737 update jolokia dependency to latest version

build.gradle, gradle-plugins/cordformation/src/main/kotlin/net/corda/plugins/Cordformation.kt, gradle-plugins/cordformation/src/main/kotlin/net/corda/plugins/Node.kt
Update jolokia to latest version (1.6.0) which includes security fixes
=> CORDA-1744 update jolokia to latest version

docs/source/shell.rst, docs/source/tut-two-party-flow.rst
=> Update Shell.rst with CashIssueFlow

core/src/main/kotlin/net/corda/core/messaging/CordaRPCOps.kt, node/src/main/kotlin/net/corda/node/internal/CordaRPCOpsImpl.kt, node/src/main/kotlin/net/corda/node/internal/rpc/proxies/ExceptionSerialisingRpcOpsProxy.kt, node/src/main/kotlin/net/corda/node/services/network/NetworkMapUpdater.kt
=> ENT-1968: Add RPC for refreshing network map cache

client/rpc/src/test/kotlin/net/corda/client/rpc/RPCFailureTests.kt, docs/source/blob-inspector.rst, docs/source/building-a-cordapp-index.rst, docs/source/serialization-index.rst, docs/source/tools-index.rst, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/SerializationHelper.kt, tools/blobinspector/build.gradle, tools/blobinspector/src/main/kotlin/net/corda/blobinspector/BlobInspector.kt
Also, tidy up a couple of minor things in the docs and an error message.
=> Add support for hex and base64 inputs to the blob inspector

node-api/src/main/kotlin/net/corda/nodeapi/internal/config/ConfigUtilities.kt, node-api/src/test/kotlin/net/corda/nodeapi/internal/config/ConfigParsingTest.kt, node/src/main/kotlin/net/corda/node/services/config/NodeConfiguration.kt, node/src/main/kotlin/net/corda/node/utilities/registration/NetworkRegistrationHelper.kt, node/src/test/kotlin/net/corda/node/services/config/NodeConfigurationImplTest.kt
Change the NodeConfiguration.tlsCertCrlIssuer type from String to X500Principal
=> CORDA-1733 X500Principal configuration parsing

node/src/main/kotlin/net/corda/node/internal/Node.kt, node/src/main/kotlin/net/corda/node/services/messaging/ArtemisMessagingServer.kt
This reverts commit ed3944c54606e876abd6483ff5d66a764f9cf577.
=> ENT-2093 Revert " Create Artemis p2p.inbound addresses before starting the broker (#3407)

node/src/main/kotlin/net/corda/node/services/messaging/P2PMessagingClient.kt
Sync with enterprise queue creation.
=> ENT-2053: add exclusive flag to created P2P queues (except service ones)

testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/DriverDSLImpl.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/ShutdownManager.kt
Backport https://github.com/corda/corda/pull/3368
=> [CORDA-1634] Destroy child processes when parent exits. (#3368)

node-api/src/main/kotlin/net/corda/nodeapi/internal/protonwrapper/netty/SSLHelper.kt, node-api/src/test/kotlin/net/corda/nodeapi/internal/crypto/X509UtilitiesTest.kt, node/src/integration-test/kotlin/net/corda/node/amqp/ProtonWrapperTests.kt
=> [CORDA-1810] newSecureRandom instead of SecureRandom

docs/source/changelog.rst, node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/CordaPersistence.kt, node/src/integration-test/kotlin/net/corda/node/persistence/FailNodeOnNotMigratedAttachmentContractsTableNameTests.kt, node/src/main/kotlin/net/corda/node/internal/Node.kt, node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt, node/src/main/kotlin/net/corda/node/services/persistence/NodeAttachmentService.kt
Backport of  CORDA-1499 https://github.com/corda/corda/pull/3202
Backport of CORDA-1804 https://github.com/corda/corda/pull/3593
=> Back-ports CORDA-1499 and CORDA-1804 

docs/source/changelog.rst, node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/CordaPersistence.kt, node/src/integration-test/kotlin/net/corda/node/persistence/FailNodeOnNotMigratedAttachmentContractsTableNameTests.kt, node/src/main/kotlin/net/corda/node/internal/Node.kt, node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt
Backport / Forward port of https://github.com/corda/corda/pull/3607
=> CORDA-1499, CORDA-1804  (#3607)

docs/source/upgrade-notes.rst
see https://github.com/corda/corda/pull/3614
=> CORDA-1812 upgrade notes

node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/CordaPersistence.kt, node/src/integration-test/kotlin/net/corda/node/persistence/FailNodeOnNotMigratedAttachmentContractsTableNameTests.kt, node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt, node/src/main/kotlin/net/corda/node/services/persistence/DBCheckpointStorage.kt
see
https://r3-cev.atlassian.net/browse/CORDA-1812
=> CORDA-1812 fix Postgres db bloat issue

docs/source/upgrade-notes.rst
Backport of https://github.com/corda/corda/pull/3567
=> Back-port upgrade notes for CORDA-1804

docs/source/messaging.rst, docs/source/node-services.rst, docs/source/vault.rst
Backporting minor docs refactoring: https://github.com/corda/enterprise/pull/1166, https://github.com/corda/enterprise/pull/1144
=> ENT-2168: Node internal docs tweaks

core/src/test/kotlin/net/corda/core/identity/CordaX500NameTest.kt, docs/source/node-structure.rst
https://r3-cev.atlassian.net/browse/CORDA-1635
=> [CORDA-1635] Update docs (node naming constraints).

node/src/main/kotlin/net/corda/node/services/statemachine/FlowStateMachineImpl.kt, node/src/main/kotlin/net/corda/node/services/statemachine/StateMachineManagerImpl.kt, node/src/test/kotlin/net/corda/node/services/statemachine/FlowFrameworkTests.kt
Backport of https://github.com/corda/corda/pull/3597
=> CORDA-1790 - Roll back flow transaction on exception (#3597)

tools/explorer/src/main/kotlin/net/corda/explorer/views/cordapps/cash/CashViewer.kt
added labels as suggested in issue https://github.com/corda/corda/issues/3167
See ![attached screenshot](https://user-images.githubusercontent.com/2249953/42793186-ef7f255c-8946-11e8-9174-e707c75bc73b.PNG)  on how the chart looks now
I accept the agreement in CONTRIBUTING.md
- [Y ] Have you run the unit, integration and smoke tests as described here? https://docs.corda.net/head/testing.html
- [NA ] If you added/changed public APIs, did you write/update the JavaDocs?
- [NA ] If the changes are of interest to application developers, have you added them to the changelog, and potentially release notes?
- [Y ] If you are contributing for the first time, please read the agreement in CONTRIBUTING.md now and add to this Pull …
=> CORDA-3167 added titles to Treasury chart in Explorer

node-api/src/test/java/net/corda/nodeapi/internal/serialization/amqp/JavaCustomSerializerTests.java, node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt
Technically a forward port from 3.2
=> CORDA-1789 - Split Doorman / NM config - fix for CORDA-1510

docs/source/network-builder.rst, docs/source/release-notes.rst, docs/source/upgrade-notes.rst
=> Pre release v3.2 docs

build.gradle, tools/explorer/capsule/build.gradle
https://github.com/corda/corda/pull/3437
=> CORDA-1674 - Publish Node Explorer artefact (#3437)

node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt
https://r3-cev.atlassian.net/browse/CORDA-1572
=> [CORDA-1572] Create marker file to track initial registration status.

docs/source/tutorial-cordapp.rst
=> Docs added MacOSX version of Intellij Project Structure JDK Set-Up

docs/source/release-notes.rst, docs/source/upgrade-notes.rst
Just updating master post 3.2, consolidating what's been added here with what was put out on the branch
=> RELEASE - Update upgrade and release notes on master post V3.2

confidential-identities/src/test/kotlin/net/corda/confidential/IdentitySyncFlowTests.kt, core/src/test/kotlin/net/corda/core/flows/CollectSignaturesFlowTests.kt, core/src/test/kotlin/net/corda/core/flows/ContractUpgradeFlowTest.kt, docs/source/example-code/src/integration-test/kotlin/net/corda/docs/IntegrationTestingTutorial.kt, finance/src/integration-test/kotlin/net/corda/finance/flows/CashSelectionTest.kt, finance/src/test/kotlin/net/corda/finance/contracts/CommercialPaperTests.kt, finance/src/test/kotlin/net/corda/finance/contracts/asset/CashTests.kt, finance/src/test/kotlin/net/corda/finance/contracts/asset/ObligationTests.kt, finance/src/test/kotlin/net/corda/finance/flows/CashExitFlowTests.kt, finance/src/test/kotlin/net/corda/finance/flows/CashIssueFlowTests.kt, finance/src/test/kotlin/net/corda/finance/flows/CashPaymentFlowTests.kt, node/src/integration-test/kotlin/net/corda/node/services/DistributedServiceTests.kt, node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt, node/src/main/kotlin/net/corda/node/services/schema/PersistentStateService.kt, node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt, node/src/test/kotlin/net/corda/node/CordaRPCOpsImplTest.kt, node/src/test/kotlin/net/corda/node/messaging/TwoPartyTradeFlowTests.kt, node/src/test/kotlin/net/corda/node/services/persistence/HibernateConfigurationTest.kt, node/src/test/kotlin/net/corda/node/services/schema/PersistentStateServiceTests.kt, node/src/test/kotlin/net/corda/node/services/vault/NodeVaultServiceTest.kt, node/src/test/kotlin/net/corda/node/services/vault/VaultQueryTests.kt, node/src/test/kotlin/net/corda/node/services/vault/VaultSoftLockManagerTest.kt, node/src/test/kotlin/net/corda/node/services/vault/VaultWithCashTest.kt, samples/trader-demo/src/test/kotlin/net/corda/traderdemo/TransactionGraphSearchTests.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/MockServices.kt
see 
https://github.com/corda/corda/pull/3689
=> CORDA-1847 Fix hibernate observer issue

samples/network-verifier/src/main/kotlin/net/corda/verification/TestNotaryFlow.kt
Add missing suspendable to flow.
=> Add missing suspendable

docs/source/network-bootstrapper.rst, docs/source/setting-up-a-corda-network.rst, docs/source/tools-index.rst
=> Backports network bootstrapper docs.

confidential-identities/src/test/kotlin/net/corda/confidential/IdentitySyncFlowTests.kt, core/src/test/kotlin/net/corda/core/flows/CollectSignaturesFlowTests.kt, core/src/test/kotlin/net/corda/core/flows/ContractUpgradeFlowTest.kt, core/src/test/kotlin/net/corda/core/flows/FinalityFlowTests.kt, docs/source/example-code/src/integration-test/java/net/corda/docs/JavaIntegrationTestingTutorial.java, docs/source/example-code/src/integration-test/kotlin/net/corda/docs/KotlinIntegrationTestingTutorial.kt, finance/src/test/kotlin/net/corda/finance/contracts/CommercialPaperTests.kt, finance/src/test/kotlin/net/corda/finance/contracts/asset/CashTests.kt, finance/src/test/kotlin/net/corda/finance/contracts/asset/ObligationTests.kt, finance/src/test/kotlin/net/corda/finance/flows/CashExitFlowTests.kt, finance/src/test/kotlin/net/corda/finance/flows/CashIssueFlowTests.kt, finance/src/test/kotlin/net/corda/finance/flows/CashPaymentFlowTests.kt, node/src/integration-test/kotlin/net/corda/node/flows/FlowCheckpointVersionNodeStartupCheckTest.kt, node/src/integration-test/kotlin/net/corda/node/services/distributed/DistributedServiceTests.kt, node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt, node/src/main/kotlin/net/corda/node/services/schema/PersistentStateService.kt, node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt, node/src/test/kotlin/net/corda/node/CordaRPCOpsImplTest.kt, node/src/test/kotlin/net/corda/node/messaging/TwoPartyTradeFlowTests.kt, node/src/test/kotlin/net/corda/node/services/ServiceHubConcurrentUsageTest.kt, node/src/test/kotlin/net/corda/node/services/persistence/HibernateConfigurationTest.kt, node/src/test/kotlin/net/corda/node/services/schema/PersistentStateServiceTests.kt, node/src/test/kotlin/net/corda/node/services/vault/NodeVaultServiceTest.kt, node/src/test/kotlin/net/corda/node/services/vault/VaultQueryExceptionsTests.kt, node/src/test/kotlin/net/corda/node/services/vault/VaultSoftLockManagerTest.kt, node/src/test/kotlin/net/corda/node/services/vault/VaultWithCashTest.kt, samples/trader-demo/src/test/kotlin/net/corda/traderdemo/TransactionGraphSearchTests.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/MockServices.kt
see https://github.com/corda/corda/pull/3689
=> Feature/corda 1847/remove hibernate observers

docs/source/hello-world-running.rst, docs/source/hello-world-state.rst
- [ Y] Have you run the unit, integration and smoke tests as described here? https://docs.corda.net/head/testing.html
- [Y ] If you added/changed public APIs, did you write/update the JavaDocs?
- [Y ] If the changes are of interest to application developers, have you added them to the changelog, and potentially release notes?
- [ Y] If you are contributing for the first time, please read the agreement in CONTRIBUTING.md now and add to this Pull Request that you agree to it.
=> Miner change to mention notary node dosen't need web server, and also change the total terminal windows number from 8 to 5

core/src/main/kotlin/net/corda/core/internal/CordaUtils.kt, core/src/main/kotlin/net/corda/core/internal/InternalUtils.kt, core/src/main/kotlin/net/corda/core/node/NetworkParameters.kt, core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt, core/src/test/kotlin/net/corda/core/transactions/TransactionBuilderTest.kt, docs/source/changelog.rst, node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt, node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt, node/src/main/kotlin/net/corda/node/services/network/PersistentNetworkMapCache.kt
Also includes some minor cleanup brought up in a previous PR.
=> CORDA-1845: Check for min plaform version of 4 when building transactions with reference states

core/src/main/kotlin/net/corda/core/internal/FetchDataFlow.kt
see https://r3-cev.atlassian.net/browse/CORDA-1865
This fixes a phantom read issue.
=> CORDA-1865 Fix race on inserting attachments

core/src/main/kotlin/net/corda/core/flows/SendTransactionFlow.kt, core/src/main/kotlin/net/corda/core/internal/FetchDataFlow.kt, core/src/main/kotlin/net/corda/core/internal/ResolveTransactionsFlow.kt, core/src/test/kotlin/net/corda/core/flows/AttachmentTests.kt, core/src/test/kotlin/net/corda/core/flows/TestDataVendingFlow.kt, core/src/test/kotlin/net/corda/core/flows/TestNoSecurityDataVendingFlow.kt, core/src/test/kotlin/net/corda/core/internal/ResolveTransactionsFlowTest.kt, core/src/test/kotlin/net/corda/core/serialization/AttachmentSerializationTest.kt
see https://r3-cev.atlassian.net/browse/CORDA-1724
=> CORDA-1724 Add tx access right validity check during resolution

client/rpc/src/main/kotlin/net/corda/client/rpc/internal/RPCClientProxyHandler.kt, client/rpc/src/main/kotlin/net/corda/client/rpc/internal/serialization/amqp/AMQPClientSerializationScheme.kt, client/rpc/src/main/kotlin/net/corda/client/rpc/internal/serialization/amqp/RpcClientObservableDeSerializer.kt, docs/source/clientrpc.rst, node/src/main/kotlin/net/corda/node/serialization/amqp/RpcServerObservableSerializer.kt, node/src/test/kotlin/net/corda/node/internal/serialization/RoundTripObservableSerializerTests.kt, node/src/test/kotlin/net/corda/node/internal/serialization/testutils/AMQPTestSerialiationScheme.kt
Renaming one internal class to more explicitly highlight what it is doing.
Few updates to RPC documentation and code comments.
=> RPC changes

confidential-identities/src/test/kotlin/net/corda/confidential/IdentitySyncFlowTests.kt, core/src/test/kotlin/net/corda/core/flows/CollectSignaturesFlowTests.kt, core/src/test/kotlin/net/corda/core/flows/ContractUpgradeFlowTest.kt, docs/source/example-code/src/integration-test/kotlin/net/corda/docs/IntegrationTestingTutorial.kt, finance/src/test/kotlin/net/corda/finance/contracts/CommercialPaperTests.kt, finance/src/test/kotlin/net/corda/finance/contracts/asset/CashTests.kt, finance/src/test/kotlin/net/corda/finance/contracts/asset/ObligationTests.kt, finance/src/test/kotlin/net/corda/finance/flows/CashExitFlowTests.kt, finance/src/test/kotlin/net/corda/finance/flows/CashIssueFlowTests.kt, finance/src/test/kotlin/net/corda/finance/flows/CashPaymentFlowTests.kt, node/src/integration-test/kotlin/net/corda/node/services/DistributedServiceTests.kt, node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt, node/src/main/kotlin/net/corda/node/services/schema/PersistentStateService.kt, node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt, node/src/test/kotlin/net/corda/node/CordaRPCOpsImplTest.kt, node/src/test/kotlin/net/corda/node/messaging/TwoPartyTradeFlowTests.kt, node/src/test/kotlin/net/corda/node/services/ServiceHubConcurrentUsageTest.kt, node/src/test/kotlin/net/corda/node/services/persistence/HibernateConfigurationTest.kt, node/src/test/kotlin/net/corda/node/services/schema/PersistentStateServiceTests.kt, node/src/test/kotlin/net/corda/node/services/vault/NodeVaultServiceTest.kt, node/src/test/kotlin/net/corda/node/services/vault/VaultQueryTests.kt, node/src/test/kotlin/net/corda/node/services/vault/VaultSoftLockManagerTest.kt, node/src/test/kotlin/net/corda/node/services/vault/VaultWithCashTest.kt, samples/trader-demo/src/test/kotlin/net/corda/traderdemo/TransactionGraphSearchTests.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/MockServices.kt
see https://github.com/corda/corda/pull/3689
=> CORDA-1847 Backport hibernate observer fix

node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt, node/src/main/kotlin/net/corda/node/utilities/registration/NetworkRegistrationHelper.kt
https://r3-cev.atlassian.net/browse/CORDA-1880
=> [CORDA-1880]: Exception if timeout during initial registration (fixed).

build.gradle, constants.properties, node/build.gradle
Minor fix after https://github.com/corda/corda/pull/3739
=> NOTICK - Fix version reference for New Relic dependency

docs/source/hello-world-flow.rst, docs/source/hello-world-running.rst, docs/source/hello-world-template.rst
=> Miscellaneous doc fixes

constants.properties, samples/cordapp-configuration/build.gradle, samples/cordapp-configuration/src/main/resources/log4j2.xml, samples/simm-valuation-demo/build.gradle
Update one simple and one complex CordFormation sample to use `nodeDefaults`.
=> CORDA-1889: Update some CordFormation samples to use nodeDefaults{}.

node/src/main/kotlin/net/corda/node/services/statemachine/StaffedFlowHospital.kt
=> CORDA-1850: Minor: improve flow timeout error message

node/src/main/kotlin/net/corda/node/services/api/ServiceHubInternal.kt
Vault logic should be in the vault.  And it stops some code in CE from executing...
=> CORDA-1894 Remove if condition from service hub that prevents vault logic executing.

node/src/main/kotlin/net/corda/node/NodeArgsParser.kt, node/src/test/kotlin/net/corda/node/NodeArgsParserTest.kt
This is required by some deployments.
=> Config file and base dir can be specified together

node/src/integration-test/kotlin/net/corda/services/vault/VaultRestartTest.kt, node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt
Fix regression introduced in https://r3-cev.atlassian.net/browse/CORDA-1663 and this time added an integration test.
=> ENT-2419 Fix Vault contractStateType's bootstrapping bug

core/src/main/kotlin/net/corda/core/context/InvocationContext.kt
https://r3-cev.atlassian.net/browse/CORDA-1681
PR against master: https://github.com/corda/corda/pull/3791
=> [CORDA-1681]: It is not possible to run stateMachinesSnapshot from the shell (fixed).

client/jackson/src/main/kotlin/net/corda/client/jackson/JacksonSupport.kt, client/jackson/src/main/kotlin/net/corda/client/jackson/internal/CordaModule.kt, client/jackson/src/test/kotlin/net/corda/client/jackson/AmountTest.kt, client/jackson/src/test/kotlin/net/corda/client/jackson/JacksonSupportTest.kt, samples/irs-demo/build.gradle, samples/irs-demo/web/build.gradle, samples/network-visualiser/build.gradle
* Extend JSON deserialisation to handle Amount<T> for any T.
* Rewrite message for @Deprecated.
Conflicts:
client/jackson/src/main/kotlin/net/corda/client/jackson/internal/CordaModule.kt
=> CORDA-1905: Extend JSON deserialisation to handle Amount<T> for any T

core/src/main/kotlin/net/corda/core/serialization/SerializationAPI.kt, node/src/integration-test/kotlin/net/corda/node/amqp/CertificateRevocationListNodeTests.kt, node/src/test/kotlin/net/corda/node/serialization/kryo/KryoTests.kt, serialization/src/main/kotlin/net/corda/serialization/internal/SerializationFormat.kt, serialization/src/main/kotlin/net/corda/serialization/internal/SerializationScheme.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/DeserializationInput.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/SerializationOutput.kt, serialization/src/test/kotlin/net/corda/serialization/internal/ListsSerializationTest.kt, serialization/src/test/kotlin/net/corda/serialization/internal/amqp/SerializationOutputTests.kt, serialization/src/test/kotlin/net/corda/serialization/internal/amqp/testutils/AMQPTestUtils.kt, tools/blobinspector/src/main/kotlin/net/corda/blobinspector/BlobInspector.kt
=> ENT-2439 Fix compression in serialization

core/src/smoke-test/kotlin/net/corda/core/cordapp/CordappSmokeTest.kt
https://r3-cev.atlassian.net/browse/CORDA-1917
=> [CORDA-1917] Fix smoke test

node/src/main/kotlin/net/corda/node/services/persistence/DBTransactionMappingStorage.kt, node/src/main/kotlin/net/corda/node/services/persistence/DBTransactionStorage.kt, node/src/main/kotlin/net/corda/node/services/schema/NodeSchemaService.kt
=> ENT-2202 Fold transaction mapping column into transactions table

finance/src/main/kotlin/net/corda/finance/contracts/asset/cash/selection/CashSelectionSQLServerImpl.kt
Fixed is_modifiable column condition.
=> Fix "isRelevant" functionality - fix is_modifiable column condition in cash selection.

.idea/compiler.xml, client/jfx/src/main/kotlin/net/corda/client/jfx/model/NetworkIdentityModel.kt, client/rpc/src/main/kotlin/net/corda/client/rpc/internal/RPCClientProxyHandler.kt, core/build.gradle, core/src/main/kotlin/net/corda/core/internal/NamedCache.kt, core/src/main/kotlin/net/corda/core/utilities/NamedCache.kt, core/src/test/kotlin/net/corda/core/internal/NamedCacheTest.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/DeduplicationChecker.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/HibernateConfiguration.kt, node/src/main/kotlin/net/corda/node/internal/security/RPCSecurityManagerImpl.kt, node/src/main/kotlin/net/corda/node/services/identity/PersistentIdentityService.kt, node/src/main/kotlin/net/corda/node/services/keys/PersistentKeyManagementService.kt, node/src/main/kotlin/net/corda/node/services/messaging/P2PMessageDeduplicator.kt, node/src/main/kotlin/net/corda/node/services/messaging/RPCServer.kt, node/src/main/kotlin/net/corda/node/services/network/PersistentNetworkMapCache.kt, node/src/main/kotlin/net/corda/node/services/persistence/DBTransactionStorage.kt, node/src/main/kotlin/net/corda/node/services/persistence/NodeAttachmentService.kt, node/src/main/kotlin/net/corda/node/services/persistence/NodePropertiesPersistentStore.kt, node/src/main/kotlin/net/corda/node/services/transactions/BFTNonValidatingNotaryService.kt, node/src/main/kotlin/net/corda/node/services/transactions/PersistentUniquenessProvider.kt, node/src/main/kotlin/net/corda/node/services/transactions/RaftUniquenessProvider.kt, node/src/main/kotlin/net/corda/node/services/upgrade/ContractUpgradeServiceImpl.kt, node/src/main/kotlin/net/corda/node/utilities/AppendOnlyPersistentMap.kt, node/src/main/kotlin/net/corda/node/utilities/NonInvalidatingCache.kt, node/src/main/kotlin/net/corda/node/utilities/NonInvalidatingUnboundCache.kt, node/src/main/kotlin/net/corda/node/utilities/PersistentMap.kt, node/src/test/kotlin/net/corda/node/services/persistence/AppendOnlyPersistentMapTest.kt, node/src/test/kotlin/net/corda/node/utilities/PersistentMapTests.kt, serialization/src/main/kotlin/net/corda/serialization/internal/SerializationScheme.kt, tools/explorer/src/main/kotlin/net/corda/explorer/identicon/IdenticonRenderer.kt
Add a helper to create named caches and apply it to all caffeine caches in production code.
=> ENT-2414 Named caches

node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/CordaPersistence.kt, node/src/integration-test/kotlin/net/corda/node/persistence/FailNodeOnNotMigratedAttachmentContractsTableNameTests.kt, node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt, node/src/main/kotlin/net/corda/node/services/persistence/DBCheckpointStorage.kt
Forward port from the 3.2 branch to ensure this goes out with the rest of the V3 releases (it's a long and tedious story)
=> CORDA-1812 - fix Postgres db bloat issue (#3614)

docs/source/permissioning.rst, node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt, node/src/main/kotlin/net/corda/node/services/network/NetworkMapClient.kt, node/src/main/kotlin/net/corda/node/utilities/registration/HTTPNetworkRegistrationService.kt, node/src/test/kotlin/net/corda/node/services/network/NetworkMapClientTest.kt, node/src/test/kotlin/net/corda/node/services/network/NetworkMapUpdaterTest.kt, node/src/test/kotlin/net/corda/node/services/network/NetworkParametersReaderTest.kt
This PR adds version info to the node info submission request.
=> CORDA-1938 Adding version info to the node info submission request

node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt
https://r3-cev.atlassian.net/browse/CORDA-1921
=> [CORDA-1542]: Exception error codes aren't stable (fixed).

docs/source/changelog.rst, node/src/integration-test/kotlin/net/corda/node/persistence/FailNodeOnNotMigratedAttachmentContractsTableNameTests.kt, node/src/integration-test/kotlin/net/corda/node/services/rpc/RpcSslTest.kt, node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt, node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt, node/src/main/kotlin/net/corda/node/shell/InteractiveShell.kt, node/src/main/kotlin/net/corda/node/utilities/registration/HTTPNetworkRegistrationService.kt, node/src/main/kotlin/net/corda/node/utilities/registration/NetworkRegistrationHelper.kt
https://r3-cev.atlassian.net/browse/CORDA-1663 (https://github.com/corda/corda/pull/3432)
https://r3-cev.atlassian.net/browse/CORDA-1638 (https://github.com/corda/corda/pull/3403)
https://r3-cev.atlassian.net/browse/CORDA-1542 (https://github.com/corda/corda/pull/3260)
=> Backports: CORDA-1663, CORDA-1638, CORDA-1542

docs/source/deploying-a-node.rst
root/sys admin should create the corda user
=> Clarify user to create the "corda" users

finance/src/main/kotlin/net/corda/finance/flows/CashPaymentFlow.kt
This is just a logging improvement.
JIRA ticket: https://r3-cev.atlassian.net/browse/ENT-2054?filter=19753
=> Cherry pick ENT-2054

core-deterministic/testing/common/src/main/kotlin/net/corda/deterministic/common/Enclavelet.kt, core-deterministic/testing/src/test/kotlin/net/corda/deterministic/txverify/EnclaveletTest.kt, djvm/build.gradle, djvm/cli/build.gradle
Ensure that DJVM's project and published POM both contain correct dependency information.
Also migrate enclavelet code into testing:common jar so that it can be shared.
=> ENT-1906: Publish DJVM artifact with its dependency information.

core/src/main/kotlin/net/corda/core/internal/CertRole.kt, core/src/test/kotlin/net/corda/core/internal/CertRoleTests.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/crypto/X509Utilities.kt
This is a cherry-pick PR from the master branch PR: https://github.com/corda/corda/pull/3844
=> CORDA-1934 renaming cert role

core/src/main/kotlin/net/corda/core/internal/DigitalSignatureWithCert.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/network/NetworkMap.kt
This is a cherry pick PR for the master branch PR: https://github.com/corda/corda/pull/3843
=> CORDA-1932 networkmap validation fix

core/src/main/kotlin/net/corda/core/messaging/CordaRPCOps.kt, node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt, node/src/main/kotlin/net/corda/node/internal/Node.kt, node/src/main/kotlin/net/corda/node/services/messaging/P2PMessagingClient.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/DriverDSLImpl.kt
- Fixed some problems with error handling for Observables.
- Eliminated incorrect double `stop()` call for RpcBroker.
- Added `Schedulers.shutdown()` call in `stop()` implementation for Node and Driver, to avoid stuck processes when observable pipelines go wrong.
=> Fixed some problem I discovered while working on another story

experimental/behave/src/main/kotlin/net/corda/behave/process/Command.kt, experimental/behave/src/main/kotlin/net/corda/behave/service/ContainerService.kt, experimental/behave/src/test/kotlin/net/corda/behave/process/CommandTests.kt
In particular, fixing the recursive call of the "use" method
=> Some clean up of behave code

tools/shell-cli/build.gradle, tools/shell/build.gradle
Resolve some issues which will break our build when Gradle 5.0 is released.
=> CORDA-1964: Resolve some Gradle warnings which will soon become errors.

core/src/main/kotlin/net/corda/core/cordapp/Cordapp.kt, core/src/main/kotlin/net/corda/core/internal/cordapp/CordappImpl.kt, finance/build.gradle, node/src/main/kotlin/net/corda/node/VersionInfo.kt, node/src/main/kotlin/net/corda/node/cordapp/CordappLoader.kt, node/src/main/kotlin/net/corda/node/internal/Node.kt, node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt, node/src/main/kotlin/net/corda/node/internal/cordapp/CordappProviderImpl.kt, node/src/main/kotlin/net/corda/node/internal/cordapp/CordappProviderInternal.kt, node/src/main/kotlin/net/corda/node/internal/cordapp/JarScanningCordappLoader.kt, node/src/main/kotlin/net/corda/node/internal/cordapp/ManifestUtils.kt, node/src/test/kotlin/net/corda/node/internal/NodeTest.kt, node/src/test/kotlin/net/corda/node/internal/cordapp/JarScanningCordappLoaderTest.kt, samples/attachment-demo/src/integration-test/kotlin/net/corda/attachmentdemo/AttachmentDemoTest.kt, testing/test-utils/src/main/kotlin/net/corda/testing/internal/MockCordappProvider.kt
Also, Cordapp.Info has been made internal as it's not used in the public API
=> Syncing Cordapp info code from ENT so that ENT-1731 is fully ported

node/src/integration-test/kotlin/net/corda/node/persistence/FailNodeOnNotMigratedAttachmentContractsTableNameTests.kt
=> CORDA-1976 Fix flaky test

node/src/main/kotlin/net/corda/node/shell/InteractiveShell.kt
=> CORDA-1892 CRaSH shell flow start fix for similar flow names. (#3874)

docs/source/hello-world-flow.rst, docs/source/hello-world-running.rst, docs/source/hello-world-template.rst
Backport of https://github.com/corda/corda/pull/3760
=> CORDA-1949, CORDA-1950 - Miscellaneous doc fixes (#3760)

node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt
plus extract method refactoring.
=> CORDA-1978 Check for empty RPC keystore/trustore passwords

node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt
Cleaned up `NodeStartup.runProgram` and added step by step clarifications. Required this during key management refactoring, so sequence of events is explained in more detail.
=> CORDA-1979 Cleanup NodeStartup for better readability 

core/src/main/kotlin/net/corda/core/flows/FlowException.kt, docs/source/changelog.rst, docs/source/clientrpc.rst, node/src/integration-test/kotlin/net/corda/node/BootTests.kt, node/src/integration-test/kotlin/net/corda/node/services/network/NetworkMapTest.kt, node/src/integration-test/kotlin/net/corda/node/services/rpc/RpcExceptionHandlingTest.kt, node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt, node/src/main/kotlin/net/corda/node/internal/rpc/proxies/ExceptionMaskingRpcOpsProxy.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/DriverDSLImpl.kt
This is a port of https://github.com/corda/enterprise/pull/871
=> CORDA-1264: Mask internal errors if devMode is false

release-tools/jiraReleaseChecker.py
Forward port of the tooling on the V3 branch (https://github.com/corda/corda/pull/3945)
=> RELEASE - Script to identity and format commits added to the branch

client/jackson/src/test/kotlin/net/corda/client/jackson/JacksonSupportTest.kt, core/src/main/kotlin/net/corda/core/internal/DigitalSignatureWithCert.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/network/NetworkMap.kt
This is a cherry-pick PR for the master branch PR: https://github.com/corda/corda/pull/3953
=> CORDA-1995 Removing DigitalSignatureWithCertPath (Cherry Pick)

node-api/src/main/kotlin/net/corda/nodeapi/internal/protonwrapper/netty/AMQPClient.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/protonwrapper/netty/SSLHelper.kt
https://github.com/corda/corda/pull/3968
=> CORDA-2001: backport SNI header

node/src/main/kotlin/net/corda/node/internal/Node.kt
=> ENT-2431: Expose cache factory further down the class hierarchy of AbtractNode

tools/demobench/src/main/kotlin/net/corda/demobench/explorer/Explorer.kt, tools/demobench/src/main/kotlin/net/corda/demobench/model/InstallFactory.kt, tools/demobench/src/main/kotlin/net/corda/demobench/model/NodeConfig.kt, tools/demobench/src/main/kotlin/net/corda/demobench/model/NodeController.kt, tools/demobench/src/main/kotlin/net/corda/demobench/model/NodeRpcSettings.kt, tools/demobench/src/main/kotlin/net/corda/demobench/rpc/NodeRPC.kt, tools/demobench/src/test/kotlin/net/corda/demobench/model/NodeConfigTest.kt, tools/demobench/src/test/kotlin/net/corda/demobench/model/NodeControllerTest.kt
https://r3-cev.atlassian.net/browse/CORDA-1948
This was fixed by an external contributor, but never ported. Original commit: https://github.com/corda/corda/commit/96d645c316d0abac4cbe1c15113c7d73a596e75e
=> [CORDA-1948]: Demobench profile load fails with stack dump -- for Corda OS 3.3 -- branch release-V3 (fix)

CONTRIBUTORS.md, docs/source/getting-set-up.rst
To be honest, I'm a Linux Mint user (which is based on Ubuntu) but however I love Linux community and I think the other major Linux distro family also deserves installation instructions.
=> Docs: Add instructions for Fedora

node/src/main/kotlin/net/corda/node/utilities/registration/NetworkRegistrationHelper.kt, node/src/test/kotlin/net/corda/node/utilities/registration/NetworkRegistrationHelperTest.kt
This is a cherry-pick PR for the: https://github.com/corda/corda/pull/3983
=> CORDA-2012 truststore copy

djvm/build.gradle, djvm/src/main/kotlin/net/corda/djvm/rewiring/SandboxClassWriter.kt
Upgrade DJVM from ASM 6.1.1 to ASM 6.2.1.
=> ENT-1906: Upgrade DJVM to use ASM 6.2.1.

core/src/main/kotlin/net/corda/core/internal/cordapp/CordappInfoResolver.kt
https://r3-cev.atlassian.net/browse/CORDA-1926
=> [CORDA-1926] Make CordappInfoResolver.withCordappInfoResolution @VisibleForTesting.

build.gradle, tools/blobinspector/build.gradle, tools/bootstrapper/build.gradle
Backport of CORDA-3370, CORDA-3354, CORDA-3321
=> CORDA-2037 - Add network bootstrapper and other tools to published binary list

docs/source/api-states.rst, docs/source/api-transactions.rst, docs/source/index.rst, docs/source/key-concepts-states.rst, docs/source/key-concepts-transactions.rst
=> Added more docs for reference states to key concepts and api docs.

node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/CordaPersistence.kt
Refactoring to reduce differences with ENT.
=> CordaPersistence class minor refactoring to align with Enterprise repo.

node/src/main/kotlin/net/corda/node/services/CoreFlowHandlers.kt, node/src/main/kotlin/net/corda/node/services/statemachine/FlowStateMachineImpl.kt, node/src/main/kotlin/net/corda/node/services/statemachine/StaffedFlowHospital.kt
https://r3-cev.atlassian.net/browse/ENT-2545
=> [ENT-2545]: Failing flow sent to Hospital does not log any ERROR's (fixed).

node-api/src/main/kotlin/net/corda/nodeapi/internal/protonwrapper/netty/SSLHelper.kt, node-api/src/test/kotlin/net/corda/nodeapi/internal/protonwrapper/netty/SSLHelperTest.kt
original PR https://github.com/corda/corda/pull/4014
=> [Cherry-Pick] CORDA-2016 Add unit tests to ensure SNI header generation will not be changed by accident

.ci/api-current.txt, core/src/main/kotlin/net/corda/core/schemas/CommonSchema.kt, core/src/main/kotlin/net/corda/core/schemas/PersistentTypes.kt, docs/source/changelog.rst, docs/source/upgrade-notes.rst, finance/src/main/kotlin/net/corda/finance/schemas/CashSchemaV1.kt, finance/src/main/kotlin/net/corda/finance/schemas/CommercialPaperSchemaV1.kt, finance/src/test/kotlin/net/corda/finance/schemas/SampleCashSchemaV1.kt, finance/src/test/kotlin/net/corda/finance/schemas/SampleCashSchemaV2.kt, finance/src/test/kotlin/net/corda/finance/schemas/SampleCashSchemaV3.kt, finance/src/test/kotlin/net/corda/finance/schemas/SampleCommercialPaperSchemaV1.kt, finance/src/test/kotlin/net/corda/finance/schemas/SampleCommercialPaperSchemaV2.kt, node/src/main/kotlin/net/corda/node/internal/schemas/NodeInfoSchema.kt, node/src/main/kotlin/net/corda/node/services/events/NodeSchedulerService.kt, node/src/main/kotlin/net/corda/node/services/identity/PersistentIdentityService.kt, node/src/main/kotlin/net/corda/node/services/keys/PersistentKeyManagementService.kt, node/src/main/kotlin/net/corda/node/services/messaging/P2PMessagingClient.kt, node/src/main/kotlin/net/corda/node/services/persistence/DBCheckpointStorage.kt, node/src/main/kotlin/net/corda/node/services/persistence/DBTransactionMappingStorage.kt, node/src/main/kotlin/net/corda/node/services/persistence/DBTransactionStorage.kt, node/src/main/kotlin/net/corda/node/services/persistence/NodeAttachmentService.kt, node/src/main/kotlin/net/corda/node/services/persistence/NodePropertiesPersistentStore.kt, node/src/main/kotlin/net/corda/node/services/transactions/BFTNonValidatingNotaryService.kt, node/src/main/kotlin/net/corda/node/services/transactions/PersistentUniquenessProvider.kt, node/src/main/kotlin/net/corda/node/services/transactions/RaftUniquenessProvider.kt, node/src/main/kotlin/net/corda/node/services/upgrade/ContractUpgradeServiceImpl.kt, node/src/main/kotlin/net/corda/node/services/vault/VaultSchema.kt, testing/test-utils/src/main/kotlin/net/corda/testing/internal/vault/DummyLinearStateSchemaV1.kt, testing/test-utils/src/main/kotlin/net/corda/testing/internal/vault/DummyLinearStateSchemaV2.kt
This should be the reverse of this: https://github.com/corda/corda/pull/3303
As it shouldn't be in v3
=> CORDA-1297 revert column nullability

node-api/src/main/kotlin/net/corda/nodeapi/internal/protonwrapper/netty/AMQPChannelHandler.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/protonwrapper/netty/AMQPClient.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/protonwrapper/netty/ConnectionChange.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/protonwrapper/netty/SSLHelper.kt, node/src/integration-test/kotlin/net/corda/node/amqp/ProtonWrapperTests.kt
original PRs:
ENT-1946, ENT-1850
https://github.com/corda/corda/pull/3225
https://github.com/corda/corda/pull/3124
=> [CHERRY-PICK] CORDA-2071 Log file filling with Artemis messages and rolling over quickly

node/src/main/resources/migration/node-notary.changelog-init.xml, node/src/main/resources/migration/node-notary.changelog-pkey.xml, node/src/main/resources/migration/node-notary.changelog-v1.xml
=> CORDA-535: Remove BFT-Smart related migration parts

core/src/test/kotlin/net/corda/core/flows/FinalityFlowTests.kt, core/src/test/kotlin/net/corda/core/flows/WithReferencedStatesFlowTests.kt, docs/source/changelog.rst, docs/source/example-code/src/main/java/net/corda/docs/java/FlowCookbook.java, docs/source/example-code/src/main/java/net/corda/docs/java/tutorial/helloworld/IOUFlow.java, docs/source/example-code/src/main/java/net/corda/docs/java/tutorial/twoparty/IOUFlow.java, docs/source/example-code/src/main/kotlin/net/corda/docs/kotlin/tutorial/helloworld/IOUFlow.kt, docs/source/example-code/src/main/kotlin/net/corda/docs/kotlin/tutorial/twoparty/IOUFlow.kt, docs/source/tutorial-attachments.rst, node/src/integration-test/kotlin/net/corda/node/modes/draining/FlowsDrainingModeContentionTest.kt, node/src/integration-test/kotlin/net/corda/node/services/events/ScheduledFlowIntegrationTests.kt, node/src/integration-test/kotlin/net/test/cordapp/v1/FlowCheckpointCordapp.kt, node/src/test/kotlin/net/corda/node/modes/draining/ScheduledFlowsDrainingModeTest.kt, node/src/test/kotlin/net/corda/node/services/FinalityHandlerTest.kt, node/src/test/kotlin/net/corda/node/services/ServiceHubConcurrentUsageTest.kt, node/src/test/kotlin/net/corda/node/services/events/ScheduledFlowTests.kt, node/src/test/kotlin/net/corda/node/services/vault/VaultSoftLockManagerTest.kt, samples/network-verifier/src/main/kotlin/net/corda/verification/TestCommsFlow.kt, samples/network-verifier/src/main/kotlin/net/corda/verification/TestNotaryFlow.kt
These are changes extracted out from a larger piece of work.
=> Code cleanup, mostly shortening long lines

build.gradle, constants.properties, docs/source/cordapp-build-systems.rst, experimental/notary-bft-smart/build.gradle, experimental/notary-raft/build.gradle, finance/build.gradle, samples/attachment-demo/build.gradle, samples/bank-of-corda-demo/build.gradle, samples/cordapp-configuration/build.gradle, samples/cordapp-configuration/src/main/kotlin/net/corda/configsample/GetStringConfigFlow.kt, samples/irs-demo/build.gradle, samples/irs-demo/cordapp/build.gradle, samples/network-verifier/build.gradle, samples/notary-demo/build.gradle, samples/simm-valuation-demo/build.gradle, samples/simm-valuation-demo/contracts-states/build.gradle, samples/simm-valuation-demo/flows/build.gradle, samples/trader-demo/build.gradle
https://r3-cev.atlassian.net/browse/CORDA-2077
=> [CORDA-2077] Use latest gradle plugin version (4.0.32), set target version in core and sample CorDapps

node/src/integration-test/kotlin/net/corda/node/flows/FlowRetryTest.kt
We'd theorised a bug to do with re-generating flow IDs but the tests prove it doesn't exist.  Going to commit the tests to ensure we do not regress.
=> CORDA-1707 Tests to prove bug doesn't exist.

experimental/notary-bft-smart/build.gradle, experimental/notary-raft/build.gradle
=> CORDA-535: Make notary implementations publishable

docs/source/design/threat-model/corda-threat-model.md
Changed order of repudiation and information disclosure in bullet point list,
to align to STRIDE .
=> fixed order of repudiation and information disclos

build.gradle
Due to Kotlin update, OWASP needs a bump as well.
=> CORDA-2111: Update OWASP to latest version after kotlin update

node/src/test/kotlin/net/corda/node/CordaRPCOpsImplTest.kt
There were no tests around `CordaRPCOps.uploadAttachmentWithMetadata`
therefore tests have been added to verify that the function works
and saves the correct metadata to the vault
=> Add tests for `CordaRPCOps.uploadAttachmentWithMetadata`

common/validation/src/main/kotlin/net/corda/common/validation/internal/Validated.kt, config/dev/log4j2.xml, docs/source/changelog.rst, docs/source/running-a-node.rst, node/build.gradle, node/src/main/kotlin/net/corda/node/NodeCmdLineOptions.kt, node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt, node/src/main/kotlin/net/corda/node/internal/subcommands/ClearNetworkCacheCli.kt, node/src/main/kotlin/net/corda/node/internal/subcommands/GenerateNodeInfoCli.kt, node/src/main/kotlin/net/corda/node/internal/subcommands/GenerateRpcSslCertsCli.kt, node/src/main/kotlin/net/corda/node/internal/subcommands/InitialRegistrationCli.kt, node/src/main/kotlin/net/corda/node/internal/subcommands/ValidateConfigurationCli.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/DriverDSLImpl.kt
https://r3-cev.atlassian.net/browse/CORDA-1763
=> [CORDA-1763]: Add node CLI option for validating configuration.

client/rpc/src/main/kotlin/net/corda/client/rpc/CordaRPCClient.kt, client/rpc/src/main/kotlin/net/corda/client/rpc/internal/serialization/amqp/AMQPClientSerializationScheme.kt, node/src/main/kotlin/net/corda/node/internal/Node.kt, node/src/main/kotlin/net/corda/node/serialization/amqp/AMQPServerSerializationScheme.kt, serialization-deterministic/src/main/kotlin/net/corda/serialization/internal/AttachmentsClassLoaderBuilder.kt, serialization/src/main/kotlin/net/corda/serialization/internal/CheckpointSerializationScheme.kt, serialization/src/main/kotlin/net/corda/serialization/internal/SerializationScheme.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/AMQPSerializationScheme.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/SerializerFactory.kt, serialization/src/test/kotlin/net/corda/serialization/internal/amqp/StaticInitialisationOfSerializedObjectTest.kt
=> ENT-2659 Eliminate lots of contention in serialization

README.md
=> CORDA-2170 Add Apache 2 license badge

node/src/integration-test/kotlin/net/corda/node/flows/FlowOverrideTests.kt, node/src/integration-test/kotlin/net/corda/node/services/messaging/ArtemisMessagingTest.kt
Explicit node names in the FlowOverrideTests integration test.
=> Minor refactoring to align to Ent repo.

core/src/test/kotlin/net/corda/core/JarSignatureTestUtils.kt, core/src/test/kotlin/net/corda/core/internal/JarSignatureCollectorTest.kt
The unit test got lost during merge conflict resolution - commit 391c6bf66fc31f2609f787298ef1ce77ffe7fb73.
=> Undo unit test deletion which got lost in merge

docs/source/api-flows.rst
changing "areshared" to "are shared"
=> Fixing a single typo

config/dev/log4j2.xml, node/src/integration-test/kotlin/net/corda/node/logging/ErrorCodeLoggingTests.kt, node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt, node/src/main/kotlin/net/corda/node/internal/subcommands/ValidateConfigurationCli.kt, node/src/main/resources/log4j2.component.properties, tools/cliutils/src/main/kotlin/net/corda/cliutils/CordaCliWrapper.kt, tools/cliutils/src/main/kotlin/net/corda/cliutils/CordaLog4j2ConfigFactory.kt, tools/cliutils/src/main/resources/log4j2.component.properties
https://r3-cev.atlassian.net/browse/ENT-2678
These are the necessary OS changes. Second PR to follow for Enterprise after porting these across.
=> [ENT-2678] PluginRegistrationTest is failing (fix) (OS part)

.ci/api-current.txt, core/src/main/kotlin/net/corda/core/contracts/StatePointer.kt, core/src/main/kotlin/net/corda/core/contracts/Structures.kt, core/src/main/kotlin/net/corda/core/internal/StatePointerSearch.kt, core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt, docs/source/api-states.rst, docs/source/design/linear-pointer/design.md, node/src/test/kotlin/net/corda/node/services/transactions/ResolveStatePointersTest.kt, samples/trader-demo/src/integration-test/kotlin/net/corda/traderdemo/TraderDemoTest.kt
Introduces the `StatePointer` concept. See design doc for more info.
Outstanding bits:
1. Tests.
2. Examples.
Will do these once the design is approved.
going forward, I'd like to experiment with making resolved pointers easier to work with.
=> StatePointer

.ci/api-current.txt
Added new static method to API Stability check (related to CORDA-2011/CORDA-2057)
=> Update api-current (related to CORDA-2011/CORDA-2057)

constants.properties
Update to  corda-grade-plugins version 4.0.34.
=> Update to latest corda-grade-plugins version

node/src/main/kotlin/net/corda/node/utilities/registration/NetworkRegistrationHelper.kt
This is the fix for the CRL issuer lookup.
=> CORDA-2205 Fixing CRL issuer store lookup

core/src/main/kotlin/net/corda/core/flows/NotaryError.kt, core/src/main/kotlin/net/corda/core/internal/notary/NotaryServiceFlow.kt, core/src/main/kotlin/net/corda/core/internal/notary/NotaryUtils.kt, core/src/main/kotlin/net/corda/core/internal/notary/SinglePartyNotaryService.kt, core/src/main/kotlin/net/corda/core/transactions/SignedTransaction.kt, node/src/main/kotlin/net/corda/node/services/transactions/NonValidatingNotaryFlow.kt, node/src/main/kotlin/net/corda/node/services/transactions/ValidatingNotaryFlow.kt, node/src/test/kotlin/net/corda/node/services/TimedFlowTests.kt, samples/notary-demo/src/main/kotlin/net/corda/notarydemo/MyCustomNotaryService.kt
- Refactored notary flows to reduce validation code duplication
- Improved notarisation error handling to provide more helpful responses to the client
=> CORDA-2190: Improve notary service flow exception handling

core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
=> removed dupe companion object.

core/src/main/kotlin/net/corda/core/node/ServiceHub.kt, docs/source/api-persistence.rst, node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/DatabaseTransaction.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/RestrictedEntityManager.kt, node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt, node/src/test/kotlin/net/corda/node/services/persistence/ExposeJpaToFlowsTests.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/MockServices.kt
* Not sure where the `RestrictedEntityManager` should sit. It must be in Core somewhere, I guess.
* Not sure if using `contextTransaction` is the right way to do things here
=> Expose JPA to flows

client/rpc/src/main/kotlin/net/corda/client/rpc/internal/RPCClientProxyHandler.kt, node/src/integration-test/kotlin/net/corda/node/services/rpc/NodeHandleTests.kt
https://r3-cev.atlassian.net/browse/CORDA-2208
=> [CORDA-2208]: NodeHandles hashcode attemps an RPC invocation. (fix)

tools/shell/src/main/kotlin/net/corda/tools/shell/InteractiveShell.kt
https://r3-cev.atlassian.net/browse/CORDA-2123
=> [CORDA-2123]: Unhandled IndexOutOfBoundsException for malformed Shell commands. (fix)

node/src/integration-test/kotlin/net/corda/node/logging/ErrorCodeLoggingTests.kt, tools/cliutils/src/main/kotlin/net/corda/cliutils/CordaVersionProvider.kt, tools/cliutils/src/main/kotlin/net/corda/cliutils/ErrorCodeRewritePolicy.kt, tools/cliutils/src/main/kotlin/net/corda/cliutils/ExceptionsErrorCodeFunctions.kt
https://r3-cev.atlassian.net/browse/CORDA-2172
=> [CORDA-2172]: Add link to error-codes-webapp in Corda.

tools/demobench/src/main/kotlin/net/corda/demobench/views/NodeTabView.kt
https://r3-cev.atlassian.net/browse/CORDA-2203
Screenshot of the new Demobench Notary type selection:
=> [CORDA-2203]: Demobench ends up with a stuck tab when you unselect notary type for the first node. (fix)

.ci/api-current.txt, node-api/src/main/kotlin/net/corda/nodeapi/internal/network/NetworkBootstrapper.kt
This pull request attempts to fix [CORDA-2219](https://r3-cev.atlassian.net/browse/CORDA-2219)
=> [CORDA-2219] Show message if CorDapp already exists

build.gradle
Have done some testing on windows and linux and everything seems fine.
=> CORDA-2197: Update picocli to latest version

docs/source/cli-ux-guidelines.rst
=> [CORDA-2004]: Update CLI UX guidelines for backwards compatibility

docs/source/getting-set-up.rst, docs/source/tutorial-cordapp.rst
Also updates Getting Set Up instructions to match master.
=> Updates Example CorDapp instructions to point to Samples repo.

node/src/integration-test/kotlin/net/corda/node/AddressBindingFailureTests.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/DriverDSLImpl.kt
https://r3-cev.atlassian.net/browse/CORDA-1877
=> [CORDA-1877]: Failures due to port clashes should result in an understandable error message. (fix)

docs/source/changelog.rst, docs/source/release-notes.rst, docs/source/upgrade-notes.rst
Change log, release notes and upgrade notes for signing CorDapp's JAR by build system.
=> CORDA-1915 Release notes for build system signing CorDapp JARs. 

build.gradle, tools/cliutils/build.gradle, tools/cliutils/src/main/kotlin/net/corda/cliutils/CordaCliWrapper.kt, tools/cliutils/src/main/kotlin/net/corda/cliutils/InstallShellExtensionsParser.kt
https://r3-cev.atlassian.net/browse/CORDA-2211
=> [CORDA-2211]: Added error for older bash versions when attempting to install shell extensions.

core/src/main/kotlin/net/corda/core/transactions/MissingContractAttachments.kt, core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
=> ENT-2675 Improve error message

common/configuration-parsing/src/main/kotlin/net/corda/common/configuration/parsing/internal/Configuration.kt, common/configuration-parsing/src/main/kotlin/net/corda/common/configuration/parsing/internal/Properties.kt, common/configuration-parsing/src/main/kotlin/net/corda/common/configuration/parsing/internal/Schema.kt, common/configuration-parsing/src/main/kotlin/net/corda/common/configuration/parsing/internal/Specification.kt, common/configuration-parsing/src/main/kotlin/net/corda/common/configuration/parsing/internal/Utils.kt, common/configuration-parsing/src/test/kotlin/net/corda/common/configuration/parsing/internal/PropertyTest.kt, common/configuration-parsing/src/test/kotlin/net/corda/common/configuration/parsing/internal/PropertyValidationTest.kt, common/configuration-parsing/src/test/kotlin/net/corda/common/configuration/parsing/internal/SpecificationTest.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/config/ConfigUtilities.kt, node/src/main/kotlin/net/corda/node/internal/subcommands/ValidateConfigurationCli.kt
https://r3-cev.atlassian.net/browse/CORDA-2244
=> [CORDA-2244]: Allow `map` and `mapValid` on entire lists wrt configuration parsing

testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/DriverDSLImpl.kt
Backport of https://github.com/corda/enterprise/pull/1571
=> [ENT-2539] backport

testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/TestCordappsUtils.kt
Resolves [CORDA-2189](https://r3-cev.atlassian.net/browse/CORDA-2189) by manually adding the manifest file to the jar and giving it timestamp `Instant.EPOCH` so there are no differences between the jars generated for different nodes.
I confirm that my PR is in agreement with the [Developer's Certificate of Origin](https://github.com/corda/corda/blob/master/CONTRIBUTING.md#developer-certificate-of-origin), https://developercertificate.org/.
=> [CORDA-2189] Fix non deterministic manifest file timestamp

build.gradle, constants.properties, samples/simm-valuation-demo/contracts-states/build.gradle, samples/simm-valuation-demo/flows/build.gradle
New version contains new development key for JAR signing.
=> Update to corda-gradle-plugins v4.0.36

serialization/src/main/kotlin/net/corda/serialization/internal/amqp/AMQPSerializationScheme.kt
=> CORDA-2248 Remove spring boot hack.

client/rpc/src/main/kotlin/net/corda/client/rpc/internal/serialization/amqp/AMQPClientSerializationScheme.kt, node/src/main/kotlin/net/corda/node/serialization/amqp/AMQPServerSerializationScheme.kt, node/src/test/kotlin/net/corda/node/internal/serialization/RoundTripObservableSerializerTests.kt, node/src/test/kotlin/net/corda/node/internal/serialization/testutils/AMQPTestSerialiationScheme.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/AMQPSerializationScheme.kt, serialization/src/test/kotlin/net/corda/serialization/internal/amqp/AbstractAMQPSerializationSchemeTest.kt
Use synchronized SerializerFactory caches.
=> Fix cache races.

docs/source/cordapp-build-systems.rst
Documentation for new task in corda-gradle-plugins.
=> Document standalone signJar task (related to CORDA-1915).

core/src/main/kotlin/net/corda/core/contracts/TransactionVerificationException.kt
=> ENT-2320 Fix comment

node/src/main/kotlin/net/corda/node/services/statemachine/FlowStateMachineImpl.kt
https://r3-cev.atlassian.net/browse/CORDA-2272
=> [CORDA-2272]: Recovering from StackOverflowErrors and given time to async logger to flush.

node/src/main/kotlin/net/corda/node/services/statemachine/FlowStateMachineImpl.kt
=> Fixed Thread.sleep() issue inside Fiber.

node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt, node/src/main/kotlin/net/corda/node/services/statemachine/StaffedFlowHospital.kt
https://r3-cev.atlassian.net/browse/CORDA-2276
=> [CORDA-2276]: FlowMonitor repeatedly / indefinitely logs flows in the flow hospital. (fix)

node/src/main/resources/migration/node-core.changelog-master.xml, node/src/main/resources/migration/node-core.changelog-v9.xml
=> Add liquibase scripts for network parameters storage

core/src/main/kotlin/net/corda/core/flows/FlowLogic.kt
https://r3-cev.atlassian.net/browse/CORDA-2273
=> [CORDA-2273]: Easy to create StackOverflowError using subflows. (fix)

core/src/test/kotlin/net/corda/core/contracts/ContractHierarchyTest.kt
https://r3-cev.atlassian.net/browse/CORDA-2161
=> [CORDA-2161]: Seems to be working. Leaving the test to ensure no future regressions.

core/src/main/kotlin/net/corda/core/serialization/SerializationAPI.kt
Fix wrong comment.
@distributedleetravis, can you please merge this if the comment is correct?
=> Fix Comment

serialization/src/main/kotlin/net/corda/serialization/internal/model/LocalTypeInformationBuilder.kt
As revealed by [CORDA-2284](https://r3-cev.atlassian.net/browse/CORDA-2284), in the case where we have a property with a getter and a constructor parameter, but no backing field, we need to make sure that the cases match between the property name and the parameter name.
=> CORDA-2284 fix constructor-paired property name to constructor parameter name

node-api/src/main/kotlin/net/corda/nodeapi/internal/cryptoservice/CryptoService.kt, node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt, node/src/main/kotlin/net/corda/node/services/keys/cryptoservice/BCCryptoService.kt, node/src/main/kotlin/net/corda/node/utilities/registration/NetworkRegistrationHelper.kt, node/src/test/kotlin/net/corda/node/services/keys/cryptoservice/BCCryptoServiceTests.kt
https://r3-cev.atlassian.net/browse/ENT-2821
=> [ENT-2821] Make the default schemes for TLS and identity available from the CryptoService interface

node/src/main/kotlin/net/corda/node/utilities/AppendOnlyPersistentMap.kt, node/src/test/kotlin/net/corda/node/services/persistence/AppendOnlyPersistentMapTest.kt
I've verified the new tests fail with the old code.  New (non-test) code is a very small diff.
=> CORDA-2293 fix append only map getIfCached when Missing

docs/source/changelog.rst
=> CORDA-2289 changelog entry for transaction mapping table.

node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt, node/src/test/kotlin/net/corda/node/internal/CordaServiceTest.kt
https://r3-cev.atlassian.net/browse/CORDA-2296
=> [CORDA-2296] Improve initialization of criteriaBuilder in NodeVaultService.

docs/source/changelog.rst, samples/irs-demo/web/src/main/resources/static/js/services/NodeApi.js
https://r3-cev.atlassian.net/browse/CORDA-2213
=> [CORDA-2213]: IRS Demo is unable to simulate future dates (fix).

webserver/build.gradle
Minor change to add missing compilation dependency to webserver
=> Add missing dependency to corda webserver

.ci/api-current.txt, core/src/main/kotlin/net/corda/core/node/services/vault/QueryCriteriaUtils.kt, node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt
https://r3-cev.atlassian.net/browse/CORDA-2007
=> [CORDA-2007]: Fixed problematic max page size.

serialization/src/main/kotlin/net/corda/serialization/internal/amqp/LocalSerializerFactory.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/TransformsSchema.kt
=>  ENT-2848 Put some caching back into serialization transforms lookup.

CONTRIBUTORS.md, finance/src/main/resources/net/corda/finance/utils/cities.txt
Add Troyan, Vratsa, Elena to cities
=> Add Troyan, Vratsa, Elena to cities

node-api/src/main/kotlin/net/corda/nodeapi/internal/cryptoservice/CryptoService.kt
https://r3-cev.atlassian.net/browse/ENT-2844
=> backport ENT-2844

node/src/main/kotlin/net/corda/node/services/persistence/DBCheckpointStorage.kt
Fix toString of object DBCheckPoint  to remove printing of array in DEBUG log
Closing Issue  https://github.com/corda/corda/issues/4337
=> Modify toString of DBCheckPoint

docs/source/corda-configuration-file.rst, node/src/integration-test/kotlin/net/corda/services/messaging/AdditionP2PAddressModeTest.kt, node/src/main/kotlin/net/corda/node/services/config/NodeConfiguration.kt, node/src/main/kotlin/net/corda/node/services/config/NodeConfigurationImpl.kt
https://r3-cev.atlassian.net/browse/CORDA-2323
=> [CORDA-2323]: Make `detectPublicIp` disabled by default.

CONTRIBUTORS.md, docs/source/tutorial-cordapp.rst
Continuation of [#162](https://github.com/corda/cordapp-example/pull/162)
=> Change IOU Example docs

core/src/main/kotlin/net/corda/core/cordapp/Cordapp.kt, core/src/main/kotlin/net/corda/core/internal/cordapp/CordappImpl.kt, core/src/main/kotlin/net/corda/core/internal/cordapp/CordappInfoResolver.kt, core/src/main/kotlin/net/corda/core/internal/cordapp/ManifestUtils.kt, core/src/test/kotlin/net/corda/core/flows/FinalityFlowTests.kt, core/src/test/kotlin/net/corda/core/internal/cordapp/CordappInfoResolverTest.kt, node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt, node/src/main/kotlin/net/corda/node/internal/cordapp/JarScanningCordappLoader.kt, node/src/main/kotlin/net/corda/node/internal/cordapp/VirtualCordapps.kt, node/src/test/kotlin/net/corda/node/internal/cordapp/JarScanningCordappLoaderTest.kt, node/src/test/kotlin/net/corda/node/services/FinalityHandlerTest.kt, testing/test-utils/src/main/kotlin/net/corda/testing/internal/InternalTestUtils.kt, testing/test-utils/src/main/kotlin/net/corda/testing/internal/MockCordappProvider.kt
Otherwise ContractAndWorkflow ends up having these two duplicated three times.
=> CORDA-1942: Moved minimumPlatformVersion and targetPlatformVersion to Cordapp

serialization/src/main/kotlin/net/corda/serialization/internal/ClientContexts.kt, serialization/src/test/kotlin/net/corda/serialization/internal/amqp/DeserializeQueryableStateTest.kt, serialization/src/test/kotlin/net/corda/serialization/internal/amqp/DeserializeQueyableStateTest.kt
https://r3-cev.atlassian.net/browse/CORDA-2330
=> [CORDA-2330] Turn on lenient mode in rpc serialization context.

samples/network-verifier/src/main/kotlin/net/corda/verification/TestCommsFlow.kt
[CORDA-2346](https://r3-cev.atlassian.net/browse/CORDA-2346)
=> [CORDA-2346] Add BelongsToContract for network-verifier's state

docs/requirements.txt
Security alert in urllib3 - update to patched version (1.32)
=> CORDA-2350 update urllib version

core/src/main/kotlin/net/corda/core/node/services/AttachmentStorage.kt, core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt, node/src/main/kotlin/net/corda/node/services/persistence/NodeAttachmentService.kt, testing/test-utils/src/main/kotlin/net/corda/testing/services/MockAttachmentStorage.kt
=> ENT-2848 More contract attachment caching to avoid database queries slowing the node down

node/src/integration-test/kotlin/net/corda/node/CordappConstraintsTests.kt
Flaky test: CordappConstraintsTests.issue cash using hash and signature constraints
=> CORDA-2366 - Adjust assertions to cater for any ordering of results.

node/src/main/kotlin/net/corda/node/cordapp/CordappLoader.kt, node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt, node/src/main/kotlin/net/corda/node/internal/cordapp/JarScanningCordappLoader.kt
This is an attempted follow-up to https://github.com/corda/corda/pull/4461.
=> Closing the app class loader on node shutdown

node/src/main/kotlin/net/corda/node/utilities/registration/NetworkRegistrationHelper.kt
OS port from Enterprise, please see: corda/enterprise#1694
=> ENT-2847: Ent port: Make logging pluggable in `NetworkRegistrationHelper`.

serialization/src/main/kotlin/net/corda/serialization/internal/ClientContexts.kt, serialization/src/main/kotlin/net/corda/serialization/internal/ServerContexts.kt, serialization/src/test/kotlin/net/corda/serialization/internal/amqp/DeserializeQueryableStateTest.kt
https://r3-cev.atlassian.net/browse/CORDA-2364
=> [CORDA-2364] Make the class carpenter for RPC lenient by default.

node/src/main/kotlin/net/corda/node/services/persistence/NodeAttachmentService.kt, node/src/test/kotlin/net/corda/node/CordaRPCOpsImplTest.kt, node/src/test/kotlin/net/corda/node/services/persistence/NodeAttachmentServiceTest.kt
https://r3-cev.atlassian.net/browse/CORDA-2376
=> [CORDA-2376]: Unable to make contract attachment trusted if it was received via network (fixed).

node/src/main/kotlin/net/corda/node/internal/cordapp/CordappProviderImpl.kt
Remove whitelist constraint warnings on node startup.
=> Remove whitelist constraint warnings.

node/src/integration-test/kotlin/net/corda/node/logging/ErrorCodeLoggingTests.kt, node/src/integration-test/kotlin/net/corda/node/logging/IssueCashLoggingTests.kt, node/src/integration-test/kotlin/net/corda/node/logging/PackageUtils.kt, node/src/main/kotlin/net/corda/node/services/api/IdentityServiceInternal.kt
https://r3-cev.atlassian.net/browse/CORDA-2387
@rick-r3 I'll have a look at these confidential identities as a separate task.
=> [CORDA-2387]: Seeing warnings for "Double insert in net.corda.node.utilities.AppendOnlyPersistentMap" (fixed)

node/src/integration-test/kotlin/net/corda/node/CordappConstraintsTests.kt, node/src/integration-test/kotlin/net/corda/node/flows/AsymmetricCorDappsTests.kt, node/src/integration-test/kotlin/net/corda/node/flows/FlowCheckpointVersionNodeStartupCheckTest.kt, node/src/integration-test/kotlin/net/corda/node/services/AttachmentLoadingTests.kt, node/src/integration-test/kotlin/net/corda/testMessage/MessageState.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/DriverDSLImpl.kt
This PR removes test classes from the driver classpath to make it identical to a normal node.
Also fixes tests that are affected by this change.
=> Attempt to fix master

core/src/main/kotlin/net/corda/core/contracts/StatePointer.kt
They were not data classes before... Not sure why but they probably should be!
=> CORDA-2098: State pointers are now comparable.

serialization/src/main/kotlin/net/corda/serialization/internal/amqp/custom/OptionalSerializer.kt
no changes to code, just correct documentation in method
https://github.com/corda/corda/issues/3531 - is already solved, standard deseralizers are there in master branch only
1. integration tests are failing since teamcity build 3435 - CORDA-2384 - Fix driver classpath
=> documentation adapted for OptionalSerializer

core/src/main/kotlin/net/corda/core/node/services/vault/QueryCriteria.kt
https://r3-cev.atlassian.net/browse/CORDA-2394
=> [CORDA-2394]: Fixed ABI issue with VaultQueryCriteria.

core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
This PR uses a decorator and reflection to apply `AttachmentURLStreamHandlerFactory` when `URL.setURLStreamHandlerFactory` has already been called. 
This seems to be the only solution for JDK8 that keeps resource resolution contained within `URL`. A quick search suggests that, starting with Java 9, either adding `--add-opens` or going through an extension/service loader will be needed.
I state that this PR is in accordance with the [Developer's Certificate of Origin](https://github.com/corda/corda/blob/master/CONTRIBUTING.md#developer-certificate-of-origin).
=> fixed #4511

docs/source/flow-overriding.rst
https://r3-cev.atlassian.net/browse/CORDA-2408
=> [CORDA-2408]: Formatting on Flow Overriding page wrong - code not rendering correctly (fixed).

docs/source/app-upgrade-notes.rst, docs/source/example-code/src/main/java/net/corda/docs/java/FinalityFlowMigration.java, docs/source/example-code/src/main/kotlin/net/corda/docs/kotlin/FinalityFlowMigration.kt
Added additional code to the example code snippets in the Finality Flow Migration section in the Upgrade guide for Corda 4.0.
- [ ✅ ] Have you run the unit, integration and smoke tests as described [here](https://docs.corda.net/head/testing.html)?
- [ ✅ ] If you added public APIs, did you write the JavaDocs?
- [ ✅] If the changes are of interest to application developers, have you added them to the [changelog](https://github.com/corda/corda/blob/master/docs/source/changelog.rst), and potentially the [release notes](https://github.com/corda/corda/blob/master/docs/source/release-notes.rst)?
- [ ✅] If you are contributing for the first time, please read the agreement in …
=> Finality flow migration doc update

node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/CordaPersistence.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/DatabaseTransaction.kt
=> Add additional transactionality check.

finance/contracts/build.gradle
Accidentally disabled when attempting to align OS and ENT finance contracts jar.
=> Re-enable signing of finance contracts jar.

node/src/test/kotlin/net/corda/notary/experimental/bftsmart/BFTNotaryServiceTests.kt
=> Exclude BFT smart tests from the build

client/rpc/src/main/kotlin/net/corda/client/rpc/PermissionException.kt, core/src/main/kotlin/net/corda/core/internal/cordapp/CordappImpl.kt
https://r3-cev.atlassian.net/browse/CORDA-2403
=> [CORDA-2403] Fix API breakage: PermissionException and CordappImpl constructor

core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
For reference, the original changes were https://github.com/corda/corda/pull/4394.
=> Avoid TransactionBuilder behaviour change for v3 or below.

docs/source/design/data-model-upgrades/migrate-to-signature-constraint.md, docs/source/design/versioning/contract-versioning.md
- Contract versioning
- Hash to Signature constraints migration
=> Merge corda private design documents

node/src/integration-test/kotlin/net/corda/node/flows/FlowCheckpointVersionNodeStartupCheckTest.kt
=> Increase timeout

node/src/integration-test/kotlin/net/corda/node/services/network/NetworkMapTest.kt
Adds a small loop to make sure the nodeInfo gets really removed.
=> Fix flaky test.

docs/source/docker-image.rst, docs/source/index.rst, docs/source/release-notes.rst
Also moves the Corda Network section higher in the toctree.
=> Mention Docker images in the release notes.

docs/source/node-database.rst
=> Document connection pool configuration.

docs/source/changelog.rst
Do we need to expand on this in the release notes?
=> ENT-2822: Minor – add a note about experimental notary upgradability

core/src/main/kotlin/net/corda/core/node/services/vault/QueryCriteria.kt
Port of #4585.
(cherry picked from commit 498db538d7c755cefe8aa5b0b99d21241818f2b5)
=> CORDA-2442: Added wither methods to the vault query classes

tools/shell/src/main/kotlin/net/corda/tools/shell/utlities/ANSIProgressRenderer.kt
* Fix stdout renderer to swap out correctly named appender.
Also fix two compiler warnings
* Add clearer exception when console appender cannot be found
* Change error displayed when appender not found to warning
* Remove type declaration on separate line
Backport of https://github.com/corda/corda/pull/4582
=> [CORDA-2441] Fix Stdout progress renderer to swap out correct appender (#4582)

docs/source/api-vault-query.rst, docs/source/app-upgrade-notes.rst, docs/source/changelog.rst, node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt, node/src/test/kotlin/net/corda/node/services/vault/NodeVaultServiceTest.kt, node/src/test/kotlin/net/corda/node/services/vault/VaultQueryTests.kt, testing/test-utils/src/main/kotlin/net/corda/testing/internal/vault/VaultFiller.kt
Backport of CORDA-2432 to release/4. See #4577
=> [CORDA-2432] Update documentation for filtering by state relevancy in vault queries

tools/shell/src/main/kotlin/net/corda/tools/shell/utlities/ANSIProgressRenderer.kt
=> CORDA-2445 print out the underlying error when an RPC call fails

build.gradle, docs/source/changelog.rst
Update postgresql to latest version (42.2.5)
=> ENT-2945 Update postgresql dependency

client/jfx/src/main/kotlin/net/corda/client/jfx/model/NodeMonitorModel.kt, core/src/main/kotlin/net/corda/core/node/services/VaultService.kt, core/src/test/kotlin/net/corda/core/flows/ReferencedStatesFlowTests.kt, core/src/test/kotlin/net/corda/core/node/VaultUpdateTests.kt, node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt
Attempt at fixing the issue whereby states in the references list are not persisted.
Clearly there's still more work to do but in the interests of time, I won't bother with it if this route is a no-go. 
Cheers
=> CORDA-2497 fix

testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/TestCordappImpl.kt
Small change to fix: https://ci-master.corda.r3cev.com/viewLog.html?buildId=140738&buildTypeId=Corda_BuildWindowsTest
=> CORDA-2345: Fix Windows build

docs/source/changelog.rst
=> ENT-2822: Add a note about experimental notary upgradability

tools/demobench/build.gradle, tools/demobench/src/main/kotlin/net/corda/demobench/plugin/CordappController.kt
=> CORDA-2510: Added missing confidential-identities CorDapp to DemoBench (#4636)

docs/source/network-map.rst
=> [Backport] - Improve documentation surrounding network parameter updates/flag day

docs/source/node-explorer.rst
JIRA: [CORDA-2419](https://r3-cev.atlassian.net/browse/CORDA-2419)
Backport of https://github.com/corda/corda/pull/4659
=>  CORDA-2419 - JavaFX requirement for Node Explorer

node/src/integration-test/kotlin/net/corda/node/services/network/NetworkMapTest.kt
Merged three tests into one to avoid repeating the same node startups. The assertions the original tests made can be done in one test without any contamination.
=> Made NetworkMapTest leaner

node/src/main/kotlin/net/corda/node/services/transactions/SimpleNotaryService.kt
Previously it used to log the mode on every notarisation request, which creates a lot of noise in the logs.
=> CORDA-2524: Minor – reduce notary service logging noise

node/src/integration-test/java/net/corda/serialization/reproduction/GenericReturnFailureReproductionIntegrationTest.java, node/src/integration-test/java/net/corda/serialization/reproduction/SuperSimpleGenericFlow.java, tools/shell/src/integration-test/kotlin/net/corda/tools/shell/HashLookupCommandTest.kt, tools/shell/src/integration-test/kotlin/net/corda/tools/shell/InteractiveShellIntegrationTest.kt, tools/shell/src/integration-test/kotlin/net/corda/tools/shell/SSHServerTest.kt, tools/shell/src/test/kotlin/net/corda/tools/shell/InteractiveShellTest.kt
This is a backport of changes made when merging OS to ENT and fixing integration tests.
=> Backport merge fixes added to ENT

docs/source/corda-configuration-file.rst
=> ENT-2822: Update notary configuration docs

core/src/test/kotlin/net/corda/core/flows/ReferencedStatesFlowTests.kt, node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt
Should be straightforward to review. A one-liner change in the vault.
Added a test to prove it works.
=> CORDA-2531 State mappings are now also updated for new reference states.

core/src/main/kotlin/net/corda/core/contracts/AttachmentConstraint.kt
Add logging to constraints checking to indicate reason of failure.
=> CORDA-2514 Constraints checking failures do not provide indication of cause

core/src/main/kotlin/net/corda/core/internal/TransactionVerifierServiceInternal.kt
Verification logic needs to use the correct Attachment in a hash to signature constraint auto-switch:
- signed for Signature constrained state (OUTPUT)
- unsigned for Hash constrained state (INPUT)
Note: the previous logic was working correctly only under certain conditions.
This fix has been validated against the QA TST: https://r3-cev.atlassian.net/browse/R3T-1560
=> CORDA-2515 Fix bug in verifier for has to signature constraints (auto-migration).

core/src/test/kotlin/net/corda/core/flows/ReferencedStatesFlowTests.kt, node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt
* State mappings are now also updated for new reference states.
Added a test to prove the above works.
* Addressed Rick's review comments.
=> CORDA-2531 - State mappings are now also updated for new reference states. (#4681)

core/src/main/kotlin/net/corda/core/flows/NotaryFlow.kt, core/src/main/kotlin/net/corda/core/flows/SendTransactionFlow.kt, core/src/main/kotlin/net/corda/core/internal/DigitalSignatureWithCert.kt, core/src/main/kotlin/net/corda/core/internal/FetchDataFlow.kt, core/src/main/kotlin/net/corda/core/internal/NetworkParametersServiceInternal.kt, core/src/main/kotlin/net/corda/core/internal/ResolveTransactionsFlow.kt, core/src/test/kotlin/net/corda/core/internal/NetworkParametersResolutionTest.kt, core/src/test/kotlin/net/corda/core/internal/ResolveTransactionsFlowTest.kt, node/src/main/kotlin/net/corda/node/internal/DBNetworkParametersStorage.kt, node/src/main/kotlin/net/corda/node/services/network/NetworkMapUpdater.kt, node/src/test/kotlin/net/corda/node/services/network/NetworkMapUpdaterTest.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/InternalMockNetwork.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/MockNetworkParametersService.kt
original PR https://github.com/corda/corda/pull/4674
=> CORDA-2520 Cherry pick

core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt, core/src/test/kotlin/net/corda/core/transactions/AttachmentsClassLoaderTests.kt
=> CORDA-2536 Tighten no overlap check.

core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt, core/src/test/kotlin/net/corda/core/transactions/AttachmentsClassLoaderTests.kt
backport of https://github.com/corda/corda/pull/4690
=> Tighten no overlap check. (#4690)

core/src/main/kotlin/net/corda/core/internal/TransactionVerifierServiceInternal.kt
=> CORDA-2515 Fix bug in verifier for has to signature constraints (auto-migration)

.ci/api-current.txt
Update API file, based on v4 release.
Already backported to RC, see PR: https://github.com/corda/corda/pull/4660
=> [CORDA-2518] - Refresh api-current.txt

node/src/integration-test/kotlin/net/corda/node/flows/FlowCheckpointVersionNodeStartupCheckTest.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/ProcessUtilities.kt
Port of commit https://github.com/corda/enterprise/commit/9b55ad2680aa41b07d66de4208443d3095fe62a2
=> Port over ENT changes

core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
Just a kdocs change. We should get this on the release branch if we can! Someone on slack pointed it though.
=> State pointers are always resolved, so the kdocs should reflect this.

docs/source/tutorial-cordapp.rst
=> Updating the docs for tutorial cordapp to reflect Spring Boot changes

docs/source/tutorial-cordapp.rst
Original PR here: https://github.com/corda/corda/pull/4705
=> [CORDA-2538] Updating the docs for tutorial cordapp to reflect Spring Boot changes

docker/src/bash/example-mini-network.sh, docker/src/bash/generate-config.sh, docker/src/bash/run-corda.sh
add example network
add ability to specify RPC password during config generation
=> CORDA-2464 - Enhance docker image, and improve usage documentation

.ci/api-current.txt, core/src/main/kotlin/net/corda/core/contracts/TransactionVerificationException.kt, core/src/main/kotlin/net/corda/core/flows/FlowLogic.kt, core/src/main/kotlin/net/corda/core/internal/AbstractAttachment.kt, core/src/main/kotlin/net/corda/core/internal/ConstraintsUtils.kt, core/src/main/kotlin/net/corda/core/internal/JarSignatureCollector.kt, core/src/main/kotlin/net/corda/core/internal/TransactionVerifierServiceInternal.kt, core/src/main/kotlin/net/corda/core/node/NetworkParameters.kt, core/src/main/kotlin/net/corda/core/node/ServiceHub.kt, core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt, core/src/main/kotlin/net/corda/core/transactions/ContractUpgradeTransactions.kt, core/src/main/kotlin/net/corda/core/transactions/LedgerTransaction.kt, core/src/main/kotlin/net/corda/core/transactions/NotaryChangeTransactions.kt, core/src/main/kotlin/net/corda/core/transactions/WireTransaction.kt, core/src/main/kotlin/net/corda/core/utilities/ProgressTracker.kt, core/src/test/kotlin/net/corda/core/contracts/ConstraintsPropagationTests.kt, core/src/test/kotlin/net/corda/core/contracts/PackageOwnershipVerificationTests.kt, core/src/test/kotlin/net/corda/core/serialization/TransactionSerializationTests.kt, core/src/test/kotlin/net/corda/core/transactions/AttachmentsClassLoaderSerializationTests.kt, core/src/test/kotlin/net/corda/core/transactions/AttachmentsClassLoaderTests.kt, core/src/test/kotlin/net/corda/core/transactions/TransactionTests.kt, node/src/integration-test/kotlin/net/corda/node/CordappConstraintsTests.kt, node/src/integration-test/kotlin/net/corda/node/services/AttachmentLoadingTests.kt, node/src/main/kotlin/net/corda/node/internal/ServicesForResolutionImpl.kt, node/src/main/kotlin/net/corda/node/services/persistence/NodeAttachmentService.kt, serialization/src/main/kotlin/net/corda/serialization/internal/carpenter/ClassCarpenter.kt, serialization/src/test/kotlin/net/corda/serialization/internal/CordaClassResolverTests.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/MockServices.kt, testing/test-utils/src/main/kotlin/net/corda/testing/internal/MockCordappProvider.kt
This PR was already approved, but against a temporary branch. However, to unblock 4.0 I'm proposing to merge it to git master in its present state (which should be OK).
Tested: TeamCity gates.
=> CORDA-2545: Merge PNO check rework to master.

docs/source/api-states.rst
Adding additional information and context to clarify reference state documentation
- [✅] Have you run the unit, integration and smoke tests as described [here](https://docs.corda.net/head/testing.html)?
- [✅ ] If you added public APIs, did you write the JavaDocs?
- [✅ ] If the changes are of interest to application developers, have you added them to the [changelog](https://github.com/corda/corda/blob/master/docs/source/changelog.rst), and potentially the [release notes](https://github.com/corda/corda/blob/master/docs/source/release-notes.rst)?
- [✅] If you are contributing for the first time, please read the agreement in [CONTRIBUTING.md](https://github.com/corda/corda/blob/master/CONTRIBUTING.md) now and add a comment …
=> Updates to API-State docs (StatePointers)

docs/source/tutorial-cordapp.rst
Updates docs to match new cordapp-example structure.
=> Updates docs to match new cordapp-example structure.

.ci/api-current.txt, core/src/main/kotlin/net/corda/core/contracts/TransactionVerificationException.kt, core/src/main/kotlin/net/corda/core/internal/TransactionVerifierServiceInternal.kt, core/src/test/kotlin/net/corda/core/contracts/ConstraintsPropagationTests.kt, docs/source/api-contract-constraints.rst, docs/source/app-upgrade-notes.rst, docs/source/changelog.rst, docs/source/release-notes.rst, docs/source/versioning.rst
See https://r3-cev.atlassian.net/browse/CORDA-2577 ticket description.
=> CORDA-2577 Disable or delete the no-downgrade rule

core/src/main/kotlin/net/corda/core/contracts/AttachmentConstraint.kt, core/src/main/kotlin/net/corda/core/contracts/TransactionVerificationException.kt, core/src/main/kotlin/net/corda/core/internal/AttachmentWithContext.kt, core/src/main/kotlin/net/corda/core/internal/ConstraintsUtils.kt, core/src/main/kotlin/net/corda/core/internal/CordaUtils.kt, core/src/main/kotlin/net/corda/core/internal/TransactionVerifierServiceInternal.kt, core/src/main/kotlin/net/corda/core/transactions/ContractUpgradeTransactions.kt, core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt, core/src/test/kotlin/net/corda/core/contracts/ConstraintsPropagationTests.kt
https://r3-cev.atlassian.net/browse/CORDA-2570
=> CORDA-2570 revert multiple contract attachments per transaction

docs/source/api-states.rst
Adding final grammar/spelling updates suggested for the API state documentation.
- [ ✅] Have you run the unit, integration and smoke tests as described [here](https://docs.corda.net/head/testing.html)?
- [ N/A ] If you added public APIs, did you write the JavaDocs?
- [ N/A ] If the changes are of interest to application developers, have you added them to the [changelog](https://github.com/corda/corda/blob/master/docs/source/changelog.rst), and potentially the [release notes](https://github.com/corda/corda/blob/master/docs/source/release-notes.rst)?
- [ ✅ ] If you are contributing for the first time, please read the agreement in [CONTRIBUTING.md](https://github.com/corda/corda/blob/master/CONTRIBUTING.md) now and add a …
=> Adding final grammatical / content changes suggested by RBG.

docs/source/changelog.rst
Porting from the release branch
=> DOCS - Changelog typo fix 

.ci/api-current.txt, client/jackson/src/test/kotlin/net/corda/client/jackson/JacksonSupportTest.kt, core-deterministic/testing/verifier/src/main/kotlin/net/corda/deterministic/verifier/MockContractAttachment.kt, core/src/main/kotlin/net/corda/core/contracts/TransactionVerificationException.kt, core/src/main/kotlin/net/corda/core/internal/AbstractAttachment.kt, core/src/main/kotlin/net/corda/core/internal/FetchDataFlow.kt, core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt, core/src/main/kotlin/net/corda/core/transactions/WireTransaction.kt, core/src/test/kotlin/net/corda/core/internal/ResolveTransactionsFlowTest.kt, core/src/test/kotlin/net/corda/core/transactions/AttachmentsClassLoaderTests.kt, core/src/test/kotlin/net/corda/core/transactions/TransactionBuilderTest.kt, core/src/test/kotlin/net/corda/core/transactions/TransactionTests.kt, node/src/main/kotlin/net/corda/node/serialization/kryo/DefaultKryoCustomizer.kt, node/src/main/kotlin/net/corda/node/services/persistence/NodeAttachmentService.kt, serialization/src/main/kotlin/net/corda/serialization/internal/GeneratedAttachment.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/custom/ContractAttachmentSerializer.kt, serialization/src/test/kotlin/net/corda/serialization/internal/ContractAttachmentSerializerTest.kt, serialization/src/test/kotlin/net/corda/serialization/internal/amqp/SerializationOutputTests.kt, testing/test-utils/src/main/kotlin/net/corda/testing/services/MockAttachmentStorage.kt
see: https://r3-cev.atlassian.net/browse/CORDA-2595
=> CORDA-2595 - check that all attachments are trusted before loading

docs/source/node-database.rst
Code wasn't formatted as code.
=> Minor fix of node database doc page formatting

core/src/main/kotlin/net/corda/core/transactions/ContractUpgradeTransactions.kt
see https://r3-cev.atlassian.net/browse/CORDA-2550
This PR adds a temporary hack to load the upgraded contract from the cordapps folder.
This needs to be properly fixed in the future.
=> CORDA-2550 use cordapp classloader for explicit upgrades

build.gradle, node-api/build.gradle, node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/CordaPersistence.kt, node/build.gradle, node/src/main/kotlin/net/corda/node/services/statemachine/FiberUtils.kt, node/src/main/kotlin/net/corda/node/services/statemachine/FlowStateMachineImpl.kt
Gradle changes are just to align OS build.gradles with ENT
=> ENT-3053 Database connection pools leaking memory on every checkpoint

docs/source/quickstart-index.rst, docs/source/release-notes.rst
Changed docs to point to Corda Network and Testnet, and tidied release notes slightly
=> CORDA-2624 Tidy docs slightly

docs/source/docker-image.rst
https://docs.corda.net/docker-image.html does not currently reflect https://hub.docker.com/u/corda
=> CORDA-2664 - Update Docker docs

testing/node-driver/build.gradle, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/TestCordappImpl.kt
=> CORDA-2668: TestCordapp – minor refactoring in jar building

.ci/api-current.txt, core/src/main/kotlin/net/corda/core/messaging/CordaRPCOps.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/RpcHelpers.kt, node/src/main/kotlin/net/corda/node/internal/CordaRPCOpsImpl.kt, tools/shell/src/main/kotlin/net/corda/tools/shell/InteractiveShell.kt
https://github.com/corda/corda/pull/4806 - backport for C4.1
=> CORDA-2669 - Reintroduce pendingFlowsCount (#4806)

node/src/main/kotlin/net/corda/node/utilities/InfrequentlyMutatedCache.kt, node/src/test/kotlin/net/corda/node/utilities/InfrequentlyMutatedCacheTest.kt
Realised these changes should be in OS.
=> ENT-3165 Backport caching changes to OS.

core/src/main/kotlin/net/corda/core/internal/LazyPool.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/CordaPersistence.kt
These are the only two I found.
=> ENT-3187 Check that we're not calling `toList` on concurrent collections

node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/SchemaMigration.kt
Liquibase appears to be non thread-safe. 
Integration tests that run multiple in-process nodes, and perform liquibase migrations, appear to be flakey. This change wraps the migration in a mutex to prevent concurrent in-process migrations.,
=> ENT-3025 Thread-safe liquibase migrations

core/src/main/kotlin/net/corda/core/internal/CordaUtils.kt, node/src/main/kotlin/net/corda/node/internal/Node.kt, node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt, node/src/test/kotlin/net/corda/node/internal/NodeTest.kt
=> Backports of small fixes raised to ENT, ENT-3075, ENT-3136

constants.properties
Update to Corda Gradle plugin 4.0.41 for Cordformation bug-fix.
=> CORDA-2697: Upgrade to Corda Gradle plugins 4.0.41.

node/src/test/kotlin/net/corda/node/services/vault/VaultQueryTests.kt
https://r3-cev.atlassian.net/browse/CORDA-2700
=> [CORDA-2700] Fix Flaky VaultQueryTests test

constants.properties, djvm/shell/djvm, djvm/shell/install, docs/source/key-concepts-djvm.rst
* Fix DJVM CLI installation and runtime scripts.
* Update DJVM documentation to explain about `RuleViolationError`.
=> CORDA-2721: Update `djvm check` documentation, and fix CLI tool installation.

docs/source/tutorial-integration-testing.rst
https://r3-cev.atlassian.net/browse/CORDA-2729
The existing docs don't include a note to tell you what you have to add to your build.gradle file if you want to write a driver based test.  I've added these now.
- [docs build, yes] Have you run the unit, integration and smoke tests as described [here](https://docs.corda.net/head/testing.html)?
- [n/a] If you added public APIs, did you write the JavaDocs?
- [n/a] If the changes are of interest to application developers, have you added them to the [changelog](https://github.com/corda/corda/blob/master/docs/source/changelog.rst), and potentially the [release notes](https://github.com/corda/corda/blob/master/docs/source/release-notes.rst)?
- [n/a] If you are contributing for …
=> CORDA-2729: Update integration testing instructions to explicitly mention node-driver dependency

docker/build.gradle
To quote Mr Punch:
> That's the way to do it!
=> NOKEY: Apply Docker Remote API plugin using Gradle's plugins block.

docs/source/clientrpc.rst, samples/bank-of-corda-demo/build.gradle, samples/bank-of-corda-demo/src/main/kotlin/net/corda/bank/IssueCash.kt, samples/bank-of-corda-demo/src/main/kotlin/net/corda/bank/api/BankOfCordaClientApi.kt
Fixed documentation snippets to refer to working compilable code.
=> CORDA-2741 RPC client connection management section not fully working

build.gradle, djvm/build.gradle, djvm/cli/build.gradle, djvm/cli/src/shell/djvm, djvm/cli/src/shell/djvm.bat, djvm/cli/src/shell/install
* Modify DJVM CLI so that it runs as executable JAR.
* Package DJVM CLI as a distributable ZIP.
* Publish DJVM CLI.
=> CORDA-2747: Package DJVM CLI for delivery.

node/src/main/kotlin/net/corda/node/services/statemachine/FiberUtils.kt, node/src/main/kotlin/net/corda/node/services/statemachine/FlowStateMachineImpl.kt
=> CORDA-2748 Always set the ThreadLocal in the Fiber from the Thread, even if not yet set in the Thread.

node/src/main/kotlin/net/corda/node/internal/subcommands/ValidateConfigurationCli.kt
JIRA ticket: [CORDA-2763](https://r3-cev.atlassian.net/browse/CORDA-2763)
=> CORDA-2763 - Log censored config at startup

node/src/main/kotlin/net/corda/node/services/network/NetworkMapUpdater.kt
Addresses [CORDA-2770](https://r3-cev.atlassian.net/browse/CORDA-2770)
=> CORDA-2770 - file watcher subscription in `NetworkMapUpdater` should be unsubscribed on close

docs/source/network-map.rst
=> CORDA-2779 - Fix Netmap REST endpoint docs

docs/source/cordapp-build-systems.rst
https://r3-cev.atlassian.net/browse/CORDA-2790
=> CORDA-2790 Clarify need for shipping contract schemas in flow JARs.

node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt
Certificates directory should only be required on node startup. For all other cases, it is optional. This was breaking initial registration in particular, which is usually responsible for creating the certificates directory.
initialiseAndRun is called from all of the different CLI commands, including but not limited to generate-node-info and initial-registration.
=> CORDA-2786: Certificates directory is only required for node startup

core/src/main/kotlin/net/corda/core/internal/InternalUtils.kt
see https://r3-cev.atlassian.net/browse/ENT-3373
=> CORDA-2803: Add default timeouts for the http connections

docs/source/building-the-docs.rst
Adding some docker docs build docs to the build docs doc.
- [docs ] Have you run the unit, integration and smoke tests as described [here](https://docs.corda.net/head/testing.html)?
- [n/a] If you added public APIs, did you write the JavaDocs?
- [n/a ] If the changes are of interest to application developers, have you added them to the [changelog](https://github.com/corda/corda/blob/master/docs/source/changelog.rst), and potentially the [release notes](https://github.com/corda/corda/blob/master/docs/source/release-notes.rst)?
- [ n/a] If you are contributing for the first time, please read the agreement in [CONTRIBUTING.md](https://github.com/corda/corda/blob/master/CONTRIBUTING.md) now and add a comment to this pull request stating that your PR is in accordance with the [Developer's …
=> CORDA-2808 docs build page

docs/source/hello-world-template.rst, docs/source/tut-two-party-contract.rst
=> Cais r3 doc fixes

core/src/main/kotlin/net/corda/core/utilities/ProgressTracker.kt, core/src/test/kotlin/net/corda/core/utilities/ProgressTrackerTest.kt
see https://r3-cev.atlassian.net/browse/CORDA-2825
=> CORDA-2825 Fix Progress Tracker bug

node/src/main/kotlin/net/corda/node/services/messaging/P2PMessagingClient.kt
This modification just pauses the P2P consumer start until the state machine has registered its message handler, which in practice requires network map checks to have finished.
=> CORDA-2824: Do not start the P2P consumer until we have at least one registered handler

docs/source/app-upgrade-notes.rst
Add java samples to `app-upgrade-notes.rst`
=> CORDA-2710 Add Java samples to upgrading to Corda 4 documentation

core/src/main/kotlin/net/corda/core/utilities/ProgressTracker.kt, core/src/test/kotlin/net/corda/core/utilities/ProgressTrackerTest.kt
backport of: https://github.com/corda/corda/pull/4986
=> CORDA-2825 Fix Progress Tracker bug (#4986)

node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt, node/src/test/kotlin/net/corda/node/internal/NodeStartupCliTest.kt
https://r3-cev.atlassian.net/browse/CORDA-2834
=> CORDA-2834 Clarify error message when base directory doesn't exist

build.gradle
=> CORDA-2519 Changed crash version to our latest.

core/src/main/kotlin/net/corda/core/contracts/Amount.kt
=> Fix missing brace

node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/SchemaMigration.kt
[CORDA-2651](https://r3-cev.atlassian.net/browse/CORDA-2651) 
Check if resources are in classpath before passing them to Liquibase. Improve exception logging.
=> CORDA-2651 Check if resources are in classpath

serialization/src/main/kotlin/net/corda/serialization/internal/model/TypeModellingFingerPrinter.kt, serialization/src/test/kotlin/net/corda/serialization/internal/amqp/TypeModellingFingerPrinterTests.kt
=> CORDA-2848 backport

experimental/nodeinfo/src/main/kotlin/net.corda.nodeinfo/NodeInfo.kt
Change parameter syntax so that it conforms to the CLI guidelines
=> CORDA-2833 change parameter syntax to conform to Corda CLI guidelines

node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/SchemaMigration.kt
=> Revert "CORDA-2651 Check if resources are in classpath (#4999)"

node/src/main/kotlin/net/corda/node/internal/artemis/BrokerJaasLoginModule.kt
=> Backport/corda 2621/log level

docs/source/upgrading-cordapps.rst
see https://github.com/corda/corda/pull/4783
=> CORDA-2456: Documentation around explicit upgrades (#4783)

core/src/main/kotlin/net/corda/core/contracts/TransactionVerificationException.kt, core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt, node/src/main/kotlin/net/corda/node/services/statemachine/FlowStateMachineImpl.kt, node/src/main/kotlin/net/corda/node/services/statemachine/StaffedFlowHospital.kt, node/src/main/kotlin/net/corda/node/services/statemachine/interceptors/DumpHistoryOnErrorInterceptor.kt
This PR is the backport of CORDA-2522 to release/4
=> [CORDA-2522] Improve error reporting around failed flows

client/rpc/src/main/kotlin/net/corda/client/rpc/internal/ReconnectingCordaRPCOps.kt, docs/source/clientrpc.rst, node/src/integration-test/kotlin/net/corda/node/services/rpc/RandomFailingProxy.kt, node/src/integration-test/kotlin/net/corda/node/services/rpc/RpcReconnectTests.kt, testing/node-driver/src/main/kotlin/net/corda/testing/driver/internal/DriverInternal.kt
=> Backport/corda 2743/reconnecting rpc

core/src/main/kotlin/net/corda/core/internal/cordapp/CordappResolver.kt
=> CORDA-2696 backport change from #4848 to release/4

docs/README.md
Changes:
* Process described in stepwise manner
* Addition of daemon selection step 
* Minor formatting and phrasing changes
=> Update README.md - minor changes, add daemon

node/src/integration-test/kotlin/net/corda/node/services/rpc/RpcReconnectTests.kt
=> CORDA-2743 Add dynamic port allocation

node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/SchemaMigration.kt
Also add null check before invoking ClassLoader.getResource due to [JDK-8136831](https://bugs.openjdk.java.net/browse/JDK-8136831)
=> CORDA-2651 Remove null values from changelog list

docs/source/testing.rst, docs/source/tutorial-cordapp.rst, node/src/main/kotlin/net/corda/node/services/statemachine/SingleThreadedStateMachineManager.kt
=>  CORDA-2821 Fix issue with Quasar errors redirecting to useless page

client/rpc/src/main/kotlin/net/corda/client/rpc/internal/ReconnectingCordaRPCOps.kt, node/src/integration-test/kotlin/net/corda/node/services/rpc/RpcReconnectTests.kt
This should fix the oracle failure
=> Add retry to receive all vault events.

docs/source/contributing-flow-internals.rst, docs/source/contributing-index.rst
This is by no means complete. Any topics that need expanding?
=> Documentation of flow framework internals

build.gradle
Update Hibernate, which will update dom4j at the same time
=> ENT-3535 Update Hibernate dependency

docs/source/docker-image.rst
Added a bit of info in the note to describe docker behaviour which occurs on azure.
=> CORDA-2641 - change documentation.

docs/source/api-service-classes.rst, docs/source/corda-api.rst
Add docs for Service classes.
Documentation change only.
No related Jira or github issue.
(cherry picked from commit a9a0f422affa9d1c4efefdc63b05382cc663b10d)
=> BACKPORT Add documentation on Corda Services / Service classes

docs/source/changelog.rst
=> CORDA-2817 Changelog for bug fix to stop commands being combined.

docs/source/api-persistence.rst, docs/source/flow-overriding.rst, docs/source/key-concepts-contracts.rst, docs/source/key-concepts-transactions.rst, docs/source/shell.rst
=> DEVREL-1287 - Minor Typographic Changes

docs/source/corda-nodes-index.rst, docs/source/node-operations-upgrade-cordapps.rst, docs/source/upgrading-cordapps.rst
Align 2 docs with enterprise.
Only made a minor change around db migration.
=> ENT-3161 - Align docs with ENT

docker/src/bash/generate-config.sh, docker/src/bash/run-corda.sh, docker/src/docker/Dockerfile, docker/src/docker/DockerfileAL, docker/test-docker.sh, docs/source/docker-image.rst
Backported docker changes from OS to allow behaviour as per documentation.
https://github.com/corda/corda/pull/5095
https://github.com/corda/corda/pull/5098
https://github.com/corda/corda/pull/5094
https://github.com/corda/corda/pull/4965
=> Siliev backport docker CORDA-2888 CORDA-2641 CORDA-2811

build.gradle
https://github.com/corda/corda/pull/5002
=> CORDA-2586: Publish corda-common-logging

docs/source/key-concepts-ecosystem.rst, docs/source/key-concepts-ledger.rst, docs/source/key-concepts.rst
- Make Lessonly and Doc Site content "conform" - Ledger section.
- Update to incorporate changes that were requested via Lessonly comments. 
- Create home page that gives more orientation to user.
=> DEVREL-1297 Ledger - Doc Site Lessonly Conformance

.idea/compiler.xml, core/build.gradle, core/src/main/kotlin/net/corda/core/crypto/internal/PlatformSecureRandom.kt, core/src/main/kotlin/net/corda/core/internal/StatePointerSearch.kt, core/src/test/kotlin/net/corda/core/crypto/Base58Test.kt, core/src/test/kotlin/net/corda/core/crypto/CryptoUtilsTest.kt, core/src/test/kotlin/net/corda/core/utilities/EncodingUtilsTest.kt, node/src/main/kotlin/net/corda/node/internal/DBNetworkParametersStorage.kt, node/src/main/kotlin/net/corda/node/internal/Node.kt, node/src/main/kotlin/net/corda/node/services/identity/PersistentIdentityService.kt, node/src/main/kotlin/net/corda/node/services/keys/BasicHSMKeyManagementService.kt, node/src/main/kotlin/net/corda/node/services/keys/PersistentKeyManagementService.kt, node/src/main/kotlin/net/corda/node/services/persistence/DBCheckpointStorage.kt, node/src/main/kotlin/net/corda/node/services/persistence/DBTransactionStorage.kt, node/src/main/kotlin/net/corda/node/utilities/StateMachineManagerUtils.kt, serialization/src/test/kotlin/net/corda/serialization/internal/ContractAttachmentSerializerTest.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/InternalTestUtils.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/NodeBasedTest.kt, tools/cliutils/src/main/kotlin/net/corda/cliutils/InstallShellExtensionsParser.kt, tools/explorer/src/main/kotlin/net/corda/explorer/Main.kt, tools/shell/src/main/kotlin/net/corda/tools/shell/utlities/ANSIProgressRenderer.kt, tools/shell/src/test/kotlin/net/corda/tools/shell/utilities/ANSIProgressRendererTest.kt
Utilised Fields.getAllFieldsList where we were doing the equivalent
=> CORDA-2954: Upgrade to common-lang3

client/rpc/src/integration-test/kotlin/net/corda/client/rpc/RPCStabilityTests.kt, node/src/main/kotlin/net/corda/node/internal/Node.kt, node/src/main/kotlin/net/corda/node/services/messaging/ArtemisMessagingServer.kt, node/src/main/kotlin/net/corda/node/services/rpc/RpcBrokerConfiguration.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/RPCDriver.kt
=> CORDA-2838 Set Artemis memory config.

core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt, core/src/test/kotlin/net/corda/core/transactions/AttachmentsClassLoaderTests.kt, testing/test-utils/src/main/kotlin/net/corda/testing/internal/InternalTestUtils.kt
See https://r3-cev.atlassian.net/browse/SUP-637
This fix reduces the number of times the attachment is opened and closed
=> SUP-637 - Improve performance of the no-overlap check

docs/source/hello-world-running.rst
Change `IOUState` path in vault query
=> Docs update: fixed vaultQuery command in Hello World tutorial

node/src/integration-test/kotlin/net/corda/node/modes/draining/P2PFlowsDrainingModeTest.kt, node/src/main/kotlin/net/corda/node/services/messaging/P2PMessagingClient.kt
Added a timer in p2pmessagingclient which is turned on and of by the drain mode events.
=> ENT-3484 - Added periodic log.warn message to remind that the node has been set into draining mode.

node/src/main/kotlin/net/corda/node/services/statemachine/FlowLogicRefFactoryImpl.kt
See https://r3-cev.atlassian.net/browse/CORDA-2972 for more info. I should add a test but don't have time at the moment.
=> Fix for CORDA-2972.

docs/source/corda-configuration-file.rst, docs/source/generating-a-node.rst
Added some clarification on the available options for Cordform tasks.
=> CORDA-1912: Add documentation on the options for deploying nodes

samples/irs-demo/src/integration-test/kotlin/net/corda/test/spring/SpringDriver.kt
Constrain the max heap size of Spring Boot processes in IRS Demo test.
=> CORDA-3031 Constrain max heap size for Spring boot processes

release-tools/testing/test-manager
=> CORDA-3017 - Fix release tooling when product name != jira project

node-api/src/main/kotlin/net/corda/nodeapi/internal/protonwrapper/netty/SSLHelper.kt, node/src/integration-test/kotlin/net/corda/node/amqp/CertificateRevocationListNodeTests.kt
=> CORDA-2935: Align timeouts for CRL retrieval and TLS handshake

node/src/main/resources/migration/common.changelog-init.xml
Just a minor rename to the correct value for liquibase.
=> renamed postgres to postgresql

client/rpc/src/main/kotlin/net/corda/client/rpc/internal/ReconnectingCordaRPCOps.kt
CORDA-3034. Reconnecting Rpc will now not wait only for 60 min after normal operation
=> CORDA-3034. Reconnecting Rpc will now not wait only for 60 min after normal operation

CONTRIBUTORS.md
Prannav contributed https://github.com/corda/corda/pull/5262
=> Adding Prannav Kotamraju from Digiledge

docs/source/design/accounts/accounts.md
Fixed typos in Accounts design documentation.
=> Fixed typos in accounts design docs

docs/source/upgrading-cordapps.rst
=> suweicong-Update upgrading-cordapps.rst-one-line-doc-typo-fix

docs/source/whitepaper/Ref.bib, docs/source/whitepaper/corda-technical-whitepaper.tex
This PR also addresses the last review comment about a confusing sentence on constraints from the last review.
=> TWP: Reformat, refresh last parts of the doc, move parts into a future work section

docs/source/changelog.rst
CORDA-3028: Add Node Diagnostics Info RPC Call - Update changelog
=> CORDA-3028: Add Node Diagnostics Info RPC Call - Update changelog

node-api/src/main/kotlin/net/corda/nodeapi/internal/cryptoservice/CryptoService.kt, node-api/src/test/kotlin/net/corda/nodeapi/internal/cryptoservice/CryptoServiceTest.kt
Will be revisited to fix ENT-3658
=> ENT-3827: Temporarily disable the HSM timeouts

docs/source/cordapp-build-systems.rst
=> BACKPORT - cordapp configuration hotswap docs correction

client/jackson/src/main/kotlin/net/corda/client/jackson/StringToMethodCallParser.kt, client/rpc/src/main/kotlin/net/corda/client/rpc/CordaRPCClient.kt, core/src/main/kotlin/net/corda/core/internal/messaging/InternalCordaRPCOps.kt, core/src/main/kotlin/net/corda/core/messaging/CordaRPCOps.kt, core/src/test/kotlin/net/corda/core/flows/ContractUpgradeFlowTest.kt, docs/source/changelog.rst, docs/source/upgrading-cordapps.rst, node/src/main/java/net/corda/node/shell/RunShellCommand.java, node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt, node/src/main/kotlin/net/corda/node/internal/CordaRPCOpsImpl.kt, node/src/main/kotlin/net/corda/node/internal/RpcAuthorisationProxy.kt, node/src/main/kotlin/net/corda/node/internal/SecureCordaRPCOps.kt, node/src/main/kotlin/net/corda/node/services/api/CheckpointStorage.kt, node/src/main/kotlin/net/corda/node/services/persistence/DBCheckpointStorage.kt, node/src/main/kotlin/net/corda/node/services/rpc/CheckpointDumper.kt, node/src/main/kotlin/net/corda/node/shell/CordaAuthenticationPlugin.kt, node/src/main/kotlin/net/corda/node/shell/CordaSSHAuthInfo.kt, node/src/main/kotlin/net/corda/node/shell/InteractiveShell.kt, node/src/main/kotlin/net/corda/node/shell/RPCOpsWithContext.kt, node/src/test/kotlin/net/corda/node/CordaRPCOpsImplTest.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/InternalMockNetwork.kt
=> CORDA-3083: Backport dumpCheckpoints shell command

node/src/main/java/net/corda/node/shell/RunShellCommand.java
Some of the backported code from the previous change was missed. This change adds the missing code.
=> Backport checkpoint dumper part 2

docs/source/whitepaper/Ref.bib, docs/source/whitepaper/corda-technical-whitepaper.tex
Add discussion of identity, accounts, SGX, network parameters, versioning and a new proposed feature "data streams" (large attachments).
=> TWP: Identity, accounts, SGX, network parameters, versioning, data streams

docs/source/whitepaper/Ref.bib, docs/source/whitepaper/corda-technical-whitepaper.tex
* Comment out the network merging section until the details are more thoroughly explored.
* Create a top level section "the node", add some more explanations and move some other sections underneath it.
* Move notary "guaranteed data distribution" into the future work section.
* Add a brief discussion of human interaction to 'future work'
* Extend the discussion of scalability.
* Rebrand SGX execution models.
* Small improvements to the privacy section.
* Add a brief mention of business networks.
=> TWP: Create a top level section "the node", human interaction, scalability, rearrangements

docs/source/corda-network/UAT.md
=> Revert "BACKPORT - Update UAT.md docs to remove specific information"

CONTRIBUTORS.md, docs/source/tutorial-contract.rst
#5132 Corrected the cashkt ref to StateSumming
=> Contract tutorial update and Contributors list update

docs/source/node-database-migration-logging.rst, node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/CordaPersistence.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/SchemaMigration.kt, node/src/integration-test/kotlin/net/corda/node/persistence/DbSchemaInitialisationTest.kt, node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt, node/src/main/kotlin/net/corda/node/internal/Node.kt
Error codes implementation as per spec in https://github.com/corda/corda/pull/5318
=> ENT-3597 Database migration error codes

build.gradle
Update owasp scanner to latest version 5.2.0
=> CORDA-3120 Update owasp scanner

docs/source/whitepaper/Ref.bib, docs/source/whitepaper/corda-technical-whitepaper.tex
Add discussion of hosting nodes, micronodes, secure software update, key recovery and key rotation.
=> TWP: Add a section on micronodes, rewrite section on accounts

docs/source/node-flow-hospital.rst
The docs changes have already been merged for ENT, but I realised this section exists in OS too, so it should have been added there.
=> [DOCS] - Clarify behaviour of hospital in unhandled errors

README.md
Hi, I found a bad index at readme.md, the right index should be 4 instead of double 3.
=> fix wrong index in readme

docs/source/conf.py, docs/source/index.rst, docs/source/quickstart-build.rst, docs/source/quickstart-deploy.rst, docs/source/quickstart-index.rst
Moving the quickstart updates into the release/4 branch. Changes replicate the changes merged in [PR5272](https://github.com/corda/corda/pull/5272)
=> Backporting PR #5272 into release/4

docs/source/testnet-explorer-corda.rst
Fixes: https://r3-cev.atlassian.net/browse/CORDA-3073
Running the provided code returned a 404, now it returns the files as expected. :)
=> CORDA-3073: Code block links 404

README.md
Updated README.md to include instructions on new branching strategy.
=> CORDA-3160: Add README file to the master branch repo (OS)

core/src/main/kotlin/net/corda/core/internal/cordapp/CordappResolver.kt
Add a more evident error message when multiple versions of the same Cordapp are installed
see https://r3-cev.atlassian.net/browse/ENT-3924
=> ENT-3924 -  more evident error message when multiple versions of the same CorDapp installed

docs/source/upgrading-cordapps.rst
see https://r3-cev.atlassian.net/browse/ENT-3916
=> ENT-3916 - document testing CorDapp upgrades.

docs/source/testnet-explorer-corda.rst, docs/source/upgrading-cordapps.rst, node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt, node/src/test/kotlin/net/corda/node/services/vault/NodeVaultServiceTest.kt
=> Tudor merge 4.1 to 4.3
