core/src/main/kotlin/net/corda/core/internal/InternalUtils.kt, docs/source/corda-configuration-file.rst, docs/source/example-code/src/main/resources/example-node.conf, node-api/src/main/kotlin/net/corda/nodeapi/internal/DevIdentityGenerator.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/bridging/AMQPBridgeManager.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/config/SSLConfiguration.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/crypto/X509Utilities.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/protonwrapper/netty/AMQPClient.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/protonwrapper/netty/AMQPServer.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/protonwrapper/netty/SSLHelper.kt, node-api/src/test/kotlin/net/corda/nodeapi/internal/crypto/X509UtilitiesTest.kt, node/src/integration-test/kotlin/net/corda/node/NodeKeystoreCheckTest.kt, node/src/integration-test/kotlin/net/corda/node/amqp/AMQPBridgeTest.kt, node/src/integration-test/kotlin/net/corda/node/amqp/CertificateRevocationListNodeTests.kt, node/src/integration-test/kotlin/net/corda/node/amqp/ProtonWrapperTests.kt, node/src/integration-test/kotlin/net/corda/services/messaging/MQSecurityAsNodeTest.kt, node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt, node/src/main/kotlin/net/corda/node/services/config/NodeConfiguration.kt, node/src/main/kotlin/net/corda/node/services/config/SslOptions.kt, node/src/main/kotlin/net/corda/node/services/config/shell/ShellConfig.kt, node/src/main/resources/reference.conf, node/src/test/kotlin/net/corda/node/services/config/NodeConfigurationImplTest.kt, testing/test-common/src/main/kotlin/net/corda/testing/common/internal/UnsafeCertificatesFactory.kt, testing/test-utils/src/main/kotlin/net/corda/testing/internal/InternalTestUtils.kt, tools/shell/src/integration-test/kotlin/net/corda/tools/shell/InteractiveShellIntegrationTest.kt, tools/shell/src/main/kotlin/net/corda/tools/shell/ShellConfiguration.kt, tools/shell/src/main/kotlin/net/corda/tools/shell/StandaloneShellArgsParser.kt, tools/shell/src/test/kotlin/net/corda/tools/shell/StandaloneShellArgsParserTest.kt, webserver/src/main/kotlin/net/corda/webserver/WebServerConfig.kt
This PR enables the CRL checking on the node side. The node configuration is extended with a new parameter called `revocationCheckConfig`, which takes 3 boolean flags configuring the SSL-level revocation check mechanism.
@mnesbit please let me know where else the SSL configuration change is required.
=> CORDA-1319 Adding CRL checking for nodes

build.gradle
Configure our build with the correct version of Gradle via the wrapper task. This allows us to upgrade Gradle by editing this version number and then executing:
$ gradlew wrapper
=> Configure Gradle's wrapper task.

docs/source/hello-world-running.rst
Line 108
Was: We want to create an IOU of 100 with PartyB. We start the ``IOUFlow`` by typing:
Should be We want to create an IOU of 99 with PartyB. We start the ``IOUFlow`` by typing:
=> A typo fix.

client/rpc/src/integration-test/kotlin/net/corda/client/rpc/CordaRPCClientTest.kt, node-api/src/main/kotlin/net/corda/nodeapi/exceptions/InternalNodeException.kt, node/src/integration-test/kotlin/net/corda/node/services/rpc/RpcExceptionHandlingTest.kt
These exceptions are designed to be propagated in P2P and so makes sense to keep them visible if the recipient is an RPC user.
=> Including FlowException in the RPC exception whitelist (CORDA-1264)

constants.properties, gradle-plugins/cordformation/src/main/kotlin/net/corda/plugins/Baseform.kt
This is to enable multiple calls to deployNodes without doing a gradle clean.
=> CORDA-1389: Delete the root nodes directory before initialising the nodes

client/rpc/src/main/kotlin/net/corda/client/rpc/CordaRPCClient.kt, client/rpc/src/main/kotlin/net/corda/client/rpc/internal/RPCClientProxyHandler.kt, client/rpc/src/main/kotlin/net/corda/client/rpc/internal/serialization/kryo/KryoClientSerializationScheme.kt, client/rpc/src/main/kotlin/net/corda/client/rpc/internal/serialization/kryo/RpcClientObservableSerializer.kt, docs/source/changelog.rst, node/src/main/kotlin/net/corda/node/internal/Node.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/RPCDriver.kt, testing/smoke-test-utils/src/main/kotlin/net/corda/smoketesting/NodeProcess.kt, testing/test-utils/src/main/kotlin/net/corda/testing/core/SerializationTestHelpers.kt, testing/test-utils/src/main/kotlin/net/corda/testing/internal/InternalSerializationTestHelpers.kt, tools/demobench/src/main/kotlin/net/corda/demobench/DemoBench.kt
Move Kryo into its own submodule - part of a generic refactor before adding AMQP RPC support - This is effectively a no-op
=> CORDA-847 - RPC Clent lib refactoring

node/src/main/kotlin/net/corda/node/services/vault/HibernateQueryCriteriaParser.kt, node/src/test/kotlin/net/corda/node/services/vault/VaultQueryTests.kt
Query parser will now generate positional parameter for aggregate function in 'group by' clause instead of aggregate function e.g.
'... order by (sum col_x)' is now generated as 'select sum(col_x) ... order by 1'. 
Following the change in R3.Corda repository.
=> Vault queries - change SQL generation for aggregate function in 'group by' clause.

build.gradle, constants.properties, finance/src/main/kotlin/net/corda/finance/flows/CashConfigDataFlow.kt, finance/src/main/kotlin/net/corda/finance/flows/CashExitFlow.kt, finance/src/main/kotlin/net/corda/finance/flows/CashIssueFlow.kt, finance/src/main/kotlin/net/corda/finance/flows/CashPaymentFlow.kt, node/src/test/kotlin/net/corda/node/services/vault/VaultQueryTests.kt, tools/demobench/build.gradle
Upgrade Corda from Kotlin 1.2.20 to 1.2.41, and fix some of the new compiler warnings.
=> CORDA-1441: Upgrade to Kotlin 1.2.41

node/src/integration-test/kotlin/net/corda/node/CordappScanningDriverTest.kt, node/src/main/kotlin/net/corda/node/internal/Node.kt, node/src/main/kotlin/net/corda/node/internal/cordapp/CordappLoader.kt, node/src/test/kotlin/net/corda/node/internal/cordapp/CordappLoaderTest.kt
Ignore duplicate packages and sub-packages in driver `extraCordappPackagesToScan`. Otherwise duplicate test CorDapps are loaded into the node.
=> CORDA-1385: Ignore duplicate packages and sub-packages in driver extraCordappPackagesToScan

node-api/src/main/kotlin/net/corda/nodeapi/internal/protonwrapper/engine/ConnectionStateMachine.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/protonwrapper/netty/AMQPChannelHandler.kt
This PR removes some excessive binary logging from the AMQP protocol wrappers, which was useful only during the initial development and is now just spam.
=> Remove debug logging left over from earlier AMQP development.

docs/source/api-testing.rst, testing/node-driver/src/main/kotlin/net/corda/testing/node/MockNetwork.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/InternalMockNetwork.kt
Little feature that allows you to exclude a list of CorDapps from specified MockNodes. I've done this because, currently, all nodes get the same CorDapps and this doesn't work under certain scenarios... In my case, I subscribe to an observable inside a CordaService. This should only be done by one node but all do it as they all get the CorDapp, this results in unusual behaviour. This PR prevents that from happening.
=> Feature to exclude CorDapps from specific MockNodes in a MockNetwork.

node/src/main/kotlin/net/corda/node/Corda.kt, node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt
New version of netty(4.1.15) clashes with our logging. We use FastThreadLocal which ends up initialising slf4j before we can set defaultLogLevel property.
=> Register crypto providers after we init logging

docs/source/cipher-suites.rst, docs/source/corda-networks-index.rst, docs/source/other-index.rst
As requested, a page enlisting our supported cipher suites is added to the documentation.
At the moment, I've added as a submenu of "Other" menu. We could also create a menu called "References".
Note: I didn't mention Composite Keys yet as an option, because although one could theoretically use a Composite Key, we still don't have helper functions to support this during node registration.
=> [ENT-1825] Document details of cipher suites

node/src/main/kotlin/net/corda/node/internal/NetworkParametersReader.kt, node/src/test/kotlin/net/corda/node/services/network/NetworkParametersReaderTest.kt
If network map is not available or returns exception on network
parameters reading (either serialization, connection, signature etc.), node should continue with parameters from file.
=> CORDA-1414: node should continue with parameters from file when network map not available

docs/source/changelog.rst, node/src/integration-test/kotlin/net/corda/node/services/events/ScheduledFlowIntegrationTests.kt, node/src/integration-test/kotlin/net/corda/testMessage/ScheduledState.kt, node/src/main/kotlin/net/corda/node/services/events/NodeSchedulerService.kt, node/src/main/kotlin/net/corda/node/services/events/PersistentScheduledFlowRepository.kt, node/src/test/kotlin/net/corda/node/services/events/NodeSchedulerServiceTest.kt, node/src/test/kotlin/net/corda/node/services/events/PersistentScheduledFlowRepositoryTest.kt
Backport from ent
* Add scheduled flow test that uses multithreaded node
* Replace use of PersistentMap in NodeSchedulerService
* Correct class name and remove duplicate test
* Address initial PR comments
* Remove debugging code
* Remove acidentally added line
* Move Scheduled State contracts to internal module
* Put things in the right places
* Add changelog message
* Fix countdown issue
* Addressing PR comments
=> CORDA-1001 - Remove peristent map in NodeSchedulerService (#763)

docs/source/tutorial-cordapp.rst
The node driver now allocates ports differently, so the CorDapp example ports when run from the command line had to be updated.
=> Updates ports to match new CorDapp example ports.

node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/CordaPersistence.kt
Database transaction can be set to retry failure due to any exception with the cause or the nested cause of SQLException type.
It may happen that underlying SQL Exception is wrapped by Hibernate, allow in such case to retry but only if this was requested e.g.
`val recoverAnyNestedSQLException = true`\
`val maxTransactionRecoveryAttempts = 3`\
`database.transaction(TransactionIsolationLevel.SERIALIZABLE, maxTransactionRecoveryAttempts, recoverAnyNestedSQLException) { .... }`
The change doesn't alter the existing behaviour.
The change is required for ENT-1447 and it's part of https://github.com/corda/enterprise/pull/777.
=> Database transaction optional ability to retry on nested SQL Exception. 

core/src/main/kotlin/net/corda/core/internal/InternalUtils.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/DeserializationInput.kt, node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializationOutputTests.kt
Replace `getStackTraceAsString()` with a more standard approach.
=> ENT-1463: Replace getStackTraceAsString() with Throwable.initCause().

.ci/api-current.txt, build.gradle, client/jackson/src/main/kotlin/net/corda/client/jackson/JacksonSupport.kt, client/jackson/src/main/kotlin/net/corda/client/jackson/internal/JacksonUtils.kt, client/jackson/src/test/kotlin/net/corda/client/jackson/JacksonSupportTest.kt, docs/source/changelog.rst, docs/source/shell.rst, samples/network-visualiser/src/main/resources/net/corda/irs/web/simulation/trade.json, testing/test-utils/src/main/kotlin/net/corda/testing/internal/TestNodeInfoBuilder.kt, tools/shell/build.gradle, tools/shell/src/main/kotlin/net/corda/tools/shell/InteractiveShell.kt, tools/shell/src/main/kotlin/net/corda/tools/shell/SerializationSupport.kt, tools/shell/src/test/kotlin/net/corda/tools/shell/CustomTypeJsonParsingTests.kt
Also deprecated all the public members that shouldn't have leaked into the public API.
=> Cleanup and improvements to the serialisation format of JacksonSupport (needed for CORDA-1238)

node/src/integration-test/kotlin/net/corda/node/services/rpc/RpcSslTest.kt
Re-wrote the tests to do proper connection close and get rid of connection loss timeout that caused the tests to hang needlessly.
=> CORDA-1443: cleanup tests, eliminate connection loss timeout

docs/make-docsite.sh
Published PDF file is missing because of a missing target directory in the script move command:
https://docs.corda.net/head/_static/corda-developer-site.pdf
This fix ensures that the generated PDF file is copied to the correct place without error.
=> CORDA-1466: Fix publication of PDF developer documentation

node/src/main/kotlin/net/corda/node/internal/NetworkParametersReader.kt, node/src/test/kotlin/net/corda/node/services/network/NetworkParametersReaderTest.kt
*** Backport from master onto V3 branch
Fix CORDA-1414
If network map is not available or returns exception on network
parameters reading, node should continue with parameters from file.
=> CORDA-1414 - node should continue with parameters from file when network map not available

node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/ByteBufferStreams.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/ServerContexts.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/SharedContexts.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/AMQPSerializationScheme.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/carpenter/ClassCarpenter.kt
- Remove `Thread` reference from `ClassCarpenter` primary constructor.
- Put `QuasarWhitelist` in the same file as the thing that uses it.
- Allow Artemis `SimpleString` serialiser to be dropped from DJVM.
- Whitespace fixes.
=> ENT-1463: Refactor serialisation slightly for determinisation.

docs/source/corda-configuration-file.rst
Fix problem with Python PDF builder failing to render the Sphinx **:math:** tag directive correctly, causing generation of a 0 byte pdf file.
Python PDF rendering fails using latest version of `Matplotlib` (version 2.2.2).
```
[11:44:10][:docs:makeDocs] [ERROR] pdfbuilder.py:130 invalid literal for float(): 0.000000/
[11:44:10][:docs:makeDocs] paragraph text u'<para>The base of the exponential backoff, <img src="/data/BuildAgent/temp/buildTmp/tmpzY63cH.png" width=10.000000 height=10.000000 valign=0.000000/>.</para>' caused exception
[11:44:10][:docs:makeDocs] Traceback (most recent call last):
```
=> CORDA-1466: Fix problem with PDF document rendering

node-api/src/main/kotlin/net/corda/nodeapi/internal/protonwrapper/netty/AMQPChannelHandler.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/protonwrapper/netty/AMQPClient.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/protonwrapper/netty/SSLHelper.kt, node/src/integration-test/kotlin/net/corda/node/amqp/ProtonWrapperTests.kt
Previously the AMQPClient code in the bridges logged a lot of ambiguous exception traces and we were retrying every second. Now we do exponential backoff and I explicitly log a light summary of the provided certificate paths when we go to check them and a full detail list when we get a validation error.
=> ENT-1850: Improve reporting of connection problems

node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt, node/src/test/kotlin/net/corda/node/services/vault/VaultQueryTests.kt
Pagination relies on a recursive call to count total results, this internal sub-query should NOT perform pagination constraint checking.
=> CORDA-861 Pagination failure with aggregate groupBy query

node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/CustomSerializer.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/EvolutionSerializer.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializerFactory.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/TransformsSchema.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/carpenter/ClassCarpenter.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/carpenter/SchemaFields.kt, node-api/src/test/java/net/corda/nodeapi/internal/serialization/amqp/JavaPrivatePropertyTests.java, node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/GenericsTests.kt
- Hide concurrent collection classes behind interfaces.
- Refactor `ClassCarpenter` invocation into a separate function.
- Tidy up lots of compiler warnings.
=> ENT-1463: Isolate more non-deterministic code from AMQP serialisation.

node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/SerializationScheme.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/AMQPSerializationScheme.kt, node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializationSchemaTests.kt
`ConcurrentHashMap` has been deleted from the DJVM, so allow it to be replaced with an ordinary `HashMap`.
=> ENT-1463: Hide more AMQP ConcurrentHashMaps behind interfaces.

core/src/main/kotlin/net/corda/core/node/NetworkParameters.kt, docs/source/network-map.rst, node-api/src/main/kotlin/net/corda/nodeapi/internal/network/NetworkBootstrapper.kt, node/src/integration-test/kotlin/net/corda/node/services/network/NetworkMapTest.kt, node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt, node/src/main/kotlin/net/corda/node/services/network/NetworkMapUpdater.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/network/NetworkMapServer.kt, testing/test-common/src/main/kotlin/net/corda/testing/common/internal/ParametersUtilities.kt
* Implement removal of stale nodes from network
Add eventHorizon to NetworkParameters structure. Add republishing of
node info on 1 day intervals - it is treated by network map as heartbeat from node indicating if it's alive or not. Add removal of old node infos on network map signing.
* Add copy method to NetworkParameters data class
Add JvmOverloads annotation to the constructor, because it's data class
exposed in API
=>  CORDA-866: Implement removal of stale nodes from network - backport

build.gradle, node-api/build.gradle, node/build.gradle
Artemis includes Netty piecemeal, but we prefer to include `netty-all` instead. This means that we end up with _two_ copies of the Netty classes because Gradle is unaware of the overlap.
Fix this by excluding `netty-all` from every module. This will force us to specify precisely which pieces of Netty we wish to use.
=> Remove duplicate Netty classes from Node.

node/src/integration-test/kotlin/net/corda/node/services/network/NodeInfoWatcherTest.kt, node/src/main/kotlin/net/corda/node/services/network/NetworkMapUpdater.kt, node/src/main/kotlin/net/corda/node/services/network/NodeInfoWatcher.kt, node/src/main/kotlin/net/corda/node/services/network/PersistentNetworkMapCache.kt, node/src/test/kotlin/net/corda/node/services/network/NetworkMapUpdaterTest.kt
Deleting NodeInfo from additional-node-infos directory should remove it from cache.
=> CORDA-1093 Deleting node info from directory

.ci/api-current.txt, build.gradle
- Updated api scanner to use current version
- Ported accross the generated `api-current.txt` from the release-v3 branch (from this PR here: https://github.com/corda/corda/pull/3154)
- Applied any changes to `api-current.txt` which have already been approved (original jira tickets/PR numbers are in individual commits to make it easier to follow)
- There was one further internal exposure which was highlighted due to the fact that the new version of api scanner shows detail of generic parameters and lambda inputs. The exposure has already been 'committed' to so I'm not sure what the best course of action is, but I've raised a seperate story here: https://r3-cev.atlassian.net/browse/CORDA-1489 to remove it.
=> CORDA-1280 Update api-current from v3.2 and use most recent version of api-scanner

core/src/main/kotlin/net/corda/core/node/services/vault/QueryCriteria.kt
Removed unresolvable documentation references to classes in `finance` package (not accessible from `core`)
=> Vault Fungible Asset Query Criteria: removed incorrect reference in docs.

config/dev/log4j2.xml
Currently the node will keep up to 10 compressed log files during rollover, and discard old ones. This limit seems too low for production use and might lead to valuable log data loss.
=> Increase the number of log files retained per day

client/jfx/src/main/kotlin/net/corda/client/jfx/model/NodeMonitorModel.kt
If we are already in the JavaFX thread - perform direct invocation without postponing it.
Or else if we are operating in JavaFX thread the sequence of invocations will change.
=> ENT-1902: Explorer GUI from Enterprise cannot be started against remote Node

build.gradle, serialization/src/main/kotlin/net/corda/serialization/internal/OrdinalIO.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/AMQPSerializer.kt
Kotlin will implement default interface methods via a synthetic nested `$DefaultImpls` class unless we apply Kotlin 1.2.40's new `@JvmDefault` annotation. This annotation instructs the compiler to implement them as Java8 `default` methods instead on the interface class itself.
Apply this annotation to interfaces required by the `-deterministic` modules so that no `$DefaultImpls` classes are generated. Otherwise we would need to configure ProGuard explicitly to keep them all.
=> ENT-1463: Declare default interface methods as Java8 default.

core/src/main/kotlin/net/corda/core/flows/FinalityFlow.kt, core/src/main/kotlin/net/corda/core/internal/Emoji.kt, core/src/main/kotlin/net/corda/core/utilities/ProgressTracker.kt, core/src/test/kotlin/net/corda/core/utilities/ProgressTrackerTest.kt, tools/shell/src/main/kotlin/net/corda/tools/shell/utlities/ANSIProgressRenderer.kt
* Progress Tracker doesn't set to "green tick" for a step which hasn't been set in the flow 
It marks steps as processed ("green tick") only if they were send to a renderer (set as the current step). Marking with green crossed sign for shell and as minus sign for ssh.  
See attached screenshots.
* Finality Flow sets the current step to NOTARISING only if the actual notarization is performed.
The underlying fix was for ProgressTracker descends to child steps to find stepIndexTree for more than two nested levels.
Added first a unit test which illustrates the problem , and it failed without a fix.
After the fix, the test passes:
https://ci-master.corda.r3cev.com/viewType.html?buildTypeId=Corda_PullRequests&branch_Corda_Build_PullRequests=3173&tab=buildTypeStatusDiv
=> ENT-1574 Progress tracker distinguishes steps which were not processed

finance/src/main/kotlin/net/corda/finance/contracts/asset/OnLedgerAsset.kt, finance/src/test/kotlin/net/corda/finance/contracts/asset/cash/selection/CashSelectionH2ImplTest.kt
Description will change in the future and Jira item to follow.
=> CORDA-1506: Cash selection logic fails when selection with a change from more that 2 different issuer groups

node-api/src/main/kotlin/net/corda/nodeapi/internal/network/NetworkBootstrapper.kt, samples/notary-demo/src/main/kotlin/net/corda/notarydemo/BFTNotaryCordform.kt, samples/notary-demo/src/main/kotlin/net/corda/notarydemo/RaftNotaryCordform.kt
Extending the bootstrapper to generate networks with HA and BFT notaries, based on the `notary.serviceLegalName` configuration.
=> Bootstrap HA and BFT notaries

docs/source/corda-configuration-file.rst, node/src/main/kotlin/net/corda/node/services/config/ConfigUtilities.kt
Allow override node properties by a system property. Especially handy for credentials.
=> CORDA-1288 Node properties can be set as system properties.

docs/source/clientrpc.rst
PR to move some code examples for rpc client connection handling from HA docs in ENT to OS
=> add RPC client examples of connection management

.ci/api-current.txt, core/src/main/kotlin/net/corda/core/node/NetworkParameters.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/network/NetworkMap.kt, node/src/integration-test/kotlin/net/corda/node/services/network/NetworkMapTest.kt, node/src/main/kotlin/net/corda/node/internal/NetworkParametersReader.kt, node/src/main/kotlin/net/corda/node/services/network/NetworkMapClient.kt, node/src/main/kotlin/net/corda/node/services/network/NetworkMapUpdater.kt, node/src/test/kotlin/net/corda/node/services/network/NetworkMapUpdaterTest.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/network/NetworkMapServer.kt
(cherry picked from commit 620ba1e)
Backport of https://github.com/corda/corda/pull/2863.
=> CORDA-1405: Integration test for network parameter updates and improved logging

docs/source/changelog.rst, node/src/main/kotlin/net/corda/node/NodeArgsParser.kt, node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt, node/src/main/kotlin/net/corda/node/services/config/ConfigUtilities.kt
https://r3-cev.atlassian.net/browse/CORDA-1458
Approach taken:
- Removed logging side-effect from `ConfigUtilities`
- Returned the raw configuration along with the result of trying to parse it into `NodeConfiguration` in `NodeArgsParser`
- Printed the raw configuration only in case `devMode` is `true` in `NodeStartup`
=> [CORDA-1458]: Prevent passwords from being logged as part of node's configuration.

node/src/integration-test/kotlin/net/corda/node/services/network/NetworkMapTest.kt, node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt, node/src/main/kotlin/net/corda/node/services/network/NetworkMapUpdater.kt, node/src/test/kotlin/net/corda/node/services/network/NetworkMapUpdaterTest.kt
Don't remove own node info from cache on network map update.
=> ENT-1882: Don't remove own node info - fix

serialization/src/main/kotlin/net/corda/serialization/internal/amqp/MapSerializer.kt
`WeakHashMap` _has ceased to be_ within the DJVM - _It is an ex-class!_ So isolate this reference to it within a single function that can be excised cleanly.
=> ENT-1903: Isolate the WeakHashMap reference.

node/src/main/kotlin/net/corda/node/services/config/NodeConfiguration.kt, node/src/main/kotlin/net/corda/node/services/messaging/P2PMessagingClient.kt, node/src/main/resources/reference.conf
The logic change here to the bridges means that we won't initiate an outgoing bridge until our first message, unless the queue is non-empty from a previous session, or we configure to initiate always.
I believe this logic is safe, even when we move towards a clustered node, though it does require the queue count to be trustworthy. If not we can disable it via config, so this shouldn't strand anyone.
=> Late start bridges (unless configured otherwise) if the queue is empty.

node/src/main/resources/reference.conf
When the config files doesn't contain `myLegalName` the exception says:
> improperly specified input name: Vast Global MegaCorp, Ltd
=> Remove default value for `myLegalName`

docs/source/corda-configuration-file.rst
Add example for node SSH server port configuration option as port property can be misleading.
=> Improve SSH server port node documentation.

finance/src/main/kotlin/net/corda/finance/flows/CashExitFlow.kt, finance/src/main/kotlin/net/corda/finance/flows/CashIssueFlow.kt, finance/src/main/kotlin/net/corda/finance/flows/CashPaymentFlow.kt
Add `import` statements to resolve compiler warnings like:
```
w: /work/corda/finance/src/main/kotlin/net/corda/finance/flows/CashIssueFlow.kt: (49, 39): Access to this type by short name is deprecated, and soon is going to be removed. Please, add explicit qualifier or import
```
=> Resolve compiler warnings for Kotlin >= 1.2.40.

finance/src/main/kotlin/net/corda/finance/contracts/asset/cash/selection/AbstractCashSelection.kt
Change only removes the mutex and the `catch` clause.  The bigger diff is due to change in indentation.  I recommend hiding whitespace changes in the Diff settings on the `Files changed` tab.
=> ENT-1975 Remove mutex and stop catching deadlock / SQLExceptions.

.idea/compiler.xml, node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt, node/src/main/kotlin/net/corda/node/services/events/NodeSchedulerService.kt, node/src/test/kotlin/net/corda/node/services/events/NodeSchedulerServiceTest.kt
The NodeSchedulerService used to have a race condition where it could happen that two flows for the same state get started, leading to an attempted double spend.
This got cleared up by giving the scheduler an event loop on a worker thread, and doing all selection of states etc. on this single thread. The external calls now only trigger this thread to recheck what to execute rather than getting involved in any of the selection logic.
=> CORDA-1524 Fix NodeSchedulerService

client/jfx/src/main/kotlin/net/corda/client/jfx/model/NodeMonitorModel.kt
Apparently, if incorrect endpoint provided, ActiveMQNotConnectedException is thrown
which is different to ActiveMQSecurityException. Extend catch block to: ActiveMQException
to cater for all such cases.
=> CORDA-1536: Fix client infinitely re-trying when incorrect endpoint specified.

serialization/src/main/kotlin/net/corda/serialization/internal/amqp/ArraySerializer.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/SerializerFactory.kt, serialization/src/test/kotlin/net/corda/serialization/internal/amqp/DeserializeSimpleTypesTests.kt
At serialization time we incorrectly encode the type as byte[p][] instead
of binary[]
=> CORDA-1545 - Arrays of primitive byte arrays don't deserialize

node-api/src/main/kotlin/net/corda/nodeapi/internal/protonwrapper/netty/ConnectionChange.kt
The original data class toString printed the full certificates into the logs which caused lots of spam. Now reduce to a few key details, especially as we have improved certificate logging on validation errors elsewhere.
=> Reduce log spam on the ConnectionChange events

node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt, node/src/test/kotlin/net/corda/node/services/vault/NodeVaultServiceTest.kt
Example: issuance of 2 coins of £1 issued by the same notary.
Build #19919 shows the new test (https://github.com/corda/corda/pull/3244/commits/00e484c401d47e2650c7ee5f4eb05a165ea89529) is failing and the next build shows the test passing #19922 after the fix (https://github.com/corda/corda/pull/3244/commits/caabd45b5992d85aac5cc6fe3036055c511bb5ad):
https://ci-master.corda.r3cev.com/viewType.html?buildTypeId=Corda_PullRequests&branch_Corda_Build_PullRequests=3244&tab=buildTypeStatusDiv
=> CORDA-1266 When a cash output is identical only the fist output is saved.

finance/src/integration-test/kotlin/net/corda/finance/flows/CashSelectionTest.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/CordaPersistence.kt
Hibernate session not flushed before handing over raw JDBC session to user code (e.g. coin selection)
Added a test `cash selection sees states added in the same transaction` to manifest that cash selection can't access states inserted during the same database transaction (additional two tests copied from Enterprise repo).
The first build fail as expected:
https://ci-master.corda.r3cev.com/viewType.html?buildTypeId=Corda_Build_PullRequests_IntegrationTests&branch_Corda_Build_PullRequests=3266&tab=buildTypeStatusDiv
The new test which failed
`CashSelectionTest.cash selection sees states added in the same transaction`and
`CashSelectionTest.dont return extra coins if the selected amount has been reached` are passing successfully after applying the fix in the next build.
=> CORDA-1548 Hibernate session not flushed before handing over raw JDBC session to user code (e.g. coin selection)

docs/source/cipher-suites.rst, docs/source/permissioning.rst
- K1 is supported by TLS 1.2 (see `TLSAuthenticationTests`)
- Sphincs is mentioned as experimental due to a [BC 1.58 reported issue](https://www.bouncycastle.org/releasenotes.html) which needs further investigation. Note that we are still using BC 1.57.
Note: integration tests for the above Sphincs reported issue (or BC lib update) will be addressed in another PR.
=> K1 is supported by TLS and Sphincs is mentioned as experimental

core/src/main/kotlin/net/corda/core/internal/InternalUtils.kt, core/src/main/kotlin/net/corda/core/utilities/UntrustworthyData.kt, node/src/main/kotlin/net/corda/node/services/statemachine/FlowSessionImpl.kt
It was added in after V3 so it's safe to make it internal.
=> Move checkPayloadIs out of the public API

node/src/main/kotlin/net/corda/node/services/statemachine/SingleThreadedStateMachineManager.kt
Just so we don't accidentally error the newly re-created flow with a message on a session that doesn't exist in the the newly restored flow.  The line after the change puts the sessions that existed at the last checkpoint back into that map, so cleaning them all up is fine.
=> CORDA-1564 Clean up old sessions when retrying flows.

node-api/src/main/kotlin/net/corda/nodeapi/internal/network/NetworkBootstrapper.kt
This allows users to bootstrap large Corda networks.
Once the bootstrapper has moved to the tools package we can
expose the number of processes as a command line parameter
(using Picocli).
=> Limit concurrency of the bootstrapper

docs/source/changelog.rst, docs/source/upgrade-notes.rst, node/src/main/kotlin/net/corda/node/services/persistence/NodeAttachmentService.kt
Database table is missing an "a" in the word attachments: `node_attchments_contracts`.
=> CORDA-1499 - Fix a typo in node_attchments_contracts table name.

node-api/src/main/kotlin/net/corda/nodeapi/internal/protonwrapper/netty/AMQPClient.kt
To reduce log spam I put in exponential backoff for the AMQP bridges. However, I set the max retry time at 5 minutes, which is too long for sensible testing.
=> Reduce AMQP bridge max retry time back to 1 minute

docs/source/corda-configuration-file.rst
If you configure a node with it set it won't start, so probably shouldn't have it in the documentation
=> DOCS - Remove references to webAddress since it's no longer a valid option

node/src/main/kotlin/net/corda/node/services/messaging/P2PMessagingClient.kt
The lazy init bridge logic was wrong in that if an external bridge is restarted the bridge creation state isn't reset.
=> ENT-2027: The logic in my recent late start bridge PR was wrong. 

client/jfx/src/main/kotlin/net/corda/client/jfx/utils/FlattenedList.kt, client/rpc/src/integration-test/kotlin/net/corda/client/rpc/RPCStabilityTests.kt, docs/source/example-code/src/main/java/net/corda/docs/FlowCookbookJava.java, docs/source/example-code/src/main/kotlin/net/corda/docs/FlowCookbook.kt, experimental/corda-utils/src/main/kotlin/io/cryptoblk/core/StatusTransitions.kt, experimental/src/main/kotlin/net/corda/finance/contracts/universal/UniversalContract.kt, experimental/src/main/kotlin/net/corda/finance/contracts/universal/Util.kt, node/src/main/kotlin/net/corda/node/serialization/kryo/Kryo.kt, node/src/test/kotlin/net/corda/node/services/RPCSecurityManagerTest.kt, serialization/src/main/kotlin/net/corda/serialization/internal/carpenter/ClassCarpenter.kt, serialization/src/main/kotlin/net/corda/serialization/internal/carpenter/MetaCarpenter.kt, serialization/src/main/kotlin/net/corda/serialization/internal/carpenter/SchemaFields.kt, serialization/src/test/kotlin/net/corda/serialization/internal/carpenter/ClassCarpenterTest.kt, serialization/src/test/kotlin/net/corda/serialization/internal/carpenter/CompositeMemberCompositeSchemaToClassCarpenterTests.kt, serialization/src/test/kotlin/net/corda/serialization/internal/carpenter/MultiMemberCompositeSchemaToClassCarpenterTests.kt, serialization/src/test/kotlin/net/corda/serialization/internal/carpenter/SingleMemberCompositeSchemaToClassCarpenterTests.kt
JVM assertions have to be enabled with the -ea flag so it's possible for these checks to be ignored.
=> Replaced all uses of assert with require

core/src/main/kotlin/net/corda/core/internal/ResolveTransactionsFlow.kt, core/src/main/kotlin/net/corda/core/internal/TopologicalSort.kt, core/src/test/kotlin/net/corda/core/internal/TopologicalSortTest.kt
This adds a utility function allowing on the fly toposort of SignedTransaction observables.
Not sure if it's worth adding to the codebase, @mikehearn ?
=> SUP-171: Observable toposort for transactions

node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt, node/src/test/kotlin/net/corda/node/services/vault/NodeVaultServiceTest.kt
When a cash output is identical only the first output is saved. (#3244)
(cherry picked from commit 0a4d981)
=> CORDA-1266 When a cash output is identical only the first output is saved. (#3244) -> V3

docs/source/changelog.rst, docs/source/upgrade-notes.rst, node/src/main/kotlin/net/corda/node/services/persistence/NodeAttachmentService.kt
Fix a typo in node_attchments_contracts table name.
(cherry picked from commit fc54263)
=> CORDA-1499 Fix a typo in node_attchments_contracts table name. -> V3

.ci/api-current.txt, core/src/main/kotlin/net/corda/core/flows/NotaryFlow.kt, core/src/main/kotlin/net/corda/core/internal/FlowIORequest.kt, core/src/main/kotlin/net/corda/core/internal/IdempotentFlow.kt, node/src/integration-test/kotlin/net/corda/node/services/NotarisationRetryTests.kt, node/src/integration-test/kotlin/net/corda/node/services/TimedFlowTests.kt, node/src/integration-test/kotlin/net/corda/services/messaging/P2PMessagingTest.kt, node/src/main/kotlin/net/corda/node/services/messaging/Messaging.kt, node/src/main/kotlin/net/corda/node/services/messaging/P2PMessagingClient.kt, node/src/main/kotlin/net/corda/node/services/schema/NodeSchemaService.kt, node/src/main/kotlin/net/corda/node/services/statemachine/Action.kt, node/src/main/kotlin/net/corda/node/services/statemachine/ActionExecutorImpl.kt, node/src/main/kotlin/net/corda/node/services/statemachine/DeduplicationId.kt, node/src/main/kotlin/net/corda/node/services/statemachine/FlowRetryException.kt, node/src/main/kotlin/net/corda/node/services/statemachine/FlowSessionImpl.kt, node/src/main/kotlin/net/corda/node/services/statemachine/FlowStateMachineImpl.kt, node/src/main/kotlin/net/corda/node/services/statemachine/FlowTimeoutException.kt, node/src/main/kotlin/net/corda/node/services/statemachine/SingleThreadedStateMachineManager.kt, node/src/main/kotlin/net/corda/node/services/statemachine/StaffedFlowHospital.kt, node/src/main/kotlin/net/corda/node/services/statemachine/StateMachineManager.kt, node/src/main/kotlin/net/corda/node/services/statemachine/StateMachineState.kt, node/src/main/kotlin/net/corda/node/services/statemachine/transitions/DeliverSessionMessageTransition.kt, node/src/main/kotlin/net/corda/node/services/statemachine/transitions/StartedFlowTransition.kt, node/src/main/kotlin/net/corda/node/services/statemachine/transitions/TopLevelTransition.kt, node/src/main/kotlin/net/corda/node/services/statemachine/transitions/UnstartedFlowTransition.kt, node/src/test/kotlin/net/corda/node/services/statemachine/RetryFlowMockTest.kt, node/src/test/kotlin/net/corda/node/services/transactions/ValidatingNotaryServiceTests.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/InMemoryMessagingNetwork.kt
The original message-based retry approach does not work well with the new flow state machine due to the way sessions are handled. We decided to move the retry logic to flow-level: introduce RetryableFlow that won't have checkpoints persisted and will be restarted after a configurable timeout if it does not complete in time.
The RetryableFlow functionality will be internal for now, as it's mainly tailored for the notary client flow, and there are many subtle ways it can fail when used with arbitrary flows.
=>  CORDA-1494: Re-enable notarisation retries in the new state machine manager

node/src/main/kotlin/net/corda/node/services/network/NodeInfoWatcher.kt
(cherry picked from commit 2fce979)
=> Cherry-pick: CORDA-1604 Node Info file watcher should block and load node info when node startup (#959)

docs/source/changelog.rst, node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt, node/src/test/kotlin/net/corda/node/services/vault/VaultQueryTests.kt, testing/test-utils/src/main/kotlin/net/corda/testing/internal/vault/VaultFiller.kt
Filter contract states returned from `NodeVaultService._trackBy` to only include the tracked state type in the `produced` and `consumed` sets.
=> VaultTrack returns undesired states #3276

node-api/src/main/kotlin/net/corda/nodeapi/internal/network/NetworkBootstrapper.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/network/WhitelisGenerator.kt, node-api/src/test/kotlin/net/corda/nodeapi/internal/network/NetworkBootstrapperTest.kt, node-api/src/test/kotlin/net/corda/nodeapi/internal/network/WhitelistGeneratorTest.kt
This PR extracts the whitelist generation logic and makes it public. This is needed for the [ENT-2020](https://r3-cev.atlassian.net/browse/ENT-2020).
This change doesn't alter the existing behaviour, therefore no docs/changelog updates are needed.
=> CORDA-1593 Extracting the whitelist logic and making it public

node-api/src/main/kotlin/net/corda/nodeapi/internal/ArtemisMessagingClient.kt, node/src/main/kotlin/net/corda/node/services/messaging/InternalRPCMessagingClient.kt, node/src/main/kotlin/net/corda/node/services/messaging/P2PMessagingClient.kt
If the Artemis connectionTTL is not set then not all cleanup actions happen on client process death. This in particular prevents durable messages being replayed to the client, but may include other resources not being cleaned. We did try to set the connectionTTLOverride server side, but that caused periodic disconnects.
I have also modified the RPC setting of this. I am happy to debate if this should be changed in this PR, or not.
=> ENT-2053: Ensure Artemis cleanup actions run on client disconnect.

node/src/main/resources/reference.conf
This will ensure that the notary client flow will retry over a sufficient
period of time for the notary to update its network map.
With a backoff base of 1.8 and 5 retries the last retry will fire after
about 20 min 8 sec of the initial flow start:
\#     Timeout, sec
0	30
1	54
2	97.2
3	174.96
4	314.928
5	566.8704
Total 1208 = 20.13 min
@fenryka that should be sufficient to ensure a network update has happened, right?
=> CORDA-1628: Increase max restart count for notary client flows.

build.gradle, buildSrc/jarfilter/src/test/kotlin/net/corda/gradle/jarfilter/DummyJar.kt, buildSrc/jarfilter/src/test/kotlin/net/corda/gradle/jarfilter/JarFilterConfigurationTest.kt, buildSrc/jarfilter/src/test/kotlin/net/corda/gradle/jarfilter/MetaFixConfigurationTests.kt, buildSrc/jarfilter/src/test/kotlin/net/corda/gradle/jarfilter/Utilities.kt
JDKs 8u <= 161 have zip compresion bugs on MacOS (High Sierra), so raise minimum JDK to 8u171.
Also ensure that Gradle unit tests show stacktraces to make bugs like these easier to diagnose in future.
=> ENT-1463, ENT-1903: Raise minimum JDK to 8u171 to fix ZIP compression bugs,

tools/bootstrapper/build.gradle
Fixes gradle publish error:
```
Execution failed for task ':tools:bootstrapper:publishTools-network-bootstrapperPublicationToMavenLocal'.
> Failed to publish publication 'tools-network-bootstrapper' to repository 'mavenLocal'
> Invalid publication 'tools-network-bootstrapper': multiple artifacts with the identical extension and classifier ('jar', 'null').`
```
NOTE: this has already been applied to the `pre-release-V3` branch
https://github.com/corda/enterprise/pull/1002
=> Fix bootstrapper publication problem.

.ci/api-current.txt, build.gradle, constants.properties, core/src/main/kotlin/net/corda/core/contracts/Attachment.kt, core/src/main/kotlin/net/corda/core/transactions/TransactionWithSignatures.kt
Kotlin 1.2.50 allows `@JvmDefault` also to generate the previous `$DefaultImpls` classes, and therefore preserve binary compatibility with earlier Corda releases.
The updated compiler option also requires everyone to update the IntelliJ Kotlin plugin to 1.2.50.
=> ENT-1463: Upgrade to Kotlin 1.2.50

docs/source/cordapp-custom-serializers.rst, serialization/src/test/java/net/corda/serialization/internal/amqp/JavaCustomSerializerTests.java
Another issue user interaction flagged is that the example code only had a Kotlin example... which they found initially offputting. Add a Java example to further clarify how things should be written.
=> CORDA-1641 - Add Java example to proxy serializer documentation

client/jfx/src/main/kotlin/net/corda/client/jfx/model/TransactionDataModel.kt, core/src/main/kotlin/net/corda/core/messaging/CordaRPCOps.kt, node/src/main/kotlin/net/corda/node/internal/CordaRPCOpsImpl.kt
The issue is that by default, not all states are saved to the vault. Only the "relevant" ones.
This causes issues with the Explorer, which displays all transactions, and calculates the balance updates based on the input and output states of the tx.
The fix is to just load the transaction that created the inputStates from the database
=> CORDA-1407 Node Explorer - fix total column

constants.properties, docs/source/generating-a-node.rst, docs/source/node-structure.rst, docs/source/release-notes.rst
Update to gradle-plugins to 4.0.24 to bring changes in Cordformation task:
* ENT-2059 Cordform Gradle task ('deployNodes') doesn't work when 'configFile' element was used
* ENT-2035 The 'node' entry has a new optional element 'drivers', which is a list of JAR files to be copied to the './driver' subdirectory relative to node directory.
=> Update to gradle-plugins 4.0.24 for ENT-2059 and ENT-2035

core/src/main/kotlin/net/corda/core/internal/FlowIORequest.kt, core/src/main/kotlin/net/corda/core/internal/InternalUtils.kt, node/src/main/kotlin/net/corda/node/services/statemachine/FlowStateMachineImpl.kt, node/src/main/kotlin/net/corda/node/services/statemachine/StaffedFlowHospital.kt, node/src/main/kotlin/net/corda/node/services/statemachine/transitions/StartedFlowTransition.kt, node/src/test/kotlin/net/corda/node/services/statemachine/IdempotentFlowTests.kt
When an idempotent sub-flow causes a flow restart, the flow will be
replayed from the last checkpoint before the sub-flow invocation.
However, the logic between the last checkpoint and the sub-flow invocation
may contain side-effects which shouldn't be replayed. Thus we need to persist
a checkpoint just before an idempotent sub-flow is invoked.
=> CORDA-1645: Checkpoint before calling an idempotent sub-flow.

node-api/src/main/kotlin/net/corda/nodeapi/internal/bridging/AMQPBridgeManager.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/protonwrapper/engine/ConnectionStateMachine.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/protonwrapper/engine/EventProcessor.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/protonwrapper/netty/AMQPChannelHandler.kt
The existing approach to logging in the bridges was to modify the name of the logger per endpoint. However, this information was incomplete and being truncated. Put it into a context local MDC, although as this all happens on the Netty thread pools we have to manually wrap all the log calls.
=> ENT-1534: Change to use MDC logic in bridge/AMQP protocol logging

node/src/integration-test/kotlin/net/corda/node/services/TimedFlowTests.kt, node/src/main/kotlin/net/corda/node/services/statemachine/SingleThreadedStateMachineManager.kt, node/src/main/kotlin/net/corda/node/utilities/StateMachineManagerUtils.kt
Make sure the same progress tracker object is re-used in the restarted flow so subscribers can keep receiving progress updates.
=> CORDA-1610: Retain progress tracker during flow retry.

docs/source/corda-configuration-file.rst, node-api/src/main/kotlin/net/corda/nodeapi/internal/crypto/X509Utilities.kt, node/src/integration-test/kotlin/net/corda/node/services/rpc/RpcSslTest.kt, node/src/main/kotlin/net/corda/node/NodeArgsParser.kt, node/src/main/kotlin/net/corda/node/internal/Node.kt, node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt, node/src/main/kotlin/net/corda/node/services/config/NodeConfiguration.kt, node/src/main/kotlin/net/corda/node/services/config/rpc/NodeRpcOptions.kt, node/src/main/kotlin/net/corda/node/utilities/CertificatesUtils.kt, node/src/test/kotlin/net/corda/node/NodeArgsParserTest.kt, node/src/test/kotlin/net/corda/node/services/rpc/ArtemisRpcTests.kt, samples/trader-demo/src/main/kotlin/net/corda/traderdemo/TraderDemo.kt, testing/test-utils/src/main/kotlin/net/corda/testing/internal/InternalTestUtils.kt, tools/shell/src/integration-test/kotlin/net/corda/tools/shell/InteractiveShellIntegrationTest.kt
see https://r3-cev.atlassian.net/browse/ENT-1796
Problems addressed by this PR:
- add "--just-generate-rpc-ssl-settings" command line argument that generates all the plumbing and also instructions around the rpc ssl configuration
- fix config documentation and add note around how to generate the settings
- make config checks better
=> ENT-1796 RPC SSL

core/src/main/kotlin/net/corda/core/internal/PathUtils.kt, core/src/test/kotlin/net/corda/core/internal/PathUtilsTest.kt
This fixes the creation of DemoBench profiles.
=> CORDA-1639: Resolve ProviderMismatchException when copying a file into a ZIP.

tools/demobench/build.gradle, tools/demobench/src/main/kotlin/net/corda/demobench/plugin/CordappController.kt, tools/demobench/src/main/kotlin/net/corda/demobench/profile/ProfileController.kt, tools/explorer/capsule/build.gradle
The `bank-of-corda` JAR used to enable the `CashIssueFlow`. However, this functionality has since been superseded and so this JAR can now be deleted.
=> CORDA-1685: Remove `bank-of-corda.jar` from DemoBench.

node/src/integration-test/kotlin/net/corda/node/services/TimedFlowTests.kt
For some reason the timed flow can take 10s or more to retry when running in CI
=> TimedFlowTests: remove progress tracker completion timeout

tools/demobench/build.gradle, tools/explorer/build.gradle
`hibernate-core` is 6.5MB, and neither DemoBench nor Node Explorer needs it. They are both quite fat enough already.
And small warning/consistency fixes in `build.gradle` files too.
=> CORDA-1687: Remove unwanted hibernate-core from DemoBench and Node Explorer.

tools/demobench/build.gradle, tools/demobench/src/main/kotlin/net/corda/demobench/model/NodeConfig.kt, tools/demobench/src/test/kotlin/net/corda/demobench/model/NodeConfigTest.kt
Write issuable currencies into `node.conf` so that DemoBench's Node Explorer can execute `Cash Issue` transactions.
=> ENT-2145: Configure DemoBench nodes to issue selected currencies.

tools/demobench/package-demobench-exe.bat, tools/demobench/package/bugfixes/apply.bat
Specify paths to build tools correctly or else bugfixes will not applied.
=> Fix DemoBench Windows installer

client/rpc/src/integration-test/kotlin/net/corda/client/rpc/CordaRPCClientTest.kt, client/rpc/src/main/kotlin/net/corda/client/rpc/CordaRPCClient.kt, client/rpc/src/main/kotlin/net/corda/client/rpc/internal/serialization/amqp/AMQPClientSerializationScheme.kt, core/src/main/kotlin/net/corda/core/contracts/TransactionState.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/SerializerFactory.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/ProcessUtilities.kt, testing/smoke-test-utils/src/main/kotlin/net/corda/smoketesting/NodeProcess.kt, testing/test-common/src/main/kotlin/net/corda/testing/common/internal/TestCommonUtils.kt, tools/shell/src/main/kotlin/net/corda/tools/shell/InteractiveShell.kt
This is to allow the standalone shell to be able to receive WireTransactions containing Cash.State objects.
=> CORDA-1660: Wiring up the CordaRPCClient class loader to the p2p serialisation context

client/rpc/src/main/kotlin/net/corda/client/rpc/internal/RPCClientProxyHandler.kt
Such that they do not prevent application that started them from exiting.
=> CORDA-1686: Make "rpc-client-sender" daemon

client/rpc/src/smoke-test/kotlin/net/corda/kotlin/rpc/StandaloneCordaRPClientTest.kt, testing/smoke-test-utils/src/main/kotlin/net/corda/smoketesting/NodeProcess.kt
For now the workaround is to manually select the notary. The proper solution is to add notaries to the network parameters in smoke tests.
=> Fixed broken smoke test caused by no notaries in the network parameters

client/jfx/src/main/kotlin/net/corda/client/jfx/model/NodeMonitorModel.kt, tools/explorer/src/main/kotlin/net/corda/explorer/Main.kt, tools/explorer/src/main/kotlin/net/corda/explorer/views/LoginView.kt
While we have already made the offending RPC thread into a daemon, Node Explorer should really also be closing its RPC connection when it shuts down.
=> CORDA-1686: Make Node Explorer release its RPC connection on shutdown.

tools/demobench/src/main/kotlin/net/corda/demobench/explorer/Explorer.kt, tools/demobench/src/main/kotlin/net/corda/demobench/pty/R3Pty.kt, tools/demobench/src/main/kotlin/net/corda/demobench/rpc/NodeRPC.kt, tools/demobench/src/main/kotlin/net/corda/demobench/views/NodeTerminalView.kt
On rare occasions, DemoBench has not shut down in a timely manner because `NodeRPC` timer threads were left running. Therefore:
- Turn these timer threads into daemons.
- Interrupt the timer threads on shutdown, in case they are stuck (e.g.) waiting for network I/O.
- Ensure that all `NodeTerminalView` resources are destroyed on close, despite any exceptions.
Also fix whitespace issues and some compiler warnings.
=> CORDA-1693: Ensure that DemoBench's RPC connections terminate on shutdown.

serialization-deterministic/build.gradle, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/AMQPSerializationScheme.kt
Do not scan the classpath for serialisers inside the DJVM.
=> ENT-1903: Remove fast-classpath-scanner from serialization-deterministic.

buildSrc/jarfilter/src/main/kotlin/net/corda/gradle/jarfilter/FilterTransformer.kt, buildSrc/jarfilter/src/main/kotlin/net/corda/gradle/jarfilter/JarFilterTask.kt, buildSrc/jarfilter/src/main/kotlin/net/corda/gradle/jarfilter/MetadataTransformer.kt, buildSrc/jarfilter/src/test/kotlin/net/corda/gradle/jarfilter/FieldRemovalTest.kt, buildSrc/jarfilter/src/test/kotlin/net/corda/gradle/jarfilter/StaticFieldRemovalTest.kt
Give `ClassTransformer` a more descriptive name now that the JarFilter plugin has evolved to implement more than one task.
=> Rename JarFilter's ClassTransformer to FilterTransformer.

docs/source/corda-configuration-file.rst, docs/source/node-administration.rst, docs/source/node-database-access-h2.rst
As a fall-out from checking the Enterprise node administration documentation, it turned out that a lot of the changes should go into Corda as well, clearing up some dev/prod differences and adding details about flags.
=> Node adminstration documentation rewrite

finance/src/main/kotlin/net/corda/finance/flows/CashConfigDataFlow.kt
The Finance CorDapp relied on `net.corda.core.internal.PathUtilsKt` which has undergone refactoring, causing incompatibility across versions OS 3.0, 3.1 and Enterprise 3.0. This PR removes the dependency on the helper class in `net.corda.core.internal`.
=> CORDA-1711 - Remove dependency on PathUtilsKt in net.corda.core.internal

docs/source/_static/codesets.js, docs/source/_static/css/custom.css
Make java examples the default in the doc site html version to make life easier for Java devs writing CordApps.
Doing this for HTML is easy as it just requires a small change in the JavaScript we use for displaying code blocks.
=> CORDA-1710 Swap order of Java and Kotlin examples in HTML docs

node-api/src/main/kotlin/net/corda/nodeapi/internal/bridging/AMQPBridgeManager.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/protonwrapper/engine/ConnectionStateMachine.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/protonwrapper/engine/EventProcessor.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/protonwrapper/netty/AMQPChannelHandler.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/protonwrapper/netty/AMQPClient.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/protonwrapper/netty/AMQPConfiguration.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/protonwrapper/netty/AMQPServer.kt, node/src/integration-test/kotlin/net/corda/node/amqp/AMQPBridgeTest.kt, node/src/integration-test/kotlin/net/corda/node/amqp/CertificateRevocationListNodeTests.kt, node/src/integration-test/kotlin/net/corda/node/amqp/ProtonWrapperTests.kt
This code rationalises the explosion in constructor parameters to the AMQP protocol wrappers.
Also uses correct nested scopes for the MDC based context logging as recommended by Michele.
Also, handles appropriately the SSL Handshake Timeout, although sadly that does require spotting the message string coming out of Netty.
=> Some code tidy up ahead of post-GA development.

buildSrc/jarfilter/kotlin-metadata/build.gradle, core-deterministic/build.gradle, core/src/main/kotlin/net/corda/core/flows/StateMachineRunId.kt, core/src/main/kotlin/net/corda/core/internal/FlowStateMachine.kt, serialization-deterministic/build.gradle, serialization/src/main/kotlin/net/corda/serialization/internal/OrdinalIO.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/CustomSerializer.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/TransformTypes.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/TransformsSchema.kt
Some of ProGuard's output is useful, although a lot of it isn't. And it can only be configured on a "class by class" basis. So disable it completely except for the `checkDeterminism` tasks.
Also resolve some of the issues that ProGuard is noticing.
=> CORDA-1704: Suppress ProGuard's "note" output

node-api/src/main/kotlin/net/corda/nodeapi/internal/config/ConfigUtilities.kt, node-api/src/test/kotlin/net/corda/nodeapi/internal/config/ConfigParsingTest.kt
The custom config parser can enable use of more complex config file parsing logic, e.g. can use to parse a list of object sharing the same super type.
=> Custom config parser for more complex config structure

docs/source/running-a-node.rst
Document running nodes on a remote machine after generating them on a local machine with Cordform task.
=> Document running nodes remotely (related to ENT-1678)

build.gradle, constants.properties
This fixes the compiler performance regression introduced by Kotlin 1.2.50.
=> CORDA-1723: Upgrade to Kotlin 1.2.51.

buildSrc/build.gradle, buildSrc/jarfilter/README.md, buildSrc/jarfilter/src/main/kotlin/net/corda/gradle/jarfilter/FilterTransformer.kt, buildSrc/jarfilter/src/main/kotlin/net/corda/gradle/jarfilter/JarFilterTask.kt, buildSrc/jarfilter/src/main/kotlin/net/corda/gradle/jarfilter/KotlinAwareVisitor.kt, buildSrc/jarfilter/src/main/kotlin/net/corda/gradle/jarfilter/MetaFixerVisitor.kt, buildSrc/jarfilter/src/main/kotlin/net/corda/gradle/jarfilter/SanitisingTransformer.kt, buildSrc/jarfilter/src/main/kotlin/net/corda/gradle/jarfilter/Utils.kt, buildSrc/jarfilter/src/test/kotlin/net/corda/gradle/jarfilter/DeleteConstructorTest.kt, buildSrc/jarfilter/src/test/kotlin/net/corda/gradle/jarfilter/SanitiseConstructorTest.kt, buildSrc/jarfilter/src/test/kotlin/net/corda/gradle/jarfilter/matcher/JavaMatchers.kt, buildSrc/jarfilter/src/test/kotlin/net/corda/gradle/jarfilter/matcher/KotlinMatchers.kt, buildSrc/jarfilter/src/test/resources/sanitise-constructor/build.gradle, buildSrc/jarfilter/src/test/resources/sanitise-constructor/kotlin/net/corda/gradle/HasOverloadedConstructors.kt, core-deterministic/build.gradle, core-deterministic/testing/build.gradle, core-deterministic/testing/src/test/kotlin/net/corda/deterministic/contracts/UniqueIdentifierTest.kt, core/src/main/kotlin/net/corda/core/contracts/UniqueIdentifier.kt, docs/source/deterministic-modules.rst, serialization-deterministic/build.gradle
Adding default parameter values to a Kotlin constructor instructs the Kotlin compiler to generate a public synthetic secondary constructor as well as the expected primary constructor. This synthetic constructor for `UniqueIdentifier` is now part of Corda's ABI and so needs to be restored after being removed accidentally from `core` proper.
Update `JarFilter` to "sanitise" certain annotations (i.e. `@DeleteForDJVM`) from primary constructors while leaving them on the secondary ones. The net effect is that JarFilter is able to delete all of a class's secondary constructors while leaving the primary constructor intact.
=> CORDA-1699: Restore binary compatibility for UniqueIdentifier class.

.idea/compiler.xml, docs/source/corda-configuration-file.rst, docs/source/network-bootstrapper.rst
Tried to add clarity to the bootstrapper documentation around
a) bootstrapping with cordapps
b) whitelisting contracts
c) regenerating the whitelist
=> CORDA-1712 - Make documentation clearer for Network Bootstrapper

docs/source/flow-state-machines.rst
in reading this document from docs.corda.net, trying to understand the flow state machines (support /development perspective), I found that the negative outlook of limitations in ethereum and bitcoin may be a bit out-dated and interrupted learning thought/understanding - on this specific page.  adjusted the verbage to keep the point that there are development challenges that we've addressed, but removed the excess language around ethereum and bitcoin
=> Removed the negative reference to ethereum/bitcoin

node/src/main/kotlin/net/corda/node/services/network/NetworkMapUpdater.kt
I noticed that after changing to http-based network map, it takes 10+ seconds for the node to shut down on Ctrl-C. This affects testing of things that need to experiment with starting corda nodes (deployment, ..). Indeed, the shutdown time is related to network map update interval.
I found that by default the executor used here will run the scheduled task on shutdown and that it can be disabled.
=> Configure NetworkMapUpdater executor so that it doesn't block node shutdown

docs/source/building-container-images.rst, docs/source/index.rst, node/build.gradle
Create image and upload to the registry without requiring docker:
```
./gradlew node:jib --image <registry>/<image>:<tag>
```
=> Add jib gradle plugin to node

build.gradle, core-deterministic/build.gradle, core/src/main/kotlin/net/corda/core/identity/CordaX500Name.kt, core/src/main/kotlin/net/corda/core/internal/InternalUtils.kt, core/src/test/kotlin/net/corda/core/internal/InternalUtilsTest.kt, serialization-deterministic/build.gradle
Remove references to Guava code from `core` so that modules that use it are free to use whichever version of Guava they like.
=> ENT-1565: Remove Guava code from core.

build.gradle
Grgit doesn't support git worktrees, see https://github.com/ajoberstar/grgit/issues/97.
I'm assuming git is always available when working in a git repository.
In the future, we might include a check if the current repo is clean, e.g.
by running `git diff --exit-code` and checking the return value.
=> Don't use grgit to enable git worktree

build.gradle, docs/source/changelog.rst, node-api/src/main/kotlin/net/corda/nodeapi/internal/MessageSizeChecksInterceptor.kt, serialization/build.gradle
Upgrading as soon as possible after CE 3.0 GA to maximise regression finding time.
=> ENT-1565 Upgrade Artemis version to latest.

node-api/src/main/kotlin/net/corda/nodeapi/internal/crypto/KeyStoreUtilities.kt
This fixes the issue with path parent returning a null value when path is given just as a file name - e.g. "file.jks" instead of "./file.jks"
There is no unit test for this as it is difficult to manipulate at runtime Java's working directory.
=> CORDA-1805 Fixing the NPE with path parent

node/src/main/resources/reference.conf
Backport of https://github.com/corda/corda/pull/3357
This will ensure that the notary client flow will retry over a sufficient
period of time for the notary to update its network map.
With a backoff base of 1.8 and 5 retries the last retry will fire after
about 20 min 8 sec of the initial flow start:
0	30
1	54
2	97.2
3	174.96
4	314.928
5	566.8704
Total 1207.9584	= 20.13264 min
=> CORDA-1628: Increase max restart count for notary client flows. (#3357)

node/src/main/kotlin/net/corda/node/services/statemachine/FlowStateMachineImpl.kt, node/src/main/kotlin/net/corda/node/services/statemachine/StateMachineManagerImpl.kt, node/src/test/kotlin/net/corda/node/services/statemachine/FlowFrameworkTests.kt
see: https://r3-cev.atlassian.net/browse/CORDA-1790
Basically the issue is that an exception thrown during a flow would cause an inconsistent db.
( node_transactions were inserted but not cash_states)
=> CORDA-1790 Roll back flow transaction on exception

buildSrc/jarfilter/src/main/kotlin/net/corda/gradle/jarfilter/Elements.kt, buildSrc/jarfilter/src/main/kotlin/net/corda/gradle/jarfilter/MetaFixerTransformer.kt, buildSrc/jarfilter/src/main/kotlin/net/corda/gradle/jarfilter/MetadataTransformer.kt, buildSrc/jarfilter/src/test/kotlin/net/corda/gradle/jarfilter/MetaFixConstructorDefaultParameterTest.kt, buildSrc/jarfilter/src/test/kotlin/net/corda/gradle/jarfilter/MetaFixConstructorTest.kt, buildSrc/jarfilter/src/test/kotlin/net/corda/gradle/jarfilter/MetaFixFunctionDefaultParameterTest.kt, buildSrc/jarfilter/src/test/kotlin/net/corda/gradle/jarfilter/MetaFixFunctionTest.kt, buildSrc/jarfilter/src/test/kotlin/net/corda/gradle/jarfilter/MetaFixPackageDefaultParameterTest.kt, buildSrc/jarfilter/src/test/kotlin/net/corda/gradle/jarfilter/MetaFixPackageTest.kt, buildSrc/jarfilter/src/test/kotlin/net/corda/gradle/jarfilter/PackageWithDefaultParameters.kt, buildSrc/jarfilter/src/test/kotlin/net/corda/gradle/jarfilter/Utilities.kt, buildSrc/jarfilter/src/test/kotlin/net/corda/gradle/jarfilter/asm/ClassMetadata.kt, buildSrc/jarfilter/src/test/kotlin/net/corda/gradle/jarfilter/template/PackageWithDefaultParameters.kt
Kotlin generates special synthetic constructors and functions to support any default parameter values. So ensure that we also update the Kotlin metadata accordingly, should these synthetic methods happen to disappear (e.g. ProGuard).
=> CORDA-1748: Delete unwanted default parameter values from Kotlin metadata.

buildSrc/jarfilter/src/main/kotlin/net/corda/gradle/jarfilter/Elements.kt, buildSrc/jarfilter/src/main/kotlin/net/corda/gradle/jarfilter/FilterTransformer.kt, buildSrc/jarfilter/src/main/kotlin/net/corda/gradle/jarfilter/JarFilterTask.kt, buildSrc/jarfilter/src/main/kotlin/net/corda/gradle/jarfilter/UnwantedCache.kt, buildSrc/jarfilter/src/test/kotlin/net/corda/gradle/jarfilter/DeleteInnerLambdaTest.kt, buildSrc/jarfilter/src/test/kotlin/net/corda/gradle/jarfilter/FieldRemovalTest.kt, buildSrc/jarfilter/src/test/kotlin/net/corda/gradle/jarfilter/StaticFieldRemovalTest.kt, buildSrc/jarfilter/src/test/kotlin/net/corda/gradle/jarfilter/UnwantedCacheTest.kt, buildSrc/jarfilter/src/test/resources/delete-inner-lambda/build.gradle, buildSrc/jarfilter/src/test/resources/delete-inner-lambda/kotlin/net/corda/gradle/HasInnerLambda.kt
Lambda classes can have an "outer class" or an "enclosing method", and the lambda should be deleted if either is removed. Otherwise ProGuard may reject the filtered classes as having inconsistent byte-code.
=> CORDA-1785: Update JarFilter to delete classes whose outer class is removed.

finance/src/integration-test/kotlin/net/corda/finance/flows/CashSelectionTest.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/CordaPersistence.kt
Backport of https://r3-cev.atlassian.net/browse/CORDA-1548
https://github.com/corda/corda/pull/3266
=> Back-port CORDA-1548 Hibernate session not flushed before handing over raw JDBC session to user code (e.g. coin selection)

confidential-identities/build.gradle, core/build.gradle
Quasar is only providing its annotations (i.e. @Suspendable) at compile time, so remove its transitive dependencies such as Guava.
=> CORDA-1814: Remove Quasar's transitive dependencies.

build.gradle, constants.properties, samples/simm-valuation-demo/build.gradle, samples/simm-valuation-demo/contracts-states/build.gradle, samples/simm-valuation-demo/flows/build.gradle
The `contracts-states` CorDapp is so large that it breaks Corda's 10 MB transaction limit. This is because OpenGamma has a lot of transitive dependencies. For now, use ProGuard to discard all of the classes that we are not using.
We cannot be as aggressive with ProGuard as we'd like, partly for licensing reasons but also because the `flows` CorDapp uses the same classpath and so may try to use these OpenGamma classes too.
=> CORDA-1800: Shrink the Simm Valuation Demo's contract states using ProGuard.

core/build.gradle, core/src/test/kotlin/net/corda/core/flows/AttachmentTests.kt, core/src/test/kotlin/net/corda/core/matchers/FlowMatchers.kt
Modify a test which uses `MockNetwork` so that a) the network is re-used between tests, and b) tests use randomised party names, so that they do not conflict or pollute each other's state.
Added utility functions (grouped into _generators_, _operations_ and _matchers_) to clarify test flow and intention. [Hamkrest](https://github.com/npryce/hamkrest) is used to defined re-usable, composable matchers.
=> Reuse mock network, randomising party names to avoid clash

docs/source/node-database-access-h2.rst, docs/source/node-database.rst
Fixed markup issue in database docs for the h2Settings syntax
=> CORDA-1818 fix markup in h2 docs

node/src/test/kotlin/net/corda/node/services/network/NetworkMapClientTest.kt, node/src/test/kotlin/net/corda/node/services/network/NetworkMapUpdaterTest.kt, node/src/test/kotlin/net/corda/node/services/network/NetworkParametersReaderTest.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/network/NetworkMapServer.kt
See discussion in https://github.com/corda/corda/pull/3630 on why these were made integration tests in the first place. Turns out that wasn't needed as we can avoid using `PortAllocation`.
=> Moved network services tests back as unit tests

docs/source/upgrade-notes.rst
Reassign the release version V3.0 to require running different SQL upgrade - related to CORDA-1804.
=> H2 database table upgrade notes from 3.0 to 3.2 fix - related to CORDA-1804.

tools/demobench/package-demobench-exe.bat, tools/demobench/package/bugfixes/apply.bat
Specify paths to build tools correctly or else bugfixes will not applied.
(cherry picked from commit 4cc4e3f)
=> Fix DemoBench Windows installer (#3451)

node/src/integration-test/kotlin/net/corda/node/services/messaging/ArtemisMessagingTest.kt, node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt, node/src/main/kotlin/net/corda/node/services/api/ServiceHubInternal.kt, node/src/main/kotlin/net/corda/node/services/network/PersistentNetworkMapCache.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/InternalMockNetwork.kt
The loading of all node infos in the start method was unnecessary, both for the changePublisher and _loadDBSuccess, and the setting of _registrationFuture was incorrect.
=> Removed PersistentNetworkMapCache.start()

core-deterministic/build.gradle, serialization-deterministic/build.gradle
Prefer files over path strings, which is hopefully more forgiving on Windows.
=> Prefer files to paths when configuring ProGuard.

confidential-identities/build.gradle, constants.properties, core/build.gradle, node/build.gradle
Remove explicit dependency on `quasar-core` agent because this is managed by the `quasar-utils` plugin, which does the following:
- Adds `quasar-core` to the `compileOnly` configuration _without_ transitive deps
- Adds `quasar-core` to the `cordaRuntime` configuration _without_ transitive deps
- Adds `quasar-core` to the `runtimeClasspath` configuration _with_ transitive deps
This means that `core` now has `quasar-core` on its compile classpath, but not any of Quasars transitive dependencies. However, these dependencies _are_ still available on the runtime classpath.
Note that we had silently upgraded to `kryo-serializers:0.42` since `quasar-core` 0.7.9, so make this explicit too.
=> CORDA-1832: Configure Quasar dependency using quasar-utils plugin.

node/src/main/kotlin/net/corda/node/services/api/CheckpointStorage.kt, node/src/main/kotlin/net/corda/node/services/persistence/DBCheckpointStorage.kt, node/src/main/kotlin/net/corda/node/services/statemachine/Action.kt, node/src/main/kotlin/net/corda/node/services/statemachine/ActionExecutorImpl.kt, node/src/main/kotlin/net/corda/node/services/statemachine/transitions/TopLevelTransition.kt, node/src/main/kotlin/net/corda/node/services/statemachine/transitions/UnstartedFlowTransition.kt
Explicitly add/update checkpoints rather than calling `addOrUpdate` which will run a `select` statement and then a add or update statement.
=> CORDA-1840 Smarter checkpoint writing

confidential-identities/src/main/kotlin/net/corda/confidential/IdentitySyncFlow.kt
This PR replaces the identical #3430 which is closed due to github merge issues.
This change makes the IdentitySyncFlow usable in more scenarios.
For example, refer to the issue per corda/obligation-cordapp#5 .
In that example, A has an obligation to B and both A and B are anonymous. B transfers it to anonymous C. To make A and C know each other's identity, we use ISF. But it will throw an TransactionResolutionException when C trying to loadStates since C does not have the input in the local storage.
The proposed fix is to first check if an input is in the local storage and load it if it is.
Yes
N/A
=> IdentitySyncFlow - loadStates of an input only if it is in local storage

serialization/src/main/kotlin/net/corda/serialization/internal/amqp/AMQPExceptions.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/ArraySerializer.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/CollectionSerializer.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/CorDappCustomSerializer.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/DeserializationInput.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/DeserializedParameterizedType.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/EnumEvolutionSerializer.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/EnumSerializer.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/Envelope.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/EvolutionSerializer.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/FingerPrinter.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/MapSerializer.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/ObjectSerializer.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/PropertySerializers.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/Schema.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/SerializationHelper.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/SerializationOutput.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/SerializerFactory.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/TransformsSchema.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/custom/ClassSerializer.kt, serialization/src/test/java/net/corda/serialization/internal/ForbiddenLambdaSerializationTests.java, serialization/src/test/kotlin/net/corda/serialization/internal/amqp/AMQPExceptionsTests.kt, serialization/src/test/kotlin/net/corda/serialization/internal/amqp/EnumEvolvabilityTests.kt, serialization/src/test/kotlin/net/corda/serialization/internal/amqp/EnumTests.kt, serialization/src/test/kotlin/net/corda/serialization/internal/amqp/PrivatePropertyTests.kt
The issue is that the error reporting framework in the serializer is
targeted at developers in the node. However, because we pass exceptions
to users over RPC those error messages aren't always helpful.
Keep an internal exception that tracks debug useful information and log
that just before any exception escapes the framework and allow for
specific user "problem mitigation" issues to be set.
=> CORDA-1672 - Enable better user-helpful error messages

testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/MutableTestCorDapp.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/TestCordappsUtils.kt
Or else tests are going to fail on Windows, e.g.:
https://ci-master.corda.r3cev.com/viewLog.html?buildId=103027&tab=buildResultsDiv&buildTypeId=Corda_BuildWindowsTest
```
java.lang.IllegalArgumentException: Illegal character in path at index 95: file:/F:/buildAgent/work/f0cf2ea65c8f73ab/finance/build/libs/corda-finance-4.0-SNAPSHOT.jar/net\corda\finance\contracts\asset\BilateralNetState.class
at java.net.URI.create(URI.java:852)
at net.corda.testing.node.internal.JarEntryInfo$Companion.classFileURL(TestCordappsUtils.kt:209)
at net.corda.testing.node.internal.JarEntryInfo$Companion.access$classFileURL(TestCordappsUtils.kt:199)
at net.corda.testing.node.internal.JarEntryInfo$ClassJarEntryInfo.<init>(TestCordappsUtils.kt:178)
at net.corda.testing.node.internal.TestCordappsUtilsKt.jarEntryInfo …
```
=> CORDA-1799: Always use "/" as a path separator inside JARs

.ci/api-current.txt, docs/source/changelog.rst, testing/node-driver/src/main/kotlin/net/corda/testing/node/MockNetwork.kt, testing/node-driver/src/test/java/net/corda/testing/node/TestResponseFlowInIsolationInJava.java, testing/node-driver/src/test/kotlin/net/corda/testing/node/internal/TestResponseFlowInIsolation.kt
An addition (non-breaking change) to the public test API (`MockNet` and `StartedMockNode`) to support a customer use case (see [CORDA-916](https://r3-cev.atlassian.net/browse/CORDA-916) and the associated [StackOverflow query](https://stackoverflow.com/questions/48166626/how-can-an-acceptor-flow-in-corda-be-isolated-for-unit-testing/)).
This PR adds a method, `StartedMockNode.registerFlowFactory` to the `StartedMockNode` API, and includes tests in Java and Kotlin, based on the original use case, which show this method in use.
It also adds a Kotlin-only extension method to `StartedMockNode` which makes use of Kotlin language features (reified type-parameters and lambda parameters) to provide a simplified form of the same functionality for Kotlin users.
=> CORDA-916: Add registerFlowFactory method to public test API

core-deterministic/testing/common/src/main/kotlin/net/corda/deterministic/common/TransactionVerificationRequest.kt, core/src/main/kotlin/net/corda/core/internal/AbstractAttachment.kt, docs/source/changelog.rst, node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt, node/src/main/kotlin/net/corda/node/internal/CordaRPCOpsImpl.kt, node/src/main/kotlin/net/corda/node/internal/cordapp/CordappProviderImpl.kt, node/src/main/kotlin/net/corda/node/services/api/ServiceHubInternal.kt, node/src/main/kotlin/net/corda/node/services/persistence/AttachmentStorageInternal.kt, node/src/main/kotlin/net/corda/node/services/persistence/NodeAttachmentService.kt, node/src/test/kotlin/net/corda/node/services/persistence/NodeAttachmentServiceTest.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/InternalMockNetwork.kt, testing/test-utils/src/main/kotlin/net/corda/testing/dsl/TestDSL.kt, testing/test-utils/src/main/kotlin/net/corda/testing/internal/MockCordappProvider.kt
"app", "rpc", "p2p" and "unknown" have security implications (see isUploaderTrusted method) and thus they are not allowed to be used in the uploader field when importing attachments via the public API.
=> Added checks against the use of the special uploader tokens

testing/node-driver/src/main/kotlin/net/corda/testing/node/MockNetwork.kt
There are two variants of `MockNetwork.createUnstartedNode(...)`, and their default parameters make
the following call ambiguous:
```kotlin
val node = mockNetwork.createUnstartedNode(DUMMY_BANK_A_NAME)
```
Remove the default value for `additionalCordapps` to align this API with `MockNetwork.createNode(...)`.
=> CORDA-1861: Remove default value to make createUnstartedNode() unambiguous.

docs/source/example-code/src/test/kotlin/net/corda/docs/CustomVaultQueryTest.kt, docs/source/example-code/src/test/kotlin/net/corda/docs/WorkflowTransactionBuildTutorialTest.kt, node/src/integration-test/kotlin/net/corda/services/messaging/MQSecurityTest.kt, node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt, node/src/test/kotlin/net/corda/node/internal/FlowRegistrationTest.kt, node/src/test/kotlin/net/corda/node/services/statemachine/FlowFrameworkTests.kt
In AbstractNode.internalRegisterFlowFactory check if a flow factory already exists for an initiating flow
If a factory does exist, throw an exception
A few tests needed to be fixed due to this change
One extra thing I want to note.
It looks like this is already somewhat handled when loading a Cordapp and that the change I have made is more likely to catch an issue in a test than in an actual application. When the cordapp is loaded with multiple registered flows you will get the following error.
```
java.lang.IllegalArgumentException: net.corda.node.Initiator has been specified as the initiating flow by both net.corda.node.Responder and net.corda.node.AnotherResponder
```
In cases where this error doesn't occur, the change I have made will catch the error.
=> In AbstractNode check if an initiating flow already has a flow registered to it and throw exception if one has been

testing/node-driver/src/main/kotlin/net/corda/testing/node/MockNetwork.kt, testing/node-driver/src/test/kotlin/net/corda/testing/node/MockNetworkTest.kt, testing/node-driver/src/test/kotlin/net/corda/testing/node/internal/MockNetworkTest.kt
Create `StartedMockNode` objects for nodes created by `MockNetwork.startNodes()`.
=> CORDA-1862: Allow MockNetwork to create StartedMockNode from UnstartedMockNode.

docs/source/corda-configuration-file.rst, docs/source/example-code/build.gradle, docs/source/node-database-access-h2.rst, docs/source/node-database.rst, node/src/integration-test/kotlin/net/corda/node/AddressBindingFailureTests.kt, node/src/integration-test/kotlin/net/corda/node/persistence/H2SecurityTests.kt, node/src/main/kotlin/net/corda/node/internal/Node.kt, samples/attachment-demo/build.gradle, samples/bank-of-corda-demo/src/main/kotlin/net/corda/bank/BankOfCordaCordform.kt, samples/cordapp-configuration/build.gradle, samples/irs-demo/cordapp/build.gradle, samples/network-verifier/build.gradle, samples/notary-demo/README.md, samples/notary-demo/src/main/kotlin/net/corda/notarydemo/BFTNotaryCordform.kt, samples/notary-demo/src/main/kotlin/net/corda/notarydemo/CustomNotaryCordform.kt, samples/notary-demo/src/main/kotlin/net/corda/notarydemo/RaftNotaryCordform.kt, samples/notary-demo/src/main/kotlin/net/corda/notarydemo/SingleNotaryCordform.kt, samples/simm-valuation-demo/build.gradle, samples/trader-demo/build.gradle
* Set the "h2.allowedClasses" system property
* Require database password when exposing H2 server on non-localhost address
* Samples start H2 server by default (reintroduces the behaviour before `h2Settings.address` configuration option was added)
=> ENT-2188 fix H2 insecure default configuration

tools/bootstrapper/src/main/kotlin/net/corda/bootstrapper/Main.kt
If you run bootstrapper with the `--install-shell-extensions` parameter it will add a line to the `~/.bashrc` settings file creating an alias so that the bootstrapper can be run using `bootstrapper <options>` from the commandline.
It will also create an auto-completion file in `~/.completion/bootstrapper` and add another line to the `~/.bashrc` file which loads all of the files in the `~/.completion` directory.
To test for bash run
```bash
./gradlew clean :tools:bootstrapper:jar
cd ./tools/bootstrapper/build/libs
java -jar network-bootstrapper-4.0-SNAPSHOT.jar --install-shell-extensions
```
Then for bash run:
```bash
. ~/.bashrc
```
For zsh run:
```bash
. ~/.zshrc
```
- ~~Merge with @kasiastreich's base class~~ - will do as part of https://r3-cev.atlassian.net/browse/CORDA-1833
=> CORDA-1848 Add example alias and autocomplete for CLI tools

core/src/main/kotlin/net/corda/core/flows/CollectSignaturesFlow.kt
Added a `@JvmOverloads` annotation to the  `SignTransactionFlow` constructor, allowing Java applications to utilize the default parameters (like the provided `ProgressTracker`)
Closes #3725 
=> Added @jvmoverloads annotation to SignTxnFlow constructor

node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/DatabaseTransaction.kt, node/src/main/kotlin/net/corda/node/services/keys/E2ETestKeyManagementService.kt, node/src/main/kotlin/net/corda/node/utilities/AppendOnlyPersistentMap.kt, node/src/test/kotlin/net/corda/node/services/persistence/HibernateColumnConverterTests.kt
Use a `SessionEventListener` to be aware of flushes.
=> CORDA-1866 Avoid circular flushing in our hibernate column converters. 

testing/node-driver/src/integration-test/kotlin/net/corda/testing/driver/DriverTests.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/DriverDSLImpl.kt
DriverDSLImpl -> NetworkVisibilityController -> register check organisation name rather than X500 name and throw IllegalStateException if already exists
Added test to DriverTests to test multiple organisation names end exceptionally
=> CORDA-1837: Reject nodes that have the same organisation name in driver tests

client/rpc/src/test/kotlin/net/corda/client/rpc/AbstractRPCTest.kt, client/rpc/src/test/kotlin/net/corda/client/rpc/RPCHighThroughputObservableTests.kt, client/rpc/src/test/kotlin/net/corda/client/rpc/RPCLargeObservableTests.kt, node/src/main/kotlin/net/corda/node/services/messaging/RPCServer.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/RPCDriver.kt
Not a proper fix for production code yet, but a testcase exposing the problem.
Also minor extension to RPCServer which will allow to shut it down quicker.
=> CORDA-1844: Support for high throughput Observables shipped via RPC

node/src/integration-test/kotlin/net/corda/node/services/messaging/ArtemisMessagingTest.kt, node/src/integration-test/kotlin/net/corda/node/services/network/PersistentNetworkMapCacheTest.kt, node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt, node/src/main/kotlin/net/corda/node/services/network/NetworkMapCacheImpl.kt, node/src/main/kotlin/net/corda/node/services/network/PersistentNetworkMapCache.kt, node/src/test/kotlin/net/corda/node/internal/NodeRestartTests.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/InternalMockNetwork.kt
Otherwise PersistentNetworkMapCache only completed the future if a node-info was added, which may not occur after a node restart and thus prevented the SMM from registering its listener with the messaging layer.
Further, the future is only completed if the node-info is other than the node's own one.
=> ENT-2359: Complete the nodeReady future if there are already node-infos in the db on startup

core/src/main/kotlin/net/corda/core/internal/notary/NotaryServiceFlow.kt, core/src/main/kotlin/net/corda/core/internal/notary/TrustedAuthorityNotaryService.kt, node/src/main/kotlin/net/corda/node/services/transactions/BFTNonValidatingNotaryService.kt, node/src/main/kotlin/net/corda/node/services/transactions/BFTSMaRt.kt, node/src/main/kotlin/net/corda/node/services/transactions/NonValidatingNotaryFlow.kt, node/src/main/kotlin/net/corda/node/services/transactions/ValidatingNotaryFlow.kt
* NotaryServiceFlow now takes references into account when comparing number of inputs vs maxAllowedInputs.
* Added reference state support for BFTSMaRt notary.
* Minor formatting changes.
=> Added reference state support for BFTSMaRt notary

node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt, node/src/test/kotlin/net/corda/node/services/vault/VaultQueryTests.kt, webserver/src/main/kotlin/net/corda/webserver/WebServer.kt
https://r3-cev.atlassian.net/browse/CORDA-1388
Notes:
- There has been some debate on the best way to address this issue, and the more general one about exposing a query API, see ticket for a summary.
- The work potentially resulting from the point above will be addressed in separate PRs.
=> [CORDA-1822]: Improved error message when too many results are asked with default pagination.

finance/src/test/kotlin/net/corda/finance/schemas/SampleCashSchemaV1.kt
This PR fixes the annoying Exception stacks generated in tests:
```
Caused by: org.h2.jdbc.JdbcSQLException: Index "CCY_CODE_IDX" already exists; SQL statement:
create index ccy_code_idx on contract_cash_states_v1 (ccy_code) [42111-197]
Caused by: org.h2.jdbc.JdbcSQLException: Index "PENNIES_IDX" already exists; SQL statement:
create index pennies_idx on contract_cash_states_v1 (pennies) [42111-197]
```
=> Fix duplicate index declaration in Cash schema.

core-deterministic/testing/data/build.gradle
The `test-data.jar` artifact is added to various test classpaths, but is not generated unless the tests are actually run. This triggers warnings in IntelliJ.
Re-jig Gradle so that this jar is built after the `assemble` task without needing to run the tests.
=> Include the deterministic test-data.jar in the build's assembly.

core/src/main/kotlin/net/corda/core/context/InvocationContext.kt
https://r3-cev.atlassian.net/browse/CORDA-1681
Considerations:
1. We need to be able to test the Shell, or it will always get broken.
2. There's a `CordaSerializableBeanSerializerModifier` in `CordaModule` which computes a difference between the AMQP properties and the renamed ones from Jackson. In this case, if the field is private, AMQP will contain the key, but the renamed ones will not, resulting in a thrown error. Not sure what's going on there.
=> [CORDA-1681]: It is not possible to run stateMachinesSnapshot from the shell (fixed)

docs/source/changelog.rst, node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt, node/src/test/kotlin/net/corda/node/services/vault/NodeVaultServiceTest.kt
Back-port for next OS release (3.3)
This has already been fixed on master as part of https://github.com/corda/corda/pull/3047
=> CORDA-1895 Fix loadStates for large page sizes and added unit test.

core/src/main/kotlin/net/corda/core/node/services/VaultService.kt, core/src/main/kotlin/net/corda/core/node/services/vault/QueryCriteria.kt, core/src/test/kotlin/net/corda/core/flows/WithReferencedStatesFlowTests.kt, finance/src/main/kotlin/net/corda/finance/contracts/GetBalances.kt, finance/src/main/kotlin/net/corda/finance/contracts/asset/cash/selection/CashSelectionH2Impl.kt, finance/src/main/kotlin/net/corda/finance/contracts/asset/cash/selection/CashSelectionPostgreSQLImpl.kt, finance/src/main/kotlin/net/corda/finance/contracts/asset/cash/selection/CashSelectionSQLServerImpl.kt, node/src/main/kotlin/net/corda/node/services/vault/HibernateQueryCriteriaParser.kt, node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt, node/src/main/kotlin/net/corda/node/services/vault/VaultSchema.kt, node/src/test/kotlin/net/corda/node/services/vault/NodeVaultServiceTest.kt
* Added new Vault Query API: `StateModificationStatus` which ca be `MODIFIABLE`, `NOT_MODIFIABLE` or `ALL`
* Updated "StateMetaData"
* All the query criteria now take `StateModificationStatus` as a new parameter
* Default behaviour is to query for `ALL` states as that is what Corda has previously done
* Added new column to `VaultStates` table called `is_modifiable` which stores the value of the enum which can only be set to RELEVANT or NOT_RELEVANT, never ALL
* Updated `getCashBalances` to only query for `MODIFIABLE` states as we only want to count cash states which we own!
* Added tests
Probably needs some optimisation as we now perform multiple "isModifiable" checks (key lookups).
TODO: Add better docs.
=> * Added "isRelevant" functionality to the vault.

webserver/build.gradle
Corda includes the Servlet 3.x APIs, but we only include the Servlet 2.0 implementation inside the WebServer. This prevents anyone from writing (say) an asynchronous servlet inside a CorDapp.
Include Jersey's Servlet 3.x implementation, which also includes the 2.0 implementation.
=> CORDA-1906: Add Servlet 3.x implementation into the WebServer.

node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt
So, with regards to https://r3-cev.atlassian.net/browse/CORDA-1920, I'm enabling the messages back.
=> Fixing exception messages not showing up in the console because of log4j2.xml setup.

core-deterministic/testing/src/test/kotlin/net/corda/deterministic/CheatingSecurityProvider.kt
Guaranteeing that each of these `Provider` classes has a unique name ensures that it can always be removed by name, even if more than one instance has been installed simultaneously.
=> Ensure that every CheatingSecurityProvider has a unique name.

.ci/api-current.txt, client/jackson/src/main/kotlin/net/corda/client/jackson/StringToMethodCallParser.kt, client/jackson/src/test/kotlin/net/corda/client/jackson/StringToMethodCallParserTest.kt, node/src/main/kotlin/net/corda/node/shell/InteractiveShell.kt, node/src/test/kotlin/net/corda/node/InteractiveShellTest.kt
Conflicts:
client/jackson/src/main/kotlin/net/corda/client/jackson/internal/JacksonUtils.kt
client/jackson/src/test/kotlin/net/corda/client/jackson/StringToMethodCallParserTest.kt
node/src/main/kotlin/net/corda/node/shell/InteractiveShell.kt
tools/shell/src/test/java/net/corda/tools/shell/InteractiveShellJavaTest.java
=> CORDA-1907: Allow Corda's shell to deserialise using generic type information.

core/src/main/kotlin/net/corda/core/contracts/ContractsDSL.kt
The `Requirements` object needs its own `@KeepForDJVM` annotation because it's has its own `.class` file. It does not inherit the `@file:KeepForDJVM` annotation applied to the `ContractsDSL.class`.
=> CORDA-1925: Include Requirements object in core-deterministic.

node/src/main/kotlin/net/corda/node/internal/schemas/NodeInfoSchema.kt, node/src/main/resources/migration/node-info.changelog-master.xml, node/src/main/resources/migration/node-info.changelog-v3.xml
Rename column HOST to HOST_NAME in table NODE_INFO_HOSTS - required by ENT-2253
=> Database column rename required by ENT-2253

core/src/main/kotlin/net/corda/core/node/services/VaultService.kt, core/src/main/kotlin/net/corda/core/node/services/vault/QueryCriteria.kt, core/src/test/kotlin/net/corda/core/flows/WithReferencedStatesFlowTests.kt, finance/src/main/kotlin/net/corda/finance/contracts/GetBalances.kt, finance/src/main/kotlin/net/corda/finance/contracts/asset/cash/selection/CashSelectionH2Impl.kt, finance/src/main/kotlin/net/corda/finance/contracts/asset/cash/selection/CashSelectionPostgreSQLImpl.kt, finance/src/main/kotlin/net/corda/finance/contracts/asset/cash/selection/CashSelectionSQLServerImpl.kt, node/src/main/kotlin/net/corda/node/services/vault/HibernateQueryCriteriaParser.kt, node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt, node/src/main/kotlin/net/corda/node/services/vault/VaultSchema.kt, node/src/main/resources/migration/vault-schema.changelog-v5.xml, node/src/test/kotlin/net/corda/node/services/vault/NodeVaultServiceTest.kt
instead of "modifiable" (states are not modifiable by definition on an immutable ledger), 
plus we already expose the notion of **relevancy** in our public API via the `StatesToRecord`  `ONLY_RELEVANT` enum type.
=> CORDA-1913 Revert back to using notion of "relevancy"

docs/source/design/data-model-upgrades/signature-constraints.md
A `CompositeKey` is typically produced by a `CompositeKey.Builder()`, the `build()` method of which is declared to return a `PublicKey`. If only one public key was added to the builder, then the builder returns that key itself as a plain `PublicKey`; otherwise it returns a `CompositeKey`, but this implementation remains hidden behind the `PublicKey` interface, which supports checking whether a key is fulfilled by multiple signers.
Accordingly, it makes sense to have `SignatureAttachmentConstraint` declare its constraining `key` as a `PublicKey` rather than a `CompositeKey`, since in many cases (where there is only one signer) it will be just a plain `PublicKey`. The [existing implementation of `SignatureAttachmentConstraint` ](https://github.com/corda/corda/pull/3839) works like this; …
=> CORDA-1916 Update docs to reflect constraint implementation

tools/shell/src/main/kotlin/net/corda/tools/shell/InteractiveShell.kt, tools/shell/src/test/java/net/corda/tools/shell/InteractiveShellJavaTest.java, tools/shell/src/test/kotlin/net/corda/tools/shell/InteractiveShellTest.kt
This makes the constructor prototypes more concise when a flow doesn't match, by using just the class names of types that are in "well known" package namespaces:
=> Improve the error messages printed by the shell when a flow c'tor doesn't match

build.gradle
* remove any transitive dependency on Logback (brought by Liquibase 3.6)
* change to older Liquibase 3.5.5 version anyway to align with Enterprise repo as Liquibase 3.6.x introduces some changes to object names case sensitivity and this is incompatible with Corda use
=> CORDA-1940 Liquibase imports logback which is redundant and conflicts with log4j2

serialization/src/main/kotlin/net/corda/serialization/internal/carpenter/ClassCarpenter.kt, serialization/src/test/kotlin/net/corda/serialization/internal/carpenter/ClassCarpenterTest.kt
The following test fails, because the `ClassCarpenter` incorrectly calculates the stack size of fields if there are double-size primitive fields (e.g. long or double) in a superclass constructor:
```kotlin
@Test
fun `superclasses with double size primitive constructor parameters`() {
val schema1 = ClassSchema(
"gen.A",
mapOf("a" to NonNullableField(Long::class.javaPrimitiveType!!)))
val schema2 = ClassSchema(
"gen.B",
mapOf("b" to NonNullableField(String::class.java)),
schema1)
val clazz = cc.build(schema2)
val i = clazz.constructors[0].newInstance(1L, "xb") as SimpleFieldAccess
assertEquals(1L, i["a"])
assertEquals("xb", i["b"])
assertEquals("B{a=1, b=xb}", i.toString())
}
```
The fault is in `ClassWriter.generateClassConstructor`, and the solution is to sum the sizes of the fields in …
=> CORDA-1945: properly support double-width interp stack slots in superclasses when synthesising

node/src/main/kotlin/net/corda/node/services/vault/HibernateQueryCriteriaParser.kt, node/src/test/java/net/corda/node/services/vault/VaultQueryJavaTests.java, node/src/test/kotlin/net/corda/node/services/persistence/HibernateConfigurationTest.kt, node/src/test/kotlin/net/corda/node/services/vault/VaultQueryTests.kt, testing/test-utils/src/main/kotlin/net/corda/testing/contracts/DummyState.kt, testing/test-utils/src/main/kotlin/net/corda/testing/internal/vault/VaultFiller.kt
* Reproduce composite query failures.
* Fixes to OR querying and composite queries that use the same QueryCriteria (Linear, Fungible, Custom) more than once.
* Revert debug logging for Hibernate SQL.
* Cleanup and remove redundant joinPredicates global var.
* Fix failing Java Unit test.
* Fix Java compilation error in example-code section of docs.
* Include copy() function for original constructor to maintain backwards API compatibility.
=> CORDA-1888 Fix Vault Query composite queries  (#3775)

core/src/main/kotlin/net/corda/core/internal/DigitalSignatureWithCert.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/network/NetworkMap.kt
This PR fixes the certificate path verification process in case of the incoming network map data. It no longer assumes any specific certificate path length.
=> CORDA-1932 Fixing network map certificate path verification

core/src/main/kotlin/net/corda/core/transactions/MerkleTransaction.kt
Primarily making the deserialiseComponentGroup method simpler.
=> Clean up of MerkleTransaction.kt

tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/volumes/Volume.kt
Since [this](https://github.com/corda/corda/commit/c0207b2219f3dd647f84da72452492d0c3fc15fb) commit, if maxTransactionSize > maxMessageSize the node will fail to start up.
=> Stop bootstrapper errors caused by maxTransactionSize > maxMessageSize

node/src/main/kotlin/net/corda/node/services/network/NetworkMapClient.kt
This PR adds missing version info headers to the node info submission request.
=> CORDA-1938 adding VersionInfo to the node info submission

node/src/test/kotlin/net/corda/node/services/vault/NodeVaultServiceTest.kt, node/src/test/kotlin/net/corda/node/services/vault/VaultFlowTest.kt, testing/test-utils/src/main/kotlin/net/corda/testing/internal/vault/UniqueDummyFungibleContract.kt, testing/test-utils/src/main/kotlin/net/corda/testing/internal/vault/UniqueDummyLinearContract.kt
Add tests to NodeVaultServiceTest
Add VaultFlowTest
Add UniqueDummyFungibleContract and UniqueLinearContract to be used in the constraint tests
This PR was added in response to [https://github.com/corda/corda/issues/3482](https://github.com/corda/corda/issues/3482) which I could not reproduce.
The tests were added to confirm that the above issue is not present and confirms that the current implementation is working as expected.
=> Add tests to confirm that if a Hibernate error occurs the transaction will fail and no states will be persisted

.ci/api-current.txt, client/rpc/src/integration-test/java/net/corda/client/rpc/CordaRPCJavaClientTest.java, client/rpc/src/integration-test/kotlin/net/corda/client/rpc/RPCStabilityTests.kt, client/rpc/src/main/kotlin/net/corda/client/rpc/CordaRPCClient.kt, client/rpc/src/main/kotlin/net/corda/client/rpc/internal/RPCClientProxyHandler.kt, client/rpc/src/main/kotlin/net/corda/client/rpc/internal/serialization/amqp/RpcClientObservableDeSerializer.kt, client/rpc/src/test/kotlin/net/corda/client/rpc/ClientRPCInfrastructureTests.kt, client/rpc/src/test/kotlin/net/corda/client/rpc/RPCConcurrencyTests.kt, client/rpc/src/test/kotlin/net/corda/client/rpc/RPCFailureTests.kt, client/rpc/src/test/kotlin/net/corda/client/rpc/RPCHighThroughputObservableTests.kt, client/rpc/src/test/kotlin/net/corda/client/rpc/RPCPerformanceTests.kt, client/rpc/src/test/kotlin/net/corda/client/rpc/RPCPermissionsTests.kt, constants.properties, core/src/main/kotlin/net/corda/core/messaging/CordaRPCOps.kt, docs/source/changelog.rst, docs/source/clientrpc.rst, node/src/integration-test/kotlin/net/corda/node/AuthDBTests.kt, node/src/integration-test/kotlin/net/corda/node/services/rpc/ArtemisRpcTests.kt, node/src/main/kotlin/net/corda/node/internal/CordaRPCOpsImpl.kt, node/src/main/kotlin/net/corda/node/internal/rpc/proxies/AuthenticatedRpcOpsProxy.kt, node/src/main/kotlin/net/corda/node/serialization/amqp/RpcServerObservableSerializer.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/InternalMockNetwork.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/NodeBasedTest.kt
* Enable trackCallSites to be enabled from the command line using a Java property.
* Mark as deprecated a confusing configuration option that wasn't used anywhere anyway.
* Improve the docs by specifying the defaults.
* RPC will throw at startup if you're using the v4 library against a v3 server, rather than waiting until you invoke a bad RPC (better to fail early than half way through an important operation).
=> Small RPC improvements

tools/demobench/src/main/java/net/corda/demobench/config/LoggingConfig.java
DemoBench should use its own `logging.properties` file, but it will fall back to the JVM's defaults if this is unavailable for any (unlikely!) reason. Ensure that this fallback code only opens the JVM's properties file for reading.
=> Tidy up DemoBench's fallback logging configuration for JUL.

docs/source/corda-configuration-file.rst, node-api/src/main/kotlin/net/corda/nodeapi/internal/ArtemisMessagingComponent.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/bridging/AMQPBridgeManager.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/bridging/BridgeControlListener.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/bridging/BridgeManager.kt, node/src/integration-test/kotlin/net/corda/node/amqp/AMQPBridgeTest.kt, node/src/integration-test/kotlin/net/corda/services/messaging/AdditionP2PAddressModeTest.kt, node/src/main/kotlin/net/corda/node/internal/Node.kt, node/src/main/kotlin/net/corda/node/services/config/NodeConfiguration.kt, node/src/main/kotlin/net/corda/node/services/messaging/P2PMessagingClient.kt, node/src/main/resources/reference.conf, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/DriverDSLImpl.kt
It seems that previous problems I had with supporting this and not breaking service address behaviour have disappeared.
The new additionalP2PAddresses property allows these extra HA/alias names, but note older code will slice off the extra addresses, so we require all nodes to be on consistent versions of software for this to be used fully.
=> ENT-1755: Support HA P2P Addresses without load balancer

node/src/main/kotlin/net/corda/node/services/network/NodeInfoWatcher.kt
https://github.com/corda/corda/pull/3333
=> Cherry-pick: CORDA-1604 Node Info file watcher should block and load node info when node startup (#959) (#3333) 

node-api/src/main/kotlin/net/corda/nodeapi/internal/DevIdentityGenerator.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/crypto/X509Utilities.kt, node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt, node/src/test/kotlin/net/corda/node/utilities/registration/NetworkRegistrationHelperTest.kt
Reasoning, it was used in `AbstractNode.obtainIdentity` and we shouldn't have dev references there.
=> Move identity alias prefixes from DevIdentityGenerator to X509Utilities

finance/src/test/kotlin/net/corda/finance/schemas/SampleCashSchemaV1.kt
Fix the annoying Exception stacks generated in tests:
Caused by: org.h2.jdbc.JdbcSQLException: Index "CCY_CODE_IDX" already exists; SQL statement:
create index ccy_code_idx on contract_cash_states_v1 (ccy_code) [42111-197]
Caused by: org.h2.jdbc.JdbcSQLException: Index "PENNIES_IDX" already exists; SQL statement:
create index pennies_idx on contract_cash_states_v1 (pennies) [42111-197]
=> CORDA-1952 Fix duplicate index declaration. (#3779)

client/rpc/src/integration-test/kotlin/net/corda/client/rpc/RPCStabilityTests.kt, client/rpc/src/main/kotlin/net/corda/client/rpc/CordaRPCClient.kt, client/rpc/src/main/kotlin/net/corda/client/rpc/internal/RPCClientProxyHandler.kt, node/src/test/kotlin/net/corda/node/services/rpc/ArtemisRpcTests.kt, samples/irs-demo/web/src/main/kotlin/net/corda/irs/web/IrsDemoWebApplication.kt, webserver/src/main/kotlin/net/corda/webserver/internal/NodeWebServer.kt
PR that contains several tweaks made to the RPC client. These changes ensures the client will not hang waiting for a response from the node in case of connection loss. All observables and futures are set to error and cleaned up. Failover will commence based on what config settings are used when the client is created. during failover, any RPC will throw RPCException. Observables will not be re-attached, just set to call onError. Clients will need to query the node for any updates that may have happened during the failover period.
=> CORDA-1875: backport tweaks made to RPC client for handling loss of node

tools/shell/src/integration-test/kotlin/net/corda/tools/shell/InteractiveShellIntegrationTest.kt, tools/shell/src/main/kotlin/net/corda/tools/shell/InteractiveShell.kt
If a node has two flows, where one's name is a longer version of the other's, they cannot be started
=> CORDA-1892 CRaSH shell flow start fix for similar flow names.

node/src/integration-test/kotlin/net/corda/node/NodeKeystoreCheckTest.kt, node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
There was no check for TrustStore validity during node startup. Apart from adding extra checks, similarly to the other two `KeyStore`s, I slightly refactored `validateKeyStores()` so it gets more readable.
=> CORDA-1968 Ensure we check for the trustroot existence and alias validity.

docs/source/cipher-suites.rst, node/src/test/kotlin/net/corda/node/utilities/TLSAuthenticationTests.kt
Library support for this curve is not as widespread as we'd like it to be for connection security. Note, it will still be supported for Corda crypto operations, just not for the transport layer.
=> CORDA-1969 Retire SECP256K1 for TLS

tools/demobench/build.gradle
Use `Automatic-Module-Name` assigned by the root `build.gradle` file. Also simplify Groovy logic slightly, and use Gradle's up-to-date runtime configuration for jar's classpath.
=> Use standard Automatic-Module-Name for DemoBench.

client/rpc/src/main/kotlin/net/corda/client/rpc/CordaRPCClient.kt, client/rpc/src/main/kotlin/net/corda/client/rpc/internal/RPCClient.kt, client/rpc/src/main/kotlin/net/corda/client/rpc/internal/RPCClientProxyHandler.kt, docs/source/changelog.rst, node/src/main/kotlin/net/corda/node/services/statemachine/SessionRejectException.kt
This is a split-out change from an enterprise feature, but since we do have: `RPCApi.RPC_TARGET_LEGAL_IDENTITY` header constant even in OS, it would make sense to extend RPC client API to populate this.
=> ENT-2489: Additional optional parameter to specify target for RPC invocation.

node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt
Our error message on old Java version, used to mention "update to latest Java release" (which implies Java 10+). However it should point to the latest Corda-"supported" version.
Also, added a TODO to reconsider the auto-resume registration functionality, especially when used in production. The rationale is auto-resume is great UX-wise, but some node owners might want to investigate what went wrong before re-registering (and at the moment this is happening automatically without prompting).
=> More descriptive message on latest "supported" Java version that might cause confusion.

core/src/main/kotlin/net/corda/core/node/services/IdentityService.kt, node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt, node/src/main/kotlin/net/corda/node/services/statemachine/SessionRejectException.kt, node/src/test/kotlin/net/corda/node/services/statemachine/ExceptionsSerializationTest.kt
Also add a unit test that exposes the problem.
Without these changes AMQP serialization fails with the following:
```
net.corda.serialization.internal.amqp.AMQPNotSerializableException: Constructor parameter - "reason" -  doesn't refer to a property of "class net.corda.node.services.statemachine.SessionRejectException"
at net.corda.serialization.internal.amqp.SerializationHelperKt.toPropertyAccessorConstructor(SerializationHelper.kt:120) ~[corda-serialization-4.0-SNAPSHOT.jar:?]
at net.corda.serialization.internal.amqp.SerializationHelperKt.propertiesForSerializationFromConstructor(SerializationHelper.kt:107) ~[corda-serialization-4.0-SNAPSHOT.jar:?]
at net.corda.serialization.internal.amqp.custom.ThrowableSerializer.toProxy(ThrowableSerializer.kt:28) …
```
=> ENT-2489: Fix serialization for some of the CordaExceptions.

build.gradle, djvm/build.gradle, experimental/avalanche/build.gradle, node/build.gradle, tools/demobench/build.gradle, tools/explorer/build.gradle, tools/network-bootstrapper/build.gradle, tools/shell-cli/build.gradle
Ensure that every module uses the same version of the `shadow` plugin by controlling this from the root project.
Also resolve a few more Gradle warnings that will become errors with Gradle 5.0.
=> CORDA-1964: Unify versioning of the shadow plugin.

node/src/integration-test/kotlin/net/corda/node/services/network/NodeInfoWatcherTest.kt, node/src/main/kotlin/net/corda/node/services/network/NetworkMapUpdater.kt, node/src/main/kotlin/net/corda/node/services/network/NodeInfoWatcher.kt, node/src/main/kotlin/net/corda/node/services/network/PersistentNetworkMapCache.kt, node/src/test/kotlin/net/corda/node/services/network/NetworkMapUpdaterTest.kt
* CORDA-1093 Deleting node info from directory
Deleting NodeInfo from additional-node-infos directory should remove it from cache.
Backport of https://github.com/corda/corda/pull/3115
=> CORDA-1093 Deleting node info from directory (#3115)

node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/CordaPersistence.kt
* Hibernate session flushed before handing over raw JDBC session to user code + test - inserting and selecting cash in the same transaction
* Additional two tests copied from Enterprise repo
Backport cherry-pick of https://github.com/corda/corda/pull/3266
=> CORDA-1548 - Hibernate session not flushed before handing over raw JDBC session to user code (e.g. coin selection) (#3266)

node-api/src/main/kotlin/net/corda/nodeapi/internal/crypto/X509Utilities.kt, node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt, node/src/main/kotlin/net/corda/node/utilities/registration/NetworkRegistrationHelper.kt
According to the most restrictive HSM vendor until now (Azure Key Vault), key aliases should be 1-127 characters in length containing only 0-9, a-z, A-Z, and - (nothing else).
_Note that the rest of tested vendors have more relaxed restrictions (i.e., Utimaco supports up to a maximum of 256 characters, including symbols and space)._
=> CORDA-1986 Ensure key alias format is supported by the major HSM vendors

build.gradle, node/capsule/build.gradle, tools/explorer/capsule/build.gradle, webserver/webcapsule/build.gradle
The Gradle plugin creates a capsule using `capsule:1.0.1` by default. We need to configure the plugin manually to use the latest `capsule:1.0.3`.
=> CORDA-1985: Configure Gradle capsule plugin to use Capsule 1.0.3.

node/src/main/kotlin/net/corda/node/NodeCmdLineOptions.kt, node/src/test/kotlin/net/corda/node/NodeCmdLineOptionsTest.kt, tools/cliutils/src/main/kotlin/net/corda/cliutils/CordaCliWrapper.kt
Also the --network-root-truststore default value has been corrected to be relative to the base dir.
The cliutils has been updated to always convert Path cmd line params to be absolute
=> CORDA-1982: Convert the --base-directory to an absolute path to avoid issues on start up

node/src/main/kotlin/net/corda/node/internal/ExceptionsHashFunction.kt, node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt
https://r3-cev.atlassian.net/browse/CORDA-1971
- Switched error code encoding to use `base36`, with a workaround to always produce positive values.
- Removed line number from the set of `StackTraceElement` fields hashed as part of error code derivation.
- Limited the number of `StackTraceElement`s hashed as part of error code derivation to 3.
- Refactored error code derivation logic and fixed a bug this refactoring exposed.
=> [CORDA-1971]: Improve error code derivation

core/src/main/kotlin/net/corda/core/crypto/CryptoUtils.kt, node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt
This feature is required for composite ownership, for instance in HTLC.
I've also commented that `PublicKey.containsAny(otherKeys)` does not return a match if any of the `otherKeys` is of type `CompositeKey`, which means that we only check matching against leaves (non-Composite) and not looking for sub-trees inside the composite key structure.
_Note that this works assuming user's keys are not of `CompositeKey` type._
=> CORDA-2000 isRelevant to work for composite ownership.

client/jackson/src/test/kotlin/net/corda/client/jackson/JacksonSupportTest.kt, core/src/main/kotlin/net/corda/core/internal/DigitalSignatureWithCert.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/network/NetworkMap.kt
This introduces a modification which makes sending the certificate path with signature more efficient.
=> CORDA-1995 removing DigitalSignatureWithCertPath

core/src/main/kotlin/net/corda/core/node/services/VaultService.kt, core/src/main/kotlin/net/corda/core/node/services/vault/QueryCriteria.kt, core/src/test/kotlin/net/corda/core/flows/WithReferencedStatesFlowTests.kt, finance/src/main/kotlin/net/corda/finance/contracts/GetBalances.kt, finance/src/main/kotlin/net/corda/finance/contracts/asset/cash/selection/CashSelectionH2Impl.kt, finance/src/main/kotlin/net/corda/finance/contracts/asset/cash/selection/CashSelectionPostgreSQLImpl.kt, finance/src/main/kotlin/net/corda/finance/contracts/asset/cash/selection/CashSelectionSQLServerImpl.kt, node/src/main/kotlin/net/corda/node/services/vault/HibernateQueryCriteriaParser.kt, node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt, node/src/main/kotlin/net/corda/node/services/vault/VaultSchema.kt, node/src/main/resources/migration/vault-schema.changelog-v5.xml, node/src/test/kotlin/net/corda/node/services/vault/NodeVaultServiceTest.kt
=> CORDA-1999 Changed isRelevant to relevancyStatus.

node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/carpenter/ClassCarpenter.kt, node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/carpenter/ClassCarpenterTest.kt
Backport of [bugfix PR](https://github.com/corda/corda/pull/3859) for [Corda-1945](https://r3-cev.atlassian.net/browse/CORDA-1945), resolving a bug in the `ClassCarpenter`.
=> Backport Corda-1945 class-carpenter bugfix

node/src/integration-test/kotlin/net/corda/node/BootTests.kt, node/src/integration-test/kotlin/net/corda/node/flows/AsymmetricCorDappsTests.kt
Ensure distinct node names in AssymetrictCorDappsTests and BootTests integration tests - align with Enterprise repo.
=> Pass distinct node names in 2 integration tests.

node/src/main/kotlin/net/corda/node/utilities/registration/NetworkRegistrationHelper.kt, node/src/test/kotlin/net/corda/node/utilities/registration/NetworkRegistrationHelperTest.kt
This PR ensures that **ALL** the certificates present in the `network-trust-store` are copied into the node's trust store.
=> CORDA-2012 Copying all certificates from the network-turst-store

node-api/src/main/kotlin/net/corda/nodeapi/internal/ArtemisTcpTransport.kt, node-api/src/test/kotlin/net/corda/nodeapi/internal/crypto/X509UtilitiesTest.kt, node/src/test/kotlin/net/corda/node/utilities/TLSAuthenticationTests.kt
This cipher family is not supported in boring SSL - if we want to use boring SSL for TLS in any version of CORDA,  we cannot support the non-elliptic DHE RSA cipher family  anywhere for TLS.
=> CORDA-2023 Remove TLS_DHE_RSA cipher family

docs/source/release-notes.rst
Add retirement of this cipher family to the release notes.
=> CORDA-2023 Release note for retirement of TLS_DHE_RSA

client/jackson/src/test/kotlin/net/corda/client/jackson/JacksonSupportTest.kt, testing/test-utils/src/main/kotlin/net/corda/testing/core/TestUtils.kt
Required for testing other than EdDSA keys (i.e., ECDSA which is usually the default for HSMs).
=> [CORDA-2044] Allow more signature schemes to TestUtils

build.gradle, config/dev/log4j2.xml, constants.properties, docs/source/node-administration.rst, node/build.gradle, node/src/main/kotlin/net/corda/node/utilities/logging/AsyncLoggerContextSelectorNoThreadLocal.kt, node/src/main/resources/log4j2.component.properties
Switch corda to use asynchronous logging (using a custom logging context selector to avoid usage of thread local storage as this causes issues with quasar).
Default behaviour is switched to async via log4j properties, documentation how to override on the command line or config has been provided.
=> Corda-1931 Asynchronous logging

node-api/src/main/kotlin/net/corda/nodeapi/internal/protonwrapper/netty/SSLHelper.kt, node-api/src/test/kotlin/net/corda/nodeapi/internal/protonwrapper/netty/SSLHelperTest.kt
* Add test for SNI header to prevent changing it accidentally.
* bug fix
=>  CORDA-2016 Add unit tests to ensure SNI header generation will not be changed by accident

core/src/main/kotlin/net/corda/core/node/services/VaultService.kt, core/src/main/kotlin/net/corda/core/node/services/vault/QueryCriteria.kt, core/src/main/kotlin/net/corda/core/node/services/vault/QueryCriteriaUtils.kt, docs/source/api-contract-constraints.rst, docs/source/api-vault-query.rst, docs/source/changelog.rst, node/src/main/kotlin/net/corda/node/services/vault/HibernateQueryCriteriaParser.kt, node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt, node/src/main/kotlin/net/corda/node/services/vault/VaultSchema.kt, node/src/main/resources/migration/vault-schema.changelog-master.xml, node/src/main/resources/migration/vault-schema.changelog-v6.xml, node/src/test/kotlin/net/corda/node/services/vault/VaultQueryTests.kt, testing/test-utils/src/main/kotlin/net/corda/testing/internal/vault/VaultFiller.kt
Vault storage of contract state constraints metadata and associated vault query functions to retrieve and sort by constraint type.
Note: a follow-up PR will address performance improvements as per
https://r3-cev.atlassian.net/browse/CORDA-2013
=> CORDA-1997 Added constraint type information to vault states table.

docs/source/network-bootstrapper.rst
https://r3-cev.atlassian.net/browse/CORDA-2019
=> [CORDA-2019]: Bootstrapper docs should not include --dir switch (fixed)

node/build.gradle
Fixes compatibility issue surfaced as "java.lang.NoClassDefFoundError: kotlin/jdk7/AutoCloseableKt"
=> CORDA-2030 - ensure the correct kotlin runtime library is used to resolve `AutoCloseable`

testing/test-utils/build.gradle, tools/network-bootstrapper/build.gradle
Kotlin complains if it sees `kotlin-stdlib-jre8` on the compile classpath, so remove it for those cases where it doesn't need to be there.
=> CORDA-2030: Resolve build warnings created by adding kotlin-stdlib-jre8 to node.

core-deterministic/testing/src/test/kotlin/net/corda/deterministic/crypto/CryptoSignUtils.kt, core-deterministic/testing/src/test/kotlin/net/corda/deterministic/crypto/TransactionSignatureTest.kt, core/src/main/kotlin/net/corda/core/crypto/Crypto.kt, core/src/main/kotlin/net/corda/core/crypto/CryptoUtils.kt, core/src/main/kotlin/net/corda/core/internal/InternalUtils.kt, core/src/main/kotlin/net/corda/core/transactions/SignedTransaction.kt
Note that this change mainly impacts nodes where ECDSA keys are used to sign transactions. Also, by setting the default BC PRNG to newSecureRandom() we ensure that other BC PRNG requests that might be invoked in the background and we don't know (i.e., cert signing might use `CryptoServicesRegistrar`) are non-blocking anymore. 
This change caused a domino effect on disallowing all signature operations on DJVM, but because we want to check sig. verification in DJVM, part of the signing code has been ported to `deterministic.crypto`.
=> [CORDA-2063] Ensure signatures and BC operations always use newSecureRandom

core-deterministic/testing/src/test/kotlin/net/corda/deterministic/crypto/TransactionSignatureTest.kt, core/src/main/kotlin/net/corda/core/crypto/Crypto.kt, core/src/main/kotlin/net/corda/core/crypto/CryptoUtils.kt
`entropyToKeyPair` is deterministic anyway and we might need it:
a) to generate keys in DJVM tests
b) special contracts might require to generate a key inside verify() (i.e., I only send the seed (because it's smaller than the actual key) to prove that I know a private key (i.e., in special commitment schemes).
=> [CORDA-2076] Do not remove entropyToKeyPair from DJVM

confidential-identities/build.gradle, core/build.gradle
The unit tests are inheriting `kotlin-stdlib-jre8` transitively from `:node`. However, `:node-driver` already includes `:node` _without_ `kotlin-stdlib-jre8` so just use that.
=> CORDA-2030: Resolve build warnings about kotlin-stdlib-jre8 in unit tests too.

core-deterministic/testing/data/build.gradle
Gradle caches artefacts by task execution signature.
A test module of `core-deterministic` depends on the generated artefacts of an associated data module. Once the data module task is cached its generated outputs are no longer available to the test module (and hence 2 unit tests fail).
This fix forces re-execution of the data module prior to running the previously failing test module `VerifyTransactionTest`
=> Gradle cache friendly Junit test fix.

core/src/main/kotlin/net/corda/core/crypto/Crypto.kt, core/src/test/kotlin/net/corda/core/crypto/CryptoUtilsTest.kt
In practice, out of the 5 supported signature schemes, only ECDSA R1/K1 is not deterministic. For the rest, no `newSecureRandom` is required when signing.
=> [CORDA-2084] EdDSA, SPHINCS-256 and RSA PKCS#1 are deterministic, no RNG required.

testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/ShutdownManager.kt
Please see comment in the code for more info.
Also, to prove my point I am including memory profiler snapshot to show how particular object graph remains reachable from GC roots after driver run has finished.
=> ENT-2569: Clean-up content of `registeredShutdowns`.

tools/blobinspector/src/main/kotlin/net/corda/blobinspector/BlobInspector.kt, tools/blobinspector/src/main/resources/log4j2.xml
Make the logging levels work the same way as the other CLI applications:
``--logging-level=<level>`` sets the default logging level (in the bootstrapper case no default log is set up, which makes sense since it's a simple utility app)
``--verbose`` displays logging input on the console at the same level as is specified by ``--logging-level`` (or INFO by default)
This gets rid of the logging spam by default and makes blobinspector work like the pre-picocli version.
=> Make blobinspector not log to console by default

build.gradle, djvm/build.gradle, djvm/cli/src/main/kotlin/net/corda/djvm/tools/cli/Utilities.kt, djvm/src/main/kotlin/net/corda/djvm/utilities/Discovery.kt, experimental/behave/build.gradle, experimental/behave/src/scenario/kotlin/net/corda/behave/scenarios/StepsContainer.kt, node-api/build.gradle, node-api/src/main/kotlin/net/corda/nodeapi/internal/ContractsScanning.kt, node/src/main/kotlin/net/corda/node/internal/cordapp/JarScanningCordappLoader.kt, serialization/build.gradle, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/AMQPSerializationScheme.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/TestCordappsUtils.kt
FastClasspathScanner was renamed to ClassGraph for the version 4 release
=> CORDA-1274: Migrated usage of FastClasspathScanner to ClassGraph

build.gradle, tools/explorer/capsule/build.gradle
Bug ticket raised as result of 3.3 testing: [CORDA-2097](https://r3-cev.atlassian.net/browse/CORDA-2097)
Backport of https://github.com/corda/corda/pull/3437
=> CORDA-2097 - Add missing Node Explorer artefact publication

core/src/main/kotlin/net/corda/core/internal/JarSignatureCollector.kt, core/src/test/kotlin/net/corda/core/internal/JarSignatureCollectorTest.kt
(Copy from discussion under https://github.com/corda/corda-gradle-plugins/pull/119):
Signature block file name in JAR file spec can be https://docs.oracle.com/javase/8/docs/technotes/guides/jar/jar.html
```
META-INF/*.DSA
META-INF/*.RSA
META-INF/SIG-*
```
and ` Digital Signatures` paragraph states: 
```
The extension varies depending on the type of digital signature.
.RSA (PKCS7 signature, SHA-256 + RSA)
.DSA (PKCS7 signature, DSA)
Digital signature files for signature algorithms not listed 
above must reside in the META-INF directory and have the prefix "SIG-"
```
However JarSigner (https://docs.oracle.com/javase/8/docs/technotes/tools/windows/jarsigner.html) paragraph:  `The Signed JAR File` can produce (and it does):
```
A signature block file with a .DSA, .RSA, or .EC extension
```
So …
=> CORDA-195 - allow META-INF/*.EC block signature 

djvm/src/main/java/sandbox/java/lang/ThreadLocal.java
Remove `<T>` from comment because JavaDoc thinks it's HTML. And add parameter description.
=> ENT-1906: Fix JavaDoc error for DJVM.

node/build.gradle
Add `kotlin-stdlib-jre8` to the `runtimeOnly` configuration to keep it from creeping into some other module's compile classpath.
=> CORDA-2030: Prevent kotlin-stdlib-jre8 from becoming an accidental transitive dependency.

finance/src/integration-test/kotlin/net/corda/finance/compat/CashExceptionSerialisationTest.kt, finance/src/integration-test/kotlin/net/corda/finance/flows/test/CashConfigDataFlowTest.kt, finance/src/test/kotlin/net/corda/finance/contracts/asset/test/DummyFungibleContract.kt, finance/src/test/kotlin/net/corda/finance/flows/test/CashExceptionThrowingFlow.kt, finance/src/test/kotlin/net/corda/finance/schemas/test/SampleCashSchemaV1.kt, finance/src/test/kotlin/net/corda/finance/schemas/test/SampleCashSchemaV2.kt, finance/src/test/kotlin/net/corda/finance/schemas/test/SampleCashSchemaV3.kt, finance/src/test/kotlin/net/corda/finance/schemas/test/SampleCommercialPaperSchemaV1.kt, finance/src/test/kotlin/net/corda/finance/schemas/test/SampleCommercialPaperSchemaV2.kt, node/src/test/java/net/corda/node/services/vault/VaultQueryJavaTests.java, node/src/test/kotlin/net/corda/node/services/persistence/HibernateConfigurationTest.kt, node/src/test/kotlin/net/corda/node/services/vault/VaultQueryExceptionsTests.kt, node/src/test/kotlin/net/corda/node/services/vault/VaultQueryTests.kt
Move classes in the `:finance` test artifact out of sealed finance packages, in preparation for upgrading our Gradle plugins to v4.0.32.
=> CORDA-2096: Migrate finance test classes into .test sub-packages.

core/src/main/kotlin/net/corda/core/internal/CertRole.kt, core/src/test/kotlin/net/corda/core/internal/CertRoleTests.kt
Similarly to legal identity certs that allow both NodeCA and doorman as parent certs, TLS can also be signed directly by doorman.
=> [CORDA-2105] Doorman can sign TLS certs directly

core/src/test/kotlin/net/corda/core/flows/ContractUpgradeFlowTest.kt, core/src/test/kotlin/net/corda/core/flows/mixins/WithContracts.kt, node/src/main/kotlin/net/corda/node/services/CoreFlowHandlers.kt, testing/test-utils/src/main/kotlin/net/corda/testing/contracts/DummyContractV3.kt
The contract upgrade handler assumes that the state to be upgraded is
created by a WireTransaction. This breaks the upgrade process if it was
in fact issued by a ContractUpgradeWireTransactions or a NotaryChangeWireTransaction.
=> CORDA-2109: Fix a bug that prevents consecutive multiparty contract upgrades

docs/source/changelog.rst, docs/source/running-a-notary.rst, experimental/notary-bft-smart/src/main/kotlin/net/corda/notary/bftsmart/BFTSMaRtConfig.kt, experimental/notary-bft-smart/src/main/kotlin/net/corda/notary/bftsmart/BftSmartNotaryService.kt, node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt, node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt
To make BFT-Smart work previously we used to install a special serialization filter on node startup. Now that all notary implementations have moved into their own modules we need a general mechanism for configuring this filter.
=> CORDA-535: Allow notary implementations to specify a serialization filter

.idea/compiler.xml, core/src/main/kotlin/net/corda/core/internal/FlowAsyncOperation.kt, core/src/main/kotlin/net/corda/core/internal/WaitForStateConsumption.kt, docs/source/example-code/src/main/java/net/corda/docs/java/tutorial/flowstatemachines/SummingOperation.java, docs/source/example-code/src/main/java/net/corda/docs/java/tutorial/flowstatemachines/SummingOperationThrowing.java, docs/source/example-code/src/main/kotlin/net/corda/docs/kotlin/tutorial/flowstatemachines/TutorialFlowAsyncOperation.kt, node/src/integration-test/kotlin/net/corda/node/flows/FlowRetryTest.kt, node/src/main/kotlin/net/corda/node/services/statemachine/Action.kt, node/src/main/kotlin/net/corda/node/services/statemachine/ActionExecutorImpl.kt, node/src/main/kotlin/net/corda/node/services/statemachine/transitions/StartedFlowTransition.kt
A deduplication ID is passed as parameter to the `execute` method of `FlowAsyncOperation`.
=> [ENT-1774] FlowAsyncOperation deduplication ID

serialization/src/main/kotlin/net/corda/serialization/internal/model/TypeIdentifier.kt, serialization/src/test/kotlin/net/corda/serialization/internal/model/TypeIdentifierTests.kt
This is the first in a series of PRs relating to [CORDA-2099](https://r3-cev.atlassian.net/browse/CORDA-2099). In this PR, we introduce a type, `TypeIdentifier`, which serves to identify a generic type in the absence of the Java `Type` to which the identifier refers. This is useful when we have received information about types which may not be visible from the current classloader.
The story to which this PR belongs involves some fairly wide-ranging changes to the way the serialisation code models and compares types, and the early PRs (such as this one) will be introducing some pieces of equipment which are intended to help with the heavy lifting later. Without the context, it might not be obvious what they're _for_, so I'm going to try to give a quick outline of the approach I'm taking …
=> CORDA-2099: Define TypeIdentifier

buildCacheSettings.gradle
Hopefully this will remove the annoying:
`Could not load entry e391e1797463ef7e1fece4fb05a7def3 for task ':core:compileKotlin' from remote build cache: Connect to localhost:5071 [localhost/127.0.0.1] failed: Connection refused (Connection refused)`
messages.
=> Explicitly disable remote gradle build cache when building locally.

core/src/main/kotlin/net/corda/core/contracts/TransactionVerificationException.kt, core/src/main/kotlin/net/corda/core/flows/AbstractStateReplacementFlow.kt, core/src/main/kotlin/net/corda/core/flows/NotaryChangeFlow.kt, core/src/main/kotlin/net/corda/core/transactions/LedgerTransaction.kt, core/src/main/kotlin/net/corda/core/transactions/NotaryChangeTransactions.kt, core/src/main/kotlin/net/corda/core/utilities/KotlinUtils.kt, core/src/test/kotlin/net/corda/core/transactions/TransactionEncumbranceTests.kt, node/src/test/kotlin/net/corda/node/services/NotaryChangeTests.kt
Encumbrances should form a complete directed cycle, otherwise one can spend the "encumbrance" state, which would freeze the "encumbered" state for ever. This should also apply to encumbrance chains with more than two elements. Changes on `NotaryChangeLedgerTransaction` were also required. 
*Note: I didn't touch `ContractUpgradeLedgerTransaction`
For instance, the following settings are valid: 
_a -> b, b -> a_
- - -
_a -> b, b -> c, c -> a_ 
- - -
_a -> c, b -> a, c -> b_
while the following are not:
_a -> b_    (because one can spend _b_, which will freeze _a_ for ever)
- - -
_a -> c, b -> c_    (because, among the others, one can spend _a_ and _c_, which will freeze _b_ for ever)
- - -
_a -> b, b -> c_   (because, among the others, one can spend _c_, which will freeze _a_ and _b_ for …
=> [CORDA-738] Ensure encumbrances are bi-directional

constants.properties, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/EvolutionSerializer.kt
Deserialization could mix together the object trees of two threads when passing through evolution.
=> ENT-2608 - Fix deserialization of evolution 

constants.properties
Kotlin 1.2.71 was released on 24th September 2018, and our Gradle plugins are using it successfully.
Here are the [release notes](https://blog.jetbrains.com/kotlin/2018/09/kotlin-1-2-70-is-out)
=> CORDA-2111: Upgrade to Kotlin 1.2.71.

testing/test-utils/src/main/kotlin/net/corda/testing/internal/stubs/CertificateStoreStubs.kt
Even though it is not used in OS, it is better to keep it in sync with Ent.
=> ENT-2610: Correct `withBaseDirectory` method

djvm/build.gradle, djvm/cli/src/main/kotlin/net/corda/djvm/tools/cli/ClassCommand.kt, djvm/cli/src/main/kotlin/net/corda/djvm/tools/cli/WhitelistGenerateCommand.kt, djvm/src/main/java/sandbox/java/lang/Object.java, djvm/src/main/java/sandbox/java/lang/String.java, djvm/src/main/java/sandbox/java/lang/System.java, djvm/src/main/kotlin/net/corda/djvm/SandboxConfiguration.kt, djvm/src/main/kotlin/net/corda/djvm/SandboxRuntimeContext.kt, djvm/src/main/kotlin/net/corda/djvm/analysis/AnalysisConfiguration.kt, djvm/src/main/kotlin/net/corda/djvm/execution/SandboxExecutor.kt, djvm/src/main/kotlin/net/corda/djvm/messages/MessageCollection.kt, djvm/src/main/kotlin/net/corda/djvm/rewiring/SandboxClassLoader.kt, djvm/src/main/kotlin/net/corda/djvm/rewiring/SandboxClassLoadingException.kt, djvm/src/main/kotlin/net/corda/djvm/source/SourceClassLoader.kt, djvm/src/main/kotlin/sandbox/java/lang/DJVM.kt, djvm/src/test/java/net/corda/djvm/execution/SandboxEnumJavaTest.java, djvm/src/test/java/net/corda/djvm/execution/SandboxThrowableJavaTest.java, djvm/src/test/kotlin/net/corda/djvm/DJVMExceptionTest.kt, djvm/src/test/kotlin/net/corda/djvm/DJVMTest.kt, djvm/src/test/kotlin/net/corda/djvm/TestBase.kt, djvm/src/test/kotlin/net/corda/djvm/Utilities.kt, djvm/src/test/kotlin/net/corda/djvm/assertions/AssertionExtensions.kt, djvm/src/test/kotlin/net/corda/djvm/assertions/AssertiveClassWithByteCode.kt, djvm/src/test/kotlin/net/corda/djvm/assertions/AssertiveDJVMObject.kt, djvm/src/test/kotlin/net/corda/djvm/execution/SandboxEnumTest.kt, djvm/src/test/kotlin/net/corda/djvm/execution/SandboxExecutorTest.kt, djvm/src/test/kotlin/net/corda/djvm/execution/SandboxThrowableTest.kt, djvm/src/test/kotlin/net/corda/djvm/rewiring/ClassRewriterTest.kt
Allow `deterministic-rt.jar` and the template Java classes to be loaded into a parent `SandboxClassLoader` that can be shared by multiple sandboxes.
Child sandbox configurations inherit the same whitelist and pinned classes as the parent.
This has required the `System.objectHashCodes` and `String.INTERNAL` data structures to be migrated to `SandboxRuntimeContext` so that each sandbox still has its own private copy. It also means that the `DJVM` class must now fetch the correct classloader from `SandboxRuntimeContext` in order to locate user-supplied `Enum` and `Throwable` classes.
Should any other "static state" still exist in the Java API classes then would also be shareable among the child classloaders. But this change has knocked over 2 minutes off the unit test times.
Note that the …
=> ENT-1906: Allow sandboxes to share a parent classloader.

node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt
Make `NodeStartupCli.startup` overridable so Enterprise can inject it's own different version.
=> CORDA-1838: Backport ENT node changes to O/S

config/dev/log4j2.xml
net.corda.testing.driver.DriverTests#`debug mode enables debug logging level` works (only tests against logging)
=> Fixed broken default logging level.

djvm/src/main/kotlin/net/corda/djvm/rules/implementation/AlwaysInheritFromSandboxedObject.kt, djvm/src/main/kotlin/net/corda/djvm/rules/implementation/RewriteObjectMethods.kt, djvm/src/main/kotlin/sandbox/java/lang/DJVM.kt, djvm/src/test/java/net/corda/djvm/WithJava.java, djvm/src/test/java/net/corda/djvm/execution/SandboxObjectHashCodeJavaTest.java, djvm/src/test/kotlin/net/corda/djvm/TestBase.kt, djvm/src/test/kotlin/net/corda/djvm/execution/SandboxExecutorTest.kt
An array of objects is itself still `java.lang.Object` inside a sandbox, and so it cannot be added to `sandbox.java.lang.Object[]`. So keep all object arrays as `java.lang.Object[]` inside the sandbox.
=> ENT-1906: Don't transform java.Object[] to sandbox.Object[].

node/src/main/java/CordaCaplet.java
- [JIRA: CORDA-1633](https://r3-cev.atlassian.net/browse/CORDA-1633) - Present the user with a sensible message if the node is attempted started on Java 9/10/11 instead of Java 8
=> CORDA-1633 - Check Java version before launch

docs/source/corda-configuration-file.rst, node-api/src/main/kotlin/net/corda/nodeapi/internal/KeyStoreConfigHelpers.kt, node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt, node/src/main/kotlin/net/corda/node/internal/cordapp/JarScanningCordappLoader.kt, node/src/main/kotlin/net/corda/node/services/config/NodeConfiguration.kt, node/src/test/kotlin/net/corda/node/internal/cordapp/JarScanningCordappLoaderTest.kt
By default Cordaps build by corda-gradle-plugins are signed by Corda development key.
In dev mode any key can be used to sign Cordapp JAR .
In Production node Corda dev keys were forbidden but allow to opt-out by `cordappSignerKeyFingerprintBlacklist=[]` or specify more.
The parsing and throwing errors will be moved to node configuration once node configuration capabilities is overhaul (Michele work on this)
=> Optionally allow the node in production mode to accept Cordapps signed by dev Key (CORDA-1915)

docs/source/api-persistence.rst, docs/source/node-database.rst
Database docs update:
* Note about database considerations regarding Cordapp compatibility between OS and ENT.
* Remove database configuration "schema" as this is not implemented in OS, it was already mentioned as ignored for SQL server.
=> Minor docs update - Persistence API and node database 

tools/cliutils/src/main/kotlin/net/corda/cliutils/CordaCliWrapper.kt
If `verbose` is set on a subcommand the `CordaCliWrapper` wasn't properly throwing the stack trace to the console.
=> Fix CLI verbosity issue with subcommands

core/src/main/kotlin/net/corda/core/internal/CordaUtils.kt, core/src/main/kotlin/net/corda/core/transactions/MerkleTransaction.kt, core/src/main/kotlin/net/corda/core/transactions/WireTransaction.kt, core/src/main/kotlin/net/corda/core/utilities/KotlinUtils.kt, core/src/test/kotlin/net/corda/core/transactions/CompatibleTransactionTests.kt, core/src/test/kotlin/net/corda/core/utilities/LazyMappedListTest.kt, node/src/main/kotlin/net/corda/node/serialization/kryo/DefaultKryoCustomizer.kt, node/src/main/kotlin/net/corda/node/serialization/kryo/Kryo.kt
This adds a simple "LazyMappedList" and wires it into the Transaction componentGroups to make deserialization lazy.
Also small change to the "checkTransactionSize" to use the existing componentGroups to avoid unnecessary serializations/deserializations.
Also, remove the unnecessary serialization/deserialization step when creating a WireTransaction.
=> CORDA-2083 Deserialize component groups lazily

finance/src/main/kotlin/net/corda/finance/internal/CashConfigDataFlow.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/DriverDSLImpl.kt
During investigation of [CORDA-2174](https://r3-cev.atlassian.net/browse/CORDA-2174) was found that running Nodes Explorer's demo nodes fails because of multiple problems.
The first problem was caused by #4100. When app config was implemented for Finance app `issuableCurrencies` was made required. This config was missing from demo setup. With the first commit I made it optional.
The second problem is that by using this app config feature if we want to add one cordapp for all nodes with driver DSL by using `cordappsForAllNodes` and then we want for some of the nodes to have different config for that app we need to pass `additionalCordapps` to `runNode` and the node will complain that there are two different jars for the same app. This is fixed by my second commit.
=> [CORDA-2174] Fix demo node startup

.ci/api-current.txt, docs/source/api-testing.rst, docs/source/upgrade-notes.rst, experimental/notary-bft-smart/src/test/kotlin/net/corda/notary/bftsmart/BFTNotaryServiceTests.kt, finance/src/test/kotlin/net/corda/finance/contracts/asset/cash/selection/CashSelectionH2ImplTest.kt, node/src/test/kotlin/net/corda/node/internal/NetworkParametersTest.kt, node/src/test/kotlin/net/corda/node/services/TimedFlowTests.kt, node/src/test/kotlin/net/corda/node/services/statemachine/IdempotentFlowTests.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/MockNetwork.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/MockNetworkConfigOverrides.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/InternalMockNetwork.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/InternalMockNetworkConfigOverrides.kt
Introduce public subset of `NodeConfiguration` inside the mock network subproject to tweak config via mock net work without exposing internal node config.
=> CORDA-1489 Exposure of node internals in mock network

docs/requirements.txt
Requests library in docs/requirements is vulnerable. 
Bump to latest version (2.20.0)
=> CORDA-2169 Update requests dependency to latest/secure version

docs/source/tutorial-attachments.rst
`NodeAttachmentStorageTest.kt` has been renamed `NodeAttachmentServiceTest.kt` but a reference in the docs hadn't been updated. Also made some grammatical changes while I was in there.
=> Fixed a missing file error when building docs

node/src/test/kotlin/net/corda/node/services/persistence/NodeAttachmentServiceTest.kt
The NodeAttachmentService tests were causing issues on windows as cleaning up the temporary directory between tests did not work - it seems that NTFS keeps a lock on the files that have been opened by the NodeAttachementService, so they cannot be deleted. This leads to various file system exceptions being thrown when trying to delete old stuff or creating new temp files for the next test.
As solution, the tests now create a new directory for each test, and swallow any file system exceptions when deleting the temp directory - the files that are earmarked for deletion will be removed by Windows as soon as the lock is removed (i.e. when the test executable stops), but they can't be deleted while the process is still running.
=> CORDA-2175 Fix attachment service tests on Windows

core/src/main/kotlin/net/corda/core/internal/JarSignatureCollector.kt, testing/test-utils/src/main/kotlin/net/corda/testing/core/JarSignatureTestUtils.kt, testing/test-utils/src/test/kotlin/net/corda/testing/core/JarSignatureCollectorTest.kt
As discovered in CORDA-2116 Mismatch between signers for files in the `META-INF` directory, the problematic file is META-INF/INDEX.LIST.
Temporally treating META-INF/INDEX.LIST as unsignable entry because java.util.jar.JarVerifier doesn't load its signers. 
Created https://r3-cev.atlassian.net/browse/CORDA-2177 for further investigation, this PR enables to work signed JAR with INDEX.LIST for now.
=> Don't check signers of META-INF/LIST.INDEX file (workaround for CORDA-2116)

config/dev/log4j2.xml, node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
Was:
`[ERROR] 15:29:08+0000 [main] internal.Node.installCordaServices - Corda service net.corda.finance.internal.ConfigHolder failed to instantiate
Cordapp configuration is incorrect due to exception`
Now displays (well it would if the bug still existed):
``[ERROR] 17:07:26+0000 [main] internal.Node.installCordaServices - Corda service net.corda.finance.internal.ConfigHolder failed to instantiate (No configuration setting found for key 'issuableCurrencies') [errorCode=ut8i8s]``
Also fixed an issue with newlines in the default log4j confg when printing throwables in the console.
=> CORDA-2183: Show root cause of error in console to aid with debugging

.idea/compiler.xml, core/src/main/kotlin/net/corda/core/CordaOID.kt, core/src/main/kotlin/net/corda/core/crypto/CordaSecurityProvider.kt, core/src/main/kotlin/net/corda/core/crypto/internal/AliasPrivateKey.kt
As noted by @shamsasari we should use an official Corda OID and not a UUID for `AliasPrivateKey`.
=> [CORDA-2192] Corda specific OID for AliasPrivateKey

tools/shell/src/test/kotlin/net/corda/tools/shell/InteractiveShellTest.kt
The interactive shell test has a constructor taking an integer that maps to the Java primitive `int` - when trying to get this reflectively with `java.lang.Integer`, the test will fail. Usually, this does not even get run, as the commandline parsing in the shell will happily parse an integer to a string if it finds a constructor taking a string first. But occasionally, this leads to test failure.
This does not fix the parsing in the shell, but at least makes the test pass when the Integer constructor gets found first.
=> Make the shell test pass when it happens to find the Integer constructor

docs/source/corda-configuration-file.rst, docs/source/cordapp-build-systems.rst
Link from signing Cordapp document to node configuration regarding enabling Cordapp signed by dev key to be run in production mode (related to CORDA-1915).
=> Document enabling CorDapp signed by dev key to run in production mode (related to CORDA-1915)

node/src/main/kotlin/net/corda/node/services/statemachine/SessionRejectException.kt, node/src/main/kotlin/net/corda/node/services/statemachine/SingleThreadedStateMachineManager.kt, node/src/main/kotlin/net/corda/node/services/statemachine/StaffedFlowHospital.kt, node/src/test/kotlin/net/corda/node/services/FinalityHandlerTest.kt, node/src/test/kotlin/net/corda/node/services/statemachine/FlowFrameworkTests.kt, node/src/test/kotlin/net/corda/node/services/statemachine/RetryFlowMockTest.kt
This allows for the case of a missing CorDapp to be installed on node restart and recover the original flow initiate request.
=> CORDA-2129: Attempts to initiate a flow that's unknown is paused and instead sent to the flow hospital

core/src/main/kotlin/net/corda/core/contracts/TransactionVerificationException.kt, core/src/main/kotlin/net/corda/core/transactions/LedgerTransaction.kt, core/src/test/kotlin/net/corda/core/transactions/TransactionEncumbranceTests.kt
Although we already check that ALL output states should be assigned to the same Notary in `LedgerTransaction.checkNoNotaryChange`, this only applies if transaction's notary is NOT null.
However, in special cases, like issuing transactions, a transaction might have a null Notary.
Previously, it was possible that an issuer could create encumbered output states assigned to different notaries which would result to freezing all encumbered states as we don't yet support multi-notary transactions. Thus, such encumbered states could NOT be consumed in the same transaction in the future.
This PR checks if all related encumbered states are assigned to the same notary (if transaction's notary is null). The word "related" is important as a transaction can have multiple encumbrance chains and we …
=> [CORDA-2130] Encumbered states should always be assigned to the same notary

buildSrc/win_scripts/kill_corda_procs.cmd
The killing jobs script doesn't work when pasted into TC - so checked it in and then the build needs to be changed to invoked the checked-in script.
=> Add cmd file to kill corda jobs on windows

node-api/src/main/kotlin/net/corda/nodeapi/internal/bridging/BridgeControlListener.kt
It has been spotted that some bridge control publish/susbcribe message paths weren't calling acknowledge on the messages and may be leaking some resources.
=> CORDA-2206: Some code paths for bridge control are not being acknowledged

node-api/src/main/kotlin/net/corda/nodeapi/internal/crypto/ContentSignerBuilder.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/cryptoservice/CryptoService.kt, node/src/main/kotlin/net/corda/node/services/config/NodeConfiguration.kt, node/src/main/kotlin/net/corda/node/services/keys/cryptoservice/BCCryptoService.kt, node/src/test/kotlin/net/corda/node/services/keys/cryptoservice/BCCryptoServiceTests.kt
- More tests for `BCCryptoService`.
- Adding a specific `CryptoServiceException`.
- Fixing `ContentSignerBuilder.build` that failed on signing certs with Sphincs (we reported and fixed the issue in BC's github, so this is a temporal fix until the new BC version is released).
- Change `BCCryptoService`'s constructor, due to CORDA-2202
=> [CORDA-2200][CORDA-2202] More tests for BCCryptoService and CryptoServiceException

node/src/main/kotlin/net/corda/node/services/api/IdentityServiceInternal.kt, node/src/main/kotlin/net/corda/node/services/identity/InMemoryIdentityService.kt, node/src/main/kotlin/net/corda/node/services/identity/PersistentIdentityService.kt
Previously, a `partiesFromName` `query` used to traverse all X500 attributes, even if a match had already been found. It's true that because we use a `Set` there were not duplicate entries, but we should indeed stop after the first match.
The following has been applied and the function was renamed to `x500Matches`:
PS: We could also refactor this method to just return true or false and not update the `result`. I didn't do as it's not marked as internal, although its name states so ???
=> [CORDA-2210] Add matching party on the first X500 attribute match

node/build.gradle, node/src/main/java/CordaCaplet.java, node/src/test/java/CordaCapletBaseDirectoryParsingFailureTest.java, node/src/test/java/CordaCapletBaseDirectoryParsingTest.java, node/src/test/java/CordaCapletConfigFileParsingFailureTest.java, node/src/test/java/CordaCapletConfigFileParsingTest.java, node/src/test/java/CordaCapletTestUtils.java
If there are errors creating the cordapp directory, rather than throw an error when modifying the classpath, just return the existing classpath. When the main method is invoked in the `Corda.jar` it will check again and fail gracefully.
Also bring capsule in line with the options accepted by the main Corda jar.
=> CORDA-1817: Fix issue with misleading capsule error messages

node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt, node/src/test/kotlin/net/corda/node/services/statemachine/FlowFrameworkPersistenceTests.kt, node/src/test/kotlin/net/corda/node/services/statemachine/FlowFrameworkTests.kt, node/src/test/kotlin/net/corda/node/services/statemachine/FlowFrameworkTripartyTests.kt
Port of https://github.com/corda/enterprise/commit/2e9d7ce8119b05cfce038c11565330f299d3ec54
=> Back porting clean up of FlowFrameworkTests.kt made in ENT

node-api/src/main/kotlin/net/corda/nodeapi/internal/DevIdentityGenerator.kt, node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- Don't generate a composite key certificate for CFT notaries
- Don't require a composite key certificate for CFT notaries on startup
=> CORDA-2221: Fix clustered notary identity generation

core/src/main/kotlin/net/corda/core/crypto/CordaSecurityProvider.kt, core/src/main/kotlin/net/corda/core/crypto/internal/PlatformSecureRandom.kt, core/src/main/kotlin/net/corda/core/crypto/internal/ProviderMap.kt, core/src/test/kotlin/net/corda/core/crypto/CryptoUtilsTest.kt
Although we've set the default algorithm for BC operations, other classes and methods like `UUID.randomUUID` directly invoke `SecureRandom()` which internally gets a default PRNG algorithm by looking through all registered providers. Then it returns the first PRNG algorithm of the first provider that has registered a SecureRandom implementation, or null if none of the registered providers supplies a SecureRandom implementation.
This means, that some operations in Corda might still use a blocking RNG.
This PR implements and uses a `PlatformSecureRandomService` that is inserted to `CordaSecurityProvider`, which is the first registered `Provider` in Corda, ensuring that all invocations to `SecureRandom()` use our `platformSecureRandom` (which is the same as `newSecureRandom`).
=> [CORDA-2225] Use platform's non-blocking PRNG when invoking SecureRandom()

serialization/src/main/kotlin/net/corda/serialization/internal/amqp/AMQPRemoteTypeModel.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/AMQPTypeIdentifierParser.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/AMQPTypeIdentifiers.kt, serialization/src/main/kotlin/net/corda/serialization/internal/model/CarpentryDependencyGraph.kt, serialization/src/main/kotlin/net/corda/serialization/internal/model/RemoteTypeCarpenter.kt, serialization/src/main/kotlin/net/corda/serialization/internal/model/RemoteTypeInformation.kt, serialization/src/main/kotlin/net/corda/serialization/internal/model/TypeIdentifier.kt, serialization/src/main/kotlin/net/corda/serialization/internal/model/TypeLoader.kt, serialization/src/test/kotlin/net/corda/serialization/internal/amqp/AMQPRemoteTypeModelTests.kt, serialization/src/test/kotlin/net/corda/serialization/internal/amqp/AMQPTypeIdentifierParserTests.kt, serialization/src/test/kotlin/net/corda/serialization/internal/model/ClassCarpentingTypeLoaderTests.kt
This PR, continuing work on [CORDA-2099](https://r3-cev.atlassian.net/browse/CORDA-2099), introduces `RemoteTypeInformation`, which models type schema information received from remote parties, together with classes to create `RemoteTypeInformation` from AMQP `TypeNotation`, and to drive the `ClassCarpenter` directly from `RemoteTypeInformation` (topologically ordered) without the assistance of the `ClassCarpenterMetaSchema`.
=> CORDA-2099 remote type model

node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt, node/src/main/kotlin/net/corda/node/services/config/NodeConfigurationImpl.kt
This is to avoid cases where registration happened in an out of band process or it didn't finish as expected (or when deploying nodes for tests as @florian-f noticed) and in which key aliases exist only in one of the `cryptoService` and `signingCertificateStrore`, respectively. Then, we output a corresponding `IllegalStateException`.
=> [CORDA-2218] CryptoService signingCertificateStore alias match

node/src/test/kotlin/net/corda/node/services/statemachine/FlowAsyncOperationTests.kt
Looks like these tests we omitted when porting the async logic across.
=> Add omitted flow async operation test

node/src/test/kotlin/net/corda/node/utilities/AddressUtilsTests.kt
Local host address can also be public
=> Address util tests: remove invalid test case

docs/source/corda-configuration-file.rst
This PR adds documentation for the `networkParameterAcceptanceSettings` node configuration setting that was missed in PR #4222
=> Fix node configuration doc for network parameter auto-acceptance settings

serialization/src/test/kotlin/net/corda/serialization/internal/model/ClassCarpentingTypeLoaderTests.kt
Fix for a unit-test failure which is due to Jackson supplying Windows CRLF line-termination when pretty-printing.
=> Fix unit test failure due to Windows end-of-line characters

core/src/main/kotlin/net/corda/core/flows/NotaryFlow.kt, core/src/main/kotlin/net/corda/core/internal/notary/NotaryUtils.kt, node/src/test/kotlin/net/corda/node/services/transactions/NonValidatingNotaryServiceTests.kt, node/src/test/kotlin/net/corda/node/services/transactions/ValidatingNotaryServiceTests.kt, testing/test-utils/src/main/kotlin/net/corda/testing/contracts/DummyContract.kt
To make sure the notary service constructs the same serialised bytes as the client.
=> [CORDA-2243] Notary client should sign over NotarisationRequest serialised with object referencing turned off

testing/test-utils/src/main/kotlin/net/corda/testing/dsl/TestDSL.kt, testing/test-utils/src/main/kotlin/net/corda/testing/dsl/TransactionDSLInterpreter.kt, testing/test-utils/src/main/kotlin/net/corda/testing/internal/InternalTestUtils.kt, testing/test-utils/src/main/kotlin/net/corda/testing/internal/MockCordappProvider.kt
This is preliminary addition to test `"Implementation-Version"` entry from `META-INF/MANIFEST.MF` in `TestDSL.kt`.
`MockCordappProvider` was creating JAR with manifest file.
Added the manifest file with the obligatory (by JAR spec) attribute `"Manifest-Version"`, other attributes can be added.
=> CORDA-2150 Non downgrade contract version - test infrastructure part 1

core/src/main/kotlin/net/corda/core/internal/InternalUtils.kt, core/src/main/kotlin/net/corda/core/node/NetworkParameters.kt, core/src/test/kotlin/net/corda/core/contracts/PackageOwnershipVerificationTests.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/network/NetworkBootstrapper.kt, node-api/src/test/kotlin/net/corda/nodeapi/internal/network/NetworkBootstrapperTest.kt, node/src/test/kotlin/net/corda/node/internal/NetworkParametersTest.kt, tools/bootstrapper/src/main/kotlin/net/corda/bootstrapper/Main.kt, tools/bootstrapper/src/test/kotlin/net/corda/bootstrapper/PackageOwnerParsingTest.kt
Changes the type of the `packageOwnership` to avoid a bug in the old carpenter code
=> ENT-2763 - Change packageOwnership type

core/src/main/kotlin/net/corda/core/internal/CertRole.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/crypto/X509Utilities.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/network/NetworkBootstrapper.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/network/NetworkMap.kt, node-api/src/test/kotlin/net/corda/nodeapi/internal/network/NetworkBootstrapperTest.kt, node/src/main/kotlin/net/corda/node/internal/NetworkParametersReader.kt, node/src/main/kotlin/net/corda/node/services/network/NetworkMapUpdater.kt, node/src/test/kotlin/net/corda/node/services/network/NetworkMapUpdaterTest.kt, node/src/test/kotlin/net/corda/node/services/network/NetworkParametersReaderTest.kt
This change introduces a new NetworkParameters certificate role (CertRole.NETWORK_PARAMETERS). This will allow the network parameters to be signed with a different cert in the future (currently it is being signed by the NetworkMap cert).
The change is backward-compatible - it will still accept network-parameters to be signed by the networkmap cert, but will also accept a (yet to exist) network-params cert when that is created.
=> CORDA-2199 NetworkParameters certificate role

node/capsule/build.gradle
https://r3-cev.atlassian.net/browse/CORDA-2249
As per the section "The Capsule ID" in http://www.capsule.io/user-guide/#building-capsule, Capsule composite ID must be unique for each application, and it's composed by `applicationId` or `<group>.<artifact>` if unspecified, plus `_<version>`.
Hence, the fix is to specify `applicationId` inside Capsule's manifest for Corda Enterprise, and for it to be different from the one in Open Source. Even if for Open Source `<group>.<artifact>` is good as an implicit `applicationId`, I put it there explicitly to avoid confusion.
=> [CORDA-2249]: Specified unique applicationId for Capsule manifest.

client/jackson/src/main/kotlin/net/corda/client/jackson/internal/CordaModule.kt, client/jackson/src/test/kotlin/net/corda/client/jackson/JacksonSupportTest.kt, core/src/main/kotlin/net/corda/core/internal/CordaUtils.kt, core/src/main/kotlin/net/corda/core/internal/TransactionUtils.kt, core/src/main/kotlin/net/corda/core/transactions/LedgerTransaction.kt, core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt, core/src/main/kotlin/net/corda/core/transactions/WireTransaction.kt, core/src/test/kotlin/net/corda/core/transactions/CompatibleTransactionTests.kt, core/src/test/kotlin/net/corda/core/transactions/TransactionTests.kt, docs/source/changelog.rst, docs/source/serialization-default-evolution.rst, testing/test-utils/src/main/kotlin/net/corda/testing/internal/InternalTestUtils.kt
LedgerTransaction is not meant to be created directly from client code, but it being a data class means we will expose new copy methods as new properties are added. The existing copy methods that we've exposed since V3 are deprecated, and equals and hashCode have been updated to be based just on id.
The primary c'tor has been clearly marked as the class' wire format, and so the internal stuff has been moved out. The references property cannot be made nullable and so DeprecatedConstructorForDeserialization is used instead.
=> LedgerTransaction no longer a data class to prevent more copy methods and fixed serialisation issue (CORDA-2231)

core/src/main/kotlin/net/corda/core/flows/NotaryFlow.kt, core/src/main/kotlin/net/corda/core/internal/CordaUtils.kt, core/src/main/kotlin/net/corda/core/transactions/MerkleTransaction.kt, core/src/test/kotlin/net/corda/core/crypto/PartialMerkleTreeTest.kt, core/src/test/kotlin/net/corda/core/transactions/ReferenceInputStateTests.kt, docs/source/changelog.rst
A new wrapper class over `StateRef` is introduced, called `ReferenceStateRef`. Although "reference input states" are stored as `StateRef` objects in `WireTransaction`, we needed a way to distinguish between "input states" and "reference input states" when required to filter by object type. Thus, when one wants to filter-in all "reference input states" in a `FilteredTransaction` then he/she should check if it is of type `ReferenceStateRef`.
Using this pattern we can still support components of the same type in the future, but still be able to filter them differently.
=> [CORDA-2230] Distinguish between regular and reference input states while filtering

testing/node-driver/src/main/kotlin/net/corda/testing/driver/Driver.kt, testing/node-driver/src/main/kotlin/net/corda/testing/driver/DriverDSL.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/DriverDSLImpl.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/RPCDriver.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/TestCordappDirectories.kt
`internalDriver` can sign CorDapp JAR, disabled by default.
=> CORDA-2150 Non downgrade contract version - test infrastructure 3

core/src/main/kotlin/net/corda/core/contracts/TransactionVerificationException.kt, core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt, core/src/test/kotlin/net/corda/core/transactions/AttachmentsClassLoaderTests.kt
The overlap check was too restrictive causing cordapps that were built with an older version of the cordapp plugin to fail.
This relaxes the checks and introduces a special case.
Also makes the `OverlappingAttachments` exception a TransactionVerificationException.
=> Fix Attachment overlap check

serialization/src/main/kotlin/net/corda/serialization/internal/model/LocalTypeInformation.kt, serialization/src/main/kotlin/net/corda/serialization/internal/model/LocalTypeModel.kt
This PR fixes the bug described in [CORDA-2253](https://r3-cev.atlassian.net/browse/CORDA-2253), by using a local cache of constructed `LocalTypeInformation` during traversal of the type graph, and merging the local cache into the global cache once all type information has been constructed and cycles have been "patched" with the type information for the types they refer to.
=> CORDA-2253 Avoid leaking unpatched Cycles via the global type info cache

docs/source/changelog.rst, finance/build.gradle
https://github.com/corda/corda/pull/4260 removed the dependency that node had to confidential-identities which means CorDapps using it must now use compile and not cordaCompile. This resolves the failing smoke test.
=> Finance CorDapp jar includes confidential-identities

tools/shell/src/main/java/net/corda/tools/shell/FlowShellCommand.java, tools/shell/src/main/java/net/corda/tools/shell/RunShellCommand.java, tools/shell/src/main/java/net/corda/tools/shell/StartShellCommand.java, tools/shell/src/main/kotlin/net/corda/tools/shell/InteractiveShell.kt, tools/shell/src/main/kotlin/net/corda/tools/shell/InteractiveShellCommand.kt
This fixes an issue with parsing the shell commands after the cordapps were removed from the system classpath.
To actually get the vault query from shell to work , this: https://r3-cev.atlassian.net/browse/CORDA-2256 needs addressing as well.
=> CORDA-2248 fix rpc classloader issue

node/src/integration-test/kotlin/net/corda/node/flows/AsymmetricCorDappsTests.kt, node/src/integration-test/kotlin/net/corda/node/flows/FlowCheckpointVersionNodeStartupCheckTest.kt, node/src/integration-test/kotlin/net/corda/node/flows/FlowOverrideTests.kt, node/src/integration-test/kotlin/net/corda/node/services/AttachmentLoadingTests.kt, testing/node-driver/src/main/kotlin/net/corda/testing/driver/Driver.kt, testing/node-driver/src/main/kotlin/net/corda/testing/driver/DriverDSL.kt, testing/node-driver/src/main/kotlin/net/corda/testing/driver/NodeParameters.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/DriverDSLImpl.kt, tools/explorer/src/main/kotlin/net/corda/explorer/ExplorerSimulation.kt
This overload is not useful for Java devs which is why NodeParameters was created in the first place. The startNode(NodeParameters) overload is now used instead.
NodeParameters.logLevel removed as it doesn't do anything and is not in V3.
=> CORDA-2239: Clean up Driver.startNode overload which specifies node parameters with default values

serialization/src/main/kotlin/net/corda/serialization/internal/model/LocalTypeInformationBuilder.kt
Sometimes the `LocalTypeInformationBuilder` will observe types that are non-composable (i.e. we can't find a unique deserialisation constructor for them, or we can't match their constructor's signature with their observable properties) while analysing read-only properties of abstract classes or interfaces. Because we will never deserialize these properties directly (they will typically be handled by a custom serializer, or else we will be using the deserializer for a concrete implementation of that abstract type), it doesn't matter that they can't be deserialized by an `ObjectSerializer`, and we don't need to warn the user that we've encountered a non-composable type.
This PR extends warning-suppression so that it covers the following cases:
* The type is flagged as `Opaque`.
* The type …
=> CORDA-2255 suppress warnings on read-only properties

serialization/src/main/kotlin/net/corda/serialization/internal/model/TypeModellingFingerPrinter.kt, serialization/src/test/kotlin/net/corda/serialization/internal/amqp/TypeModellingFingerPrinterTests.kt
As per [CORDA-2266](https://r3-cev.atlassian.net/browse/CORDA-2266), notaries using pre-v4 code will fall into evolution serialisation (and fail) if the type descriptor of a `NotarisationPayload` sent to them doesn't match their own fingerprint. Prior to v4, the fingerprinter treated `Any` differently to `?`, and as `NotarisationPayload` has a parameter of type `Any` this results in an incompatible fingerprint being generated. The solution is to make the new fingerprinter do the same thing as the old one with these two types.
=> CORDA-2266 match old fingerprinter on Any type

.ci/api-current.txt, core/src/main/kotlin/net/corda/core/serialization/internal/SerializationEnvironment.kt, node/src/integration-test/kotlin/net/corda/node/services/network/NetworkMapTest.kt, node/src/integration-test/kotlin/net/corda/node/utilities/registration/NodeRegistrationTest.kt, testing/node-driver/src/main/kotlin/net/corda/testing/driver/Driver.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/DriverDSLImpl.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/InternalMockNetwork.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/InternalTestUtils.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/RPCDriver.kt, testing/test-utils/src/main/kotlin/net/corda/testing/internal/InternalSerializationTestHelpers.kt
Instead we detect if a serialisation environment already exists and initialise one if not.
=> CORDA-2269: Removed DriverParameters.initialiseSerialization as it's not needed

node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt, node/src/test/kotlin/net/corda/node/internal/NodeStartupCliTest.kt, node/src/test/kotlin/net/corda/node/internal/NodeStartupTest.kt, testing/node-driver/src/integration-test/kotlin/net/corda/testing/driver/DriverTests.kt
The test `started node, which is not waited for in the driver, is shutdown when the driver exits` fails on Windows.
The reason is that the test is assuming that the `process-id` is always deleted when the node is shutdown, however the `addShutdownHook` function isn't guaranteed to run, and seems to consistently not run on Windows, even if the node exits gracefully.
A better test of whether the node is running is that there is a file lock on the {{process-id}} file.
=> [CORDA-2275] Fix DriverTests for windows

client/rpc/src/main/kotlin/net/corda/client/rpc/CordaRPCClient.kt, client/rpc/src/main/kotlin/net/corda/client/rpc/internal/serialization/amqp/AMQPClientSerializationScheme.kt, core-deterministic/testing/verifier/src/main/kotlin/net/corda/deterministic/verifier/LocalSerializationRule.kt, core/src/main/kotlin/net/corda/core/serialization/SerializationAPI.kt, core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt, node/src/main/kotlin/net/corda/node/internal/Node.kt, node/src/main/kotlin/net/corda/node/serialization/amqp/AMQPServerSerializationScheme.kt, node/src/main/kotlin/net/corda/node/serialization/kryo/KryoCheckpointSerializer.kt, node/src/test/kotlin/net/corda/node/internal/serialization/RoundTripObservableSerializerTests.kt, node/src/test/kotlin/net/corda/node/internal/serialization/testutils/AMQPTestSerialiationScheme.kt, serialization/src/main/kotlin/net/corda/serialization/internal/SerializationScheme.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/AMQPSerializationScheme.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/AMQPSerializerFactories.kt, serialization/src/test/kotlin/net/corda/serialization/internal/amqp/AbstractAMQPSerializationSchemeTest.kt
- adds `withPreventDataLoss()` method to the SerializationContext that sets `mustPreserveDataWhenEvolving=true`.
- add this flag to the serialization factory cache.
- uses `withPreventDataLoss()` when creating the context to verify transactions.
This needs some integration test that is able to run with 2 different versions of the same class.
Note: It can't be manually tested yet because of this bug : https://r3-cev.atlassian.net/browse/CORDA-2263
=> CORDA-2147 Use serialization strict mode during transaction verification.

node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
(cherry picked from commit 15c11d964f5d8cd80c47aa81c56da6ef1e358bbe)
https://github.com/corda/enterprise/pull/1620
=> Stop messaging services before node dies, to prevent port hogging when using in process node (#1620)

node/src/main/kotlin/net/corda/node/services/transactions/PersistentUniquenessProvider.kt, node/src/main/resources/migration/node-notary.changelog-committed-transactions-table.xml
Shorten notary table name for older Oracle deployments. The names can't be longer than 30 characters.
=> CORDA-2277 Shorten table name

testing/node-driver/src/integration-test/kotlin/net/corda/testing/driver/DriverTests.kt, testing/node-driver/src/main/kotlin/net/corda/testing/driver/Driver.kt, testing/node-driver/src/main/kotlin/net/corda/testing/driver/internal/DriverInternal.kt, testing/node-driver/src/main/kotlin/net/corda/testing/driver/internal/GlobalTestPortAllocation.kt
https://r3-cev.atlassian.net/browse/CORDA-2282
=> [CORDA-2282]: Ensure global test port allocation prevents port clashes

core/src/main/kotlin/net/corda/core/flows/CollectSignaturesFlow.kt, core/src/main/kotlin/net/corda/core/flows/ReceiveTransactionFlow.kt, core/src/main/kotlin/net/corda/core/internal/TransactionUtils.kt, core/src/main/kotlin/net/corda/core/internal/notary/NotaryServiceFlow.kt, node/src/test/kotlin/net/corda/node/services/transactions/NotaryServiceTests.kt, node/src/test/kotlin/net/corda/node/services/transactions/ValidatingNotaryServiceTests.kt
At flag day, not all nodes may update their network parameters at the same time. There will be a period of time where the previous version of the parameters should still be accepted. That requires e.g. some timewindow encoded in the parameters, but it needs more thinking.
Until the design work is done, it's better to not check for parameter  "currentness" at all to not cause flow failures right after flag day.
=> ENT-2666: Don't check for network parameter currentness for now

build.gradle, gradle.properties
https://r3-cev.atlassian.net/browse/CORDA-2285
Gradle property "test.parallel" controls this feature, default to `false`.
=> [CORDA-2285]: Enabled jUnit parallel execution.

serialization/src/main/kotlin/net/corda/serialization/internal/amqp/AMQPRemoteTypeModel.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/EvolutionSerializerFactory.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/LocalSerializerFactory.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/TransformTypes.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/TransformsSchema.kt, serialization/src/main/kotlin/net/corda/serialization/internal/model/EnumTransforms.kt, serialization/src/main/kotlin/net/corda/serialization/internal/model/LocalTypeInformation.kt, serialization/src/main/kotlin/net/corda/serialization/internal/model/LocalTypeInformationBuilder.kt, serialization/src/main/kotlin/net/corda/serialization/internal/model/RemoteTypeInformation.kt, serialization/src/test/kotlin/net/corda/serialization/internal/amqp/EnumEvolvabilityTests.kt, serialization/src/test/kotlin/net/corda/serialization/internal/amqp/EnumTransformationTests.kt
PR addressing [CORDA-1497](https://r3-cev.atlassian.net/browse/CORDA-1497).
When the transform annotations for an enum included both renaming and defaulting of enum constants, the validation was failing if we wanted to rename a defaulted constant.
```kotlin
@CordaSerializationTransformEnumDefaults(
CordaSerializationTransformEnumDefault(old = "C", new = "D"),
CordaSerializationTransformEnumDefault(old = "D", new = "E")
)
@CordaSerializationTransformRename(to = "BOB", from = "E")
enum class MultiOperations { A, B, C, D, BOB }
```
In this PR, we clean up the handling of enum transforms a bit, eliminating the transforms cache from `LocalSerializerFactory` and storing transforms directly in `LocalTypeInformation.AnEnum`, and move validation into the `EnumTransforms` class where it is easier …
=> CORDA-1497 enum evolution

serialization/src/main/kotlin/net/corda/serialization/internal/model/EnumTransforms.kt, serialization/src/test/kotlin/net/corda/serialization/internal/amqp/EnumTransformationTests.kt
Reviewing the [previous PR](https://github.com/corda/corda/pull/4343) for [CORDA-1497](https://r3-cev.atlassian.net/projects/CORDA/issues/CORDA-1497), I noticed that I'd accidentally removed a couple of validation rules (they weren't tested, so it didn't break anything, but it's still good to have them). This PR restores those rules, together with tests.
=> CORDA-1497 replace missing validation

testing/test-utils/src/main/kotlin/net/corda/testing/core/internal/ContractJarTestUtils.kt
Or else tests:
AttachmentsClassLoaderTests.Test valid overlapping contract jar
ConstraintsPropagationTests.Happy path for Hash to Signature Constraint migration
are failing.
=> CORDA-2157: Fix Windows build

core/src/main/kotlin/net/corda/core/internal/notary/NotaryServiceFlow.kt
(or might be due to wrong order of merging dependent PRs).
=> ENT-2666 remove dangling method left from prior PR harmless conflict resolution mistake.

node-api/src/main/kotlin/net/corda/nodeapi/internal/ContractsScanning.kt
Or else the file remains open and test `VaultQueryJavaTests.testAttachmentQueryCriteria` fails on Windows as open for reading files cannot be deleted.
=> CORDA-2157: Close `inputStream` properly in withContractsInJar

docs/source/changelog.rst, node/src/main/kotlin/net/corda/node/services/vault/HibernateQueryCriteriaParser.kt, node/src/test/kotlin/net/corda/node/services/vault/VaultQueryTests.kt
https://r3-cev.atlassian.net/browse/CORDA-2247
Notes:
1. Fixed a problem that was preventing Hibernate from generating left joins instead of cross joins.
2. Added an additional sort column on `stateRef` to avoid unstable sorts on fields with possible duplicate values. This is added only if no sort columns are based on `stateRef` already.
=> [CORDA-2247]: Fixed a bug causing Hibernate to produce cross joins.

core/src/main/kotlin/net/corda/core/serialization/MissingAttachmentsException.kt, core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt, docs/source/changelog.rst
https://r3-cev.atlassian.net/browse/CORDA-2294
=> [CORDA-2294]: Improved exception thrown by AttachmentsClassLoader when attachment uploader is not trusted.

.ci/api-current.txt, testing/node-driver/src/main/kotlin/net/corda/testing/node/NodeTestUtils.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/MockNetworkParametersStorage.kt, testing/test-utils/src/main/kotlin/net/corda/testing/core/SerializationEnvironmentRule.kt, testing/test-utils/src/main/kotlin/net/corda/testing/internal/InternalSerializationTestHelpers.kt, testing/test-utils/src/main/kotlin/net/corda/testing/internal/InternalTestUtils.kt
It exposed the internal SerializationEnvironment class. It previously documented that the SerializationEnvironmentRule JUnit rule should be used instead, and so any existing test code have a migration path.
=> CORDA-2128: Removed SerializationEnvironmentRule.run

.ci/api-current.txt, testing/node-driver/src/main/kotlin/net/corda/testing/node/MockServices.kt
While technically a break in the test API, it has no practical implications as InMemoryIdentityService does not provide any extra APIs.
=> CORDA-2128: makeTestIdentityService no longer declared to return internal InMemoryIdentityService

serialization/src/main/kotlin/net/corda/serialization/internal/amqp/AMQPTypeIdentifiers.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/CustomSerializer.kt, serialization/src/main/kotlin/net/corda/serialization/internal/model/LocalTypeInformationBuilder.kt, serialization/src/test/kotlin/net/corda/serialization/internal/amqp/AMQPRemoteTypeModelTests.kt, serialization/src/test/kotlin/net/corda/serialization/internal/amqp/AMQPTypeIdentifierParserTests.kt
Although it doesn't make much difference in practice, v3's AMQP type notation for `List<*>` is `List<java.lang.Object>` while v4's is `List<?>`. I noticed the mismatch while investigating [CORDA-2227](https://r3-cev.atlassian.net/browse/CORDA-2227); although this PR isn't needed to resolve that issue, it eliminates a red herring that held me up while trying to find the cause.
Another irritation I noticed in passing is that `java.lang.String` is treated as `LocalTypeInformation.Opaque` rather than `LocalTypeInformation.Atomic`, which makes the `toString` unnecessarily long and difficult to read (since it includes full `NonComposable` information for `java.lang.String`). That is also fixed here.
=> CORDA-2227 Change ? to java.lang.Object in type notation for Any

serialization/src/main/kotlin/net/corda/serialization/internal/amqp/AMQPTypeIdentifiers.kt, serialization/src/test/kotlin/net/corda/serialization/internal/amqp/AMQPRemoteTypeModelTests.kt, serialization/src/test/kotlin/net/corda/serialization/internal/amqp/AMQPTypeIdentifierParserTests.kt
If a type parameter is `*`, we should write it as `java.lang.Object`, so that Corda V3 can interpret it correctly.
=> CORDA-2227 Emit java.lang.Object, not *, in TypeNotation

samples/simm-valuation-demo/build.gradle, samples/simm-valuation-demo/contracts-states/build.gradle, samples/simm-valuation-demo/flows/build.gradle
The build process of demo creates new version fo Cordapp JAR in post 'jar' task.
So far JAR signing was integral part of jar task, now it's also available as a separate task `signJar` (gradle-plugins PR https://github.com/corda/corda-gradle-plugins/pull/130).
Using `signJar` to re-sign Cordapp shrink JAR, fat JAR is also signed.
=> CORDA-1915 Simm Valuation demo update for JAR signing

core/src/main/kotlin/net/corda/core/internal/Emoji.kt, tools/shell/src/main/kotlin/net/corda/tools/shell/utlities/ANSIProgressRenderer.kt, tools/shell/src/test/kotlin/net/corda/tools/shell/utilities/ANSIProgressRendererTest.kt
I adjusted the rendering for flow stages that have been skipped, so that user is not misled into thinking they failed (by the X symbol). 
Notes:
* I initially went for strikethrough, but realised it's not working for most terminals, so went for the faint effect. Also, could not find a more appropriate symbol, so used the ballot box check. Open to suggestions.
* I took the liberty of removing the `treeIndex == tree.lastIndex` condition, since I believe it's dead code and I think it's also confusing. The reason is it's comparing the index of the steps in progress with the `tree.lastIndex`, which corresponds to the number of times the structure of the progress tracker has changed. I run a few more tests, as shown below to make sure this does not introduce regressions. Let me know if I am …
=> [CORDA-1676] Adjust progress tracking rendering for skipped elements

node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/SchemaMigration.kt
`Finance CorDapp` `v3.0` doesn't have Liquibase migration script, as `Corda OS 3.0` doesn't use Liquibase.
`Corda OS 4.0` supports Liquibase, but needs to allow run the older `Finance Cordapp v3.0` which doesn't have Liquibase Script.
Run Liquibase setup for schemas of Finance App only if they are present in the Cordapp (so when `FinanceApp v4 is used). 
Tested - trader demo run entirely on `v3` (node/cordpapps), then corda.jar `v4` was dropped and the demo restored - all works, (Liquibase created for core tables), then stopped and dropped new finance jar,  Liquibase for Finance schema created.
=> CORDA-2291 enable Finance App 3.x on Corda 4.x

docs/source/key-concepts.rst
I am reading through the key-concepts in V3.3 of your docs [here](https://docs.corda.net/key-concepts.html) and I think that transactions should appear before contracts. Especially since the video for transactions is labeled Key Concepts 3 and the video for contracts as Key Concepts 4.
“I hereby certify that my contribution is in accordance with the Developer Certificate of Origin (https://developercertificate.org/).”
=> In docs:key-concepts, transactions should come before contracts

node/src/main/kotlin/net/corda/node/services/keys/BasicHSMKeyManagementService.kt, node/src/main/kotlin/net/corda/node/services/keys/PersistentKeyManagementService.kt, node/src/main/kotlin/net/corda/node/services/schema/NodeSchemaService.kt, node/src/test/kotlin/net/corda/node/services/vault/ExternalIdMappingTest.kt
There was a parallel work done on `PersistentKeyManagementService` (added new table) while this service has been superseded by `BasicHSMKeyManagementService`.
Move this change for the former class to the later one and did some minor cleanup. 
The general question `PersistentKeyManagementService` is not used anymore, should in  introduction https://github.com/corda/corda/pull/4099, or is there a reason to keep it?
There are still some references to `PersistentKeyManagementService` in docs.
=> CORDA-2262 Align ID -> pubKey mapping between BasicHSMKeyManagementService and PersistentKeyManagementService

build.gradle
Disable the .NET assembly scan because it is not required and is causing builds to fail when the build server does not have mono installed
Also bumping owasp scanner version to 4.0.0
=> CORDA-2322 disable owasp .NET assembly scan

serialization/src/main/kotlin/net/corda/serialization/internal/model/TypeIdentifier.kt, serialization/src/test/kotlin/net/corda/serialization/internal/amqp/RoundTripTests.kt
When resolving a parameterised type against another type which may hold information about its type variables, we need to take wildcard type parameters to their upper bounds recursively (i.e. converting `Foo<? extends Bar<? extends Baz>>` to `Foo<Bar<Baz>>`, otherwise nested generics will not be handled correctly.
The reason we need to do this in v4, and didn't in v3, is that in v3 the order of traversal of types when constructing a serialiser was different, and things got resolved naturally along the way. Now that we traverse the entire graph of related types up-front via the `LocalTypeInformationBuilder`, we need to fix up type parameters at each stage before proceeding further into the graph traversal.
As all of this is cached, the performance impact should be minimal.
This PR addresses …
=> CORDA-2318 resolve nested type params

docs/source/changelog.rst, docs/source/corda-configuration-file.rst, node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/CordaPersistence.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/HibernateConfiguration.kt, node/src/main/kotlin/net/corda/node/services/config/NodeConfigurationImpl.kt, node/src/main/kotlin/net/corda/node/services/config/schema/v1/ConfigSections.kt
New property database.initialiseAppSchema is introduced that allows to turn-off Hibernate DDL generation while leaving Node-specific Liquibase handling enabled.
=> initialiseSchema property couples corda node and cordapp

node/src/main/kotlin/net/corda/node/services/statemachine/StaffedFlowHospital.kt
If flows get retried for DB deadlocks, add exponential back off to avoid the retries increasing the DB deadlock probability.
=> CORDA-2306 backoff on flow retries

serialization/src/main/kotlin/net/corda/serialization/internal/model/TypeIdentifier.kt, serialization/src/test/kotlin/net/corda/serialization/internal/amqp/RoundTripTests.kt
Following [CORDA-2318](https://r3-cev.atlassian.net/browse/CORDA-2318), I did some investigatory poking around with generics to see if it could be broken in any other way. It turned out that it could:
```kotlin
interface I<T> {
val t: T
}
data class C<A, B : A>(override val t: B) : I<B>
```
If we try to serialize an erased instance of `C`, the type parameter `B` is resolved to `A` rather than `*`, and serialisation fails. We need to resolve from `A` to `*` after going from `B` to `A`.
This PR introduces a test for this edge case, and code to make it pass.
=> CORDA-2318 resolve type variables recursively

docs/source/node-administration.rst, docs/source/tutorial-cordapp.rst
Make log4j2 consistence - to make docs search easier (log4j 2) wasn't
catch by 'log4j2' search.
This is trivial docs change. Currently docs search won't return pages where there was a space between  'log4j' and '2'. I've changed it to make wider search results.
=> Trival change to improve search hits for log4j2

node/src/main/kotlin/net/corda/node/internal/subcommands/InitialRegistrationCli.kt
The node should exit with an error when the initial registration fails.
=> Remove safe cast at initial registration attempt

docs/source/corda-configuration-file.rst
I was sure I documented this originally, but it seems to have been cut out somewhere along the line.
=> CORDA-970: Document the messagingServerExternal property on the OS node.

docs/source/corda-configuration-file.rst, docs/source/deploying-a-node.rst, docs/source/running-a-node.rst
Document the ways and behaviours of setting JVM args on a corda node process.
=> CORDA-2301 JVM args documentation

core/src/main/kotlin/net/corda/core/flows/NotaryFlow.kt, core/src/main/kotlin/net/corda/core/internal/IdempotentFlow.kt, docs/source/changelog.rst, docs/source/corda-configuration-file.rst, node/src/main/kotlin/net/corda/node/services/statemachine/Event.kt, node/src/main/kotlin/net/corda/node/services/statemachine/FlowStateMachineImpl.kt, node/src/main/kotlin/net/corda/node/services/statemachine/FlowTimeoutException.kt, node/src/main/kotlin/net/corda/node/services/statemachine/SingleThreadedStateMachineManager.kt, node/src/main/kotlin/net/corda/node/services/statemachine/StaffedFlowHospital.kt, node/src/main/kotlin/net/corda/node/services/statemachine/StateMachineState.kt, node/src/main/kotlin/net/corda/node/services/statemachine/SubFlow.kt, node/src/main/kotlin/net/corda/node/services/statemachine/transitions/TopLevelTransition.kt, node/src/main/kotlin/net/corda/node/utilities/TimedFlowUtils.kt, node/src/test/kotlin/net/corda/node/services/TimedFlowTests.kt, node/src/test/kotlin/net/corda/node/services/persistence/DBCheckpointStorageTests.kt, node/src/test/kotlin/net/corda/node/services/statemachine/IdempotentFlowTests.kt
Timed flows would give up after a configurable number of tries. However, this can cause problems when a node gives up on a notarisation, as the notary might receive the request and mark states as spent, but the answer doesn't come back, so the node gives up and releases the states as unspent. Now the node and the notary don't agree any longer on the state of the world, and future flows trying to use these states will error.
A node therefore should never give up on trying to notarise a transaction.
Also, if the notary is a single node notary, don't even retry a notarisation - if the node comes back up, the message will eventually go through (or if the node gets restarted, it will be resent), but there is no alternative node that could answer any quicker.
=> CORDA-2304 Never give up on notarisations

docs/source/api-contract-constraints.rst, docs/source/api-identity.rst, docs/source/api-states.rst, docs/source/building-a-cordapp-index.rst, docs/source/corda-networks-index.rst, docs/source/index.rst, docs/source/upgrade-notes.rst, docs/source/upgrading-cordapps.rst, docs/source/versioning.rst
* Adds some more information on target/min platform versioning (prior info was only the design doc)
* Add a missing design doc to the toctree
* Move the versioning page to the API section
* Add more info to the upgrade notes
* Delete old upgrade notes that are no longer relevant
=> Docs: improve upgrade notes and versioning page

core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
https://r3-cev.atlassian.net/browse/CORDA-2341
This might break the API. If that's the case, we can decide not to release these overloaded constructors, or to add them back manually.
=> [CORDA-2341]: Fixing ABI compatibility for TransactionBuilder vs Corda 3.3.

node-api/src/main/kotlin/net/corda/nodeapi/internal/ArtemisTcpTransport.kt
Connections from load balancers and other health checks can last for a long time without sending any bytes. This logs messages like:
[ERROR] 2018-12-18T11:00:05,509Z [Thread-4 (ActiveMQ-scheduled-threads)] core.server.lambda$channelActive$0 - AMQ224088: Timeout (10 seconds) while handshaking has occurred.
that fill the logs up and make monitoring of errors difficult.
This change suppresses this artemis logic, although the normal TLS timers will still apply, but silently. The RPC plan socket will allow an indefinite connection without disconnect, but that should be fine with a load balancer and the complexity of adding yet more confusing config is not worth it.
=> ENT-2589: Suppress core.server.lambda$channelActive$0 - AMQ224088 errors

serialization/src/main/kotlin/net/corda/serialization/internal/amqp/PropertyDescriptor.kt, serialization/src/test/java/net/corda/serialization/internal/amqp/SetterConstructorTests.java
Correcting a regression introduced by serialisation code refactoring, we relax the rule that "setter" methods must have a void return method, so that serialisation will continue to work with Java frameworks such as Lombok which generate setter methods with non-void returns for method-chaining purposes. See [CORDA-2352](https://r3-cev.atlassian.net/browse/CORDA-2352).
=> CORDA-2352 Be more lenient with setter property signature validation

samples/irs-demo/README.md, samples/irs-demo/cordapp/build.gradle, samples/irs-demo/web/build.gradle, samples/irs-demo/web/src/main/resources/log4j2.xml, testing/test-common/build.gradle, tools/cliutils/build.gradle
The irs-demo is throwing an error on startup because it has a log4j.xml which uses a custom plugin which is in cli utils. However, it turns out the log4j2.xml is in the classpath because the irs-demo webapp is depending on the test utils, as well as the full corda jar. I have reworked the dependencies so that these are test only and added it's own log4j2.xml file, along with the spring boot log4j2 plugin. 
Additionally, `test-utils` needs to depend on `cli-utils` anyway, which I've changed.
=> Fix irs-demo dependency issues

.ci/api-current.txt, core/src/main/kotlin/net/corda/core/schemas/PersistentTypes.kt, node/src/main/kotlin/net/corda/node/services/vault/HibernateQueryCriteriaParser.kt, node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt, node/src/main/kotlin/net/corda/node/services/vault/VaultSchema.kt, node/src/main/resources/migration/vault-schema.changelog-v8.xml
The generated IDs slow things down, and shouldn't be necessary.  There's a natural primary key.
=> ENT-2848 remove need for generated IDs on some frequently used tables

core/src/test/kotlin/net/corda/core/internal/InternalUtilsTest.kt, docs/source/changelog.rst, finance/workflows/src/test/kotlin/net/corda/finance/flows/CashPaymentFlowTests.kt, node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt
This change removes a race condition between `trackBy` and `notifyAll`, which could lead to states missing from both the snapshot and the observable, included in the returned `DataFeed` from `trackBy`.  For more details, check the JIRA ticket, it has extremely elaborate explanation.
Notes:
- I also added a missing test for `bufferUntilSubscribed`
- There was a test in `CashFlowPaymentTest`, executing both `trackBy` and `notifyAll` in a single transaction. I unwrapped the test from this transaction, since as discussed `trackBy` should not be invoked with an open transaction to avoid race conditions and thus I think it's better to demonstrate good practices in the tests, as well.
- To simulate the race condition, I've instrumented a test, triggering the expected race condition (documented …
=> CORDA-1839 - Remove race condition between trackBy and notifyAll

core/src/main/kotlin/net/corda/core/flows/NotaryError.kt
The introduction of a non-null property requires the use of DeprecatedConstructorForDeserialization.
=> StateConsumptionDetails fixed to handle evolution properly

confidential-identities/src/test/kotlin/net/corda/confidential/SwapIdentitiesFlowTests.kt, core/src/test/kotlin/net/corda/core/transactions/ReferenceInputStateTests.kt, finance/contracts/src/test/kotlin/net/corda/finance/contracts/asset/CashTests.kt, node-api/src/test/kotlin/net/corda/nodeapi/internal/crypto/AliasPrivateKeyTest.kt, node/src/integration-test/kotlin/net/corda/node/amqp/CertificateRevocationListNodeTests.kt, node/src/test/kotlin/net/corda/node/services/persistence/NodeAttachmentServiceTest.kt
The overload that takes in a String does NOT check that the exception thrown has that message, which is what these tests are assuming. Rather it's the assertion message when the test fails.
=> Fixed incorrect usages of assertFailsWith

docs/source/node-explorer.rst
This PR adds a note to the Node Explorer documentation setting out the requirement that all CorDapps on a node must be available to the Node Explorer in order for it to run. These are made available by putting them in a cordapps directory within the directory from which the Node Explorer is run. Note that the finance CorDapp is always available.
Failing to do this leads to the exceptions seen in [CORDA-1992](https://r3-cev.atlassian.net/browse/CORDA-1992) when the Node Explorer connects.
=> [CORDA-1992] Better document requirements for Node Explorer

docs/source/tutorial-contract.rst
Fix for a small typo in the contract tutorial docs.
=> Fix typo in contract tutorial

.ci/api-current.txt, docs/source/changelog.rst, testing/node-driver/src/main/kotlin/net/corda/testing/node/MockNetwork.kt, testing/node-driver/src/test/java/net/corda/testing/node/TestResponseFlowInIsolationInJava.java, testing/node-driver/src/test/kotlin/net/corda/testing/node/internal/TestResponseFlowInIsolation.kt
The ResponderFlowFactory parameter is not used and so removed. Also, instead of returning a Future it returns an Observable of responder flows, to support multiple invocations.
=> CORDA-1942: StartedMockNode.registerResponderFlow simplified

core/src/main/kotlin/net/corda/core/flows/WithReferencedStatesFlow.kt, core/src/test/kotlin/net/corda/core/flows/WithReferencedStatesFlowTests.kt
* Internal classe were being exposed and have been hidden
* The single `flowLogic` instance has been changed into a lambda producer. Flows may not be written to be executed twice, especially if they hold internal state.
* Added JVM c'tor overloads
=> CORDA-1942: Improvements to the WithReferencedStatesFlow API

docs/source/node-database.rst
Added a new-line before the beginning of the list, because otherwise markdown is not recognised as list, leading to a broken format.
=> Fix docs formatting for node-database

client/jackson/src/test/kotlin/net/corda/client/jackson/JacksonSupportTest.kt, core/src/main/kotlin/net/corda/core/flows/NotaryChangeFlow.kt, core/src/main/kotlin/net/corda/core/flows/NotaryFlow.kt, core/src/main/kotlin/net/corda/core/internal/ContractUpgradeUtils.kt, core/src/main/kotlin/net/corda/core/internal/NetworkParametersServiceInternal.kt, core/src/main/kotlin/net/corda/core/internal/TransactionUtils.kt, core/src/main/kotlin/net/corda/core/node/ServiceHub.kt, core/src/main/kotlin/net/corda/core/node/services/NetworkParametersService.kt, core/src/main/kotlin/net/corda/core/transactions/ContractUpgradeTransactions.kt, core/src/main/kotlin/net/corda/core/transactions/NotaryChangeTransactions.kt, core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt, core/src/main/kotlin/net/corda/core/transactions/WireTransaction.kt, core/src/test/kotlin/net/corda/core/transactions/TransactionBuilderTest.kt, node-api/src/test/kotlin/net/corda/nodeapi/internal/AttachmentsClassLoaderStaticContractTests.kt, node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt, node/src/main/kotlin/net/corda/node/internal/DBNetworkParametersStorage.kt, node/src/main/kotlin/net/corda/node/internal/ServicesForResolutionImpl.kt, node/src/main/kotlin/net/corda/node/services/network/NetworkMapUpdater.kt, node/src/main/kotlin/net/corda/node/services/transactions/NonValidatingNotaryFlow.kt, node/src/test/kotlin/net/corda/node/services/network/DBNetworkParametersStorageTest.kt, node/src/test/kotlin/net/corda/node/services/network/NetworkMapUpdaterTest.kt, node/src/test/kotlin/net/corda/node/services/persistence/HibernateColumnConverterTests.kt, node/src/test/kotlin/net/corda/node/services/transactions/NotaryServiceTests.kt, node/src/test/kotlin/net/corda/node/services/transactions/NotaryWhitelistTests.kt, node/src/test/kotlin/net/corda/node/services/vault/NodeVaultServiceTest.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/MockServices.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/NodeTestUtils.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/InternalMockNetwork.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/MockNetworkParametersService.kt
As a public API it's not a true storage - CorDapps can't add network parameters.
=> CORDA-1942: Renamed NetworkParametersStorage to NetworkParametersService to match its public usage

docs/source/api-persistence.rst
In working with the persistence API docs, I found some discrepancies which have been updated/fixed in this PR (some spelling/grammar issues were also addressed).
Major changes:
- Marking the JPA Support as being available in Corda 4+. The section discusses the withEntityManager method which isn't available in the current Corda version.
- Rewrote the Custom Schema Registration section which referenced the deprecated plugins folder.
- Rewrote the section describing the behaviour of the schemaService.
- Added a section describing how to persist hierarchical data using JPA annotations.
- Spelling / grammar clean up. Rewrote some sections for readability.
- Attempted to standardize formatting.
@amoothart 
@joeldudleyr3 
- [ …
=> Persistence API - Updates

core/src/main/kotlin/net/corda/core/utilities/Try.kt, node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt, node/src/main/kotlin/net/corda/node/internal/subcommands/InitialRegistrationCli.kt
Apps may depend on the previous behaviour of catching Throwable rather than just Exception. Better to not risk this break and instead provide a helper to throw Errors.
Also using Consumer to avoid ugly usage in Java for doOnSuccess and doOnFailure.
=> CORDA-2391: Revert behaviour of Try.on to V3

docs/source/api-transactions.rst
Bug: Fixed some dodgy formatting in the `api-transactions.rst` file whereby some of the code samples were not displaying correctly.
=> CORDA-2386 Fix for formatting of the reference states part of api-transaction.rst

core/src/main/kotlin/net/corda/core/node/ServiceHub.kt
As requested in https://github.com/corda/corda/issues/4498 I created a pull request with the new description
=> CORDA-4498 - Incorrect description of `ServiceHub.jdbcSession`

.ci/check-api-changes.sh
This change is related to: https://github.com/corda/corda-gradle-plugins/pull/150
It excludes `jvm.kotlin.internal` from the internal classes that are scanned in the API compatibility checks.
- Run the API compatibility tests (`./gradlew generateApi && .ci/check-api-changes.sh`) and verified no new changes, as expected
- Additional tests have been done in the linked PR
=> CORDA-2349 - Exclude kotlin.jvm.internal from api scanning

node/src/integration-test/kotlin/net/corda/node/AddressBindingFailureTests.kt, node/src/main/kotlin/net/corda/node/internal/Node.kt
The current IP autodetect can trigger with any 192.168.x.x address, or 10.x.x.x address even if the user has intentionally set it. Users also sometimes setup 0.0.0.0 in the p2pAddress field.
This change makes the autodetect only apply to localhost:<port> addresses and prints a clear message to say how to disable the lookup if desired.
=> Reduce the operation of ip autodetect to nodes specifying localhost

node/src/main/kotlin/net/corda/node/services/identity/PersistentIdentityService.kt, node/src/main/kotlin/net/corda/node/services/keys/BasicHSMKeyManagementService.kt, node/src/main/kotlin/net/corda/node/services/keys/PersistentKeyManagementService.kt, node/src/main/kotlin/net/corda/node/utilities/AppendOnlyPersistentMap.kt, node/src/test/kotlin/net/corda/node/services/identity/PersistentIdentityServiceTests.kt, node/src/test/kotlin/net/corda/node/services/persistence/AppendOnlyPersistentMapTest.kt
All the affected code is in OS.
This fixes the original problem identified in the JIRA.  During testing, this was shown not to help because access is distributed across the identity and key service caches.  Focussing access on the identity cache results in better hit rates and greater performance.
=> ENT-2924 Fix performance of identity checking.

node-api/src/main/kotlin/net/corda/nodeapi/internal/KeyStoreConfigHelpers.kt, node/src/integration-test/kotlin/net/corda/node/utilities/registration/NodeRegistrationTest.kt, testing/test-utils/src/main/kotlin/net/corda/testing/core/internal/JarSignatureTestUtils.kt
Add the DEV Code Signing key to the node fingerprint blacklist such that a Node cannot use artifacts signed by this key in a production environment (eg. devMode = false).
=> CORDA-2395 Add cordapp code signing dev key to production blacklist.

.idea/compiler.xml, node/src/integration-test/kotlin/net/corda/node/flows/FlowRetryTest.kt
Use FlowTimeOut exception rather than SQL deadlock in unit tests to avoid hitting the exponential back-off.
=> ENT-2930 Speed up FlowRetryTests again

core/src/main/kotlin/net/corda/core/contracts/Structures.kt, finance/contracts/src/main/kotlin/net/corda/finance/contracts/asset/Obligation.kt
https://r3-cev.atlassian.net/browse/CORDA-2388
`CommandWithParties.signingParties` should not be used in contract verification code as it is non-deterministic.
Replaced one remaining usage of ``signingParties`` with ``signers`` in Obligation following other examples (e.g. around https://github.com/corda/corda/blob/4aaefb4fe9dcb3eb2fe55f0fb7cf2b3216cd8f31/finance/contracts/src/main/kotlin/net/corda/finance/contracts/asset/Cash.kt#L197).
No other contracts use ``signingParties`` in their logic.
=> CORDA-2388 Deprecate `CommandWithParties.signingParties`

docs/source/changelog.rst, docs/source/corda-api.rst, docs/source/release-notes.rst, samples/bank-of-corda-demo/build.gradle, samples/trader-demo/build.gradle
Also, updated the trader and BoC demos to include confidential-identities jar.
=> Updated docs on the need to load confidential-identities CorDapp separately

constants.properties, docs/source/app-upgrade-notes.rst, docs/source/generating-a-node.rst
Includes following changes:
* `cordformation`: deployNodes does not attempt to sign any JARs unless explicitly configured to do so using `signing.enabled = true`
* `cordapp`: enforce CorDapp `workflow` and `contract` version identifier metadata to be an integer.
* `cordapp`: relax cordapp metadata checking (warn on missing metadata rather than failing-fast).
This allows multi-module structured CorDapps to only define metadata for flows and/or contracts modules.
=> Update Corda gradle plugins to 4.0.38

core/src/main/kotlin/net/corda/core/internal/StatePointerSearch.kt, core/src/test/kotlin/net/corda/core/internal/StatePointerSearchTests.kt, node/src/test/kotlin/net/corda/node/services/transactions/ResolveStatePointersTest.kt
This fixes some of the bugs in state pointer search, see JIRA: https://r3-cev.atlassian.net/browse/CORDA-2426
Pointers are now searched for inside iterables and maps but this fix still doesn't search for state pointers inside computed properties.
This code will just be used temporarily until Dominic has split all the basic type model stuff from serialisation to core but that won't happen until next week.
=> CORDA-2426 Fixed bug in state pointer search.

docs/source/api-contract-constraints.rst, node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/AttachmentVersionMigration.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/AttachmentVersionNumberMigration.kt, node/src/main/kotlin/net/corda/node/services/persistence/NodeAttachmentService.kt, node/src/main/resources/migration/node-core.changelog-master.xml, node/src/main/resources/migration/node-core.changelog-v11.xml, node/src/test/java/net/corda/node/services/vault/VaultQueryJavaTests.java, node/src/test/kotlin/net/corda/node/services/persistence/NodeAttachmentServiceTest.kt, testing/test-common/src/main/kotlin/net/corda/testing/common/internal/ParametersUtilities.kt
The version of contract attachments that are whitelisted should be read from NetworkParameters.whitelistedContractImplementations
It use the lattes network map from db (the highest epoch) and not the "current" map form the file.
=> CORDA-2405 Update versions of whitelisted attachments 

core/src/main/kotlin/net/corda/core/internal/PathUtils.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/TestCordappImpl.kt
The gradle process that runs the tests keeps an exclusive hold on built jars in Windows, which means if a test wants to get hold of the CorDapp, and it's requested from the same module, it will fail. Now instead of deleting the "libs" dir we just use the latest created jar.
=> CORDA-2418: Fixed inability to use TestCordapp under gradle in Windows if referring to self cordapp

node-api/src/main/kotlin/net/corda/nodeapi/internal/bridging/AMQPBridgeManager.kt
so that we don't have to wait for an ack flush or end up with ack'd messages queued up.
=> CORDA-2209 Make the AMQP bridge individually ACK artemis messages

docs/source/contributing-philosophy.rst, docs/source/contributing.rst, docs/source/index.rst
The contributing section of the docs is buried currently. It also wasn't clear from the section about finding an area to contribute that you could just reach out to a maintainer.
=> Moves Contrib and Network sections up in index. Makes requesting a contribution more prominent.

core/src/main/kotlin/net/corda/core/internal/ClassLoadingUtils.kt, samples/attachment-demo/src/integration-test/kotlin/net/corda/attachmentdemo/AttachmentDemoTest.kt, samples/irs-demo/cordapp/src/main/kotlin/net/corda/irs/flows/FixingFlow.kt, samples/simm-valuation-demo/src/integration-test/kotlin/net/corda/vega/SimmValuationTest.kt, samples/trader-demo/src/integration-test/kotlin/net/corda/traderdemo/TraderDemoTest.kt, webserver/src/integration-test/kotlin/net/corda/webserver/WebserverDriverTests.kt
This change switches from enabling all info to only class info during class loading to reduce the memory footprint. 
I also switched all the affected tests back to their previous defaults and run them locally, they all passed.
=> [CORDA-2431] - Reduce memory footprint of classpath scanning

client/rpc/src/main/kotlin/net/corda/client/rpc/CordaRPCClient.kt, core-deterministic/testing/src/test/kotlin/net/corda/core/internal/ClassLoadingUtils.kt, core/src/main/kotlin/net/corda/core/internal/ClassLoadingUtils.kt, core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt, core/src/test/kotlin/net/corda/core/internal/ClassLoadingUtilsTest.kt, node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt, node/src/main/kotlin/net/corda/node/internal/rpc/proxies/ThreadContextAdjustingRpcOpsProxy.kt, node/src/test/kotlin/net/corda/node/internal/rpc/proxies/ThreadContextAdjustingRpcOpsProxyTest.kt, samples/simm-valuation-demo/contracts-states/src/main/kotlin/net/corda/vega/plugin/customserializers/CurrencySerializer.kt
This addresses the remaining comments from https://github.com/corda/corda/pull/4551, which was merged to expedite RC testing. It's mainly refactorings + a fix of a Kotlin-only ABI breakage.
For the API breakage, I run `./gradlew generateApi`, using the enhanced version of api-scanner, making sure that the breakage was reported and removed after the fix.
=> [CORDA-2431] - Small refactorings following-up on PR-4551

tools/shell/src/main/kotlin/net/corda/tools/shell/utlities/ANSIProgressRenderer.kt
The StdoutANSIProgressRenderer uses a bit of a hack to ensure the progress tracker information is printed at the bottom of the console - it looks for the console appender in the current log4j configuration and swaps this out for its own. To do this it looks for the name of this appender in the log4j config. This was changed in a previous fix ([CORDA-1897](https://r3-cev.atlassian.net/browse/CORDA-1897)), but the corresponding name the renderer was looking up was not changed.
This fix has been tested manually, by deploying the Bank of Corda demo and running a CashIssueFlow.
Changes:
- Update the name of the appender the renderer looks for to swap out
- Remove two superfluous return types the compiler was warning about
=> [CORDA-2441] Fix Stdout progress renderer to swap out correct appender

docs/source/versioning.rst
Fix incorrect spelling of "licence" in sample config snippet.
=> CORDA-2447 - Typo in versioning docsite code example (license vs licence)

constants.properties, testing/node-driver/build.gradle
* Bump gradle-plugins to 4.0.39 to enable synthetic methods in API scanning (I've already published it)
* Disable non-effective constructors that are synthesized by Kotlin
```
$ ./gradlew generateApi && .ci/check-api-changes.sh
Number of API removals/changes:  0
Number of new internal class exposures:  0
Number of new abstract APIs:  0
Exiting with exit code 0
```
=> Enable methods synthesized by Kotlin in api scanning

node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/AttachmentVersionNumberMigration.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/SchemaMigration.kt, node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
Upgrade from node 3.0 to 4.0 fails to create versions of whitelisted JARs from networkParameters - read parameters from file at first as in Corda 3.0 there no relevant table, then try from the table.
Tested using https://r3-cev.atlassian.net/browse/R3T-1549
As this is migration, the code will run only once on each node, she increased log level to info for messages.
=> CORDA-2450 Creating attachment version from whitelisted JARs fails for node upgrade

samples/simm-valuation-demo/src/integration-test/kotlin/net/corda/vega/SimmValuationTest.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/DriverDSLImpl.kt
This brings the SIMM valuation integ test in line with the manual run, so that it's not masking serialization issues, as was the case now.
I switched the custom serializers of the context to a hard-coded empty set & verified that:
* the manual run was failing, while the integ test passed (before the fix)
* both were failing (after the fix)
=> Remove dependencies from classpath in SIMM valuation integ test

constants.properties, testing/node-driver/build.gradle
This change enables reporting of methods synthesized by Kotlin, so that Kotlin-only ABI breakages are prevented.
The reason to backport this to the RC is so that we can have a point-in-time, where we know that any subsequent fix introduced in the RC does not cause any such breakage (since things can slip under the current version of api-scanning) & use this point to compare with 3.0 version, ensuring we eliminated all the breakages that were introduced (without being reported) during this period.
Link to original PR in master: https://github.com/corda/corda/pull/4595
=> [CORDA-2349] - Upgrade API scanner to include Kotlin-synthesized mehtods

serialization/src/test/kotlin/net/corda/serialization/internal/amqp/AbstractAMQPSerializationSchemeTest.kt
This removes the `SerializationEnvironmentRule` from the amqp test, since this only needs a serializatio factory and that rule does some other preparations, as well.
=> Remove unneeded SerializationEnvironmentRule from amqp test

node/src/main/kotlin/net/corda/node/NodeCmdLineOptions.kt
The new `InitialRegistrationCmdLineOptions` was throwing an error if `devMode=true` and `networkServices` or `compatibilityZoneURL` was set, however, it should also accept those parameters if `devMode=true` AND `devModeOptions.allowCompatibilityZone=true`
=> Fix issue with devModeOptions.allowCompatabilityZone not working

core/src/main/kotlin/net/corda/core/crypto/Crypto.kt, core/src/main/kotlin/net/corda/core/crypto/SignatureScheme.kt, core/src/main/kotlin/net/corda/core/internal/ConstraintsUtils.kt, serialization/src/main/kotlin/net/corda/serialization/internal/model/TypeIdentifier.kt
All code is in OS.  Each has a global mutex.
Stop repeated look up of KeyFactory.
Stop repeatedly asking for system class loader.
Replace ClassLoader.loadClass with Class.forName.
=> ENT-2967 Fix up use of various JDK performance contention points

core/src/main/kotlin/net/corda/core/node/services/AttachmentStorage.kt, core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt, core/src/test/kotlin/net/corda/core/transactions/TransactionBuilderTest.kt, node-api/src/test/kotlin/net/corda/nodeapi/internal/AttachmentsClassLoaderStaticContractTests.kt, node/src/main/kotlin/net/corda/node/services/persistence/NodeAttachmentService.kt, node/src/test/kotlin/net/corda/node/services/persistence/NodeAttachmentServiceTest.kt, testing/test-utils/src/main/kotlin/net/corda/testing/services/MockAttachmentStorage.kt
when querying for signed/unsigned jars by contract class and version.
Addresses CORDA-2475 bug with title:
"Cannot build transaction having  two unsigned, not whitelisted and trusted JARs for the same contract."
=> CORDA-2475 Adjust attachments query logic to return correct results 

docs/source/app-upgrade-notes.rst, docs/source/release-notes.rst, node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt, node/src/main/kotlin/net/corda/node/services/api/VaultServiceInternal.kt, node/src/main/kotlin/net/corda/node/services/config/NodeConfiguration.kt, node/src/main/kotlin/net/corda/node/services/config/NodeConfigurationImpl.kt, node/src/main/kotlin/net/corda/node/services/config/schema/v1/V1NodeConfigurationSpec.kt, node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt, node/src/main/resources/reference.conf, node/src/test/kotlin/net/corda/node/services/vault/NodeVaultServiceTest.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/InternalMockNetwork.kt
If a node is upgraded from V3 to V4, then any states currently in the vault are not migrated correctly. In particular, the relevancy column in the vault is filled in as relevant for all states (even if the node has recorded non-relevant states) and the state_party table is not populated with old states. The result is that certain V4 features will not work correctly with these states.
It turns out that fixing this for V4 is fairly involved. However, as the issue only affects nodes that are upgrading with V3 states in the vault, it is deemed acceptable to block these nodes from starting. This gives time to provide a proper fix for the problem in time for V4.1. This PR adds code to detect V3 states in the vault and block the node from starting in this case. It also adds a configuration …
=> [CORDA-2435] Print an error and exit if the vault contains V3 states

node/src/main/kotlin/net/corda/node/NodeCmdLineOptions.kt
Original PR here: https://github.com/corda/corda/pull/4613
=> CORDA-2482: Fix issue with devModeOptions.allowCompatibilityZone not working (#4613)

node/src/main/kotlin/net/corda/node/services/persistence/NodeAttachmentService.kt
The column 'uploader' was marked as not updatable entity so any update wasn't propagated to the database when the attachment was uploaded again and the uploader field was changed to a trusted one. Also 'saveOrUpdate' removed, the entity is already managed, saveOrUpdate is for detached/new entity.
(cherry picked from commit 9f4c8bcea5bb780eec1c1f663302ed92f2c38733)
=> CORDA-2490 Attachment in the directory fails to correctly upload (#4627)

serialization/src/main/kotlin/net/corda/serialization/internal/amqp/CustomSerializerRegistry.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/LocalSerializerFactory.kt
When looking up a serializer for a concrete type implementing `PublicKey`, we really don't need to perform detailed type-and-property analysis on that type, since it will be handled by a custom serializer anyway. Although we don't know quite what causes the exception observed in [ENT-2977](https://r3-cev.atlassian.net/browse/ENT-2977), it does seem to be being thrown during analysis of one such type, and we can avoid this by performing custom serializer lookup immediately rather than waiting until we have all the type information for the object to be serialized.
To avoid introducing an inefficient scan across the entire custom serializer registry every time a serializer is requested, we modify the registry to record when a type does _not_ have a custom serializer, as well as when it does. …
=> ENT-2977 resolve custom serializers earlier

.ci/api-current.txt, core/src/main/kotlin/net/corda/core/transactions/MissingContractAttachments.kt, core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt, docs/source/api-contract-constraints.rst, docs/source/api-testing.rst
Fix infamous ``net.corda.core.transactions.MissingContractAttachments: Cannot find contract attachments for [], minimum required contract class version 1. See https://docs.corda.net/api-contract-constraints.html#debugging``
The error message had no ``ContractClassName`` is some cases.
This was especially visible when developing tests/integration tests.
Change to API:
1) added new overloaded constructor
2) another constructor changed - but this one was introduced only in v4 so it's not breaking v3
=> CORDA-2504 improve error message of missing contract attachments

core/src/main/kotlin/net/corda/core/internal/cordapp/CordappResolver.kt, core/src/test/kotlin/net/corda/core/internal/cordapp/CordappResolverTest.kt, docs/source/app-upgrade-notes.rst
* Allow `CordappResolver` to handle the case, where the same CorDapp is registered multiple times, by deduplicating. As an example, this happens, when running tests via `MockNetwork`, because a single resolver is shared between the several in-memory nodes, where the same CorDapp is regsitered for all of them.
* Update upgrade docs to be a bit more descriptive on the steps needed
* Performed an upgrade of the [tests](https://github.com/corda/corda-solutions/blob/master/bn-apps/ledger-sync/ledger-sync-service/src/test/kotlin/com/r3/businessnetworks/ledgersync/LedgerConsistencyTests.kt) from a business networks app to ensure that the described steps are enough
=> [CORDA-2496] - Adjust CorDappResolver to handle same CorDapp registered multiple times

node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/AttachmentVersionNumberMigration.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/SchemaMigration.kt
When system property is not provided or was set wrongly (a String with text "null" and not null reference).
=> Fix Liquibase AttachmentVersionNumberMigration unnecessary error log or failure in test

.ci/api-current.txt, core/src/main/kotlin/net/corda/core/transactions/MissingContractAttachments.kt, core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt, docs/source/api-contract-constraints.rst, docs/source/api-testing.rst
* CORDA-2504 Improved MissingContractAttachments error to ensure it contains contractClassName.
* CORDA-2504 Improved MissingContractAttachments error to ensure it contains contractClassName - additional API overloaded method.
* Docs
(cherry picked from commit 1b89ece09b183338b28030bd086a5e7b4d5de65f)
=> CORDA-2504 improve error message of missing contract attachments (#4628)

docs/source/network-map.rst
Previously, flag days were mentioned in the release notes but not explained anywhere in the docs. This PR adds more information surrounding network parameter updates and flag days to the network map doc.
=> Improve documentation surrounding network parameter updates/flag day

.idea/compiler.xml, core/src/main/kotlin/net/corda/core/internal/PathUtils.kt, node/src/integration-test/kotlin/net/corda/node/flows/FlowCheckpointVersionNodeStartupCheckTest.kt, samples/trader-demo/workflows-trader/src/integration-test/kotlin/net/corda/traderdemo/TraderDemoTest.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/InternalTestUtils.kt
* Removed `restart node successfully with suspended flow` as it duplicates `TraderDemoTest#Test restart node during flow works properly`
* Removed the need for a notary
=> Made FlowCheckpointVersionNodeStartupCheckTest leaner

tools/cliutils/src/main/kotlin/net/corda/cliutils/CordaCliWrapper.kt, tools/cliutils/src/main/kotlin/net/corda/cliutils/InstallShellExtensionsParser.kt
This is to prevent initialising it multiple times.
Please see linked Jira to understand how this can cause harm.
=> ENT-3001: Make `subCommands` lazy val

testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/TestCordappImpl.kt
`net.corda.testing.node.internal.TestCordappImpl.Companion#findProjectRoot` looks for a Gradle build file, but only does so for Groovy DSL (__build.gradle__). This minor fix for https://github.com/corda/corda/issues/4648 adds support for Kotlin DSL (__build.gradle.kts__).
Would it be possible to add this fix to v4 as well?
=> Fixed #4648: minor change to support Gradle's Kotlin DSL

core/src/main/kotlin/net/corda/core/flows/NotaryFlow.kt, core/src/main/kotlin/net/corda/core/flows/SendTransactionFlow.kt, core/src/main/kotlin/net/corda/core/internal/DigitalSignatureWithCert.kt, core/src/main/kotlin/net/corda/core/internal/FetchDataFlow.kt, core/src/main/kotlin/net/corda/core/internal/NetworkParametersServiceInternal.kt, core/src/main/kotlin/net/corda/core/internal/ResolveTransactionsFlow.kt, core/src/test/kotlin/net/corda/core/internal/NetworkParametersResolutionTest.kt, core/src/test/kotlin/net/corda/core/internal/ResolveTransactionsFlowTest.kt, node/src/main/kotlin/net/corda/node/internal/DBNetworkParametersStorage.kt, node/src/main/kotlin/net/corda/node/services/network/NetworkMapUpdater.kt, node/src/test/kotlin/net/corda/node/services/network/NetworkMapUpdaterTest.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/InternalMockNetwork.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/MockNetworkParametersService.kt
Add FetchParametersFlow. It requires minimumPlatformVersion to be >=4 because nodes on lower versions won't understand this flow (also, in this case transactions are not tagged). It doesn't solve the CORDA-2520 issue entirely for mixed bootstrapped networks when node 3 passes transaction that has v4 transaction in a chain, that node (also on v4) doesn't know about. But, network bootstrapper sets minimumPlatform version to 4 so it is unlikely.
=> CORDA-2520: Add FetchParametersFlow

core/src/main/kotlin/net/corda/core/internal/ClassGraphUtils.kt, core/src/main/kotlin/net/corda/core/internal/ClassLoadingUtils.kt, core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt, experimental/behave/src/scenario/kotlin/net/corda/behave/scenarios/StepsContainer.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/ContractsScanning.kt, node/src/main/kotlin/net/corda/node/internal/cordapp/JarScanningCordappLoader.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/AMQPSerializationScheme.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/CustomCordapp.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/TestCordappImpl.kt
Constrain threads used in ClassGraph calls.
Quickly patch synchronisation of attachment class loader cache.  Needs a revisit but more complicated due to DJVM.
=> ENT-3000 Start pooling classpath scanning and related fixes

core/src/main/kotlin/net/corda/core/crypto/Crypto.kt, core/src/main/kotlin/net/corda/core/crypto/SignatureScheme.kt, core/src/main/kotlin/net/corda/core/internal/ConstraintsUtils.kt, serialization/src/main/kotlin/net/corda/serialization/internal/model/TypeIdentifier.kt
Backport of https://github.com/corda/corda/pull/4608
(cherry picked from commit 197a13611dd0f15fe165b3ea0c6738c932c74d17)
=> ENT-2967 Fix up use of various JDK performance contention points (#4608)

docs/.gitattributes, docs/build.gradle, docs/docs_builder/Dockerfile, docs/make-docsite.sh
At the moment, building docs is quite hit and miss. We currently have developers on OSX, Windows, and various distros of linux. 
This new container will isolate the individual developer system from the required setup for building docs.
=> dockerize docs building

.ci/api-current.txt
This refreshes the `api-current.txt` file before release of v4.
The API has been generated, using `./gradlew generateApi` on the head of `release/4`.
It includes several new (synthetic) methods. 
All the changes have been examined, as part of https://r3-cev.atlassian.net/browse/CORDA-2349 to ensure there was no breakage.
=> [CORDA-2518] - Refresh the current API file

node-api/src/test/kotlin/net/corda/nodeapi/internal/AttachmentsClassLoaderStaticContractTests.kt, node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt, node/src/main/kotlin/net/corda/node/internal/cordapp/CordappProviderImpl.kt, node/src/main/kotlin/net/corda/node/services/persistence/NodeAttachmentService.kt, node/src/test/kotlin/net/corda/node/internal/cordapp/CordappProviderImplTests.kt, node/src/test/kotlin/net/corda/node/services/persistence/NodeAttachmentServiceTest.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/MockServices.kt, testing/test-utils/src/main/kotlin/net/corda/testing/core/internal/ContractJarTestUtils.kt
This PR relaxes the current check on Node start-up that throws a `DuplicateContractClassException` if an existing Contract Attachment of the same name and version Id already exists in the attachment store.
Note: our current logic for querying Contract Versions uses a query sorted by descending "insertion date" and we always pick the most recent entry from the query results (so this change maintains semantic compatibility in the transaction verifier).
=> CORDA-2526 Allow for duplicate signed attachments in devMode

docs/source/network-map.rst
The command listed in the docs `java -jar corda.jar clear-network-cache` is not correct.
Admins must run `java -jar corda.jar --clear-network-map-cache` instead.
=> correct command docs for clear network map cache

node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializerFactory.kt, node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/DeserializeNeedingCarpentryTests.kt, node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/StaticInitialisationOfSerializedObjectTest.kt
This changes slightly the way schema processing is performed. The interfaces included in the schema will now be loaded on-demand, instead of loading all the interfaces included in the schema. When a class is detected that's missing from the class, all of the interfaces that it implements will be loaded.
This improves backwards compatibility in cases, like the one described in the ticket.
* Re-run the test case provided in the ticket, verifying the fix is resolving the issue
* Note: the test that is removed should have been failing, but other code was masking the failure. It was trying to process a schema, where a class (and its associated interface) were missing from the classpath.
=> [CORDA-2422] - Remove interfaces from carpenting

docs/source/flow-state-machines.rst, docs/source/hello-world-flow.rst
Document the draining requirements for node upgrade in the flow state machines docs, explaining that while evolution of transaction data is supported, there is no equivalent mechanism for evolving persisted flow checkpoints.
=> CORDA-2423 document draining requirements in flow state machines

docs/build.gradle, docs/source/api-flows.rst, docs/source/api-identity.rst, docs/source/api-persistence.rst, docs/source/api-states.rst, docs/source/tutorial-attachments.rst
This fixes some issues with documentation:
* Added the rest of the projects as a second volume in the Docker used, so that code references to the other projects are successfully resolved. Attempted to do the same with a single mount, but got defeated, because of the way the Docker image is currently setup to execute the build process in the `/opt/docs_builder` path.
* Renamed some references to some projects that have been refactored (i.e. `finance`), so that they are valid
* Fixed some small typos/syntax issues in `api-persistence.rst`
Note: I'll have a look if these issues exist in the `release/4` and backport, if needed.
`./gradlew makeDocs` and verified all the links are resolved
=> Fix documentation issues

build.gradle
Finance is no longer published as a single JAR.
=> Remove old reference to publishing a single corda finance jar.

serialization/src/main/kotlin/net/corda/serialization/internal/OrdinalIO.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/LocalSerializerFactory.kt
Kotlin will put an interface's default methods into a nested `$DefaultImpls` class unless those methods are annotated with `@JvmDefault`. The "determinisation" process cannot guarantee to preserve any `$DefaultImpls` classes, and so it's safer if they're not required at all.
Ensure that Kotlin implements interface default methods as standard Java 8.
=> CORDA-2564: Ensure that corda-serialization uses @JvmDefault for interfaces.

.ci/api-current.txt, core/src/main/kotlin/net/corda/core/contracts/TransactionVerificationException.kt, core/src/main/kotlin/net/corda/core/flows/FlowLogic.kt, core/src/main/kotlin/net/corda/core/internal/AbstractAttachment.kt, core/src/main/kotlin/net/corda/core/internal/ConstraintsUtils.kt, core/src/main/kotlin/net/corda/core/internal/JarSignatureCollector.kt, core/src/main/kotlin/net/corda/core/internal/TransactionVerifierServiceInternal.kt, core/src/main/kotlin/net/corda/core/node/NetworkParameters.kt, core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt, core/src/main/kotlin/net/corda/core/transactions/ContractUpgradeTransactions.kt, core/src/main/kotlin/net/corda/core/transactions/LedgerTransaction.kt, core/src/main/kotlin/net/corda/core/transactions/NotaryChangeTransactions.kt, core/src/main/kotlin/net/corda/core/transactions/WireTransaction.kt, core/src/main/kotlin/net/corda/core/utilities/ProgressTracker.kt, core/src/test/kotlin/net/corda/core/contracts/ConstraintsPropagationTests.kt, core/src/test/kotlin/net/corda/core/contracts/PackageOwnershipVerificationTests.kt, core/src/test/kotlin/net/corda/core/transactions/AttachmentsClassLoaderSerializationTests.kt, core/src/test/kotlin/net/corda/core/transactions/AttachmentsClassLoaderTests.kt, core/src/test/kotlin/net/corda/core/transactions/TransactionTests.kt, node/src/integration-test/kotlin/net/corda/node/CordappConstraintsTests.kt, node/src/integration-test/kotlin/net/corda/node/services/AttachmentLoadingTests.kt, node/src/main/kotlin/net/corda/node/services/persistence/NodeAttachmentService.kt, serialization/src/main/kotlin/net/corda/serialization/internal/carpenter/ClassCarpenter.kt, serialization/src/test/kotlin/net/corda/serialization/internal/CordaClassResolverTests.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/MockServices.kt, testing/test-utils/src/main/kotlin/net/corda/testing/internal/MockCordappProvider.kt
This PR patches up the package namespace ownership check to work as originally specified, and moves it into the attachments classloader. It also fixes a few cases where the unit test simulation code wasn't accurate enough.
=> [CORDA-2545] Rework package namespace ownership check

docs/source/corda-api.rst
This change makes the difference between public/non-public a bit more explicit in the documentation.
Notes:
* I was thinking of adding links for the modules to Github for a better experience, but I refrained. The reason is that modules will move around and links could go stale, until we take the burden of updating them on every release, instead of having them point to `master`. Open to any alternative ideas of how it could be done, though.
=> [CORDA-2420] - Make boundary of public API explicit in docs

docs/source/corda-network/UAT.md
We need to have an external page which talks about UAT. As agreed with R3's marketing team and the Network team, this should be on docs.corda.net rather than elsewhere. 
(The idea is that this cannot be corda.network since UAT is part of R3, not the Foundation.)
This page + relevant sub-pages will continue to be updated, with more detail.
=> Adding new page on UAT environment

docs/source/network-map.rst
This reverts commit 0a50d76ab18c19682eea54b54bb1e03137a4b78d.
Reverting this change which is not the correct command for v4 (the old command will work but is deprecated). The issue occurred because that flag was missing altogether in the v3 docs - have created a Jira for someone to https://r3-cev.atlassian.net/browse/CORDA-2571 add it.
=> Revert "DOCS - correct command docs for clear network map cache (#4677)"

docs/source/api-contract-constraints.rst, docs/source/app-upgrade-notes.rst
- Delete information about hash->signature constraint migration. That
won't work for C4.0
- Rewrite parts of the api-contract-constraints.rst file to fix grammar
problems and reduce the weight of the page. Some detail isn't really
necessary at this point in the docs.
- Mention more things in the upgrade notes.
=> Docs: fix various issues for C4.

docs/source/clientrpc.rst
This fleshes out a bit more information to users on how to configure and connect to RPC using TLS.
=> ENT-2192: Add a bit more docs detail on how to use RPC with TLS.

core/src/main/kotlin/net/corda/core/node/NodeInfo.kt, core/src/test/kotlin/net/corda/core/node/NodeInfoTests.kt
Simple change to the message returned when the requested legal identity does not exist on the Node. Previously it returned `Node does not have an identity`, which is slightly confusing as the Node does have a legal identity, just not the one that was requested. Changing the message text to `Node does not have the requested identity of` makes it clearer that the client requested an identity different to any of the ones that this Node represents.
Added an `isLegalIdentity` function that allows the client to check if the Node represents the requested `CordaX500Name` without throwing an exception if it does not.
My PR is in accordance with the Developer Certificate of Origin
Note that there are failures in the `H2SecurityTests` due to `Expected an exception of class …
=> Clarify error message when Node does not have the requested identity

core/src/main/kotlin/net/corda/core/transactions/SignedTransaction.kt, core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt, node/src/integration-test/kotlin/net/corda/contracts/SignatureConstraintVersioningTests.kt
Adjust the way we select attachments so we don't use the latest known version but rather, the installed version (stop viral propagation)
=> CORDA-2576 Viral update propagation: select attachments from those loaded by node on startup.

.ci/api-current.txt, core/src/main/kotlin/net/corda/core/node/services/KeyManagementService.kt, node/src/main/kotlin/net/corda/node/services/keys/BasicHSMKeyManagementService.kt, node/src/main/kotlin/net/corda/node/services/keys/E2ETestKeyManagementService.kt, node/src/main/kotlin/net/corda/node/services/keys/KeyManagementServiceInternal.kt, node/src/main/kotlin/net/corda/node/services/keys/PersistentKeyManagementService.kt, node/src/main/kotlin/net/corda/node/services/schema/NodeSchemaService.kt, node/src/test/kotlin/net/corda/node/services/persistence/HibernateColumnConverterTests.kt, node/src/test/kotlin/net/corda/node/services/vault/ExternalIdMappingTest.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/MockServices.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/InternalMockNetwork.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/MockKeyManagementService.kt
Added two overloads in key management service to create a key pair and assign it to an ID. Ideally we need this in the Corda 4 release.
JIRA: https://r3-cev.atlassian.net/browse/CORDA-2563
Thoughts? Objections?
=> CORDA-2563: Assign external IDs when creating new keys

node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/AttachmentVersionNumberMigration.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/SchemaMigration.kt, node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
The `AttachmentVersionNumberMigration` relies on the network parameters being available in order to find what contract implementations are whitelisted. These may not be available if, for example, the node is being bootstrapped or is first connecting to the doorman. However, the migrations will still run in these cases, resulting in an error message being printed to the console. This can be misleading, as it does not prevent operations such as connecting to the doorman from succeeding.
This PR updates the migration to handle this case in such a way that an error message is not printed to the console. The node logs will still contain an indication of what went wrong.
Changes:
- Detect if the network parameters file is not present while trying to read them from the supplied path
- Log at the …
=> [CORDA-2591] Prevent spurious logs in AttachmentVersionNumberMigration

core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt, docs/source/release-notes.rst, node/src/main/kotlin/net/corda/node/migration/CordaMigration.kt, node/src/main/kotlin/net/corda/node/migration/MigrationNamedCacheFactory.kt, node/src/main/kotlin/net/corda/node/migration/MigrationServicesForResolution.kt, node/src/main/kotlin/net/corda/node/migration/VaultStateMigration.kt, node/src/test/kotlin/net/corda/node/migration/VaultStateMigrationTest.kt
[CORDA-2487](https://r3-cev.atlassian.net/browse/CORDA-2487) introduces a custom liquibase migration to populate the state_party table and correctly mark states as relevant or not when upgrading from V3. In order to do this, it must deserialise transactions in the database to obtain the output contract states, and from these read the participants in the state. If the jar defining the contract state is on the classpath (as is likely if the migration is run at node startup), then this will succeed. However, if this isn't the case, then whether the participants can be read depends on how the state was serialised. The carpenter will only provide a readable participants list if this field was not calculated, or was marked as a `SerializableCalculatedProperty`. This could result in states …
=> [CORDA-2561] Use the attachments classloader to deserialise contract states in migrations

docs/source/corda-configuration-file.rst, docs/source/node-administration.rst
Porting over some of the changes from https://github.com/corda/enterprise/pull/1811.
=> Syncing config file doc page with ENT

tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/Main.kt, tools/network-bootstrapper/src/main/kotlin/net/corda/bootstrapper/cli/CommandParsers.kt
Note that `${COMPLETION-CANDIDATES}` from Picocli doesn't work for this due to `BackendType.toString()`. So have hardcoded the options for now.
=> CORDA-2623 - Add help screen to Network Builder CLI tool

tools/cliutils/src/main/kotlin/net/corda/cliutils/InstallShellExtensionsParser.kt
[CORDA-2622](https://r3-cev.atlassian.net/browse/CORDA-2622) - Fix broken shell extensions. `ProcessBuilder` takes a list of program plus arguments, not a string for the whole command. Also added a check for failed program execution with enhanced logging.
Fix for behaviour introduced in https://github.com/corda/corda/pull/4263
=> CORDA-2622 - Fix shell extensions

docs/source/tutorial-cordapp.rst
The sample RPC client was removed from the example CorDapp because:
* The templates now contain an example RPC client
* The example CorDapp's Spring webserver also serves as an example of an RPC client
This PR updates the docs accordingly.
=> CORDA-2616 Update doc to reflect removed RPC client.

docs/source/changelog.rst
It looks (after a thorough grep) like there's only one, in the changelog.
=> CORDA-2625 remove reference to Corda 4.1

.idea/compiler.xml, node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt, node/src/main/kotlin/net/corda/node/services/statemachine/SessionRejectException.kt, node/src/main/kotlin/net/corda/node/services/statemachine/StaffedFlowHospital.kt, node/src/test/kotlin/net/corda/node/services/FinalityHandlerTest.kt
To allow rolling upgrades where members of a BN may not all upgrade at the same time, the FinalityHandler is now always enabled, and not disabled if no old apps are installed.
Previously any attempt to use the FinalityHandler in such a scenerio would send the flow to the hospital, where manual intervention would be required to recover the transaction.
=> CORDA-2613: FinalityHandler is no longer gated on app target versions

node/src/main/kotlin/net/corda/node/migration/VaultStateMigration.kt, node/src/test/kotlin/net/corda/node/migration/VaultStateMigrationTest.kt
If the custom vault state migration detects failures, today it will log the error that occurred, but will finish the migration and mark this as successful. This change instead causes the migration to fail if any states were skipped. Note that non-skipped states will still be migrated even if the migration subsequently fails; on attempting to migrate again only skipped states will be added.
Changes:
- Updated any error conditions to also throw an exception, signalling to liquibase that this migration has failed.
=> [CORDA-2627] Fail the custom vault state migration if any states were skipped

core/src/main/kotlin/net/corda/core/internal/cordapp/CordappImpl.kt, core/src/main/kotlin/net/corda/core/internal/cordapp/CordappResolver.kt, core/src/test/kotlin/net/corda/core/transactions/TransactionBuilderTest.kt, node/src/main/kotlin/net/corda/node/internal/cordapp/JarScanningCordappLoader.kt
Abstract flow classes are not associated with CorDapps, and consequently, the node is unable to resolve the correct target platform version.
JIRA: [CORDA-2634](https://r3-cev.atlassian.net/browse/CORDA-2634)
=> CORDA-2634 - Fix derivation of currentTargetVersion for abstract classes

.ci/api-current.txt, core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/cordapp/CordappLoader.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/SchemaMigration.kt, node-api/src/test/kotlin/net/corda/nodeapi/internal/AttachmentsClassLoaderStaticContractTests.kt, node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt, node/src/main/kotlin/net/corda/node/internal/cordapp/CordappProviderImpl.kt, node/src/main/kotlin/net/corda/node/internal/cordapp/JarScanningCordappLoader.kt, node/src/main/kotlin/net/corda/node/migration/MigrationServicesForResolution.kt, node/src/main/kotlin/net/corda/node/utilities/NotaryLoader.kt, node/src/test/kotlin/net/corda/node/services/vault/VaultSoftLockManagerTest.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/MockServices.kt, testing/test-utils/src/main/kotlin/net/corda/testing/internal/MockCordappProvider.kt
States created via a contract upgrade transaction currently do not migrate correctly, as in order to work out the participants the creating transaction must be deserialised and resolved, and the process of resolving requires a classloader, which is currently not supplied by the custom migration. This PR adds this by providing the cordapp loader used by the `SchemaMigration`, which is used to load classes in these cases. The classloader from this is also used as a parent when deserialising states from normal wire transactions.
Changes:
- Add an extra field to the `SchemaMigration` class to pass in a `CordappLoader`, and pass this to the custom migration via a thread local
- Move `CordappLoader` to the node-api module to break a circular dependency
- Provide a `CordappProvider` …
=> [CORDA-2636] Ensure states created with contract upgrades can be migrated

docs/source/changelog.rst
The `issuableCurrencies` property has been moved from `node.conf` to the finance workflows CorDapp configuration. This change has not been mentioned anywhere. This PR adds it to the changelog.
=> [CORDA-2635] Documentation update for issuableCurrencies

docs/source/cordapp-build-systems.rst
Creating this doc fix as until https://r3-cev.atlassian.net/browse/CORDA-2615 is fixed the second method of adding cordapps to the node doesn't work.
Also created https://r3-cev.atlassian.net/browse/CORDA-2650 to remind us to put the documentation back in once the issue is fixed.
=> [CORDA-2615] - Remove incorrect documentation

docs/source/docker-image.rst
Small fix-up after removing the v4 snapshot images from DockerHub: https://hub.docker.com/u/corda
=> NOTICK - Docker: point to release images instead of snapshot

djvm/build.gradle, djvm/src/main/kotlin/net/corda/djvm/analysis/ClassResolver.kt, djvm/src/main/kotlin/net/corda/djvm/rewiring/ClassRewriter.kt, djvm/src/main/kotlin/net/corda/djvm/rewiring/SandboxClassWriter.kt, djvm/src/main/kotlin/net/corda/djvm/source/SourceClassLoader.kt
Fix DJVM SourceClassLoader so that ASM will use it only to load classes from outside the sandbox.
=> CORDA-2667: Fix DJVM SourceClassLoader for ASM.

docs/source/corda-api.rst
(cherry picked from commit 08ce12f068f12e3ed14d4baeb366c80dfbe74da5)
Port of https://github.com/corda/corda/pull/4788.
=> CORDA-2610: Internal APIs made much clearer in API doc page

build.gradle, testing/node-driver/build.gradle, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/TestCordappImpl.kt
The TestCordappImpl runs gradle to build cordapp jars required for tests. It's causing multiple issues including not actually building a jar or causing the JVM to die with SIGBUS.
Using the Gradle Tooling API to run the builds seems to fix the issues.
=> ENT-3017: TestCordapp – use Gradle tooling API for builds

.ci/api-current.txt, core/src/main/kotlin/net/corda/core/messaging/CordaRPCOps.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/RpcHelpers.kt, node/src/main/kotlin/net/corda/node/internal/CordaRPCOpsImpl.kt, tools/shell/src/main/kotlin/net/corda/tools/shell/InteractiveShell.kt
Reintroduce `pendingFlowsCount` to public API (as deprecated). Advise to use the `gracefulShutdown` command in the shell instead.
The draining API should be revisited and tidied up for future releases.
See [CORDA-2669](https://r3-cev.atlassian.net/browse/CORDA-2669) for further details.
=> CORDA-2669 - Reintroduce pendingFlowsCount

tools/demobench/src/main/kotlin/net/corda/demobench/plugin/CordappController.kt
Allow for more "built-in" CorDapps to be added to DemoBench at some point.
=> ENT-3128: Tidy up DemoBench's "built-in CorDapp" management.

node/src/main/kotlin/net/corda/node/services/rpc/RPCServer.kt
When an RPC client disconnects from the RPC server, the log entry created now has its log level set to info rather than warning. It is perfectly normal for an RPC client to disconnect - only the RPC client knows if it was intentional.
=> ENT-3059: RPC disconnect log entry changed to info

core/src/test/kotlin/net/corda/core/flows/ReferencedStatesFlowTests.kt
Adds a test that creates state on node 0 and does not share.  Then creates a transaction referring to it that is shared with node 1 (relevant only record).  Then evolve the reference state on node 0 and do not share it.   Then creates a transaction referring to it that is shared with node 1 (relevant only record).
That last transaction should then update the states recorded for the reference states transaction to include the second version of the reference state (since it wasn't originally relevant), thus consuming the original version.
PR coming in enterprise (which should be merged first to avoid breaking merge PR).
=> ENT-3165 Add unit test for reference state consumption.

docs/source/changelog.rst, node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt, node/src/test/kotlin/net/corda/node/services/vault/NodeVaultServiceTest.kt
https://github.com/corda/corda/pull/3789 changed the relevancy check of OwnableState to include the participants list in addition to the owner. This however breaks existing apps which assume (in their vault query) an OwnableState is recorded to the vault if-and-only-if the owner matches.
=> CORDA-2665: Updated OwnableState relevancy check put back to V3 version

docs/source/node-explorer.rst, tools/explorer/README.md
Remove some lingering references to deleted Gradle tasks, fix formatting, grammar.
=> ENT-3128: Update documentation for Node Explorer.

core/src/main/kotlin/net/corda/core/node/services/vault/QueryCriteria.kt
When a V3 RPC client is used to talk to a V4 node, a failure is observed when using vault queries. This occurs because the old constructors are not marked with `DeprecatedConstructorForDeserialization`. Introducing these annotations to the `VaultQueryCriteria` fixes the problem.
Note that this JIRA ticket also covers the reverse problem (V4 RPC clients are not able to talk to V3 clients), but this is not addressed by this PR. Instead, a fix is needed in V3, which will be supplied in a separate PR.
Changes:
- Add `DeprecatedConstructorForDeserialization` annotations to all non-primary constructors for classes within `VaultQueryCriteria` and `AttachmentQueryCriteria`.
=> [ENT-3138] Ensure V4 can deserialize vault query criteria from V3 RPC clients

serialization/src/main/kotlin/net/corda/serialization/internal/amqp/EvolutionSerializerFactory.kt
This PR is a port of the improved error message when a non-backwards compatible change is detected during deserialization to Open Source.
=> [ENT-3068] Port error message in deserialization improvements to OS

docs/source/flow-overriding.rst
Add `@InitiatedBy` to the java docs on the responder flow, this is
already shown in the kotlin version.
Add a note on overriding responders, instructing developers to still
include the `@InitiatedBy` annotation on the new responder even though
the configuration setup can make developers think that defining the
override will guarantee the initiator and responder will join up
correctly.
=> Correct extending flows java docs and add note on overriding responders

.ci/api-current.txt, core/src/main/kotlin/net/corda/core/contracts/TransactionVerificationException.kt, core/src/test/kotlin/net/corda/core/contracts/TransactionVerificationExceptionSerialisationTests.kt
Two of the subclasses of `TransactionVerificationException` take a non-nullable `cause` parameter, and use the message from this `cause` to construct the exception's own message.
Unfortunately, `ExceptionSerializingRpcOpsProxy` nulls out the `cause` parameter of `CordaThrowable` exceptions over the wire, resulting in an `IllegalArgumentException` thrown by Kotlin's own null-checking when we try to deserialize the exception at the receiving end.
To remedy this, we make the `cause` parameter nullable, and introduce an explicit `message` parameter, matching the `message` property on the exception, that can be used to convey the message over the wire even when the `cause` has been nulled out.
=> ENT-3166 don't depend on cause for message

docs/source/network-bootstrapper.rst
Bootstrapper will be updated to give a better error message if it sees any node.confs with devMode=false (CORDA-2686). This PR updates the docs to match.
=> CORDA-2691 Clarify that bootstrapper only works in devMode

node-api/src/main/kotlin/net/corda/nodeapi/internal/network/NetworkBootstrapper.kt, node-api/src/test/kotlin/net/corda/nodeapi/internal/network/NetworkBootstrapperTest.kt
The JVM is _supposed_ to delete the `NetworkBootstrapper` classes once the `cordformation` Gradle plugin closes their `ClassLoader`. However, VisualVM shows that some classes still linger. In general, these seem to be "singleton" classes such as `object`, `companion` or some lambdas. So I've done the following:
- Simplified some "deeply-lambda'd" expressions.
- Turned `AMQPParametersSerializationScheme` into a `class`.
- Passed `corda.jar` as a `URL` instead of an `InputStream` so that we are _guaranteed_ to close the stream after use.
- Ensured that shutting the `ExecutorService` down will also kill any Node processes that are still running.
Unfortunately this doesn't completely fix the problem. It just reduces it slightly.
=> CORDA-2679: Allow more Network Bootstrapper code to be unloaded from JVM.

docs/source/tutorial-building-transactions.rst
You can't do this as TransactionBuilder is not serializable.
=> Removed part about exchanging transaction builder between parties. 

docs/source/network-bootstrapper.rst, node-api/src/main/kotlin/net/corda/nodeapi/internal/network/NetworkBootstrapper.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/network/WhitelistGenerator.kt, node-api/src/test/kotlin/net/corda/nodeapi/internal/network/WhitelistGeneratorTest.kt
For migration from CZ whitelist to Signature consorting, the signed JAR needs to be whitelisted, however bootstrapper doesn't whitelist contracts from signed jars, added additional "include_whitelist.txt" file which force adding contracts to whitelist from signed jars.
=> CORDA-2554 - Bootstrapper - option to include contracts to whitelist from signed JARs

node/src/main/kotlin/net/corda/node/internal/cordapp/JarScanningCordappLoader.kt
Only log a line about looking for notary implementations if at least notary implementation is found.
It might be unnecessary and confusing to log when no implementations are found.
=> CORDA-2690: Reduce CordApp scanning logging

core/src/main/kotlin/net/corda/core/serialization/SerializationAPI.kt, core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt, serialization/src/main/kotlin/net/corda/serialization/internal/SerializationScheme.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/DeserializationInput.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/ObjectSerializer.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/RemoteSerializerFactory.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/SerializerFactoryBuilder.kt, serialization/src/main/kotlin/net/corda/serialization/internal/model/TypeLoader.kt, serialization/src/test/java/net/corda/serialization/internal/carpenter/JavaCalculatedValuesToClassCarpenterTest.java, serialization/src/test/kotlin/net/corda/serialization/internal/amqp/DeserializeNeedingCarpentryTests.kt, serialization/src/test/kotlin/net/corda/serialization/internal/amqp/DeserializeSimpleTypesTests.kt, serialization/src/test/kotlin/net/corda/serialization/internal/carpenter/ClassCarpenterTestUtils.kt, serialization/src/test/kotlin/net/corda/serialization/internal/carpenter/CompositeMemberCompositeSchemaToClassCarpenterTests.kt, serialization/src/test/kotlin/net/corda/serialization/internal/carpenter/InheritanceSchemaToClassCarpenterTests.kt, serialization/src/test/kotlin/net/corda/serialization/internal/carpenter/MultiMemberCompositeSchemaToClassCarpenterTests.kt, serialization/src/test/kotlin/net/corda/serialization/internal/model/ClassCarpentingTypeLoaderTests.kt
Can be used by the attachment class loader - Serialisation Framework will still consume all Exceptions and throw a NotSerializableException
@tudor-malene unsure how to test this from your perspective, but the carpentry unit tests now try
without it enabled and assert it throws a NotSerializableException
=> CORDA-2688 - Add Serialization Context option for no carpenting

client/jfx/src/main/kotlin/net/corda/client/jfx/model/NodeMonitorModel.kt, client/jfx/src/main/kotlin/net/corda/client/jfx/model/TransactionDataModel.kt, core/src/main/kotlin/net/corda/core/internal/ConstraintsUtils.kt, core/src/main/kotlin/net/corda/core/internal/InternalUtils.kt, core/src/main/kotlin/net/corda/core/transactions/WireTransaction.kt, core/src/main/kotlin/net/corda/core/utilities/KotlinUtils.kt, core/src/test/kotlin/net/corda/core/utilities/LazyMappedListTest.kt
Forcibly deserialise the `WireTransaction`'s `TransactionState<ContractState>` output objects up-front, replacing any that fail to deserialise with a dummy `UNKNOWN_TRANSACTION_STATE` object instead.
Also simplify some lambda-spaghetti and remove an unused import.
=> CORDA-2694: Prevent Node Explorer from crashing should it receive unknown transaction objects.

node/src/main/kotlin/net/corda/node/services/statemachine/SingleThreadedStateMachineManager.kt
On existing session message when can't find a flow corresponding to
session ID. See JIRA: ENT-3058
=> CORDA-2706: Change logging level from warn to info

core/src/main/kotlin/net/corda/core/internal/CordaUtils.kt, core/src/main/kotlin/net/corda/core/transactions/SignedTransaction.kt, core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
see https://r3-cev.atlassian.net/browse/CORDA-2692
1. Modify the `internalFindTrustedAttachmentForClass` function to look through any attachments , not just "Contract Attachments"
2. Handle more exception types which are caused by a `ClassNotFoundException` to make this feature more robust.
3. Improve error messages and warnings
=> CORDA-2692 Handle more exceptions for addMissingDependencies

constants.properties
Cordformation now adds Jolokia to Gradle's `cordaRuntime` configuration instead of `runtime`. This means that the `cordapp` plugin will no longer add Jolokia to the CorDapp semi-fat jar.
=> CORDA-2642, CORDA-2699: Upgrade to Corda Gradle plugins 4.0.42 to remove Jolokia from sample CorDapps.

docs/source/app-upgrade-notes.rst
This is a small change in the upgrade docs related to the `FinalityFlow` in order to make a bit more explicit the difference between initiating & non-initiating flows and the implications on the possible ways the upgrade can be deployed.
=> DOCS - clarify the upgrade policy for finality flow

docs/source/api-contract-constraints.rst, docs/source/app-upgrade-notes.rst, docs/source/cordapp-constraint-migration.rst, docs/source/cordapp-upgradeability.rst, docs/source/network-bootstrapper.rst, docs/source/upgrading-cordapps.rst
Documentation explaining how to consume existing hash and CZ whitelisted states using Corda 4.
=> CORDA-2684 Added new guide on CorDapp Constraints Migration procedures.

node/src/main/kotlin/net/corda/node/internal/cordapp/JarScanningCordappLoader.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/TestCordappInternal.kt
There's a bug with the ServiceLoader which leaks a file handle to the app jar on shutdown. This causes an issue if a mock node is restarted in Windows. To avoid the problem completely we no longer overwrite any existing jars, as the jar to be copied will be same anyway.
(cherry picked from commit 0038a864817d331d7e48d741770b7acc40af2574)
Port of https://github.com/corda/enterprise/pull/1906
=> ENT-3266: Do not attempt to overrwite an existing CorDapp jar in tests

client/jackson/src/main/kotlin/net/corda/client/jackson/internal/CordaModule.kt, client/jackson/src/test/kotlin/net/corda/client/jackson/StateMachineRunIdTest.kt, client/rpc/src/smoke-test/java/net/corda/java/rpc/StandaloneCordaRPCJavaClientTest.java, client/rpc/src/smoke-test/kotlin/net/corda/kotlin/rpc/StandaloneCordaRPClientTest.kt, core/src/smoke-test/kotlin/net/corda/core/NodeVersioningTest.kt, core/src/smoke-test/kotlin/net/corda/core/cordapp/CordappSmokeTest.kt, docs/source/shell.rst, node/src/main/kotlin/net/corda/node/internal/rpc/proxies/AuthenticatedRpcOpsProxy.kt, node/src/main/kotlin/net/corda/node/internal/security/RPCSecurityManagerImpl.kt, node/src/test/kotlin/net/corda/node/services/RPCSecurityManagerTest.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/MockServices.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/DriverDSLImpl.kt, testing/smoke-test-utils/src/main/kotlin/net/corda/smoketesting/NodeProcess.kt, tools/shell/build.gradle, tools/shell/src/main/java/net/corda/tools/shell/FlowShellCommand.java, tools/shell/src/main/java/net/corda/tools/shell/RunShellCommand.java, tools/shell/src/main/kotlin/net/corda/tools/shell/InteractiveShell.kt, tools/shell/src/test/kotlin/net/corda/tools/shell/InteractiveShellTest.kt
Add "kill" to the list of explicit flow operations allowed from Corda's shell. Also fix Jackson support for `StateMachineRunId` so that we can serialise UUID values directly to flow IDs.
=> CORDA-2569: Add "flow kill <ID>" command to Corda's shell.

docs/source/clientrpc.rst
Fix commas in documents: elements inside a list `[]` are comma-separated, whereas element in an object `{}` are not.
=> CORDA-2703: Fix use of commas in node.conf examples.

node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
Overriding a val leads to initialisation ordering complications that can't be elegantly solved in kotlin (in Java you could).
=> ENT-3256 Cleaner way to override

djvm/cli/src/main/kotlin/net/corda/djvm/tools/cli/CommandBase.kt, djvm/cli/src/main/resources/log4j2.xml, djvm/src/main/kotlin/net/corda/djvm/messages/Severity.kt
- Set DJVM CLI logging threshold to "TRACE".
- Configure root logging level programmatically.
- Support DEBUG logging level.
=> CORDA-2725: Fix logging configuration for DJVM CLI.

djvm/cli/src/main/kotlin/net/corda/djvm/tools/cli/CommandBase.kt
Include the new `DEBUG` level in the output of `--help`.
=> CORDA-2725: Include DEBUG in DJVM CLI help's list of logging levels.

docs/source/tutorial-cordapp.rst
@anthonykeenan - apols - appear to have used a forked repo for this - will try a non-forked one post this change.
In this PR: https://github.com/corda/cordapp-template-kotlin/pull/46
We have deleted the lib/quasar.jar and updated the docs to change the way we recommend running tests inside IntelliJ. It's a bit controversial, but we did this for the following reasons:
when corda 4 was released, everyone forgot to update the quasar.jar in the template projects to the corda 4 version
customers who had written cordapps based on the template needed to know to update the quasar version in their existing cordapps, but this was missed from the upgrade nodes
we could have written some gradle to automatically download the jar file, but you still have to do the -javaagent dance each time you run a …
=> CORDA-2715 - Update test runner instructions for CorDapp tutorial

node/src/main/kotlin/net/corda/node/utilities/NotaryLoader.kt, node/src/test/kotlin/net/corda/node/services/TimedFlowTests.kt
If a notary service is misconfigured with the type (either validating or not validating) stored in the node's configuration not matching that advertised in the network map cache, the notary will throw an exception and fail on startup.
Previously, this misconfiguration would result in an exception being thrown when attempting to notarise a transaction. This change results in the exception being thrown at node startup and the node operator being aware of the misconfiguration earlier.
=> CORDA-2629: Provide a better error msg when notary type misconfig

node/src/main/kotlin/net/corda/node/services/identity/PersistentIdentityService.kt, node/src/main/kotlin/net/corda/node/utilities/AppendOnlyPersistentMap.kt, node/src/test/kotlin/net/corda/node/services/persistence/AppendOnlyPersistentMapNonConcurrentTest.kt
This change removes some bugs that led to the issue described in the linked ticket. What was happening is the following: when a confidential identity was registered, the `principalToParties` was updated, which is a mapping from x500 name to the hash of the identity's key. This could potentially override the existing mapping from the associated legal identity. Indeed, that was happening only in a specific case, where the cache was small enough to cause evictions. In this case, an unrelated bug in `AppendOnlyPersistentMap` led to this mapping replacing the existing one (from the legal identity) only in the cache, without replacing it in the DB though.
As a result, this contains the following 2 changes:
- Registration of confidential identities is adjusted, so that only `keyToParties` is …
=> CORDA-2705 - Prevent duplicates in cache and fix the mappings persisted for confidential identities

docs/source/tutorial-test-dsl.rst
A small style fix. Apparently, `` block in rst does not support surrounding text, unless it's escaped, thus breaking the format.
=> DOCS - style fix

release-tools/jiraReleaseChecker.py
Amusingly, if all the tickets mentioned as fixed in Jira are marked in the Git commits we fell over... so yay people getting things right.
Also allows for resetting your password in the keyring if, like me, you mess up typing it you're now no longer locked out
=> RELEASE - Add password reset, cope with all git tickets marked in Jira

testing/smoke-test-utils/src/main/kotlin/net/corda/smoketesting/NodeProcess.kt
Ensure that Notary network parameters are consistent with their `node.conf` files.
=> CORDA-2629: Configure smoke-test nodes to have validating notaries.

core/src/main/kotlin/net/corda/core/utilities/ProgressTracker.kt, core/src/test/kotlin/net/corda/core/utilities/ProgressTrackerTest.kt, docs/source/changelog.rst, finance/workflows/src/main/kotlin/net/corda/finance/flows/CashIssueAndPaymentFlow.kt, node/src/test/kotlin/net/corda/node/services/statemachine/FlowFrameworkTests.kt, tools/shell/src/main/kotlin/net/corda/tools/shell/utlities/ANSIProgressRenderer.kt
When running tracked flows via RPC, often the first few steps from the `ProgressTracker` will be lost. This happens as the `ProgressTracker` observables are "hot", meaning they start emitting events before anyone has subscribed to the observable. This means the flow has often completed the first few events before any observer has subscribed. This PR changes the progress tracker observables to all buffer events before an observer subscribes.
Carrying this out results in a number of progress tracking issues becoming visible relating to the `CashIssueAndPaymentFlow`. In particular, this defines a top level progress tracker that is never stepped through, which has been removed. A related issue is that the progress tracking for issuance of cash is overwritten by that for paying it, which is …
=> [CORDA-2737] Buffer events from observables in ProgressTracker until subscribed to

docs/source/node-database.rst
Documentation improvement for Node Database to explain a manual step to create ``hibernate_sequence`` object, in some cases Hibernate may skip creating the sequence causing imminent error at startup:
```
[1;31m[ERROR] 09:25:18+0530 [main] spi.SqlExceptionHelper.logExceptions - ERROR: relation "hibernate_sequence" does not exist
Position: 17
[m[1;31m[ERROR] 09:25:19+0530 [main] internal.Node.run - Exception during node startup
[m javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
=> CORDA-2393 Improve documentation for PostgreSQL to avoid missing hibernate_sequence

node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt, node/src/main/kotlin/net/corda/node/internal/subcommands/InitialRegistrationCli.kt, node/src/main/kotlin/net/corda/node/internal/subcommands/ValidateConfigurationCli.kt, tools/cliutils/src/main/kotlin/net/corda/cliutils/CordaCliWrapper.kt, tools/shell-cli/src/main/kotlin/net/corda/tools/shell/StandaloneShell.kt
Test if we have access to the logging path (baseDirectory/logs) before attempting to write to them. This allows us to shut down gracefully with an easily understandable error message.
Without doing this, the log4j2 will attempt to access the logPath when it first uses the logger in the call() function.
This does involve changing the signature of initiLogging to return a Boolean. This allows call() to know whether initLogging was successful and hence either continue execution or shut down.
=> CORDA-2506: Better handling of invalid log path

node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt, node/src/main/kotlin/net/corda/node/services/identity/PersistentIdentityService.kt, node/src/main/kotlin/net/corda/node/services/persistence/AbstractPartyToX500NameAsStringConverter.kt
Add a cache for notary identities in the PersistentIdentityService. This
solves a reported problem where notary identity lookup fails if its network
map entry is missing, which results in an exception when trying to insert
a state into the vault after recording a transaction.
=> CORDA-2745: Cache notary identity lookups

node/src/main/kotlin/net/corda/node/services/statemachine/TransitionExecutorImpl.kt
Leave error logging for the flow hospital ([ENT-3060](https://r3-cev.atlassian.net/browse/ENT-3060), moved to [CORDA-2757](https://r3-cev.atlassian.net/browse/CORDA-2757))
=> CORDA-2757 / ENT-3060 - Change log level in flow transition executor

core/src/main/kotlin/net/corda/core/utilities/ProgressTracker.kt, core/src/test/kotlin/net/corda/core/utilities/ProgressTrackerTest.kt, finance/workflows/src/main/kotlin/net/corda/finance/flows/CashIssueAndPaymentFlow.kt, tools/shell/src/main/kotlin/net/corda/tools/shell/utlities/ANSIProgressRenderer.kt, tools/shell/src/test/kotlin/net/corda/tools/shell/utilities/ANSIProgressRendererTest.kt
This PR is a set of robustness enhancements to the `ProgressTracker` and `AnsiProgressRenderer` that should mean these report the correct steps as being executed under more circumstances. The main fix is to allow multiple child trackers to have the same steps, which happens in, for example, the `CashIssueAndPaymentFlow`. There are also a few other changes to try and remove other sources of bugs, and a few commenting improvements and removal of unneeded code.
Changes:
- Fixed the calculation of the `stepsTreeIndex` in `ProgressTracker` to account for the same step label existing under multiple top level steps.
- Fixed the recalculation of indices seen in the `AnsiProgressRenderer` to account for the same step label possibly existing at multiple points in the step tree.
- Fixed an issue …
=> [CORDA-2738] Allow the ProgressTracker to cope with child trackers with the same steps

node/build.gradle, testing/node-driver/src/main/kotlin/net/corda/testing/driver/Driver.kt, testing/node-driver/src/main/kotlin/net/corda/testing/driver/internal/GlobalTestPortAllocation.kt
Node's integration tests are repeatedly creating servers that listen on a small range of ports starting from 10,000. If a previous test's servers don't shut down quickly enough then the next test can accidentally connect to one of them, and then Chaos Happens.
Chaos is Bad. Avoid Chaos by incrementing port allocations globally across all of the Node's integration tests so that lingering servers will be ignored.
=> CORDA-2759: Use GlobalTestPortAllocation for Node's integration tests.

config/dev/log4j2.xml, docs/source/node-administration.rst, node/src/integration-test/kotlin/net/corda/node/BootTests.kt, testing/node-driver/src/integration-test/kotlin/net/corda/testing/driver/DriverTests.kt
If a hibernate error occurs (deadlock, for example) that would cause a flow to be sent to the hospital, hibernate logs the warnings and errors before we do. This results in duplication in the logs, and pollutes the log. To solve this, we create a new log appender named diagnostic-{node-name}.log and log any org.hibernate messages of warn and above to that file. This way, messages are not lost, which means that the information can be retrieved if need be.
=> ENT-3057: Log hibernate warns and errors in different log

core/src/test/kotlin/net/corda/core/internal/TopologicalSortTest.kt, core/src/test/kotlin/net/corda/core/node/VaultUpdateTests.kt, node/src/integration-test/kotlin/net/corda/testMessage/ScheduledState.kt, node/src/test/kotlin/net/corda/node/services/events/ScheduledFlowTests.kt, node/src/test/kotlin/net/corda/node/services/transactions/ResolveStatePointersTest.kt, node/src/test/kotlin/net/corda/node/services/vault/VaultSoftLockManagerTest.kt, node/src/test/kotlin/net/corda/node/testing/MessageChainState.kt
The build logs are full of warnings about States not being correctly associated with their Contracts. Resolve the easy/obvious ones.
=> BUILD: Fix some warnings about @BelongsToContract in tests.

build.gradle, gradle.properties
* Properties in `gradle.properties` are Gradle properties and not Java system properties.
* Access Gradle properties via documented `property(String)` API.
* Put `test.parallel` check with the rest of the `Test` configuration.
* Disable Gradle's cache by default. It can be enabled on the command line for Team City.
=> BUILD: Resolve warnings with Gradle and system property API usage.

node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt, node/src/test/kotlin/net/corda/node/internal/CordaServiceTest.kt
This is regarding JIRA: [CORDA-2653](https://r3-cev.atlassian.net/browse/CORDA-2653).
During the initalisation of a `CordaService` if `Thread.currentThread().getContextClassLoader()` is `null`, certain third party libraries may fail to load. 
This fix ensures that a classloader is available during initialisation.
=> CORDA-2653 - during initialisation a Corda Service should have a thread context classloader

core/src/main/kotlin/net/corda/core/contracts/TransactionVerificationException.kt, core/src/test/kotlin/net/corda/core/contracts/TransactionVerificationExceptionSerialisationTests.kt
An exception intended for serialization needs to expose via publicly readable properties all of the values it requires to populate its constructor, or the custom ThrowableSerializer will fail (typically by trying to call that constructor reflectively, passing in a `null` where no null value is expected, and failing Kotlin's own null-check on the method).
Some of the newer `TransactionVerificationExceptions` don't do this, and don't get propagated properly to the RPC client as a result. This PR fixes that, unit tests the fix, and adds a comment explaining what needs to be done.
=> CORDA-2765 Make TransactionVerificationExceptions serializable

tools/cliutils/src/main/kotlin/net/corda/cliutils/CordaCliWrapper.kt
If an invalid command line option is specified and the parser is unable to parse the input, return an error code to the caller. This is useful in scripting scenarios where it might be important to detect that Corda failed to start due to invalid command line parameters.
=> ENT-3333: Return error code for invalid cmdline options

djvm/djvm/build.gradle, djvm/djvm/cli/build.gradle
Use `baseName` and `classifier` for `shadowJar` tasks to ensure that the artifacts are published to Maven with the correct names.
=> CORDA-2750: Fix published names for DJVM artifacts.

node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt
While the node is starting up, we now check for the presence of the certificates directory. This allows us to print out an easily understandable error message if the directory is not present. An exception is made for devMode, as devMode will result in the directory being created in any case.
=>  ENT-3327: Check for missing certificates directory

djvm/djvm/build.gradle, djvm/djvm/src/main/kotlin/net/corda/djvm/analysis/AnalysisConfiguration.kt, djvm/djvm/src/main/kotlin/net/corda/djvm/analysis/ClassResolver.kt, djvm/djvm/src/main/kotlin/net/corda/djvm/rewiring/ClassRewriter.kt, djvm/djvm/src/main/kotlin/net/corda/djvm/rewiring/SandboxClassLoader.kt, djvm/djvm/src/main/kotlin/net/corda/djvm/rewiring/SandboxClassWriter.kt, djvm/djvm/src/main/kotlin/net/corda/djvm/source/SourceClassLoader.kt, djvm/djvm/src/test/java/net/corda/djvm/execution/SandboxExecutorJavaTest.java, djvm/djvm/src/test/kotlin/net/corda/djvm/TestBase.kt, djvm/djvm/src/test/kotlin/net/corda/djvm/execution/SandboxExecutorTest.kt
Simplify the `SourceClassLoader` logic to make it easier for people to use DJVM as a library.
Removing `SandboxSourceClassLoader` means that we don't need `AbstractSourceClassLoader` any more either, leaving us with just `SourceClassLoader` again.
=> CORDA-2775: Simplify SourceClassLoader logic for DJVM.

core/src/main/kotlin/net/corda/core/flows/ReceiveTransactionFlow.kt
Clarify that a received transaction is only stored in the Vault when checkSufficientSignatures  is true.
=> CORDA-2762 Docs clarification in ReceiveTransactionFlow 

node/src/integration-test/kotlin/net/corda/node/persistence/FailNodeOnNotMigratedAttachmentContractsTableNameTests.kt, testing/node-driver/src/main/kotlin/net/corda/testing/driver/internal/DriverInternal.kt
* Ensure that this test stops nodes that it starts.
* Also ensure that random ephemeral ports can be reused.
It looks like the test doesn't fail per-se. Just that Gradle is left waiting indefinitely for it to complete properly, and then Team City kills the build when it eventually times out. This sounds like something isn't being closed down properly - try putting `nodeHandle.stop()` inside a `finally` block for starters. And setting `reuseAddress` on the ephemeral port that we want to grab can't hurt either.
=> BUILD: Try to fix flaky FailNodeOnNotMigratedAttachmentContractsTableNameTests.

core/src/main/kotlin/net/corda/core/internal/LazyStickyPool.kt
This PR addresses [CORDA-2772](https://r3-cev.atlassian.net/browse/CORDA-2772)
=> CORDA-2772 - fix edge case when `stickTo.hashCode` return `Int.MIN_VALUE`

samples/irs-demo/web/build.gradle
* Remove duplicate Gradle plugins and _Evil TAB_ characters.
* Use Spring's dependency management to ensure we use a uniform version of Log4J2.
=> BUILD: Tidy up Gradle for irs-demo:web.

node/src/main/resources/migration/common.changelog-init.xml
Liquibase initial migration shouldn't fail if hibernate_sequence is already created in the target database. To avoid this we use 'preConditions' check.
My PR is in accordance with the [Developer's Certificate of Origin](https://github.com/corda/corda/blob/master/CONTRIBUTING.md#developer-certificate-of-origin).
=>  Create hibernate_sequence database sequence object only if it doesn't exist

docs/README.md, docs/source/app-upgrade-notes.rst, docs/source/conf.py
Ok this change switches to a mechanism by which we replace the various versions of things in sphinx. The reason is so that we can do substitution inside code blocks.  The pros of this are that we can have nicely styled things and still do substitution.  The obvious downside is that we all think code blocks are sacrosanct!
I've attached a diff between the master and my branch diffs.
And screenshots of the new versions so that we can see they're ok.
If this is accepted I'm happy to go on a mission to replace all the <version> things we have with the relevant versions.
There only are 4 diffs, btw:
`
~/dev/corda/corda/docs   nimmaj/corda-2777-doc-subst  grep 'diff -r' ~/tmp/html.diffs 
diff -r /Users/nimmaj/tmp/html.master/_sources/app-upgrade-notes.rst.txt …
=> changing substitution mechanism so that it can work with code blocks

node/src/main/kotlin/net/corda/node/internal/CordaRPCOpsImpl.kt, node/src/main/kotlin/net/corda/node/services/statemachine/StaffedFlowHospital.kt
Normally, these requests are left unacknowledged in the MQ broker to allow recovery via installing the missing CorDapp. If this is not applicable then the request can be dropped (and the other side informed of the error).
=> CORDA-2683: Requests to start unknown flows can be deleted using killFlow

node/src/integration-test/kotlin/net/corda/node/services/statemachine/HardRestartTest.kt
The `HardRestartTest` is trying to reuse the same ports, over and over again. Use the global port allocator instead so that each test case will use different ports.
=> BUILD: Use global port allocator for flaky HardRestartTest.

client/rpc/src/smoke-test/kotlin/net/corda/kotlin/rpc/StandaloneCordaRPClientTest.kt, serialization-deterministic/src/main/kotlin/net/corda/serialization/internal/DefaultWhitelist.kt, serialization/src/main/kotlin/net/corda/serialization/internal/DefaultWhitelist.kt
https://r3-cev.atlassian.net/browse/CORDA-2782
Discussed preferred approach towards fixing the broken **serialization-deterministic** **_VerifyTransactionTest_** unit test which generates a binary file for a transaction and then attempts to verify this using the deterministic code. 
@r3domfox attempted to suppress the new _java.lang.Comparable_ default whitelisted type in the serializer schema generation but this caused a binary compatibility break. The simplest solution was to add the new _java.lang.Comparable_ whitelisted type to the equivalent deterministic default whitelist.
=> CORDA-2782 Add Comparable to default whitelist for vault query criteria using comparables

docs/source/api-scanner.rst, docs/source/api-testing.rst, docs/source/app-upgrade-notes.rst, docs/source/azure-vm.rst, docs/source/cli-application-shell-extensions.rst, docs/source/conf.py, docs/source/cordapp-build-systems.rst, docs/source/deploying-a-node.rst, docs/source/generating-a-node.rst, docs/source/network-bootstrapper.rst, docs/source/running-a-notary.rst, docs/source/testnet-explorer-corda.rst, docs/source/tutorial-cordapp.rst, docs/source/writing-a-cordapp.rst
post checkin to make substitutions work in code blocks, went through the code base and replaced static versions with the placeholders.
there was an error - one of the tables disappeared due to formatting issues so I've changed the way we do that table.  will go through the docs and remove all the warnings next I suspect...
- [docs, yes ] Have you run the unit, integration and smoke tests as described [here](https://docs.corda.net/head/testing.html)?
- [n/a ] If you added public APIs, did you write the JavaDocs?
- [n/a ] If the changes are of interest to application developers, have you added them to the [changelog](https://github.com/corda/corda/blob/master/docs/source/changelog.rst), and potentially the [release notes](https://github.com/corda/corda/blob/master/docs/source/release-notes.r …
=> corda-2781 replace manual versions with substitutions

node/src/main/kotlin/net/corda/node/NodeCmdLineOptions.kt
In response to [CORDA-2783](https://r3-cev.atlassian.net/browse/CORDA-2783):
If `devMode=true` is set in the config, and `devModeOptions.allowCompatibilityZone` isn't, the node would fail with an uninformative message `Failed requirement`. With this fix, the following output gets produced instead:
```
______               __
/ ____/     _________/ /___ _
/ /     __  / ___/ __  / __ `/         Computers are useless. They can only
/ /___  /_/ / /  / /_/ / /_/ /          give you answers.  -- Picasso
\____/     /_/   \__,_/\__,_/
--- Corda Open Source 5.0-SNAPSHOT (a1f7c4f) -------------------------------------------------------------
Logs can be found in                    : C:\Users\TommyLillehagen\IdeaProjects\test-node\logs
Cannot perform initial registration when 'devMode' is true, …
```
=> CORDA-2783 - Improve error message for initial registration with devMode=true

docs/source/generating-a-node.rst, docs/source/network-bootstrapper.rst, docs/source/testnet-explorer-corda.rst, docs/source/tutorial-cordapp.rst
Further clean-up after https://github.com/corda/corda/pull/4927
=> Fix incorrect version identifiers in URL's by adopting |corda_version| consistently.

client/rpc/src/smoke-test/kotlin/net/corda/kotlin/rpc/StandaloneCordaRPClientTest.kt, serialization-deterministic/src/main/kotlin/net/corda/serialization/internal/DefaultWhitelist.kt, serialization/src/main/kotlin/net/corda/serialization/internal/DefaultWhitelist.kt
Reverts corda/corda#4920
Caused serialisation issues which were evident both in our behave tests and also in performance tests.
Example:
`[WARN ] 2019-03-26T01:03:39,964Z [Thread-8 (ActiveMQ-client-global-threads)] rpc.RPCServer.clientArtemisMessageHandler - Inbound RPC failed [errorCode=bcgta6, moreInformationAt=https://errors.corda.net/OS/4.0/bcgta6] {actor_id=corda, actor_owning_identity=O=PartyA-f73e241b-2589-4ccb-b7d2-ce179a1904c7, L=London, C=GB, actor_store_id=NODE_CONFIG, invocation_id=155bf49f-3ecb-4593-8675-4d145fea8de3, invocation_timestamp=2019-03-26T01:03:39.963Z, origin=corda, session_id=a256d3a8-0522-40be-ab62-63811c7274f8, session_timestamp=2019-03-26T01:03:38.632Z}
java.io.NotSerializableException: Class "java.lang.Comparable<net.corda.core.contracts.Amount<*>>" is not on …
=> CORDA-2782 REVERT - Add Comparable to default whitelist for vault query criteria using comparables"

core/src/main/kotlin/net/corda/core/transactions/LedgerTransaction.kt, node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt
see https://r3-cev.atlassian.net/browse/CORDA-2615
This PR:
1. catch serialisation exceptions during tx resolution and consider those states irrelevant for the vault.
2. move a Ledger transaction check from the constructor to the verify method.
=> CORDA-2615 - add fix for serialization failure on relevancy check.

node/src/integration-test/kotlin/net/corda/node/internal/subcommands/InitialRegistrationCliTest.kt, node/src/main/kotlin/net/corda/node/internal/subcommands/InitialRegistrationCli.kt, node/src/test/kotlin/net/corda/node/internal/subcommands/InitialRegistrationCliTest.kt
This changes slightly the registration process, so that it fails fast, in case there's existing state from previous runs (artemis files, DB tables etc.). 
* Added some unit tests for the cases introduced
* Also, tested it manually, performing a registration twice (using H2 / postgreSQL) on a node
=> [CORDA-2647] - Prevent registration when previous state exists

docs/source/api-contract-constraints.rst, docs/source/changelog.rst, docs/source/cli-ux-guidelines.rst, docs/source/corda-network/index.md, docs/source/cordapp-build-systems.rst, docs/source/design/data-model-upgrades/migrate-to-signature-constraint.md, docs/source/design/linear-pointer/design.md, docs/source/design/monitoring-management/design.md, docs/source/design/sgx-infrastructure/details/attestation.md, docs/source/design/versioning/contract-versioning.md, docs/source/network-bootstrapper.rst, docs/source/node-administration.rst, docs/source/node-commandline.rst
This gets rid of a lot of the html docs warnings.  Left to do (in another issue):
* fix latex warnings
* fix the ``WARNING: Could not lex literal_block as "kotlin". Highlighting skipped.`` type issues (requires a fix to the payments Kotlin lexer)
* fix the dedent issues
* fix the docs build docs which I suspect are somewhat out of date
- [docs] Have you run the unit, integration and smoke tests as described [here](https://docs.corda.net/head/testing.html)?
- [n/a ] If you added public APIs, did you write the JavaDocs?
- [n/a ] If the changes are of interest to application developers, have you added them to the [changelog](https://github.com/corda/corda/blob/master/docs/source/changelog.rst), and potentially the [release notes](https://github.com/corda/corda/blob/master/docs/source/release- …
=> CORDA-2787 docs warnings

docs/source/api-persistence.rst, docs/source/building-a-cordapp-index.rst, docs/source/conf.py, docs/source/design/design-docs-index.rst, docs/source/index.rst, docs/source/key-concepts-vault.rst, docs/source/key-concepts.rst, docs/source/node-internals-index.rst
Minor re-structuring to include:
- Corda API link moves to top-level (near top)
- Cheatsheet moves to top-level
- Design documents grouped under sub-header in Contributions
- Vault / Soft-locking moved to key concepts
- added toc entries for missing references as reported by `WARNING: document isn't included in any toctree`
=> Minor tweaks and improvements in docs TOC to aid navigation and access.

core-deterministic/build.gradle, core/build.gradle
We have already upgraded Hibernate from 5.2.6 to 5.3.6, and Hibernate 5.3.x uses JPA 2.2. We should therefore upgrade Corda to use the JPA 2.2 annotations as well.
=> CORDA-2804: Replace JPA 2.1 annotations with JPA 2.2.

tools/demobench/package-demobench-exe.bat, tools/demobench/package/bugfixes/apply.bat
Specify paths to build tools correctly or else bugfixes will not applied.
(cherry picked from commit 4cc4e3f01bd95c9454b3487d6e1f29b53aace077)
This is not essential for 3.4 release, but helps a lot when building DemoBench installer on Windows.
=> RELEASE - Fix DemoBench Windows installer (#3451)

client/rpc/src/main/kotlin/net/corda/client/rpc/CordaRPCClient.kt, docs/source/cordapp-custom-serializers.rst, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/AMQPSerializationScheme.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/DriverDSLImpl.kt
With the recent changes in C4, the AMQP system property is effectively not used anymore, since Cordapps are loaded as attachments & the RPC client scans the classpath for any custom serializers/whitelists. This change removes this property and the scanning performed in `AbstractAMQPSerializationScheme` which is dead code currently, in an effort to simplify this part of the code base a bit.
Refer to the JIRA for more details.
=> [CORDA-2473] - Remove AMQP system property

docs/source/api-flows.rst, docs/source/node-flow-hospital.rst
https://r3-cev.atlassian.net/browse/CORDA-2780
This PR reverts back some documentation that was deleted with additional improvements, including the Flow Hospital document added to Enterprise (https://github.com/corda/enterprise/pull/1928) but stripped of its Enterprise-only UI visualization section.
=> CORDA-2780 Document FinalityFlow error handling logic and reference flow hospital

core/src/main/kotlin/net/corda/core/flows/FinalityFlow.kt, core/src/test/kotlin/net/corda/core/flows/FinalityFlowTests.kt, docs/source/versioning.rst
In Corda 4, `FinalityFlow` was updated to become an initiated flow, in order to ensure a node does not have to accept any signed transaction it receives without being able to check it first. The old behaviour of `FinalityFlow` was gated behind a `targetPlatformVersion` check, to prevent apps targeting V4 from using the old behaviour.
This is problematic for a few reasons. For an app wishing to be backwards compatible with a version running on V3, this forces the app to set `targetPlatformVersion = 3`, even if the app is thoroughly tested against V4. This goes against the purpose of the `targetPlatformVersion`. Another consequence is that an app remains pinned to `targetPlatformVersion = 3` until it is sure that there are no other apps running at a lower version in the network, which would …
=> [CORDA-2784] Remove targetPlatformVersion check from FinalityFlow

node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/CordaPersistence.kt, node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
Retries can lead to confusing error messages in case the CFT notary is
misconfigured and throws a SQLException causing a retry.
=> [CORDA-2807] Don't retry db transaction in AbstactNode start

serialization/src/main/kotlin/net/corda/serialization/internal/amqp/SerializationHelper.kt, serialization/src/test/kotlin/net/corda/serialization/internal/amqp/DeserializeSimpleTypesTests.kt
Because vault queries have properties of type `Comparable<T>`, and the default whitelist used in RPC serialisation does not include `Comparable`. we need to make special exception for `Comparable` when checking against the whitelist. (The alternative approach of adding `Comparable` to the default whitelist was tried, but amounted to a wide-ranging change in what gets sent on the wire during RPC serialisation, which caused breakages elsewhere).
This was not an issue in Corda OS v3 because Kryo serialisation was used for RPC.
=> CORDA-2782 allow un-whitelisted Comparable

docs/make-docsite.sh
Candidly this is a bit of a nightmare.
The error file is currently over 7000 lines and no-one is looking at it.
Lots of the errors are things like "the reference doesn't exist" but we actually expect this in the first couple of passes through by the converter.
Given that we are actively missing real errors (like tables disappearing) in the html pages, in the noise of the latex build, I propose we:
* basically hide the latex/pdf errors
* fix the rest of the html errors
* fail the build if the html docs error
In this way we will notice errors and those that we see we know we need to fix.
This PR represents turning off the latex warnings.
- [docs ] Have you run the unit, integration and smoke tests as described [here](https://docs.corda.net/head/testing.html)?
- [ n/a] If you added public …
=> CORDA-2809 - reduce latex/pdf erros

node/src/main/kotlin/net/corda/node/internal/DbExceptionHandler.kt, node/src/main/kotlin/net/corda/node/internal/Node.kt, node/src/main/kotlin/net/corda/node/services/statemachine/FlowStateMachineImpl.kt, node/src/main/kotlin/net/corda/node/services/statemachine/SingleThreadedStateMachineManager.kt, node/src/main/kotlin/net/corda/node/utilities/errorAndTerminate.kt
Add DbException handler to terminate process when the DB goes away or gives up.
Also add a helper to terminate the node and use it instead of calling Runtime.halt() in random places.
=> CORDA-2813 Handle loss of database

.ci/api-current.txt, core/src/main/kotlin/net/corda/core/concurrent/CordaFuture.kt, core/src/main/kotlin/net/corda/core/contracts/ContractAttachment.kt, core/src/main/kotlin/net/corda/core/contracts/TransactionVerificationException.kt, core/src/main/kotlin/net/corda/core/crypto/CompositeKey.kt, core/src/main/kotlin/net/corda/core/crypto/NullKeys.kt, core/src/main/kotlin/net/corda/core/internal/ResolveTransactionsFlow.kt, core/src/main/kotlin/net/corda/core/serialization/SerializationAPI.kt, core/src/main/kotlin/net/corda/core/transactions/SignedTransaction.kt, core/src/main/kotlin/net/corda/core/utilities/ByteArrays.kt, node/src/main/kotlin/net/corda/node/services/persistence/NodeAttachmentService.kt, node/src/main/kotlin/net/corda/node/utilities/registration/NetworkRegistrationService.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/CustomSerializerRegistry.kt, serialization/src/test/kotlin/net/corda/serialization/internal/amqp/CustomSerializerRegistryTests.kt
Backport from Enterprise of:
[ENT-3440](https://r3-cev.atlassian.net/browse/ENT-3440) Allow custom serializers that extend CordaThrowable
[ENT-3121](https://r3-cev.atlassian.net/browse/ENT-3121) restrict custom serializers
=> (BACKPORT) ENT-3121 restrict custom serializers

docs/source/api-contract-constraints.rst
Code for these docs had the java and kotlin samples but were not combined into a single codeset with tabs for each language.
=> Tidy up codesets in contract constraints documentation

docs/source/tutorial-cordapp.rst
Adding guidance for mac users when using the `runnodes` task as it fails to start nodes when they're opened in separate windows.
=> Willh docupdate

node/src/test/kotlin/net/corda/node/services/statemachine/RetryFlowMockTest.kt
The default 5-second timeout for `eventually` isn't always sufficient for `RetryFlowMockTest.Restart does not set senderUUID` to complete its work, so we extend it to 30 seconds, with a 100ms retry interval.
=> CORDA-2827 extend timeout on test

docs/source/tutorial-test-dsl.rst
Update the contract testing documentation in `tutorial-test-dsl` to include the addition of `ledgerServices` / `MockServices` to the java sample. Also add a setup section to the docs.
=> CORDA-2528 Update contract testing documentation

serialization/src/main/kotlin/net/corda/serialization/internal/amqp/EvolutionSerializerFactory.kt
This PR reformats the `EvolutionSerializationException` to print the type name and reason for serialization failure before the full type information. This ensures the problem is the first thing displayed in the error message.
An example of the new format:
```
Caused by: net.corda.core.node.services.VaultQueryException: An error occurred w
hile attempting to query the vault: Failed to deserialise group OUTPUTS_GROUP at
index 0 in transaction:       Cannot construct evolution serializer for remote
type net.corda.examples.obligation.contract.Obligation: Mandatory property defau
lted of local type is not present in remote type. This implies the type has not
evolved in a backwards compatible way. Consider making defaulted nullable in the
newer version of this type.
Full type information: …
```
=> [CORDA-2633] Restructure EvolutionSerializationException to print failure reason first

common/logging/build.gradle, common/logging/src/main/kotlin/net/corda/common/logging/CordaVersion.kt, common/logging/src/main/kotlin/net/corda/common/logging/ErrorCodeRewritePolicy.kt, common/logging/src/main/kotlin/net/corda/common/logging/ExceptionsErrorCodeFunctions.kt, config/dev/log4j2.xml, node/build.gradle, node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt, settings.gradle, testing/test-common/build.gradle, testing/test-common/src/main/resources/log4j2-test.xml, tools/blobinspector/build.gradle, tools/bootstrapper/build.gradle, tools/cliutils/build.gradle, tools/cliutils/src/main/kotlin/net/corda/cliutils/CordaVersionProvider.kt, tools/cliutils/src/main/kotlin/net/corda/cliutils/ErrorCodeRewritePolicy.kt, tools/cliutils/src/main/kotlin/net/corda/cliutils/ExceptionsErrorCodeFunctions.kt, tools/cliutils/src/main/kotlin/net/corda/cliutils/InstallShellExtensionsParser.kt, tools/explorer/build.gradle, tools/explorer/src/main/kotlin/net/corda/explorer/ui/AdvancedExceptionDialog.kt, tools/explorer/src/main/kotlin/net/corda/explorer/views/LoginView.kt, tools/shell-cli/build.gradle, webserver/build.gradle
Changed the dialog used for exception handling in the login view from the default ExceptionDialog which always shows a stack trace to a custom Dialog that won't show stack trace unless asked to. RPC exceptions won't show a stack trace as from my understanding running through the code that throws them, they are either network or protocol issues, thus there isn't much point. Other exceptions that reach the catch will still be shown. The Dialog should display a hyperlink to whatever is generated by errorCodeUrl() extension function. (Only tested that it works on mac) 
CordaVersionProvider now contains a CordaVersion, so that the error url generation logic could be moved to a different library, because CordaVersionProvider extends some  third party module interface and there is no point in …
=> CORDA-2586 explorer exception handling

core/src/main/kotlin/net/corda/core/internal/cordapp/CordappImpl.kt, node/src/test/kotlin/net/corda/node/internal/cordapp/JarScanningCordappLoaderTest.kt
This change includes the actual whitelisted classes in the set of all classes of a cordapp.
* Added a unit test that was previously failing, because the name of the `CordappImpl` was added, instead of the actual set of whitelisted classes.
=> [CORDA-2851] - Fix the way serialization whitelist is calculated for CordappImpl

core/src/main/kotlin/net/corda/core/contracts/TransactionVerificationException.kt, core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt, node/src/main/kotlin/net/corda/node/services/statemachine/FlowStateMachineImpl.kt, node/src/main/kotlin/net/corda/node/services/statemachine/StaffedFlowHospital.kt, node/src/main/kotlin/net/corda/node/services/statemachine/interceptors/DumpHistoryOnErrorInterceptor.kt
Error reporting around flow failures can be difficult to parse, owing to the error being buried within a lot of other information. This PR makes a few tweaks that aim to improve the clarity of error messages, reduce the amount of duplicate information, and move some of the more verbose logging to lower logging levels.
Changes:
- In `StaffedFlowHospital`, reword the log that prints each error for a flow to make it clear that (possibly) multiple errors are being printed. Additionally, remove extra information that is printed in the logging context, and promote the log to warn. This is where the exception traceback is printed.
- In `FlowStateMachineImpl`, remove a duplicate printing of the exception traceback
- In `AttachmentsClassloader`, add a log at the point where an unverified …
=> [CORDA-2522] Improve error reporting around failed flows

docs/docs_builder/lexer-fix/.gitignore, docs/docs_builder/lexer-fix/Dockerfile, docs/docs_builder/lexer-fix/jvm.py, docs/docs_builder/lexer-fix/readme.md, docs/docs_builder/lexer-fix/test_kotlin.py, docs/requirements.txt, docs/source/app-upgrade-notes.rst, docs/source/conf.py, docs/source/contract-upgrade.rst, docs/source/contributing-flow-state-machines.rst, docs/source/contributing.rst, docs/source/corda-configuration-file.rst, docs/source/corda-nodes-index.rst, docs/source/demobench.rst, docs/source/deploying-a-node.rst, docs/source/deterministic-modules.rst, docs/source/example-code/src/main/kotlin/net/corda/docs/kotlin/tutorial/twoparty/IOUFlowResponder.kt, docs/source/flow-overriding.rst, docs/source/hello-world-running.rst, docs/source/key-concepts-djvm.rst, docs/source/loadtesting.rst, docs/source/node-administration.rst, docs/source/release-notes.rst, docs/source/running-a-node.rst, docs/source/testnet-explorer-corda.rst, docs/source/tut-two-party-flow.rst, docs/source/tutorial-attachments.rst, docs/source/tutorial-custom-notary.rst, docs/source/tutorial-test-dsl.rst, docs/source/writing-a-cordapp.rst
Got rid of most of the remaining docs build warnings.  There are a few left that we need to talk through (e.g. the latex build has links to docs we have excluded from it in the design section, some broken internal links etc).
In this checkin are:
* some cleanups of the rst files that help to remove warnings
* a change to the latest version of Pygments (the basis for the below)
* I've attached a fixed Kotlin lever (and tests) that can lex all the Kotlin it needs to now
* NB I've uploaded a new version of the docs builder image to docker hub with this new version built in
* I will separately try and get the Kotlin lexer changes accepted into Pygments properly
Thanks
- [docs ] Have you run the unit, integration and smoke tests as described [here](https://docs.corda.net/head/testing.html)?
- …
=> CORDA-2810 - more doc build cleanups

serialization/src/main/kotlin/net/corda/serialization/internal/model/TypeModellingFingerPrinter.kt, serialization/src/test/kotlin/net/corda/serialization/internal/amqp/TypeModellingFingerPrinterTests.kt
The fingerprinter will refuse to fingerprint any type that is not serializable; however, sometimes types are mentioned (as type parameters) but never used (as the types of concrete property values), and in these cases it is premature to throw an exception during fingerprinting. Instead, we should fingerprint any non-serializable type's publicly readable properties, along with its interfaces and type parameters, just as we would if it were an abstract type.
This is the behaviour of the v3 fingerprinter, which some CorDapps depend on, so we must revert to it.
=> CORDA-2848 relax fingerprinter strictness

node-api/src/main/kotlin/net/corda/nodeapi/internal/cryptoservice/SupportedCryptoServices.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/cryptoservice/bouncycastle/BCCryptoService.kt, node-api/src/test/kotlin/net/corda/nodeapi/internal/cryptoservice/bouncycastle/BCCryptoServiceTests.kt, node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt, node/src/main/kotlin/net/corda/node/services/config/ConfigUtilities.kt, node/src/main/kotlin/net/corda/node/services/config/NodeConfiguration.kt, node/src/main/kotlin/net/corda/node/services/keys/E2ETestKeyManagementService.kt, node/src/main/kotlin/net/corda/node/utilities/registration/NetworkRegistrationHelper.kt, node/src/test/kotlin/net/corda/node/services/keys/cryptoservice/BCCryptoServiceTests.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/InternalMockNetwork.kt
The crypto service implementation is currently in the Node module. The firewall product needs access to these implementations, but it should not depend on the node module for this. So the plan is to move the crypto service implementations to the node api which the firewall product has access to. The same change is being made in this OS branch for consistency - although this branch wont have the HSM implementations.
Note as part of this change the certificateStore property has been made public
=> ENT-3482: Move BC crypto service implementation to node api.

node/src/main/kotlin/net/corda/node/services/statemachine/StaffedFlowHospital.kt, node/src/main/kotlin/net/corda/node/services/statemachine/interceptors/DumpHistoryOnErrorInterceptor.kt
The previous PR (#5000) ended up getting reviewed at the same time that it got merged, resulting in a few pieces of tidying up that didn't find their way into master. This PR addresses those issues:
- Change a warning back to info, as it has been pointed out that the error condition has been logged elsewhere.
- `FinalityDoctor` now reports the error message stack trace, as this is the point with the most context about the problem
- Use the Corda provided `debug` utility where appropriate
- Remove some other `flowFiber.id`s that should be in the logging context
=> [CORDA-2522] Follow up changes to error reporting around failed flows

docs/source/upgrading-cordapps.rst
This PR just touches only the explicit upgrade part.
This document needs some overall rethinking.
=> CORDA-2456: Documentation around explicit upgrades

serialization/src/main/kotlin/net/corda/serialization/internal/amqp/EvolutionSerializerFactory.kt
This is a backport of CORDA-2633 to release/4.
=> CORDA-2633 Restructure evolution serialization errors to print reason first

client/jfx/src/main/kotlin/net/corda/client/jfx/model/NetworkIdentityModel.kt, client/jfx/src/main/kotlin/net/corda/client/jfx/model/NodeMonitorModel.kt, client/jfx/src/main/kotlin/net/corda/client/jfx/model/TransactionDataModel.kt, samples/bank-of-corda-demo/src/main/kotlin/net/corda/bank/api/BankOfCordaClientApi.kt, tools/explorer/src/main/kotlin/net/corda/explorer/model/IssuerModel.kt, tools/explorer/src/main/kotlin/net/corda/explorer/views/cordapps/cash/NewTransaction.kt, tools/shell-cli/src/main/kotlin/net/corda/tools/shell/StandaloneShell.kt, tools/shell/src/main/kotlin/net/corda/tools/shell/InteractiveShell.kt, webserver/src/main/kotlin/net/corda/webserver/internal/NodeWebServer.kt
This PR creates a sample wrapper over `CordaRPCOps` that is able to reconnect on any connection exceptions and is also returning `DataFeed` Observables that are able to reconnect.
This wrapper also provides a method to start flows with a logical retry condition, that would guarantee that  this flow will be run even when the underlying node is flaky.
This wrapper is thoroughly tested with a test that randomly kills the node, stops it, kills the connection and introduces random latencies.
=> CORDA-2858: Wire-up node components with better RPC reconnect logic

docs/source/getting-set-up.rst
Raised to address https://r3-cev.atlassian.net/browse/CORDA-2602 . 
Remove some information that is way to specific for installing the
oracle jdk.
Specify that the docs will go through how to install the oracle jdk
only but provide links to amazon corretto and openjdk.
Also say that we support intellij 2019 which has been released now.
=> CORDA-2602 Update getting setup guide java details

finance/workflows/src/integration-test/kotlin/net/corda/finance/workflows/CashExceptionSerialisationTest.kt, node/src/integration-test/kotlin/net/corda/node/services/rpc/RpcExceptionHandlingTest.kt, node/src/main/kotlin/net/corda/node/internal/rpc/proxies/ExceptionSerialisingRpcOpsProxy.kt
Raised to resolve https://r3-cev.atlassian.net/browse/CORDA-2645
`ExceptionSerialisingRpcOpsProxy` was removing information about the original exception in dev mode. This code has been removed. Although there is no check in `ExceptionSerialisingRpcOpsProxy` for dev mode (and also due to it being about serialising), `ExceptionMaskingRpcOpsProxy` will handle the removal of exception data in non dev mode (production mode)
=> CORDA-2645 Remove dev mode rpc exception swallowing

docs/source/example-code/src/main/java/net/corda/docs/java/tutorial/twoparty/IOUFlowResponder.java, docs/source/example-code/src/main/kotlin/net/corda/docs/kotlin/tutorial/twoparty/IOUFlowResponder.kt, docs/source/tut-two-party-flow.rst
- `DOCSTART`s were not in sync
- Incorrect indentation
- Documentation not very clear
=> Fix tut-two-party-flow kotlin docs + make both versions easier to read

docs/source/api-contract-constraints.rst
Fixing a small typo. Docs should say @BelongsToContract not @BelongToContract
=> Typo - should be @BelongsToContract not @BelongToContract

docs/source/example-code/src/main/java/net/corda/docs/java/tutorial/twoparty/IOUFlowResponder.java, docs/source/example-code/src/main/kotlin/net/corda/docs/kotlin/tutorial/twoparty/IOUFlowResponder.kt, docs/source/tut-two-party-flow.rst
(#5024)
- `DOCSTART`s were not in sync
- Incorrect indentation
- Documentation not very clear
(cherry picked from commit 360660e4d77ab17b68617f8d9c46fab451890cbe)
=> Backport - Fix tut-two-party-flow kotlin docs + make both versions easier to read

client/rpc/src/main/kotlin/net/corda/client/rpc/internal/ReconnectingCordaRPCOps.kt, node/src/integration-test/kotlin/net/corda/node/services/rpc/RpcReconnectTests.kt
This change should make the test less flaky.
=> Tweak RPC reconnecting test. Adjust the exponential retry factor.

node/src/main/kotlin/net/corda/node/services/messaging/P2PMessagingClient.kt
PR to backport fix for CORDA-2861. 
Master PR is https://github.com/corda/corda/pull/5031
=> CORDA-2861: give the message executor its own artemis session and producer

serialization/src/main/kotlin/net/corda/serialization/internal/amqp/PropertyDescriptor.kt, serialization/src/main/kotlin/net/corda/serialization/internal/model/LocalTypeInformationBuilder.kt, serialization/src/test/kotlin/net/corda/serialization/internal/SetsSerializationTest.kt, serialization/src/test/kotlin/net/corda/serialization/internal/model/LocalTypeModelTests.kt
Backport of CORDA-2860
* CORDA-2860 relax property type checking
* Remove redundant check
* Unit test
* Comment linking ticket to test
* More descriptive comment
* Fix test that was broken by jacocoData field being silently added to class
* Revert to previous behaviour around opaques, suppress validation
=> CORDA-2860 relax property type checking (#5028)

node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt
- If logs directory in corda base directory is a soft link to some other existing director, it does not work in Corda 4.
- This corda is a fix to allow such soft links to work.
- Have test the code, it works.
- Tried]$ ./gradlew   samples:trader-demo:deployNodes
- Got a working node -- Test passed.
=> CORDA-2862: Fix to allow softlinks of logs directory

core/src/main/kotlin/net/corda/core/flows/FlowException.kt, node/src/main/kotlin/net/corda/node/services/statemachine/FlowStateMachineImpl.kt, node/src/main/kotlin/net/corda/node/services/statemachine/transitions/DeliverSessionMessageTransition.kt, node/src/test/kotlin/net/corda/node/services/statemachine/FlowFrameworkTests.kt
When an exception is thrown the receiving party / counter flow will receive the `FlowException` with an altered message indicating it has come from the sending party / counter flow.
Locally the thrown exception will remain the same.
=> CORDA-2572 Alter the message of a `FlowException` on receiving side

docker/src/bash/generate-config.sh, docker/src/bash/run-corda.sh, docker/src/docker/Dockerfile, docker/src/docker/DockerfileAL, docker/test-docker.sh
#4954 
* Changes made as per issue.
* Truststore proposal not implemented.  More design discussions required first.
* EXPOSE left in to improve maintainability.
_tests completed_ 
* New `test-docker.sh` script added to ensure docker image works.
* Regression tested against last release (4.0) and latest snapshot (20190329190533).
* Tests run against images created with `./gradlew buildOfficialCorrettoDockerImage  buildOfficialZuluDockerImage`
```bash
./test-docker.sh corda/corda-zulu-4.0:RELEASE
TEST-IMAGE-corda/corda-zulu-4.0:RELEASE: SUCCESS : Succesfully registered with http://localhost:8080
TEST-IMAGE-corda/corda-zulu-4.0:RELEASE:  SUCCESS : Node started up and registered
./test-docker.sh corda/corda-zulu-5.0-snapshot:20190329190533 …
```
=> CORDA-4954 : Improvements to docker image : compatible with v3.3; image size; truststore

samples/irs-demo/cordapp/workflows-irs/build.gradle
`compileOnly` instead of `cordaCompile` should be used as per https://docs.corda.net/cordapp-build-systems.html#corda-dependencies
The irs-demo uses `cordaCompile` to bring in the `node` module. This has been changed to `compileOnly`.
=> Use `compileOnly` instead of `cordaCompile` in irs-demo to depend on `node` module

client/rpc/src/main/kotlin/net/corda/client/rpc/internal/ReconnectingCordaRPCOps.kt
This addresses the (one?) cause of flakyness for the RpcReconnectTest.
see https://r3-cev.atlassian.net/browse/CORDA-2886
=> CORDA-2886 - Better handling of authentication error when re-connecting to RPC in RpcReconnectTest

core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt, samples/simm-valuation-demo/contracts-states/src/main/kotlin/net/corda/vega/plugin/customserializers/UnusedFinanceSerializers.kt
see https://r3-cev.atlassian.net/browse/CORDA-2847
Improve `addMissingDependencies`   and log better error message in case of unknown error.
Added a couple of serializers to the the simm valuation demo that would break without this fix.
=> CORDA-2847 - Improve addMissingDependencies

client/jackson/src/main/kotlin/net/corda/client/jackson/StringToMethodCallParser.kt, tools/shell/src/main/kotlin/net/corda/tools/shell/InteractiveShell.kt
Added a catch clause for the specific case of StringToMethodCallParser.UnparseableCallException.FailedParse which is only thrown during argument parsing.
CORDA-2632
=> CORDA-2632 Handle exceptions when file does not exist.

finance/workflows/src/main/kotlin/net/corda/finance/workflows/asset/CashUtils.kt
This one replaces #5047 which touches too many unnecessary files. We only need to change one file CashUtils.kt. 
Mike,
Can we add a flag to the generateSpend functions in CashUtils to indicate whether or not to use CI for the party who is going to receive the change? Default to true so this change won't impact existing usages.
We have disabled the CA function of our node certs so the current generateSpend which uses CI exclusively would fail for our use case. Providing that flag will give the developer the tool to override that behavior.
That way, we don't have to fork away the Corda codebase.
=> CashUtils.generateSpend: add anonymous flag, default to true

node-api/src/main/kotlin/net/corda/nodeapi/internal/cryptoservice/CryptoService.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/cryptoservice/bouncycastle/BCCryptoService.kt, node-api/src/test/kotlin/net/corda/nodeapi/internal/cryptoservice/bouncycastle/BCCryptoServiceTests.kt
The CryptoService interface exposes a sign operation, however there is no way to specify the signature scheme when signing. Currently when signing the private key is used to select the signature scheme. With this PR it will be possible to select the signature scheme when signing.
=> CORDA-2882: Added ability to specify signature scheme when signing.

client/jackson/src/main/kotlin/net/corda/client/jackson/StringToMethodCallParser.kt, client/jackson/src/main/kotlin/net/corda/client/jackson/internal/CustomRPCSerializationJacksonModule.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/cordapp/CustomRPCSerializationJacksonModule.kt, tools/shell/src/integration-test/kotlin/net/corda/tools/shell/InteractiveShellIntegrationTest.kt, tools/shell/src/main/kotlin/net/corda/tools/shell/CordaAuthenticationPlugin.kt, tools/shell/src/main/kotlin/net/corda/tools/shell/CordaSSHAuthInfo.kt, tools/shell/src/main/kotlin/net/corda/tools/shell/InteractiveShell.kt
see https://r3-cev.atlassian.net/browse/CORDA-2773
Added an internal class that extends the Jackson SimpleModule which will get autodiscovered and autowired into the RPC ObjectMapper
=> CORDA-2773 Add support for Custom RPC Jackson serializers

docker/build.gradle
Changed the buildDockerFolder to use the corda artifact for the current project.version. Still packages the built config-exporter from shadowJar.
=> CORDA-2884 - Docker build tasks will pull the corda jar from artifactory.

core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt, docs/source/cordapp-constraint-migration.rst, node/src/integration-test/kotlin/net/corda/contracts/SignatureConstraintVersioningTests.kt
If a single whitelisted constraint is being used by input states and the version of the cordapp changes + is signed, then the constraint will transition to a signature constraint.
Tests were taken from another pr that was started (https://github.com/corda/corda/pull/4596)
Created to resolve - https://r3-cev.atlassian.net/browse/CORDA-2280
=> CORDA-2280 Automatic propagation of whitelisted to Signature Constraints

core/src/main/kotlin/net/corda/core/contracts/AttachmentConstraint.kt, core/src/main/kotlin/net/corda/core/internal/JarSignatureCollector.kt, docs/source/api-contract-constraints.rst, docs/source/app-upgrade-notes.rst, docs/source/versioning.rst, testing/test-utils/src/test/kotlin/net/corda/testing/core/JarSignatureCollectorTest.kt
Opened to resolve - https://r3-cev.atlassian.net/browse/CORDA-2477
The Signature Constraint documentation in `api-contract-constraints` was very limited and referred to the design doc for most information. Information was extracted from the design doc and added to the main documentation.
- Reorder the documentation in `api-contract-constraints`
- Add further information on Signature Constraints
- Add code examples for using Contract Constraints with
  `TransactionBuilder`
- Correct some links from other docs
- General tidy up documentation
Note there is no mention of `devMode=true` ignoring missing signatures since this has not been implemented and is unlikely to do so in the future.
Link to the new Signature Constraint docs instead of the design doc in
the code.
=> CORDA-2477 Improve Signature Constraints documentation

node/src/integration-test/kotlin/net/corda/contracts/SignatureConstraintVersioningTests.kt
A test was failing due to `assumeFalse` (to stop a test running on windows)
being inside of a `assertThatExceptionOfType` block. The exception it
threw was consumed by the block instead of junit.
=> CORDA-2280 Fix build - Move `assumeFalse` in `SignatureConstraintVersioningTests`

core/src/main/kotlin/net/corda/core/contracts/AttachmentConstraint.kt, core/src/main/kotlin/net/corda/core/internal/JarSignatureCollector.kt, docs/source/api-contract-constraints.rst, docs/source/app-upgrade-notes.rst, docs/source/versioning.rst, testing/test-utils/src/test/kotlin/net/corda/testing/core/JarSignatureCollectorTest.kt
The Signature Constraint documentation in `api-contract-constraints`
was very limited and referred to the design doc for most information.
Information was extracted from the design doc and added to the main
documentation.
(cherry picked from commit cb85dd1e927f1bdd42ba483f53191f8be2ed4722)
Backporting in relation to - https://r3-cev.atlassian.net/browse/CORDA-2477
=> Backport CORDA-2477

docker/build.gradle
Fixed docker to use artifactory so that hashes will be the same for the release jar and the jar inside the container.
=> CORDA-2884 - Make docker images use artifactory corda version rather than a rebuilt version

docs/source/api-service-classes.rst, docs/source/corda-api.rst
There was no documentation added around creating your own service class. Therefore documentation on the subject has been added, which is currently placed in the Corda API section of the docs.
=> Add documentation on Corda Services / Service classes

node/src/test/kotlin/net/corda/node/internal/CordaServiceTest.kt
I couldnt find any other servicehub functions that were not using transactions from the testing i did. The only ones that weren't were `jdbcSession` and `withEntityManager`.
After talking to Tudor and Stefano, I get the impression that there shouldn't really be any situations where devs are calling code inside of a service that don't already have a db transaction (provided by a flow or trackby). Therefore the only other situation where devs can do this is in the constructor of the service itself. 
This situation is already handled with a db transaction. Therefore only tests were added.
* Add tests to check that `jdbcSession` and `withEntityManager` work inside of Corda Service constructors using the db transaction provided by the `AbstractNode`s initialisation code.
=> CORDA-825 Test jdbc session and entity manager in corda service constuctors

core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/AMQPExceptions.kt
Fix for: https://r3-cev.atlassian.net/browse/CORDA-2863
1. Remove  "helpful" debug message from "ClassNotFoundException" and "NoClassDefFoundError".
2. Small tweak for retrieving the root "ClassNotFoundException"
=> CORDA-2863 Fix ClassNotFound handling

docker/src/bash/generate-config.sh
modify run logic so that if node config is present, do not generate a new one
=> CORDA-2888 Allow bring-your-own-config to docker image

docker/src/bash/run-corda.sh, docs/source/docker-image.rst
Added a command line argument for corda.jar when there is no dataSourceProperties in the node.conf file which was mounted for the container.
=> CORDA-2888 change default dataSource.url to match the docker container structure.

docs/build.gradle
jackson-core api is on version 2.9.  Catching up the link in the documentation to reflect this.
=> updated jackson-core api documentation to 2.9

core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
To allow better usage in Java, a new `addOutputState` overload has
been added.
It does not use the `@JvmOverloads` annotation as other overloads
already provide the same functionality.
Tidied up the `requireNotNull` code that was duplicated between the
overloads and moved to `requireNotNullContractClassName`.
=> CORDA-2892 Add a `TransactionBuilder.addOutputState` overload

build.gradle, node-api/src/main/kotlin/net/corda/nodeapi/internal/protonwrapper/engine/ConnectionStateMachine.kt
This moves to a more recent version of proton-J which won't be flagged by CVE scanners (we never used the suspect functionality TLS anyway). Also, moves to the more efficient API for parsing streamed AMQP buffers.
=> CORDA-2856: Update the proton-j library to latest version

docs/source/changelog.rst, docs/source/generating-a-node.rst, node-api/build.gradle, node-api/src/main/kotlin/net/corda/nodeapi/internal/network/NetworkBootstrapper.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/network/NetworkParameterOverridesSpec.kt
[CORDA-2491](https://r3-cev.atlassian.net/browse/CORDA-2491)
- Added a new entrypoint for `CordFormation` plugin, with a an additional `String` for extra configuration options. It should be generic enough to pass HOCON representations, not only for networkParameter overrides, but other extra configurations options we might want to pass.
- Moved `NetworkParameterOverridesSpec` from `bootstrapper` to `node-api` to avoid circular dependencies and provide means to validate the HOCON objects passed to the entrypoint.
- Widened the scope of `AMQPParametersSerializationScheme` so it can be used in `CordFormation` tests.
- Removed password logging in case of error.
Related with: corda/corda-gradle-plugins#190, corda/corda#5081
=> CORDA-2491 Add cordform entrypoint

node/src/integration-test/kotlin/net/corda/node/services/rpc/RpcExceptionHandlingTest.kt
CORDA-2866 introduced a check in the database on startup to prevent the node from starting if it has a legal identity but has lost the corresponding key. There is a test case that invokes the driver twice (which causes the key to be lost between invocations). On H2, the database is also destroyed and recreated, which allows the test to pass. On non-H2 databases, however, the database persists, and so on the second invocation the check fails and the nodes fail to start, which fails the test.
This change adjusts the change to use one driver invocation and different nodes for the second part of the test, which should prevent this problem from occurring.
=> [CORDA-2866] Adjust RPC test case to prevent failures on non-H2 databases

docs/source/node-upgrade-notes.rst
The Corda 4.x  upgrade notes include guidance to upgrade from minimum Corda 3.2 version
(https://r3-cev.atlassian.net/browse/CORDA-2511).
=> CORDA-2511 Upgrade notes for C4 need to include required minimum previous Corda version

docs/source/node-database-tables.rst
Change paragraphs heading of Database Tables page so they don't appear as top level in the side bar; fix a web page link.
The change has already been applied on Enterprise (https://github.com/corda/enterprise/pull/2061).
Before:
After the fix:
=> Database Tables doc page fix - paragraphs heading

serialization/src/main/kotlin/net/corda/serialization/internal/amqp/CorDappCustomSerializer.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/CustomSerializerRegistry.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/LocalSerializerFactory.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/ObjectSerializer.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/PropertyDescriptor.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/SerializerFactory.kt, serialization/src/main/kotlin/net/corda/serialization/internal/model/LocalTypeInformation.kt, serialization/src/main/kotlin/net/corda/serialization/internal/model/LocalTypeInformationBuilder.kt, serialization/src/test/kotlin/net/corda/serialization/internal/amqp/DeserializeSimpleTypesTests.kt, serialization/src/test/kotlin/net/corda/serialization/internal/model/LocalTypeModelTests.kt
Raised for https://r3-cev.atlassian.net/browse/CORDA-2870 . I have followed the recommendations of information to include in this change that Dom mentioned in the Jira ticket. I think the format of the error messages is quite good and useful now, but the classloader information probably needs a little more work on it.
Below are the main changes:
When creating `LocalTypeInformation.NonComposable` pass in the `reason`
a type was not composable and the `remedy` to fix it. This required
changes in `LocalTypeInformationBuilder` to pass in this extra
information so that it can be used later.
The message that the `ObjectSerializer` includes in its
`NotSerializableException` now includes the extra information about the
non composable type.
In `ObjectSerializer`, when a serialization exception is …
=> CORDA-2870 improve error messages for non composable types

docs/source/changelog.rst, node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/HibernateConfiguration.kt
see https://r3-cev.atlassian.net/browse/CORDA-2934
I've tested manually, and the node can be started without hibernate validator in the "lib" folder
=> CORDA-2934 disable hibernate validator integration with hibernate

docs/source/api-contract-constraints.rst, docs/source/api-states.rst, docs/source/cordapp-advanced-concepts.rst, docs/source/cordapp-dependencies.rst
see https://r3-cev.atlassian.net/browse/CORDA-2639
Added some documentation explaining what the problems are with cordapp dependencies in Corda 4 and how it can be solved.
I don't know where doc should live, so I just created a new file for it.
Looking for some feedback on the content, structure and logic of this.
Raised: https://r3-cev.atlassian.net/browse/CORDA-2666 , to create supporting tooling.
=> CORDA-2639: CorDapp dependencies documentation

docs/source/deploying-a-node.rst
Fix a link to remote webpage, as reported on #general Slack channel  https://cordaledger.slack.com/archives/C2KGD72UX/p1558697615038600
=> Docs - fix broken link to nssm third-party tool

docs/source/getting-set-up.rst, docs/source/tutorial-cordapp.rst
- Updated the `Getting set-up` docs. Specifically the section describing how to set-up Oracle JDK 8 on Ubuntu since the installer PPA mentioned in the current documentation has been [discontinued](https://launchpad.net/~webupd8team/+archive/ubuntu/java) following Oracle's decision to change the JDK licensing and archive JDK 8.
- Fixed a minor typo
- Seems like the `/api/example/create-iou` endpoint in the example cordapp has been changed from a `PUT` to a `POST` so the docs have been updated to reflect that change.
=> Update getting set-up documentation for Ubuntu/Debian

node/src/main/kotlin/net/corda/node/services/persistence/NodeAttachmentService.kt, node/src/test/kotlin/net/corda/node/services/persistence/NodeAttachmentServiceTest.kt
see: https://r3-cev.atlassian.net/browse/CORDA-2975
This removes the contract version uniqueness check.
The version field is no longer used anywhere.
Follow-up PR should remove all other traces.
=> CORDA-2975 Remove version uniqueness check

tools/explorer/src/main/kotlin/net/corda/explorer/views/cordapps/cash/NewTransaction.kt
Catching the exception means we don't early exit when a bad amount is entered
=> CORDA-2945: Catch IllegalArgumentException to avoid shutdown of NodeExplorer

node/src/integration-test/kotlin/net/corda/node/persistence/DbSchemaInitialisationTest.kt
Add integration tests to check if database.initialiseSchema=false is respected.The expected behaviour is:For a fresh node when the option is set to false Hibernate doesn't create database objects (e.g. tables) upon a node startup and node fails to start beacuse the databse objects defined in JPA annotations can not be found.
This is backport of some test done for Corda Enteprise in ENT-3616 .
=> CORDA-2971 - added tests for initialiseSchema configuration option

build.gradle
Jackson was updated to 2.9.8, however this version has a transitive dependency on kotlin 1.3.10 which is incompatible with corda (which uses 1.2 currently).
=> ENT-3540 Reverting jackson - kotlin runtime issue

client/rpc/src/integration-test/kotlin/net/corda/client/rpc/RPCStabilityTests.kt, node/src/main/kotlin/net/corda/node/services/rpc/RpcBrokerConfiguration.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/RPCDriver.kt
I've only disabled the test in case we can get the feature fixed.
=> CORDA-2981 Disable slow consumers for RPC since it doesn't work.

docs/source/tutorial-cordapp.rst
So for this specific cordapp-example, after you run the nodes, you would not see net.corda.finance.flows.CashExitFlow and etc. I guess this demo code actually have two cordapps running on these nodes. So, for this tutorial, we should delete the last 5 lines of codes
=> Update tutorial cordapp

.idea/compiler.xml, core/src/main/kotlin/net/corda/core/contracts/TransactionVerificationException.kt
This keeps things in sync with ENT.
=> ENT-3489: Removing unnecessary @CordaSerializable annotation from exceptions

node/src/main/resources/migration/common.changelog-init.xml
This fixes the wanings arising from database not being h2, even if there is a precondition about it. This does not touch upon the other skipping changeset about clustered changes. (as the fix there would be to mention non existing db for OS)
=> CORDA-2774 Fix for liquibase changelog warnings.

core/src/main/kotlin/net/corda/core/identity/CordaX500Name.kt, core/src/main/kotlin/net/corda/core/internal/X500Utils.kt
This fixes the issue with the x500Principal decoding from the certificate in the JKS store. It turns out that some parts of the x500Principal are either instances of DERPrintableString or DERUTF8String.
=> CORDA-2974 Fixing x500Prinicipal matching

build.gradle
4.8.38 not working with the changes from 2152961d
=> CORDA-2333: Reverting ClassGraph version back to 4.6.12

core/src/main/kotlin/net/corda/core/contracts/StatePointer.kt
Apply `@KeepForDJVM` and `@DeleteForDJVM` annotations to ensure that `StatePointer` classes are included in `corda-core-deterministic`.
We achieve this by deleting the `resolve(ServiceHub)` methods using JarFilter.
=> CORDA-3015: Add StatePointer classes to corda-core-deterministic.

docs/source/network-builder.rst
The link to the network builder executable JAR was incorrect in the documentation file network-builder.rst
It was pointing to a version 4.0 of the network builder JAR which does not exist. The link was changed to point to the most recent version, which is 3.2.1847.
=> CORDA-2999: Corrected network builder JAR url in docs

docs/source/node-upgrade-notes.rst
CORDA-2511 doc fix: upgrade notes for C4 need to include guidance to upgrade from C3.2 (minimum) to C4
(cherry picked from commit ab8d4a312aff2ff4c1ddaa69f9306024c039b3fc)
=> CORDA-2511 Upgrade notes for C4 need to include required minimum previous Corda version (#5039)

constants.properties, core-deterministic/build.gradle, core-deterministic/testing/verifier/build.gradle, jdk8u-deterministic/build.gradle, serialization-deterministic/build.gradle
Use Gradle's `java-library` plugin and `publish-utils` 5.0.2 to publish Corda's deterministic artifacts with appropriate `compile` and `runtime` dependencies. This will allow projects just as Tokens SDK to use `corda-core-deterministic` with its correct transitive dependencies under Gradle 5.x
=> CORDA-2871: Fine-tune compile vs runtime scopes for published deterministic jars.

docs/source/whitepaper/Ref.bib, docs/source/whitepaper/corda-technical-whitepaper.tex
First PR in a series that goes onto a feature branch. When the whole doc is refreshed and more content is added, it can be merged.
In part 1:
* A new section is added on package namespace ownership and the no-overlap rule.
* The spelling of "serialize" is standardized on the US spelling used by the code, and add some content on serialization to the docs.
* Make a variety of smaller edits intended to make it read better.
* Spelling fixes.
* The discussion of C-I is temporarily removed, pending later re-addition in a new privacy section.
* Reference states are described.
* More TODOs are added to help me keep track of things that are needed.
* The discussion of time and clock sync is updated.
* The discussion of identity lookups is removed.
Much more work remains. I have been re-reading and …
=> Tech white paper refresh, part 1

node/src/test/kotlin/net/corda/node/services/events/NodeSchedulerServiceTest.kt
Test the scheduler picking up a persisted scheduled state without shutting down/restart the db.
=> Flaky test fix in SchedulerService tests

.ci/api-current.txt, core/src/main/kotlin/net/corda/core/flows/CollectSignaturesFlow.kt, core/src/main/kotlin/net/corda/core/flows/FlowLogic.kt, core/src/main/kotlin/net/corda/core/flows/FlowSession.kt, core/src/main/kotlin/net/corda/core/identity/AnonymousParty.kt, core/src/main/kotlin/net/corda/core/identity/Party.kt, core/src/main/kotlin/net/corda/core/internal/FlowStateMachine.kt, core/src/main/kotlin/net/corda/core/node/services/IdentityService.kt, core/src/test/kotlin/net/corda/core/flows/CollectSignaturesFlowTests.kt, docs/source/changelog.rst, finance/workflows/src/main/kotlin/net/corda/finance/flows/CashPaymentFlow.kt, finance/workflows/src/main/kotlin/net/corda/finance/workflows/asset/CashUtils.kt, node/src/main/kotlin/net/corda/node/services/api/IdentityServiceInternal.kt, node/src/main/kotlin/net/corda/node/services/identity/PersistentIdentityService.kt, node/src/main/kotlin/net/corda/node/services/statemachine/Action.kt, node/src/main/kotlin/net/corda/node/services/statemachine/ActionExecutorImpl.kt, node/src/main/kotlin/net/corda/node/services/statemachine/Event.kt, node/src/main/kotlin/net/corda/node/services/statemachine/FlowMessaging.kt, node/src/main/kotlin/net/corda/node/services/statemachine/FlowSessionImpl.kt, node/src/main/kotlin/net/corda/node/services/statemachine/FlowStateMachineImpl.kt, node/src/main/kotlin/net/corda/node/services/statemachine/StateMachineState.kt, node/src/main/kotlin/net/corda/node/services/statemachine/transitions/StartedFlowTransition.kt, node/src/main/kotlin/net/corda/node/services/statemachine/transitions/TopLevelTransition.kt, node/src/test/kotlin/net/corda/node/services/statemachine/FlowFrameworkTests.kt, node/src/test/kotlin/net/corda/node/services/statemachine/RetryFlowMockTest.kt
This change is a prerequisite for the accounts SDK. Initiating flows with AnonymousParty s allows CorDapp developers to create transactions involving account holders which can still be used with the standard platform flows e.g. FinalityFlow and CollectSignatureFlow. Without this change, shims would be required to use the standard platform flows, this is because the party objects for account holders are always AnonymousParty s.
=> CID-878 Flows: Create flow sessions with anonymous parties

node/src/integration-test/kotlin/net/corda/node/logging/ErrorCodeLoggingTests.kt, testing/node-driver/src/main/kotlin/net/corda/testing/driver/DriverDSL.kt, testing/node-driver/src/main/kotlin/net/corda/testing/driver/NodeParameters.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/DriverDSLImpl.kt
Added a test that raises the log level to error as normally when one of the logger initialises everything before the init logging call, the level is set to info. We expect that the node would not log any errors during startup, thus we check if the log file is empty.
=> CORDA-2176 - test that logging is not broken.

client/jackson/src/main/kotlin/net/corda/client/jackson/StringToMethodCallParser.kt, client/jackson/src/main/kotlin/net/corda/client/jackson/internal/CordaModule.kt, client/rpc/src/main/kotlin/net/corda/client/rpc/CordaRPCClient.kt, client/rpc/src/main/kotlin/net/corda/client/rpc/internal/ReconnectingCordaRPCOps.kt, core/src/main/kotlin/net/corda/core/internal/messaging/InternalCordaRPCOps.kt, core/src/main/kotlin/net/corda/core/messaging/CordaRPCOps.kt, docs/source/changelog.rst, docs/source/upgrading-cordapps.rst, node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt, node/src/main/kotlin/net/corda/node/internal/CordaRPCOpsImpl.kt, node/src/main/kotlin/net/corda/node/internal/rpc/proxies/AuthenticatedRpcOpsProxy.kt, node/src/main/kotlin/net/corda/node/internal/rpc/proxies/ExceptionMaskingRpcOpsProxy.kt, node/src/main/kotlin/net/corda/node/internal/rpc/proxies/ExceptionSerialisingRpcOpsProxy.kt, node/src/main/kotlin/net/corda/node/internal/rpc/proxies/ThreadContextAdjustingRpcOpsProxy.kt, node/src/main/kotlin/net/corda/node/services/rpc/CheckpointDumper.kt, node/src/test/kotlin/net/corda/node/internal/rpc/proxies/ThreadContextAdjustingRpcOpsProxyTest.kt, tools/shell/src/integration-test/kotlin/net/corda/tools/shell/InteractiveShellIntegrationTest.kt, tools/shell/src/main/java/net/corda/tools/shell/RunShellCommand.java, tools/shell/src/main/kotlin/net/corda/tools/shell/CordaAuthenticationPlugin.kt, tools/shell/src/main/kotlin/net/corda/tools/shell/CordaSSHAuthInfo.kt, tools/shell/src/main/kotlin/net/corda/tools/shell/InteractiveShell.kt, tools/shell/src/main/kotlin/net/corda/tools/shell/RPCOpsWithContext.kt, tools/shell/src/test/kotlin/net/corda/tools/shell/InteractiveShellTest.kt
Dumps all the node's checkpoints as JSON into a single zip file in the node's directory. The output contains:
* All the fields for the top-level flow
* The current sub-flow call stack, along with the current progress tracker step for each sub-flow
* The event that suspended the flow, which if it's a send or sendAndReceive will show the payload that was sent
* Low level information on the active sessions with other peers
=> ENT-3496: dumpCheckpoints RPC

build.gradle
`jackson-module-kotlin` version `2.9.5` was causing runtime errors. Updating to `2.9.7` resolved these errors. The dependency was not updated to a more recent version as they require kotlin 1.3.
=> CORDA-2333: Upgrade jackson version to 2.9.7

node/src/main/kotlin/net/corda/node/internal/subcommands/InitialRegistrationCli.kt, node/src/main/kotlin/net/corda/node/utilities/registration/NetworkRegistrationHelper.kt, node/src/test/kotlin/net/corda/node/utilities/registration/NetworkRegistrationHelperTest.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/DriverDSLImpl.kt
Refactor `NodeRegistrationHelper` to use it's own config class (`NodeRegistrationConfiguration`) rather than the larger (and largely unnecessary) `NodeConfiguration`
=> CORDA-2720: Refactor NodeConfiguration out of NodeRegistrationHelper

build.gradle
Reverting upgrade of dokka. See linked ticket for details.
Change has been tested on the nightly job that was failing.
=> [CORDA-3042] - Revert upgrade of dokka

docs/source/clientrpc.rst
Fix broken links for `ReconnectingCordaRPCOps` and `RpcReconnectTests` as they were moved out of the samples repo into the main repo.
Pointed links to master since it seems to be the most reliable way for the links to work.
=> DOCS - Fix broken url to reconnecting rpc code

node-api/src/main/kotlin/net/corda/nodeapi/internal/network/NodeInfoFilesCopier.kt, node/src/main/kotlin/net/corda/node/services/network/NodeInfoWatcher.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/DriverDSLImpl.kt
Shorten the polling interval for propagating node info files between nodes, in the hope of avoiding test failures due to nodes not having received each other's info yet.
=> CORDA-2991 shorten poll intervals for node info file propagation

core/src/test/kotlin/net/corda/core/flows/ReferencedStatesFlowTests.kt, docs/source/changelog.rst, docs/source/tutorial-observer-nodes.rst, node/src/main/kotlin/net/corda/node/services/api/ServiceHubInternal.kt, node/src/main/kotlin/net/corda/node/services/api/VaultServiceInternal.kt, node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt, node/src/test/kotlin/net/corda/node/services/persistence/ObserverNodeTransactionTests.kt, node/src/test/kotlin/net/corda/node/testing/MessageChainState.kt
When recording transactions, the `StatesToRecord` flag is set to indicate what output states should be recorded. Once a transaction has been recorded once, it will be filtered out from further attempts to record it. This is an issue if a node wishes to record the non-relevant states of a transaction after having seen it once already.
This PR introduces a new list of transactions to be passed to the `NodeVaultService`: the `previouslySeenTxs` list. This list is only populated if the transaction list passed to the `ServiceHubInternal` instance should be recorded at `StatesToRecord.ALL_VISIBLE`. This list is processed by the vault by looking up all the outputs for the transaction, and only recording those outputs that are not already present in the vault.
The code is structured such that the …
=> [CORDA-2086] Allow transactions to be re-recorded using StatesToRecord.ALL_VISIBLE

node/src/main/kotlin/net/corda/node/services/config/schema/v1/V1NodeConfigurationSpec.kt, node/src/main/resources/reference.conf, tools/demobench/src/test/kotlin/net/corda/demobench/model/NodeConfigTest.kt
Added this and `custom` to reference.conf so tests fail if they are not supported.
=> CORDA-3053 Validation should pass with systemProperties defined in config

docs/source/node-flow-hospital.rst, node/src/integration-test/kotlin/net/corda/node/flows/FlowRetryTest.kt, node/src/main/kotlin/net/corda/node/services/statemachine/StaffedFlowHospital.kt
To handle `SQLTransientConnectionException`s from hikari, `TransientConnectionCardiologist` has been added to the flow hospital staff.
The exception handling is tailored to hikari's db connection timeout at the moment.
Comments from https://github.com/corda/enterprise/pull/2200 have been taken into account when creating this PR and moving the change into OS.
=> ENT-3710 Add `TransientConnectionCardiologist` to Flow Hospital

docs/source/tutorial-contract.rst
Correcting the method name in ServiceHub. It is mentioned as serviceHub.toSignedTransaction where toSignedTransaction is a method from TransactionBuilder. 
Optionally this can be changed to TransactionBuilder.toSignedTransaction however as it is an internal function it is of less relevance I suppose.
=> DOCS - use signInitialTransaction instead of toSignedTransaction in tutorial docs

docs/source/api-contract-constraints.rst, docs/source/app-upgrade-notes.rst, docs/source/versioning.rst, node-api/src/main/kotlin/net/corda/nodeapi/exceptions/RpcExceptions.kt, node/src/main/kotlin/net/corda/node/services/persistence/NodeAttachmentService.kt, node/src/test/kotlin/net/corda/node/services/persistence/NodeAttachmentServiceTest.kt
- Remove exception from code
- Remove reference to it in docs
- Tidy up docs since the versioning checks it mentions are not valid
- Fix spelling mistakes in test names
=> Delete unused DuplicateContractClassException

core/src/main/kotlin/net/corda/core/internal/InternalUtils.kt, node/src/main/kotlin/net/corda/node/internal/DBNetworkParametersStorage.kt, node/src/main/kotlin/net/corda/node/migration/MigrationServicesForResolution.kt, node/src/main/kotlin/net/corda/node/services/identity/PersistentIdentityService.kt, node/src/main/kotlin/net/corda/node/services/keys/BasicHSMKeyManagementService.kt, node/src/main/kotlin/net/corda/node/services/keys/PersistentKeyManagementService.kt, node/src/main/kotlin/net/corda/node/services/persistence/DBTransactionStorage.kt, node/src/main/kotlin/net/corda/node/utilities/AppendOnlyPersistentMap.kt, node/src/main/kotlin/net/corda/notary/experimental/bftsmart/BFTSmart.kt, node/src/main/kotlin/net/corda/notary/experimental/raft/RaftTransactionCommitLog.kt
As a general purpose API, allPersisted should not be loading the entire contents of the database table into memory. Instead now it returns a Stream for processing one element at a time.
=> AppendOnlyPersistentMapBase.allPersisted no longer loads everything into memory at once

node-api/src/main/kotlin/net/corda/nodeapi/internal/config/ConfigUtilities.kt, node/src/main/kotlin/net/corda/node/services/config/schema/v1/V1NodeConfigurationSpec.kt, node/src/test/kotlin/net/corda/node/services/config/NodeConfigurationImplTest.kt, node/src/test/resources/working-config.conf
We have 2 different methods/frameworks:
1. Reflection based ConfigUtilities from NodeAPI. This has no effect on Node configuration parsing.
2. Specification driven parsing which is used for Node configuration written by @sollecitom
=> CORDA-3068: Pass base directory when resolving relative paths

node/src/main/kotlin/net/corda/node/services/statemachine/SingleThreadedStateMachineManager.kt
Change to `SingleThreadedStateMachineManager`.
Instead of throwing an exception when a flow's fiber cannot be found,
just log the message at info level.
Related to https://github.com/corda/enterprise/pull/2263 .
=> ENT-3504 Do not throw exception for missing fiber and log instead - OS version

docs/source/clientrpc.rst
(cherry picked from commit 2bfd2c8cb5c8ff894d63f825f58e893c44d3e432)
No related jira. Docs only change.
=> BACKPORT - docs reconnecting rpc correct link

docs/source/changelog.rst, docs/source/tutorial-custom-notary.rst, testing/node-driver/src/main/kotlin/net/corda/testing/node/MockNetwork.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/InternalMockNetwork.kt, testing/node-driver/src/test/kotlin/net/corda/testing/node/CustomNotaryTest.kt
Currently it is possible to run a notary with a custom service class as described here: https://docs.corda.net/tutorial-custom-notary.html. What that page does **not** describe is how to write a flow test using your custom notary. This is because that is currently not possible (or at least not in an elegant way). This PR makes it possible to set the className property in the MockNetworkNotarySpec like so:
```kotlin
MockNetworkNotarySpec(
name = CordaX500Name("Custom Notary", "Amsterdam", "NL"),
className = "net.corda.testing.node.CustomNotaryTest\$CustomNotaryService"
)
```
=> Add MockNet support for custom Notary class

client/rpc/src/integration-test/kotlin/net/corda/client/rpc/CordaRPCClientReconnectionTest.kt
The `CordaRPCClientReconnectionTests` do not close the RPC connection once they are done with it. This appears to result in a serialization environment leak, causing tests run after this set to fail due to multiple serialization environments being set. This PR ensures that these connections are closed at the end of the tests.
=> [CORDA-2923] Ensure the RPC connection is closed in Reconnection test

node/src/main/kotlin/net/corda/node/services/statemachine/StateMachineManagerImpl.kt
Port of https://github.com/corda/corda/pull/5308
=> CORDA-3092: Exception is logged if flow session message can't be deserialised

client/rpc/src/integration-test/kotlin/net/corda/client/rpc/RPCStabilityTests.kt, client/rpc/src/main/kotlin/net/corda/client/rpc/internal/ReconnectingCordaRPCOps.kt
A flaky set of tests was exposed by #5303. The `CordaRPCClientReconnectionTest` leaves some threads running after completion, which themselves sometimes spawned new threads. A test in the `RPCStabilityTests` checks for leaking threads, and was sometimes detecting that the thread count had gone up.
The issue turned out to be that on reconnect, the `ReconnectingCordaRPCOps` didn't attempt to close resources from the old connection. This PR adds that logic in, and also adjusts the `RPCStabilityTests` to look for new threads, which makes the test more reliably pick up thread leaking issues.
=> [CORDA-2923] Prevent connection threads leaking on reconnect

node-api/src/main/kotlin/net/corda/nodeapi/internal/config/CertificateStore.kt
By now we were lucky because all the time `X509Utilities.CORDA_ROOT_CA` been used as an input parameter.
=> CORDA-1937: Do not ignore `alias` parameter passed in.

docs/source/network-bootstrapper.rst
The old url was pointing to a link that was not used anywhere else and all it did was end up redirecting to the docs homepage.
This has been replaced with the bootstrappers location on artifactory. I have not linked to the specific version that the docs relate to, as this will not work for master.
=> DOCS - Point network bootstrapper url to the artifactory download location

core-tests/src/test/kotlin/net/corda/coretests/transactions/TransactionBuilderTest.kt, core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt, node/src/integration-test/kotlin/net/corda/contracts/SignatureConstraintVersioningTests.kt
Allow Hash Constraints to propagate to Signature Constraints. When
propagating, the new jar is added to the transaction instead of the
original contract attachment (jar).
The following requirements must be met to do so:
- System property "net.corda.node.disableHashConstraints" must be set
to `true`
- The min platform version must be 4 or greater
- There must be an input state with a hash constraint
- There must be no output states with a hash constraint
- The new jar must be signed
If these requirements are not met, the original Hash
Constraint will be kept and the contract attachment related to it is
also used.
This transition is done at the start of `handleContract` as it is not
the normal path a transition would follow. It is considered a backdoor
and should be treated separately from …
=> CORDA-2920 Hash to Signature Constraint automatic propagation

node-api/src/main/kotlin/net/corda/nodeapi/internal/crypto/X509Utilities.kt
- Remove `anyExtendedKeyUsage` from all certificates
- Restrict to server and client auth for all certificates except `ROOT_CA` which has had all extended key usages removed
In regards to https://r3-cev.atlassian.net/browse/CORDA-2216
=> CORDA-2216 Restrict extended key usage of certificate types

.ci/api-current.txt, core/src/main/kotlin/net/corda/core/crypto/CompositeKey.kt, core/src/main/kotlin/net/corda/core/crypto/CompositeKeyFactory.kt, core/src/main/kotlin/net/corda/core/crypto/CordaSecurityProvider.kt
`CompositeKey` support was mistakenly removed from `core-deterministic` and must now be restored.
=> CORDA-2871: Restore CompositeKey support to core-deterministic.

node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt
When a Cordapp JAR lacks some entries in manifest file  ( name/vendor/license)  depending on the
CorDapp type it can be :
- for old fashied JAR: "Name"/"Implementation-Vendor"/"Implementation-Version"
- for new contact JAR: "Cordapp-Contract-Name"/"Cordapp-Contract-Vendor"/"Cordapp-Contract-Licence"
- for new workflow JAR: "Cordapp-Workflow-Name"/"Cordapp-Workflow-Vendor"/"Cordapp-Workflow-Licence"
then during node startup we use to prived minimal log info:
```
[INFO ] [time] [main] BasicInfo. - Loaded 3 CorDapp(s)                     : Contract CorDapp: Corda Finance Demo version 1 by vendor R3 with licence Open Source (Apache 2), Workflow CorDapp: Trader Demo version 1 by vendor R3 with licence Open Source (Apache 2), Workflow CorDapp: Corda Finance Demo version 1 by vendor Unknown with …
```
=> CORDA-3012 More information in log warning for Cordapps missing advised JAR manifest file entries.

node/src/main/kotlin/net/corda/node/services/statemachine/SingleThreadedStateMachineManager.kt
Change to `SingleThreadedStateMachineManager`.
Instead of throwing an exception when a flow's fiber cannot be found,
just log the message at info level.
(cherry picked from commit 70b2a94fda4e1b4f4ee7aff2e369d87fb1c9f7f5)
Related jira - https://r3-cev.atlassian.net/browse/ENT-3504
=> ENT-3504 Statemachine IllegalStateException logging (BACKPORT)

docs/source/network-bootstrapper.rst
Point network bootstrapper url to the artifactory download location
(cherry picked from commit 41634d1fda740a75961f53582370e6040e90026b)
No related jira. 
Docs change only.
=> DOCS - Fix network bootstrapper link to download (BACKPORT)

constants.properties, docs/source/api-testing.rst, docs/source/azure-vm.rst, docs/source/conf.py, docs/source/generating-a-node.rst, docs/source/running-a-notary.rst
Fully replace base path to open source codebase - `openSourceBranch`
Fully replace base path to open source samples - `openSourceSamplesBranch`
These can be accessed in the docs using `os_branch` and `os_samples_branch`
Correct usages in the docs to use these constants.
=> Add constants for the open source and samples repos branch names

core-tests/build.gradle, core/build.gradle, node/build.gradle
The `core-tests` module requires the Node's capsule for the smoke tests, i.e.
```gradle
processSmokeTestResources {
// Bring in the fully built corda.jar for use by NodeFactory in the smoke tests
from(project(':node:capsule').tasks['buildCordaJAR']) {
...
}
```
=> CORDA-3127: Move evaluationDependsOn() from core to core-tests.

core-tests/src/test/kotlin/net/corda/coretests/transactions/AttachmentsClassLoaderTests.kt, core/src/main/kotlin/net/corda/core/internal/TransactionUtils.kt, node/src/test/kotlin/net/corda/node/services/persistence/NodeAttachmentServiceTest.kt, testing/test-utils/src/main/kotlin/net/corda/testing/services/MockAttachmentStorage.kt
Related jira - https://r3-cev.atlassian.net/browse/CORDA-3018
This change covers the relaxing the signer restrictions. The blacklisting of public keys will be handled in a separate PR.
-------------
The requirement of containing the same contract classes has been removed. Therefore the contents of the existing trusted attachment no longer matters.
Allow a subset/intersection of signers to satisfy the signer requirements of `isAttachmentTrusted`. This allows an "untrusted" attachment that is signed by one or more keys to be "trusted" as long as another trusted attachment already exists that is signed by at least one of the "untrusted" attachments signers.
A cache of trusted and untrusted public keys is now held (replacing the previous cache of `List<PublicKey>`.
Tests have been added to …
=> CORDA-3018 Whitelisting attachments by public key - relax signer restrictions

testing/node-driver/src/main/kotlin/net/corda/testing/driver/Driver.kt, testing/node-driver/src/main/kotlin/net/corda/testing/driver/internal/SharedMemoryIncremental.kt, testing/node-driver/src/test/java/net/corda/testing/node/PortAllocationRunner.java, testing/node-driver/src/test/kotlin/net/corda/testing/driver/PortAllocationTest.kt, testing/test-utils/src/main/kotlin/net/corda/testing/internal/InternalTestUtils.kt
Also moved `SharedMemoryIncremental` into a separate file as it getting bigger
and improved readability of logic and added some logging.
=> CORDA-3139: Cater for port already bound scenario during port allocation

docs/source/shell.rst, tools/shell-cli/src/main/resources/net/corda/tools/shell/base/login.groovy
Improved welcome message for Standalone Shell - bye command to exit shell only - not the node.
Docs clarifications gracefulShutdown/shutdown commands needs 'run' as other commands.
=> ENT-3965 Improved welcome message for Standalone Shell

docs/source/checkpoint-tooling.rst, node/src/main/kotlin/net/corda/node/services/rpc/CheckpointDumper.kt
- Handle errors in Jackson and checkpoint deserialisation. A file notifying the user that the checkpoint dump failed is created when errors occur.
- Handle message deserialisation errors. A string placeholder is used if an error occurs.
- Add more information about subflows (include their `FlowLogic`)
- Increase clarity in checkpoint output field names
- Add `flowCallStackSummary` to the output which contains the same content as `flowCallStack` minus each subflow's `FlowLogic`. The `FlowLogic` contains a ton of info which is normally repeated in each subflow. Adding the summary gives an overview of the steps the flow executed and which step it is currently on.
- The `suspendedOn` field is put underneath the summary and the original
call stack is moved below the suspended info.
- This puts …
=> CORDA-3094 improvements to checkpoint dumper

docs/source/app-upgrade-notes.rst
The introduction of the `Destination` interface has introduced a potential source incompatibility between platform versions 4 and 5. This occurs due to a type inference limitation in the Kotlin compiler. This PR updates the upgrade notes for platform version 5 to describe the possible break and how to fix it.
=> [CORDA-3082] Update app upgrade notes to document source incompatibility

node/src/main/kotlin/net/corda/node/services/DbTransactionsResolver.kt, node/src/main/kotlin/net/corda/node/services/persistence/DBTransactionStorage.kt, node/src/main/resources/migration/node-core.changelog-v13.xml, node/src/test/kotlin/net/corda/node/migration/VaultStateMigrationTest.kt, node/src/test/kotlin/net/corda/node/services/statemachine/RetryFlowMockTest.kt
The new database transaction resolver can sometimes cause issues when some database providers are used, due to the character type used by the transaction status column. Moving this to be a string type fixes the problem.
Additionally, a small number of other issues have been corrected.
=> [ENT-4024] Use string for the status column in the transaction table

docs/source/building-a-cordapp-index.rst, docs/source/corda-api.rst, docs/source/index.rst, docs/source/versioning-and-upgrades.rst
* Create a new versioning and upgrades section, currently only with content from existing sections.
* Give the PDF version its own intro, to avoid odd text referring to non-existent videos etc.
* Adjust the formatting of the intro page, make the white papers have big buttons to view them.
=> Tweak the docsite in various ways

serialization-deterministic/build.gradle, serialization-deterministic/src/main/kotlin/net/corda/serialization/internal/amqp/AMQPSerializerFactories.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/AMQPSerializerFactories.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/AMQPTypeIdentifiers.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/ArraySerializer.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/ComposableTypePropertySerializer.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/CustomSerializer.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/CustomSerializerRegistry.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/DeserializationInput.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/EvolutionSerializerFactory.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/LocalSerializerFactory.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/RemoteSerializerFactory.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/Schema.kt, serialization/src/main/kotlin/net/corda/serialization/internal/amqp/SerializerFactoryBuilder.kt, serialization/src/main/kotlin/net/corda/serialization/internal/model/LocalTypeModel.kt, serialization/src/main/kotlin/net/corda/serialization/internal/model/TypeIdentifier.kt, serialization/src/main/kotlin/net/corda/serialization/internal/model/TypeModellingFingerPrinter.kt
- Support "factory" custom serialisers that can generate specific `AMQPSerializer` instances at runtime.
- Fix lockup when computing fingerprints for custom serialisers.
- Allow a custom serialiser to deserialise "alias" types.
- Ensure that all subclasses of `CustomSerializer` are present in `corda-serialization-deterministic`.
- Fix custom serialiser look-up to use any generic type values, where available, because a raw type is *insufficient* to find a custom serialiser created for a parameterised type.
- Fix some typos and compiler warnings.
- Make `DeserialisationInput.readObject()` methods public so that other custom serialisers can use them.
=> CORDA-3157: Modify Corda's custom serialiser support for the DJVM.

common/logging/src/main/kotlin/net/corda/common/logging/Constants.kt, constants.properties, docker/src/bash/example-mini-network.sh, docs/source/docker-image.rst, node/src/integration-test/kotlin/net/corda/node/NodeRPCTests.kt
Change Corda version from 5.0-SNAPSHOT to 4.3-SNAPSHOT to reflect the next version of Corda to be released.
=> [NOTICK]: Change Corda version

node-api/src/main/kotlin/net/corda/nodeapi/internal/cryptoservice/CryptoService.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/cryptoservice/SupportedCryptoServices.kt, node-api/src/main/kotlin/net/corda/nodeapi/internal/cryptoservice/bouncycastle/BCCryptoService.kt, testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/MockCryptoService.kt
Exposing the type of a `CryptoService` through a method in the interface.
For context on what are the benefits/uses of this, see: https://github.com/corda/enterprise/pull/2483
Note: removed the commented-out types, since they were not up-to-date and they are essentially noise here.
=> [NOTICK] Expose type in CryptoService

docs/source/clientrpc.rst
Refining documentation related to rpc reconnection.
Summary:
- The term `client` was used with 2 different meanings: referring to the RPC client and application code. I replaced the occurences having the second meaning with the more explicit `application code` to prevent confusion
- Removed the term `in-flight calls` and replaced it with explicit comments on what this actually referred to.
- Elaborated more on the behaviour of graceful reconnection, specifically around which types of RPC calls are retried and which are not.
- Removed the section `Logical  retries for flow invocation`, since it contained mostly information existing above and roadmap-related commentary, which should not exist in the docs.
=> [CORDA-3106] - Refine documentation around rpc reconnection

core/src/main/kotlin/net/corda/core/utilities/ByteArrays.kt, core/src/main/kotlin/net/corda/core/utilities/EncodingUtils.kt, core/src/test/kotlin/net/corda/core/utilities/ByteArraysTest.kt
See https://r3-cev.atlassian.net/browse/CORDA-3175
**Note**: without this refactoring, when moving to JDK11 it becomes necessary to add the following 3rd party compile time dependency to several Corda modules:
```
// JDK 11 (https://stackoverflow.com/questions/52502189/java-11-package-javax-xml-bind-does-not-exist)
compile group: 'javax.xml.bind', name: 'jaxb-api', version: '2.3.0'
```
=> CORDA-3175 Remove dependency on 3rd party javax.xml.bind library for simple hex parsing/printing.

client/rpc/src/integration-test/kotlin/net/corda/client/rpc/CordaRPCClientTest.kt, client/rpc/src/main/kotlin/net/corda/client/rpc/internal/ReconnectingCordaRPCOps.kt, node/src/main/kotlin/net/corda/node/services/rpc/ArtemisRpcBroker.kt, node/src/main/kotlin/net/corda/node/services/rpc/RPCServer.kt
`SecurityManager` was closed from the `RpcServer` component, instead of `RpcBroker` component. As a result, during node shut down, clients attempting to perform RPC calls could be erroneously receiving `ActiveMQSecurityException` indicating authentication failed.
This moves the tear down of `SecurityManager` into `RpcBroker`. It also contains some cleanups on tests that were ignoring `ActiveMQSecurityException`s, since it can mask other genuine issues.
=> [CORDA-2890] - Close security manager after broker is shut down

core-tests/src/test/kotlin/net/corda/coretests/internal/ResolveTransactionsFlowTest.kt, node/src/main/kotlin/net/corda/node/services/DbTransactionsResolver.kt
This PR relates to Jira: https://r3-cev.atlassian.net/browse/ENT-4058
Two performance enhancements for back chain resolution as a result of using the Back Chain Resolution tester:
1 - Changing the main loop to request one item at a time.
2 - Remove duplicate SecureHash objects
These changes have been tested in the performance cluster on enterprise with a back chain of 16384 items to fetch.
=> CORDA-3177 Additional Back Chain Resolution performance enhancements

core/src/main/kotlin/net/corda/core/internal/StatePointerSearch.kt, core/src/test/kotlin/net/corda/core/internal/StatePointerSearchTests.kt
Fix for https://github.com/corda/corda/issues/5362
=> CORDA-3188: Ignore synthetic and static fields when searching for state pointers

docs/source/node-administration.rst
Fix misleading doc about extending (but not replacing) the default log4j configuration settings.
The improved instruction will be referenced by a database initlisation logs doc in https://github.com/corda/corda/pull/5310.
Tested:
1) ./gradlew samples:tarder-demo:deployNodes
2) ```cd``` to BankOfCorda, ```rm *.db, rm logs/*.log```
3) followed the original doc  ( java -jar -Dlog4j.configurationFile=<path_to_file>/sql.xml corda.jar)
there ar eno logs in logs folder as the configuration was completley replaced
4) stop node
5) ```rm *.db, rm logs/*.log```
6) followed the ned doc.( java -jar -Dlog4j.configurationFile=log4j2.xml,<path_to_file>/sql.xml corda.jar) - the contend is loged to the file inside 'logs' folder
=>  Improve docs about extending log4j2 settings (prerequisite for  CORDA-3096)
