corda/corda

- build.gradle
- gradle-plugins/build.gradle
- gradle-plugins/cordformation/src/main/resources/net/corda/plugins/runnodes
JAVA_HOME may not be set, and if not the script will exit without running the nodes. This PR fixes it by correctly testing if JAVA_HOME is set (since we have set -o). 
This PR requires a new release of gradle plugins once merged and an update of the cordapp template to fix the issue there too.
> Fix an error in runnodes when running on Linux

- build.gradle
- docs/source/example-code/build.gradle
- docs/source/permissioning.rst
- experimental/build.gradle
- node/build.gradle
- samples/attachment-demo/build.gradle
- samples/irs-demo/build.gradle
- samples/network-visualiser/build.gradle
- samples/raft-notary-demo/build.gradle
- samples/simm-valuation-demo/build.gradle
- samples/trader-demo/build.gradle
Alter the way that the corda.jar is created to be an artifact of the :node module. Then point at this as a runtime dependency, rather than as a locally published artifact.
> Change gradle to not need an install step before build

- docs/source/_templates/layout.html
- docs/source/_templates/layout_for_doc_website.html
- docs/source/getting-set-up.rst
The doc site has no links to discourse or slack - Added them to be included just below the link the API reference.
> Adding links to discourse and slack on docsite

- .gitignore
- core/src/main/kotlin/net/corda/core/node/services/NetworkMapCache.kt
- core/src/main/kotlin/net/corda/flows/TwoPartyDealFlow.kt
- node/src/main/kotlin/net/corda/node/services/network/InMemoryNetworkMapCache.kt
- samples/irs-demo/src/main/kotlin/net/corda/irs/flows/FixingFlow.kt
Clean up of NetworkMapCache:
* Removed `get()` as it was duplicated by `partyNodes`
* Moved most of the notary val getter implementations in `InMemoryNetworkMapCache` to `NetworkMapCache` as they only depend on `partyNodes` and the implementations are generic
* Renamed `regulators` to `regulatorNodes` to be consistent
> Clean up NetworkMapCache and InMemoryNetworkMapCache

- client/src/main/kotlin/net/corda/client/CordaRPCClient.kt
- client/src/main/kotlin/net/corda/client/impl/CordaRPCClientImpl.kt
- client/src/test/kotlin/net/corda/client/ClientRPCInfrastructureTests.kt
- core/src/main/kotlin/net/corda/core/crypto/X509Utilities.kt
- core/src/main/kotlin/net/corda/core/messaging/Messaging.kt
- core/src/main/kotlin/net/corda/flows/NotaryFlow.kt
- core/src/main/kotlin/net/corda/flows/ValidatingNotaryFlow.kt
- core/src/test/kotlin/net/corda/core/crypto/X509UtilitiesTest.kt
- docs/source/messaging.rst
- docs/source/setting-up-a-corda-network.rst
- node/build.gradle
- node/src/integration-test/kotlin/net/corda/services/messaging/MQSecurityTest.kt
- node/src/integration-test/kotlin/net/corda/services/messaging/P2PSecurityTest.kt
- node/src/integration-test/kotlin/net/corda/services/messaging/RPCSecurityTest.kt
- node/src/main/kotlin/net/corda/node/internal/Node.kt
- node/src/main/kotlin/net/corda/node/services/config/ConfigUtilities.kt
- node/src/main/kotlin/net/corda/node/services/messaging/ArtemisMessagingComponent.kt
- node/src/main/kotlin/net/corda/node/services/messaging/ArtemisMessagingServer.kt
- node/src/main/kotlin/net/corda/node/services/messaging/NodeMessagingClient.kt
- node/src/main/kotlin/net/corda/node/services/messaging/RPCDispatcher.kt
- node/src/main/kotlin/net/corda/node/services/statemachine/FlowStateMachineImpl.kt
- node/src/main/kotlin/net/corda/node/services/statemachine/StateMachineManager.kt
- node/src/test/kotlin/net/corda/node/messaging/InMemoryMessagingTests.kt
- node/src/test/kotlin/net/corda/node/services/ArtemisMessagingTests.kt
- node/src/test/kotlin/net/corda/node/services/statemachine/StateMachineManagerTests.kt
- samples/network-visualiser/src/main/kotlin/net/corda/netmap/NetworkMapVisualiser.kt
- test-utils/src/main/kotlin/net/corda/testing/messaging/SimpleMQClient.kt
- test-utils/src/main/kotlin/net/corda/testing/node/InMemoryMessagingNetwork.kt
- test-utils/src/main/kotlin/net/corda/testing/node/NodeBasedTest.kt
This is re-opened from the private repo.
This locks down the Artemis broker to only give the necessary permissions to clients, of which there are three types:
* The node and processes which are logically part of the node - these are given full access to the broker
* Peers on the same Corda network - they are only given permission to send to the node
* RPC users - one of the valid users configured which is given enough permission to do RPC with the node.
Received messages are now tagged with the authenticated user which allows the flow framework to authentically retrieve the sender Party.
> Added security to RPC and P2P systems.

- client/src/main/kotlin/net/corda/client/model/NetworkIdentityModel.kt
- client/src/main/kotlin/net/corda/client/model/NodeMonitorModel.kt
- core/src/main/kotlin/net/corda/core/node/services/NetworkMapCache.kt
- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/main/kotlin/net/corda/node/services/messaging/ArtemisMessagingServer.kt
- node/src/main/kotlin/net/corda/node/services/messaging/RPCStructures.kt
- node/src/main/kotlin/net/corda/node/services/network/InMemoryNetworkMapCache.kt
The use of the `MapChangeType` enum meant that `prevNodeInfo` had to be nullable because it wasn't relevant for adds and removes. Now it only appears in the `Modified` class.
> Converted MapChange into a sealed data structure

- core/src/main/kotlin/net/corda/core/crypto/X509Utilities.kt
- core/src/test/kotlin/net/corda/core/crypto/X509UtilitiesTest.kt
This PR fixes some issues in the cert code. Some old code still assumed that the CN is the hostname. Should fix ci
> core: Remove CN from X509 subjectAlternativeNames, always add hostname

- docs/source/index.rst
Minor change such that the version parameter is used in the warning instead of h/coded "master"
> Making the warning make sense for branches that aren't master

- core/src/main/kotlin/net/corda/core/contracts/DummyContract.kt
- core/src/main/kotlin/net/corda/core/node/ServiceHub.kt
- docs/source/example-code/src/main/kotlin/net/corda/docs/WorkflowTransactionBuildTutorial.kt
- finance/src/main/java/net/corda/contracts/JavaCommercialPaper.java
- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/main/kotlin/net/corda/node/services/events/NodeSchedulerService.kt
- node/src/main/kotlin/net/corda/node/services/statemachine/StateMachineManager.kt
- node/src/test/kotlin/net/corda/node/services/ScheduledFlowTests.kt
- test-utils/src/main/kotlin/net/corda/testing/node/InMemoryMessagingNetwork.kt
- test-utils/src/main/kotlin/net/corda/testing/node/MockNode.kt
I have added some hooks to the NodeSchedulerService, StateMachineManager and InMemoryNetwork so that unit tests with scheduled actions can pause using net.waitQuiescent() until all node activity has finally ended. I have also added a test which uses a SchedulableState to trigger a flow and move states to another node using the FinalityFlow, so that we actually exercise this activity more than in the rather specialist scheduler tests.
> Add some hooks to StateMachineManager and NodeSchedulerService

- core/src/main/kotlin/net/corda/core/contracts/TransactionVerification.kt
- finance/src/test/kotlin/net/corda/contracts/asset/CashTests.kt
- test-utils/src/main/kotlin/net/corda/testing/TestDSL.kt
Simple fix with tracking of used inputs on a ledger level.
> Fix double spending of inputs issue on ledger level in test dsl.

- core/src/main/kotlin/net/corda/core/Utils.kt
- core/src/main/kotlin/net/corda/core/node/services/Services.kt
- docs/source/example-code/src/test/kotlin/net/corda/docs/FxTransactionBuildTutorialTest.kt
- docs/source/example-code/src/test/kotlin/net/corda/docs/WorkflowTransactionBuildTutorialTest.kt
- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/main/kotlin/net/corda/node/services/api/ServiceHubInternal.kt
- node/src/main/kotlin/net/corda/node/services/events/ScheduledActivityObserver.kt
- node/src/main/kotlin/net/corda/node/services/network/InMemoryNetworkMapCache.kt
- node/src/main/kotlin/net/corda/node/services/persistence/DBTransactionMappingStorage.kt
- node/src/main/kotlin/net/corda/node/services/persistence/DBTransactionStorage.kt
- node/src/main/kotlin/net/corda/node/services/schema/HibernateObserver.kt
- node/src/main/kotlin/net/corda/node/services/statemachine/StateMachineManager.kt
- node/src/main/kotlin/net/corda/node/services/vault/CashBalanceAsMetricsObserver.kt
- node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt
- node/src/main/kotlin/net/corda/node/utilities/DatabaseSupport.kt
- node/src/test/kotlin/net/corda/node/services/ArtemisMessagingTests.kt
- node/src/test/kotlin/net/corda/node/services/InMemoryNetworkMapCacheTest.kt
- node/src/test/kotlin/net/corda/node/services/InMemoryNetworkMapServiceTest.kt
- node/src/test/kotlin/net/corda/node/utilities/ObservablesTests.kt
Currently our `Observers` immediately push their observations to subscribers, even though the change of state they refer to will likely not be visible to anyone not inside the same database transaction.  e.g. observe a change in the vault and then query it only to **not** find what you were just informed of.  This particularly impacts RPC and tests. 
An example test that was impacted by this was `FxTransactionBuildTutorialTest` which had to be re-written from the original form to that which is now in the master branch because the vault update was sometimes not visible to the subscribers due to that race condition, and would occasionally fail.  It is restored to the original form as part of this PR.
Use the extension method `Observable.afterCommit()` to create a buffered form of the …
> Buffer observations until database commit.

- test-utils/src/main/kotlin/net/corda/testing/node/InMemoryMessagingNetwork.kt
We have been seeing some errors when running unit tests using the InMemoryMessagingNetwork run in multi-threaded mode. It appears that the root cause is that Kryo transiently modifies the source ByteArray when reading strings. Therefore we must give each thread/node in the network a separate message data copy to make it thread safe.
> Fix errors with multi-thread InMemoryMessagingNetwork

- client/src/main/kotlin/net/corda/client/model/ContractStateModel.kt
- core/src/main/kotlin/net/corda/core/node/services/Services.kt
- core/src/test/kotlin/net/corda/core/node/VaultUpdateTests.kt
- node/src/main/kotlin/net/corda/node/services/api/ServiceHubInternal.kt
- node/src/main/kotlin/net/corda/node/services/events/ScheduledActivityObserver.kt
- node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt
Made vault updates contain full StateAndRef in the consumed set (instead of just StateRef). This allows subscribers to check whether the update contains relevant states.
Cash balances are now calculated by keeping only the aggregate values (it no longer needs to iterate through all states in the vault). The aggregate values are persisted.
> Refactor vault cash balance calculation

- node/src/integration-test/kotlin/net/corda/node/driver/DriverTests.kt
- node/src/integration-test/kotlin/net/corda/node/services/RaftValidatingNotaryServiceTests.kt
- node/src/integration-test/kotlin/net/corda/services/messaging/MQSecurityTest.kt
- node/src/main/kotlin/net/corda/node/driver/Driver.kt
- node/src/main/kotlin/net/corda/node/internal/Node.kt
- node/src/main/kotlin/net/corda/node/services/messaging/ArtemisMessagingComponent.kt
- node/src/main/kotlin/net/corda/node/services/messaging/ArtemisMessagingServer.kt
- node/src/main/kotlin/net/corda/node/services/messaging/NodeMessagingClient.kt
There is no requirement anymore for the nodes to start strictly after the network map, so we can optimise the driver by starting up the network map in parallel.
> node: Driver network map starts parallel with other nodes

- node/src/main/kotlin/net/corda/node/internal/CordaRPCOpsImpl.kt
- node/src/main/kotlin/net/corda/node/services/network/InMemoryNetworkMapCache.kt
- node/src/main/kotlin/net/corda/node/services/persistence/DBTransactionMappingStorage.kt
- node/src/main/kotlin/net/corda/node/services/persistence/DBTransactionStorage.kt
- node/src/main/kotlin/net/corda/node/services/statemachine/StateMachineManager.kt
- node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt
- node/src/main/kotlin/net/corda/node/utilities/DatabaseSupport.kt
- node/src/test/kotlin/net/corda/node/CordaRPCOpsImplTest.kt
- node/src/test/kotlin/net/corda/node/utilities/ObservablesTests.kt
Having made the observations _post database commit_ the `Observers` no longer have access to a database transaction.  This change re-introduces a database transaction for the `Observers`, so that they can interact with the database as needed, but it is distinct from that being observed.
Matthew encountered this when he updated to using the post-commit change.
Seems like this should have been easier, using more built in functionality but, alas, no.
> Add database transactions back onto observations.

- core/src/main/kotlin/net/corda/core/node/ServiceHub.kt
- finance/src/test/kotlin/net/corda/flows/IssuerFlowTest.kt
- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/main/kotlin/net/corda/node/services/api/ServiceHubInternal.kt
- node/src/main/kotlin/net/corda/node/services/statemachine/StateMachineManager.kt
- node/src/test/kotlin/net/corda/node/messaging/TwoPartyTradeProtocolTests.kt
- node/src/test/kotlin/net/corda/node/services/MockServiceHubInternal.kt
- node/src/test/kotlin/net/corda/node/services/NodeSchedulerServiceTest.kt
- node/src/test/kotlin/net/corda/node/services/statemachine/StateMachineManagerTests.kt
Check that the SMM.add method is being called on the SMM thread and throw if not. Make ServiceHubInternal.startFlow() do a blocking call onto the server thread. Update unit tests.
This resolves an issue whereby the scheduler was starting flows outside of the server thread, which isn't intended.
> Additional thread affinity for the StateMachineManager.

- .idea/runConfigurations/Raft_Notary_Demo__Run_Nodes.xml
- .idea/runConfigurations/Raft_Notary_Demo__Run_Notarisation.xml
- docs/source/running-the-demos.rst
Renamed distributed and notary demo to 'Raft Notary Demo' to improve consistency in naming. Since we're adding a BFT notary demo in the future the name "distributed notary demo" would be ambiguous at a later date, so Raft is picked.
> Made the Raft demo name consistent

- core/src/main/kotlin/net/corda/core/contracts/Structures.kt
- core/src/main/kotlin/net/corda/core/contracts/TransactionTypes.kt
- core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
- core/src/main/kotlin/net/corda/flows/AbstractStateReplacementFlow.kt
- core/src/main/kotlin/net/corda/flows/NotaryChangeFlow.kt
- core/src/test/kotlin/net/corda/core/contracts/TransactionEncumbranceTests.kt
- docs/source/example-code/src/main/kotlin/net/corda/docs/FxTransactionBuildTutorial.kt
- finance/src/main/java/net/corda/contracts/JavaCommercialPaper.java
- finance/src/main/kotlin/net/corda/contracts/asset/Cash.kt
- finance/src/main/kotlin/net/corda/schemas/CashSchemaV1.kt
- finance/src/test/java/net/corda/contracts/asset/CashTestsJava.java
- node/src/test/kotlin/net/corda/node/services/NotaryChangeTests.kt
- test-utils/src/main/kotlin/net/corda/testing/TestDSL.kt
- test-utils/src/main/kotlin/net/corda/testing/TransactionDSLInterpreter.kt
Also moved the encumbrance pointer from ContractState to TransactionState - during the notary change tx we sometimes need to modify the encumbrance pointer to reflect the new output indexes.
Continuing from the discussion in Discourse, this is the minimal fix that makes encumbrances usable, without introducing a new type of state.
Will clean up & add tests later, just want to get some feedback first.
> Update notary change flow to support encumbrances

- gradle-plugins/cordformation/src/main/resources/net/corda/plugins/runnodes.bat
- publish.properties
Before it would go into an infinite loop and crash the machine, or fail to start any nodes.
> Windows runnodes.bat now works from any working directory

- core/build.gradle
- node/src/main/kotlin/net/corda/node/utilities/DatabaseSupport.kt
(please excuse somewhat bogus branch title)
When upgrading previously we encountered some failing tests.  These could not be reproduced locally and so we suspected some kind of thread safety issue.  On further inspection it seems the database boundary related subject is obviously useable from multiple threads yet isn't _serialized_.  Converting this to the thread safe form using `toSerialized()` seems to resolve the issue after numerous runs of the branch in CI.  The run in CI after upgrading the library but before any other changes failed.
> Upgrade reactivex.rxjava version to latest 1.x

- gradle-plugins/cordformation/src/main/resources/net/corda/plugins/runnodes
1) Support users who run non-bash shells
2) Use /usr/bin/libexec to pick the right Java version, as currently Corda does not start on Java 9
> Two runnodes fixes for MacOS X

- docs/source/running-the-demos.rst
- samples/simm-valuation-demo/src/main/kotlin/net/corda/vega/Main.kt
There was naming inconsistency when run via CLI and IntelliJ. Additionally through IntelliJ Bank C node wasn't started (in documentation this node is used as an example that trade between A and B is not visible to C).
> Simm demo fix

- core/src/main/kotlin/net/corda/flows/NotaryFlow.kt
- node/src/test/kotlin/net/corda/node/services/NotaryServiceTests.kt
Alternatively, we could make the underlying UniquenessProviders idempotent.
> Make NotaryFlow idempotent

- client/src/integration-test/kotlin/net/corda/client/CordaRPCClientTest.kt
- docs/build/html/_sources/tutorial-clientrpc-api.txt
- docs/source/example-code/src/integration-test/kotlin/net/corda/docs/IntegrationTestingTutorial.kt
- docs/source/example-code/src/main/kotlin/net/corda/docs/ClientRpcTutorial.kt
- docs/source/tutorial-integration-testing.rst
- node/src/integration-test/kotlin/net/corda/node/driver/DriverTests.kt
- node/src/integration-test/kotlin/net/corda/node/services/DistributedServiceTests.kt
- node/src/main/kotlin/net/corda/node/driver/Driver.kt
- node/src/main/kotlin/net/corda/node/services/config/NodeConfiguration.kt
- samples/attachment-demo/src/integration-test/kotlin/net/corda/attachmentdemo/AttachmentDemoTest.kt
- samples/bank-of-corda-demo/src/integration-test/kotlin/net/corda/bank/BankOfCordaHttpAPITest.kt
- samples/bank-of-corda-demo/src/integration-test/kotlin/net/corda/bank/BankOfCordaRPCClientTest.kt
- samples/irs-demo/src/integration-test/kotlin/net/corda/irs/IRSDemoTest.kt
- samples/simm-valuation-demo/src/integration-test/kotlin/net/corda/vega/SimmValuationTest.kt
- samples/trader-demo/src/integration-test/kotlin/net/corda/traderdemo/TraderDemoTest.kt
- test-utils/src/main/kotlin/net/corda/testing/CoreTestUtils.kt
- tools/explorer/src/main/kotlin/net/corda/explorer/Main.kt
Added `NodeHandle.rpcClientToNode()` which uses the the node's configuration object to connect to as RPC. This simplifies existing driver code which connect to the node. 
Some of the existing code used `configureTestSSL()` to generate the required TSL keystores but since the driver starts the nodes in dev mode the node's settings are the same so we can get away with using the node's config object.
> Added a method to NodeHandle to simplify using RPC in the Driver

- core/src/main/kotlin/net/corda/core/contracts/ContractsDSL.kt
- finance/src/main/kotlin/net/corda/contracts/asset/Obligation.kt
- finance/src/test/java/net/corda/contracts/asset/CashTestsJava.java
- finance/src/test/kotlin/net/corda/contracts/asset/CashTests.kt
- finance/src/test/kotlin/net/corda/contracts/asset/ObligationTests.kt
The keys used to sign a command are tested for being a superset of the keys which own the states, not for being an exact match (as the text previously suggested). This corrects the message used if this requirement isn't met.
> Correct message when checking signing keys

- core/src/main/kotlin/net/corda/core/contracts/FinanceTypes.kt
- core/src/test/kotlin/net/corda/core/contracts/AmountTests.kt
Add new functions for converting amounts to/from decimal representation. Also adds clarification that the constructor which takes in a BigDecimal drops any fractional part.
Signed-off-by: Ross Nicoll <ross.nicoll@r3.com>
> Add functions for converting Amount to/from decimal

- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/main/kotlin/net/corda/node/services/events/NodeSchedulerService.kt
- node/src/main/kotlin/net/corda/node/services/statemachine/FlowStateMachineImpl.kt
- node/src/main/kotlin/net/corda/node/services/statemachine/StateMachineManager.kt
- node/src/test/kotlin/net/corda/node/services/ScheduledFlowTests.kt
- test-utils/src/main/kotlin/net/corda/testing/node/InMemoryMessagingNetwork.kt
- test-utils/src/main/kotlin/net/corda/testing/node/MockNode.kt
Solve race condition across testing various counters by moving to single threaded network and testing counters on that single thread.
> Fix intermittent failure in ScheduledFlowTests 

- docs/source/node-administration.rst
- node/capsule/build.gradle
- node/src/main/kotlin/net/corda/node/Corda.kt
- node/src/main/kotlin/net/corda/node/driver/Driver.kt
- samples/trader-demo/src/integration-test/kotlin/net/corda/traderdemo/TraderDemoTest.kt
Configure Capsule/Driver to give Corda a relatively poxy 200mb heap by default: we don't seem to need more for development purposes. Switch to G1GC by default and configure a default name for the VisualVM program to use.
> JVM argument tweaks

- docs/generate-docsite.sh
Use curl instead of wget, for compatibility with OS X.
> Use curl instead of wget

- build.gradle
- docs/generate-docsite.sh
- docs/source/_templates/layout.html
Docs: upgrade Dokka, start building a javadoc version of the API docs alongside the Kotlin API docs. Switch to using gradle to download/invoke it.
https://r3-cev.atlassian.net/browse/CORDA-153
There is more we can do here: the docs don't API link to the Java SDK or the javadoc sites of any of our libraries. Dokka and the gradle plugin *do* support this, but the syntax is confusing to me and the feature isn't well documented. I've filed CORDA-154 to track setting that up, but this is still an improvement.
I'll push a docsite regen after this is merged.
> Upgrade Dokka

- docs/source/consensus.rst
changing instances of "Notaries" to "notaries", reconciling them with the rest of the document
> enforcing consistency of capitalization

- node/src/main/kotlin/net/corda/node/Corda.kt
- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
Add logging to avoid node startup "hang" when it attempt to connects to the network map, also can use as a hint telling user Network map might be down or unreachable.
Fix for https://github.com/corda/corda/issues/97
> Add logging to node startup when it attempt to connect to the map server 

- core/src/main/kotlin/net/corda/core/serialization/Kryo.kt
This key pair generation takes up about 17% node thread CPU time
> Kryo: Remove unnecessary keypair generation

- node/src/test/kotlin/net/corda/node/services/statemachine/StateMachineManagerTests.kt
- test-utils/src/main/kotlin/net/corda/testing/node/InMemoryMessagingNetwork.kt
Remove TransferRecipient from StateMachineManagerTests to get rid one of the approximately 6 different ways in which we refer to endpoints, as part of work to simplify this data model.
Signed-off-by: Ross Nicoll <ross.nicoll@r3.com>
> Remove TransferRecipient

- core/src/main/kotlin/net/corda/flows/NotaryFlow.kt
- core/src/main/kotlin/net/corda/flows/ValidatingNotaryFlow.kt
- node/src/test/kotlin/net/corda/node/services/ValidatingNotaryServiceTests.kt
I'd appreciate thoughts on what the notary should be throwing, as I'm getting less convinced I'm even throwing an appropriate exception. Maybe the exception should simply wrap the cause instead of unpacking/repacking. Thoughts?
> Expand details in missing signatures error

- client/src/integration-test/kotlin/net/corda/client/NodeMonitorModelTest.kt
- core/src/main/kotlin/net/corda/core/messaging/CordaRPCOps.kt
- node/src/main/kotlin/net/corda/node/driver/Driver.kt
- node/src/main/kotlin/net/corda/node/internal/CordaRPCOpsImpl.kt
This PR adds an `isRegisteredWithNetworkMap` RPC, returning true once the node registered with the network map. This value is polled in the driver on node startup.
This fixes the current flakiness which is caused by a test node trying to notarise a tx before it knows about the notary party.
I also added the rpc proxy to `NodeHandle` as we always establish an rpc connection anyway. In another PR I'll change integ tests to use this instead of the current duplication of connections.
> Add isRegisteredWithNetworkMap RPC, poll in Driver, expose RPC proxy

- core/src/main/kotlin/net/corda/core/node/services/NetworkMapCache.kt
- node/src/main/kotlin/net/corda/node/services/network/InMemoryNetworkMapCache.kt
- node/src/test/kotlin/net/corda/node/services/InMemoryNetworkMapCacheTest.kt
InMemoryNetworkMapCacheTest was not actually asserting that an expected exception was thrown, which meant when earlier changes to the service changed the operation it wasn't caught. The service now overwrites previous node if a new matching node is added, and this updates the test to follow that design.
> Correct network map cache tests 

- node/capsule/build.gradle
- node/src/main/java/CordaCaplet.java
- node/src/main/kotlin/net/corda/node/internal/Node.kt
On first run a version file is created in the node dir, and on subsequent runs the node version is matched against it.
> Prevent node from starting across upgrades (until we support it better)

- core/src/main/kotlin/net/corda/core/flows/FlowLogic.kt
- core/src/main/kotlin/net/corda/core/flows/FlowLogicRef.kt
- core/src/main/kotlin/net/corda/core/flows/FlowStateMachine.kt
- core/src/main/kotlin/net/corda/core/messaging/Messaging.kt
- core/src/main/kotlin/net/corda/core/node/ServiceHub.kt
- core/src/main/kotlin/net/corda/core/node/services/Services.kt
- core/src/main/kotlin/net/corda/flows/BroadcastTransactionFlow.kt
- core/src/main/kotlin/net/corda/flows/FinalityFlow.kt
- core/src/main/kotlin/net/corda/flows/NotaryFlow.kt
- core/src/main/kotlin/net/corda/flows/ResolveTransactionsFlow.kt
- docs/source/example-code/src/main/kotlin/net/corda/docs/FxTransactionBuildTutorial.kt
- docs/source/example-code/src/main/kotlin/net/corda/docs/WorkflowTransactionBuildTutorial.kt
- docs/source/flow-state-machines.rst
- docs/source/release-notes.rst
- finance/src/main/kotlin/net/corda/flows/CashFlow.kt
- finance/src/main/kotlin/net/corda/flows/TwoPartyTradeFlow.kt
- node/build.gradle
- node/src/main/kotlin/net/corda/node/internal/CordaRPCOpsImpl.kt
- node/src/main/kotlin/net/corda/node/services/persistence/DataVendingService.kt
- node/src/main/kotlin/net/corda/node/services/statemachine/FlowIORequest.kt
- node/src/main/kotlin/net/corda/node/services/statemachine/FlowStateMachineImpl.kt
- node/src/main/kotlin/net/corda/node/services/statemachine/StateMachineManager.kt
- node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt
- node/src/test/kotlin/net/corda/node/services/statemachine/StateMachineManagerTests.kt
- samples/attachment-demo/src/integration-test/kotlin/net/corda/attachmentdemo/AttachmentDemoTest.kt
- samples/irs-demo/src/main/kotlin/net/corda/irs/flows/FixingFlow.kt
- samples/trader-demo/src/main/kotlin/net/corda/traderdemo/flow/SellerFlow.kt
Make FinalityFlow do more, and be used more consistently.
Add a new waitForLedgerCommit API that is intended to be used at the end of flows, or at any other point where a flow wants to wait for a transaction to finalise (but the finalisation flow is being done by someone else).
Update the docs a bit.
> Improve the flow commit API.

- node/src/main/kotlin/net/corda/node/services/network/InMemoryNetworkMapCache.kt
- test-utils/src/main/kotlin/net/corda/testing/node/MockNetworkMapCache.kt
Switch to using CompositeKey inside network map cache, so that look up of node info from keys
can be done in a more sensible manner. Follow on to #204
> Switch to using CompositeKey inside network map cache

- core/src/main/kotlin/net/corda/core/node/services/Services.kt
- finance/src/main/kotlin/net/corda/contracts/asset/Obligation.kt
- finance/src/main/kotlin/net/corda/contracts/clause/AbstractConserveAmount.kt
- finance/src/test/kotlin/net/corda/contracts/asset/CashTests.kt
- finance/src/test/kotlin/net/corda/contracts/asset/ObligationTests.kt
Remove dependency on name data that cash/obligation state objects will not have access to party details (such as name) once privacy is correctly enforced.
> Remove use of names from contracts

- docs/build/html/_sources/node-explorer.txt
- docs/build/html/node-explorer.html
- docs/source/node-explorer.rst
- tools/explorer/README.md
The current documentation incorrectly identifies the port numbers when running up the node explorer. This can lead to confusion as developers use the documentation over the log messages and fail to connect to the nodes.
> Fix incorrect port numbers in documentation for node explorer

- client/src/integration-test/kotlin/net/corda/client/CordaRPCClientTest.kt
- client/src/integration-test/kotlin/net/corda/client/NodeMonitorModelTest.kt
- client/src/main/kotlin/net/corda/client/mock/EventGenerator.kt
- docs/source/example-code/src/integration-test/kotlin/net/corda/docs/IntegrationTestingTutorial.kt
- docs/source/example-code/src/main/kotlin/net/corda/docs/ClientRpcTutorial.kt
- docs/source/example-code/src/test/kotlin/net/corda/docs/FxTransactionBuildTutorialTest.kt
- docs/source/running-the-demos.rst
- finance/src/main/kotlin/net/corda/flows/AbstractCashFlow.kt
- finance/src/main/kotlin/net/corda/flows/CashExitFlow.kt
- finance/src/main/kotlin/net/corda/flows/CashFlow.kt
- finance/src/main/kotlin/net/corda/flows/CashIssueFlow.kt
- finance/src/main/kotlin/net/corda/flows/CashPaymentFlow.kt
- finance/src/main/kotlin/net/corda/flows/IssuerFlow.kt
- node/src/integration-test/kotlin/net/corda/node/services/DistributedServiceTests.kt
- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/test/kotlin/net/corda/node/CordaRPCOpsImplTest.kt
- node/src/test/kotlin/net/corda/node/services/statemachine/StateMachineManagerTests.kt
- samples/bank-of-corda-demo/README.md
- samples/bank-of-corda-demo/build.gradle
- samples/bank-of-corda-demo/src/main/kotlin/net/corda/bank/BankOfCordaDriver.kt
- samples/bank-of-corda-demo/src/main/kotlin/net/corda/bank/api/BankOfCordaClientApi.kt
- tools/explorer/src/main/kotlin/net/corda/explorer/views/cordapps/cash/NewTransaction.kt
- tools/loadtest/src/main/kotlin/net/corda/loadtest/tests/CrossCashTest.kt
- tools/loadtest/src/main/kotlin/net/corda/loadtest/tests/GenerateHelpers.kt
- tools/loadtest/src/main/kotlin/net/corda/loadtest/tests/SelfIssueTest.kt
Split CashFlow into independent CashIssueFlow, CashExitFlow and CashPaymentFlow, so that users can be given access to one but not the other(s). This is part of work on a wider refactor of flows for cash.
> Split CashFlow into three flows

- core/src/main/kotlin/net/corda/core/flows/FlowLogic.kt
- node/src/main/kotlin/net/corda/node/services/statemachine/FlowIORequest.kt
- node/src/main/kotlin/net/corda/node/services/statemachine/FlowStateMachineImpl.kt
- node/src/main/kotlin/net/corda/node/services/statemachine/SessionMessage.kt
- node/src/main/kotlin/net/corda/node/services/statemachine/StateMachineManager.kt
- node/src/test/kotlin/net/corda/node/services/statemachine/StateMachineManagerTests.kt
- test-utils/src/main/kotlin/net/corda/testing/node/MockNode.kt
The new `waitForLedgerCommit` would wait forever if the other side (the committer) threw an exception before it did the FinalityFlow call.
> End flow if waiting for ledger commit and committer flow errors

- core/src/main/kotlin/net/corda/core/transactions/MerkleTransaction.kt
- core/src/test/kotlin/net/corda/core/crypto/PartialMerkleTreeTest.kt
- samples/irs-demo/src/main/kotlin/net/corda/irs/api/NodeInterestRates.kt
- samples/irs-demo/src/main/kotlin/net/corda/irs/flows/RatesFixFlow.kt
- samples/irs-demo/src/test/kotlin/net/corda/irs/testing/NodeInterestRatesTest.kt
Simplifies verification & no need to pass the root hash around
> Include merkle tree root hash in FilteredTransaction

- core/src/main/kotlin/net/corda/core/node/services/NetworkMapCache.kt
- core/src/main/kotlin/net/corda/core/node/services/ServiceType.kt
- core/src/main/kotlin/net/corda/flows/FinalityFlow.kt
- core/src/main/kotlin/net/corda/flows/NonValidatingNotaryFlow.kt
- core/src/main/kotlin/net/corda/flows/NotaryFlow.kt
- core/src/main/kotlin/net/corda/flows/ValidatingNotaryFlow.kt
- node/src/integration-test/kotlin/net/corda/node/services/RaftNotaryServiceTests.kt
- node/src/main/kotlin/net/corda/node/services/transactions/SimpleNotaryService.kt
- node/src/test/kotlin/net/corda/node/services/NotaryServiceTests.kt
Pass a FilteredTransaction instead of a Signed transaction to a non-validating notary flow to preserve privacy.
This also means that the non-validating notary can service requests on the network without loading any custom plugins, as it does not need to deserialize any commands/output states or run contract verification logic.
> Make non-validating notary use FilteredTransactions

- core/src/main/kotlin/net/corda/core/contracts/DummyContractV2.kt
- core/src/main/kotlin/net/corda/core/contracts/Structures.kt
- core/src/main/kotlin/net/corda/core/messaging/CordaRPCOps.kt
- core/src/main/kotlin/net/corda/core/node/services/Services.kt
- core/src/main/kotlin/net/corda/flows/ContractUpgradeFlow.kt
- core/src/test/kotlin/net/corda/core/flows/ContractUpgradeFlowTest.kt
- docs/source/contract-upgrade.rst
- docs/source/index.rst
- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/main/kotlin/net/corda/node/internal/CordaRPCOpsImpl.kt
- node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt
* Added missing out modifier to UpgradedContract class
* Added ContractUpgradeFlow.Instigator to whitelist in AbstractNode
* Added test for contract upgrade using RPC
> Example code for contract upgrade using RPC.

- gradle-plugins/cordformation/src/main/groovy/net/corda/plugins/Node.groovy
- publish.properties
Before they would all be in the dependencies directory.
> Cordformation now correctly includes and excludes cordapps.

- core/src/main/kotlin/net/corda/core/crypto/EncodingUtils.kt
- core/src/test/kotlin/net/corda/core/crypto/EncodingUtilsTest.kt
As basic `ByteArray` and `String` encoding/decoding operations are (and will be) required from multiple classes, especially inside the crypto-package, I created a utilities file (and it's corresponding unit-tests) to enlist some of the most common functions used for encoding (hex, base58, base64).
We can always add here new extension {en,de}coding functions, so we hopefully reuse code whenever required.
> Useful ByteArray and String {en,de}coding extension functions

- core/src/main/kotlin/net/corda/core/crypto/EncodingUtils.kt
- core/src/test/kotlin/net/corda/core/crypto/EncodingUtilsTest.kt
Some extra utilities to convert between base58, base64 and hex `String ` formats. This is useful for flexibility purposes + it will be required to convert crypto-keys and other data from and to CERTs.
> Change encoding between base58, base64, hex

- core/src/main/kotlin/net/corda/core/crypto/AbstractParty.kt
- core/src/main/kotlin/net/corda/core/crypto/AnonymousParty.kt
- core/src/main/kotlin/net/corda/core/crypto/Party.kt
- core/src/main/kotlin/net/corda/core/node/services/Services.kt
- core/src/main/kotlin/net/corda/flows/TwoPartyDealFlow.kt
- core/src/test/kotlin/net/corda/core/crypto/PartyTest.kt
- finance/src/main/kotlin/net/corda/contracts/asset/Cash.kt
- finance/src/main/kotlin/net/corda/contracts/asset/Obligation.kt
- finance/src/main/kotlin/net/corda/contracts/testing/DummyDealContract.kt
- finance/src/test/kotlin/net/corda/contracts/asset/CashTests.kt
- node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt
- samples/irs-demo/src/main/kotlin/net/corda/irs/flows/AutoOfferFlow.kt
- samples/simm-valuation-demo/src/main/kotlin/net/corda/vega/api/PortfolioApi.kt
- samples/simm-valuation-demo/src/main/kotlin/net/corda/vega/api/PortfolioApiUtils.kt
- samples/simm-valuation-demo/src/main/kotlin/net/corda/vega/contracts/SwapData.kt
- tools/explorer/src/main/kotlin/net/corda/explorer/views/cordapps/cash/NewTransaction.kt
- tools/loadtest/src/main/kotlin/net/corda/loadtest/tests/CrossCashTest.kt
- tools/loadtest/src/main/kotlin/net/corda/loadtest/tests/SelfIssueTest.kt
Introduce AbstractParty and have AnonymousParty and Party subclass it, such that where AnonymousParty is expected a Party cannot accidentally be supplied instead. Avoids a number of risk cases with the data persisted to the ledger. 
This isn't strictly needed after the previous patch, but I still think enforcing this via type safety is a good idea.
> Enforce separation of AnonymousParty and Party

- .gitignore
- build.gradle
- node/bft-smart-config/hosts.config
- node/bft-smart-config/system.config
- node/build.gradle
- node/src/main/kotlin/net/corda/node/internal/Node.kt
- node/src/main/kotlin/net/corda/node/services/transactions/BFTSmartUniquenessProvider.kt
- node/src/main/kotlin/net/corda/node/services/transactions/BFTValidatingNotaryService.kt
- node/src/main/kotlin/net/corda/node/services/transactions/DistributedImmutableBFTMap.kt
- node/src/test/kotlin/net/corda/node/services/DistributedImmutableBFTMapTests.kt
@adagys or others please take a look 😃
Work towards a [bft-smart prototype](https://r3-cev.atlassian.net/projects/CDT/issues/CORDA-5?filter=allopenissues), currently up to the `UniquenessProvider` plus some unfinished bits in an attempt to make a `BFTValidatingNotaryService` available as part of the Corda node.
The implementation is inspired by the [bft-smart map demo](https://github.com/bft-smart/library/blob/master/src/bftsmart/demo/bftmap/BFTMapServer.java#L43) and the `RaftNotary`.
> bft-smart notary prototype

- docs/build/html/_sources/oracles.txt
- docs/source/oracles.rst
Constructor for `FixOf` was updated in this commit https://github.com/corda/corda/commit/6c0e6961078cb5816c83f4cbfc1f02571af288c9#diff-e738b0f300324e8641cf05106b1e3d89L82 but documentation was not yet updated
> Fix typo in docs for FixOf where Duration should be Tenor

- core/src/main/resources/net/corda/core/node/cities.txt
Noticed that Hong Kong was missing in the `cities.txt` lookup table.
Here's the Google Maps link for reference: https://www.google.co.uk/maps/place/22%C2%B016'48.0%22N+114%C2%B009'36.0%22E/@22.2800248,114.1582843,17.28z/data=!4m5!3m4!1s0x0:0x0!8m2!3d22.28!4d114.16
> Add Hong Kong to list of cities in lookup table

- core/src/main/kotlin/net/corda/core/node/ServiceHub.kt
- core/src/main/kotlin/net/corda/core/node/services/Services.kt
- core/src/main/kotlin/net/corda/core/transactions/WireTransaction.kt
This PR factors out services needed for transaction resolution (`SignedTransaction` -> `LedgerTransaction`) into a new interface `ServicesForResolution`.
> core: Add ServicesForResolution interface

- docs/source/running-the-demos.rst
- samples/irs-demo/build.gradle
- samples/irs-demo/src/main/kotlin/net/corda/irs/IRSDemo.kt
- samples/irs-demo/src/main/kotlin/net/corda/irs/api/InterestRateSwapAPI.kt
- samples/irs-demo/src/main/kotlin/net/corda/irs/api/IrsDemoClientApi.kt
Override party keys from example-irs-trade.json file, so demos run correctly. Add api call to query for
Bank A and Bank B keys. Change port numbers, which are hardcoded in 2 places and were different when run through IntelliJ and through CLI.
> Fix IRS demo after Party changes.

- core/build.gradle
- node/build.gradle
The Maven `groupId` coordinate for Javassist has changed from `javassist` to `org.javassist` between v3.11.0.GA and v3.20.0-GA. This means that Gradle considers them to be distinct artifacts and so includes _both_ Javassist versions. We only want the latest version to be included.
The `core` project includes `javassist:javassist:3.11.0.GA` as a transitive dependency. The `node` project include `org.javassist:javassist:3.20.0-GA` via Hibernate. So we need to exclude `javassist:javassist` from any project that has `core` as a transitive dependency.
> Exclude old version of Javassist in favour of Hibernate's version from Node.

- node/capsule/build.gradle
When run in this way, it eliminates the overhead of a second JVM.
runnodes changes coming in another PR.
> Make the corda.jar executable on UNIX.

- node/src/main/kotlin/net/corda/node/services/messaging/CordaRPCClientImpl.kt
We had a warning in place to remind folks to `subscribe().unsubscribe()` from `Observables` returned from RPC.  That warning could never happen though, as the RPC layer held two strong references. Once in the consumer message handler and another in the cache of `Observers`.  I made both of these weak, but then we had a failing test due to early GC.  I created a work around to that using reference counting.  Hopefully the comments explain this.
Also noticed a typo.
> Allow escaped unsubscribed RPC Observables to be GC'd

- build.gradle
- node/build.gradle
See issue #342 
Upgrade to Catalyst 1.1.2, which also depends on Netty 4.1.5.Final.
Once both Catalyst and Artemis depend on the same version of Netty, we can remove the individual netty modules in favour of `netty-all` (as requested by Artemis).
> Ensure Node uses only a single version of Netty.

- core/src/main/kotlin/net/corda/core/crypto/CryptoUtilities.kt
Remove out of date documentation about the "covering" field of DigitalSignature, which no longer
exists.
> Remove out of date documentation

- gradle-plugins/cordformation/src/main/resources/net/corda/plugins/runnodes
- gradle-plugins/cordformation/src/main/resources/net/corda/plugins/runnodes.bat
Depends on #327 because it removes the explicit java version selection (the capsule is supposed to be able to do this itself).
> Allow web servers to be suppressed in runnodes and use direct execution.

- tools/explorer/build.gradle
Node Explorer does not need to use Kotlin 1.0.3, and can use 1.0.6 like the rest of Corda.
> Use the project's version of Kotlin to build Explorer.

- core/src/main/kotlin/net/corda/core/contracts/ContractsDSL.kt
- core/src/main/kotlin/net/corda/core/contracts/FinanceTypes.kt
- core/src/test/kotlin/net/corda/core/contracts/AmountTests.kt
The symbols are just conveniences (they are ambiguous so would not normally be used in pro-level apps).
> Amount: add support for basic parsing from text.

- core/src/main/kotlin/net/corda/core/node/services/Services.kt
- core/src/test/kotlin/net/corda/core/flows/ContractUpgradeFlowTest.kt
- finance/src/test/kotlin/net/corda/contracts/asset/CashTests.kt
- node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt
- node/src/test/kotlin/net/corda/node/services/NodeVaultServiceTest.kt
- node/src/test/kotlin/net/corda/node/services/VaultWithCashTest.kt
- node/src/test/kotlin/net/corda/node/services/persistence/DataVendingServiceTests.kt
Change return type to `Iterable` that is actually backed by a `Sequence` to achieve lazy state loading from Vault's DB. Both `VaultService.unconsumedStates()` and `VaultService.consumedStates()` have been affected. Unit-tests are aligned to reflect this change. No changes seem to be required on corda-tutorial and corda-template, respectively.
>  Lazy NodeVaultService.states

- build.gradle
- client/build.gradle
- core/build.gradle
- node/build.gradle
- test-utils/build.gradle
Corda uses the SLF4J logging API with Log4j2 as the sole SLF4J back-end. We therefore need to exclude Apache's `commons-logging:commons-logging` module in favour of SL4J's own `jcl-over-slf4j` module so that JARs using the `common-logging` API will integrate with SLF4J correctly.
As a rule, only Corda application modules (e.g. Node) should include an explicit dependency on Log4j2. The library modules should only require SLF4J.
> Refactor use of SLF4J's dependencies in Gradle.

- experimental/build.gradle
- experimental/src/main/kotlin/net/corda/carpenter/ClassCarpenter.kt
- experimental/src/test/kotlin/net/corda/carpenter/ClassCarpenterTest.kt
This is intended for use in the serialisation framework, to create stub classes when the original defining class for the binary schema isn't available on the classpath (i.e. not an installed app).
> Add experimental class building class (the 'carpenter').

- node/src/main/kotlin/net/corda/node/utilities/ANSIProgressObserver.kt
ArrayDeque FlowLogic references were not being removed on flow termination
Identified this memory leak in YourKitProfiler upon load testing soft locking.
> ANSIProgressObserver memory leak

- node/src/main/kotlin/net/corda/node/services/messaging/CordaRPCClientImpl.kt
This PR fixes a subtle (timeouting) deadlock that happens when when an RPC queue is closed while another message is being delivered
> rpc: Fix deadlock caused by deliver() and close()

- core/src/test/kotlin/net/corda/core/crypto/CryptoUtilsTest.kt
Removing unused vars and change set/get with indexing operator.
> Remove unused vars in CryptoUtilsTest

- client/jackson/build.gradle
- client/jackson/src/main/kotlin/net/corda/jackson/JacksonSupport.kt
- client/jackson/src/main/kotlin/net/corda/jackson/StringToMethodCallParser.kt
- client/jackson/src/test/kotlin/net/corda/jackson/JacksonSupportTest.kt
- client/jackson/src/test/kotlin/net/corda/jackson/StringToMethodCallParserTest.kt
- docs/source/changelog.rst
- samples/irs-demo/src/main/resources/example-irs-trade.json
- samples/irs-demo/src/main/resources/simulation/trade.json
- test-utils/src/main/kotlin/net/corda/testing/http/HttpUtils.kt
* Add explicit support for Amount<Currency> serialisation and deserialisation with a more convenient format, and backwards compatibility.
* Switch to using the official Jackson java.time support module instead of our own.
* Add a YaML string to method call parser class. This will be used later in the shell patch to enable you to invoke RPCs and flow constructors from the command line.
> Improvements to the Jackson module

- node/src/main/kotlin/net/corda/node/services/database/RequeryConfiguration.kt
RequeryConfiguration setting for table creation is now CREATE_NOT_EXISTS (was DROP_CREATE)
> Fix to prevent node dropping and re-creating Requery tables on startup

- node/src/main/kotlin/net/corda/node/utilities/JDBCHashMap.kt
formula used: `DEFAULT_MAX_BUCKETS = 256 * ( 1 + MAX(0, (maxHeapSize - 128) / 64))`
Two slightly different approaches have also been tested, here is the comparison chart:
> DEFAULT_MAX_BUCKETS based on max heap size

- core/src/main/kotlin/net/corda/core/serialization/CordaClassResolver.kt
- core/src/main/kotlin/net/corda/core/serialization/Kryo.kt
- core/src/test/kotlin/net/corda/core/node/AttachmentClassLoaderTests.kt
- core/src/test/kotlin/net/corda/core/serialization/KryoTests.kt
- node/src/main/kotlin/net/corda/node/serialization/DefaultWhitelist.kt
1. Stop returning meddled with Kryo's to the common pool in two sets of tests.
1. Kryo has a cache of class names to class instances that is incompatible with attachments.  Created a workaround and associated unit test.
1. Do not allow an attachment storage instance to be associated with a Kryo beyond the necessary scope.
1. Whilst investigating, found a class that needed to be on the serialisation whitelist.
> Several tests were corrupting Kryo which was then returned to the common pool.

- test-utils/src/main/kotlin/net/corda/testing/node/NodeBasedTest.kt
Ever since the RPC port split, the `CordaRPCClientTest` has experienced intermittent failures:
```
java.net.BindException: Address already in use
at sun.nio.ch.Net.bind0(Native Method)
```
Stop allocating multiple local ports using `freeLocalHostAndPort()` method, because this is unsafe. Use `getFreeLocalPorts()` instead.
> Fix intermittent BindException test failures.

- client/src/integration-test/kotlin/net/corda/client/CordaRPCClientTest.kt
- client/src/integration-test/kotlin/net/corda/client/NodeMonitorModelTest.kt
- client/src/main/kotlin/net/corda/client/mock/EventGenerator.kt
- core/src/main/kotlin/net/corda/core/contracts/FungibleAsset.kt
- docs/source/example-code/src/integration-test/kotlin/net/corda/docs/IntegrationTestingTutorial.kt
- docs/source/example-code/src/main/kotlin/net/corda/docs/ClientRpcTutorial.kt
- finance/src/main/kotlin/net/corda/flows/CashFlowCommand.kt
- finance/src/main/kotlin/net/corda/flows/CashPaymentFlow.kt
- finance/src/main/kotlin/net/corda/flows/IssuerFlow.kt
- node/src/integration-test/kotlin/net/corda/node/services/DistributedServiceTests.kt
- node/src/test/kotlin/net/corda/node/CordaRPCOpsImplTest.kt
- node/src/test/kotlin/net/corda/node/services/statemachine/StateMachineManagerTests.kt
- tools/explorer/src/main/kotlin/net/corda/explorer/views/cordapps/cash/NewTransaction.kt
- tools/loadtest/src/main/kotlin/net/corda/loadtest/tests/CrossCashTest.kt
- tools/loadtest/src/main/kotlin/net/corda/loadtest/tests/GenerateHelpers.kt
This makes it easier to use the payment flow from the shell.
I've done some manual testing on this with the bank of corda demo and using the payment flow from the command line. Regression tests and the Explorer app and the BoC demo all pass but oddly, when I make a payment via the shell, the payment flow stops because the notary expected a FilteredTransaction but got a SignedTransaction (or vice-versa, don't remember). I don't see why this change would cause that, so I have some debugging to do.
> De-issuerify the cash payment flow. 

- tools/explorer/src/main/kotlin/net/corda/explorer/Main.kt
Small correction on `issuerClientUSD = issuerNodeUSD.rpcClientToNode()`, causing 'exiting more cash than exists' errors.
> issuerNodeUSD fix on Explorer.Main

- core/build.gradle
Stop relying on `jcl-over-slf4j`'s transitive dependency on `slf4j-api` because this can confuse IntelliJ.
> Explicit dependency on SLF4J API, to help IntelliJ.

- build.gradle
Quick fix for `node-api` missing from publish list
> build: Fix publishing list

- node-schemas/build.gradle
Reason: This fixes the compile issues with IntelliJ.
> Generated files in node-schemas are now correctly identified by IntelliJ

- node/src/main/kotlin/net/corda/node/services/statemachine/FlowStateMachineImpl.kt
I intended to use this for performance tests only, but think it will be a useful metric for test/production deployments to detect performance degradation.
This exports a metric via JMX with the rate and duration distribution, which we can graph and potentially alert on.
> Record a metric for duration and rate of execution for every flow

- core/src/main/kotlin/net/corda/core/node/services/NetworkMapCache.kt
Fix isValidatingNotary check: throw exception if the provided party is not a notary
This will result in the client failing before sending an incorrect type of tx to the notary which leads to a more obscure error.
> Minor: Fix isValidatingNotary check

- tools/demobench/build.gradle
The platform version of Guava is 19.0, which exceeds DemoBench's own requirement. So use the platform version instead.
> Use platform version of Guava for DemoBench.

- tools/demobench/src/main/kotlin/net/corda/demobench/DemoBench.kt
- tools/demobench/src/main/kotlin/net/corda/demobench/explorer/Explorer.kt
- tools/demobench/src/main/kotlin/net/corda/demobench/pty/R3Pty.kt
- tools/demobench/src/main/kotlin/net/corda/demobench/rpc/NodeRPC.kt
- tools/demobench/src/main/kotlin/net/corda/demobench/web/DBViewer.kt
- tools/demobench/src/main/kotlin/net/corda/demobench/web/WebServer.kt
We've removed as much of Node as we can from DemoBench, so use this function from Core rather than reimplementing it.
> Use loggerFor() function from Core.

- gradle-plugins/cordformation/src/noderunner/kotlin/net/corda/plugins/NodeRunner.kt
The sleep is needed so that Terminal opens every process in a new tab properly. Starting all nodes at the same time just leads to a single new tab being open..
I also think it's useful to start the nodes in order, e.g. with Raft or BFT notaries the first node has to fully initialize before all others do.
> NodeRunner: fix OSX script. Add a delay before starting the next node.

- client/jackson/build.gradle
- core/build.gradle
- finance/build.gradle
Create a jar containing the `:core` project's test classes, and assign it classifier "tests" (which is the same classifier that Maven assigns to test artifacts).
Reference this test artifact in the `:client:jackson` and `:finance` modules.
> Create testArtifacts configuration for 'core' module.

- node/build.gradle
- `:finance` and `:node-schemas` no longer contain `junit-quickcheck-*` and so no longer need to exclude `javassist:javassist`.
- `RPCStructures.kt` has been moved to `:node-api`, and so we no longer need the `commons-fileupload` dependency here.
> Remove gradlisms that have leaked back in after merging.

- samples/irs-demo/src/integration-test/kotlin/net/corda/irs/IRSDemoTest.kt
- samples/irs-demo/src/main/kotlin/net/corda/irs/api/InterestRateSwapAPI.kt
- samples/irs-demo/src/main/kotlin/net/corda/irs/api/IrsDemoClientApi.kt
- samples/irs-demo/src/main/kotlin/net/corda/irs/api/NodeInterestRates.kt
- samples/irs-demo/src/main/kotlin/net/corda/irs/contract/IRS.kt
- samples/irs-demo/src/main/kotlin/net/corda/irs/contract/IRSExport.kt
- samples/irs-demo/src/main/kotlin/net/corda/simulation/IRSSimulation.kt
- samples/irs-demo/src/main/resources/example-irs-trade.json
- samples/irs-demo/src/test/kotlin/net/corda/irs/testing/IRSTests.kt
This removes the need for the IRS UI to manage mapping between well known identity names, and owning keys, by making the `State` object generic so it can hold either anonymous or full parties depending on context, then modifying the API to take in the full version.
> Modify IRS API to take states with full party

- node-schemas/generated/source/kapt/main/net/corda/node/services/vault/schemas/VaultStatesEntity.java
- node-schemas/src/main/kotlin/net/corda/node/services/vault/schemas/VaultSchema.kt
- node-schemas/src/test/kotlin/net/corda/node/services/vault/schemas/VaultSchemaTest.kt
Fix in vault schema so notary_key can have more key entries in CompositeKey, as it's kept as Base58 string. Change default varchar field with size 255 to text.
> Size of notary key in vault schema fix.

- core/src/main/kotlin/net/corda/core/crypto/CompositeKey.kt
Move algorithm and format into companion object so that they can be referenced from other
classes (i.e. the upcoming signature class).
> Move algorithm and format into companion object

- node/src/main/kotlin/net/corda/node/services/identity/InMemoryIdentityService.kt
- node/src/test/kotlin/net/corda/node/services/InMemoryIdentityServiceTests.kt
RBS report problems with multiple nodes being able to find each other in the identity service. This extends the name lookup test case to try three nodes, to check all of the stored values, and to use random keys rather than static.
> Extend identity service tests

- tools/demobench/build.gradle
- tools/demobench/src/main/kotlin/net/corda/demobench/explorer/Explorer.kt
- tools/demobench/src/main/kotlin/net/corda/demobench/model/InstallFactory.kt
- tools/demobench/src/main/kotlin/net/corda/demobench/model/NodeConfig.kt
- tools/demobench/src/main/kotlin/net/corda/demobench/model/User.kt
- tools/demobench/src/main/kotlin/net/corda/demobench/rpc/NodeRPC.kt
- tools/demobench/src/test/kotlin/net/corda/demobench/model/NodeConfigTest.kt
- tools/demobench/src/test/kotlin/net/corda/demobench/model/NodeControllerTest.kt
- tools/demobench/src/test/kotlin/net/corda/demobench/model/UserTest.kt
Use inherited `User` class rather than reimplementing it, and test that we can read the node's configuration file correctly.
> Chrisr3 demobench config

- core/src/main/kotlin/net/corda/flows/TxKeyFlowUtilities.kt
- core/src/test/kotlin/net/corda/core/flows/TxKeyFlow.kt
- core/src/test/kotlin/net/corda/core/flows/TxKeyFlowUtilitiesTests.kt
Add utility functions for requesting transaction keys and a small example flow which uses
these functions for testing purposes. These keys are required in for the anonymisation of
transactions, by providing per-transaction keys which cannot be associated with the owning
party's keys without an intermediary certificate.
> Add utility functions for requesting transaction keys

- docs/source/getting-set-up.rst
- docs/source/index.rst
Reason: Because otherwise the main docsite refers to an out of date release.
> Updated docs to refer to the latest M9.2 release.

- tools/demobench/src/main/kotlin/net/corda/demobench/pty/R3Pty.kt
DemoBench launches Corda with a copy of its environment, which means that Corda inherits the following environment variables on MacOSX;
```
TERM=xterm-256color
TERM_PROGRAM=iTerm.app
```
However, when Corda sees the `TERM_PROGRAM` environment variable, it assumes that the terminal supports emojis. But DemoBench uses JediTerm, which does  _not_ support emojis.
> Remove TERM_PROGRAM from Corda environment.

- build.gradle
- test-utils/src/main/kotlin/net/corda/testing/node/InMemoryMessagingNetwork.kt
Why: It seems Kotlin 1.0.7 has a bug with building the template that 1.1.1 doesn't have. Since we're aiming to upgrade to 1.1.x and the IntelliJ error has been fixed by https://github.com/corda/corda/pull/434 we can now proceed with this upgrade too. 
Once this is merged the template and tutorial will be fixed.
> Upgraded Kotlin version to 1.1.1 to fix issues with Cordapp building.

- verifier/build.gradle
- `kotlin-test` is the testing framework, and should not be at compile scope.
- We must exclude the Apache version of the `commons-logging` APIs in favour of SLF4J.
> Remove unwanted dependencies.

- build.gradle
- core/src/main/kotlin/net/corda/core/node/services/Services.kt
- node-schemas/generated/source/kapt/main/net/corda/node/services/vault/schemas/Models.java
- node-schemas/generated/source/kapt/main/net/corda/node/services/vault/schemas/VaultCashBalancesEntity.java
- node-schemas/generated/source/kapt/main/net/corda/node/services/vault/schemas/VaultStatesEntity.java
- node-schemas/generated/source/kapt/main/net/corda/node/services/vault/schemas/VaultTxnNoteEntity.java
- node-schemas/src/test/kotlin/net/corda/node/services/vault/schemas/VaultSchemaTest.kt
- node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt
- node/src/test/kotlin/net/corda/node/services/vault/NodeVaultServiceTest.kt
Updated Vault queries that were using standard JDBC SQL to use Requery DSL with composite key.
The only standard JDBC SQL query remaining is in Coin Selection - which uses a proprietary H2 session variable as an accumulator.
> Upgrade to Requery 1.2.1 with Composite Key support

- client/jackson/src/main/kotlin/net/corda/jackson/StringToMethodCallParser.kt
- core/src/main/kotlin/net/corda/core/flows/FlowLogicRef.kt
- core/src/main/kotlin/net/corda/core/node/ServiceHub.kt
- core/src/main/kotlin/net/corda/core/serialization/Kryo.kt
- core/src/main/kotlin/net/corda/flows/AbstractStateReplacementFlow.kt
- core/src/main/kotlin/net/corda/flows/TwoPartyDealFlow.kt
- core/src/test/kotlin/net/corda/core/flows/ContractUpgradeFlowTest.kt
- core/src/test/kotlin/net/corda/core/flows/ResolveTransactionsFlowTest.kt
- docs/source/example-code/src/test/kotlin/net/corda/docs/ExampleConfigTest.kt
- finance/src/main/kotlin/net/corda/contracts/testing/VaultFiller.kt
- finance/src/test/kotlin/net/corda/contracts/CommercialPaperTests.kt
- node-api/src/main/kotlin/net/corda/nodeapi/ArtemisTcpTransport.kt
- node/src/main/kotlin/net/corda/node/driver/Driver.kt
- node/src/main/kotlin/net/corda/node/internal/Node.kt
- node/src/main/kotlin/net/corda/node/services/messaging/ArtemisMessagingServer.kt
- node/src/main/kotlin/net/corda/node/services/transactions/RaftUniquenessProvider.kt
- node/src/test/kotlin/net/corda/node/services/DistributedImmutableMapTests.kt
- node/src/test/kotlin/net/corda/node/services/NodeSchedulerServiceTest.kt
- node/src/test/kotlin/net/corda/node/visualiser/GroupToGraphConversion.kt
- samples/irs-demo/src/main/kotlin/net/corda/irs/contract/IRS.kt
- samples/irs-demo/src/main/kotlin/net/corda/simulation/TradeSimulation.kt
- tools/loadtest/src/main/kotlin/net/corda/loadtest/ConnectionManager.kt
* Changed deprecated kotlin.reflect.primaryConstructor to kotlin.reflect.full.primaryConstructor
* Changed deprecated kotlin.reflect.memberProperties to kotlin.reflect.full.memberProperties
* Changed deprecated kotlin.reflect.declaredMemberProperties to kotlin.reflect.full.declaredMemberProperties
* Changed deprecated AllComposition to AllOf
* Changed deprecated AnyComposition to AnyOf
* Changed deprecated kotlin.reflect.KotlinReflectionInternalError to kotlin.reflect.jvm.internal.KotlinReflectionInternalError
* Changed deprecated HostAndPort.hostText to HostAndPort.host
* Removed duplicated method net.corda.core.node.recordTransactions
> Fixes for deprecated warnings

- build.gradle
- client/jackson/build.gradle
- client/jfx/src/main/kotlin/net/corda/client/jfx/model/ContractStateModel.kt
- client/jfx/src/main/kotlin/net/corda/client/jfx/model/NetworkIdentityModel.kt
- client/jfx/src/main/kotlin/net/corda/client/jfx/utils/AmountBindings.kt
- constants.properties
- core/build.gradle
- core/src/main/kotlin/net/corda/core/Utils.kt
- gradle-plugins/build.gradle
- gradle-plugins/cordformation/build.gradle
- gradle-plugins/cordformation/src/noderunner/kotlin/net/corda/plugins/NodeRunner.kt
- node-api/build.gradle
- node/build.gradle
- node/src/integration-test/kotlin/net/corda/services/messaging/P2PSecurityTest.kt
- node/src/main/kotlin/net/corda/node/services/schema/HibernateObserver.kt
- node/src/main/kotlin/net/corda/node/services/statemachine/StateMachineManager.kt
- samples/attachment-demo/build.gradle
- samples/bank-of-corda-demo/build.gradle
- samples/irs-demo/build.gradle
- samples/network-visualiser/build.gradle
- samples/raft-notary-demo/build.gradle
- samples/simm-valuation-demo/build.gradle
- samples/simm-valuation-demo/src/test/kotlin/net/corda/vega/SwapExample.kt
- samples/trader-demo/build.gradle
- test-utils/build.gradle
- tools/demobench/src/main/kotlin/net/corda/demobench/profile/ProfileController.kt
- tools/explorer/build.gradle
- tools/loadtest/src/main/kotlin/net/corda/loadtest/ConnectionManager.kt
- tools/loadtest/src/main/kotlin/net/corda/loadtest/LoadTest.kt
- verifier/build.gradle
We no longer need `kotlinx-support-jdk8` as of Kotlin 1.1.
> Replace kotlinx-support-jdk8 with kotlin-stdlib-jre8.

- client/jfx/src/main/kotlin/net/corda/client/jfx/utils/ObservableUtilities.kt
Original code compiles, but then throws a typecast expression at runtime when trying to process the lambdas. This means that the explorer will crash out as soon as there are cash states to load from the vault.
Hopefully, we can revert once there is a compiler fix, but for M10 we may have to live with this.
> Tactical fix for Explorer crash issue under Kotlin 1.1.1

- core/src/main/kotlin/net/corda/core/node/services/Services.kt
- finance/src/main/kotlin/net/corda/flows/CashExitFlow.kt
- node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt
This PR fixes a NotaryException (double spend) scenario whereby an Exit and Spend are executed concurrently, but the Exit flow was NOT soft locking any states in its coin selection.
> CashExitFlow now uses soft locked states

- core/src/main/kotlin/net/corda/core/contracts/ContractsDSL.kt
- core/src/main/kotlin/net/corda/core/contracts/FinanceTypes.kt
- core/src/test/kotlin/net/corda/core/contracts/AmountTests.kt
- docs/source/key-concepts-financial-model.rst
- finance/src/test/kotlin/net/corda/contracts/asset/CashTests.kt
- finance/src/test/kotlin/net/corda/contracts/asset/ObligationTests.kt
- tools/explorer/src/main/kotlin/net/corda/explorer/formatters/AmountFormatter.kt
- tools/explorer/src/main/kotlin/net/corda/explorer/views/cordapps/cash/NewTransaction.kt
This PR tries to address some concerns about Amount raised in the  CORDA-221, though at this stage this is really a discussion PR.
I have not gone with putting fixed precision arithmetic into Amount as the JIRA suggests! This caused lots of compilation problems and change that carried through to too many aspects of the system. More fundamentally the transactionally conserved, positive token concept of Amount is best represented as an unsigned Long as was already the case.
Therefore I have tackled instead the unit conversions that was leaking into consumers of the Amount code. Hopefully, this will prevent the all too familiar scaling problems encountered when applications forget to scale up/down from pennies to pounds and back. This is also based on the assumption that generally Amounts …
> Modify the Amount concept to allow conversion to from displayable formats

- tools/demobench/src/test/kotlin/net/corda/demobench/model/NodeConfigTest.kt
- webserver/build.gradle
- webserver/src/main/kotlin/net/corda/webserver/internal/NodeWebServer.kt
Removing `finance` from the WebServer means that the `BankOfCorda` plugin can no longer be instantiated. This generates a `NoClassDefFoundError` as the WebServer tries to boot:
```
Caused by: java.lang.NoClassDefFoundError: net/corda/flows/IssuerFlow$IssuanceRequester
at net.corda.bank.plugin.BankOfCordaPlugin.<init>(BankOfCordaPlugin.kt:16) ~[bank-of-corda.jar:?]
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_121]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_121]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_121]
at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_121]
at …
```
> Add 'finance' module to Corda WebServer, for plugins to use.

- core/src/main/kotlin/net/corda/core/node/services/Services.kt
- finance/src/main/kotlin/net/corda/contracts/clause/AbstractConserveAmount.kt
- finance/src/main/kotlin/net/corda/flows/CashExitFlow.kt
- node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt
- node/src/test/kotlin/net/corda/node/services/vault/NodeVaultServiceTest.kt
Added additional JUnit tests for coin selection by issuer.
Added some trace logging in AbstractConserveAmount.
> Fixed bug whereby Cash Exit was not taking into account the issuer reference

- docs/build.gradle
Why: sh mapping to dash and not bash in Ubuntu. 
The build server needs this fix ASAP, it has been broken on docs building for days.
> Fixed docsite building on Ubuntu by explicitly calling bash.

- finance/src/main/kotlin/net/corda/contracts/asset/Cash.kt
- finance/src/main/kotlin/net/corda/contracts/clause/AbstractConserveAmount.kt
- finance/src/test/kotlin/net/corda/flows/CashExitFlowTests.kt
- finance/src/test/kotlin/net/corda/flows/CashIssueFlowTests.kt
- finance/src/test/kotlin/net/corda/flows/CashPaymentFlowTests.kt
- node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt
Add tests for CashIssueFlow, CashPaymentFlow and CashExitFlow. While these were mostly covered by other tests already, CashExistFlow was not, and any bugs would be harder to identify because they are mixed in with other functionality (i.e. vault tests).
> Add Cash*Flow tests

- gradle-plugins/cordformation/src/main/resources/net/corda/plugins/runnodes
- gradle-plugins/cordformation/src/main/resources/net/corda/plugins/runnodes.bat
- gradle-plugins/cordformation/src/noderunner/kotlin/net/corda/plugins/NodeRunner.kt
Why: Previous behaviour was buggy - correct behaviour is to pass all args to the noderunner and not start crash in the headless mode.
> Args are correctly passed to node runner

- tools/demobench/src/main/kotlin/net/corda/demobench/DemoBench.kt
- tools/demobench/src/main/kotlin/net/corda/demobench/explorer/Explorer.kt
- tools/demobench/src/main/kotlin/net/corda/demobench/model/JVMConfig.kt
- tools/demobench/src/main/kotlin/net/corda/demobench/model/NodeController.kt
- tools/demobench/src/main/kotlin/net/corda/demobench/pty/R3Pty.kt
- tools/demobench/src/main/kotlin/net/corda/demobench/views/NodeTerminalView.kt
- tools/demobench/src/main/kotlin/net/corda/demobench/web/WebServer.kt
- tools/demobench/src/test/kotlin/net/corda/demobench/model/NodeControllerTest.kt
Alert the user if s/he tries to run DemoBench without installing it correctly.
> Avoid errors if Corda / Explorer cannot be found at runtime.

- client/rpc/src/integration-test/kotlin/net/corda/client/rpc/CordaRPCClientTest.kt
This integration test was accidentally left in the wrong module.
> Move CordaRPCClientTest into :client:rpc module.

- core/src/main/kotlin/net/corda/core/serialization/DefaultKryoCustomizer.kt
- core/src/test/kotlin/net/corda/core/serialization/KryoTests.kt
- node/src/main/kotlin/net/corda/node/services/persistence/NodeAttachmentService.kt
A solution for [#347](https://github.com/corda/corda/issues/347) and [#447](https://github.com/corda/corda/issues/447) where HashCheckingStream could not be (de)serialised. I've also registered FileInputStream as it may be required in attachments.
> Kryo register FileInputStream and addDefaultSerializer for InputStream

- docs/source/tutorial-building-transactions.rst
* Get IntelliJ to add quasar to new unit test configs instead of asking users to do it every time
* No need to modify working directory
> Improve Quasar agent config instructions for unit testing

- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/main/kotlin/net/corda/node/services/schema/HibernateObserver.kt
- node/src/test/kotlin/net/corda/node/services/HibernateObserverTests.kt
- test-utils/src/main/kotlin/net/corda/testing/node/MockServices.kt
Fixes https://github.com/corda/corda/issues/514
Switch from `StatelessSession` to normal `Session` since stateless version will not cascade persistence, and adds unit test to ensure persistence cascades.
Have run the Explorer demo in simulation mode (which repeatedly persists cash) connected to YourKit and it shows no memory leaks involving Hibernate so I think I have successfully disabled any caching and any other state retention (which is the original motivation for using `StatelessSession` since we are write-only).
> Fix up HibernateObserver to allow cascading persistence after bug report

- client/rpc/src/test/kotlin/net/corda/client/rpc/AbstractClientRPC.kt
- client/rpc/src/test/kotlin/net/corda/client/rpc/ClientRPCInfrastructureTests.kt
- client/rpc/src/test/kotlin/net/corda/client/rpc/RPCPermissionsTest.kt
These tests were misplaced when `client:rpc` module was created.
> Restore :client:rpc unit tests to their correct location.

- core/src/main/kotlin/net/corda/core/node/Version.kt
- core/src/test/kotlin/net/corda/core/node/VersionTest.kt
- node/src/main/kotlin/net/corda/node/Corda.kt
- test-utils/src/main/kotlin/net/corda/testing/CoreTestUtils.kt
Why: We use patch versions often.
> [M10 Fixes] Version number parser can now handle patch versions.

- docs/source/getting-set-up.rst
The path .idea/runConfiguration doesn't exist in git, it should be .idea/runConfigurations
> Fix always-failing command in Getting set up documentation

- core/src/main/kotlin/net/corda/core/contracts/ContractsDSL.kt
- core/src/main/kotlin/net/corda/core/contracts/Structures.kt
- core/src/main/kotlin/net/corda/flows/ContractUpgradeFlow.kt
- core/src/test/kotlin/net/corda/core/contracts/TransactionEncumbranceTests.kt
- docs/source/example-code/src/main/kotlin/net/corda/docs/WorkflowTransactionBuildTutorial.kt
- docs/source/tutorial-contract-clauses.rst
- docs/source/tutorial-contract.rst
- docs/source/tutorial-cordapp.rst
- experimental/src/main/kotlin/net/corda/contracts/universal/UniversalContract.kt
- finance/src/main/java/net/corda/contracts/JavaCommercialPaper.java
- finance/src/main/kotlin/net/corda/contracts/CommercialPaper.kt
- finance/src/main/kotlin/net/corda/contracts/CommercialPaperLegacy.kt
- finance/src/main/kotlin/net/corda/contracts/asset/Obligation.kt
- finance/src/main/kotlin/net/corda/contracts/clause/AbstractConserveAmount.kt
- finance/src/main/kotlin/net/corda/contracts/clause/AbstractIssue.kt
- finance/src/main/kotlin/net/corda/contracts/clause/Net.kt
- finance/src/main/kotlin/net/corda/contracts/clause/NoZeroSizedOutputs.kt
- samples/irs-demo/src/main/kotlin/net/corda/irs/contract/IRS.kt
- samples/simm-valuation-demo/src/main/kotlin/net/corda/vega/contracts/PortfolioSwap.kt
The `ContractsDSL` overloads the Kotlin `by` keyword. User feedback from training courses indicates that a better choice would be `using` to avoid any confusion with built-in DSLs.
This PR covers
* changing `by` to `using` in `ContractsDSL`
* refactoring all uses within the Corda codebase
* providing a `ReplaceWith` definition to assist downstream users with automatic migration
To test:
1. Open `CommercialPaper` in Intellij and locate the `using` keyword (line 146)
2. Change to `by`
3. Observe deprecated status with comment
4. Use auto-correct to replace with `using` either at individual or project level
> Replace 'by' with 'using' to avoid overloading Kotlin keyword

- samples/irs-demo/build.gradle
- samples/irs-demo/src/integration-test/kotlin/net/corda/irs/IRSDemoTest.kt
- samples/simm-valuation-demo/build.gradle
- samples/simm-valuation-demo/src/integration-test/kotlin/net/corda/vega/SimmValuationTest.kt
- samples/trader-demo/build.gradle
- samples/trader-demo/src/integration-test/kotlin/net/corda/traderdemo/TraderDemoTest.kt
- samples/trader-demo/src/main/kotlin/net/corda/traderdemo/TraderDemoClientApi.kt
- test-utils/src/main/kotlin/net/corda/testing/node/NodeBasedTest.kt
Why: The tests below are a hotbed for false positives due to a lack of assertions about the final state.
What: Each of the tests now have checks to verify various quantities to ensure the final output is what we're expecting. To avoid making the tests more brittle I have avoided testing details that would be too specific.
> Improve robustness of integration tests that commonly have false positives

- core/src/main/kotlin/net/corda/core/crypto/CompositeSignature.kt
- core/src/main/kotlin/net/corda/core/crypto/CompositeSignaturesWithKeys.kt
- core/src/main/kotlin/net/corda/core/crypto/CryptoUtilities.kt
- core/src/main/kotlin/net/corda/core/transactions/SignedTransaction.kt
- core/src/test/kotlin/net/corda/core/crypto/CompositeKeyTests.kt
- docs/source/changelog.rst
- docs/source/release-notes.rst
- node/src/test/kotlin/net/corda/node/CordaRPCOpsImplTest.kt
Add `CompositeSignature` engine and `CompositeSignatureData` type as part of next steps towards integrating composite signatures with the Java standard crypto libraries.
This doesn't add this to the signature types recognised by Corda yet, that work requires further extensions (such as a key generator).
> Add composite signature engine

- build.gradle
- constants.properties
- gradle-plugins/cordformation/build.gradle
- gradle-plugins/cordformation/src/noderunner/kotlin/net/corda/plugins/NodeRunner.kt
The use of double-quotes for the debug port argument string breaks the MacOS start script. Using single fixes it. I need you both to test on your respective machines that runnodes is still working.
> Fixed broken NodeRunner on MacOS

- docs/source/clientrpc.rst
Fix link destinations for `CordaRPCOps` and `CordaRPCClient` classes on the [Doc Site](https://docs.corda.net/clientrpc.html). These have been broken since the module structure was refactored.
> Fix broken documentation links for RPC classes.

- build.gradle
(demobench upgrade depends on this because new TornadoFX uses Java 8 bytecode and so can't be inlined into Java 6 classes)
> Make Kotlin emit Java 8 bytecode and parameter reflection data

- core/src/main/kotlin/net/corda/core/utilities/TestConstants.kt
... causing failing code using CHARLIE as a test key.
> Fix incorrectly referenced public key.

- docs/source/changelog.rst
Renaming DemoBench is not an API change!
> Fix M11 changelog entry for DemoBench.

- core/src/main/kotlin/net/corda/core/contracts/FungibleAsset.kt
- docs/source/changelog.rst
- finance/src/main/kotlin/net/corda/contracts/asset/Cash.kt
- finance/src/main/kotlin/net/corda/contracts/asset/CommodityContract.kt
- finance/src/main/kotlin/net/corda/contracts/asset/Obligation.kt
- finance/src/main/kotlin/net/corda/contracts/asset/OnLedgerAsset.kt
- finance/src/main/kotlin/net/corda/contracts/clause/AbstractConserveAmount.kt
- node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt
Move generateSpend() into AbstractConserveAmount and make it generic enough to use for other
similar contracts to cash, rather than just cash. Also removes duplicated logic in gathering
coins.
> Move generateSpend() into AbstractConserveAmount (revised)

- docs/source/running-the-demos.rst
Correct the IRS demo web server ports in the documentation to match the ports specified
in samples/irs-demo/build.gradle.
> Correct IRS web server ports

- build.gradle
- experimental/sandbox/build.gradle
- experimental/sandbox/src/main/java/net/corda/sandbox/Utils.java
- experimental/sandbox/src/main/java/net/corda/sandbox/tools/SandboxCreator.java
- experimental/sandbox/src/main/java/net/corda/sandbox/visitors/WhitelistCheckingClassVisitor.java
- experimental/sandbox/src/main/java/net/corda/sandbox/visitors/WhitelistCheckingMethodVisitor.java
- experimental/sandbox/src/test/java/net/corda/sandbox/CandidateMethodTest.java
- Upgrade to SLF4J 1.7.25 (as required by Logback)
- Inherit properties from top-level build file.
- Create executable fat jar.
- Remove unused imports.
> Integrate sandbox properly with top-level build.

- tools/demobench/src/main/kotlin/net/corda/demobench/views/NodeTerminalView.kt
Ignore exceptions when unsubscribing from Observables because they prevent DemoBench shutting down properly.
> Fix DemoBench shutdown, even when failing to unsubscribe from an Observable.

- node/src/integration-test/kotlin/net/corda/node/services/BFTNotaryServiceTests.kt
BFTNotaryServiceTests generates a master node independently of the cluster nodes, so it can put it
at the end of the list of nodes. The calling function however treats the first node in the list as
the master, not the last node. This simplifies the code while maintaining the same behaviour.
> Clean up BFTNotaryServiceTests

- build.gradle
- client/jfx/build.gradle
- client/mock/build.gradle
- client/rpc/build.gradle
- core/build.gradle
- docs/source/example-code/build.gradle
- finance/build.gradle
- finance/isolated/build.gradle
- node-api/build.gradle
- node/build.gradle
- node/capsule/build.gradle
- samples/attachment-demo/build.gradle
- samples/bank-of-corda-demo/build.gradle
- samples/irs-demo/build.gradle
- samples/raft-notary-demo/build.gradle
- samples/simm-valuation-demo/build.gradle
- samples/trader-demo/build.gradle
- tools/explorer/build.gradle
- tools/loadtest/build.gradle
- verifier/build.gradle
- webserver/build.gradle
- webserver/webcapsule/build.gradle
Copy the log4j2.xml files manually during the resource processing steps in gradle. This avoids the problem where IntelliJ identifies the config folders as being used in multiple projects.
This should address the following issues:
https://github.com/corda/corda/issues/525
https://github.com/corda/corda/issues/553
https://github.com/corda/corda/issues/325
> Fix duplicate content root problems in IntelliJ

- core/src/main/kotlin/net/corda/core/Utils.kt
- core/src/main/kotlin/net/corda/core/utilities/Logging.kt
- docs/source/example-code/src/integration-test/kotlin/net/corda/docs/IntegrationTestingTutorial.kt
- node/src/main/kotlin/net/corda/node/services/statemachine/FlowStateMachineImpl.kt
* Previously the futures stack was likely to be empty, so failure in startFlow was not caught and would result in the test hanging
* Minor unrelated improvements
> Fix race in IntegrationTestingTutorial.

- docs/source/tutorial-building-transactions.rst
so that errors due to missing @Suspendable are less cryptic.
* Previously it was possible for a test to succeed in the IDE but fail in the Gradle build, as the Gradle build enables verifyInstrumentation and it's a little too strict
* IntelliJ only looks at the default config when creating a new test config, so users are free to remove verifyInstrumentation from individual test configs for performance
> Add note for enabling verifyInstrumentation in IntelliJ

- webserver/build.gradle
- webserver/src/main/kotlin/net/corda/webserver/internal/NodeWebServer.kt
- webserver/src/main/kotlin/net/corda/webserver/servlets/CorDappInfoServlet.kt
First stab at a rough and ready index page for the web server which displays the api end-points available as well as any static content served and all whitelisted flows. Useful for when you can't remember the paths to your api end-points.
TODO: Enumerate all flow initiators as well.
> Rog webserver index

- node/capsule/build.gradle
- node/src/main/kotlin/net/corda/node/Corda.kt
- node/src/main/kotlin/net/corda/node/driver/Driver.kt
We need to set the jdk.serialFilter system property in the Capsule, as anywhere else may be too late. E.g. for the JVM on Windows.
> Fix deserialisation check for JDK on all platforms.

- core/src/main/kotlin/net/corda/core/node/services/Services.kt
- core/src/main/kotlin/net/corda/core/serialization/Kryo.kt
- core/src/main/kotlin/net/corda/core/serialization/SerializationToken.kt
- core/src/test/kotlin/net/corda/core/node/AttachmentClassLoaderTests.kt
- core/src/test/kotlin/net/corda/core/serialization/SerializationTokenTest.kt
- node/src/main/kotlin/net/corda/node/services/persistence/StorageServiceImpl.kt
- node/src/main/kotlin/net/corda/node/services/statemachine/StateMachineManager.kt
- test-utils/src/main/kotlin/net/corda/testing/node/MockServices.kt
* The mechanism is currently under review in https://github.com/corda/corda/pull/543
* attachmentsClassLoaderEnabled is only ever true in the unit test, to preserve current behaviour
> Replace code only used in 1 test with existing general mechanism.

- node/src/main/kotlin/net/corda/node/Corda.kt
- node/src/main/kotlin/net/corda/node/driver/Driver.kt
Give the user more useful information when Corda refuses to boot.
> Customise the error message according to why Corda cannot boot.

- build.gradle
- constants.properties
- gradle-plugins/cordformation/build.gradle
- gradle-plugins/cordformation/src/main/groovy/net/corda/plugins/Node.groovy
Strip commas from node legal name before assembling path, to work around Windows treating the comma as a separator and then complaining the extension is too long.
> Strip commas from node paths

- finance/src/main/java/net/corda/contracts/JavaCommercialPaper.java
- finance/src/main/kotlin/net/corda/contracts/CommercialPaper.kt
- finance/src/main/kotlin/net/corda/contracts/CommercialPaperLegacy.kt
- finance/src/main/kotlin/net/corda/flows/TwoPartyTradeFlow.kt
- node/src/test/kotlin/net/corda/node/messaging/TwoPartyTradeFlowTests.kt
This is a general Quasar requirement which surfaced as a bug in the `TwoPartyTradeFlow` whereby the `Buyer` call flow was calling a private method `assembleSharedTX` (non-annotated with @Suspendable) which in turn was calling the vault `generateSpend` @Suspendable annotated method.
This PR ensures all callers to `generateSpend` are also annotated with @Suspendable.
The manifestation of this error caused the following unhelpful exception:
**Caught exception from flow
// java.lang.IllegalStateException: No transaction in context.**
> Apply @Suspendable on all flow methods that call vault generateSpend

- core/src/main/resources/net/corda/core/node/cities.txt
- samples/irs-demo/src/main/kotlin/net/corda/simulation/Simulation.kt
- samples/network-visualiser/src/main/kotlin/net/corda/netmap/VisualiserViewModel.kt
* Restore missing cities to cities.txt.
* Only display the common name for each node, not the full X500 name.
> Fixes for Network Visualiser

- docs/source/changelog.rst
- docs/source/conf.py
- docs/source/flow-state-machines.rst
- docs/source/getting-set-up-fault-finding.rst
- docs/source/inthebox.rst
- docs/source/key-concepts-consensus-notaries.rst
- docs/source/release-notes.rst
- docs/source/tutorial-clientrpc-api.rst
- docs/source/tutorial-contract.rst
Update documentation for M11, and draw line for start of M12.
> M11 documentation

- core/src/test/kotlin/net/corda/core/crypto/X509UtilitiesTest.kt
Expand string names in X509UtilitiesTest into full X500 names, so it's clearer what the final name will be. Also use the standard MEGA_CORP identity rather than making up our own.
> Clean up X.500 names in X509UtilitiesTest

- core/src/main/kotlin/net/corda/core/contracts/Structures.kt
- samples/attachment-demo/build.gradle
- samples/attachment-demo/src/main/kotlin/net/corda/attachmentdemo/AttachmentDemo.kt
- webserver/src/main/kotlin/net/corda/webserver/servlets/AttachmentDownloadServlet.kt
- webserver/src/main/kotlin/net/corda/webserver/servlets/CorDappInfoServlet.kt
- webserver/src/main/kotlin/net/corda/webserver/servlets/DataUploadServlet.kt
- webserver/src/main/kotlin/net/corda/webserver/servlets/ResponseFilter.kt
The /attachments HTTP endpoint on the WebServer needs to use `CordaRPCOps` instead of `StorageService`. Update `attachment-demo` to test this functionality as well.
> Fix downloading attachments from WebServer.

- core/src/main/kotlin/net/corda/core/crypto/X509Utilities.kt
- core/src/main/kotlin/net/corda/core/utilities/TestConstants.kt
- core/src/test/kotlin/net/corda/core/crypto/X509UtilitiesTest.kt
- docs/source/creating-a-cordapp.rst
- samples/attachment-demo/build.gradle
- samples/bank-of-corda-demo/build.gradle
- samples/irs-demo/build.gradle
- samples/irs-demo/src/main/kotlin/net/corda/simulation/Simulation.kt
- samples/irs-demo/src/main/resources/example-irs-trade.json
- samples/irs-demo/src/main/resources/irsweb/js/viewmodel/FloatingLeg.js
- samples/simm-valuation-demo/build.gradle
- samples/simm-valuation-demo/src/main/resources/simmvaluationweb/app/viewmodel/FloatingLegViewModel.js
- samples/simm-valuation-demo/src/main/web/src/app/viewmodel/FloatingLegViewModel.ts
- samples/trader-demo/build.gradle
- test-utils/src/main/kotlin/net/corda/testing/CoreTestUtils.kt
- tools/demobench/src/test/kotlin/net/corda/demobench/model/NodeConfigTest.kt
- tools/explorer/src/main/kotlin/net/corda/explorer/Main.kt
Clean up X500 names in Corda simulation, and ensure they're consistent with the standard test names. This includes using the locations present in those test names, which requires updates to the node config test.
> Clean up X500 names in Corda simulation

- core/src/main/kotlin/net/corda/core/node/ServiceHub.kt
- core/src/main/kotlin/net/corda/core/node/services/Services.kt
- node/src/main/kotlin/net/corda/node/services/api/SchedulerService.kt
- node/src/main/kotlin/net/corda/node/services/api/ServiceHubInternal.kt
- node/src/main/kotlin/net/corda/node/services/events/NodeSchedulerService.kt
- node/src/test/kotlin/net/corda/node/services/MockServiceHubInternal.kt
- test-utils/src/main/kotlin/net/corda/testing/node/MockServices.kt
The scheduler service is an internal component of the node machinery. It should not be directly visible on the ServiceHub, because flows should record SchedulableState items to the vault and they will automatically be run.
> Remove scheduler service from ServiceHub

- core/src/main/kotlin/net/corda/core/flows/FlowLogic.kt
- core/src/main/kotlin/net/corda/core/flows/FlowStateMachine.kt
- core/src/main/kotlin/net/corda/flows/NotaryFlow.kt
- node/src/integration-test/kotlin/net/corda/services/messaging/P2PMessagingTest.kt
- node/src/main/kotlin/net/corda/node/services/config/NodeConfiguration.kt
- node/src/main/kotlin/net/corda/node/services/messaging/Messaging.kt
- node/src/main/kotlin/net/corda/node/services/messaging/NodeMessagingClient.kt
- node/src/main/kotlin/net/corda/node/services/statemachine/FlowSession.kt
- node/src/main/kotlin/net/corda/node/services/statemachine/FlowStateMachineImpl.kt
- node/src/main/kotlin/net/corda/node/services/statemachine/StateMachineManager.kt
- node/src/test/kotlin/net/corda/node/InteractiveShellTest.kt
- test-utils/src/main/kotlin/net/corda/testing/CoreTestUtils.kt
- test-utils/src/main/kotlin/net/corda/testing/node/InMemoryMessagingNetwork.kt
Add support for re-sending session messages. This is useful when talking to a distributed service, e.g. notary – if one of the nodes go down in the middle of a session, the session will be re-established with a different node (round-robin order).
I introduced a new method in `FlowLogic`: `sendAndReceiveWithRetry`, which creates a new `FlowSession` and marks it as _idempotent_. The `SessionInit` message of such session is then scheduled to be redelivered in the `NodeMessagingClient` until a `SessionData` or `SessionEnd` is received. Duplicate `SessionConfirm` responses are ignored.
> Notarisation retry

- build.gradle
- node/build.gradle
- node/capsule/build.gradle
- tools/explorer/build.gradle
- verifier/build.gradle
- webserver/build.gradle
- webserver/webcapsule/build.gradle
An application (e.g. DemoBench) may have its own `log4j2.xml`, but Log4J will use the first `log4j2.xml` file that it finds on the classpath. And so we do not want every Corda library jar to contain a copy of Node's `log4j2.xml`.
Technically, Node Explorer and Verifier should have their own `log4j2.xml` files and not use Node's.
This fixes #633.
> Include log4j2.xml into application jars only.

- build.gradle
- node/src/main/kotlin/net/corda/node/driver/Driver.kt
Prevent the unit and integration tests from creating files outside of Gradle's $buildDir.
> Set java.io.tmpdir to Gradle's build directory for tests.

- core/src/main/kotlin/net/corda/core/flows/FlowLogicRef.kt
- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/main/kotlin/net/corda/node/services/api/ServiceHubInternal.kt
- node/src/main/kotlin/net/corda/node/services/events/NodeSchedulerService.kt
- node/src/main/kotlin/net/corda/node/services/statemachine/FlowLogicRefFactoryImpl.kt
- node/src/test/java/net/corda/node/services/events/FlowLogicRefFromJavaTest.java
- node/src/test/kotlin/net/corda/node/services/MockServiceHubInternal.kt
- node/src/test/kotlin/net/corda/node/services/events/FlowLogicRefTest.kt
- node/src/test/kotlin/net/corda/node/services/events/NodeSchedulerServiceTest.kt
The FlowLogicRefFactory in core is an implementation detail not a part of the main API, except via its interaction with SchedulableState. Therefore move the logic internal to the node.
> Move the implementation of the FlowLogicRefFactory internal

- core/src/main/kotlin/net/corda/core/crypto/X509Utilities.kt
- node/src/integration-test/kotlin/net/corda/node/services/BFTNotaryServiceTests.kt
- node/src/main/kotlin/net/corda/node/driver/Driver.kt
- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
* Mark several functions in X509Utilities as @JvmStatic so they're readily accessible from Java.
* Add functions for modifying common name of an X.500 name, either direct replacement or adding a postfix.
> Expand X509Utilities

- core/src/main/kotlin/net/corda/core/crypto/Crypto.kt
- core/src/main/kotlin/net/corda/core/crypto/CryptoUtils.kt
Move the implementation of entropyToKeyPair from CryptoUtils to Crypto, as per convention and for security reasons, all important cryptographic operations/calculations should be done inside Crypto.
Currently EdDSA is the sole algorithm supported, as we need more sophisticated deterministic key generation algorithms per case.
> Move keyPairFromEntropy to Crypto.kt

- core/src/main/kotlin/net/corda/core/crypto/Crypto.kt
- core/src/test/kotlin/net/corda/core/crypto/CryptoUtilsTest.kt
Check if a point's coordinates are on the expected curve to avoid certain types of ECC attacks.
Point-at-infinity is not permitted.
See [Small subgroup and invalid-curve attacks](https://safecurves.cr.yp.to/twist.html) for a more descriptive explanation on such attacks.
The above validation check currently applies to ECDSA (both R1 and K1 curves) and EdDSA (ed25519 curve).
> Check that a public key (EC point) lies on its corresponding curve.

- core/src/main/kotlin/net/corda/core/crypto/CryptoUtils.kt
- core/src/main/kotlin/net/corda/core/crypto/EncodingUtils.kt
- core/src/main/kotlin/net/corda/core/serialization/Kryo.kt
- experimental/src/main/kotlin/net/corda/contracts/universal/PrettyPrint.kt
- samples/raft-notary-demo/src/main/kotlin/net/corda/notarydemo/NotaryDemo.kt
Addressing the [PublicKey friendly print](https://github.com/corda/corda/issues/621) issue, by using `PublicKey.toStringShort()` when possible.
The new scheme agnostic format for the short string is the key's hash (in Base58) of its serialised form using the DL prefix: `PublicKey.toStringShort(): String  = "DL" + this.toSHA256Bytes().toBase58()`
> Generic PublicKey.toStringShort()

- core/src/main/kotlin/net/corda/core/flows/FlowException.kt
- node/src/main/kotlin/net/corda/node/services/statemachine/SessionMessage.kt
- node/src/test/kotlin/net/corda/node/services/statemachine/FlowFrameworkTests.kt
FlowSessionException is currently in node, which prevents it from being serialised and sent to the client. Move this exception into core.
> Move FlowSessionException into core so that it can be serialised.

- core/src/main/kotlin/net/corda/core/messaging/FlowHandle.kt
- node/src/main/kotlin/net/corda/node/internal/CordaRPCOpsImpl.kt
We cannot send FlowHandle classes across via RPC because the clients do not have the private implementation classes. So move these implementations back into code.
Fixes #650.
> Move FlowHandle implementations back into core.

- tools/demobench/src/main/kotlin/net/corda/demobench/explorer/Explorer.kt
Windows 10 throws a `FileSystemException` (child of `IOException`) if the user is not permitted to create symlinks. So catch any `IOException` thrown by `createSymbolicLink()` and try to copy the file instead.
Fixes #658
> Try to copy the CorDapp if we fail to create a symlink, e.g. on Win10.

- node/src/integration-test/kotlin/net/corda/node/BootTests.kt
- node/src/integration-test/kotlin/net/corda/node/driver/DriverTests.kt
- node/src/main/kotlin/net/corda/node/Corda.kt
- node/src/main/kotlin/net/corda/node/driver/Driver.kt
- node/src/main/kotlin/net/corda/node/internal/EnforceSingleNodeIsRunning.kt
- node/src/main/kotlin/net/corda/node/internal/Node.kt
This PR aims to fix #55
It factors out the file locking into a separate class `EnforceSingleNodeIsRunning`, which is started before the logging is initialised.
I added an integ test that checks that only a single node is writing to the logfile, though it's a bit brittle, it greps for "Logs can be found in". Thoughts?
Note also that `EnforceSingleNodeIsRunning` itself does some logging - as the logging is not initialised by this time it will use the default slf4j settings. We could leave it like this or do some manual printing instead
> Fix issue #55

- core/src/main/kotlin/net/corda/core/flows/FlowLogic.kt
- core/src/main/kotlin/net/corda/core/flows/FlowStateMachine.kt
- core/src/main/kotlin/net/corda/core/utilities/ProgressTracker.kt
- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/main/kotlin/net/corda/node/services/RPCUserService.kt
- node/src/main/kotlin/net/corda/node/services/api/AuditService.kt
- node/src/main/kotlin/net/corda/node/services/api/ServiceHubInternal.kt
- node/src/main/kotlin/net/corda/node/services/statemachine/FlowStateMachineImpl.kt
- node/src/test/kotlin/net/corda/node/InteractiveShellTest.kt
- node/src/test/kotlin/net/corda/node/services/MockServiceHubInternal.kt
This PR is to allow discussion of the shape of the flow audit api. It is not intended as a full implementation.
> Create header files for discussion of possible flow audit api.

- build.gradle
- constants.properties
Note: Removed Quasar utils to avoid an issue the latest Kotlin plugin introduced. Manual testing showed no issues and shouldn't given that the root project has nothing to instrument.
> Upgraded to Kotlin 1.1.2

- client/rpc/build.gradle
- client/rpc/src/smoke-test/kotlin/net/corda/kotlin/rpc/NodeConfig.kt
- client/rpc/src/smoke-test/kotlin/net/corda/kotlin/rpc/NodeProcess.kt
- client/rpc/src/smoke-test/kotlin/net/corda/kotlin/rpc/StandaloneCordaRPClientTest.kt
Start the node as a stand-alone process and then run simple RPC operations against it, e.g. flows and uploading attachments. This is the most effective way to test the node without also having any node classes on the classpath.
> Add simple smoke tests for CordaRPCClient.

- core/src/main/kotlin/net/corda/core/crypto/Crypto.kt
When we check if the requested SignatureScheme is supported by the system, we should do via Object equality in the map values, rather then checking the map-key Strings only.
> SignatureScheme object equality in supported schemes.

- client/rpc/src/smoke-test/kotlin/net/corda/kotlin/rpc/NodeProcess.kt
- client/rpc/src/smoke-test/kotlin/net/corda/kotlin/rpc/StandaloneCordaRPClientTest.kt
This allows the smoke tests to run on Windows. However, Corda on Windows runs as a subprocess of the Capsule's JVM. This means that killing the process only removes the Capsule and leave Corda itself running. I think that this is only fixable via the Capsule unless Java can also destroy all subprocesses.
> Update smoke tests to start/stop on Windows.

- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
It should be removed once we separate cash flows into cordapp.
> Add Cash flows to default RPC flow list, so they can be invoked by shell commands.

- node/src/main/kotlin/net/corda/node/shell/InteractiveShell.kt
- tools/demobench/src/main/kotlin/net/corda/demobench/rpc/NodeRPC.kt
- tools/demobench/src/main/kotlin/net/corda/demobench/views/NodeTabView.kt
- tools/demobench/src/main/kotlin/net/corda/demobench/views/NodeTerminalView.kt
DemoBench currently keeps the tab open if the node's exit code is not zero. However, we also need to close the RPC connections and disable all of the controls on the tab.
Also extend logging in the node to record if someone exits via the CRaSH shell.
> Disable the DemoBench tab if the node exits abnormally.

- node/src/main/kotlin/net/corda/node/services/messaging/NodeMessagingClient.kt
Fix issue with automatic shutdown if the app is paused for longer than 30 seconds. This can happen on Mac laptops that put the node to sleep to save energy.
> Fix issue with automatic shutdown if the app is paused

- core/src/test/kotlin/net/corda/core/flows/TxKeyFlowUtilitiesTests.kt
- finance/src/test/kotlin/net/corda/flows/IssuerFlowTest.kt
- node/src/main/kotlin/net/corda/node/services/identity/InMemoryIdentityService.kt
- node/src/test/kotlin/net/corda/node/messaging/TwoPartyTradeFlowTests.kt
- samples/irs-demo/src/main/kotlin/net/corda/irs/simulation/IRSSimulation.kt
- test-utils/src/main/kotlin/net/corda/testing/CoreTestUtils.kt
- test-utils/src/main/kotlin/net/corda/testing/node/MockNode.kt
- test-utils/src/main/kotlin/net/corda/testing/node/MockServices.kt
Remove mock identity service and merge it with the in memory identity service. The two services
provide extremely similar functionality, and having two different version for production/test
risks subtle implementation differences. On that note, this patch includes changes to a number
of tests which worked only with mock identity service.
> Remove mock identity service

- verifier/build.gradle
Include the verifier's own classes with the standalone jar, and attach the standalone jar task to the build.
> Fix the standalone verifier jar.

- tools/demobench/src/main/kotlin/net/corda/demobench/pty/R3Pty.kt
- tools/demobench/src/main/kotlin/net/corda/demobench/rpc/NodeRPC.kt
- tools/demobench/src/main/kotlin/net/corda/demobench/views/NodeTabView.kt
We need to close the RPC client in order to destroy the non-daemon `rpc-client-reaper-*` thread(s). Sleep instead when the node exits, just long enough for the RPC client to realise that the other end of the connection is now dead.
> Prevent DemoBench hanging on shutdown

- core/src/main/kotlin/net/corda/core/crypto/Crypto.kt
- core/src/main/kotlin/net/corda/core/crypto/X509Utilities.kt
- core/src/test/kotlin/net/corda/core/crypto/X509UtilitiesTest.kt
Add "TLS" to createTlsServerCert() to differentiate it from future work to introduce a non-TLS variant.
Change to using Java 8 time types for certificate validity - does introduce so unnecessary roundtrips, but makes the code significantly easier to read/follow. In particular avoids opaque integers in the code and replaces them with `Duration`.
> X509Utilities API changes

- core/src/main/kotlin/net/corda/core/transactions/MerkleTransaction.kt
This function previously ALWAYS returned true providing the checkList wasn't empty!
> FilteredLeaves Bug Fix

- node/capsule/build.gradle
- tools/explorer/capsule/build.gradle
- webserver/webcapsule/build.gradle
We were originally packaging empty `capsule-0.12-SNAPSHOT.jar` and `webcapsule-0.12-SNAPSHOT.jar` artifacts into Node and WebServer respectively. This is currently harmless, except that we already have a third-party artifact called `capsule`. So rewrite the Gradle tasks that create capsules.
> Modify how Gradle creates capsules.

- build.gradle
- node/build.gradle
- tools/explorer/build.gradle
The version of Capsule that we use is determined by the version of `gradle-capsule-plugin`.
`gradle-capsule-plugin:1.0.2` actually uses `capsule:1.0.1` rather than `capsule:1.0.3`, so update
Gradle to reflect the real situation.
> Compile caplets against correct version of capsule.

- tools/demobench/build.gradle
- tools/demobench/package/macosx/Corda DemoBench-post-image.sh
Ensure that we're using R3's Developer ID Application key when signing the DMG.
The user could conceivably have multiple Developer ID Application keys on the keychain, and the code-signing step fails if the choice of key is ambiguous.
> Require user R3CEV for DemoBench DMG signing key.

- core/src/main/kotlin/net/corda/core/Utils.kt
- node-api/src/main/kotlin/net/corda/nodeapi/RPCStructures.kt
We cannot send internal node classes over RPC because the clients cannot deserialise them. Check for this in the node.
> Forbid classes from packages under net.corda.node.* from being serialised.

- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
This fixes running a distributed notary demo for the second and subsequent times (when the node directories have not been cleaned).
> Don't persist loaded keyPair to the keystore when owningKey is composite

- node-api/src/main/kotlin/net/corda/nodeapi/RPCStructures.kt
- node/src/main/kotlin/net/corda/node/services/persistence/NodeAttachmentService.kt
The `HashCheckingStream` class is internal to the node, but we can still serialise it with the standard `InputStreamSerializer`. So check for standard serialisers before checking whether the class in internal.
The `HashCheckingStream` is also not closed by `InputStreamSerializer` and so validate the hash once we reach the end of the stream instead.
> Allow RPC for internal classes with special serialisers.

- experimental/sandbox/src/test/java/net/corda/sandbox/WhitelistClassLoaderTest.java
Builds keep failing on CI due to this experimental feature, so ignore till we can fix properly.
> Ignore the flaky sandbox test, which keeps throwing stackoverflow

- core/src/main/kotlin/net/corda/core/crypto/Crypto.kt
- core/src/main/kotlin/net/corda/core/crypto/CryptoUtils.kt
- core/src/main/kotlin/net/corda/core/crypto/KeyStoreUtilities.kt
- core/src/main/kotlin/net/corda/core/crypto/X509Utilities.kt
- core/src/main/kotlin/net/corda/core/flows/TxKeyFlow.kt
- core/src/main/kotlin/net/corda/core/identity/Party.kt
- core/src/main/kotlin/net/corda/core/node/services/IdentityService.kt
- core/src/main/kotlin/net/corda/core/node/services/Services.kt
- core/src/main/kotlin/net/corda/core/serialization/DefaultKryoCustomizer.kt
- core/src/main/kotlin/net/corda/core/serialization/Kryo.kt
- core/src/test/kotlin/net/corda/core/crypto/X509NameConstraintsTest.kt
- core/src/test/kotlin/net/corda/core/crypto/X509UtilitiesTest.kt
- core/src/test/kotlin/net/corda/core/serialization/KryoTests.kt
- docs/source/changelog.rst
- node/src/integration-test/kotlin/net/corda/services/messaging/MQSecurityAsNodeTest.kt
- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/main/kotlin/net/corda/node/services/identity/InMemoryIdentityService.kt
- node/src/main/kotlin/net/corda/node/services/keys/E2ETestKeyManagementService.kt
- node/src/main/kotlin/net/corda/node/services/keys/KMSUtils.kt
- node/src/main/kotlin/net/corda/node/services/keys/PersistentKeyManagementService.kt
- node/src/main/kotlin/net/corda/node/services/messaging/ArtemisMessagingServer.kt
- node/src/main/kotlin/net/corda/node/services/network/NetworkMapService.kt
- node/src/main/kotlin/net/corda/node/utilities/registration/NetworkRegistrationHelper.kt
- node/src/test/kotlin/net/corda/node/utilities/registration/NetworkisRegistrationHelperTest.kt
- test-utils/src/main/kotlin/net/corda/testing/node/MockServices.kt
- test-utils/src/main/kotlin/net/corda/testing/node/SimpleNode.kt
Replace X509Certificate with X509CertificateHolder for consistency in implementation of how X.509 certificates are managed. Using the Java standard class entails the actual implementing class being one of several options depending how a certificate is built, which makes serialization/deserialization with Kryo inconsistent as some of these forms cannot be directly built from outside restricted classes.
> Replace X509Certificate with X509CertificateHolder

- tools/demobench/src/main/kotlin/net/corda/demobench/explorer/Explorer.kt
`Files.createSymbolicLink()` throws `java.nio.file.FileAlreadyExistsException`, but we were catching `kotlin.io.FileAlreadyExistsException`. And while we're at it, ensure that `Files.copy()` doesn't fail either if the target already exists.
Fixes #753
> Allow DemoBench to install Explorer's CorDapps multiple times.

- docs/source/running-the-demos.rst
- samples/bank-of-corda-demo/build.gradle
- samples/notary-demo/build.gradle
- samples/trader-demo/build.gradle
In Notary demo, introduce deployNodes task, that deploys all three types of Notary into different directories (so there is no need to do clean, when you want to run them one after another).
> Fix Bank of Corda, Trader and Notary demos. 

- build.gradle
- config/dev/generalnodea.conf
- config/dev/generalnodeb.conf
- config/dev/nameservernode.conf
- cordform-common/src/main/java/net/corda/cordform/CordformNode.java
- core/src/main/kotlin/net/corda/core/crypto/X509Utilities.kt
- docs/source/corda-configuration-file.rst
- docs/source/creating-a-cordapp.rst
- docs/source/example-code/build.gradle
- docs/source/example-code/src/main/resources/example-network-map-node.conf
- docs/source/example-code/src/main/resources/example-node.conf
- docs/source/example-code/src/main/resources/example-out-of-process-verifier-node.conf
- docs/source/permissioning.rst
- docs/source/tutorial-cordapp.rst
- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/main/kotlin/net/corda/node/services/config/NodeConfiguration.kt
- node/src/main/kotlin/net/corda/node/utilities/registration/NetworkRegistrationHelper.kt
- node/src/main/resources/reference.conf
- samples/attachment-demo/build.gradle
- samples/bank-of-corda-demo/build.gradle
- samples/irs-demo/build.gradle
- samples/irs-demo/src/main/kotlin/net/corda/irs/simulation/Simulation.kt
- samples/simm-valuation-demo/build.gradle
- samples/trader-demo/build.gradle
- test-utils/src/main/kotlin/net/corda/testing/CoreTestUtils.kt
- tools/demobench/src/main/kotlin/net/corda/demobench/model/InstallFactory.kt
- tools/demobench/src/main/kotlin/net/corda/demobench/model/NodeConfig.kt
- tools/demobench/src/main/kotlin/net/corda/demobench/model/NodeController.kt
- tools/demobench/src/main/kotlin/net/corda/demobench/views/NodeTabView.kt
- tools/explorer/src/main/kotlin/net/corda/explorer/Main.kt
Remove nearestCity from node configuration. Now information about the location is always taken from node's legal name. If not present - exception on node startup.
Fixes also: https://github.com/corda/corda/issues/696
> Remove nearestCity from node configuration.

- .gitignore
- core/src/main/kotlin/net/corda/core/Utils.kt
- core/src/test/kotlin/net/corda/core/UtilsTest.kt
- node/src/main/kotlin/net/corda/node/driver/Driver.kt
- test-utils/src/main/kotlin/net/corda/testing/RPCDriver.kt
- test-utils/src/main/kotlin/net/corda/testing/node/NodeBasedTest.kt
Also RPCDriver.startRpcBroker now waits for port to be unbound, as was probably intended. Same problem seems to have happened a few times, so I've made addressMustBeBound synchronous and you can use addressMustBeBoundFuture if you really want a future.
> Fix tests that check ports are bound/unbound

- node/src/main/kotlin/net/corda/node/Corda.kt
... by replacing an expression which crashes Dokka with an older more verbose notation.
> Fix docs build

- build.gradle
- node/src/main/kotlin/net/corda/node/internal/Node.kt
- node/src/main/kotlin/net/corda/node/services/messaging/ArtemisMessagingServer.kt
- node/src/main/kotlin/net/corda/node/services/messaging/NodeMessagingClient.kt
Seems like in 2.0.0 there haven't been any major changes for Artemis core, most work was done for better support of other protocols, like AMQP.
(this change is needed because I want to submit a patch to Artemis, and it makes sense to upgrade to the latest)
> Upgrade Artemis to 2.1.0

- build.gradle
The explicit dependency on `netty-all` was added to Node so that Artemis and `io-catalyst` would agree which Netty artifacts to use. Artemis 2.1.0 uses Netty 4.1.9.Final rather than 4.1.5.Final, so update Gradle to agree.
This is probably just a documentation fix, because Gradle seems to accept the transitive 4.1.9.Final dependency over the explicit 4.1.5.Final one.
> Upgrade to Netty 4.1.9

- client/rpc/src/main/kotlin/net/corda/client/rpc/internal/RPCClientProxyHandler.kt
Failing to close an RPC client is currently preventing the JVM from shutting down because of running non-daemon `rpc-client-reaper-*` threads. While these clients really _should_ be shutdown cleanly, having the JVMs failing to terminate is more serious.
Make the `rpc-client-reaper-*` threads into daemon threads.
> Make RPC client reaper threads into daemons.

- tools/demobench/build.gradle
We are hoping that `purejavacomm-0.0.18` is not also flagged by firewalls' malware scanners.
Fixes #772
> Upgrade DemoBench to purejavacomm 0.0.18

- build.gradle
- node/src/main/kotlin/net/corda/node/internal/Node.kt
- node/src/main/kotlin/net/corda/node/services/messaging/ArtemisMessagingServer.kt
- node/src/main/kotlin/net/corda/node/services/messaging/NodeMessagingClient.kt
The new version seems to introduce a race condition that causes a RPC stability test to randomly hang. We don't actually need to upgrade until our patch is in (could be 2.2.0 or 2.3.0), so I'll revisit the issue then.
This reverts commit 81d32fd6a7d95d2004967796e5ea7e37d5b7b80c.
> Reverting "Upgrade Artemis to 2.1.0" 

- build.gradle
- client/jackson/build.gradle
- client/jfx/build.gradle
- client/mock/build.gradle
- client/rpc/build.gradle
- constants.properties
- core/build.gradle
- finance/build.gradle
- gradle-plugins/publish-utils/src/main/groovy/net/corda/plugins/PublishTasks.groovy
- gradle-plugins/settings.gradle
- node-api/build.gradle
- node-schemas/build.gradle
- node/build.gradle
- test-utils/build.gradle
- verifier/build.gradle
- webserver/build.gradle
Why: It is standard for projects with multiple publications to have <project>- at the start or some other prefix.
> Corda publications and JARs now have cord or corda at the start.

- node/src/main/kotlin/net/corda/node/Corda.kt
Show a descriptive message and suggest @wawrzek's fix if current JDK version does not support the required elliptic curve specs. See [Unknown curve](https://discourse.corda.net/t/unknown-named-curve/1122) and [#701](https://github.com/corda/corda/issues/701)
> Unknown curve on node startup

- docs/source/example-code/build.gradle
- test-utils/build.gradle
The verifier is a standalone "fat" jar, so we don't want other projects to depend upon it transitively.
> Remove verifier from test-utils because it's unused.

- docs/source/changelog.rst
Remove out of date changelog entry about flows accepting PartyAndCertificate, which
was reverted.
> Remove out of date changelog entry

- client/rpc/src/integration-test/kotlin/net/corda/client/rpc/RPCStabilityTests.kt
Background:
* Test failed frequently after Artemis upgrade
* So we downgraded Artemis, and made the test impl depend on Artemis version
* But now I've noticed the test also fails occasionally with current Artemis
* This PR defers the problem until we upgrade Artemis
* There is indeed a bug in Artemis, Andrius has reproduced it and reported it to them
> Disable occasionally-failing test until we upgrade Artemis

- core/src/main/kotlin/net/corda/core/contracts/Structures.kt
- core/src/main/kotlin/net/corda/core/node/services/Services.kt
- core/src/main/kotlin/net/corda/flows/TwoPartyDealFlow.kt
- finance/src/main/kotlin/net/corda/contracts/testing/DummyDealContract.kt
- samples/irs-demo/src/main/kotlin/net/corda/irs/contract/IRS.kt
- samples/irs-demo/src/main/kotlin/net/corda/irs/flows/AutoOfferFlow.kt
- samples/irs-demo/src/main/kotlin/net/corda/irs/flows/FixingFlow.kt
- samples/simm-valuation-demo/src/main/kotlin/net/corda/vega/api/PortfolioApi.kt
- samples/simm-valuation-demo/src/main/kotlin/net/corda/vega/contracts/IRSState.kt
- samples/simm-valuation-demo/src/main/kotlin/net/corda/vega/contracts/OGTrade.kt
- samples/simm-valuation-demo/src/main/kotlin/net/corda/vega/contracts/PortfolioState.kt
- samples/simm-valuation-demo/src/main/kotlin/net/corda/vega/contracts/PortfolioSwap.kt
- samples/simm-valuation-demo/src/main/kotlin/net/corda/vega/flows/SimmRevaluation.kt
Removed duplicate identity attribute (parties) from DealState.
All references to 'parties' now refer to the inherited 'participants' attribute from ContractState.
> Removed duplicate identity attribute (parties) from DealState.

- docs/source/demobench.rst
- tools/demobench/package/macosx/Corda DemoBench-post-image.sh
Explain better how to configure MacOS to build a signed DMG, including using the JetBrains JDK.
> Update documentation for DemoBench's MacOSX signing key.

- client/jackson/src/main/kotlin/net/corda/jackson/JacksonSupport.kt
- core/src/main/kotlin/net/corda/core/messaging/CordaRPCOps.kt
- core/src/main/kotlin/net/corda/core/node/services/IdentityService.kt
- docs/source/changelog.rst
- node/src/main/kotlin/net/corda/node/internal/CordaRPCOpsImpl.kt
- node/src/main/kotlin/net/corda/node/services/identity/InMemoryIdentityService.kt
- node/src/main/kotlin/net/corda/node/shell/InteractiveShell.kt
- node/src/test/kotlin/net/corda/node/services/network/InMemoryIdentityServiceTests.kt
Matching can be done with case insensitive substrings in the identity service, RPC and shell. In future cleverer matching should be possible, e.g. using Lucene or RDBMS free text search features.
> Support fuzzy matching for identities.

- core/src/main/kotlin/net/corda/core/crypto/KeyStoreUtilities.kt
- core/src/main/kotlin/net/corda/core/crypto/X509Utilities.kt
- core/src/test/kotlin/net/corda/core/crypto/X509NameConstraintsTest.kt
- core/src/test/kotlin/net/corda/core/crypto/X509UtilitiesTest.kt
- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/main/kotlin/net/corda/node/services/identity/InMemoryIdentityService.kt
- node/src/main/kotlin/net/corda/node/utilities/registration/NetworkRegistrationHelper.kt
- node/src/test/kotlin/net/corda/node/utilities/registration/NetworkisRegistrationHelperTest.kt
... and use that instead of the verbose JcaX509CertificateConverter construct everywhere.
> Cleanup: add an extension function to X509CertificateHolder 

- core/src/main/kotlin/net/corda/core/serialization/AllButBlacklisted.kt
- core/src/main/kotlin/net/corda/core/serialization/Blacklist.kt
- core/src/main/kotlin/net/corda/core/serialization/CordaClassResolver.kt
- core/src/main/kotlin/net/corda/core/serialization/Kryo.kt
- core/src/test/kotlin/net/corda/core/serialization/CordaClassResolverTests.kt
This is a simpler model than [#784](https://github.com/corda/corda/pull/784), where we use an `AllButBlacklisted `implementation of `ClassWhitelist`.
- `AllButBlacklisted` is a singleton `ClassWhitelist` object that includes a hashset of blacklisted classes and interfaces. Thus, in practice everything still behaves like a whitelist.
- KryoStorage uses the above whitelist
- Inheritance is supported.
- there is an extra `forciblyAllowedClasses` hashset, in which we specifically exclude classes from being blacklisted, even if one or more of their super-classes or super-interfaces are blacklisted. `LinkedHashSet` is such an example.
- hasListed(Class) throws a ~~NotSerializableException~~  IllegalStateException that informs the user if a class is blacklisted.
- due to the above, we receive a …
> Simpler Blacklist implementation for internal Kryo

- core/src/main/kotlin/net/corda/core/crypto/Crypto.kt
- core/src/main/kotlin/net/corda/core/crypto/CryptoUtils.kt
- core/src/test/kotlin/net/corda/core/crypto/CryptoUtilsTest.kt
This version applies the BIP32 logic, with some modifications, mainly due to the fact that extension chain code for keys is not currently utilised in Corda.
**Algorithm:** each new private key is generated using the HMAC-SHA512 function, where the hmac-key is the private key and the hmac-data is a seed input, accordingly. The public key is then easily computed as a scalar multiplication on the curve.
**Note:** Current logic does not include a serialisation/padding mechanism for the HMAC inputs.
Solution: A compatible approach (easy to  implement) would be to have **HMAC-512(SHA256(private_key), SHA256(seed))**
@mikehearn and @mnesbit what are your thoughts on it?
> Deterministic Key Generation for ECDSA and EdDSA

- node/capsule/build.gradle
- tools/explorer/capsule/build.gradle
- webserver/webcapsule/build.gradle
We should really include runtime dependencies here, which should also contain the compile dependencies.
> Build capsules using runtime dependencies instead of compile ones.

- core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
A pointer for CorDapp devs that this won't be needed going forward.
> Marked TransactionBuilder.signWith() as deprecated.

- core/src/main/kotlin/net/corda/flows/TxKeyFlow.kt
Correct construction of anonymous parties to use the first certificate (the target) rather than the last (the trust root). Worked because early tests used single certificate paths, but later work introducing multi-certificate paths reveal it's rather broken.
> Correct construction of anonymous parties

- core/src/main/kotlin/net/corda/core/crypto/X509Utilities.kt
- core/src/main/kotlin/net/corda/core/utilities/TestConstants.kt
- node/src/main/kotlin/net/corda/node/services/identity/InMemoryIdentityService.kt
- node/src/test/kotlin/net/corda/node/services/network/InMemoryIdentityServiceTests.kt
* Correct path composition in identity service tests
* Correct identity service certificate path verification to handle the owning certificate being anywhere in the path, rather than expecting it to be trust root
> Correct identity service tests

- core/src/main/kotlin/net/corda/core/crypto/Crypto.kt
1. Remove the previously used modular reduction which may induce biases that would be detrimental to security (according to [Deterministic ECDSA rfc](https://tools.ietf.org/html/rfc6979) and BIP32 logic).
2. Use the first 256 bits (fieldSize) of the HMAC output to extract the key according to [HKDF rfc](https://tools.ietf.org/html/rfc5869) step1 - Extract, and make the test that the private key output is < order-of-the-curve, as BIP32 recommends.
3. Extract deriveHMAC method as part of the refactoring tasks.
4. More descriptive comments on the logic behind our DKG selection.
5. If a generated key does not meet the security criteria, we retry using SHA256(seed)
> DKG - Remove the modular reduction which may induce bias

- core/src/main/kotlin/net/corda/core/transactions/MerkleTransaction.kt
- core/src/main/kotlin/net/corda/core/transactions/WireTransaction.kt
- core/src/main/kotlin/net/corda/flows/NotaryFlow.kt
- core/src/test/kotlin/net/corda/core/crypto/PartialMerkleTreeTest.kt
- samples/irs-demo/src/main/kotlin/net/corda/irs/flows/RatesFixFlow.kt
- samples/irs-demo/src/test/kotlin/net/corda/irs/testing/NodeInterestRatesTest.kt
The currently exposed merkle tree api is using kotlin function types. Change this to Java Predicate types to improve Java interop.
> Java accessible API for merkle trees

- client/rpc/src/test/kotlin/net/corda/client/rpc/RPCPerformanceTests.kt
- node/src/integration-test/kotlin/net/corda/node/NodePerformanceTests.kt
- node/src/integration-test/kotlin/net/corda/node/services/DistributedServiceTests.kt
- test-utils/src/integration-test/kotlin/net/corda/testing/driver/DriverTests.kt
- test-utils/src/main/kotlin/net/corda/testing/RPCDriver.kt
- test-utils/src/main/kotlin/net/corda/testing/driver/Driver.kt
- test-utils/src/main/kotlin/net/corda/testing/performance/Injectors.kt
- test-utils/src/main/kotlin/net/corda/testing/performance/Reporter.kt
- verifier/src/integration-test/kotlin/net/corda/verifier/VerifierDriver.kt
This PR adds a way to start driver nodes in-process, and adds a couple of node performance tests (to be run locally)
> driver, node: Allow in-process starting of nodes, add a couple of node performance tests

- core/src/main/kotlin/net/corda/core/crypto/X509Utilities.kt
- core/src/main/kotlin/net/corda/core/utilities/TestConstants.kt
- core/src/test/kotlin/net/corda/core/serialization/KryoTests.kt
- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/main/kotlin/net/corda/node/services/keys/KMSUtils.kt
- node/src/main/kotlin/net/corda/node/utilities/ServiceIdentityGenerator.kt
Use the certificate factory directly to build paths rather than assembling them via an interim API call. After reducing the complexity of the utility API, it's replacing two lines of code, at which point it seems better to make the behaviour clearer rather than having a function hide what's actually going on.
> Replace certificate path generation

- node/src/main/kotlin/net/corda/node/services/database/KotlinConfigurationTransactionWrapper.kt
- node/src/main/kotlin/net/corda/node/services/database/RequeryConfiguration.kt
- node/src/test/kotlin/net/corda/node/services/persistence/NodeAttachmentStorageTest.kt
Tighten up transaction creation code to flag situations where calling code SHOULD BE within a demarcated transaction boundary.
Now fail fast with an appropriate message indicating course of action to be taken.
https://github.com/corda/corda/issues/827
> Fix java.lang.IllegalStateException: Was not expecting to find existing database transaction on current strand

- constants.properties
Among other fixes, BC-1.57 EC FixedPointCombMultiplier avoids 'infinity' point in lookup tables, reducing timing side-channels.
> Update BC to 1.57 to reduce timing side-channel attacks

- samples/irs-demo/src/main/kotlin/net/corda/irs/api/NodeInterestRates.kt
This is a temporary fix:
Set some default fixes to the Oracle, so we can smoothly run the IRS Demo.
Description on running the demo will be updated soon in a docs-update related PR, as part of M13 release.
> hack: addDefaultFixes to IRS Demo to make it work

- samples/simm-valuation-demo/src/main/kotlin/net/corda/vega/flows/SimmFlow.kt
Required as ACK is not-whitelisted and demo breaks
> SIMM demo Ack CordaSerializable

- core/src/main/kotlin/net/corda/core/node/services/IdentityService.kt
- core/src/main/kotlin/net/corda/core/serialization/DefaultKryoCustomizer.kt
- node/src/integration-test/kotlin/net/corda/services/messaging/P2PSecurityTest.kt
- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/main/kotlin/net/corda/node/services/identity/InMemoryIdentityService.kt
- node/src/main/kotlin/net/corda/node/utilities/ServiceIdentityGenerator.kt
- samples/irs-demo/src/main/resources/net/corda/irs/simulation/trade.json
- test-utils/src/main/kotlin/net/corda/testing/CoreTestUtils.kt
- test-utils/src/main/kotlin/net/corda/testing/node/MockNode.kt
- test-utils/src/main/kotlin/net/corda/testing/node/SimpleNode.kt
Enforce that the identity service must always have a root CA specified, which all identities have
certificates signed by (or intermediaries of). Also adds a certificate store to the identity service
for help building/verifying certificate paths.
> Correctly enforce certificate constraints on all identities

- tools/demobench/src/main/kotlin/net/corda/demobench/model/NodeConfig.kt
- tools/demobench/src/test/kotlin/net/corda/demobench/model/NodeConfigTest.kt
Localhost resolution can be slow on MacOSX, as described [here](http://stackoverflow.com/questions/39636792/jvm-takes-a-long-time-to-resolve-ip-address-for-localhost). DemoBench doesn't need to be affected by this.
> DemoBench operates exclusively on localhost, so no need for public IP.

- config/dev/log4j2.xml
- config/test/log4j2.xml
- samples/simm-valuation-demo/src/main/resources/log4j2.xml
- tools/demobench/src/main/resources/log4j2.xml
- tools/demobench/src/test/resources/log4j2-test.xml
Log4J2 supports the following [conversion patterns](https://logging.apache.org/log4j/2.x/manual/layouts.html#Patterns) within its configuration files. Most of these patterns have several synonyms, e.g.
%d, %date   -> Date
%m, %msg    -> Message
%M, %method -> Method name
%c, %logger -> Logger name
%t, %thread -> Thread name
We use some of the more explicit forms already, e.g. `%msg`. This patch expands on this slightly by replacing `%d` with `%date` and `%M` with `%method` across all of our `log4j2(-test).xml` files. The intention here is to make the files both more readable (e.g. I had no idea what `%M` was for until I looked it up) and consistent.
We could also extend this to include `%t -> %thread` and/or `%c -> %logger`, if required.
It is also my hope that this patch will resolve the …
> Alter some logging patterns to a more explicit form.

- experimental/src/main/kotlin/net/corda/carpenter/ClassCarpenter.kt
- experimental/src/test/kotlin/net/corda/carpenter/ClassCarpenterTest.kt
Currently the carpenter only generates concreate classes, add the
ability to also synthesise interfaces and have those interfaces used by
other gnerated classes
> Add Interface synthesis to the carpenter

- build.gradle
- docs/source/changelog.rst
I've also deleted the Kotlin upgrade to 1.1.2 from changelog in master (I did that in M13 already), we are still in 1.1.1.
> Change master to 0.14-SNAPSHOT

- docs/source/api-index.rst
- docs/source/api-vault-query.rst
- docs/source/node-internals-index.rst
- docs/source/release-notes.rst
- docs/source/vault.rst
Vault Query API is distinct to the existing Vault Service API.
Clarified naming and fixed incorrect references to both Vault Query and Persistence docs.
> Cleaned up incorrect references to vault query and persistence.

- core/src/main/kotlin/net/corda/core/node/services/Services.kt
Correct trackBy() call on vault service, which should call _trackBy() but previously called _queryBy()
> Correct trackBy() call

- core/src/main/kotlin/net/corda/core/serialization/CordaClassResolver.kt
- core/src/main/kotlin/net/corda/core/serialization/KryoAMQPSerializer.kt
- core/src/main/kotlin/net/corda/core/serialization/amqp/AMQPPrimitiveSerializer.kt
- core/src/main/kotlin/net/corda/core/serialization/amqp/ArraySerializer.kt
- core/src/main/kotlin/net/corda/core/serialization/amqp/CollectionSerializer.kt
- core/src/main/kotlin/net/corda/core/serialization/amqp/CustomSerializer.kt
- core/src/main/kotlin/net/corda/core/serialization/amqp/DeserializationInput.kt
- core/src/main/kotlin/net/corda/core/serialization/amqp/DeserializedParameterizedType.kt
- core/src/main/kotlin/net/corda/core/serialization/amqp/MapSerializer.kt
- core/src/main/kotlin/net/corda/core/serialization/amqp/ObjectSerializer.kt
- core/src/main/kotlin/net/corda/core/serialization/amqp/PropertySerializer.kt
- core/src/main/kotlin/net/corda/core/serialization/amqp/Schema.kt
- core/src/main/kotlin/net/corda/core/serialization/amqp/SerializationHelper.kt
- core/src/main/kotlin/net/corda/core/serialization/amqp/SerializerFactory.kt
- core/src/main/kotlin/net/corda/core/serialization/amqp/SingletonSerializer.kt
- core/src/main/kotlin/net/corda/core/serialization/amqp/custom/BigDecimalSerializer.kt
- core/src/main/kotlin/net/corda/core/serialization/amqp/custom/CurrencySerializer.kt
- core/src/main/kotlin/net/corda/core/serialization/amqp/custom/InstantSerializer.kt
- core/src/main/kotlin/net/corda/core/serialization/amqp/custom/PublicKeySerializer.kt
- core/src/main/kotlin/net/corda/core/serialization/amqp/custom/X500NameSerializer.kt
- core/src/test/kotlin/net/corda/core/serialization/amqp/SerializationOutputTests.kt
- integrates with Kryo so that any `@CordaSerializable` triggers a switch to using AMQP serialization (but only if a boolean flag is adjusted in the code first, so will be disabled in master)
- using this to discover issues / corner cases that need supporting
- some custom serializers to marshal some of our common types
- some refactoring to handle generics for e.g. Amount<T>
- some bug fixes that @fenryka needs for the carpenter work
- more test cases relating to above work
Plenty of TODOs left to do.
> AMQP serialization part 3: some custom serializers, integration with Kryo (disabled)

- core/src/main/kotlin/net/corda/core/crypto/ContentSignerBuilder.kt
- core/src/main/kotlin/net/corda/core/crypto/Crypto.kt
- core/src/main/kotlin/net/corda/core/crypto/SignatureScheme.kt
Remove use of Sun internal APIs and algorithm identifiers (which are incomplete and non-standard)
in Crypto. Also eliminates uncertainty about which signature scheme is being used (and therefore
iterating through several to find the correct one).
> Restructure Crypto to use standard OIDs

- constants.properties
- gradle-plugins/quasar-utils/src/main/groovy/net/corda/plugins/QuasarPlugin.groovy
This plugin was modifying project repositories - this is not behaviour a gradle plugin should be doing and it made downstream gradle configurations nearly impossible to debug.
> Removing repository addition from Quasar Plugin

- core/src/main/kotlin/net/corda/core/serialization/amqp/DeserializationInput.kt
- core/src/test/kotlin/net/corda/core/serialization/amqp/DeserializeAndReturnEnvelope.kt
- core/src/test/kotlin/net/corda/core/serialization/amqp/DeserializeAndReturnEnvelopeTests.kt
Useful for testing the carpenter by giving access to a constructed
envelope rather than manually building one every time
> Add secondry deserializer to return amqp envelope

- core/src/main/kotlin/net/corda/core/node/services/vault/QueryCriteria.kt
- docs/source/api-vault-query.rst
- node/src/main/kotlin/net/corda/node/services/vault/HibernateQueryCriteriaParser.kt
- node/src/test/java/net/corda/node/services/vault/VaultQueryJavaTests.java
- node/src/test/kotlin/net/corda/node/services/vault/VaultQueryTests.kt
Fix https://github.com/corda/corda/issues/949 by providing a default StateStatus argument to all QueryCriteria types.
> FIX Vault Query defaults to UNCONSUMED in all QueryCriteria types

- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
* Added SSL certificate name checks on node startup to make it fail fast instead of failing when it connect to other node.  This PR address issue #715 .
> Add certificate subject name check on node startup

- core/src/main/kotlin/net/corda/core/crypto/CompositeKey.kt
- core/src/test/kotlin/net/corda/core/crypto/CompositeKeyTests.kt
Some extra validation checks for CompositeKeys
1) Min threshold = 1
2) Min weight = 1
3) threshold <= totalWeight (total = aggregated)
4) Graph cycle detection (to avoid infinite loops)
5) totalWeight integer overflow detection (inherently,  due to 1 & 2, we protect against underflow as well)
Also, because `@CordaSerializable` doesn't invoke the constructor and thus a key may be malformed (i.e. cannot be validated), `isFulfilledBy()` runs a full validity check before checking thresholds are satisfied.
There is also a small fix on the "N of N" requirement, where the total (aggregated) weight value is now taken into account, if threshold is not provided. Previously this was `children.size`.
~_This is not subject for review yet; unit-tests are required._~ Ready for review.
> CompositeKey validation checks

- constants.properties
- gradle-plugins/cordformation/src/main/groovy/net/corda/plugins/Cordformation.groovy
This fixes the notary demo and future cordapps that will be broken.
For reference there is a workaround for all cordapps built on M13 and that is to add the following to the cordapp's project;
jar {
exclude 'META-INF/**'
}
> Cordapps now exclude the META-INF of dependencies.

- core/src/main/kotlin/net/corda/core/crypto/CompositeKey.kt
- core/src/main/kotlin/net/corda/core/crypto/EncodingUtils.kt
- core/src/test/kotlin/net/corda/core/crypto/CompositeKeyTests.kt
To construct a `CompositeKey`, `children` were previously sorted using `hashcode` of the underlying public key, which may not be deterministic.
Now, `NodeAndWeight.compareTo` uses the `BigInteger` representation of the SHA256 of public keys to compare between NodeAndWeight objects having the same `weight`.
> NodeAndWeight deterministic comparator

- node/src/main/kotlin/net/corda/node/utilities/DatabaseSupport.kt
- node/src/test/kotlin/net/corda/node/utilities/ObservablesTests.kt
If we dip down to zero subscribers, no future vault updates are streamed. This hasn't been seen historically, because the cash metrics observer is always present, but this will be moved out of node into cordapps. As a result the normal vault subscription count becomes zero and for instance the WorkflowTransactionBuildTutorialTest starts to hang waiting for vault updates.
> Fix a bug in the wrapper code for the vault.

- client/rpc/src/smoke-test/kotlin/net/corda/kotlin/rpc/StandaloneCordaRPClientTest.kt
- core/src/main/kotlin/net/corda/core/messaging/CordaRPCOps.kt
- core/src/main/kotlin/net/corda/core/node/services/Services.kt
- core/src/main/kotlin/net/corda/core/node/services/vault/QueryCriteriaUtils.kt
- docs/source/api-vault-query.rst
- node/src/main/kotlin/net/corda/node/services/vault/HibernateQueryCriteriaParser.kt
- node/src/main/kotlin/net/corda/node/services/vault/HibernateVaultQueryImpl.kt
- node/src/test/java/net/corda/node/services/vault/VaultQueryJavaTests.java
- node/src/test/kotlin/net/corda/node/services/vault/VaultQueryTests.kt
Pagination continues to be optional, but with following changes:
1) If no `PageSpecification` provided then a maximum of MAX_PAGE_SIZE (200) results will be returned, otherwise we fail-fast with a `VaultQueryException`to alert the API user to the need to specify a `PageSpecification`.
Internally, we no longer need to calculate a results count (thus eliminating an expensive SQL query) unless a `PageSpecification` is supplied (note: that a value of -1 is returned for total_results in this scenario).
Internally, we now use the `AggregateFunction` capability to perform the count.
2) Paging now starts from 1 (was previously 0).
> Vault Query Pagination simplification

- core/src/main/kotlin/net/corda/core/crypto/CryptoUtils.kt
- core/src/main/kotlin/net/corda/core/crypto/DigitalSignature.kt
- docs/source/oracles.rst
- node/src/main/kotlin/net/corda/node/services/keys/PersistentKeyManagementService.kt
- samples/irs-demo/src/main/kotlin/net/corda/irs/api/NodeInterestRates.kt
- samples/irs-demo/src/main/kotlin/net/corda/irs/flows/RatesFixFlow.kt
`DigitialSignature.LegallyIdentifiable` has been removed as it is only required for Oracles and we eventually decided that public keys are enough to distinguish between entities (we can always ask to the network map).
This is part of the cleanup before applying the full transaction signature metadata functionality.
> Remove DigitalSignature.LegallyIdentifiable

- core/src/main/kotlin/net/corda/core/serialization/amqp/SerializationOutput.kt
For testing I need to be able to mess with the schema before it gets
added to the envelope, extract the function where that happens and make
it open so the tests can do what they want
> Make serialise putObject function an open function

- core/src/main/kotlin/net/corda/core/serialization/carpenter/ClassCarpenter.kt
- core/src/test/kotlin/net/corda/core/serialization/carpenter/ClassCarpenterTest.kt
Pass signature as null, not empty string, otherwise the class asm isn't
correct. Using javap at the command line prior to the fix yields
public class MyClass implements
net.corda.core.serialization.carpenter.SimpleFieldAccess {
protected final java.lang.Integer a;
descriptor: Ljava/lang/Integer;
public MyClass(java.lang.Integer);
descriptor: (Ljava/lang/Integer;)V
public java.lang.Integer getA();
descriptor: ()Ljava/lang/Integer;
public java.lang.Object get(java.lang.String);
descriptor:
(Ljava/lang/String;)Ljava/lang/Object;
Error: A serious internal error has occurred: java.lang.StringIndexOutOfBoundsException: String index out of range: 0
> Fix toString generated method that breaks Introspection for BEANS

- tools/demobench/src/main/kotlin/net/corda/demobench/views/NodeTerminalView.kt
The total number of states returned by the query is irrespective of the pagination.
> Comment that vault returns the total number of available states.

- client/jfx/src/integration-test/kotlin/net/corda/client/jfx/NodeMonitorModelTest.kt
- samples/trader-demo/src/main/kotlin/net/corda/traderdemo/flow/BuyerFlow.kt
A couple of tests actually fail due to the broadcast nature of finality flow. The trader demo throws an exception on the remote node due to duplicate recordTransactions call. I therefore investigated what failed if finality flow was made blocking. This found that NodeMonitorTests was ignoring some background flows triggered to carry out transaction resolution, but passes normally due to the usual timing.
> Fix a couple of tests

- tools/demobench/package-demobench-dmg.sh
- tools/demobench/package-demobench-exe.bat
- tools/demobench/package-demobench-rpm.sh
Allow TeamCity builds to fail if they cannot package DemoBench successfully.
> Update DemoBench packager scripts to fail when packaging fails.

- core/src/main/kotlin/net/corda/core/flows/FinalityFlow.kt
- core/src/main/kotlin/net/corda/core/flows/ManualFinalityFlow.kt
- core/src/test/kotlin/net/corda/core/flows/FinalityFlowTests.kt
- core/src/test/kotlin/net/corda/core/flows/ManualFinalityFlowTests.kt
- docs/source/changelog.rst
- docs/source/release-notes.rst
Add extension hooks to FinalityFlow to support different behaviours depending on whether the node knows who all of the parties in a transaction are.
> Rnicoll finality flow extensions

- client/rpc/src/smoke-test/kotlin/net/corda/kotlin/rpc/StandaloneCordaRPClientTest.kt
- core/src/main/kotlin/net/corda/core/Utils.kt
- core/src/main/kotlin/net/corda/core/flows/FetchAttachmentsFlow.kt
- core/src/main/kotlin/net/corda/core/flows/FetchDataFlow.kt
- core/src/main/kotlin/net/corda/core/flows/FetchTransactionsFlow.kt
- docs/source/troubleshooting.rst
- node/src/integration-test/kotlin/net/corda/node/services/statemachine/LargeTransactionsTest.kt
- node/src/main/kotlin/net/corda/node/services/CoreFlowHandlers.kt
- samples/attachment-demo/src/main/kotlin/net/corda/attachmentdemo/AttachmentDemo.kt
- test-utils/src/main/kotlin/net/corda/testing/TestConstants.kt
A user has encountered a bug whereby our limit of 10mb per transaction and per attachment is not being respected due to our use of batching in the fetch flows.  There should be no such limit on attachment sizes (or rather it should be a lot higher) but we put one in place to temporarily avoid upstream Artemis large message handling bugs. Once those are fixed we can re-batch this code if we want, and allow >10mb attachments.
This PR has a few commits:
* 3 which make some minor test utility changes and doc improvements.
* 1 which de-batches the test flow, and makes a new integration test pass. The integration test reproduces the bug reported to us by this user.
> Fix a bug with transactions that have >10mb of attachments

- core/src/main/kotlin/net/corda/core/flows/FinalityFlow.kt
- core/src/main/kotlin/net/corda/core/flows/TransactionKeyFlow.kt
- docs/source/example-code/src/integration-test/kotlin/net/corda/docs/IntegrationTestingTutorial.kt
- finance/src/main/kotlin/net/corda/flows/TwoPartyTradeFlow.kt
- finance/src/test/kotlin/net/corda/flows/IssuerFlowTest.kt
- node/src/test/kotlin/net/corda/node/messaging/TwoPartyTradeFlowTests.kt
Enable anonymisation in integration testing tutorial, and as a requirement fix a bug where the counterparty anonymous identity was not registered by `TransactionKeyFlow`.
Enforces that all parties are identified during `FinalityFlow` to avoid silently failing to deliver transactions to a party.
> Enable anonymisation in integration testing tutorial

- core/src/main/kotlin/net/corda/core/serialization/AttachmentsClassLoader.kt
- core/src/main/kotlin/net/corda/core/serialization/CordaClassResolver.kt
- core/src/main/kotlin/net/corda/core/serialization/Kryo.kt
- core/src/test/kotlin/net/corda/core/serialization/CordaClassResolverTests.kt
The AttachementClassLoader is really an implementation detail of the serialisation. It should be put with that code and not look like it is a required bit of API.
> Move AttachmentClassLoader away from main API files

- core/src/main/kotlin/net/corda/core/node/services/TimeWindowChecker.kt
- core/src/test/kotlin/net/corda/core/node/services/TimeWindowCheckerTests.kt
As agreed, the client should add a tolerance value when creating the transaction, thus no tolerance is required on the notary side.
> Remove tolerance from TimeWindowChecker

- node/src/integration-test/kotlin/net/corda/services/messaging/MQSecurityAsNodeTest.kt
- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/main/kotlin/net/corda/node/services/config/ConfigUtilities.kt
- node/src/main/kotlin/net/corda/node/utilities/KeyStoreUtilities.kt
- node/src/main/kotlin/net/corda/node/utilities/registration/NetworkRegistrationHelper.kt
* Store composite key in keystore from file for notaries's identity.
* Some refactoring.
added a TODO to make `ServiceIdentityGenerator.generateToDisk` write to keystore instead of writing keys to file, that will be on a different PR as its more involved.
> Store notaries's identity composite key in keystore

- node/src/test/kotlin/net/corda/node/messaging/TwoPartyTradeFlowTests.kt
Switch to using a dedicated bank node in two party trade flows so that when KYC checks are enforced, all nodes on the network know who the issuer is.
> Remove dummy cash issuer from two party trade flows

- tools/demobench/build.gradle
- tools/demobench/package-demobench-exe.bat
- tools/demobench/package/bugfixes/apply.bat
- tools/demobench/package/bugfixes/apply.sh
- tools/demobench/package/bugfixes/java/sun/swing/JLightweightFrame.java
- tools/demobench/package/linux/CordaDemoBench.spec
- tools/demobench/package/macosx/Corda DemoBench-post-image.sh
- tools/demobench/package/windows/Corda DemoBench-post-image.wsf
There is a JavaFX bug that is occasionally crashing DemoBench with a NPE. While the correct fix is ultimately to patch OpenJDK, we need DemoBench to work **now**. The broken class is `sun.swing.JLightweightFrame`, which lives in `rt.jar` and cannot be overridden and so we need to update `rt.jar` itself. Or more accurately, we need to update the copy of `rt.jar` that JavaPackager includes in the DemoBench installers.
This fixes issue #1049.
> Patch DemoBench for JavaFX bugs when building installers.

- core/src/main/kotlin/net/corda/core/flows/FlowLogic.kt
- samples/bank-of-corda-demo/src/main/kotlin/net/corda/bank/api/BankOfCordaWebApi.kt
Remove logging of the entire return from a fiber, which can now include a certificate (several hundred lines of text).
Correct identity used in the web API test for Bank of Corda.
> Misc. cleanup

- core/src/main/kotlin/net/corda/core/serialization/DefaultKryoCustomizer.kt
- core/src/main/kotlin/net/corda/core/serialization/Kryo.kt
- core/src/main/kotlin/net/corda/core/serialization/SerializationAPI.kt
- core/src/main/kotlin/net/corda/core/transactions/SignedTransaction.kt
- core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
- core/src/main/kotlin/net/corda/core/transactions/WireTransaction.kt
- core/src/test/kotlin/net/corda/core/contracts/TransactionTests.kt
- core/src/test/kotlin/net/corda/core/crypto/PartialMerkleTreeTest.kt
- core/src/test/kotlin/net/corda/core/serialization/TransactionSerializationTests.kt
- finance/src/test/kotlin/net/corda/contracts/testing/Generators.kt
- node/src/test/kotlin/net/corda/node/messaging/TwoPartyTradeFlowTests.kt
- node/src/test/kotlin/net/corda/node/services/database/RequeryConfigurationTest.kt
- node/src/test/kotlin/net/corda/node/services/persistence/DBTransactionStorageTests.kt
- test-utils/src/main/kotlin/net/corda/testing/TestDSL.kt
…erialized form.
Since we now calculate the transaction id as the Merkle root hash instead of the hash of the serialized bytes of the whole transaction, the txBits property serves no purpose.
EDIT: txBits are actually needed so we can move transactions around without a large serialization overhead, so keeping it and just changing the serialization caching behaviour
> Refactor transaction serialization caching

- core/src/main/kotlin/net/corda/core/serialization/amqp/ArraySerializer.kt
- core/src/main/kotlin/net/corda/core/serialization/amqp/DeserializationInput.kt
- core/src/main/kotlin/net/corda/core/serialization/amqp/DeserializedGenericArrayType.kt
- core/src/main/kotlin/net/corda/core/serialization/amqp/SerializerFactory.kt
- core/src/test/kotlin/net/corda/core/serialization/amqp/DeserializeSimpleTypesTests.kt
Arrays of objects are represented in the schema as <type> followed by [], so int[] for example. The problem here is that there is no mapping between that type and weather it is boxed or unboxed, so on deserialisation it will fail since the current assumption is that all types are boxed
To indicate an array of unboxed type we add the syntax <type>[p]
> Add support for serialising arrays of unboxed primitives

- core/src/main/kotlin/net/corda/core/serialization/amqp/ArraySerializer.kt
- core/src/test/kotlin/net/corda/core/serialization/amqp/DeserializeSimpleTypesTests.kt
We were relying on the Java typename conversion to work for our AMQP
envelope type selection, and only special casing arrays of primitives.
However with nested arrays this breaks as the intermediate serialises
for the nested arrays still have no idea as to what the underlaying type
is as the assumption will be being made that the type is a boxed
primitive.
Solution is to compute the typename properly, walking down the nested
array chain
> Ensure typename is calculated correctly for nested arrays

- client/jfx/src/integration-test/kotlin/net/corda/client/jfx/NodeMonitorModelTest.kt
- client/jfx/src/main/kotlin/net/corda/client/jfx/model/ContractStateModel.kt
- client/jfx/src/main/kotlin/net/corda/client/jfx/model/NodeMonitorModel.kt
- client/jfx/src/main/kotlin/net/corda/client/jfx/utils/ObservableUtilities.kt
- client/rpc/src/main/kotlin/net/corda/client/rpc/internal/RPCClientProxyHandler.kt
- core/src/main/kotlin/net/corda/core/messaging/CordaRPCOps.kt
- core/src/main/kotlin/net/corda/core/node/services/VaultQueryService.kt
- core/src/main/kotlin/net/corda/core/node/services/VaultService.kt
- core/src/test/kotlin/net/corda/core/node/VaultUpdateTests.kt
- docs/source/example-code/src/integration-test/kotlin/net/corda/docs/IntegrationTestingTutorial.kt
- node/src/main/kotlin/net/corda/node/internal/CordaRPCOpsImpl.kt
- node/src/main/kotlin/net/corda/node/services/schema/HibernateObserver.kt
- node/src/main/kotlin/net/corda/node/services/vault/HibernateVaultQueryImpl.kt
- node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt
- node/src/test/java/net/corda/node/services/vault/VaultQueryJavaTests.java
- node/src/test/kotlin/net/corda/node/CordaRPCOpsImplTest.kt
- node/src/test/kotlin/net/corda/node/services/schema/HibernateObserverTests.kt
- node/src/test/kotlin/net/corda/node/services/vault/NodeVaultServiceTest.kt
- test-utils/src/main/kotlin/net/corda/testing/Expect.kt
Add generics to Vault.Update so that the type of the contract state is propagated through to the right places when we know it specifically (because we restricted our vault query to a particular state type).
Introduce some helpers on DataFeed for JavaFX users. This simplifies UI code in the event bookings app quite a bit.
> Generify Vault.Update<T>, add a JavaFX utility and fix a daemon thread issue

- core/src/main/kotlin/net/corda/core/serialization/DefaultKryoCustomizer.kt
This change is related to the discussions forum link:
https://discourse.corda.net/t/simple-corda-rpc-client-getting-class-kotlin-collections-emptylist-is-not-annotated-or-on-the-whitelist-so-cannot-be-used-in-serialization/1315
This changes the DefaultKryoCustomizer class to pass the class loader in the ServiceLoader.load call instead of relying on the default behaviour of using the thread context class loader. This allows apps with custom class loader hierarchies to use corda.
> Changed the ServiceLoader.load call to explicitly specify the class loader

- core/src/main/kotlin/net/corda/core/serialization/amqp/PropertySerializer.kt
- core/src/test/kotlin/net/corda/core/serialization/amqp/DeserializeSimpleTypesTests.kt
The recent changes that were put in to allow chars to be serialised at
all failed to take into account nullability and thus if a char was null
and that object was first serlialised then desierliased it would throw
a NPE
> Serialising null chars was broken

- core/src/main/kotlin/net/corda/core/serialization/carpenter/ClassCarpenter.kt
This fix really only applies to the testing case where, to test the
carpenter as it integrates with the deserialzer we need classes not
found on the class path. To do this they can be created by a second
class carpenter
However, the original carpenter *always* added SimpleFieldAccess as an
interface to the class it would be creating. Under normal circumstances
that's fine as that interface wouldn't be in the list of interfaces
given to the carpenter for the class it's being asked to created.
However, if as described above the carpenter schema was synthesised from
a class that was carpented it will.
If this happens we get an error as understandably you can't have a
duplicate interface.
Fix is to simply check weather the list of interfaces the schema
describes and only add SimpleFieldAccess …
> Don't blindly add SimpleFieldAccess as interface to carpented classes

- node/src/main/kotlin/net/corda/node/services/identity/InMemoryIdentityService.kt
There was a bug in M13 where `InMemoryIdentityService.partiesByName` was broken as `HashSet` is not on the serialisation whitelist due to it being non-deterministic.
`LinkedHashSet` is on the whitelist, as it is deterministic, so we can use that instead.
> Use LinkedHashSet instead of HashSet as HashSet is not on the whitelist!

- core/src/main/kotlin/net/corda/core/contracts/Structures.kt
- core/src/test/kotlin/net/corda/core/contracts/TransactionTests.kt
- core/src/test/kotlin/net/corda/core/crypto/PartialMerkleTreeTest.kt
> Minor: Add a test to ensure "identical" issue transactions have different ids

- samples/trader-demo/src/main/kotlin/net/corda/traderdemo/TraderDemoClientApi.kt
- samples/trader-demo/src/main/kotlin/net/corda/traderdemo/flow/SellerFlow.kt
* Remove BOC reference from trader demo client API as it fails at runtime because the test constants are not available.
* Disable anonymisation in the command line trader demo.
> Remove BOC reference from trader demo client API

- node/src/main/kotlin/net/corda/node/services/api/ServiceHubInternal.kt
- samples/notary-demo/src/main/kotlin/net/corda/notarydemo/flows/DummyIssueAndMove.kt
Shams, I've asked you to review because I've changed a test you added to `ServiceHubInternal`, do let me know if this is an inappropriate solution. Previously however in the RAFT notary case it for some reason double-records transactions, which leads to it throwing an error as after filtering the `recordedTransactions` list is empty.
> Correct notary demo in M14

- node/src/main/kotlin/net/corda/node/services/vault/HibernateQueryCriteriaParser.kt
- node/src/test/kotlin/net/corda/node/services/vault/VaultQueryTests.kt
Bug surfaced in TraderDemo integration test where assertions use vault custom query aggregate function to count number of states of a given contract type (commercial paper, cash). 
This PR ensures the contract type filter is applied to all 4 types of VaultQueryCriteria:
```
VaultQueryCriteria
LinearStateQueryCriteria
FungibleAssetQueryCriteria
VaultCustomQueryCriteria
```
> Applied contract type filtering to ALL Query Criteria types 

- docs/source/api-index.rst
Just a very small change to the Sphinx docs as I was getting annoyed that the API pages don't have links in the TOC. The "API: blah" pages now show up in the TOC and also each "API: blah" page has the menu so you don't need to go back to the main "API" page to get to the page for each "API: blah" page.
Before (as it currently is):
After (this PR):
> Docs: Stop the API pages being orphaned without a menu

- docs/source/changelog.rst
- node/src/main/kotlin/net/corda/node/services/vault/HibernateQueryCriteriaParser.kt
- node/src/test/kotlin/net/corda/node/services/vault/VaultQueryTests.kt
Query was matching on a single issuer party name.
> Vault Query fix: query by multiple issuer party names.

- core/src/main/kotlin/net/corda/core/node/services/VaultService.kt
- core/src/main/kotlin/net/corda/core/node/services/vault/QueryCriteria.kt
- docs/source/api-vault-query.rst
- docs/source/changelog.rst
- docs/source/soft-locking.rst
- node/src/main/kotlin/net/corda/node/services/database/HibernateConfiguration.kt
- node/src/main/kotlin/net/corda/node/services/vault/HibernateQueryCriteriaParser.kt
- node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt
- node/src/test/kotlin/net/corda/node/services/vault/NodeVaultServiceTest.kt
- node/src/test/kotlin/net/corda/node/services/vault/VaultQueryTests.kt
- node/src/test/kotlin/net/corda/node/services/vault/VaultWithCashTest.kt
Removed deprecated `softLockStates` query method from `VaultService`
Introduced flexible `SoftLockingCondition` filterable attribute in `VaultQueryCriteria`
> Improvements to Vault Query Service soft locked state querying

- samples/notary-demo/src/main/kotlin/net/corda/notarydemo/Notarise.kt
- samples/notary-demo/src/main/kotlin/net/corda/notarydemo/flows/DummyIssueAndMove.kt
* DummyContract inlined and spectator code removed
* Should be more robust than the fix currently in M14, the Cash stuff is a distraction from demonstrating notarisation
* All 3 notary demos tested in IntelliJ and from gradle
> Fix the BFT notary demo

- core/src/main/kotlin/net/corda/core/serialization/Kryo.kt
This class isn't currently used, which probably explains why this hasn't been caught, but it looks strange to see a set of prim types and have only seven instead of eight
> Boolean primitive type is missing

- samples/notary-demo/src/main/kotlin/net/corda/notarydemo/flows/DummyIssueAndMove.kt
* Use Cash contract instead of DummyContract in notary demo to remove dependency on test utils
* Check transactions to be recorded before filtering rather than after, as currently if the entire
list of transactions is already recorded, it's mis-reported as an empty input.
> Sync notary demo fixes from M14

- docs/source/api-vault-query.rst
- node/src/main/kotlin/net/corda/node/services/database/HibernateConfiguration.kt
- test-common/src/main/resources/log4j2-test.xml
Was previously setting Hibernate SQL statement debug logging by explicitly setting a boolean flag in code.
This PR removes the unnecessary debug variable and delegates configuration to equivalent log4j2.xml.
> Specify correct use of Hibernate SQL statement debug output

- client/jackson/src/main/kotlin/net/corda/jackson/JacksonSupport.kt
- client/jackson/src/test/kotlin/net/corda/jackson/JacksonSupportTest.kt
By default it attempts to serialize any property (anything that looks like a _getter_), which causes issues on the SignedTransaction, since it attempts to resolve both a regular and a notary change transaction from the serialized bytes.
@andr3ej discovered it causes an exception on the shell:
```
>>> run verifiedTransactionsFeed
RPC failed: java.lang.ClassCastException: net.corda.core.transactions.WireTransaction cannot be cast to net.corda.core.transactions.NotaryChangeWireTransaction
```
> Fix jackson serialization of transaction types. 

- core/src/main/kotlin/net/corda/core/node/services/VaultService.kt
- docs/source/changelog.rst
- docs/source/example-code/src/main/kotlin/net/corda/docs/FxTransactionBuildTutorial.kt
- docs/source/flow-state-machines.rst
- docs/source/tutorial-building-transactions.rst
- docs/source/tutorial-contract.rst
- finance/src/main/java/net/corda/contracts/JavaCommercialPaper.java
- finance/src/main/kotlin/net/corda/contracts/CommercialPaper.kt
- finance/src/main/kotlin/net/corda/contracts/asset/Cash.kt
- finance/src/main/kotlin/net/corda/contracts/asset/OnLedgerAsset.kt
- finance/src/main/kotlin/net/corda/flows/CashExitFlow.kt
- finance/src/main/kotlin/net/corda/flows/CashPaymentFlow.kt
- finance/src/main/kotlin/net/corda/flows/TwoPartyTradeFlow.kt
- finance/src/test/kotlin/net/corda/contracts/CommercialPaperTests.kt
- finance/src/test/kotlin/net/corda/contracts/asset/CashTests.kt
- node/build.gradle
- node/src/main/kotlin/net/corda/node/services/vault/HibernateQueryCriteriaParser.kt
- node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt
- node/src/test/java/net/corda/node/services/vault/VaultQueryJavaTests.java
- node/src/test/kotlin/net/corda/node/messaging/TwoPartyTradeFlowTests.kt
- node/src/test/kotlin/net/corda/node/services/database/HibernateConfigurationTest.kt
- node/src/test/kotlin/net/corda/node/services/vault/NodeVaultServiceTest.kt
- node/src/test/kotlin/net/corda/node/services/vault/VaultQueryTests.kt
- node/src/test/kotlin/net/corda/node/services/vault/VaultWithCashTest.kt
- samples/notary-demo/src/main/kotlin/net/corda/notarydemo/flows/DummyIssueAndMove.kt
- test-utils/src/main/kotlin/net/corda/testing/contracts/VaultFiller.kt
- test-utils/src/main/kotlin/net/corda/testing/node/MockServices.kt
The original Vault queries in the NodeVaultService for unconsumedStatesForSpending and then in turn for generateSpend were tied to the Cash schema. This PR uses the new functionality on ServiceHub to move the original queries onto the Cash contract inside the finance module.
I have added back to the VaultService a VaultQuery based equivalent of unconsumedStatesForSpending  called tryLockFungibleStatesForSpending that can work for any FungibleAsset and allows people to write queries that filter on custom account fields, etc.
During this work I then discovered that numerous tests were depending upon an assumption that consumed states were taken in a particular order (FIFO submission order), which is not the case. Therefore I have fixed up the tests.
This work has allowed me to break the …
> Move generateSpend onto Cash contract. Add fully generic replacement.

- node/src/test/kotlin/net/corda/node/services/events/ScheduledFlowTests.kt
Store loaded states as a map instead of as lists, so that the comparison is not
order dependent.
> Store loaded states as a map

- core/src/main/kotlin/net/corda/core/schemas/converters/AbstractPartyConverter.kt
- core/src/main/kotlin/net/corda/core/schemas/converters/AbstractPartyToX500NameAsStringConverter.kt
- docs/source/api-persistence.rst
- docs/source/changelog.rst
- finance/src/test/kotlin/net/corda/contracts/asset/CashTests.kt
- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/main/kotlin/net/corda/node/services/database/HibernateConfiguration.kt
- node/src/main/kotlin/net/corda/node/services/vault/VaultSchema.kt
- node/src/test/java/net/corda/node/services/vault/VaultQueryJavaTests.java
- node/src/test/kotlin/net/corda/node/services/database/HibernateConfigurationTest.kt
- node/src/test/kotlin/net/corda/node/services/schema/HibernateObserverTests.kt
- node/src/test/kotlin/net/corda/node/services/vault/NodeVaultServiceTest.kt
- node/src/test/kotlin/net/corda/node/services/vault/VaultQueryTests.kt
- node/src/test/kotlin/net/corda/node/services/vault/VaultWithCashTest.kt
- test-utils/src/main/kotlin/net/corda/testing/node/MockServices.kt
Schema entity attributes with an `AbstractParty` type will be stored according to the following rules:
- (concrete) Party -> store string'ified X500Name
- Anonymous Party -> if resolvable to legal identity (using identityService), store string'ified X500Name of resolved identity
- Anonymous Party -> if not resolvable (eg. legal identity not owner) then store `null` value
> JPA Hibernate AbstractParty converter

- docs/source/changelog.rst
- docs/source/running-the-demos.rst
- finance/src/main/kotlin/net/corda/flows/TwoPartyTradeFlow.kt
- samples/trader-demo/build.gradle
- samples/trader-demo/src/integration-test/kotlin/net/corda/traderdemo/TraderDemoTest.kt
- samples/trader-demo/src/main/kotlin/net/corda/traderdemo/TraderDemo.kt
- samples/trader-demo/src/main/kotlin/net/corda/traderdemo/TraderDemoClientApi.kt
- samples/trader-demo/src/main/kotlin/net/corda/traderdemo/flow/BankFlow.kt
- samples/trader-demo/src/main/kotlin/net/corda/traderdemo/flow/CommercialPaperIssueFlow.kt
- samples/trader-demo/src/main/kotlin/net/corda/traderdemo/flow/SellerFlow.kt
Follow up to #1157 which eliminates the hard coded party from the sample. The workflow is now that the Bank of Corda node does the actual commercial paper issuance, rather than the seller self-issuing commercial paper with the Bank of Corda's name on it.
> Issue commercial paper from the Bank of Corda node

- core/src/main/kotlin/net/corda/core/crypto/Crypto.kt
- core/src/main/kotlin/net/corda/core/crypto/X500NameUtils.kt
- core/src/test/kotlin/net/corda/core/crypto/CompositeKeyTests.kt
- core/src/test/kotlin/net/corda/core/crypto/X509NameConstraintsTest.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/KryoTests.kt
- node/src/integration-test/kotlin/net/corda/services/messaging/MQSecurityAsNodeTest.kt
- node/src/main/kotlin/net/corda/node/services/config/ConfigUtilities.kt
- node/src/main/kotlin/net/corda/node/services/keys/KMSUtils.kt
- node/src/main/kotlin/net/corda/node/services/messaging/ArtemisMessagingServer.kt
- node/src/main/kotlin/net/corda/node/utilities/X509Utilities.kt
- node/src/main/kotlin/net/corda/node/utilities/registration/HTTPNetworkRegistrationService.kt
- node/src/main/kotlin/net/corda/node/utilities/registration/NetworkRegistrationHelper.kt
- node/src/test/kotlin/net/corda/node/services/network/InMemoryIdentityServiceTests.kt
- node/src/test/kotlin/net/corda/node/utilities/X509UtilitiesTest.kt
- node/src/test/kotlin/net/corda/node/utilities/registration/NetworkisRegistrationHelperTest.kt
- test-utils/src/main/kotlin/net/corda/testing/CoreTestUtils.kt
- test-utils/src/main/kotlin/net/corda/testing/TestConstants.kt
- test-utils/src/main/kotlin/net/corda/testing/driver/Driver.kt
- test-utils/src/main/kotlin/net/corda/testing/node/InMemoryMessagingNetwork.kt
- test-utils/src/main/kotlin/net/corda/testing/node/NodeBasedTest.kt
- tools/demobench/src/main/kotlin/net/corda/demobench/model/NodeController.kt
- tools/demobench/src/test/kotlin/net/corda/demobench/model/NodeControllerTest.kt
- verifier/src/integration-test/kotlin/net/corda/verifier/GeneratedLedger.kt
- verifier/src/integration-test/kotlin/net/corda/verifier/VerifierDriver.kt
The certificate code is implementation detail, not API. So I have moved the parts of X509Utilities and Crypto for certificates into the node. This leaves X500Name related functions, so I have renamed the core api file to X500Name.
> Move certificate builder code from core to node utilities.

- core/src/main/kotlin/net/corda/core/transactions/TransactionWithSignatures.kt
- docs/source/example-code/src/main/java/net/corda/docs/FlowCookbookJava.java
`checkSignaturesAreValid()` calls `TransactionSignature.verify()`, which throws `InvalidKeyException` but `checkSignaturesAreValid()` did not indicate it could throw `InvalidKeyException`.
> Correct exceptions thrown from checkSignaturesAreValid()

- core/src/main/kotlin/net/corda/core/node/ServiceHub.kt
- core/src/main/kotlin/net/corda/core/transactions/SignedTransaction.kt
- core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
- docs/source/api-service-hub.rst
- docs/source/changelog.rst
- docs/source/hello-world-flow.rst
- docs/source/tut-two-party-flow.rst
- docs/source/tutorial-contract.rst
- docs/source/using-a-notary.rst
- finance/src/main/kotlin/net/corda/flows/TwoPartyDealFlow.kt
- finance/src/test/kotlin/net/corda/contracts/CommercialPaperTests.kt
- finance/src/test/kotlin/net/corda/contracts/asset/CashTests.kt
- node/src/test/java/net/corda/node/services/vault/VaultQueryJavaTests.java
- node/src/test/kotlin/net/corda/node/messaging/TwoPartyTradeFlowTests.kt
- node/src/test/kotlin/net/corda/node/services/database/HibernateConfigurationTest.kt
- node/src/test/kotlin/net/corda/node/services/vault/NodeVaultServiceTest.kt
- node/src/test/kotlin/net/corda/node/services/vault/VaultQueryTests.kt
- node/src/test/kotlin/net/corda/node/services/vault/VaultWithCashTest.kt
- samples/irs-demo/src/main/kotlin/net/corda/irs/flows/FixingFlow.kt
- samples/irs-demo/src/main/kotlin/net/corda/irs/flows/RatesFixFlow.kt
- test-utils/src/main/kotlin/net/corda/testing/contracts/VaultFiller.kt
Remove deprecated signing functions from `TransactionBuilder`, introducing replacement functions where needed for specific cases (i.e. signatures provided by a third party node or unit tests).
> Remove deprecated signing functions

- core/src/main/kotlin/net/corda/core/node/services/vault/QueryCriteria.kt
- core/src/main/kotlin/net/corda/core/node/services/vault/QueryCriteriaUtils.kt
- docs/source/example-code/src/test/kotlin/net/corda/docs/WorkflowTransactionBuildTutorialTest.kt
- finance/src/main/kotlin/net/corda/contracts/FinanceTypes.kt
- finance/src/main/kotlin/net/corda/flows/TwoPartyDealFlow.kt
- node/src/main/kotlin/net/corda/node/services/schema/NodeSchemaService.kt
- node/src/main/kotlin/net/corda/node/services/vault/HibernateQueryCriteriaParser.kt
- node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt
- node/src/main/kotlin/net/corda/node/services/vault/VaultSchema.kt
- node/src/test/java/net/corda/node/services/vault/VaultQueryJavaTests.java
- node/src/test/kotlin/net/corda/node/services/vault/VaultQueryTests.kt
- node/src/test/kotlin/net/corda/node/services/vault/VaultWithCashTest.kt
- samples/irs-demo/src/main/kotlin/net/corda/irs/api/InterestRateSwapAPI.kt
- samples/irs-demo/src/main/kotlin/net/corda/irs/contract/IRS.kt
- samples/simm-valuation-demo/src/main/kotlin/net/corda/vega/contracts/IRSState.kt
- samples/simm-valuation-demo/src/main/kotlin/net/corda/vega/contracts/PortfolioState.kt
- test-utils/src/main/kotlin/net/corda/testing/contracts/DummyDealContract.kt
- test-utils/src/main/kotlin/net/corda/testing/schemas/DummyDealStateSchemaV1.kt
One of the lingering finance dependencies inside the NodeSchemaService is the DealState, because we allow filters against the ref field. However, we always allowed the equivalent data inside the linearId as this has an externalId field. Also, the query by linearId isn't quite the same as the equality function on the UniqueIdentifier class, which is by UUID only.
Therefore I have moved to make the usages all point at linearid component and allowed separate queries for the two components of the linearId.
> Remove DealState dependency inside Vault

- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializerFactory.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/DeserializeNeedingCarpentrySimpleTypesTest.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/DeserializeNeedingCarpentryTests.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/DeserializeSimpleTypesTests.kt
This removed the need to calculate anything on de-serialisation if using
the same factory
Ran the IntelliJ reformatter on one of the files so there are some moderately spurious whitespace changes
> Optimise by caching class when serialising

- core/src/main/kotlin/net/corda/core/node/services/IdentityService.kt
- node/src/main/kotlin/net/corda/node/services/identity/InMemoryIdentityService.kt
- test-utils/src/main/kotlin/net/corda/testing/node/MockNode.kt
Correct behaviour of anonymousToParty() in identity API; it previously presumed any Party was a well known identity, now it tries to look up the well known identity irrespective of whether it's been given a full party or not.
> Correct behaviour of anonymousToParty()

- node/src/main/kotlin/net/corda/node/internal/Node.kt
- node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt
- samples/irs-demo/src/integration-test/kotlin/net/corda/irs/IRSDemoTest.kt
- test-utils/src/main/kotlin/net/corda/testing/driver/Driver.kt
- test-utils/src/main/kotlin/net/corda/testing/node/NodeBasedTest.kt
This PR moves the `if (useTestClock)` conditional into the Node's constructor. I also included a change to the IRS demo test so it uses proper logging.
This is a result of a debugging session in the enterprise repo, but this changeset should be in open source
> Move useTestClock conditional to Node constructor

- core/src/test/kotlin/net/corda/core/contracts/LedgerTransactionQueryTests.kt
- core/src/test/kotlin/net/corda/core/contracts/TransactionGraphSearchTests.kt
- finance/src/main/kotlin/net/corda/contracts/asset/Obligation.kt
- finance/src/test/kotlin/net/corda/contracts/asset/ObligationTests.kt
- node/src/test/kotlin/net/corda/node/services/NotaryChangeTests.kt
- node/src/test/kotlin/net/corda/node/services/database/RequeryConfigurationTest.kt
- node/src/test/kotlin/net/corda/node/services/events/ScheduledFlowTests.kt
- node/src/test/kotlin/net/corda/node/services/persistence/DBTransactionStorageTests.kt
- node/src/test/kotlin/net/corda/node/services/statemachine/FlowFrameworkTests.kt
- node/src/test/kotlin/net/corda/node/services/transactions/NotaryServiceTests.kt
- node/src/test/kotlin/net/corda/node/services/transactions/ValidatingNotaryServiceTests.kt
- node/src/test/kotlin/net/corda/node/services/vault/VaultWithCashTest.kt
- samples/irs-demo/src/test/kotlin/net/corda/irs/api/NodeInterestRatesTest.kt
- test-utils/src/main/kotlin/net/corda/testing/TestConstants.kt
- test-utils/src/main/kotlin/net/corda/testing/contracts/VaultFiller.kt
Transaction validity rules dictate that every tx must have at least one command (the actual check will be enforced in a subsequent PR)
> Ensure transactions in tests have commands

- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/main/kotlin/net/corda/node/services/vault/HibernateQueryCriteriaParser.kt
- node/src/main/kotlin/net/corda/node/services/vault/HibernateVaultQueryImpl.kt
- node/src/test/kotlin/net/corda/node/services/vault/VaultQueryTests.kt
- test-utils/src/main/kotlin/net/corda/testing/node/MockServices.kt
Removed unnecessary additional SQL query used to build a map of contract state interfaces to concrete types stored in the vault. This map is now build dynamically by subscribing directly to vault state updates (using "rawupdate" observable).
> Vault Query performance fix

- core/src/main/kotlin/net/corda/core/serialization/SerializationAPI.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/AMQPSerializationScheme.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/DefaultKryoCustomizer.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/SerializationScheme.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/KryoTests.kt
- test-utils/src/main/kotlin/net/corda/testing/SerializationTestHelpers.kt
- verifier/src/main/kotlin/net/corda/verifier/Verifier.kt
The main one is the custom serialiser for `PrivacySalt` so that we can deserialise it without incidentally invoking the default constructor. (Because a dummy RNG would then try to initialise the object with a constraint-violating all-zero array before replacing the array with the proper values.)
There's also a spelling fix and minor tidy of the `KryoVerifierSerializationScheme` class.
> Simple deserialisation fixes.

- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/SerializationTokenTest.kt
The test still needs a bit more work as some private classes cannot be serialized with AMQP, e.g.:
java.io.NotSerializableException: Unexpected throwable: Class net.corda.nodeapi.internal.serialization.amqp.ObjectSerializer can not access a member of class net.corda.nodeapi.internal.serialization.SerializationTokenTest$LargeTokenizable with modifiers "public" java.lang.IllegalAccessException: Class net.corda.nodeapi.internal.serialization.amqp.ObjectSerializer can not access a member of class net.corda.nodeapi.internal.serialization.SerializationTokenTest$LargeTokenizable with modifiers "public"
at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102)
at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:296)
at …
> Eliminate explicit Kryo configuration to allow flexibility for AMQP

- core/src/main/kotlin/net/corda/core/flows/FlowStackSnapshot.kt
- test-utils/src/main/kotlin/net/corda/testing/FlowStackSnapshot.kt
This is a very minor change, that is intended to simplify the FlowStackSnapshot instance serialization/deserialization process.
> Use String instead of Class for the flowClass

- node-api/src/test/java/net/corda/nodeapi/internal/serialization/amqp/JavaSerializationOutputTests.java
Somehow this slipped past Gradle that I hadn't changed the serializer
factory here to take the needed argument now it's no longer defaulted
> Re-re-move Java test to the correct location, fix compile issue

- node/src/main/kotlin/net/corda/node/services/statemachine/StateMachineManager.kt
- test-utils/src/main/kotlin/net/corda/testing/driver/Driver.kt
Providing a hint to a developer on test failure caused by missing Quasar java agent.
> Adding hint on how to fix the 'not instrumented' error message

- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/ObjectSerializer.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/PropertySerializer.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/Schema.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializationHelper.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializerFactory.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/SingletonSerializer.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/carpenter/ClassCarpenter.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/AMQPTestUtils.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/DeserializeAndReturnEnvelopeTests.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/DeserializeNeedingCarpentryTests.kt
Don't attempt to include non-serializable interfaces in schemas, since things like `Comparable` don't make sense to include and build serializers for, and we wouldn't know how to implement the associated methods in the carpenter.
I also discovered, after fixing this, that we need to make the getter accessible with reflection to avoid a bunch of errors when running unit tests with AMQP turned on.
> AMQP fixes: Don't attempt to include non-serializable interfaces in schemas 

- core/src/main/kotlin/net/corda/core/contracts/FungibleAsset.kt
- core/src/main/kotlin/net/corda/core/contracts/Structures.kt
- core/src/test/kotlin/net/corda/core/contracts/LedgerTransactionQueryTests.kt
- core/src/test/kotlin/net/corda/core/flows/ContractUpgradeFlowTest.kt
- docs/source/example-code/src/main/java/net/corda/docs/FlowCookbookJava.java
- docs/source/example-code/src/main/kotlin/net/corda/docs/FlowCookbook.kt
- docs/source/using-a-notary.rst
- finance/src/main/kotlin/net/corda/contracts/asset/Cash.kt
- finance/src/main/kotlin/net/corda/contracts/asset/CommodityContract.kt
- finance/src/main/kotlin/net/corda/contracts/asset/Obligation.kt
- finance/src/main/kotlin/net/corda/contracts/asset/OnLedgerAsset.kt
- finance/src/test/kotlin/net/corda/contracts/asset/CashTests.kt
- finance/src/test/kotlin/net/corda/contracts/asset/DummyFungibleContract.kt
- finance/src/test/kotlin/net/corda/contracts/asset/ObligationTests.kt
This is part of the [finance CorDapp improvements](https://discourse.corda.net/t/various-things-to-improve-in-the-finance-cordapp/1386)
IssueCommand is also totally removed as no nonce is required anymore and all Issues can be `TypeOnlyCommandData`
> Remove grouping from FungibleAsset (Issue and Move)

- core/src/main/kotlin/net/corda/core/utilities/ByteArrays.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/AMQPSerializationScheme.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/custom/OpaqueBytesSubSequenceSerializer.kt
As discussed with @rick-r3 - limit amount of data we sent over the wire in case when OpaqueBytesSubSequence only point to a smaller section of the referenced ByteArray
> Make OpaqueBytesSubSequence AMQP serializable

- core/src/main/kotlin/net/corda/core/contracts/Structures.kt
The old text on Issued is not sufficiently detailed and confuses people who see the Amount<Issued<T>> on FungibleAsset. This tries to expand upon the explanation.
> Attempt to explain the Issued class

- core/src/main/kotlin/net/corda/core/flows/CollectSignaturesFlow.kt
- core/src/test/kotlin/net/corda/core/flows/CollectSignaturesFlowTests.kt
- node/src/test/kotlin/net/corda/node/messaging/TwoPartyTradeFlowTests.kt
- samples/network-visualiser/src/main/kotlin/net/corda/netmap/simulation/IRSSimulation.kt
Adapt `CollectSignaturesFlow` to handle anonymous transactions where the keys signing commands on a transaction are not necessarily the well known identity of the participating nodes. Also prepares for any potential move away from nodes having a single primary identity by requiring flows to specify
the identities they're using for a transaction.
> Adapt CollectSignaturesFlow to handle anonymous transactions

- build.gradle
- test-utils/src/main/kotlin/net/corda/testing/SerializationTestHelpers.kt
This can be useful if we decide to create a custom TeamCity configuration that will enable us to independently run *all* tests in AMQP mode to know where we stand.
I have tested that it runs locally from root of Git repo using the following command:
`gradlew -Dnet.corda.testing.amqp.enable=true clean build`
> Introduced a property to be able to enable AMQP mode from command line for Gradle run

- client/rpc/src/main/kotlin/net/corda/client/rpc/internal/RPCClient.kt
- client/rpc/src/main/kotlin/net/corda/client/rpc/internal/RPCClientProxyHandler.kt
- tools/demobench/src/main/kotlin/net/corda/demobench/pty/R3Pty.kt
- tools/demobench/src/main/kotlin/net/corda/demobench/rpc/NodeRPC.kt
This fixes the demobench UI freeze issue.
The proposed solution is to extend the `close` function (on the `RPCConnection` and `RPCClientProxyHandler`) with a possibility to choose either to notify the counterparty via the AMQP messaging or to skip this step. Previously, the close function was always notifying the counterpart. This caused accessing the Artemis message queue (in order to send the `close` message), which was unable to deliver the message to the other side. The timeout for this process was blocking the UI. 
As a remedy an overload for the aforementioned `close` function has been added and from the DemoBench project it is called with a parameter requesting the skipping of the counterpart notification.
> Fixing demobench freeze on terminal command 'bye'

- core/src/main/kotlin/net/corda/core/node/services/vault/QueryCriteria.kt
- core/src/main/kotlin/net/corda/core/node/services/vault/QueryCriteriaUtils.kt
- docs/source/api-vault-query.rst
- docs/source/changelog.rst
- node/src/main/kotlin/net/corda/node/services/vault/HibernateQueryCriteriaParser.kt
- node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt
- node/src/test/java/net/corda/node/services/vault/VaultQueryJavaTests.java
- node/src/test/kotlin/net/corda/node/services/vault/VaultQueryTests.kt
Removed `QueryEditor` implementation from `NodeVaultService`.
Query parsing now ensures there is a single SQL specification for common attributes:
1) Vault.StateStatus is now overridable (last override wins)
2) Contract state types are now aggregatable (single combined set used in SQL query).
Addresses PR [Vault Query Criteria defaults handling](https://r3-cev.atlassian.net/browse/CORDA-504)
Also includes a performance fix:
Prevent self joins on VaultStates table (occurring when using a ``Sort`` criteria)
> Vault query criteria default attribute handling.

- node/src/main/kotlin/net/corda/node/services/transactions/RaftUniquenessProvider.kt
Without this setting of the Copycat library, it will make no attept to reconnect after intermittent network failure or other cases and it starts throwing exceptions about event executor being shut down.
> Enable autorecovery in RAFT Copycat client

- node/src/integration-test/kotlin/net/corda/services/messaging/P2PMessagingTest.kt
- node/src/main/kotlin/net/corda/node/services/api/AbstractNodeService.kt
- node/src/main/kotlin/net/corda/node/services/api/ServiceHubInternal.kt
- node/src/main/kotlin/net/corda/node/services/messaging/Messaging.kt
- node/src/main/kotlin/net/corda/node/services/messaging/ServiceRequestMessage.kt
- node/src/main/kotlin/net/corda/node/services/network/InMemoryNetworkMapCache.kt
- node/src/main/kotlin/net/corda/node/services/network/NetworkMapService.kt
- node/src/test/kotlin/net/corda/node/messaging/InMemoryMessagingTests.kt
- node/src/test/kotlin/net/corda/node/services/messaging/ArtemisMessagingTests.kt
- node/src/test/kotlin/net/corda/node/services/network/AbstractNetworkMapServiceTest.kt
Move default session ID into messaging service to clean up the API. This means it no longer shows up in a Java class (`ServiceHubInternalKt`) as its only member, and is instead scoped into the service that actually uses the value. This does result in a `MessagingService.Companion` object (as `MessagingService` is an interface), however this is probably the most sensible solution.
> Move default session ID into messaging service

- core/src/main/kotlin/net/corda/core/flows/IdentitySyncFlow.kt
- core/src/test/kotlin/net/corda/core/flows/IdentitySyncFlowTests.kt
- node/src/test/kotlin/net/corda/node/messaging/TwoPartyTradeFlowTests.kt
Add IdentitySyncFlow for synchronizing the certificate paths for confidential identities in a transaction with all counterparties of the transaction.
> Add IdentitySyncFlow

- core/src/main/kotlin/net/corda/core/node/services/vault/QueryCriteria.kt
- node/src/main/kotlin/net/corda/node/services/vault/HibernateQueryCriteriaParser.kt
- node/src/test/java/net/corda/node/services/vault/VaultQueryJavaTests.java
- node/src/test/kotlin/net/corda/node/services/vault/VaultQueryTests.kt
Re-introduce the `linearId: List<UniqueIdentifier>` Vault Query search attribute on `LinearStateQueryCriteria` for CorDapp developer convenience and ease of use.
This was removed in [PR#1237](https://github.com/corda/corda/pull/1237) as part of a refactoring exercise.
Note: the same assumptions still apply (ie. equality on `UniqueIdentifier` only takes into account the `UUID` field, and **not** the optional `externalId`). Should this equality check change in future, the Vault Query criteria implementation will be modified accordingly but the API will remain consistent.
> Revert `linearId` (UniqueIdentifier) Vault Query search attribute

- docs/source/api-persistence.rst
- docs/source/api-vault-query.rst
- node/src/test/kotlin/net/corda/node/services/database/HibernateConfigurationTest.kt
- node/src/test/kotlin/net/corda/node/services/events/ScheduledFlowTests.kt
Removed redundant deprecated query examples.
Updated old references (party query).
Add extra sample showing paging iteration.
Added additional references to ServiceHub jdbcSession()
Fixed incorrect code in jdbcSession() code snippet example.
> Updated vault query api documentation.

- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializationOutput.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/AMQPTestUtils.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/DeserializeAndReturnEnvelopeTests.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializeAndReturnSchemaTest.kt
For future testing it would be nice, post serialisation, to have easy
access to the serialised objects schema so we can check how it was
serialised. Adding a helper function to return a data class that does
this in the same way we can for deserialize
> Add alt serialise method that returns the schema and the bytes

- core/src/main/kotlin/net/corda/core/contracts/Structures.kt
- core/src/main/kotlin/net/corda/core/transactions/BaseTransaction.kt
- core/src/main/kotlin/net/corda/core/transactions/WireTransaction.kt
- experimental/src/test/kotlin/net/corda/finance/contracts/universal/Cap.kt
- experimental/src/test/kotlin/net/corda/finance/contracts/universal/Caplet.kt
- experimental/src/test/kotlin/net/corda/finance/contracts/universal/FXFwdTimeOption.kt
- experimental/src/test/kotlin/net/corda/finance/contracts/universal/FXSwap.kt
- experimental/src/test/kotlin/net/corda/finance/contracts/universal/IRS.kt
- experimental/src/test/kotlin/net/corda/finance/contracts/universal/RollOutTests.kt
- experimental/src/test/kotlin/net/corda/finance/contracts/universal/Swaption.kt
- experimental/src/test/kotlin/net/corda/finance/contracts/universal/ZeroCouponBond.kt
- finance/src/test/java/net/corda/finance/contracts/asset/CashTestsJava.java
- finance/src/test/kotlin/net/corda/finance/contracts/asset/CashTests.kt
- node/src/integration-test/kotlin/net/corda/node/services/BFTNotaryServiceTests.kt
- node/src/integration-test/kotlin/net/corda/node/services/RaftNotaryServiceTests.kt
- node/src/integration-test/kotlin/net/corda/node/services/statemachine/LargeTransactionsTest.kt
- samples/attachment-demo/src/main/kotlin/net/corda/attachmentdemo/AttachmentDemo.kt
- test-utils/src/main/kotlin/net/corda/testing/CoreTestUtils.kt
- test-utils/src/main/kotlin/net/corda/testing/TestDSL.kt
- test-utils/src/main/kotlin/net/corda/testing/TransactionDSLInterpreter.kt
As per https://r3-cev.atlassian.net/browse/CORDA-485 we decided to disallow transactions that have no commands, and transactions with no input and output states.
> Additional transaction validation rules

- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/main/kotlin/net/corda/node/services/persistence/HibernateConfiguration.kt
- node/src/main/kotlin/net/corda/node/services/schema/HibernateObserver.kt
- node/src/main/kotlin/net/corda/node/services/vault/HibernateVaultQueryImpl.kt
- node/src/main/kotlin/net/corda/node/utilities/CordaPersistence.kt
- node/src/test/kotlin/net/corda/node/services/persistence/DBTransactionStorageTests.kt
- node/src/test/kotlin/net/corda/node/services/persistence/HibernateConfigurationTest.kt
- test-utils/src/main/kotlin/net/corda/testing/node/MockServices.kt
Move `HibernateConfiguration` into `net.corda.node.services.persistence` as having a single-class package that's differentiated from the persistence package seems excessive.
> Move HibernateConfiguration into net.corda.node.services.persistence

- tools/demobench/build.gradle
Upgrade to TornadoFX 1.7.10 now that we've upgraded to Kotlin 1.1.4.
> Upgrade DemoBench to TornadoFX 1.7.10

- client/jackson/src/main/kotlin/net/corda/client/jackson/JacksonSupport.kt
- client/jackson/src/main/kotlin/net/corda/client/jackson/StringToMethodCallParser.kt
- client/jackson/src/test/kotlin/net/corda/client/jackson/JacksonSupportTest.kt
- client/jackson/src/test/kotlin/net/corda/client/jackson/StringToMethodCallParserTest.kt
- docs/packages.md
- node/src/main/java/net/corda/node/shell/RunShellCommand.java
- node/src/main/kotlin/net/corda/node/shell/InteractiveShell.kt
- node/src/test/kotlin/net/corda/node/InteractiveShellTest.kt
- samples/irs-demo/src/integration-test/kotlin/net/corda/irs/IRSDemoTest.kt
- samples/network-visualiser/src/main/kotlin/net/corda/netmap/simulation/IRSSimulation.kt
- test-utils/src/integration-test/kotlin/net/corda/testing/FlowStackSnapshotTest.kt
- test-utils/src/main/kotlin/net/corda/testing/FlowStackSnapshot.kt
- test-utils/src/main/kotlin/net/corda/testing/http/HttpApi.kt
- test-utils/src/main/kotlin/net/corda/testing/http/HttpUtils.kt
- webserver/src/main/kotlin/net/corda/webserver/internal/NodeWebServer.kt
Move Jackson client support into net.corda.client.jackson package to match naming scheme used elsewhere
> Move Jackson client support into net.corda.client.jackson package

- core/src/main/kotlin/net/corda/core/contracts/Structures.kt
- docs/source/api-vault-query.rst
- docs/source/changelog.rst
- docs/source/example-code/src/main/kotlin/net/corda/docs/WorkflowTransactionBuildTutorial.kt
- node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt
- node/src/test/kotlin/net/corda/node/services/events/NodeSchedulerServiceTest.kt
- node/src/test/kotlin/net/corda/node/services/events/ScheduledFlowTests.kt
- node/src/test/kotlin/net/corda/node/services/vault/NodeVaultServiceTest.kt
- samples/irs-demo/src/main/kotlin/net/corda/irs/contract/IRS.kt
- samples/simm-valuation-demo/src/main/kotlin/net/corda/vega/contracts/IRSState.kt
- samples/simm-valuation-demo/src/main/kotlin/net/corda/vega/contracts/PortfolioState.kt
- test-utils/src/main/kotlin/net/corda/testing/contracts/DummyDealContract.kt
- test-utils/src/main/kotlin/net/corda/testing/contracts/DummyLinearContract.kt
* added a flag in the config file to allow storing of irrelevant states in the vault.
* added relevancy to CommonQueryCriteria for querying irrelevant states.
> Removed is relevant from LinearState.

- node/src/main/kotlin/net/corda/node/services/events/NodeSchedulerService.kt
- node/src/main/kotlin/net/corda/node/services/statemachine/StateMachineManager.kt
- node/src/test/kotlin/net/corda/node/services/events/NodeSchedulerServiceTest.kt
- node/src/test/kotlin/net/corda/node/services/statemachine/FlowFrameworkTests.kt
- samples/irs-demo/src/test/kotlin/net/corda/irs/flows/UpdateBusinessDayFlow.kt
This catches a bunch of unit tests where it's missing and also resolves an issue I saw Roger hit the other day.
Additionally, adds a missing exception logging path.
> Throw a diagnostic exception if your FlowLogic.call method is not marked as @Suspendable.

- experimental/build.gradle
- finance/build.gradle
- finance/src/main/java/net/corda/finance/contracts/JavaCommercialPaper.java
Declare Guava as a `cordaCompile` dependency so that we don't bundle it inside the finance module.
> Remove the copy of Guava from within the finance module.

- client/jfx/src/main/kotlin/net/corda/client/jfx/model/ExchangeRateModel.kt
- client/jfx/src/main/kotlin/net/corda/client/jfx/utils/AmountBindings.kt
- core/src/main/kotlin/net/corda/core/contracts/Amount.kt
Rewrite `ExchangeRate` to use `BigDecimal` for the quantity multiplication, to ensure that there is no loss of precision during the conversion process.
Also extends `Amount` to provide a multiplication function with rounding mode specified.
> Rewrite ExchangeRate to use BigDecimal

- core/src/test/java/net/corda/core/flows/FlowsInJavaTest.java
- core/src/test/kotlin/net/corda/core/flows/AttachmentTests.kt
- core/src/test/kotlin/net/corda/core/flows/CollectSignaturesFlowTests.kt
- core/src/test/kotlin/net/corda/core/flows/ContractUpgradeFlowTest.kt
- core/src/test/kotlin/net/corda/core/flows/FinalityFlowTests.kt
- core/src/test/kotlin/net/corda/core/flows/ManualFinalityFlowTests.kt
- core/src/test/kotlin/net/corda/core/internal/concurrent/CordaFutureImplTest.kt
- core/src/test/kotlin/net/corda/core/serialization/AttachmentSerializationTest.kt
- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/main/kotlin/net/corda/node/internal/Node.kt
- node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt
- node/src/main/kotlin/net/corda/node/services/network/NetworkMapService.kt
- test-utils/src/main/kotlin/net/corda/testing/node/MockNode.kt
Registration may fail due to low level serialization problems especially when running in AMQP mode
Also some minor improvements for exceptions reporting and test coverage
> CORDA-540: Ensure that registration of a test node was a success prior to performing further testing with it

- finance/src/main/kotlin/net/corda/finance/contracts/CommercialPaper.kt
- finance/src/main/kotlin/net/corda/finance/contracts/FinanceTypes.kt
- finance/src/main/kotlin/net/corda/finance/contracts/asset/CommodityContract.kt
- samples/irs-demo/src/main/kotlin/net/corda/irs/contract/IRS.kt
Eliminate generated `...Kt` classes, to make Java API cleaner
Part of https://r3-cev.atlassian.net/browse/CORDA-499
> Eliminate generated `Kt` classes

- constants.properties
- core/build.gradle
- gradle-plugins/quasar-utils/src/main/groovy/net/corda/plugins/QuasarPlugin.groovy
- node/src/integration-test/kotlin/net/corda/node/services/statemachine/FlowVersioningTest.kt
- samples/network-visualiser/build.gradle
- verifier/build.gradle
We want `quasar-core` as a runtime dependency rather than a compile dependency so that we are still able to exclude it from any "fat jars" that we build. The `QuasarPlugin` only installs `quasar-core` as a Java agent, and runtime scope is fine for that.
Add `quasar-core` to `:core` as a non-transitive "compileOnly" dependency so that we still have access to the `@Suspendable` annotation.
This change also flushed a (known) Quasar/Kotlin instrumentation bug in `FlowVersioningTest`, which @exFalso helped me fix.
And I've corrected the use of `capsule` in `network-visualiser` too, for good measure.
> Demote quasar-core to a runtime dependency.

- samples/notary-demo/src/main/kotlin/net/corda/notarydemo/flows/DummyIssueAndMove.kt
The notary demo got reverted to a cash version that didn't work, due to incorrect use of soft-locking.
This reverts to a simple custom state suitable for showing notary logic.
> Fix notary demo

- core/src/main/kotlin/net/corda/core/messaging/CordaRPCOps.kt
- node/src/main/kotlin/net/corda/node/internal/CordaRPCOpsImpl.kt
- node/src/main/kotlin/net/corda/node/services/api/ServiceHubInternal.kt
- node/src/test/kotlin/net/corda/node/CordaRPCOpsImplTest.kt
Usage of `<T: Any>` in RPC calls to `startFlow*()` prevents calling Flows which return nothing (eg. Void). Compiler is unable to resolve the typed parameter for Void (as this is not a subtype of Any).
> Enable RPC start of Flows that return nothing (eg. Void).

- core/src/main/kotlin/net/corda/core/flows/NotaryFlow.kt
- core/src/main/kotlin/net/corda/core/transactions/SignedTransaction.kt
- docs/source/changelog.rst
Required to bypass the wire transaction `tx`. Our aim is to minimise access to `WireTransaction`. I used the same method name for consistency.
> Helper SignedTransaction.buildFilteredTransaction(filtering)

- core/src/main/kotlin/net/corda/core/crypto/CompositeKey.kt
- core/src/main/kotlin/net/corda/core/crypto/CompositeKeyFactory.kt
- core/src/main/kotlin/net/corda/core/crypto/CordaSecurityProvider.kt
- core/src/main/kotlin/net/corda/core/crypto/Crypto.kt
- core/src/main/kotlin/net/corda/core/crypto/CryptoUtils.kt
- core/src/main/kotlin/net/corda/core/crypto/DigitalSignature.kt
- core/src/main/kotlin/net/corda/core/crypto/MerkleTree.kt
- core/src/main/kotlin/net/corda/core/crypto/SecureHash.kt
- core/src/main/kotlin/net/corda/core/crypto/SignableData.kt
- core/src/main/kotlin/net/corda/core/crypto/SignatureScheme.kt
- core/src/main/kotlin/net/corda/core/transactions/MerkleTransaction.kt
The `Alg.Alias.Signature.OID` in `CordaSecurityProvider` was still using the keyOID vs signatureOID.
Also did some minor clean up, mainly in comments and api docs references.
> Composite Signature OID fix and crypto comments clean up

- test-utils/src/main/kotlin/net/corda/testing/driver/Driver.kt
This timeout is introduced after experiencing the test hanging issue. It took me some time to find out what the cause was. This will provide a quick failover with the TimeoutException being thrown.
> Adding time limit for Driver address binding.

- constants.properties
- gradle-plugins/cordformation/src/main/groovy/net/corda/plugins/Cordformation.groovy
when trying to build nodes for a project with a file as a dependency and any other dependencies without a group
This will need to be backported to M14 as well.
It fixes the issue described in this SO post; https://stackoverflow.com/questions/46004915/getting-an-error-when-adding-a-3rd-party-jar-file
> Fixed a crash in cordformation 

- client/jfx/src/main/kotlin/net/corda/client/jfx/model/NodeMonitorModel.kt
- core/src/main/kotlin/net/corda/core/messaging/CordaRPCOps.kt
- docs/source/example-code/src/main/kotlin/net/corda/docs/ClientRpcTutorial.kt
- node/src/main/kotlin/net/corda/node/internal/CordaRPCOpsImpl.kt
- node/src/test/kotlin/net/corda/node/CordaRPCOpsImplTest.kt
- samples/attachment-demo/src/main/kotlin/net/corda/attachmentdemo/AttachmentDemo.kt
- tools/demobench/src/main/kotlin/net/corda/demobench/views/NodeTerminalView.kt
Both methods are not included in the JavaDocs anymore.
> Deprecating verifiedTransactions from the public API

- docs/source/example-code/build.gradle
The example code uses cash flows and contracts, but doesn't depend on the finance CorDapp. This happens to work at the moment but breaks other changes currently in progress.
> Add missing finance CorDapp depdendency to example code

- core/src/test/kotlin/net/corda/core/flows/CollectSignaturesFlowTests.kt
- core/src/test/kotlin/net/corda/core/flows/ContractUpgradeFlowTest.kt
- core/src/test/kotlin/net/corda/core/flows/IdentitySyncFlowTests.kt
- core/src/test/kotlin/net/corda/core/flows/TransactionKeyFlowTests.kt
- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/main/kotlin/net/corda/node/internal/CordaRPCOpsImpl.kt
- node/src/main/kotlin/net/corda/node/services/identity/PersistentIdentityService.kt
- node/src/main/kotlin/net/corda/node/services/schema/NodeSchemaService.kt
- node/src/main/kotlin/net/corda/node/utilities/PersistentMap.kt
- node/src/test/kotlin/net/corda/node/messaging/TwoPartyTradeFlowTests.kt
- node/src/test/kotlin/net/corda/node/services/network/NetworkMapCacheTest.kt
- node/src/test/kotlin/net/corda/node/services/network/PersistentIdentityServiceTests.kt
- node/src/test/kotlin/net/corda/node/services/statemachine/FlowFrameworkTests.kt
- samples/network-visualiser/src/main/kotlin/net/corda/netmap/simulation/IRSSimulation.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/MockNode.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/MockServices.kt
The existing IdentityService implementation is not persistent. This work creates a PersistentMap extension so that identities are stored permanently in the DB. This in turn has exposed a few hidden bugs, so a few of those are fixed here too so that tests pass.
> Create Persistent Identity Service

- core/src/main/kotlin/net/corda/core/flows/AbstractStateReplacementFlow.kt
- core/src/main/kotlin/net/corda/core/flows/ContractUpgradeFlow.kt
- core/src/main/kotlin/net/corda/core/messaging/CordaRPCOps.kt
- core/src/main/kotlin/net/corda/core/node/services/ContractUpgradeService.kt
- core/src/test/kotlin/net/corda/core/flows/ContractUpgradeFlowTest.kt
- docs/source/changelog.rst
- docs/source/contract-upgrade.rst
- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/main/kotlin/net/corda/node/internal/CordaRPCOpsImpl.kt
- node/src/main/kotlin/net/corda/node/services/CoreFlowHandlers.kt
- node/src/main/kotlin/net/corda/node/services/schema/NodeSchemaService.kt
- node/src/main/kotlin/net/corda/node/services/upgrade/ContractUpgradeServiceImpl.kt
- test-utils/src/main/kotlin/net/corda/testing/contracts/DummyContractV2.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/MockServices.kt
All Contract Upgrade functionality performed within a flow.
Removed RPC API calls for contract upgrade authorisation / de-authorisation.
Added persistence using PersistentMap.
> Contract Upgrade API improvements + persistence

- node/src/main/kotlin/net/corda/node/utilities/registration/NetworkRegistrationHelper.kt
Reshuffle docs on NetworkRegistrationHelper, and in particular note that it can cause the whole
process to exit.
> Reshuffle docs on NetworkRegistrationHelper

- node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt
The vault code is making a spurious and expensive call to get all node keys. This should be removed
> Remove dead and expensive call to key management service

- core/src/main/kotlin/net/corda/core/serialization/SerializationAPI.kt
- core/src/main/kotlin/net/corda/core/transactions/MerkleTransaction.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/Kryo.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/SerializationScheme.kt
- node-api/src/test/kotlin/net/corda/nodeapi/AttachmentClassLoaderTests.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/CordaClassResolverTests.kt
- testing/test-utils/src/main/kotlin/net/corda/testing/SerializationTestHelpers.kt
Allows grabbing the current context and then modifying before calling recursively (e.g. to use attachment class loader).
Also added attachment class loader support in preparation for changes from @kchalkias 
Also made some nicer ways to refer to defaults for serialization.
> Introduce current context concept for serialization in preparation for WireTransaction changes

- client/jfx/src/main/kotlin/net/corda/client/jfx/utils/ObservableFold.kt
- client/jfx/src/main/kotlin/net/corda/client/jfx/utils/ObservableUtilities.kt
- client/jfx/src/main/kotlin/net/corda/client/jfx/utils/ReadOnlyBackedObservableMapBase.kt
- client/mock/src/main/kotlin/net/corda/client/mock/Generator.kt
- client/mock/src/main/kotlin/net/corda/client/mock/Generators.kt
- client/rpc/src/main/kotlin/net/corda/client/rpc/internal/RPCClientProxyHandler.kt
- core/src/main/kotlin/net/corda/core/concurrent/ConcurrencyUtils.kt
- core/src/main/kotlin/net/corda/core/messaging/FlowHandle.kt
- core/src/main/kotlin/net/corda/core/node/services/ServiceInfo.kt
- core/src/test/kotlin/net/corda/core/flows/IdentitySyncFlowTests.kt
- core/src/test/kotlin/net/corda/core/flows/TransactionKeyFlowTests.kt
- samples/network-visualiser/src/main/kotlin/net/corda/netmap/simulation/Simulation.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/RPCDriver.kt
- tools/explorer/src/main/kotlin/net/corda/explorer/ExplorerSimulation.kt
- tools/loadtest/src/main/kotlin/net/corda/loadtest/tests/CrossCashTest.kt
- tools/loadtest/src/main/kotlin/net/corda/loadtest/tests/GenerateHelpers.kt
- tools/loadtest/src/main/kotlin/net/corda/loadtest/tests/NotaryTest.kt
- tools/loadtest/src/main/kotlin/net/corda/loadtest/tests/SelfIssueTest.kt
- verifier/src/integration-test/kotlin/net/corda/verifier/VerifierTests.kt
Continued cleanup of Kotlin structure to eliminate (where possible) generated `...Kt` classes.
> CORDA-499: Dokka 'Kt' class cleanup

- core/src/test/kotlin/net/corda/core/flows/IdentitySyncFlowTests.kt
- core/src/test/kotlin/net/corda/core/flows/TransactionKeyFlowTests.kt
Remove unneeded identity registrations from tests, which sometimes cause duplicated entries in the database, leading to instability in these two tests.
> Remove unneeded identity registration

- node/src/main/kotlin/net/corda/node/services/vault/VaultSchema.kt
This change also removes the 100,000 hard size constraint.
This change is aligned with other schema changes to map all Kotlin `ByteArray` types to explicit Hibernate `Lob` annotations.
> Redefine VaultSchema attribute of serialized Contract state to LOB 

- core/src/main/kotlin/net/corda/core/contracts/TransactionGraphSearch.kt
- core/src/test/kotlin/net/corda/core/contracts/TransactionGraphSearchTests.kt
- samples/trader-demo/src/main/kotlin/net/corda/traderdemo/TransactionGraphSearch.kt
- samples/trader-demo/src/main/kotlin/net/corda/traderdemo/flow/BuyerFlow.kt
- samples/trader-demo/src/test/kotlin/net/corda/traderdemo/TransactionGraphSearchTests.kt
* Remove internal state of TransactionGraphSearch from being publicly visible.
* Add Dokka comments for TransactionGraphSearch.Query values.
* Move query into TransactionGraphSearch constructor as it should always be set except for test cases.
> CORDA-499: Restructure TransactionGraphSearch to be Dokka-friendly

- node/src/test/kotlin/net/corda/node/messaging/TwoPartyTradeFlowTests.kt
[CORDA-460]: Removed usages of deprecated APIs in the codebase. `CordaRPCOps.internalVerifiedTransactionsFeed(): DataFeed<List<SignedTransaction>, SignedTransaction>` could not be removed at this stage. Not sure why it's already deprecated.
> [CORDA-460]: Removed usages of deprecated APIs in the codebase.

- samples/notary-demo/src/main/kotlin/net/corda/notarydemo/RaftNotaryCordform.kt
Using the same CN causes the directories to collapse and override, leaving only last one
> Raft Notary Demo fix

- core/src/main/kotlin/net/corda/core/contracts/AttachmentConstraint.kt
Or else many core/contract unit tests failing in AMQP mode
> CORDA-540: Correctly mark AttachmentConstraint to be CordaSerializable

- docs/build.gradle
This adds the `node-driver` and `test-utils` testing modules to Dokka.
> CORDA-499: Add testing classes to Dokka

- docs/source/changelog.rst
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/carpenter/ClassCarpenter.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/carpenter/Exceptions.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/carpenter/MetaCarpenter.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/carpenter/Schema.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/carpenter/SchemaFields.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/carpenter/ClassCarpenterTest.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/carpenter/ClassCarpenterTestUtils.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/carpenter/EnumClassTests.kt
If the serializer is going to support enumerated types then the class
carpenter also has to
Refactor the Carpenter schema and fields to add an enum type, add code
in the carpenter to generate enum's and of course add tests
> CORDA-539 - Add enum support to the carpenter

- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/EnumSerializer.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializerFactory.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/carpenter/AMQPSchemaExtensions.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/carpenter/MetaCarpenter.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/carpenter/SchemaFields.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/DeserializeNeedingCarpentryOfEnumsTest.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/DeserializeNeedingCarpentrySimpleTypesTest.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/carpenter/MultiMemberCompositeSchemaToClassCarpenterTests.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/carpenter/SingleMemberCompositeSchemaToClassCarpenterTests.kt
Final piece to integrate enums and the serialiser, given we can currently carpent them and serialise them, add the capability to generate enum schemas in the serialiser when a type is missing
> CORDA-539 - Integrate enum carpentry into serializer factory

- node/src/main/kotlin/net/corda/node/utilities/registration/NetworkRegistrationHelper.kt
- node/src/test/kotlin/net/corda/node/utilities/registration/NetworkisRegistrationHelperTest.kt
fix a bug where network registration helper creates a SSL cert with wrong X500 name
> SSL cert wrong X500Name fix

- constants.properties
- gradle-plugins/cordformation/src/main/groovy/net/corda/plugins/Cordformation.groovy
Open Source modules are `net.corda`, whereas Enterprise modules are `com.r3.corda.enterprise`. We don't want CorDapps to contain either.
> Filter for Open Source and Enterprise modules.

- client/rpc/src/integration-test/java/net/corda/client/rpc/CordaRPCJavaClientTest.java
- finance/src/main/kotlin/net/corda/finance/Currencies.kt
- finance/src/test/java/net/corda/finance/contracts/asset/CashTestsJava.java
- finance/src/test/kotlin/net/corda/finance/CurrenciesTests.kt
Rename CurrencyUtils to Currencies to explain why it's not in the finance utils package. Replaces #1403
> CORDA-499: Rename CurrencyUtils to Currencies

- docs/source/running-the-demos.rst
Fix the indent of the last bulletpoints in the lists under:
https://docs.corda.net/running-the-demos.html#trader-demo
> fix .rst, enumerations must have a blank line at the end

- samples/bank-of-corda-demo/build.gradle
Fix https://r3-cev.atlassian.net/browse/CORDA-563
A node named in both code and gradle had 2 different names.
Changed the name in the gradle script, by dropping the OrganizaionUnit
> Arri fix corda 563

- finance/src/main/kotlin/net/corda/finance/contracts/asset/Cash.kt
- finance/src/main/kotlin/net/corda/finance/contracts/asset/OnLedgerAsset.kt
- finance/src/test/kotlin/net/corda/finance/contracts/asset/CashTests.kt
Reverts corda/corda#1522
Reported on public Slack:
https://ci-master.corda.r3cev.com/viewType.html?buildTypeId=Corda_CordaBuild&tab=buildTypeStatusDiv&guest=1
> Revert "Modify generateSpend() to send change to a fresh confidential identity"

- finance/src/main/kotlin/net/corda/finance/contracts/asset/Cash.kt
- finance/src/main/kotlin/net/corda/finance/contracts/asset/OnLedgerAsset.kt
- finance/src/test/kotlin/net/corda/finance/contracts/asset/CashTests.kt
[Modify generateSpend() to send change to a fresh confidential identity](https://github.com/corda/corda/pull/1522) was merged to master following successful Unit and Integration test completion, but nevertheless broke the master build with a compilation error (possible cause is a time delay between build and merge to master - in which other PRs were merged to master, but did not trigger an auto-build of this one.) 
This PR fixes the compilation error.
> FIX - Modify generateSpend() to send change to a fresh confidential identity

- confidential-identities/build.gradle
- confidential-identities/src/main/kotlin/net/corda/confidential/SwapIdentitiesHandler.kt
Tidy up the `build.gradle` for `confidential-identities` so that:
- Kotlin classes are not bundled into the CorDapp.
- We don't build an unwanted `tests` jar.
Also fix some minor compiler warnings.
> Remove Kotlin classes from confidential-identities.

- constants.properties
- gradle-plugins/cordformation/src/main/groovy/net/corda/plugins/Cordformation.groovy
Ensure that `kotlin-reflect` is not bundled into CorDapps, because this artifact is expected to be imported from the Node.
> Exclude kotlin-reflect artifact from any CorDapp.

- tools/explorer/src/main/kotlin/net/corda/explorer/views/GuiUtilities.kt
- tools/explorer/src/main/kotlin/net/corda/explorer/views/LoginView.kt
- tools/explorer/src/main/kotlin/net/corda/explorer/views/MainView.kt
minor UI tweak: make the Node explorer dialog have a non empty title.
That will show more nicely in application bars and lists
> Set title for node explorer windows

- core/src/main/kotlin/net/corda/core/crypto/Crypto.kt
- core/src/main/kotlin/net/i2p/crypto/eddsa/KludgeEdDSAEngine.kt
- core/src/main/kotlin/net/i2p/crypto/eddsa/X509EdDSAEngine.kt
- core/src/test/kotlin/net/corda/core/identity/PartyAndCertificateTest.kt
Works around an issue with deserialized X.509 certificates containing EdDSA keys that the library we use cannot accept. A permanent fix should go into the library, this is just an interim solution.
> CORDA-579: Add EdDSA engine that understands X.509 keys

- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/main/kotlin/net/corda/node/services/upgrade/ContractUpgradeServiceImpl.kt
- node/src/test/kotlin/net/corda/node/messaging/TwoPartyTradeFlowTests.kt
Discovered by accident, on another branch, that if ServiceHub got captured on the stack then it didn't serialize correctly.  Turns out it and many of the services on it were not registered for tokenisation.
> Fix serialization of ServiceHub

- core/src/main/kotlin/net/corda/core/contracts/ComponentGroupEnum.kt
- core/src/main/kotlin/net/corda/core/contracts/Structures.kt
- core/src/main/kotlin/net/corda/core/crypto/CryptoUtils.kt
- core/src/main/kotlin/net/corda/core/crypto/PartialMerkleTree.kt
- core/src/main/kotlin/net/corda/core/crypto/SecureHash.kt
- core/src/main/kotlin/net/corda/core/serialization/MissingAttachmentsException.kt
- core/src/main/kotlin/net/corda/core/transactions/MerkleTransaction.kt
- core/src/main/kotlin/net/corda/core/transactions/NotaryChangeTransactions.kt
- core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
- core/src/main/kotlin/net/corda/core/transactions/WireTransaction.kt
- core/src/test/kotlin/net/corda/core/contracts/CompatibleTransactionTests.kt
- core/src/test/kotlin/net/corda/core/contracts/DummyContractV2Tests.kt
- core/src/test/kotlin/net/corda/core/crypto/PartialMerkleTreeTest.kt
- docs/source/changelog.rst
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/Kryo.kt
- node-api/src/test/kotlin/net/corda/nodeapi/AttachmentsClassLoaderTests.kt
- node/src/main/kotlin/net/corda/node/services/transactions/BFTNonValidatingNotaryService.kt
- node/src/main/kotlin/net/corda/node/services/transactions/NonValidatingNotaryFlow.kt
- samples/irs-demo/src/main/kotlin/net/corda/irs/api/NodeInterestRates.kt
- samples/irs-demo/src/test/kotlin/net/corda/irs/api/NodeInterestRatesTest.kt
To allow for backwards compatibility in the transaction format (both wire and filtered), one should be able to compute the Merkle root without knowing all of a transaction's components. 
This design suggests that each component group (inputs, outputs, commands, attachments, notary, timeWindow) has its own Merkle tree. Then, each distinct Merkle root from every component-based sub-tree is now used as a leaf on a top-level Merkle tree, as depicted below.
The new format for each of the above transaction types is
`WireTransaction(
val componentGroups: List<ComponentGroup>, 
val privacySalt: PrivacySalt = PrivacySalt())` 
and
`FilteredTransaction(
val id: SecureHash,
val filteredComponentGroups: List<FilteredComponentGroup>,
private val partialMerkleTree: PartialMerkleTree)`
Also, …
> CORDA-521: Backwards compatible Transactions using sub-Merkle trees

- core/src/main/kotlin/net/corda/core/flows/NotaryFlow.kt
- core/src/main/kotlin/net/corda/core/node/ServiceHub.kt
- core/src/main/kotlin/net/corda/core/node/services/NotaryService.kt
- docs/source/example-code/src/main/kotlin/net/corda/docs/CustomNotaryTutorial.kt
- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/main/kotlin/net/corda/node/services/transactions/BFTNonValidatingNotaryService.kt
- node/src/main/kotlin/net/corda/node/services/transactions/BFTSMaRt.kt
- node/src/main/kotlin/net/corda/node/services/transactions/NonValidatingNotaryFlow.kt
- node/src/main/kotlin/net/corda/node/services/transactions/RaftNonValidatingNotaryService.kt
- node/src/main/kotlin/net/corda/node/services/transactions/RaftValidatingNotaryService.kt
- node/src/main/kotlin/net/corda/node/services/transactions/SimpleNotaryService.kt
- node/src/main/kotlin/net/corda/node/services/transactions/ValidatingNotaryFlow.kt
- node/src/main/kotlin/net/corda/node/services/transactions/ValidatingNotaryService.kt
- node/src/test/kotlin/net/corda/node/messaging/TwoPartyTradeFlowTests.kt
- node/src/test/kotlin/net/corda/node/services/transactions/NotaryServiceTests.kt
- node/src/test/kotlin/net/corda/node/services/transactions/ValidatingNotaryServiceTests.kt
- testing/node-driver/src/main/kotlin/net/corda/node/testing/MockServiceHubInternal.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/MockNode.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/MockServices.kt
It was redundant, as we have notary field on a transaction. Notaries can
use this field to check if the transaction was meant for them and then
use that information while choosing a key to sign a transaction.
> Remove notaryIdentityKey from ServiceHub

- confidential-identities/src/main/kotlin/net/corda/confidential/IdentitySyncFlow.kt
- confidential-identities/src/test/kotlin/net/corda/confidential/IdentitySyncFlowTests.kt
- finance/src/main/kotlin/net/corda/finance/flows/TwoPartyTradeFlow.kt
Move IdentitySyncFlow into confidential-identities for consistency in where confidential identity components are in the 1.0 release.
> Move IdentitySyncFlow into confidential-identities

- core/src/main/kotlin/net/corda/core/crypto/CompositeSignature.kt
- core/src/main/kotlin/net/corda/core/messaging/CordaRPCOps.kt
- docs/source/example-code/src/main/java/net/corda/docs/FlowCookbookJava.java
- finance/src/main/kotlin/net/corda/finance/contracts/CommercialPaper.kt
- finance/src/main/kotlin/net/corda/finance/contracts/asset/Cash.kt
- finance/src/main/kotlin/net/corda/finance/contracts/asset/Obligation.kt
- finance/src/test/java/net/corda/finance/contracts/asset/CashTestsJava.java
- samples/irs-demo/src/main/kotlin/net/corda/irs/contract/IRS.kt
- samples/simm-valuation-demo/src/main/kotlin/net/corda/vega/contracts/IRSState.kt
- testing/test-utils/src/main/kotlin/net/corda/testing/contracts/DummyContract.kt
- testing/test-utils/src/main/kotlin/net/corda/testing/contracts/DummyContractV2.kt
Add annotations and change values to be constant in order to clean up generated Javadocs. Cut down version of #1575
> CORDA-499: Dokka cleanup for 1.0

- client/jackson/src/main/kotlin/net/corda/client/jackson/JacksonSupport.kt
- confidential-identities/src/main/kotlin/net/corda/confidential/IdentitySyncFlow.kt
- confidential-identities/src/test/kotlin/net/corda/confidential/IdentitySyncFlowTests.kt
- confidential-identities/src/test/kotlin/net/corda/confidential/SwapIdentitiesFlowTests.kt
- core/src/main/kotlin/net/corda/core/messaging/CordaRPCOps.kt
- core/src/main/kotlin/net/corda/core/node/ServiceHub.kt
- core/src/main/kotlin/net/corda/core/node/services/IdentityService.kt
- docs/source/api-rpc.rst
- docs/source/example-code/src/main/java/net/corda/docs/FlowCookbookJava.java
- docs/source/example-code/src/main/kotlin/net/corda/docs/FlowCookbook.kt
- docs/source/tutorial-attachments.rst
- finance/src/main/kotlin/net/corda/finance/flows/CashExitFlow.kt
- finance/src/main/kotlin/net/corda/finance/flows/TwoPartyDealFlow.kt
- finance/src/main/kotlin/net/corda/finance/flows/TwoPartyTradeFlow.kt
- node/src/integration-test/kotlin/net/corda/node/services/statemachine/LargeTransactionsTest.kt
- node/src/main/kotlin/net/corda/node/internal/CordaRPCOpsImpl.kt
- node/src/main/kotlin/net/corda/node/services/identity/InMemoryIdentityService.kt
- node/src/main/kotlin/net/corda/node/services/identity/PersistentIdentityService.kt
- node/src/main/kotlin/net/corda/node/services/network/PersistentNetworkMapCache.kt
- node/src/main/kotlin/net/corda/node/services/persistence/AbstractPartyToX500NameAsStringConverter.kt
- node/src/test/kotlin/net/corda/node/services/network/InMemoryIdentityServiceTests.kt
- node/src/test/kotlin/net/corda/node/services/network/PersistentIdentityServiceTests.kt
- samples/attachment-demo/src/main/kotlin/net/corda/attachmentdemo/AttachmentDemo.kt
- samples/bank-of-corda-demo/src/main/kotlin/net/corda/bank/api/BankOfCordaClientApi.kt
- samples/bank-of-corda-demo/src/main/kotlin/net/corda/bank/api/BankOfCordaWebApi.kt
- samples/irs-demo/src/main/kotlin/net/corda/irs/flows/FixingFlow.kt
- samples/simm-valuation-demo/src/main/kotlin/net/corda/vega/flows/SimmFlow.kt
- samples/simm-valuation-demo/src/main/kotlin/net/corda/vega/flows/SimmRevaluation.kt
- samples/trader-demo/src/main/kotlin/net/corda/traderdemo/TraderDemoClientApi.kt
The partyFromXXX methods on IdentityService actually return different forms of Party. Some return well known Parties i.e. In NetworkMapCache and some return the requested Party only i.e. only qualify the X500Name for a key. To make this clearer this PR just renames those returning a well known party.
There has been lots of debate about making well known identity type safe, but for now I am just cleaning the API.
> Clarify method names on IdentityService for well known party methods

- core/src/main/kotlin/net/corda/core/crypto/CompositeKey.kt
- experimental/src/main/kotlin/net/corda/finance/contracts/universal/UniversalContract.kt
- finance/src/main/kotlin/net/corda/finance/contracts/asset/cash/selection/CashSelectionH2Impl.kt
- finance/src/main/kotlin/net/corda/finance/contracts/asset/cash/selection/CashSelectionMySQLImpl.kt
- node-api/src/main/kotlin/net/corda/nodeapi/VerifierApi.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/Schema.kt
- node/src/main/kotlin/net/corda/node/services/network/NetworkMapService.kt
- node/src/main/kotlin/net/corda/node/utilities/KeyStoreUtilities.kt
- node/src/main/kotlin/net/corda/node/utilities/X509Utilities.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/InMemoryMessagingNetwork.kt
There are a number of places in the code where we have Kotlin values which appear to be constants. As-is, these are exposed to Java via getter methods, for example `getKEY_ALGORITHM()`. By changing them to constants they are instead exposed in a more natural way, for example as `KEY_ALGORITHM`.
This change has impact on Java API, and therefore I'd like to get it in for 1.0 if practical.
> Change public constant values to Kotlin constants

- core/src/main/kotlin/net/corda/core/flows/ContractUpgradeFlow.kt
- core/src/main/kotlin/net/corda/core/internal/ContractUpgradeUtils.kt
- core/src/test/kotlin/net/corda/core/flows/ContractUpgradeFlowTest.kt
- docs/source/changelog.rst
- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/main/kotlin/net/corda/node/internal/cordapp/CordappLoader.kt
- node/src/main/kotlin/net/corda/node/services/CoreFlowHandlers.kt
- node/src/test/kotlin/net/corda/node/cordapp/CordappLoaderTest.kt
- testing/test-utils/src/main/kotlin/net/corda/testing/contracts/DummyContractV2.kt
This includes moving the Acceptor out of core as it's not meant to be started directly
> Cleaned up ContractUpgradeFlow API

- node/src/main/kotlin/net/corda/node/shell/InteractiveShell.kt
- node/src/test/kotlin/net/corda/node/InteractiveShellTest.kt
Identity transformations from JSON now need a database transaction and a few cases were missed inside the crash shell. This adds in the required fix for https://r3-cev.atlassian.net/browse/CORDA-606.
> Ensure Shell parsing of commands has a database

- core/src/main/kotlin/net/corda/core/identity/PartyAndCertificate.kt
- docs/source/serialization.rst
This PR introduces the concept of the migration to AMQP (but does not yet detail the format itself) and describes the "core types" that will be supported when we move to AMQP serialization, which are very closely aligned to those supported under Kryo.
> CORDA-205: Supported core types documentation

- docs/source/api-index.rst
- docs/source/other-index.rst
- docs/source/release-process-index.rst
Also move coding style to 'other' where it belongs.
> Update docsite with some notes on which APIs are stabilised and which are not.

- core/src/main/kotlin/net/corda/core/contracts/Structures.kt
Pretty print for keys on `Command.toString()` to remove the ugly net.i2p.crypto.eddsa.EdDSAPublicKey@a008fda0 when printing info about transactions.
It will print the hash of signers' keys:
Transaction:
▶︎INPUT:      7E81CBEC6A4281697E5A366623C692B90EF1E4439B71B7D0A0C473FE56470141(0)
▶︎INPUT:      F9AA9322B83651C88D330D55F574228D672CFCC26118B7F5FCDDB4D0BC9A18B4(1)
▶︎INPUT:      44ACD46E9A8E6B5F9542981FF7F37F17279021348A0087EF634F60C46A0E29E4(0)
OUTPUT:     DummyState(magicNumber=0)
OUTPUT:     DummyState(magicNumber=0)
COMMAND:   Move(contract=null) with pubkeys **DLuthJPURTGFuGvyivv3EEwD7QeSkgGhrDK4d4SEj6HeD, DLBVrDkXKJpuK2iEyJqnu3V99BkYbnBbgNAUja1p1WCyQp**
> Command toString signers keys format

- node/src/test/kotlin/net/corda/node/services/identity/InMemoryIdentityServiceTests.kt
- node/src/test/kotlin/net/corda/node/services/identity/PersistentIdentityServiceTests.kt
Move identity service tests from `net.corda.services.network` to `net.corda.services.identity` to match the service classes they correspond to.
> Move identity service tests

- finance/src/main/kotlin/net/corda/finance/contracts/asset/cash/selection/CashSelectionH2Impl.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/DeserializationInput.kt
- node/src/main/kotlin/net/corda/node/services/messaging/Messaging.kt
- node/src/main/kotlin/net/corda/node/utilities/AddressUtils.kt
- node/src/test/kotlin/net/corda/node/services/events/ScheduledFlowTests.kt
- tools/explorer/src/main/kotlin/net/corda/explorer/identicon/IdenticonRenderer.kt
Follow-up to #1588 to change remaining constant values into `const` types, targeting 1.1.
> Change constants values to Kotlin const type

- samples/notary-demo/src/main/kotlin/net/corda/notarydemo/BFTNotaryCordform.kt
- samples/notary-demo/src/main/kotlin/net/corda/notarydemo/RaftNotaryCordform.kt
- samples/notary-demo/src/main/kotlin/net/corda/notarydemo/SingleNotaryCordform.kt
Add warning to not use the notary demo Cordform extension pattern, as it's experimental and should be replaced later on.
> Add warning to notary demo Cordform extensions

- core/src/main/kotlin/net/corda/core/crypto/CompositeKey.kt
Remove cyclic call from CompositeKey cycle detection code. Previously when trying to report a cyclic graph in a CompositeKey, it called toString() which resulted in serialization of the graph, which of course was cyclic, so it failed.
> CORDA-249: Remove cyclic call from CompositeKey

- build.gradle
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/CordaClassResolver.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/DefaultWhitelist.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/CordaClassResolverTests.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/KryoTests.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/ListsSerializationTest.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/MapsSerializationTest.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/SetsSerializationTest.kt
We prefer to replace Kotlin's `EmptyList`, `EmptySet` and `EmptyMap` classes with standard Java classes when serialising.
Fixes #994
> Transform Kotlin's EmptyList, EmptySet and EmptyMap into Java classes

- node/src/main/kotlin/net/corda/node/services/identity/PersistentIdentityService.kt
- node/src/main/kotlin/net/corda/node/utilities/AppendOnlyPersistentMap.kt
* depends on the context the warning about inserting a duplicated key is not needed
> optional warning when adding duplicated key to AppendOnlyPersistenMap

- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializerFactory.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/carpenter/ClassCarpenter.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/carpenter/MetaCarpenter.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/DeserializeNeedingCarpentryOfEnumsTest.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/DeserializeNeedingCarpentrySimpleTypesTest.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/DeserializeNeedingCarpentryTests.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/carpenter/ClassCarpenterTest.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/carpenter/ClassCarpenterTestUtils.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/carpenter/CompositeMemberCompositeSchemaToClassCarpenterTests.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/carpenter/EnumClassTests.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/carpenter/InheritanceSchemaToClassCarpenterTests.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/carpenter/MultiMemberCompositeSchemaToClassCarpenterTests.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/carpenter/SingleMemberCompositeSchemaToClassCarpenterTests.kt
Set things up so that the carpenter must be constructed with a Corda
white list object. Right now we don't do anything with it but this will
capture all the changes in the tests to make it "just work" as is before
getting into the meat of the change
Externally this is a "no-op" as the serializer factory already takes a
whitelist as a construction parameter and the carpenter should use that
anyway
Also had the IntelliJ code reformatter touch some of the files so there are some spurious whitespace changes
> CORDA-601 - Start adding whitelist support to the carpenter

- client/jackson/src/main/kotlin/net/corda/client/jackson/JacksonSupport.kt
- client/jackson/src/test/kotlin/net/corda/client/jackson/JacksonSupportTest.kt
- samples/irs-demo/src/main/resources/net/corda/irs/simulation/trade.json
This changes JSON serialized key format to base58 encoded DER, and enforces it in the unit tests by using stably generated keys so the serialized form should always be the same.
> Enforce JSON serialized key format

- .idea/scopes/Corda_API.xml
- build.gradle
- client/rpc/src/integration-test/java/net/corda/client/rpc/CordaRPCJavaClientTest.java
- client/rpc/src/main/kotlin/net/corda/client/rpc/CordaRPCClient.kt
- client/rpc/src/main/kotlin/net/corda/client/rpc/RPCConnection.kt
- client/rpc/src/main/kotlin/net/corda/client/rpc/internal/RPCClient.kt
- core/src/main/kotlin/net/corda/core/internal/InternalUtils.kt
- core/src/main/kotlin/net/corda/core/node/NodeInfo.kt
- core/src/main/kotlin/net/corda/core/node/ServiceHub.kt
- core/src/main/kotlin/net/corda/core/node/services/TransactionVerifierService.kt
- core/src/main/kotlin/net/corda/core/node/services/VaultQueryService.kt
- core/src/main/kotlin/net/corda/core/node/services/VaultService.kt
- docs/build.gradle
* RPC docs improvements (mostly moving stuff around)
* Make RPCClient.RPCConnection a top level public interface
* Make package descriptions appear in Kotlin API docs
* Flesh out docs on ServiceHub
* Upgrade the Gradle version check plugin to make it work again
* Add an IntelliJ scope that covers the public API, useful for spotting missing kdocs.
* Suppress Any extension functions that are internal.
> A variety of small fixes

- core/src/main/kotlin/net/corda/core/concurrent/ConcurrencyUtils.kt
This message shouldn't be visible anyway, although it is. Declare it as `const` to make it `static final`.
> Declare this internal message string as "const".

- client/jfx/src/integration-test/kotlin/net/corda/client/jfx/NodeMonitorModelTest.kt
- client/jfx/src/main/kotlin/net/corda/client/jfx/model/NodeMonitorModel.kt
- client/rpc/src/integration-test/java/net/corda/client/rpc/CordaRPCJavaClientTest.java
- client/rpc/src/integration-test/kotlin/net/corda/client/rpc/CordaRPCClientTest.kt
- client/rpc/src/main/kotlin/net/corda/client/rpc/CordaRPCClient.kt
- client/rpc/src/main/kotlin/net/corda/client/rpc/internal/InternalCordaRPCClient.kt
- client/rpc/src/main/kotlin/net/corda/client/rpc/internal/KryoClientSerializationScheme.kt
- node/src/integration-test/kotlin/net/corda/services/messaging/MQSecurityTest.kt
- samples/irs-demo/src/integration-test/kotlin/net/corda/irs/IRSDemoTest.kt
- samples/trader-demo/src/integration-test/kotlin/net/corda/traderdemo/TraderDemoTest.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/driver/Driver.kt
- testing/test-utils/src/main/kotlin/net/corda/testing/SerializationTestHelpers.kt
- webserver/src/main/kotlin/net/corda/webserver/internal/NodeWebServer.kt
The removal of RPC-SSL is too late to go into v1.0 so I've just deprecated the relevant c'tor. This also tackles the problematic `initialiseSerialization` parameter which I was going to remove but won't now.
> Problematic CordaRPCClient c'tor made private

- testing/node-driver/src/integration-test/kotlin/net/corda/testing/FlowStackSnapshotTest.kt
- testing/test-utils/src/main/kotlin/net/corda/testing/FlowStackSnapshot.kt
There is an error when serialising the snapshot object (just before the checkpointing). It is due to the Kryo lack of support for the SubList class (thanks @mnesbit for spotting this).
> FlowSnapshot serialization error

- testing/node-driver/src/integration-test/kotlin/net/corda/testing/FlowStackSnapshotTest.kt
- testing/test-utils/src/main/kotlin/net/corda/testing/FlowStackSnapshot.kt
Fixes the flow snapshot feature bug related to Kryo being unable to serialize SubList instances.
It has been reviewed in https://github.com/corda/corda/pull/1671
> Fixing flow snapshot feature

- docs/source/changelog.rst
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializerFactory.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/EnumTests.kt
Have the serialiser factories apply whitelisting to enumerated types
> CORDA-653 - Serialised enums should respect whitelist

- core/src/main/kotlin/net/corda/core/contracts/Structures.kt
- core/src/main/kotlin/net/corda/core/flows/ContractUpgradeFlow.kt
- core/src/main/kotlin/net/corda/core/internal/UpgradeCommand.kt
- core/src/main/kotlin/net/corda/core/transactions/LedgerTransaction.kt
- core/src/test/kotlin/net/corda/core/contracts/DummyContractV2Tests.kt
- core/src/test/kotlin/net/corda/core/flows/ContractUpgradeFlowTest.kt
- node/src/main/kotlin/net/corda/node/services/CoreFlowHandlers.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/MockNode.kt
- testing/test-utils/src/main/kotlin/net/corda/testing/contracts/DummyContractV2.kt
During LedgerTransaction verification run the right logic based on whether
it contains the UpgradeCommand.
The current still has some issues:
- Changing contracts break encumbrance links
- We need a separate vault update type for these types of transactions
- Need to make sure expected state equality checks always work properly
Further work will be fixing the above and potentially introducing a new transaction type inline with the current notary change transaction model.
> CORDA-641: A temporary fix for contract upgrade transactions

- build.gradle
Disable the `Jar` task in the root project so that it cannot build a large, unwanted dummy CorDapp.
> Prevent the root project from building an unwanted dummy cordapp.

- docs/source/node-explorer.rst
Add a comment in the docs, warning users of:
https://r3-cev.atlassian.net/projects/CORDA/issues/CORDA-665?filter=allopenissues
> [CORDA-665] Add node warning windows users they might need to manually kill node explorer demo nodes

- client/jackson/src/main/kotlin/net/corda/client/jackson/StringToMethodCallParser.kt
- client/rpc/src/main/kotlin/net/corda/client/rpc/PermissionException.kt
- core/src/main/kotlin/net/corda/core/CordaException.kt
- core/src/main/kotlin/net/corda/core/crypto/PartialMerkleTree.kt
- core/src/main/kotlin/net/corda/core/internal/ResolveTransactionsFlow.kt
- core/src/main/kotlin/net/corda/core/node/services/IdentityService.kt
- core/src/main/kotlin/net/corda/core/serialization/MissingAttachmentsException.kt
- core/src/main/kotlin/net/corda/core/transactions/MerkleTransaction.kt
- finance/src/main/kotlin/net/corda/finance/contracts/FinanceTypes.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/custom/ThrowableSerializer.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/carpenter/Exceptions.kt
- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/main/kotlin/net/corda/node/internal/Node.kt
- node/src/main/kotlin/net/corda/node/services/api/ServiceHubInternal.kt
- node/src/main/kotlin/net/corda/node/services/network/NetworkMapService.kt
- node/src/main/kotlin/net/corda/node/services/network/PersistentNetworkMapCache.kt
- node/src/main/kotlin/net/corda/node/services/persistence/NodeAttachmentService.kt
- node/src/main/kotlin/net/corda/node/services/statemachine/StateMachineManager.kt
- node/src/main/kotlin/net/corda/node/shell/InteractiveShell.kt
- node/src/main/kotlin/net/corda/node/utilities/registration/NetworkRegistrationService.kt
Custom exceptions in corda, should either derive from an appropriate closely related java exception, or CordaException, or CordaRuntimeException. They should not inherit just from Exception, or RuntimeException.
> Consistent use of CordaException and CordaRuntimeException

- finance/src/main/kotlin/net/corda/finance/flows/TwoPartyTradeFlow.kt
- node/src/test/kotlin/net/corda/node/messaging/TwoPartyTradeFlowTests.kt
* Parameterize TwoPartyTradeFlowTests to confirm deanonymised functionality works
* Correct handling of counterparty using well known identity in `TwoPartyTradeFlow`
> CORDA-668: Correct non-anonymous two party trade flow

- docs/source/example-code/build.gradle
- node/build.gradle
- samples/network-visualiser/build.gradle
This library has one usage in ClientRPC example and:
* Uses Scala 2.10 - which is quite dated
* Has a transitive dependency on JUnit
> CORDA-650: Eliminate unnecessary dependency on "graphstream" library

- core/src/main/kotlin/net/corda/core/messaging/CordaRPCOps.kt
- core/src/main/kotlin/net/corda/core/node/services/NetworkMapCache.kt
- node/src/main/kotlin/net/corda/node/services/network/PersistentNetworkMapCache.kt
NodeInfo lookup can return more than one node for distribute services.
> Improve NetworkMapCache docs.

- core/src/main/kotlin/net/corda/core/transactions/SignedTransaction.kt
As discussed with @chrisr3 - hide companion object completely from external visibility
> Hide companion object completely from external visibility

- gradle-plugins/api-scanner/src/main/java/net/corda/plugins/GenerateApi.java
- gradle-plugins/api-scanner/src/main/java/net/corda/plugins/ScanApi.java
Just a few tweaks to the API Scanner plugin so that it behaves correctly for incremental builds.
- `@Input` -> `@InputFiles` so that Gradle checks whether the files' _content_ have changed. This should make Gradle rescan the APIs _more_ aggressively.
- Add `@CompileClasspath` so that Gradle is less sensitive to changes to these particular file inputs. This should make Gradle rescan the APIs _less_ aggressively.
Also, Gradle will automatically create the output directory for every property annotated as an `@OutputFile`, so we don't need to do this manually.
There's no hurry to re-release the Gradle plugins just yet either. I'm still looking for more tweaks, and our main use-case doesn't use incremental builds.
> Annotate Gradle task inputs and outputs correctly.

- docs/source/key-concepts-contract-constraints.rst
Fixes formatting in the Key Concepts: Contract Constraints docs.
> Fixes .rst formatting.

- build.gradle
- core/src/main/kotlin/net/corda/core/transactions/SignedTransaction.kt
- node/build.gradle
- node/src/integration-test/kotlin/net/corda/node/services/network/PersistentNetworkMapCacheTest.kt
- testing/test-utils/src/main/kotlin/net/corda/testing/Eventually.kt
Ended-up writing custom "eventually" that handles gracefully AssertionError and continues
I will be running Integration tests multiple times to ensure the test is indeed stable before merging
> CORDA-649: Second attempt to make PersistentNetworkMapCacheTest more stable

- docs/source/getting-set-up.rst
- docs/source/hello-world-template.rst
- docs/source/troubleshooting.rst
- docs/source/tutorial-cordapp.rst
Cordapp templates and example will default to the latest milestone from now on, so there's no need to tell people to check out the latest version.
> Checking out the latest milestone is no longer be required.

- core/src/main/kotlin/net/corda/core/internal/ResolveTransactionsFlow.kt
Fixes a typo in the java-docs for ResolveTransactionsFlow, which causes the java-docs links to break.
> Fixes java-docs breaking typo.

- docs/source/getting-set-up.rst
- docs/source/hello-world-template.rst
- docs/source/troubleshooting.rst
- docs/source/tutorial-cordapp.rst
Cordapp templates and example will point to the latest milestone by default, so there's no need to tell people to check out the latest version.
> Checking out the latest milestone will no longer be required.

- .ci/check-api-changes.sh
Don't fail the API check for lines like:
```diff
--- .ci/api-current.txt	2017-10-03 10:51:43.794307705 +0100
```
> Fail the API check for lines starting with a single '-'.

- .ci/check-api-changes.sh
Modify the `check-api-changes` script to derive the project directory structure relative to its own location. This means that users don't need to run the script from the `.ci` directory.
> Derive working directory for API check from location of script.

- core/src/test/kotlin/net/corda/core/crypto/CompositeKeyTests.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/SerializationScheme.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/AttachmentsClassLoaderTests.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/ListsSerializationTest.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/MapsSerializationTest.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/SetsSerializationTest.kt
- testing/test-utils/src/main/kotlin/net/corda/testing/CoreTestUtils.kt
Use special instruction to exclude newly introduced tests from running in AMQP mode.
> CORDA-540: AMQP specific fixes in "node-api" project

- constants.properties
- docs/source/changelog.rst
- gradle-plugins/cordform-common/src/main/java/net/corda/cordform/CordformNode.java
- gradle-plugins/cordformation/src/main/groovy/net/corda/plugins/Cordform.groovy
- node/src/main/kotlin/net/corda/node/ArgsParser.kt
- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/main/kotlin/net/corda/node/internal/Node.kt
- node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt
- node/src/main/kotlin/net/corda/node/services/network/NodeInfoSerializer.kt
- node/src/main/kotlin/net/corda/node/services/network/PersistentNetworkMapCache.kt
- node/src/test/kotlin/net/corda/node/ArgsParserTest.kt
- node/src/test/kotlin/net/corda/node/services/network/NodeInfoSerializerTest.kt
- samples/trader-demo/build.gradle
Initial PR for https://r3-cev.atlassian.net/projects/CORDA/issues/CORDA-442
Allow for cordformation not to specify which node is network map.
When that happens Cordformation will start each node and make it serialize its NodeInfo to disk.
This make 'depolyNodes' slower. On my machine for the traderDemo it's ~25s
PersistentNetworkMapCache will load files from disk at startup.
Additionally nodeinfos are loaded in the networkMapCache only if they're newer than the currently known version.
> [CORDA-442] Make cordformation serialize NodeInfos to disk during deployment.

- core/src/main/kotlin/net/corda/core/crypto/Crypto.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/DefaultKryoCustomizer.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/Kryo.kt
Where `toSupportedPublicKey` or `toSupportedPrivateKey` is called with a key type we support, return it as-is rather than serializing then deserializing.
> Don't repackage well known key types

- confidential-identities/src/main/kotlin/net/corda/confidential/IdentitySyncFlow.kt
- confidential-identities/src/test/kotlin/net/corda/confidential/IdentitySyncFlowTests.kt
Change IdentitySyncFlow to only offer confidential identities matching the identity the flow is run as. This avoids risks of nodes being convinced to include a state with a confidential identity in it, by a remote node, then feeding the well known identity to the node during identity sync.
> CORDA-657: Change IdentitySyncFlow to only offer own identities

- core/src/main/kotlin/net/corda/core/transactions/LedgerTransaction.kt
- verifier/src/integration-test/kotlin/net/corda/verifier/VerifierTests.kt
The `LedgerTransaction.verify()` function does not have access to Java Reflection, so instantiate the contract classes when creating the `LedgerTransaction` instance instead.
> Instantiate Contract classes outside of LedgerTransaction.verify()

- node/src/integration-test/kotlin/net/corda/node/services/network/NodeInfoWatcherTest.kt
- node/src/test/kotlin/net/corda/node/services/network/NodeInfoWatcherTest.kt
See
https://ci-master.corda.r3cev.com/viewLog.html?buildId=26873&tab=buildResultsDiv&buildTypeId=Corda_CordaBuild#
for a flake.
The test exercises the filesystem WatchService so we need to wait for the filesystem to report file changes.
> Deflake NodeInfoWatcherTest

- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/AllButBlacklisted.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/Kryo.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/UseCaseAwareness.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/KryoTests.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/PrivateKeySerializationTest.kt
At the moment, even in Kryo mode, we allow unconstrained serialization of Private Keys.
This could be dangerous as the the key may leak to the external party.
> CORDA-540: Add verification to ensure that private keys can only be serialized with specific contexts

- node/src/main/kotlin/net/corda/node/services/network/PersistentNetworkMapCache.kt
val publicKey in unused.
I've removed it.
It was causing a warning in building corda.
> removed unused variable in PersistentNetworkMapCache

- testing/node-driver/src/main/kotlin/net/corda/testing/driver/Driver.kt
Throws helpful error message when driver is instantiated by a function outside a package.
> Better error for driver instantiated outside package.

- core/src/main/kotlin/net/corda/core/cordapp/Cordapp.kt
- core/src/main/kotlin/net/corda/core/flows/FlowInitiator.kt
- core/src/main/kotlin/net/corda/core/flows/StartableByService.kt
- core/src/main/kotlin/net/corda/core/internal/cordapp/CordappImpl.kt
- core/src/main/kotlin/net/corda/core/node/AppServiceHub.kt
- core/src/main/kotlin/net/corda/core/node/services/CordaService.kt
- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/main/kotlin/net/corda/node/internal/cordapp/CordappLoader.kt
- node/src/main/kotlin/net/corda/node/shell/FlowWatchPrintingSubscriber.kt
- node/src/test/kotlin/net/corda/node/internal/CordaServiceTest.kt
- node/src/test/kotlin/net/corda/node/internal/cordapp/CordappLoaderTest.kt
- testing/test-utils/src/main/kotlin/net/corda/testing/node/MockCordappProvider.kt
This adds the AppServiceHub which allows CordaService classes to start flows marked with StartableByService in a many analogous to RPC flow support.
> Start Flows from services

- docs/source/hello-world-running.rst
The Java version of the instructions for running the Hello, World tutorial was outdated, and is now fixed.
> Fix outdated shell command.

- core/src/main/kotlin/net/corda/core/node/services/IdentityService.kt
- core/src/main/kotlin/net/corda/core/node/services/NetworkMapCache.kt
- node/src/main/kotlin/net/corda/node/services/network/NetworkMapService.kt
- node/src/main/kotlin/net/corda/node/services/network/PersistentNetworkMapCache.kt
- node/src/test/kotlin/net/corda/node/services/network/NetworkMapCacheTest.kt
Add functions to:
* Return PartyAndCertificate rather than just Party
* Return all NodeInfo entries for a name (rather than just by key)
* Return all Party/PartyAndCertificate entries for name, based on the above function
> Extend NetworkMapCache API

- client/rpc/src/integration-test/kotlin/net/corda/client/rpc/BlacklistKotlinClosureTest.kt
- core/src/main/kotlin/net/corda/core/serialization/CordaSerializable.kt
- core/src/test/kotlin/net/corda/core/utilities/KotlinUtilsTest.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/CordaClassResolver.kt
- node/src/main/kotlin/net/corda/node/services/statemachine/FlowStateMachineImpl.kt
This local function is indistinguishable (at a JVM level) from the potentially problematic lambda parameter on the example flow in [CORDA-644](https://r3-cev.atlassian.net/browse/CORDA-644). I am removing it now to prevent this code from breaking when we switch from Kryo to AMQP.
> CORDA-644: Only serialise Kotlin lambdas when checkpointing.

- node/src/integration-test/kotlin/net/corda/node/services/network/NodeInfoWatcherTest.kt
- node/src/main/kotlin/net/corda/node/services/network/NodeInfoWatcher.kt
Change the implementation not to rely on the Java WatchService and instead just list the whole directory contents every time.
> Deflake node infoWatcherTest

- node/src/integration-test/kotlin/net/corda/node/services/network/NodeInfoWatcherTest.kt
- node/src/main/kotlin/net/corda/node/services/network/NodeInfoWatcher.kt
Handle non-standard file systems such as JimFs, in NodeInfoWatcher. Instead of using toFile() to convert a Path to a File, open the Path for writing to directly.
> CORDA-654: Handle non-standard file systems in NodeInfoWatcher

- confidential-identities/src/main/kotlin/net/corda/confidential/SwapIdentitiesFlow.kt
- confidential-identities/src/main/kotlin/net/corda/confidential/SwapIdentitiesHandler.kt
- confidential-identities/src/test/kotlin/net/corda/confidential/SwapIdentitiesFlowTests.kt
- core/src/main/kotlin/net/corda/core/crypto/DigitalSignature.kt
- core/src/main/kotlin/net/corda/core/serialization/SerializationAPI.kt
Add signature exchange to transaction key flow to verify that the counterparty actually owns the key they claim to.
> Add signature exchange to transaction key flow

- confidential-identities/src/main/kotlin/net/corda/confidential/IdentitySyncFlow.kt
- confidential-identities/src/test/kotlin/net/corda/confidential/IdentitySyncFlowTests.kt
Change IdentitySyncFlow to only offer confidential identities matching the identity the flow is run as. This avoids risks of nodes being convinced to include a state with a confidential identity in it, by a remote node, then feeding the well known identity to the node during identity sync.
> Change IdentitySyncFlow to only offer own identities

- .ci/api-current.txt
- .ci/check-api-changes.sh
We can also break the API by adding new abstract methods to classes or interfaces, so check for that too.
> Scan API for addition of new abstract methods.

- docs/source/example-code/src/main/kotlin/net/corda/docs/tutorial/testdsl/TutorialTestDSL.kt
- finance/src/main/kotlin/net/corda/finance/contracts/asset/Cash.kt
- finance/src/main/kotlin/net/corda/finance/contracts/asset/CommodityContract.kt
- finance/src/test/kotlin/net/corda/finance/contracts/CommercialPaperTests.kt
- finance/src/test/kotlin/net/corda/finance/contracts/asset/CashTests.kt
- finance/src/test/kotlin/net/corda/finance/contracts/asset/ObligationTests.kt
- node/src/test/kotlin/net/corda/node/messaging/TwoPartyTradeFlowTests.kt
- samples/irs-demo/src/test/kotlin/net/corda/irs/api/NodeInterestRatesTest.kt
See https://github.com/corda/corda/issues/1730
Remove all the Kotlin functions with spaces in them since the Android doesn't support them.
> [GH 1730] Remove functions with spaces in their name

- node/src/integration-test/kotlin/net/corda/node/services/AttachmentLoadingTests.kt
By allowing extra time for nodes' cluster to become stable.
Presently the test `AttachmentLoadingTests.test that attachments retrieved over the network are not used for code`
is still unstable, stats can be found here:
https://ci-master.corda.r3cev.com/project.html?projectId=Corda_Build_PullRequests&buildTypeId=&tab=testDetails&testNameId=915514848694478200&order=TEST_STATUS_DESC&branch_Corda_Build_PullRequests=__all_branches__&itemsCount=50
> Make AttachmentLoadingTests more stable

- core/src/main/kotlin/net/corda/core/flows/AbstractStateReplacementFlow.kt
- core/src/main/kotlin/net/corda/core/flows/NotaryFlow.kt
- core/src/main/kotlin/net/corda/core/node/ServiceHub.kt
- core/src/main/kotlin/net/corda/core/transactions/SignedTransaction.kt
- core/src/main/kotlin/net/corda/core/transactions/TransactionWithSignatures.kt
- docs/source/example-code/src/main/kotlin/net/corda/docs/CustomNotaryTutorial.kt
- node/src/main/kotlin/net/corda/node/internal/StartedNode.kt
- node/src/main/kotlin/net/corda/node/services/transactions/ValidatingNotaryFlow.kt
Move special case handling of notary transactions into `SignedTransaction` so it's implemented once and reusable, instead of scattered through flows.
> CORDA-641: Move special case handling of notary transactions into `SignedTransaction`

- finance/src/main/kotlin/net/corda/finance/contracts/asset/OnLedgerAsset.kt
- finance/src/test/kotlin/net/corda/finance/contracts/asset/CashTests.kt
generateExit() previously required all states to have a single owner, which was used as the change output's owner. This deprecates that function but enables it to work as expected using `firstOrNull()` instead of `singleOrNull()`, and adds new functions which take in the change output's owner.
> Add confidential identity support to cash exit logic

- constants.properties
- docs/source/changelog.rst
- gradle-plugins/cordform-common/src/main/java/net/corda/cordform/CordformNode.java
- gradle-plugins/cordformation/src/main/groovy/net/corda/plugins/Node.groovy
Appending properties from an optional file when deploying node is useful when e.g. testing against different databases.
> deployNodes Gradle task appends properties from an optional file to node.conf

- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/CordaClassResolver.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/CordaClassResolverTests.kt
Prevent `isAbstract()` from accidentally whitelisting types which have not been annotated as `@CordaSerializable`.
> CORDA-702: Don't whitelist certain non-annotated types

- node/src/integration-test/kotlin/net/corda/node/services/network/NodeInfoWatcherTest.kt
- node/src/main/kotlin/net/corda/node/services/network/NodeInfoWatcher.kt
Let NodeInfoWatcher create the directory it wants to poll at startup.
Also log failure in creating the directory, but don't log anything if it can be found at poll time.
> Create nodeInfoDirectory on NodeInfoWatcher init and don't log when it does not exist

- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/ListsSerializationTest.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/MapsSerializationTest.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/SetsSerializationTest.kt
- node/src/main/kotlin/net/corda/node/services/statemachine/FlowStateMachineImpl.kt
- node/src/main/kotlin/net/corda/node/services/statemachine/SessionMessage.kt
- node/src/main/kotlin/net/corda/node/services/statemachine/StateMachineManager.kt
- node/src/test/kotlin/net/corda/node/services/statemachine/FlowFrameworkTests.kt
The current SessionMessage deserialization is not within an exception catcher and also the payload is directly deserialized, which prevents any opportunity to apply the checking logic if the class is not available to the node. This puts some basic checks in, although the full fix requires the safe AMQP serializers, rather than Kryo.
> Protect the serialization/deserialization code of SessionMessage data

- confidential-identities/src/test/kotlin/net/corda/confidential/SwapIdentitiesFlowTests.kt
- core/src/main/kotlin/net/corda/core/node/NodeInfo.kt
- core/src/test/kotlin/net/corda/core/flows/AttachmentTests.kt
- core/src/test/kotlin/net/corda/core/flows/CollectSignaturesFlowTests.kt
- core/src/test/kotlin/net/corda/core/flows/FinalityFlowTests.kt
- docs/source/example-code/src/test/kotlin/net/corda/docs/WorkflowTransactionBuildTutorialTest.kt
- node/src/test/kotlin/net/corda/node/services/NotaryChangeTests.kt
- node/src/test/kotlin/net/corda/node/services/transactions/ValidatingNotaryServiceTests.kt
- samples/bank-of-corda-demo/src/integration-test/kotlin/net/corda/bank/BankOfCordaRPCClientTest.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/MockNode.kt
- testing/test-utils/src/main/kotlin/net/corda/testing/TestConstants.kt
- verifier/src/integration-test/kotlin/net/corda/verifier/VerifierTests.kt
Replace special case API usage in unit tests with approaches that more closely model actual production scenarios. Specifically:
* Stop pulling identities from running nodes' own info, and instead extract them via the network map, which is how lookup should behave in production.
* Stop accessing `StartedNode` directly, and instead work on the `ServiceHubInternal`; while in many cases code is limited to `ServiceHub`, it's at least closer to reality.
> CORDA-654: Migrate test APIs to match identity changes

- .ci/api-current.txt
- core/src/main/kotlin/net/corda/core/crypto/SecureHash.kt
- core/src/main/kotlin/net/corda/core/transactions/TransactionWithSignatures.kt
- core/src/main/kotlin/net/corda/core/utilities/ByteArrays.kt
- core/src/test/kotlin/net/corda/core/serialization/TransactionSerializationTests.kt
- docs/source/changelog.rst
Force `OpaqueBytes.bytes` to return a clone of its contents, and then make this field `final`. This effectively makes the contents immutable.
> Ensure that the contents of OpaqueBytes cannot be modified.

- finance/src/main/kotlin/net/corda/finance/contracts/asset/cash/selection/CashSelectionH2Impl.kt
- finance/src/test/kotlin/net/corda/finance/contracts/asset/CashTests.kt
Updated H2 coin selection code to use Prepared Statement to protect against SQL Injection attacks, as per http://www.h2database.com/html/advanced.html#sql_injection
> H2 coin selection uses Prepared Statement to protect against SQL injection

- .idea/compiler.xml
- testing/node-driver/src/main/kotlin/net/corda/testing/driver/Driver.kt
- verifier/src/integration-test/kotlin/net/corda/verifier/VerifierTests.kt
The test `net.corda.verifier.VerifierTests#single verifier works with a node` is quite flaky in `master` at the moment.
Main point for improvement: Alice node will always be faster to locate Alice by name than NotaryNode. Especially given that it may take some time for Alice node to get reflected on the Notary's NetworkMap.
Also additional logging which might be helpful during debug and IntelliJ changed project structure reflection.
> Attempting to make VerifierTests more stable

- tools/demobench/build.gradle
- tools/demobench/src/main/kotlin/net/corda/demobench/model/NodeController.kt
- tools/demobench/src/main/kotlin/net/corda/demobench/model/NodeInfoFilesCopier.kt
- tools/demobench/src/test/kotlin/net/corda/demobench/model/NodeInfoFilesCopierTest.kt
NodeBench now copies the nodeInfo files of running nodes to each other node.
In detail, each node writes its own nodeInfo-<HASH> to its base folder and polls the filesystem for new ones in <nodepath>/additional-node-infos
Demobench now monitors the nodes path, waiting for them to write their own nodeInfo and then copies each nodeInfo to all other running nodes' additional-node-info directories.
(nodes polling the filesystem is happening here https://github.com/corda/corda/pull/1623, however the logic in this PR is independent of that)
Note that currently DemoBench makes the first node to start the 'networkmapnode' this PR is in preparation for when the 'networkmapnode' will be dismantled
> [CORDA-442] DemoBench copies around the NodeInfos for running nodes.

- finance/src/test/kotlin/net/corda/finance/contracts/asset/CashSelectionH2Test.kt
Although test assertions were passing, the code was not executing correctly due to missing declaration of CashSchema:
```
[ERROR] 15:14:55,725 [Mock node 2 thread] (AbstractCashSelection.kt:158) selection.AbstractCashSelection.attemptSpend - Failed retrieving unconsumed states for: amount [100.00 USD], onlyFromIssuerParties [[]], notary [null], lockId [45310aee-1904-4c2f-8148-981791a7abdb]
org.h2.jdbc.JdbcSQLException: Table "CONTRACT_CASH_STATES" not found; SQL statement:
```
> Fix CashSelectionH2Test unit test.

- core/src/main/kotlin/net/corda/core/contracts/ComponentGroupEnum.kt
- core/src/main/kotlin/net/corda/core/crypto/PartialMerkleTree.kt
- core/src/main/kotlin/net/corda/core/transactions/MerkleTransaction.kt
- core/src/main/kotlin/net/corda/core/transactions/WireTransaction.kt
- core/src/test/kotlin/net/corda/core/contracts/CompatibleTransactionTests.kt
- core/src/test/kotlin/net/corda/core/crypto/PartialMerkleTreeTest.kt
- docs/source/changelog.rst
- samples/irs-demo/src/main/kotlin/net/corda/irs/api/NodeInterestRates.kt
A new functionality is implemented to enable command visibility for Oracles without sacrificing privacy.
Previously, one could achieve the above functionality by requiring full access to every command in the original transaction.
In contrast, this approach suggests we only send the list of `signers` per `command`, but not `CommandData` for unrelated `Command`s.
The algorithm works as follows:
a) a new `SIGNERS_GROUP` with ordinal 6 is added.
b) Unlike other components, signers is NOT a property in `TraversableTransaction`, but of course it is part of the `ComponentGroup` `OpaqueBytes`.
c) Due to the above, we ensure that filtering over `signers` is not possible (eg. someone by mistake sends some commands but filters out the signers)
d) If even one `Command` is included in the …
> [CORDA-694] Commands visibility for Oracles (without sacrificing privacy)

- .ci/api-current.txt
- core/src/main/kotlin/net/corda/core/crypto/SecureHash.kt
- core/src/main/kotlin/net/corda/core/utilities/ByteArrays.kt
- core/src/test/kotlin/net/corda/core/serialization/TransactionSerializationTests.kt
- docs/source/changelog.rst
* Ensure that contents of OpaqueBytes cannot be modified.
* Update documentation and restore the signature verification check.
* Update the API definition.
* KDoc fixes.
* Update the changelog for v1.1.
> Ensure that the contents of OpaqueBytes cannot be modified. (#1871)

- .ci/api-current.txt
- .ci/check-api-changes.sh
- client/rpc/src/main/kotlin/net/corda/client/rpc/RPCConnection.kt
- constants.properties
- core/src/main/kotlin/net/corda/core/DoNotImplement.kt
- core/src/main/kotlin/net/corda/core/cordapp/Cordapp.kt
- core/src/main/kotlin/net/corda/core/cordapp/CordappProvider.kt
- core/src/main/kotlin/net/corda/core/flows/FlowLogicRef.kt
- core/src/main/kotlin/net/corda/core/flows/FlowSession.kt
- core/src/main/kotlin/net/corda/core/identity/AbstractParty.kt
- core/src/main/kotlin/net/corda/core/messaging/CordaRPCOps.kt
- core/src/main/kotlin/net/corda/core/messaging/FlowHandle.kt
- core/src/main/kotlin/net/corda/core/messaging/RPCOps.kt
- core/src/main/kotlin/net/corda/core/node/ServiceHub.kt
- core/src/main/kotlin/net/corda/core/node/services/AttachmentStorage.kt
- core/src/main/kotlin/net/corda/core/node/services/ContractUpgradeService.kt
- core/src/main/kotlin/net/corda/core/node/services/IdentityService.kt
- core/src/main/kotlin/net/corda/core/node/services/KeyManagementService.kt
- core/src/main/kotlin/net/corda/core/node/services/NetworkMapCache.kt
- core/src/main/kotlin/net/corda/core/node/services/TransactionStorage.kt
- core/src/main/kotlin/net/corda/core/node/services/TransactionVerifierService.kt
- core/src/main/kotlin/net/corda/core/node/services/VaultService.kt
- core/src/main/kotlin/net/corda/core/node/services/vault/QueryCriteria.kt
- core/src/main/kotlin/net/corda/core/node/services/vault/QueryCriteriaUtils.kt
- core/src/main/kotlin/net/corda/core/transactions/BaseTransaction.kt
- core/src/main/kotlin/net/corda/core/transactions/TransactionWithSignatures.kt
- docs/source/corda-api.rst
- gradle-plugins/api-scanner/src/main/java/net/corda/plugins/ScanApi.java
- node/src/main/kotlin/net/corda/node/services/statemachine/FlowLogicRefFactoryImpl.kt
Some public APIs are not intended to be extended. Annotate these as `@DoNotImplement` and enhance the API Stability check to ignore such classes when warning about new abstract API methods.
> CORDA-704: Implement `@DoNotImplement` annotation

- samples/bank-of-corda-demo/src/main/kotlin/net/corda/bank/BankOfCordaDriver.kt
In the previous version when running with `--role ISSUER` the application failed to start.
The reason was that in spite of `quantity` and `currency` were optional,
un-necessary `requestParams` been constructed regardless.
> Fix-up: Bank Of Corda sample

- .ci/dependency-checker/suppressedLibraries.xml
- build.gradle
Added the OWASP dependency check plugin to the gradle build script. It comes with several configurable tasks, 3 of which are the most important:
1. `gradle dependencyCheckAnalyze` will run for all projects and create a report containing detailed descriptions of known library vulnerabilities. The report can be found in several formats(html, xml, json, csv) in /corda/build/reports/
2. `gradle dependencyCheckUpdate` will update the local h2 database with the latest information in the National Vulnerability Database
3. `gradle :dependencyCheckPurge` will delete the h2 database. This task needs to be run only for the root project or it will fail when it's run for the subprojects(database already deleted)
The h2 database is create by default in the .gradle directory and takes up about 300MB. A …
> CORDA-351: added dependency check plugin to gradle build script

- docs/source/api-identity.rst
- finance/src/main/kotlin/net/corda/finance/flows/TwoPartyTradeFlow.kt
- Adds information about other side of `IdentitySyncFlow`
- Style changes
> Adds receiver side of sync flow to ID docs. Cleanup.

- core/src/test/kotlin/net/corda/core/utilities/KotlinUtilsTest.kt
Also correct lambda typos (from lamba)
> CORDA-435 - Ensure Kryo only tests use Kryo serialisation context

- node/src/test/kotlin/net/corda/node/services/events/NodeSchedulerServiceTest.kt
They won't be reported as properties by the introspector and thus we
will fail to find a constructor for them. This makes sense as we will be
unable to serialise an object whose members we cannot read
> CORDA-435 - AMQP serialisation cannot work with private vals

- node/src/test/kotlin/net/corda/node/services/vault/VaultSoftLockManagerTest.kt
AMQP has different serialization rules than Kryo surrounding the way we
introspect objects to work out how to construct them
> CORDA-435 - AMQP enablement fixes

- core/src/main/kotlin/net/corda/core/schemas/NodeInfoSchema.kt
- node/src/main/kotlin/net/corda/node/services/identity/PersistentIdentityService.kt
- node/src/main/kotlin/net/corda/node/services/keys/PersistentKeyManagementService.kt
- node/src/main/kotlin/net/corda/node/services/network/PersistentNetworkMapService.kt
- node/src/main/kotlin/net/corda/node/utilities/CordaPersistence.kt
Retrofit changes from https://github.com/corda/enterprise/pull/61
> Eliminate use of PublicKey (as string or binary) as primary key in database

- docs/source/corda-configuration-file.rst
- node/capsule/build.gradle
- node/src/main/java/CordaCaplet.java
- testing/smoke-test-utils/src/main/kotlin/net/corda/smoketesting/NodeProcess.kt
1. Ability to configure system properties for switching A / B testing and other runtime configurable features.
2. Include additional JARs for e.g. JDBC drivers.
3. JVM arguments for tweaking heap size, profiling, debug arguments etc.
It also requires us to respect command line args understood by the node for specifying the configuration file for completeness.  This requires the caplet to be able to parse the config file and see reference.conf.
> CORDA-736 Add some new features to corda.jar via node.conf for testing

- .ci/api-current.txt
- core/src/main/kotlin/net/corda/core/schemas/NodeInfoSchema.kt
- core/src/main/kotlin/net/corda/core/utilities/EncodingUtils.kt
- finance/src/main/kotlin/net/corda/finance/contracts/CommercialPaper.kt
- finance/src/main/kotlin/net/corda/finance/contracts/asset/Cash.kt
- finance/src/main/kotlin/net/corda/finance/contracts/asset/cash/selection/CashSelectionH2Impl.kt
- finance/src/main/kotlin/net/corda/finance/schemas/CashSchemaV1.kt
- finance/src/main/kotlin/net/corda/finance/schemas/CommercialPaperSchemaV1.kt
- finance/src/test/kotlin/net/corda/finance/contracts/asset/DummyFungibleContract.kt
- finance/src/test/kotlin/net/corda/finance/schemas/SampleCashSchemaV1.kt
- finance/src/test/kotlin/net/corda/finance/schemas/SampleCommercialPaperSchemaV1.kt
- finance/src/test/kotlin/net/corda/finance/schemas/SampleCommercialPaperSchemaV2.kt
- node/src/main/kotlin/net/corda/node/services/identity/PersistentIdentityService.kt
- node/src/main/kotlin/net/corda/node/services/keys/PersistentKeyManagementService.kt
- node/src/main/kotlin/net/corda/node/services/network/PersistentNetworkMapCache.kt
- node/src/main/kotlin/net/corda/node/services/network/PersistentNetworkMapService.kt
- node/src/main/kotlin/net/corda/node/services/transactions/BFTNonValidatingNotaryService.kt
- node/src/main/kotlin/net/corda/node/services/transactions/PersistentUniquenessProvider.kt
- node/src/main/kotlin/net/corda/node/utilities/CordaPersistence.kt
- node/src/test/kotlin/net/corda/node/services/persistence/HibernateConfigurationTest.kt
- node/src/test/kotlin/net/corda/node/services/vault/VaultQueryTests.kt
Retrofit changes from Enterprise PR [Standardisation of Public Keys in Schema entities](https://github.com/corda/enterprise/pull/68)
Updated Stability API checking golden source (api-current.txt) to reflect change in schema attribute - which is not yet considered API stable.
> Standardisation of Public Keys in Schema entities. (#68)

- client/jfx/src/main/kotlin/net/corda/client/jfx/model/ExchangeRateModel.kt
- client/jfx/src/test/kotlin/net/corda/client/jfx/model/ExchangeRateModelTest.kt
It is kind of sad to see 1 GBP to be equal to 1 USD and also it looks misleading in the blotter.
> Perform sensible currency conversion

- .idea/compiler.xml
- core/src/main/kotlin/net/corda/core/flows/InitiatedBy.kt
- core/src/main/kotlin/net/corda/core/flows/ReceiveTransactionFlow.kt
- core/src/main/kotlin/net/corda/core/internal/ResolveTransactionsFlow.kt
- core/src/main/kotlin/net/corda/core/node/ServiceHub.kt
- docs/source/changelog.rst
- docs/source/release-notes.rst
- docs/source/tutorial-observer-nodes.rst
- docs/source/tutorials-index.rst
- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/main/kotlin/net/corda/node/internal/cordapp/CordappLoader.kt
- node/src/main/kotlin/net/corda/node/services/CoreFlowHandlers.kt
- node/src/main/kotlin/net/corda/node/services/api/ServiceHubInternal.kt
- node/src/main/kotlin/net/corda/node/services/api/VaultServiceInternal.kt
- node/src/main/kotlin/net/corda/node/services/statemachine/FlowSessionImpl.kt
- node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt
- node/src/test/kotlin/net/corda/node/services/events/NodeSchedulerServiceTest.kt
- node/src/test/kotlin/net/corda/node/services/persistence/DBTransactionStorageTests.kt
- node/src/test/kotlin/net/corda/node/services/persistence/HibernateConfigurationTest.kt
- node/src/test/kotlin/net/corda/node/services/vault/NodeVaultServiceTest.kt
- samples/irs-demo/cordapp/src/main/kotlin/net/corda/irs/flows/AutoOfferFlow.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/MockServices.kt
This PR adds support for observer nodes in a different way to PR #1918 - the primary differences are:
* No tagging of states
* No new demo, just a small extension to the IRS demo
* There is no distinction in vault queries or observables between observed or not-observed states.
* Whether states should be "observed" or not is passed through the API from the flows, rather than inferred by the vault based on the state contents.
The latter approach avoids verb/noun type conceptual mixup and solves the probably common case where two sides to a transaction wish to report the same transaction to different regulators (which would otherwise require both to be listed in the observers and involve both receiving duplicated reports). In the case where the regulatory reporting process is more involved …
> Add support for observer nodes (alternative approach)

- node/src/test/kotlin/net/corda/node/services/statemachine/FlowFrameworkTests.kt
Remove a test in MockNetwork checking for things happening before the network map node registration.
There isn't any networkmap node registration in MockNetwork anymore
> remove outdated test

- node/src/integration-test/kotlin/net/corda/node/NodePerformanceTests.kt
- node/src/main/kotlin/net/corda/node/services/config/NodeConfiguration.kt
- node/src/main/kotlin/net/corda/node/services/statemachine/StateMachineManagerImpl.kt
- node/src/main/kotlin/net/corda/node/utilities/NamedThreadFactory.kt
- node/src/test/kotlin/net/corda/node/services/config/FullNodeConfigurationTest.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/NodeTestUtils.kt
- Give  the checkpoint checker thread a meaningful name so it can be identified while debugging or profiling
- Add devModeOptions as a bag of options that can be set for dev mode and add an options to turn the checkpoint checker off in dev mode (e.g. for profiling)
> checkpoint checker thread

- testing/node-driver/src/main/kotlin/net/corda/testing/driver/Driver.kt
Please see Jira for background info.
The change should help all the Windows developers.
Closer examination shows that in the command line we include the classpath of size ~20,000 characters twice.
Once with `-cp` option - which is fine and second time with `-Djava.class.path=` - the latter is completely unnecessary and can be eliminated shortening the command length dramatically to around: 24,000 characters which should give us some leg room for further expanding the classpath.
> CORDA-751: Eliminate duplicating entry for classpath when OutOfProcess node is started

- gradle-plugins/api-scanner/src/main/java/net/corda/plugins/ApiScanner.java
Trivial fix that still applies to Gradle 4.1.
Gradle will set the dependency between the `jar` and `scanApi` tasks automatically because the input source is a `ConfigurableFileCollection`.
There is no functional change, so this can wait for the next plugins release.
> Allow Gradle to set dependency between Jar and ScanApi tasks.

- build.gradle
- constants.properties
- docs/source/deploying-a-node.rst
- gradle-plugins/cordform-common/src/main/java/net/corda/cordform/CordformNode.java
- gradle-plugins/cordformation/src/main/kotlin/net/corda/plugins/Node.kt
Why: A part of API stability for cordformation and a common request.
> Cordformation now allows addresses to be used for non-database addresses.

- client/rpc/src/main/kotlin/net/corda/client/rpc/CordaRPCClient.kt
- client/rpc/src/main/kotlin/net/corda/client/rpc/internal/KryoClientSerializationScheme.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/ClientContexts.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/CordaClassResolver.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/SerializationScheme.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/ServerContexts.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/AMQPSerializationScheme.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/kryo/CordaClosureSerializer.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/kryo/DefaultKryoCustomizer.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/kryo/Kryo.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/kryo/KryoSerializationScheme.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/kryo/SerializeAsTokenSerializer.kt
- node-api/src/test/java/net/corda/nodeapi/internal/serialization/ForbiddenLambdaSerializationTests.java
- node-api/src/test/java/net/corda/nodeapi/internal/serialization/LambdaCheckpointSerializationTest.java
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/CordaClassResolverTests.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/KryoTests.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/ListsSerializationTest.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/MapsSerializationTest.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/SerializationTokenTest.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/SetsSerializationTest.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializationOutputTests.kt
- node/src/main/kotlin/net/corda/node/internal/Node.kt
- node/src/main/kotlin/net/corda/node/serialization/KryoServerSerializationScheme.kt
- node/src/test/kotlin/net/corda/node/utilities/X509UtilitiesTest.kt
- testing/test-utils/src/main/kotlin/net/corda/testing/CoreTestUtils.kt
- testing/test-utils/src/main/kotlin/net/corda/testing/SerializationTestHelpers.kt
- verifier/src/main/kotlin/net/corda/verifier/Verifier.kt
Prior to enabling AMQP RPC move Kryo code to it's own submodule just like AMQP
> Refactor Kryo into sub module just like AMQP

- config/dev/generalnodeb.conf
- docs/source/azure-vm.rst
- docs/source/demobench.rst
- docs/source/example-code/src/main/resources/example-out-of-process-verifier-node.conf
- docs/source/messaging.rst
- docs/source/node-services.rst
- docs/source/setting-up-a-corda-network.rst
- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/main/kotlin/net/corda/node/internal/Node.kt
- node/src/main/kotlin/net/corda/node/services/api/ServiceHubInternal.kt
- node/src/main/kotlin/net/corda/node/services/messaging/ArtemisMessagingServer.kt
- node/src/main/kotlin/net/corda/node/services/messaging/NodeMessagingClient.kt
- node/src/main/kotlin/net/corda/node/services/network/NetworkMapService.kt
- node/src/main/kotlin/net/corda/node/services/network/PersistentNetworkMapService.kt
- node/src/test/kotlin/net/corda/node/services/messaging/ArtemisMessagingTests.kt
- samples/network-visualiser/src/main/kotlin/net/corda/netmap/NetworkMapVisualiser.kt
- samples/trader-demo/README.md
- testing/node-driver/src/main/kotlin/net/corda/testing/driver/Driver.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/MockNode.kt
- testing/test-utils/src/main/kotlin/net/corda/testing/TestConstants.kt
Remove most remaining mentions of the network map node.
Update all the docs, to remove/update references to the network map
Also the NodeMessagingClient won't depend on the nodeReadyFuture anymore.
NodeMessagingClient won't have any special treatment for network map messages, as they don't exist anymore
> [CORDA-446] Clean up other mentions of network map node and logic

- tools/demobench/src/main/kotlin/net/corda/demobench/model/InstallFactory.kt
- tools/demobench/src/main/kotlin/net/corda/demobench/model/NodeConfig.kt
- tools/demobench/src/main/kotlin/net/corda/demobench/model/NodeController.kt
- tools/demobench/src/main/kotlin/net/corda/demobench/views/NodeTabView.kt
- tools/demobench/src/test/kotlin/net/corda/demobench/model/NodeConfigTest.kt
- tools/demobench/src/test/kotlin/net/corda/demobench/model/NodeControllerTest.kt
Remove mentions of networkmap node from Demobench.
Note that Demobench used to check for a network map to decide whether one could launch a Notary or a non-notary node.
Now it checks for there being a running notary.
> [CORDA-446] Remove mentions of networkmap node in DemoBench

- client/jfx/src/main/kotlin/net/corda/client/jfx/model/ContractStateModel.kt
Or else NodeExplorer will not start due to exception, see below.
It looks like during the `map()` call resulting type cannot be inferred correctly.
This is likely to be caused by: #1667
```
java.lang.ClassCastException: net.corda.core.contracts.StateAndRef cannot be cast to java.lang.Void
at net.corda.client.jfx.model.ContractStateModel$Companion.filterCashStateAndRefs(ContractStateModel.kt:43)
at net.corda.client.jfx.model.ContractStateModel$Companion.access$filterCashStateAndRefs(ContractStateModel.kt:38)
at net.corda.client.jfx.model.ContractStateModel$cashStatesDiff$1.call(ContractStateModel.kt:29)
at net.corda.client.jfx.model.ContractStateModel$cashStatesDiff$1.call(ContractStateModel.kt:22)
at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
at …
```
> Correct unchecked cast call

- .ci/api-current.txt
- core/src/main/kotlin/net/corda/core/internal/schemas/NodeInfoSchema.kt
- docs/source/changelog.rst
- node/src/main/kotlin/net/corda/node/services/network/PersistentNetworkMapCache.kt
- node/src/main/kotlin/net/corda/node/services/schema/NodeSchemaService.kt
NodeInfoSchema shouldn't be part of the public API, moving it to internal package and modified api-current.txt.
This changes is  needed to allow new ``node_info_hash`` column to be added for the network map redesign work.
> Move node info schema to internal package

- .ci/check-api-changes.sh
The valid range of a process exit code is 0 - 255. So protect against overflow by capping this value at 255.
> Protect against VERY unlikey chance of overflow.

- node-api/src/main/kotlin/net/corda/nodeapi/ArtemisTcpTransport.kt
- samples/simm-valuation-demo/src/integration-test/kotlin/net/corda/vega/SimmValuationTest.kt
Remove unsafe/unused TLS cipher suites.
Reasoning:
- We currently issue ECDSA TLS certs.
- However, we should support RSA keys because we've seen that some cloud providers support RSA HSMs, but not ECDSA yet.
- We don't (and it seems we won't) support DSS.
- ECDHE is more secure (forward secrecy) than ECDH and RSA (no DH at all), however slightly slower than ECDH (need to create an ephemeral key per session).
- TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 is also an option for anyone wanting to avoid any use of ECC  (and potentially corrupted curves) when using RSA, but it is slower than ECDHE.
> Supported TLS cipher suites

- core/src/test/kotlin/net/corda/core/flows/CollectSignaturesFlowTests.kt
- core/src/test/kotlin/net/corda/core/flows/FinalityFlowTests.kt
- core/src/test/kotlin/net/corda/core/internal/ResolveTransactionsFlowTest.kt
- docs/source/example-code/src/test/kotlin/net/corda/docs/CustomVaultQueryTest.kt
- docs/source/example-code/src/test/kotlin/net/corda/docs/FxTransactionBuildTutorialTest.kt
- finance/src/test/kotlin/net/corda/finance/flows/CashExitFlowTests.kt
- node/src/test/kotlin/net/corda/node/messaging/TwoPartyTradeFlowTests.kt
- node/src/test/kotlin/net/corda/node/services/events/ScheduledFlowTests.kt
- node/src/test/kotlin/net/corda/node/services/statemachine/FlowFrameworkTests.kt
- node/src/test/kotlin/net/corda/node/services/transactions/NotaryServiceTests.kt
- testing/test-utils/src/main/kotlin/net/corda/testing/CoreTestUtils.kt
Most uses where with MockNetwork which recently got a defaultNotaryIdentity property for dealing with the default single notary case. The remaining uses where in flows.
> Retired getDefaultNotary test extension method.

- settings.gradle
Replace unsupported syntax with official Gradle approach for changing the project directory.
> Fix Gradle warning for example-code project.

- client/rpc/src/integration-test/kotlin/net/corda/client/rpc/RPCStabilityTests.kt
- core/src/main/kotlin/net/corda/core/messaging/CordaRPCOps.kt
- core/src/main/kotlin/net/corda/core/node/ServiceHub.kt
- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/main/kotlin/net/corda/node/internal/CordaRPCOpsImpl.kt
- node/src/main/kotlin/net/corda/node/internal/RpcAuthorisationProxy.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/MockServices.kt
A first step towards making the node shutdown and overall RPC client-to-node connection better.
RPC clients can subscribe to an observable and be notified when the node will shutdown intentionally.
> CORDA-296: added rpc that returns an observable for node state

- core/src/main/kotlin/net/corda/core/node/ServiceHub.kt
- core/src/main/kotlin/net/corda/core/transactions/ContractUpgradeTransactions.kt
- core/src/main/kotlin/net/corda/core/transactions/NotaryChangeTransactions.kt
- core/src/main/kotlin/net/corda/core/transactions/SignedTransaction.kt
- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/main/kotlin/net/corda/node/internal/StartedNode.kt
- node/src/main/kotlin/net/corda/node/services/events/NodeSchedulerService.kt
- node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt
- node/src/test/kotlin/net/corda/node/services/events/NodeSchedulerServiceTest.kt
- node/src/test/kotlin/net/corda/node/services/persistence/DBTransactionStorageTests.kt
- node/src/test/kotlin/net/corda/node/services/vault/VaultSoftLockManagerTest.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/MockServices.kt
* strategy is for functions to take what they need, with ServiceHub helpers where convenient
* this all makes AbstractNode a little less crazy which is a good thing
* some files reverted to master state
> Fix circular dependency

- node/src/main/kotlin/net/corda/node/services/identity/InMemoryIdentityService.kt
- node/src/main/kotlin/net/corda/node/services/identity/PersistentIdentityService.kt
Always register identities in a certificate path from the root down to the target certificate, so that the first certificate with a name is always the one recorded in the name lookup map.
> Step through cert path when registering

- testing/node-driver/src/main/kotlin/net/corda/testing/node/MockNode.kt
It breaks master on the open jdk and isn't actually used by the code
> BUGFIX: Remove bad import

- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/ServerContexts.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/SharedContexts.kt
The `AllButBlacklisted` class is uninstantiable by the deterministic JVM, which knows nothing about SQL, networking etc. However, the JVM initialises the class file when it loads it, and hence instantiates all of the constants inside it. So we _must_ keep the server-specific serialisation contexts in a separate `.class` file from the serialisation contexts which the enclave will need to use.
> Separate server contexts from shared contexts.

- node/src/main/kotlin/net/corda/node/services/vault/HibernateQueryCriteriaParser.kt
- node/src/test/java/net/corda/node/services/vault/VaultQueryJavaTests.java
- node/src/test/kotlin/net/corda/node/services/vault/VaultQueryTests.kt
When a vault query has multiple aggregate function (e.g sum and avg), the column used to group by was repeated accordingly to number of aggregate functions.
Example aggregate sum and max of `pennies` group by `currency`:
val sumCriteria = VaultCustomQueryCriteria(builder { CashSchemaV1.PersistentCashState::pennies.sum(groupByColumns = listOf(CashSchemaV1.PersistentCashState::currency)) })
val maxCriteria = VaultCustomQueryCriteria(builder { CashSchemaV1.PersistentCashState::pennies.max(groupByColumns = listOf(CashSchemaV1.PersistentCashState::currency)) })
vaultService.queryBy<FungibleAsset<*>>(sumCriteria.and(maxCriteria))
Before the change the query would return the following columns:
`sum, currency, max, currency`,
after the change (the column with currency is not duplicated):
`sum, …
> Vault query - don't return repeated column which groups multiple aggregation functions.

- docs/source/running-a-notary.rst
- node/src/main/kotlin/net/corda/node/ArgsParser.kt
- node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt
- node/src/test/kotlin/net/corda/node/ArgsParserTest.kt
When the bootstrap-raft-cluster flag is set, the node forms a single node cluster (ignoring configured peer addresses), acting as a seed for other nodes to join the cluster.
> CORDA-768: Raft Notary: bootstrap command line flag

- node/src/main/kotlin/net/corda/node/services/transactions/DistributedImmutableMap.kt
We remove snapshotting since it is not effective in our use case. We keep the Raft command log "forever" to allow new nodes to join the cluster and replay the commands.
> CORDA-767: Raft Notary: remove snapshotting

- core/src/main/kotlin/net/corda/core/internal/schemas/NodeInfoSchema.kt
- finance/src/main/kotlin/net/corda/finance/schemas/CashSchemaV1.kt
Certain Database providers do not work well with LOB field types when joining across different tables. Specifically, certain cash queries were failing when attempting to query by issuer_key_hash.
> Removed incorrect @Lob annotation from key_hash schema fields.

- node/capsule/build.gradle
- webserver/webcapsule/build.gradle
Changes to make node.conf more powerful resulted in webserver capsule JAR throwing class not found exception due to missing config parsing library.  Also include default config to avoid error about missing default config.
> Add config library and default config to webserver JAR

- node/src/test/java/net/corda/node/services/vault/VaultQueryJavaTests.java
- node/src/test/kotlin/net/corda/node/services/vault/NodeVaultServiceTest.kt
- node/src/test/kotlin/net/corda/node/services/vault/VaultQueryTests.kt
- testing/test-utils/src/main/kotlin/net/corda/testing/contracts/VaultFiller.kt
Detangle issuers in NodeVaultServiceTest, which has been using two keys on a single node, for different issuing identities, which doesn't work right now because we don't actually have multiple identity support.
Also remove duplicate data in parameters to fillWithSomeTestCash().
> Detangle issuers in NodeVaultServiceTest

- core/src/main/kotlin/net/corda/core/internal/schemas/NodeInfoSchema.kt
- node/src/main/kotlin/net/corda/node/services/transactions/BFTNonValidatingNotaryService.kt
- node/src/main/kotlin/net/corda/node/services/transactions/RaftUniquenessProvider.kt
- node/src/main/kotlin/net/corda/node/services/vault/VaultSchema.kt
* Added explicit table names (mostly for join tables).
* Shorten or alter 2 tables backing notaries.
* Change a compound index declaration to one column index.
> Consistent database tables naming convention.

- core/src/main/kotlin/net/corda/core/node/ServiceHub.kt
- finance/src/main/kotlin/net/corda/finance/contracts/asset/cash/selection/AbstractCashSelection.kt
- finance/src/main/kotlin/net/corda/finance/contracts/asset/cash/selection/CashSelectionH2Impl.kt
- finance/src/main/kotlin/net/corda/finance/contracts/asset/cash/selection/CashSelectionPostgreSQLImpl.kt
- node/src/main/kotlin/net/corda/node/internal/StartedNode.kt
- node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt
- node/src/main/kotlin/net/corda/node/services/vault/VaultSchema.kt
- node/src/test/kotlin/net/corda/node/services/persistence/HibernateConfigurationTest.kt
- node/src/test/kotlin/net/corda/node/services/vault/NodeVaultServiceTest.kt
- node/src/test/kotlin/net/corda/node/services/vault/VaultQueryTests.kt
Certain database providers have limitations on join table queries where LOB attributes are included in the select criteria. This PR removes the duplicated copy of the Transaction (Contract State) from the `VaultStates` table to prevent Vault Query failure.
Transaction contract state now resolved using `StateLoader` (from `DBTransactionStorage`).
An additional `loadStates(Set<StateRef>)` has also been added to the StateLoader interface.
> Removal of transaction contract state as BLOB in VaultStates table.

- testing/node-driver/src/main/kotlin/net/corda/testing/node/MockNode.kt
Change how mock notary identity is extracted, to match reversion in commit 3bb018a5
> Change how mock notary identity is extracted

- node/src/main/kotlin/net/corda/node/internal/cordapp/CordappLoader.kt
First Corda PR.
Reason:
- when running unit tests I noticed tests scanning the classpath repeatedly, which is usually very slow
Fix:
- I've added a cache, and it reduced the "node:test" time by about 15-20s (locally)  
- as a cache implementation I used a LRUMap with a max size to avoid memory issues
> Performance improvement: cache app classloaders

- docs/source/changelog.rst
- finance/src/test/kotlin/net/corda/finance/contracts/asset/CashTests.kt
- node/src/integration-test/kotlin/net/corda/test/node/NodeStatePersistenceTests.kt
- node/src/main/kotlin/net/corda/node/services/identity/InMemoryIdentityService.kt
- node/src/main/kotlin/net/corda/node/services/identity/PersistentIdentityService.kt
- node/src/main/kotlin/net/corda/node/services/persistence/AbstractPartyToX500NameAsStringConverter.kt
- node/src/test/java/net/corda/node/services/vault/VaultQueryJavaTests.java
- node/src/test/kotlin/net/corda/node/services/identity/InMemoryIdentityServiceTests.kt
- node/src/test/kotlin/net/corda/node/services/identity/PersistentIdentityServiceTests.kt
- node/src/test/kotlin/net/corda/node/services/persistence/HibernateConfigurationTest.kt
- node/src/test/kotlin/net/corda/node/services/vault/NodeVaultServiceTest.kt
- node/src/test/kotlin/net/corda/node/services/vault/VaultQueryTests.kt
- node/src/test/kotlin/net/corda/node/services/vault/VaultWithCashTest.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/NodeTestUtils.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/MockServices.kt
- testing/test-utils/src/main/kotlin/net/corda/testing/CoreTestUtils.kt
- testing/test-utils/src/main/kotlin/net/corda/testing/contracts/VaultFiller.kt
Previously when de-anonymising a Party instance, the name of the Party was used rather than
the key, meaning a Party could be constructed with a random nonsense key and any name, and be
treated as corresponding to the well known identity. This is not a security hole in itself as
in any real scenario a party shouldn't be trusted without having been registered, it creates
a significant risk of a security hole depending on how trusted the anonymous identity is, and
the returned identity is considered.
> CORDA-759: Enforce key checks on identity de-anonymisation

- finance/src/main/kotlin/net/corda/finance/contracts/asset/cash/selection/CashSelectionPostgreSQLImpl.kt
Issuer Reference has reverted back to being of type `BYTEA` (a previous PR changes this to VARCHAR).
Issuer Party should always be a VARCHAR.
> Correct PostgreSQL types

- node/src/main/kotlin/net/corda/node/services/vault/VaultSchema.kt
Open sourcing intentionally.  Results in 10x throughput increase after 30,000 transactions.
> ENT-1110 Additional index to vault_states table to stop a table scan.

- testing/node-driver/src/integration-test/kotlin/net/corda/testing/driver/DriverTests.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/driver/Driver.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/internal/RPCDriver.kt
- verifier/src/integration-test/kotlin/net/corda/verifier/VerifierDriver.kt
Let Driver start nodes in registration mode.
Added a simple test to verify that the started node hits a URL
> ENT-1069 Allow for nodes to be started in registration mode

- node/src/main/kotlin/net/corda/node/shell/RPCOpsWithContext.kt
Before merging the PR to rollback the node state RPC, another PR that used it was merged thus causing the build to fail. This PR removes the last uses of this RPC.
> remove NodeState and nodeStateObservable remnants

- core/src/main/kotlin/net/corda/core/crypto/Crypto.kt
- node/src/test/kotlin/net/corda/node/utilities/TLSAuthenticationTests.kt
Various unit tests for EC NIST P-256 - RSA mixed key mutual TLS authentication.
RSA functionality will be required for nodes running on cloud (e.g. Azure), where HSMs provide support for RSA keys only. I am also checking for mixed CA keys required during cert path validation.
Also changed the `Crypto.kt` RSA OIDs due to PKCS1 cert validation compatibility purposes.
> Mutual TLS auth - mixed keys

- node/src/main/kotlin/net/corda/node/services/network/PersistentNetworkMapCache.kt
Removed a workaround that caused a db transaction to hang when using Azure SQLServer.
> ENT-1128 fix node restarts when using AzureSQLServer

- core/src/main/kotlin/net/corda/core/internal/ToggleField.kt
- core/src/main/kotlin/net/corda/core/serialization/internal/SerializationEnvironment.kt
- core/src/test/kotlin/net/corda/core/internal/ToggleFieldTest.kt
- testing/test-utils/src/main/kotlin/net/corda/testing/SerializationTestHelpers.kt
for debugging, exceptions now look like:
````
net.corda.core.internal.ThreadLeakException: Leaked thread 'pool-2-thread-1' detected, value was: testSerializationEnv(inherited values are poisoned on clear(net.corda.core.internal.ToggleFieldTest))
````
> CORDA-806 Show origin test in ThreadLeakException

- docs/source/example-code/src/main/kotlin/net/corda/docs/CustomVaultQuery.kt
- finance/src/main/kotlin/net/corda/finance/contracts/asset/cash/selection/AbstractCashSelection.kt
- finance/src/main/kotlin/net/corda/finance/contracts/asset/cash/selection/CashSelectionH2Impl.kt
- finance/src/main/kotlin/net/corda/finance/contracts/asset/cash/selection/CashSelectionMySQLImpl.kt
- finance/src/main/kotlin/net/corda/finance/contracts/asset/cash/selection/CashSelectionPostgreSQLImpl.kt
This fixes the leak by sending the business logic as a lambda to the executeQuery method that actually opens the PreparedStatement, and is responsible to close it.
Another non-disruptive option would be for the executeQuery to return some Tuple with a String and a List of parameters, and the abstract class to be responsible to create the PS and execute.
> [CORDA-824]: fix resource leak in Cash selection

- docs/source/deploying-a-node.rst
- docs/source/running-a-node.rst
Change to docs to fix systemctl syntax and enable services to start on boot.
> Docs update: instructions to enable service

- node/src/integration-test/kotlin/net/corda/node/services/network/NodeInfoWatcherTest.kt
- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/main/kotlin/net/corda/node/internal/Node.kt
- node/src/main/kotlin/net/corda/node/services/network/NodeInfoWatcher.kt
- node/src/test/kotlin/net/corda/node/services/network/NetworkMapUpdaterTest.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/driver/Driver.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/internal/NodeBasedTest.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/MockNode.kt
so that the inheritable thread local serialization env can be propagated through it without affecting subsequent tests
> CORDA-806 Use non-static Rx pool when testing

- node-api/src/main/kotlin/net/corda/nodeapi/config/SSLConfiguration.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/ServiceIdentityGenerator.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/crypto/X509Utilities.kt
- node/src/integration-test/kotlin/net/corda/node/utilities/registration/NetworkRegistrationHelperDriverTest.kt
- node/src/main/kotlin/net/corda/node/utilities/registration/NetworkRegistrationHelper.kt
- node/src/test/kotlin/net/corda/node/utilities/registration/NetworkisRegistrationHelperTest.kt
- testing/node-driver/src/integration-test/kotlin/net/corda/testing/driver/DriverTests.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/NodeTestUtils.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/driver/Driver.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/internal/RPCDriver.kt
- verifier/src/integration-test/kotlin/net/corda/verifier/VerifierDriver.kt
During the node registration process make nodes check that the root of the certificate is an expected certificate stored under /certificates/rootCaCert.cer
Note this PR makes the registration FAIL if there is no such file, we might want to relax that for testing/dev purposes.
Also this borrows some code from doorman (to craft a fake doorman reply), all that code should be put in the OS repo so that both doorman & tests can use it.
> ENT-1125 bootstrap root certificate

- docs/source/deploying-a-node.rst
A user asked on Discourse about running Corda using Upstart (Ubuntu 14.04) rather than SystemD so I thought I'd add the instructions here too.
> add upstart instructions

- build.gradle
- constants.properties
- gradle-plugins/api-scanner/build.gradle
- gradle-plugins/build.gradle
- gradle-plugins/cordapp/build.gradle
- gradle-plugins/cordform-common/build.gradle
- gradle-plugins/cordformation/build.gradle
- gradle-plugins/publish-utils/build.gradle
- gradle-plugins/quasar-utils/build.gradle
Why: Because it's needed to remove the publisher role and to make it easier to publish custom versions of gradle-plugins for feature branches.
> CORDA-840: Gradle plugins are now able to be published to artifactory.

- finance/src/test/kotlin/net/corda/finance/contracts/asset/CashTests.kt
- node/src/test/kotlin/net/corda/node/services/vault/NodeVaultServiceTest.kt
Pass well known identities instead of confidential into generateSpend()
> Correct identities passed to generateSpend

- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/main/kotlin/net/corda/node/services/network/NetworkMapClient.kt
Ensure NodeInfo is generated only once, specifically when using Cordformation to deploy a node.
Now initNodeInfo takes a NetworkMapCacheBaseInternal so that it can check the database to see if we already have a NodeInfo "for" this node.
Also removed the dependency of IdentityService on NodeInfo (it wasn't used anyway) to break the dependency loop, as initialiseDatabasePersistence needs an IdentityService
> Create a single NodeInfo

- node/src/main/kotlin/net/corda/node/services/messaging/ArtemisMessagingServer.kt
- node/src/main/kotlin/net/corda/node/services/messaging/RPCServer.kt
Minor cleanup: stop giving full RPC permissions to NODE_USER.
This was previously required to authorize accesses from NodeWebServer and local Shell; in both cases we now use a different mechanism.
> Stop granting NODE_USER full RPC permissions

- node-api/src/main/kotlin/net/corda/nodeapi/internal/config/SSLConfiguration.kt
- node/src/integration-test/kotlin/net/corda/node/utilities/registration/NodeRegistrationTest.kt
- node/src/main/kotlin/net/corda/node/utilities/registration/NetworkRegistrationHelper.kt
- node/src/test/kotlin/net/corda/node/utilities/registration/NetworkRegistrationHelperTest.kt
- testing/node-driver/src/integration-test/kotlin/net/corda/testing/driver/DriverTests.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/internal/DriverDSLImpl.kt
Revert https://github.com/corda/corda/pull/2151
we decided not to ship/deliver a .cer file.
We will use the node truststore instead.
> Revert bootstrap netcert

- core/src/test/kotlin/net/corda/core/flows/AttachmentTests.kt
> Bypass needless lookup

- node/src/test/kotlin/net/corda/node/services/events/NodeSchedulerServiceTest.kt
- node/src/test/kotlin/net/corda/node/services/messaging/ArtemisMessagingTests.kt
- node/src/test/kotlin/net/corda/node/utilities/registration/NetworkRegistrationHelperTest.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/MockNode.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/NodeTestUtils.kt
shouldn't be api, and only MockNode needs most of the fields
> CORDA-716 Inline testNodeConfiguration

- gradle-plugins/cordformation/src/noderunner/kotlin/net/corda/plugins/NodeRunner.kt
So samples can be run again
Direct port of https://github.com/corda/enterprise/pull/191
> [ENT-1257] Proper escaping of space in all parameters on Windows

- node-api/src/main/kotlin/net/corda/nodeapi/internal/NetworkMap.kt
- node/src/main/kotlin/net/corda/node/services/network/NetworkMapClient.kt
SignedNetworkMap verification should also include cert path validation,
which was probably moved away by accident, because docs say about the
exception CertPathValidatorException.
> SignedNetworkMap verification fix

- docs/source/clientrpc.rst
This includes:
* More fixes to typos and inconsistencies
* Avoid deprecation claims. As separately discussed, this leads to other inconsistencies and requires a properly standardised config format.
> CORDA-827: more doc changes

- build.gradle
- client/rpc/src/test/kotlin/net/corda/client/rpc/RPCConcurrencyTests.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/RPCDriver.kt
Downgrade Artemis to version 2.1 to protect against rogue non-TLS connections causing OOM.
* https://issues.apache.org/jira/browse/ARTEMIS-1559
> ENT-1249 - Downgrade Artemis from v2.4 to v2.1

- docs/source/network-map.rst
- node-api/src/main/kotlin/net/corda/nodeapi/internal/NetworkMap.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/NetworkParametersCopier.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/NetworkParametersGenerator.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/NetworkParametersTest.kt
- node/src/integration-test/kotlin/net/corda/node/services/network/NetworkMapTest.kt
- node/src/integration-test/kotlin/net/corda/node/utilities/registration/NodeRegistrationTest.kt
- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/main/kotlin/net/corda/node/internal/Node.kt
- node/src/main/kotlin/net/corda/node/services/messaging/ArtemisMessagingClient.kt
- node/src/main/kotlin/net/corda/node/services/messaging/ArtemisMessagingServer.kt
- node/src/main/kotlin/net/corda/node/services/messaging/P2PMessagingClient.kt
- node/src/main/kotlin/net/corda/node/services/messaging/RPCMessagingClient.kt
- node/src/main/kotlin/net/corda/node/services/messaging/VerifierMessagingClient.kt
- node/src/main/kotlin/net/corda/node/services/network/NetworkMapClient.kt
- node/src/main/kotlin/net/corda/node/services/network/PersistentNetworkMapCache.kt
- node/src/test/kotlin/net/corda/node/internal/NetworkParametersTest.kt
- node/src/test/kotlin/net/corda/node/services/messaging/ArtemisMessagingTests.kt
- node/src/test/kotlin/net/corda/node/services/network/NetworkMapClientTest.kt
- node/src/test/kotlin/net/corda/node/services/network/NetworkMapUpdaterTest.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/MockNode.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/DriverDSLImpl.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/RPCDriver.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/network/NetworkMapServer.kt
- testing/test-common/src/main/kotlin/net/corda/testing/common/internal/ParametersUtilities.kt
- testing/test-utils/src/main/kotlin/net/corda/testing/TestConstants.kt
- tools/demobench/src/main/kotlin/net/corda/demobench/model/NodeController.kt
Added handling of the situation when network map is advertising different parameters hash - for now we stop the node.
Added wiring of maxMessageSize (in fact we already had that, now it's just taken from network parameters), also handling of epoch on node startup.
> Wire part of network parameters

- core/src/main/kotlin/net/corda/core/contracts/ContractsDSL.kt
- core/src/main/kotlin/net/corda/core/identity/CordaX500Name.kt
- core/src/main/kotlin/net/corda/core/internal/InternalUtils.kt
- core/src/test/kotlin/net/corda/core/contracts/ContractsDSLTests.kt
- testing/test-utils/src/main/kotlin/net/corda/testing/CoreTestUtils.kt
* Made ContractsDSL.requireSingleCommand behave the same way for the inline function and the java version (thrown error messages were different)
* Added java compatible implementations of the ContractsDSL.single
* Added tests for the above functions to make sure both signatures work the same way
> CORDA-880 Make contractsdsl java interop functions behave same as inline functions

- gradle-plugins/cordformation/src/noderunner/kotlin/net/corda/plugins/NodeRunner.kt
The monitoring option was overwriting the JVM args to enable debug.  Now they coexist.
> ENT-1302 Fix debug option in Cordformation

- docs/source/setting-up-a-corda-network.rst
- node-api/src/main/kotlin/net/corda/nodeapi/internal/network/NetworkBootstrapper.kt
- tools/bootstrapper/build.gradle
Give the bootstrapper a directory containing a list of .conf files and a corda.jar
Generate a node directory for each .conf file, using the name of the .conf file
The old method where the directories are already created will still work
> [CORDA-879] Generate node directories as part of bootstrapping

- client/rpc/src/integration-test/java/net/corda/client/rpc/CordaRPCJavaClientTest.java
* Align CordaRPCJavaClientTest with Kotlin version of the test (`(byte)0` instead of `"1".getBytes()`)
* Refactoring to align with enterprise repo (exceptions).
> Minor refactoring of CordaRPCJavaClientTest to align with enterprise repo.

- core/src/main/kotlin/net/corda/core/crypto/Crypto.kt
- core/src/test/kotlin/net/corda/core/crypto/CryptoUtilsTest.kt
- core/src/test/kotlin/net/corda/core/crypto/EdDSATests.kt
RFC8032 _Edwards-Curve Digital Signature Algorithm (EdDSA)_ mentions various variants of EdDSA.
This PR includes unit-tests based on the test vectors provided in RFC8032 and show that i2p implementation is indeed compatible with PureEdDSA Ed25519.
> [CORDA-890] Adding tests to check EdDSA compatibility with RFC8032

- node-api/src/main/kotlin/net/corda/nodeapi/internal/DevIdentityGenerator.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/crypto/X509Utilities.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/crypto/X509UtilitiesTest.kt
- node/src/integration-test/kotlin/net/corda/node/services/network/NetworkMapTest.kt
- node/src/integration-test/kotlin/net/corda/node/utilities/registration/NodeRegistrationTest.kt
- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/main/kotlin/net/corda/node/internal/Node.kt
- node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt
- node/src/test/kotlin/net/corda/node/services/network/NetworkMapClientTest.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/driver/Driver.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/DriverDSLImpl.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/RPCDriver.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/network/NetworkMapServer.kt
- verifier/src/integration-test/kotlin/net/corda/verifier/VerifierDriver.kt
Using the --just-generate-node-info flag for the notary nodes so that their identities can be submitted to the network map server, which does the network parameters generation.
> Internal driver now also does the registration for the notaries.

- core/src/main/kotlin/net/corda/core/flows/FlowLogicRef.kt
- node/src/main/kotlin/net/corda/node/services/statemachine/FlowLogicRefFactoryImpl.kt
- node/src/test/kotlin/net/corda/node/services/events/ScheduledFlowTests.kt
- node/src/test/kotlin/net/corda/node/services/statemachine/FlowLogicRefFactoryImplTest.kt
- samples/irs-demo/cordapp/src/main/kotlin/net/corda/irs/contract/IRS.kt
- samples/simm-valuation-demo/src/main/kotlin/net/corda/vega/contracts/PortfolioState.kt
Removes the need for schedulable flow states to hold a reference to the class.
>  CORDA-785: Add functions for constructing FlowLogicRef without the class

- finance/src/main/kotlin/net/corda/finance/flows/CashExitFlow.kt
- node/src/integration-test/kotlin/net/corda/test/node/NodeStatePersistenceTests.kt
- tools/explorer/src/main/kotlin/net/corda/explorer/ExplorerSimulation.kt
Previously, one constructor used `issueRef`, and the other used `issuerRef`. This is confusing when starting the flow from the CRaSH shell and using named parameters.
> Harmonises the names of the parameters across CashExitFlow constructors.

- core/src/main/kotlin/net/corda/core/crypto/Crypto.kt
- core/src/main/kotlin/net/corda/core/crypto/CryptoUtils.kt
- core/src/test/kotlin/net/corda/core/crypto/CryptoUtilsTest.kt
- node/src/test/kotlin/net/corda/node/services/transactions/NotaryServiceTests.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/MockNode.kt
Fully supporting ECDSA (both R1 and K1) in case they are set as the default signature schemes.
This work includes:
- Ignoring a test that assumes signature idempotency (ECDSA is randomised and not deterministic)
- IRS demo uses keys via MockNode and will still use EdDSA (even if we ever change the default) as the keys are fixed in json files.
- Support entropyToKeyPair for ECDSA R1 and K1
- Unit tests for both EdDSA and ECDSA (eg EdDSA trims the entropy to the first 256 bytes, while ECDSA uses hash(entropy) if it is out of range)
- The default algorithm is still EdDSA, but this PR will allow for easier transition to ECDSA when and if required.
> [CORDA-843] ECDSA full support and entropyToKeyPair

- gradle-plugins/api-scanner/README.md
Fix broken link to the Corda public API strategy.
> Update link for Corda API strategy documentation.

- constants.properties
- gradle-plugins/cordformation/src/main/kotlin/net/corda/plugins/Cordform.kt
- gradle-plugins/cordformation/src/main/kotlin/net/corda/plugins/Cordformation.kt
- gradle-plugins/cordformation/src/main/kotlin/net/corda/plugins/Node.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/network/NetworkBootstrapper.kt
Make the cordform task
- generate config files in the root dir
- extract the corda jar to the root dir
- run the network bootstrapper to create the node directories
- place the cordapps and any additional config in the generated node directories.
> CORDA-892: Make cordform test use new network bootstrapper logic

- docs/source/example-code/src/main/resources/example-node.conf
Minor fix: permission syntax used in example-node.conf
> Fix example-node.conf in docs

- node/src/main/kotlin/net/corda/node/services/network/NetworkMapClient.kt
- node/src/test/kotlin/net/corda/node/services/network/NetworkMapClientTest.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/network/NetworkMapServer.kt
Pull through the error responses that are returned from the network map server, to aid the user in debugging. Currently returned response code is shown but any message is lost.
> ENT-1226 Improve Network client Error Handling

- .ci/api-current.txt
- core/src/main/kotlin/net/corda/core/internal/schemas/NodeInfoSchema.kt
- core/src/main/kotlin/net/corda/core/schemas/CommonSchema.kt
- docs/source/changelog.rst
- docs/source/upgrade-notes.rst
- finance/src/test/kotlin/net/corda/finance/schemas/SampleCashSchemaV2.kt
- finance/src/test/kotlin/net/corda/finance/schemas/SampleCommercialPaperSchemaV2.kt
- node/src/main/kotlin/net/corda/node/services/vault/VaultSchema.kt
- testing/test-utils/src/main/kotlin/net/corda/testing/internal/vault/DummyDealContract.kt
- testing/test-utils/src/main/kotlin/net/corda/testing/internal/vault/DummyDealStateSchemaV1.kt
- testing/test-utils/src/main/kotlin/net/corda/testing/internal/vault/DummyLinearContract.kt
- testing/test-utils/src/main/kotlin/net/corda/testing/internal/vault/DummyLinearStateSchemaV1.kt
- testing/test-utils/src/main/kotlin/net/corda/testing/internal/vault/DummyLinearStateSchemaV2.kt
add human readable foreign key names 
and move the State `participants` mapping to the subclass so that the table name can be configured
> Tudor - hibernate mapping changes

- node/src/integration-test/kotlin/net/corda/node/AuthDBTests.kt
This fixes the `ActiveMQ-client-factory-threads` thread leaks, but i'm still seeing leaked Hikari pool threads occasionally
> Minor: AuthDBTests - close RPC connections to prevent thread leaks

- node/src/integration-test/kotlin/net/corda/node/NodeKeystoreCheckTest.kt
- node/src/integration-test/kotlin/net/corda/node/SSHServerTest.kt
- node/src/integration-test/kotlin/net/corda/node/services/AttachmentLoadingTests.kt
- node/src/integration-test/kotlin/net/corda/node/services/DistributedServiceTests.kt
- node/src/integration-test/kotlin/net/corda/node/services/RaftNotaryServiceTests.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/ShutdownManager.kt
Some of the recent integration test flakiness (namely port conflict exceptions) in CI was caused by leaked in process nodes. That seems to happen when the driver is shut down before the default notary node has started, and the notary node's 'dispose' future times out in the ShutdownManager (the timeout was set to 1s), so it never gets stopped.
> Integration test port binding exception fix

- node/src/test/kotlin/net/corda/node/services/transactions/NotaryServiceTests.kt
It's a bit dangerous leaving this test ignored
> Re-enable notary idempotence test

- node-api/src/main/kotlin/net/corda/nodeapi/internal/DevIdentityGenerator.kt
- node/src/integration-test/kotlin/net/corda/node/services/BFTNotaryServiceTests.kt
- node/src/integration-test/kotlin/net/corda/node/services/DistributedServiceTests.kt
- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- samples/notary-demo/src/main/kotlin/net/corda/notarydemo/BFTNotaryCordform.kt
- samples/notary-demo/src/main/kotlin/net/corda/notarydemo/Notarise.kt
- samples/notary-demo/src/main/kotlin/net/corda/notarydemo/RaftNotaryCordform.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/NotarySpec.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/DriverDSLImpl.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/DummyClusterSpec.kt
This has been approved & merged as part of https://github.com/corda/corda/pull/2269, but reverted because of integration test flakiness. It turned out to be not related to the flakiness.
> ENT-811: Raft notaries can share a single key pair for the service identity 

- node-api/src/main/kotlin/net/corda/nodeapi/ArtemisTcpTransport.kt
TLDR: This reduces the number of epoll fds created during testing which occasionally cause "too many open files" shenanigary and subsequent hangs like this: https://ci-master.corda.r3cev.com/viewLog.html?buildId=53620&buildTypeId=CordaEnterprise_PullRequests_IntegrationTests&tab=buildLog
Long story: with the GLOBAL_THREAD_POOL_THING switched off during testing, the number of threads used by netty to do stuff became linear with the number of remoting connections. Artemis for some reason defaults to using (processor count * 3) threads per such connection. On my setup this means 24. On linux each such thread creates 3 epoll fds, which means a single remoting connection (= bridge) creates 72 fds. not cool. Anyway this hardcodes the number of threads to 1 (during testing)/
> Use single thread per netty eventgroup during testing

- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/main/kotlin/net/corda/node/services/config/NodeConfiguration.kt
- node/src/main/kotlin/net/corda/node/services/persistence/DBTransactionStorage.kt
- node/src/main/kotlin/net/corda/node/utilities/AppendOnlyPersistentMap.kt
- node/src/main/kotlin/net/corda/node/utilities/NonInvalidatingCache.kt
- node/src/test/kotlin/net/corda/node/messaging/TwoPartyTradeFlowTests.kt
- node/src/test/kotlin/net/corda/node/services/persistence/DBTransactionStorageTests.kt
Make the transaction cache in DBTransactionStorage memory-we…ight based (rather than count based) so large transactions can no longer use an undue amount of memory.
> ENT-1383 Memory weight based transaction cache

- node/src/main/kotlin/net/corda/node/services/schema/HibernateObserver.kt
- node/src/test/kotlin/net/corda/node/services/persistence/HibernateConfigurationTest.kt
Modify the HibernateObserver to persist states by schema (and only create a session per schema, not one per state per schema)
> ENT-1389 persist transaction by schema

- docs/source/example-code/src/test/java/net/corda/docs/java/tutorial/testdsl/CommercialPaperTest.java
- docs/source/example-code/src/test/kotlin/net/corda/docs/tutorial/testdsl/TutorialTestDSL.kt
- docs/source/tutorial-test-dsl.rst
Move the CommercialPaperTest examples to a location where it'll be run by gradle/ci. Make sure the tests pass, even the example tests that are intended to fail, so these files are kept up to date as the code changes.
> Move the CommercialPaperTest examples

- core/src/main/kotlin/net/corda/core/flows/NotaryFlow.kt
- core/src/main/kotlin/net/corda/core/node/services/NotaryService.kt
If the notary backend fails we should return a generic "service unavailable" error instead of propagating potentially cryptic implementation-specific exceptions. This should only be used when the issue can't be solved via internal retries.
> Don't propagate internal notary service errors to the client

- client/rpc/src/main/kotlin/net/corda/client/rpc/internal/RPCClientProxyHandler.kt
- docs/source/changelog.rst
- docs/source/messaging.rst
- node-api/src/main/kotlin/net/corda/nodeapi/internal/ArtemisMessagingComponent.kt
- node/src/integration-test/kotlin/net/corda/node/amqp/AMQPBridgeTest.kt
- node/src/integration-test/kotlin/net/corda/node/amqp/ProtonWrapperTests.kt
- node/src/integration-test/kotlin/net/corda/services/messaging/MQSecurityTest.kt
- node/src/main/kotlin/net/corda/node/internal/Node.kt
- node/src/main/kotlin/net/corda/node/services/api/ServiceHubInternal.kt
- node/src/main/kotlin/net/corda/node/services/messaging/AMQPBridgeManager.kt
- node/src/main/kotlin/net/corda/node/services/messaging/ArtemisMessagingServer.kt
- node/src/main/kotlin/net/corda/node/services/messaging/CoreBridgeManager.kt
- node/src/main/kotlin/net/corda/node/services/messaging/P2PMessagingClient.kt
- node/src/main/kotlin/net/corda/node/services/messaging/VerifierMessagingClient.kt
- node/src/main/kotlin/net/corda/node/services/network/PersistentNetworkMapCache.kt
- node/src/test/kotlin/net/corda/node/services/messaging/ArtemisMessagingTests.kt
This PR renames the outgoing and inbox queue addresses to enhance broker agility.
First, by using a hash of the public key of the nodes in the address construction we reduce the length of the addresses to a range supported by more brokers. Also, with post-quantum keys this will drastically reduce the size of the string.
Also, by changing the name of the inbox to a topic tied to the node identity we disambiguate the identity and potentially in the future we will be able share the broker between nodes for performance and HA purposes.
> Rename Artemis Queue Addresses to allow future broker agility

- core/src/main/kotlin/net/corda/core/internal/schemas/NodeInfoSchema.kt
- core/src/main/kotlin/net/corda/core/node/services/NetworkMapCache.kt
- node/src/integration-test/kotlin/net/corda/node/services/network/PersistentNetworkMapCacheTest.kt
- node/src/main/kotlin/net/corda/node/services/network/PersistentNetworkMapCache.kt
- node/src/test/kotlin/net/corda/node/services/network/NetworkMapCacheTest.kt
I think we should avoid advertising this kind of node infos on network map level though.
> Remove primary key constraint on DBHostAndPort

- finance/src/main/kotlin/net/corda/finance/schemas/CommercialPaperSchemaV1.kt
- finance/src/test/kotlin/net/corda/finance/schemas/SampleCommercialPaperSchemaV1.kt
- node/src/main/kotlin/net/corda/node/services/transactions/PersistentUniquenessProvider.kt
- node/src/main/kotlin/net/corda/node/services/vault/VaultSchema.kt
- node/src/test/kotlin/net/corda/node/services/vault/VaultQueryTests.kt
- testing/test-utils/src/main/kotlin/net/corda/testing/internal/vault/DummyDealStateSchemaV1.kt
- testing/test-utils/src/main/kotlin/net/corda/testing/internal/vault/DummyLinearStateSchemaV2.kt
Changes compatible with R3.Corda (ENT-794):
* Added Hibernate corda-wrapper-binary to CommercialPaperSchema/issuanceRef column, and PersistentUniqnessProvider/requesting_party_key column.
* Shorten names of tables in dummy schemas used in tests.
* Undo removal of compound index of VaultTxnNote (https://github.com/corda/corda/commit/b423fea537077c3336501a300c31dddf3be02c7a).
* Assertions for 2 vault tests don't rely on order of rows.
> Database schema changes

- node-api/src/main/kotlin/net/corda/nodeapi/internal/KeyStoreConfigHelpers.kt
- testing/test-utils/src/main/kotlin/net/corda/testing/internal/InternalTestUtils.kt
- testing/test-utils/src/main/kotlin/net/corda/testing/internal/TestNodeInfoBuilder.kt
This PR extends the createDevNodeCa header with the nodeKeyPair parameter allowing for usage of this method with the pre-existing key pair. This, subsequently, allows for use of this method in more scenarios. A similar change was added in the testing module.
> CORDA-937 adding node key pair to utility/testing methods

- testing/test-utils/src/main/kotlin/net/corda/testing/dsl/TestDSL.kt
Currently, doing:
@Test
fun `test`() {
ledgerServices.ledger(DUMMY_NOTARY) {
transaction {
tweak {
fails()
}
fails()
}
}
}
Will throw an obscure error message (`java.lang.IllegalStateException: A transaction must contain at least one input or output state`), because a test tx that is party of a test ledger is expected to create a valid tx.
> Rethrows a clearer error message when a test tx in a test ledger does not create a valid tx.

- node/capsule/build.gradle
- webserver/src/main/kotlin/net/corda/webserver/internal/NodeWebServer.kt
* Removed the Jolokia endpoint from the node-webserver module. Jolokia (which provides access to JMX monitoring over HTTP) is not required on the webserver - because it is the corda node itself that would be the subject of any monitoring.
* Also removed the Jolokia WAR package from the node module, as it is an unused/unnecessary dependency. JMX monitoring is provided via the Node-Driver if required.
> Remove jolokia war reference from webserver

- node/src/main/kotlin/net/corda/node/services/events/NodeSchedulerService.kt
- node/src/main/kotlin/net/corda/node/services/events/ScheduledActivityObserver.kt
- node/src/test/kotlin/net/corda/node/services/events/NodeSchedulerServiceTest.kt
Was showing up as point of contention in performance testing.
>  CORDA-959 Filter unschedules and remove database activity from inside mutex.

- build.gradle
OWASP dependency checker updated - previous version was no longer working. 
Dependency-checker is a gradle plugin used during development - should be no impact on builds
> Update OWASP dependency checker to latest working version

- node/src/test/kotlin/net/corda/node/services/persistence/HibernateConfigurationTest.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/MockServices.kt
The makeVaultService in MockServices asks for net.corda.nodeapi.internal.persistence.HibernateConfiguration to be passed in as a parameter.
It is only used internally by MockServices, and then in the HibernateConfigurationTest in the net.corda.node package. 
Since the HibernateConfigurationTest is specifically testing hibernate anyway, I've changed it to instantiate what it needs directly and made the makeVaultService function internal to MockServices, so the public API doesn't expose internal types.
> [CORDA-939] Remove exposure of internal hibernate configuration from mockservices

- core/src/main/kotlin/net/corda/core/contracts/ContractState.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/AMQPPrimitiveSerializer.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/AMQPSerializer.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/ArraySerializer.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/CollectionSerializer.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/CorDappCustomSerializer.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/CustomSerializer.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/DeserializationInput.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/EnumEvolutionSerializer.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/EnumSerializer.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/EvolutionSerializer.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/MapSerializer.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/ObjectSerializer.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/PropertySerializer.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/Schema.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializationHelper.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializationOutput.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializerFactory.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/SingletonSerializer.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/carpenter/AMQPSchemaExtensions.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/EvolvabilityTests.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/GenericsTests.kt
This is a multi issue problem
1. Fingerprinting of generics treats <T> and <?> differently, forcing
the evolver to be used when not needed
2. However, the evolver is required sometimes as generics are not
guaranteed to fingerprinting bi-directionally (thanks to type erasure of
deeply nested generic types). However, with serialization now writing
properties in a specific order, we need to ensure they're read back in
that order before applying them to an evolved constructor so as to
not corrupt the object reference cache
3. Keep some helpful debug parameters
> CORDA-943 - Fix trader demo

- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializationHelper.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/PrivatePropertyTests.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializationOutputTests.kt
Because of inheritance, we have to consider multiple getters existing on a class for a property, however in that, we weren't excluding getters that take parameters, something we're unable to provide, so depending no the returned order sometimes we select the wrong one and it all goes terribley wrong.
> CORDA-978 - Only consider getters that accpet zero parameters

- core/src/main/kotlin/net/corda/core/crypto/CompositeKey.kt
- core/src/main/kotlin/net/corda/core/transactions/SignedTransaction.kt
- core/src/main/kotlin/net/corda/core/transactions/TransactionWithSignatures.kt
- Fix double sig verification issue in  `toLedgerTransaction` and `verifyRegularTransaction`. The problem was that `checkSignaturesAreValid` was called twice.
- `CompositeKey.checkFulfilledBy` returns right after the threshold requirement is met. Previously, it required a full scan of signing keys.
- checkValidity() "knows" if it ran before; not required any more to externally check `if (!validated)`
- we now first check for missing signers, then validate signatures.
- fixed missing `checkSignaturesAreValid` from `verifyNotaryChangeTransaction
- some comments and `method signature consistency fixes (private methods)
> CORDA-986 and CORDA-985 CompositeKey and Signature verification performance fixes

- core/src/main/kotlin/net/corda/core/crypto/Crypto.kt
- core/src/main/kotlin/net/corda/core/crypto/PartialMerkleTree.kt
- core/src/main/kotlin/net/corda/core/crypto/SignableData.kt
- core/src/main/kotlin/net/corda/core/crypto/TransactionSignature.kt
- core/src/main/kotlin/net/corda/core/node/services/NotaryService.kt
- core/src/test/kotlin/net/corda/core/crypto/TransactionSignatureTest.kt
Add support for signature verification when we sign over a block of transactions.
According to this model, if and when block-tx signing is enabled in the future, a `TransactionSignature` might be accompanied by a partial Merkle tree, which indicates it's a tx-block signature. This might be useful if we allow block signing in the notary side.
Note that for backwards compatibility and performance purposes, if we only sign over a single transaction, then no Merkle tree computations are applied. 
Also, for advanced privacy, the leaves of a tx-block Merkle tree are `hash(txId)` and not `txId`, as shown in the following diagram.
If we sign a single tx, we sign over the `txId` itself; in this case, we don't utilise the partial tree which should be null.
> CORDA-967 Multi-tx signature verification

- node/src/main/kotlin/net/corda/node/utilities/AppendOnlyPersistentMap.kt
- node/src/test/kotlin/net/corda/node/services/persistence/DBTransactionStorageTests.kt
This should fix https://r3-cev.atlassian.net/browse/SUP-103, the test reproduced a similar condition without the one-liner fix
> CORDA-1003: Fix duplicate detection on cache evict

- node-api/src/main/kotlin/net/corda/nodeapi/internal/network/NetworkBootstrapper.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/network/NetworkMapServer.kt
Trader demo runs fine after the fix.
> CORDA-1008 Samples fail to run due to wrongly configured max transaction size in the network bootstrapper

- core/src/main/kotlin/net/corda/core/internal/X509EdDSAEngine.kt
- core/src/test/kotlin/net/corda/core/internal/X509EdDSAEngineTest.kt
Required for the deterministic core, because `sun.security.x509.X509Key` isn't going to link as it uses an internal `sun.` class.
> CORDA-1009 Remove X509EdDSAEngine dependency on X509Key

- docs/source/tutorial-attachments.rst
Really minor change - fixing a mistake in the docs.
To add attachments the file must first be **added to uploaded** to the node
> Fixing a small mistake added/uploaded, only one required

- .ci/api-current.txt
- client/rpc/src/main/kotlin/net/corda/client/rpc/CordaRPCClient.kt
- client/rpc/src/main/kotlin/net/corda/client/rpc/internal/CordaRPCClientUtils.kt
- client/rpc/src/main/kotlin/net/corda/client/rpc/internal/RPCClient.kt
- node/src/integration-test/kotlin/net/corda/node/services/rpc/RpcSslTest.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/DriverDSLImpl.kt
Remove the sslConfiguration paraemter from the public constructor of CordaRPCClient
Have created an internal factory method for initialising the sslConfiguration - and created an internal utility in net.corda.clienty.rpc.internal.CordaRPCClientUtils for other corda modules to get instances of CordaRPCClient. I considered making the constructor private but it seemed like it was used in so many places this broke the least things.
> CORDA-939 Remove sslConfiguration from public constructor of CordaRPCClient

- core/src/main/kotlin/net/corda/core/node/NodeInfo.kt
- core/src/main/kotlin/net/corda/core/node/services/NetworkMapCache.kt
- docs/source/changelog.rst
- node-api/src/main/kotlin/net/corda/nodeapi/internal/bridging/AMQPBridgeManager.kt
- node/src/integration-test/kotlin/net/corda/node/services/network/PersistentNetworkMapCacheTest.kt
- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/main/kotlin/net/corda/node/internal/Node.kt
- node/src/main/kotlin/net/corda/node/services/network/PersistentNetworkMapCache.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/MockServices.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/InternalMockNetwork.kt
Further, the look up of the node's own node-info from its database has been tightened to ensure there isn't more than one.
Also fixed some brittle code which was assuming exactly one address rather than at least one.
> ENT-1519: Ensure NodeInfo always has at least one address by checking in the c'tor

- build.gradle
- node/build.gradle
- webserver/build.gradle
* Remove compile-time dependencies on jolokia-war from webserver
* Stop exporting jolokia version to all projects, it is only used by node
> Some build tweaks [CORDA-1042]

- docs/source/api-transactions.rst
- docs/source/example-code/src/main/java/net/corda/docs/FlowCookbookJava.java
- docs/source/example-code/src/main/kotlin/net/corda/docs/FlowCookbook.kt
Update [api-transactions.rst](https://docs.corda.net/head/api-transactions.html#verifying-the-transaction-s-signatures) to reflect new ``TransactionWithSignatures.verifySignaturesExcept`` which takes in a ``Collection`` of ``PublicKey``s.
> CORDA-1038 Update verifySignaturesExcept in api-transactions.rst

- node-api/src/main/kotlin/net/corda/nodeapi/internal/protonwrapper/engine/ConnectionStateMachine.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/protonwrapper/engine/EventProcessor.kt
When debugging code with active AMQP connections it is possible for the proton-j state machine to become hung and not drop the bridging socket. This is due to timeout events not flushing through the events on the executor. This change ensures the events leading to close are always run.
> CORDA-1064: Fix a hang in AMQP protocol code

- .ci/api-current.txt
- core/src/main/kotlin/net/corda/core/flows/NotarisationRequest.kt
- core/src/main/kotlin/net/corda/core/flows/NotaryFlow.kt
- core/src/main/kotlin/net/corda/core/flows/SendTransactionFlow.kt
- core/src/main/kotlin/net/corda/core/internal/InternalUtils.kt
- core/src/main/kotlin/net/corda/core/node/services/NotaryService.kt
- core/src/main/kotlin/net/corda/core/transactions/BaseTransactions.kt
- node/src/main/kotlin/net/corda/node/services/transactions/BFTNonValidatingNotaryService.kt
- node/src/main/kotlin/net/corda/node/services/transactions/BFTSMaRt.kt
- node/src/main/kotlin/net/corda/node/services/transactions/NonValidatingNotaryFlow.kt
- node/src/main/kotlin/net/corda/node/services/transactions/ValidatingNotaryFlow.kt
- node/src/test/kotlin/net/corda/node/services/transactions/NotaryServiceTests.kt
- samples/notary-demo/src/main/kotlin/net/corda/notarydemo/MyCustomNotaryService.kt
I'm still working on tests, but this is ready for a first look. I made both validating and non-validating notaries enforce the notarisation request signature check.
More details are under the Jira ticked and NotarisationRequest api docs.
> CORDA-1010: Send a request signature in addition to a transaction to the notary

- constants.properties
- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
I've wanted this error when debugging custom deployments of Corda a dozen times now.
> Added a helpful error log when validating keystores.

- confidential-identities/src/test/kotlin/net/corda/confidential/IdentitySyncFlowTests.kt
- confidential-identities/src/test/kotlin/net/corda/confidential/SwapIdentitiesFlowTests.kt
- core/src/test/kotlin/net/corda/core/flows/AttachmentTests.kt
- core/src/test/kotlin/net/corda/core/serialization/AttachmentSerializationTest.kt
- node/src/main/kotlin/net/corda/node/internal/cordapp/CordappConfigFileProvider.kt
- node/src/test/kotlin/net/corda/node/messaging/TwoPartyTradeFlowTests.kt
- node/src/test/kotlin/net/corda/node/modes/draining/ScheduledFlowsDrainingModeTest.kt
- node/src/test/kotlin/net/corda/node/services/events/ScheduledFlowTests.kt
- node/src/test/kotlin/net/corda/node/services/statemachine/FlowFrameworkTests.kt
- node/src/test/kotlin/net/corda/node/services/transactions/MaxTransactionSizeTests.kt
- node/src/test/kotlin/net/corda/node/services/vault/VaultSoftLockManagerTest.kt
- samples/network-visualiser/src/main/kotlin/net/corda/netmap/simulation/Simulation.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/InMemoryMessagingNetwork.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/MockNetwork.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/InternalMockNetwork.kt
- testing/node-driver/src/test/java/net/corda/testing/node/MockNodeFactoryInJavaTest.java
- testing/node-driver/src/test/kotlin/net/corda/testing/node/internal/InternalMockNetworkTests.kt
Forward-port from the 3.0 release branch, where this went in first.
> Minor: reduce the size of the MockNetwork API a bit, add some better documentation

- .idea/compiler.xml
- client/rpc/src/integration-test/kotlin/net/corda/client/rpc/RPCStabilityTests.kt
- client/rpc/src/main/kotlin/net/corda/client/rpc/internal/RPCClient.kt
- client/rpc/src/main/kotlin/net/corda/client/rpc/internal/RPCClientProxyHandler.kt
- client/rpc/src/test/kotlin/net/corda/client/rpc/RPCPerformanceTests.kt
- node-api/src/main/kotlin/net/corda/nodeapi/RPCApi.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/DeduplicationChecker.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/CordaPersistence.kt
- node/src/main/kotlin/net/corda/node/services/messaging/RPCServer.kt
Hopefully this should fix https://github.com/corda/corda/issues/2300
I found one way of reproducing the dupes, which is kicking of the client at inopportune times, this is what I used for the test.
The dedupe cache is based on time which may result in extended memory usage under heavy load in particular in the server (and hence the node). Just something to keep in mind during perf testing
> Add RPC deduplication to client and server

- .idea/compiler.xml
- client/rpc/build.gradle
Also for "client/rpc" explicitly specify "jvmTarget" (similar to what "experimental/behave" does) to avoid ambiguity.
Without this change the following compilation error been observed in IntelliJ:
```
Z:\corda\experimental\behave\src\main\kotlin\net\corda\behave\node\Node.kt
Error:(163, 44) Kotlin: Cannot inline bytecode built with JVM target 1.8 into bytecode that is being built with JVM target 1.6. Please specify proper '-jvm-target' option
```
> Eliminate references to Java target "1.6"

- .ci/api-current.txt
- core/src/main/kotlin/net/corda/core/flows/FlowLogic.kt
- core/src/test/kotlin/net/corda/core/flows/FlowTestsUtils.kt
- docs/source/api-flows.rst
- docs/source/example-code/src/main/kotlin/net/corda/docs/FlowCookbook.kt
This also includes a rename of `receiveAll` to `receiveAllMap`, necessitated by https://github.com/puniverse/quasar/issues/294
> CORDA-1043

- confidential-identities/src/main/kotlin/net/corda/confidential/IdentitySyncFlow.kt
- core/src/main/kotlin/net/corda/core/flows/NotaryFlow.kt
- core/src/main/kotlin/net/corda/core/node/ServiceHub.kt
- core/src/main/kotlin/net/corda/core/node/services/TransactionStorage.kt
- core/src/main/kotlin/net/corda/core/transactions/NotaryChangeTransactions.kt
- finance/src/main/kotlin/net/corda/finance/flows/TwoPartyTradeFlow.kt
- node/src/integration-test/kotlin/net/corda/node/services/AttachmentLoadingTests.kt
- testing/test-utils/src/main/kotlin/net/corda/testing/dsl/TestDSL.kt
- verifier/src/integration-test/kotlin/net/corda/verifier/GeneratedLedger.kt
Avoid calling `loadState()` for many states from the same transaction to avoid deserializing the transaction more than once.
> CORDA-1096 Performance when loading multiple states from the vault

- core/src/main/kotlin/net/corda/core/transactions/WireTransaction.kt
- node/src/integration-test/kotlin/net/corda/node/modes/draining/P2PFlowsDrainingModeTest.kt
- node/src/main/kotlin/net/corda/node/services/messaging/P2PMessagingClient.kt
@ags313 when we refactored `P2PFlowsDrainingModeTest` to use an `ExecutorService` instead of a `ScheduledExecutorService` we made that test useless (it was going green regardless, for a race condition).
When we refactored the `P2PMessagingClient` to use server-side filters, the feature got broken without us realising.
> [CORDA-1098]: Fixed Artemis filters for flows draining mode.

- confidential-identities/src/main/kotlin/net/corda/confidential/IdentitySyncFlow.kt
- core/src/main/kotlin/net/corda/core/flows/NotaryFlow.kt
- core/src/main/kotlin/net/corda/core/node/ServiceHub.kt
- core/src/main/kotlin/net/corda/core/node/services/TransactionStorage.kt
- core/src/main/kotlin/net/corda/core/transactions/NotaryChangeTransactions.kt
- finance/src/main/kotlin/net/corda/finance/flows/TwoPartyTradeFlow.kt
- node/src/integration-test/kotlin/net/corda/node/services/AttachmentLoadingTests.kt
- testing/test-utils/src/main/kotlin/net/corda/testing/dsl/TestDSL.kt
- verifier/src/integration-test/kotlin/net/corda/verifier/GeneratedLedger.kt
Merge from per-release-v3
* Provide efficient `loadStates()` implementation
* Replace loops using `loadState` with calls to `loadStates`
> CORDA-1096 - Performance when loading multiple states from the vault

- docs/source/generating-a-node.rst
Added description for `configFile` option in `deployNodes` Cordform Gradle task.
The option is only used when generating a node configuration and it's not present in node.conf (so it was not added to https://docs.corda.net/head/corda-configuration-file.html ).
https://github.com/corda/corda/pull/2615
> [CORDA-2615]: Added description for configFile option in deployNodes Cordform Gradle task.

- node-api/src/main/kotlin/net/corda/nodeapi/internal/bridging/AMQPBridgeManager.kt
- node/src/integration-test/kotlin/net/corda/node/amqp/AMQPBridgeTest.kt
Remove needless pinch point in the AMQP bridge where calling `session.commit()` could limit message throughput.
Auto commit sends and acks, and only call commit explicitly before a rollback to ensure a consistent state of the session in this case.
> CORDA-1122 Switch AMQP bridge to use auto-commit sends and acks

- samples/irs-demo/web/build.gradle
Content of ```bower_components``` folder is being downloaded by ```clientInstall``` step, directly into the source tree for easier development. This however seems to cause a problem with builds on fresh repos.
> [CORDA-1112] Explicit dependency on JS dep dir seems to eliminate race condition bug

- core/src/main/kotlin/net/corda/core/internal/ProgressTracker.kt
- core/src/main/kotlin/net/corda/core/utilities/ProgressTracker.kt
- docs/source/tutorial-cordapp.rst
- node/src/main/kotlin/net/corda/node/internal/CordaRPCOpsImpl.kt
We can't filter out the structural steps by class, because `FlowLogic.track` is part of the public API and returns strings only.
> 1076 - Filters out structural steps when tracking a flow via RPC.

- core/src/main/kotlin/net/corda/core/contracts/TransactionVerificationException.kt
- core/src/main/kotlin/net/corda/core/transactions/LedgerTransaction.kt
- core/src/test/kotlin/net/corda/core/contracts/TransactionVerificationExceptionSerialisationTests.kt
Fix the serialisability of TransactionVerificationException and subtypes.
Add KDocs for the exceptions in this file, and deprecate exceptions that aren't actually used.
> Fix the serialisability of TransactionVerificationException and subtypes.

- node-api/src/main/kotlin/net/corda/nodeapi/internal/bridging/AMQPBridgeManager.kt
- node/src/integration-test/kotlin/net/corda/node/amqp/AMQPBridgeTest.kt
This fixes the flaky bridge rollback test and also an associated deadlock that was happening in the BridgeManager during the test.
> Fix flaky bridge test

- buildSrc/build.gradle
There is no longer anything to build in the top-level project, so stop creating an empty jar.
> Disable empty jar in top-level buildSrc project.

- .ci/api-current.txt
- constants.properties
Upgrade to API Scanner 4.0.6 so that field annotations are also sorted. In practice, this change just deletes `@JvmField` from the API file.
> [CORDA-1167] Sort field annotations in public API and remove unnecessary @JvmField.

- node-api/src/main/kotlin/net/corda/nodeapi/internal/ArtemisMessagingComponent.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/bridging/AMQPBridgeManager.kt
- node/src/integration-test/kotlin/net/corda/node/amqp/AMQPBridgeTest.kt
- node/src/main/kotlin/net/corda/node/services/messaging/Messaging.kt
- node/src/main/kotlin/net/corda/node/services/messaging/P2PMessagingClient.kt
- node/src/main/kotlin/net/corda/node/services/statemachine/StateMachineManagerImpl.kt
Currently, we have defined in several places headers that we use in Artemis messages and we blindly copy all headers over the bridges. During review of my out of process bridge work on ENT it was pointed out that we should whitelist control these. Therefore this pushes the constants into nodeapi internal and only copies the defined headers across the AMQP bridges.
> CORDA-1170: Define and whitelist the Artemis/AMQP application headers that are accepted by Corda

- node-api/src/main/kotlin/net/corda/core/serialization/ConstructorForDeserialization.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializationHelper.kt
- node-api/src/test/java/net/corda/nodeapi/internal/serialization/amqp/JavaSerializationOutputTests.java
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/EvolvabilityTests.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/PrivatePropertyTests.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializationPropertyOrdering.kt
Since it's a user facing object it shouldn't exist in an internal
package. Move to core to exist with the other serialization annotations
> CORDA-1186 - Move ConstructorForDeserialization out of internal

- .ci/api-current.txt
This PR overwrites the api-current.txt on the master branch with the api-current.txt on the v3 release branch.
There are several compatibility breaks between the two for work that has happened on master that is not part of v3, which I have marked in the comments with reference to their original pull requests, and I've done each change as a seperate commit.
It may make more sense to review the commits individually rather than look at the overall diff.
> [CORDA-991] - Update committed api from v3 release branch

- testing/test-common/src/main/resources/log4j2-test.xml
Loggers in tests no longer reference a non-existent appender.
> CORDA-1155 Removed a reference to an appender not present in tests

- tools/shell/src/test/kotlin/net/corda/tools/shell/StandaloneShellArgsParserTest.kt
Fix test which uses Paths.get() and doesn't match on Windows.
> Corda-792 - fix test on Windows

- core/src/main/kotlin/net/corda/core/crypto/CryptoUtils.kt
- core/src/main/kotlin/net/corda/core/crypto/SecureHash.kt
`secureRandomBytes` should call `getNextBytes()`. It affects `SecureHash.randomSHA256()` as well.
> CORDA-1092 secureRandomBytes should call getNextBytes, not generateSeed

- node-api/src/main/kotlin/net/corda/nodeapi/internal/ArtemisMessagingComponent.kt
The bridgedCertificateSubject  header tag constant appears to have been mistakenly duplicated during my work to define a whitelist of packet headers. This deletes the unused duplicate.
> Remove a mistakenly duplicated constant defined on ArtemisMessagingComponent

- .ci/api-current.txt
- core/src/main/kotlin/net/corda/core/flows/NotarisationRequest.kt
- core/src/main/kotlin/net/corda/core/flows/NotaryFlow.kt
- core/src/main/kotlin/net/corda/core/internal/NotaryUtils.kt
- core/src/main/kotlin/net/corda/core/node/services/NotaryService.kt
- core/src/main/kotlin/net/corda/core/node/services/UniquenessProvider.kt
- docs/source/tutorial-custom-notary.rst
- node/src/integration-test/kotlin/net/corda/node/services/BFTNotaryServiceTests.kt
- node/src/main/kotlin/net/corda/node/services/transactions/BFTNonValidatingNotaryService.kt
- node/src/main/kotlin/net/corda/node/services/transactions/BFTSMaRt.kt
- node/src/main/kotlin/net/corda/node/services/transactions/PersistentUniquenessProvider.kt
- node/src/main/kotlin/net/corda/node/services/transactions/RaftUniquenessProvider.kt
- node/src/main/kotlin/net/corda/node/services/transactions/ValidatingNotaryFlow.kt
- node/src/test/kotlin/net/corda/node/services/transactions/NotaryServiceTests.kt
- node/src/test/kotlin/net/corda/node/services/transactions/PersistentUniquenessProviderTests.kt
- node/src/test/kotlin/net/corda/node/services/transactions/ValidatingNotaryServiceTests.kt
- samples/notary-demo/src/main/kotlin/net/corda/notarydemo/MyCustomNotaryService.kt
When a double-spend occurs, do not send the consuming transaction id and requesting party back to the client - this might lead to privacy leak. Only the transaction id hash is now returned.
> CORDA-1171: Fix potential privacy leak in notary double spend exceptions

- tools/explorer/src/main/kotlin/net/corda/explorer/views/cordapps/cash/CashViewer.kt
Current logic in `CashWidget` is not handling well updates done in close succession, i.e. less than 1 second.
And such frequent updates do indeed happen, e.g. from: `net.corda.client.jfx.model.ContractStateModel#cashStates`
where `list` is modified twice.
Also use `.toDecimal()` instead of `.quantity`to have amount represented in pounds rather than in pennies.
> CORDA-1197: Take into account last amount submitted when adding data points.

- node/src/main/kotlin/net/corda/node/ArgsParser.kt
During --initial-registration, the exceptions raised if you are missing --network-root-truststore-password or compatibilityZoneURL are too vague.
> Improve exception detail during --initial-registration

- node-api/src/main/kotlin/net/corda/nodeapi/internal/config/ConfigUtilities.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/config/ConfigParsingTest.kt
Porting over the change from https://github.com/corda/enterprise/pull/547/.
> Unwrapping InvocationTargetException during config parsing

- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/DefaultWhitelist.kt
Adding CRLReason to the default whitelist. This class is needed for the certificate revocation list support.
> Whitelisting CRLReason class

- tools/shell/src/integration-test/kotlin/net/corda/tools/shell/InteractiveShellIntegrationTest.kt
Ignore 2 flaky tests introduced for [CORDA-792] - Re-implement shell to be a standalone process using RPC client, investigate and test them on a branch.
>  Ignore 2 flaky SSH via StandaloneShell tests temporarily.

- .ci/api-current.txt
- constants.properties
- Ensure API Scanner also applies `@DoNotImplement` annotation to all child classes. Previously, it would only apply it to child classes in the same module as `@DoNotImplement`, i.e. `core`.
- Allow publishing Javadoc artifacts to be optional.
> Upgrade to corda-gradle-plugins 4.0.8

- node/src/main/kotlin/net/corda/node/utilities/JVMAgentRegistry.kt
Old code failed with:
```
11:34:01.536 [main] ERROR net.corda.node.internal.Node - Exception during node startup
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Program%20Files/JetBrains/IntelliJ%20IDEA%20Community%20Edition%202017.3.1/lib/idea_rt.jar
at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182) ~[?:1.8.0_144]
at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153) ~[?:1.8.0_144]
at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77) ~[?:1.8.0_144]
at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94) ~[?:1.8.0_144]
at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255) ~[?:1.8.0_144]
at java.nio.file.Paths.get(Paths.java:84) ~[?:1.8.0_144]
at net.corda.node.utilities.JVMAgentRegistry.resolveAgentJar(JVMAgentRegi …
```
> CORDA-1042: Change the way how Jolokia library located on the classpath so that it work on Windows

- client/jfx/src/main/kotlin/net/corda/client/jfx/model/NodeMonitorModel.kt
- client/jfx/src/main/kotlin/net/corda/client/jfx/model/TransactionDataModel.kt
- tools/explorer/src/main/kotlin/net/corda/explorer/views/Network.kt
- tools/explorer/src/main/kotlin/net/corda/explorer/views/TransactionViewer.kt
NotaryChange and ContractUpgrade transactions don't contain the output states - they're recalculated on demand from the inputs. I changed the explorer logic to resolve transaction inputs and outputs from vault updates rather than from transactions directly.
> CORDA-1142: Fix explorer to support all transaction types

- core/src/main/kotlin/net/corda/core/crypto/SecureHash.kt
The `SecureHash.zeroHash` and `SecureHash.allOnesHash` properties must currently be accessed from Java as:
```java
SecureHash.Companion.getZeroHash()
```
and
```java
SecureHash.Companion.getAllOnesHash()
```
Make these more "Java friendly" by using `@JvmField`, and preserve API compatibility by adding explicit getter functions.
> Expose two static fields on SecureHash for Java.

- core/src/main/kotlin/net/corda/core/transactions/LedgerTransaction.kt
Remove `@JvmStatic` to stop generating an extra function we don't need.
> Remove superfluous @JvmStatic annotation.

- client/rpc/src/integration-test/kotlin/net/corda/client/rpc/RPCStabilityTests.kt
Also eliminate warnings and other minor changes.
This PR is unlikely to fix the flaky test, but hopefully will provide more information as for why the test `RPCStabilityTests` failing intermittently.
> Improve error reporting in case of failure of flaky tests

- client/rpc/src/main/kotlin/net/corda/client/rpc/internal/RPCClientProxyHandler.kt
Prior to this change it was intermittently failing with:
```
net.corda.client.rpc.RPCException: RPC server is not available.
at net.corda.client.rpc.internal.RPCClientProxyHandler.invoke(RPCClientProxyHandler.kt:222)
at com.sun.proxy.$Proxy79.ping(Unknown Source)
at net.corda.client.rpc.RPCStabilityTests$client reconnects to rebooted server$1$pingFuture$1.invoke(RPCStabilityTests.kt:251)
at net.corda.client.rpc.RPCStabilityTests$client reconnects to rebooted server$1$pingFuture$1.invoke(RPCStabilityTests.kt:36)
at net.corda.core.internal.concurrent.ValueOrException$DefaultImpls.capture(CordaFutureImpl.kt:107)
at net.corda.core.internal.concurrent.OpenFuture$DefaultImpls.capture(CordaFutureImpl.kt:65535)
at net.corda.core.internal.concurrent.CordaFutureImpl.capture(CordaFutureImpl.kt:119) …
```
> Trying to improve stability of `RPCStabilityTests.client reconnects to rebooted server`

- node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/CordaPersistence.kt
- node/src/main/java/CordaCaplet.java
- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/main/kotlin/net/corda/node/internal/Node.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/MockServices.kt
As mentioned in: https://r3-cev.atlassian.net/browse/CORDA-1232,  although classloader changes looked fine they break in some circumstances and the fix is to upgrade RPC serialization to AMQP. To unlock the next release i am temporarily re-enabling loading of cordApps via Capsule.
> CordApps back in node and webserver classpath [CORDA-1232]

- .ci/api-current.txt
- constants.properties
Upgrading to corda-gradle-plugins 4.0.9 removes `@JvmStatic` from API output.
> CORDA-1224: Remove @JvmStatic annotations.

- node/src/main/kotlin/net/corda/node/services/transactions/PersistentUniquenessProvider.kt
Don't assign a value as it's auto generated.
Remove redundant default value for GeneratedValue strategy.
> ENT-1634 Fix value generation for PK column of node_notary_request_log table

- node-api/src/main/kotlin/net/corda/nodeapi/internal/network/NetworkMap.kt
- node/src/integration-test/kotlin/net/corda/node/services/network/NetworkMapTest.kt
- node/src/main/kotlin/net/corda/node/internal/NetworkParametersReader.kt
- node/src/main/kotlin/net/corda/node/services/network/NetworkMapClient.kt
- node/src/main/kotlin/net/corda/node/services/network/NetworkMapUpdater.kt
- node/src/test/kotlin/net/corda/node/services/network/NetworkMapUpdaterTest.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/network/NetworkMapServer.kt
This is a backport of the relevant changes from https://github.com/corda/enterprise/pull/565 and https://github.com/corda/enterprise/pull/477.
> Integration test for network parameter updates and improved logging

- finance/src/main/kotlin/net/corda/finance/contracts/asset/cash/selection/CashSelectionPostgreSQLImpl.kt
CORDA-1262: https://r3-cev.atlassian.net/browse/CORDA-1262
> [CORDA-1262]: Fixed incorrect reference to column "issuer_key" in cash selection SQL for Postgres

- docs/source/changelog.rst
- node-api/build.gradle
The problem manifests now that the classpath scanner is used by the
serialization framework in factory initialization to locate pluggable
serializers. The actual thrown error is
java.lang.RuntimeException: Unknown constant pool tag
Given this is a known issue and a fixed bug it makes sense to move the
version forward. Unfortunately, at this time we cannot move beyond
2.12.3 as 2.12.4 and later versions (up to the latest 2.18.1) exhibit
some other error that needs investigating. Thus, move to the latest
version that is stable for our current set of use cases.
More information on the nature of the problem exhibited by moving beyond
2.12.3 can be found on the linked Jira (ENT-1665) as well as details on
reproducing the issue moving forward to 2.12.3 fixes.
> ENT-1665 - Update fast-classpath-scanner version to 2.12.3 (was 2.0.21)

- client/rpc/src/integration-test/kotlin/net/corda/client/rpc/RPCStabilityTests.kt
- client/rpc/src/main/kotlin/net/corda/client/rpc/CordaRPCClient.kt
With the recent RPCClient changes, the user is expected to provide error handlers when subscribing to observables. This was not being reflected in the kdocs. Also update a unit test with usage example.
> ENT-1670: update kdocs and unit test for better user experience

- node/src/main/kotlin/net/corda/node/services/events/NodeSchedulerService.kt
- node/src/test/kotlin/net/corda/node/services/events/NodeSchedulerServiceTest.kt
Adds some extra tests to the NodeSchedulerService that test the database persistence. Related to this github issue: https://github.com/corda/corda/issues/2454.
There was no need to fix the NodeSchedulerService, as the underlying issue has been fixed by this commit: https://github.com/corda/corda/commit/9d66214f4a97710109df3baecb1244013c7d41ea however it is not immediately clear why this commit fixed it.
The `scheduledStates` were originally declared as a `PersistentMap<StateRef, ScheduledStateRef>` on the `NodeSchedulerService`. The above mentioned commit changes it to be initialised by the constructor and explicitly states the parameter type is the generic base class of type `MutableMap<StateRef, ScheduledStateRef>`.
If you assign a value to the `PersistentMap` via index (i.e. …
> CORDA-1002 Add node scheduler persistence tests

- docs/source/changelog.rst
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/DeserializationInput.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/SerializerFactory.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/carpenter/AMQPSchemaExtensions.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/carpenter/ClassCarpenter.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/carpenter/Exceptions.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/carpenter/MetaCarpenter.kt
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/carpenter/SchemaFields.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/EnumEvolveTests.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/carpenter/CarpenterExceptionTests.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/kryo/KryoTests.kt
Also move a Kryo specific test into the correct sub module
> CORDA-1236 - Don't let Carpenter exceptions escape the serializer

- docs/source/changelog.rst
- node-api/build.gradle
Backport of https://github.com/corda/corda/pull/2877
> Ent-1665 - Upgrade fast-classpath-scanner from 2.0.21 to 2.12.3

- docs/source/serialization.rst
- node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/amqp/RoundTripTests.kt
Forward port of https://github.com/corda/corda/pull/2883 onto master (because I did the original against the wrong branch)
> DOCS: Serialization roundtrip removes mutability explanation

- node/src/main/kotlin/net/corda/node/internal/NetworkParametersReader.kt
Don't crash on node startup when network map is not available
> ENT-1668: Don't crash on node startup when network map is not available

- docs/source/changelog.rst
- docs/source/corda-configuration-file.rst
- docs/source/example-code/src/main/resources/example-node.conf
- node/src/main/kotlin/net/corda/node/services/config/ConfigUtilities.kt
- node/src/main/resources/reference.conf
Removing double quotes around keys from reference conf, added an error to ConfigParser if such quoted keys are detected.
> CORDA-1277 Remove double quotes from keys in reference.conf

- core/src/main/kotlin/net/corda/core/transactions/LedgerTransaction.kt
To reduce the possibility of any side effect from aborting half-way through, we instantiate all of the contract classes before calling any of their verify methods.
We still load the contract classes when we create the `LedgerTransaction` object because the `ClassLoader` class may not be available to the JVM during verification.
> ENT-1463: Instantiate all contract classes before verifying any of them.

- node-api/src/main/kotlin/net/corda/nodeapi/internal/SignedNodeInfo.kt
This fixes the security vulnerability described in [ENT-1732](https://r3-cev.atlassian.net/browse/ENT-1732).
> ENT-1732: Fixing SignedNodeInfo security issue

- node/src/integration-test/kotlin/net/corda/node/utilities/registration/NodeRegistrationTest.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/DriverDSLImpl.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/network/NetworkMapServer.kt
There was a problem identified with `NetworkMapServer` where response cache interval has not been correctly set for it.
This resulted delay of 1 minute in all the nodes discovering each other on the NetworkMap.
After the changes the test running time is down to 55 seconds from around 2 minutes previously.
> Speed-up `NodeRegistrationTest`

- node/src/integration-test/kotlin/net/corda/node/services/rpc/RpcExceptionHandlingTest.kt
Add explicit node names in RpcExceptionHandlingTest for multi nodes tests (align with enterprise repo).
> Update RpcExceptionHandlingTest tests introduced by CORDA-1264

- node/src/integration-test/kotlin/net/corda/node/modes/draining/FlowsDrainingModeContentionTest.kt
- node/src/integration-test/kotlin/net/corda/node/persistence/NodeStatePersistenceTests.kt
- node/src/integration-test/kotlin/net/corda/testMessage/MessageState.kt
- node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
- node/src/main/kotlin/net/corda/node/services/identity/PersistentIdentityService.kt
Packages re-jig was meant to reduce the size of the jars that are being produced by the
node driver. E.g. previously `MessageState` was in package `net.corda` which resulted in jar file
of around 2MB to be created multiple times. Same for `NodeStatePersistenceTests` which was in `net.corda.node`.
This change alone saves couple of minutes in build time.
Please compare this build without change:
https://ci-master.corda.r3cev.com/viewLog.html?currentGroup=test&scope=%23teamcity%23net.corda.node%23teamcity%23NodeStatePersistenceTests&pager.currentPage=1&order=DURATION_DESC&recordsPerPage=20&filterText=&status=&buildTypeId=Corda_CordaBuild&buildId=75021&tab=testsInfo
with:
https://ci-master.corda.r3cev.com/viewLog.html?currentGroup=test&scope=%23teamcity%23net.corda.node.persistence%23teamcity% …
> Improve performance of NodeStatePersistenceTests

- node-api/src/test/kotlin/net/corda/nodeapi/internal/SignedNodeInfoTest.kt
This adds the test for the SignedNodeInfo verification. In particular the test focuses on verifying recently added composite check.
> CORDA-1300 Adding a unit test for SignedNodeInfo verification

- node-api/src/main/kotlin/net/corda/nodeapi/internal/crypto/X509Utilities.kt
- node-api/src/test/kotlin/net/corda/nodeapi/internal/crypto/X509UtilitiesTest.kt
- node/src/main/kotlin/net/corda/node/services/keys/KMSUtils.kt
This PR adds the CRL support for the generated certificates in the X509Utilities class.
Here is the certificate snippet:
[
[
Version: V3
Subject: CN=Server Cert, O=R3 Ltd, L=London, C=GB
Signature Algorithm: SHA256withECDSA, params unparsed, OID = 1.2.840.10045.4.3.2
Key:  Sun EC public key, 256 bits
public x coord: 4480091252781703195661860073149098197905970789947759358848305764737974351635
public y coord: 91515947767866989687528832609777756360177875523811291720844490776224837881690
parameters: secp256r1 [NIST P-256, X9.62 prime256v1] (1.2.840.10045.3.1.7)
Validity: [From: Thu Apr 05 01:00:00 BST 2018,
To: Sun Apr 02 01:00:00 BST 2028]
Issuer: CN=Test CA Cert, O=R3 Ltd, L=London, C=GB
SerialNumber: [    74820859 611c7975]
Certificate Extensions: 7
[1]: ObjectId: 1.3.6.1.4.1.50530.1.1 …
> Adding CRL support in the generated certificates.

- samples/irs-demo/src/integration-test/kotlin/net/corda/test/spring/SpringDriver.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/DriverDSLImpl.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/ProcessUtilities.kt
StdErr is always written to working directory if such path specified.
> Remove `errorLogPath` parameter which is not used anyway.

- node/src/integration-test/kotlin/net/corda/node/utilities/registration/NodeRegistrationTest.kt
Since we are running web-server and different handling methods will be called from
different threads, it is more appropriate to use concurrent data structures
for exchanging information between threads.
Prior to this change I observed the following exception which is likely to be due `certPaths` not synchronized between threads:
```
Caused by: kotlin.KotlinNullPointerException
at net.corda.node.utilities.registration.RegistrationHandler$reply$1.invoke(NodeRegistrationTest.kt:151) ~[integrationTest/:?]
at net.corda.node.utilities.registration.RegistrationHandler$reply$1.invoke(NodeRegistrationTest.kt:122) ~[integrationTest/:?]
at net.corda.core.internal.InternalUtils.logElapsedTime(InternalUtils.kt:221) ~[corda-core-corda-4.0-snapshot.jar:?]
at …
```
> Try to improve stability of `NodeRegistrationTest`

- node/src/integration-test/kotlin/net/corda/node/amqp/AMQPBridgeTest.kt
- node/src/integration-test/kotlin/net/corda/node/amqp/ProtonWrapperTests.kt
- node/src/main/kotlin/net/corda/node/internal/Node.kt
- node/src/main/kotlin/net/corda/node/services/config/NodeConfiguration.kt
- node/src/main/kotlin/net/corda/node/services/messaging/ArtemisMessagingServer.kt
- node/src/main/resources/reference.conf
- node/src/test/kotlin/net/corda/node/services/config/NodeConfigurationImplTest.kt
- node/src/test/kotlin/net/corda/node/services/messaging/ArtemisMessagingTest.kt
This adds a messagingServerExternal flag to the node configuration, which controls whether to start an in-process p2p artemis. By default the messagingServerExternal setting follows the existing p2p artemis logic. Thus if messagingServerAddress is null (default) then messagingServerExternal is false and the node starts an internal artemis server bound to the p2pAddress port on all interface cards. If messagingServerAddress is specified then by default messagingServerExternal is set to true and the node will connect to an externally provided broker on the messagingServerAddress and advertise the public p2pAddress to the network map. However, now the messagingServerExternal can be forced to false in config and the node will start an internal p2p broker bound to the messagingServerAddress. …
> Add support for different internal p2p artemis bind address/port

- docs/source/hello-world-state.rst
This change is removing a duplicated description of Kotlin, there is a same description in the "Note" section right below it, so remove this part and keep "Note" part.
- [NA] Have you run the unit, integration and smoke tests as described here? https://docs.corda.net/head/testing.html
- [NA] If you added/changed public APIs, did you write/update the JavaDocs?
- [NA] If the changes are of interest to application developers, have you added them to the changelog, and potentially release notes?
- [Yes] If you are contributing for the first time, please read the agreement in CONTRIBUTING.md now and add to this Pull Request that you agree to it.
> [CORDA-1201] Remove a duplication of the kotlin introduction part, which is the same as "Note" section right below it

- finance/src/main/kotlin/net/corda/finance/contracts/asset/cash/selection/CashSelectionPostgreSQLImpl.kt
- node/src/test/kotlin/net/corda/node/services/vault/VaultQueryTests.kt
Change conversion to toStringShort() instead of toBase58String() - as done for H2 Cash Selection.
Fix withIssuerRefs case - iterate via list of IssuerRefs and setBytes instead of setArray of BYTEA.
Add test for Cash Selection with issuerRef.
> Fix cash selection with PostgreSQL

- node/src/main/kotlin/net/corda/node/internal/Node.kt
In productionMode ssh could login to a node using "shell/shell" which is supposed to be available only in dev mode (to enable embedded shell).
> CORDA-1326 - Add default shell user only when local shell is started.

- docs/source/changelog.rst
- docs/source/release-notes.rst
- docs/source/upgrade-notes.rst
Backport relase and upgrade notes for 3.1 into master
Fix issue where upgrade notes for 3.0 didn't get completely back-merged
> Kat/release/merge 3.1 releasenotes

- node-api/src/main/kotlin/net/corda/nodeapi/ArtemisTcpTransport.kt
this can deadlock when the server gets busy and switches back and forth between
direct and async delivery if it can't keep up.
> CORDA-1336: Turn off direct delivery in Artemis via config

- .ci/api-current.txt
- build.gradle
We are currently compiling against the old Kotlin 1.1 language/API definitions, despite using Kotlin 1.2.20 artifacts. Upgrade to use Kotlin 1.2 completely.
> CORDA-1265: Upgrade to Kotlin language/API 1.2

- core/src/test/java/net/corda/core/flows/FlowsInJavaTest.java
- core/src/test/kotlin/net/corda/core/flows/CollectSignaturesFlowTests.kt
- core/src/test/kotlin/net/corda/core/internal/ResolveTransactionsFlowTest.kt
- docs/source/api-testing.rst
- docs/source/example-code/src/main/kotlin/net/corda/docs/tutorial/mocknetwork/TutorialMockNetwork.kt
- docs/source/flow-testing.rst
- samples/trader-demo/src/integration-test/kotlin/net/corda/traderdemo/TraderDemoTest.kt
The use of registerInitiatedFlow is no longer needed in tests - MockNetwork scans the supplied packages for flows and registers them automatically, so I've removed that part from the tutorial and example tests to reduce confusion.
> Remove superfluous registerInitiatedFlow calls from tutorial and example tests

- node-api/src/main/kotlin/net/corda/nodeapi/internal/ClassloaderUtils.kt
- node/src/main/kotlin/net/corda/node/internal/cordapp/CordappLoader.kt
`ClassloaderUtils.scanJarForContracts()` performs scan for instances of `Contract` including our `core` module. Every such scan takes approximately 1 second. When `core` excluded scan takes around 50ms.
> CORDA-1335: Scan attachment Jar only to speed-up the process.

- docs/source/changelog.rst
- docs/source/cordapp-custom-serializers.rst
- node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/AMQPSerializationScheme.kt
- samples/simm-valuation-demo/src/integration-test/kotlin/net/corda/vega/SimmValuationTest.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/DriverDSLImpl.kt
This should help with execution performance of the integration tests and reduce the memory footprint used by `FastClasspathScanner`
I people like this change and will be thinking of approving it then I will update Corda documentation to explain the purpose of the newly introduced property.
> CORDA-1355: Introduce a dedicated property which controls what is going to be in scope for classpath scanning

- client/rpc/src/integration-test/kotlin/net/corda/client/rpc/RPCStabilityTests.kt
- client/rpc/src/main/kotlin/net/corda/client/rpc/CordaRPCClient.kt
- client/rpc/src/main/kotlin/net/corda/client/rpc/internal/RPCClient.kt
- client/rpc/src/main/kotlin/net/corda/client/rpc/internal/RPCClientProxyHandler.kt
- node-api/src/main/kotlin/net/corda/nodeapi/ArtemisTcpTransport.kt
- testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/RPCDriver.kt
Cherry picked. RPC level failover with round-robin through list of available nodes. 
* ENT-1775: reworked client to handle failover in HA mode instead of relying on artemis
* ENT-1775: address PR comments
> ENT-1775: reworked client to handle failover in HA mode instead of Artemis

- client/jfx/build.gradle
- core/build.gradle
- experimental/behave/build.gradle
- experimental/kryo-hook/build.gradle
- experimental/quasar-hook/build.gradle
- node-api/build.gradle
- node/build.gradle
- samples/attachment-demo/build.gradle
- samples/bank-of-corda-demo/build.gradle
- samples/notary-demo/build.gradle
- samples/simm-valuation-demo/build.gradle
- samples/trader-demo/build.gradle
- testing/test-utils/build.gradle
- tools/explorer/build.gradle
Replace the deprecated `kotlin-stdlib-jre8` artifact with `kotlin-stdlib-jdk8`.
> CORDA-1263: Replace deprecated Kotlin artifacts.

- .idea/compiler.xml
- experimental/behave/build.gradle
- experimental/behave/prepare.sh
- experimental/behave/src/main/kotlin/net/corda/behave/network/Network.kt
- experimental/behave/src/main/kotlin/net/corda/behave/node/Distribution.kt
- experimental/behave/src/main/kotlin/net/corda/behave/node/Node.kt
- experimental/behave/src/main/kotlin/net/corda/behave/node/configuration/Configuration.kt
- experimental/behave/src/main/kotlin/net/corda/behave/process/JarCommand.kt
- experimental/behave/src/scenario/kotlin/net/corda/behave/scenarios/helpers/Cash.kt
- experimental/behave/src/scenario/kotlin/net/corda/behave/scenarios/helpers/Startup.kt
- experimental/behave/src/scenario/kotlin/net/corda/behave/scenarios/steps/VaultSteps.kt
- experimental/behave/src/scenario/resources/features/cash/currencies.feature
- experimental/behave/src/scenario/resources/features/database/connection.feature
- experimental/behave/src/scenario/resources/features/startup/logging.feature
- experimental/behave/src/scenario/resources/scripts/run-behave-features.sh
- build fat behave-jar so can run scenarios from shell scripts (from TC)
- additional run script to execute basic scenarios (for TC)
- default staging path shortened to "corda" (removed deps)
- toned down logging (info -> debug)
- fixed all compiler warnings
- fixed couple of bugs in startup checking steps
- base scenarios use variables declared using Examples parameterization
> Corda Behave: compendium of minor changes and improvements

- node/src/main/kotlin/net/corda/node/utilities/PersistentMap.kt
- node/src/test/kotlin/net/corda/node/utilities/PersistentMapTests.kt
The `PersistentMap` currently has support for a map that doesn't allow duplicates. If the map is updated with duplicates, it doesn't do anything and doesn't persist the changes. That functionality isn't used however and is confusing, so I've removed it.
I've also removed the set operator - this isn't called if the `PersistentMap `is cast to a `MutableMap`, in which case the `MutableMap`'s set operator is called which calls the put function. The set operator should should just call the put operator for consistency.
I've also added some unit tests to make sure that the functions work properly and which should flag an error if someone tries to re-implement the set operator differently in the future by testing that the assignment operators work the same for a `PersistentMap` or a `MutableMap`
> CORDA-1001 Remove unused bits of PersistentMap

- .ci/api-current.txt
- core/src/main/kotlin/net/corda/core/flows/NotaryFlow.kt
- core/src/main/kotlin/net/corda/core/internal/NotaryUtils.kt
- core/src/main/kotlin/net/corda/core/node/services/NotaryService.kt
- core/src/main/kotlin/net/corda/core/node/services/UniquenessProvider.kt
- node/build.gradle
- node/src/integration-test/kotlin/net/corda/node/services/BFTNotaryServiceTests.kt
- node/src/integration-test/kotlin/net/corda/node/services/BFTSMaRtTests.kt
- node/src/main/kotlin/net/corda/node/services/transactions/BFTNonValidatingNotaryService.kt
- node/src/main/kotlin/net/corda/node/services/transactions/BFTSMaRt.kt
- node/src/main/kotlin/net/corda/node/services/transactions/PersistentUniquenessProvider.kt
- node/src/main/kotlin/net/corda/node/services/transactions/RaftTransactionCommitLog.kt
- node/src/main/kotlin/net/corda/node/services/transactions/RaftUniquenessProvider.kt
- node/src/test/kotlin/net/corda/node/services/transactions/PersistentUniquenessProviderTests.kt
- node/src/test/kotlin/net/corda/node/services/transactions/RaftTransactionCommitLogTests.kt
- node/src/test/kotlin/net/corda/node/services/transactions/ValidatingNotaryServiceTests.kt
Currently the time window is checked before states are being passed to a uniqueness provider. If the time window is invalid, the transaction will be rejected even if it has already been notarised, which violates idempotency.
For this reason the time window verification was moved alongside state conflict checks – this required some interface changes.
- Added expired timewindow re-notarisation tests for all types of notaries.
- As a result, BFTNotaryService tests were taking around 3min to run, so I split the test up into `BFTSMaRtTests` and `BFTNotaryServiceTests`. The latter re-uses the same cluster for all tests, shaving down the total run-time to under a minute.
> ENT-1540: Make sure transactions with "expired" time windows get re-notarised correctly

- build.gradle
- node-api/build.gradle
- node/build.gradle
- testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/RPCDriver.kt
Upgrading o artemis 2.5.0 which caused a few issues with netty dependencies. Basically, in node-api, artemis-core-client and artemis-commons are used which, in 2.2.0, used to pull in netty-all. 2.5.0 doesn't pull in the netty dependencies used by the AMQP code. Therefore, moved the netty-all dependency from node to node-api.
> artemis upgrade to 2.5.0
